library/bignum.c, library/rsa.c
This pull request brings two changes:
- I have improved the time- and flow- constantness of some parts of the code handling big integers;
- I have removed statistical biases in the prime generation routines, and implemented a rejection method instead, which is the proper way to do. Such biases might have devastating consequences in terms of security for certain public-key cryptosystems. Note that I don't claim any attack here: I am not an expert in this field of cryptanalysis. However, look at the paper of Aranha et al. *GLV/GLS Decomposition, Power Analysis, and Attacks on ECDSA Signatures With Single-Bit Nonce Bias* presented at ASIACRYPT'14 as well as the references therein to be convinced that biases are bad in cryptography.
=> Added more constant-time code / removed biases in the prime number generation routines.

library/x509_crt.c
What do you think, is this a bug or not? I don't think it's dangerous, you'd need to have two CAs in the `trust_ca` list with the same subject name, but I think it counts as unintended behaviour that should be fixed.
Noticed during code review.
Commit comment: If the top certificate occurs twice in trust_ca (for example) it would not be good for the second instance to be checked with check_path_cnt reduced twice!
=> fix minor bug in path_cnt checks

library/platform.c
This causes a compile-time error: 
platform.c(157): error:  #147: declaration is incompatible with "void (*polarssl_exit)(int)" (declared at line 179 of "platform.h")
=> Fix compile bug: incompatible declaration of polarssl_exit in platform.c

yotta/data/example-authcrypt/README.md, yotta/data/example-benchmark/README.md, yotta/data/example-hashing/README.md, yotta/data/example-selftest/README.md, yotta/data/example-tls-client/README.md
This removes the yt ls steps from the example READMEs. It seems like an unnecessary step because yt build will install them any way. It currently doesn't provide the command needed to remedy missing dependencies (yt install), so if removing it entirely isn't the correct way to change the READMEs then info about yt install should be added.
=> Removing yt ls step in READMEs of examples

include/mbedtls/ssl.h, library/ssl_tls.c
Otherwise, it's impossible to pass in a pointer to `mbedtls_x509_crt_profile_next`!
=> fix const-ness of argument to mbedtls_ssl_conf_cert_profile

library/net.c
The return value of recvfrom is being downsized (with warnings) to an int.
=> FIX: compiler warning with recvfrom on 64-bit

ChangeLog, library/ssl_srv.c
There is only one length byte but for some reason we skipped two, resulting in
reading one byte past the end of the extension. Fortunately, even if that
extension is at the very end of the ClientHello, it can't be at the end of the
buffer since the ClientHello length is at most SSL_MAX_CONTENT_LEN and the
buffer has some more room after that for MAC and so on. So there is no
buffer overread.
Possible consequences are:
- nothing, if the next byte is 0x00, which is a comment first byte for other
extensions, which is why the bug remained unnoticed
- using a point format that was not offered by the peer if next byte is 0x01.
In that case the peer will reject our ServerKeyExchange message and the
handshake will fail.
- thinking that we don't have a common point format even if we do, which will …
=> Fix bug in server parsing point formats extension

ChangeLog, library/rsa.c, library/ssl_cli.c
Merge of mbedtls-1.3-restricted branch, including:
* iotssl-469 - RSA-CRT fix
* Fix for possible client-side NULL pointer dereference
=> Merge of mbedtls-1.3-restricted

configs/config-ccm-psk-tls1_2.h, configs/config-picocoin.h
This way all config examples work when used like described in the README
=> Make config check include for configs examples more consistent

programs/pkey/gen_key.c
Found using Lintian (https://lintian.debian.org/).
=> Fix minor spelling mistake in programs/pkey/gen_key.c

yotta/data/module.json
Recent changes in various repositories broke the build of the yotta
module again :( This change fixes the build. Build tested with
frdm-k64f-gcc. I didn't update the yotta version number because I
don't know what is your policy with regards to version changes.
=> Fix yotta dependencies

ChangeLog, include/mbedtls/ssl.h, include/mbedtls/x509_crt.h, library/x509_crt.c, tests/suites/test_suite_x509parse.data, tests/suites/test_suite_x509parse.function
- also adapt tests to use lesser requirement for compatibility with old
testing material
=> Fix missing check for RSA key length on EE certs

programs/x509/cert_req.c, programs/x509/cert_write.c
In cert_req and cert_write programs, "key_certificate_sign" is not an
allowed value for "key_usage" parameter. The correct value is
"key_cert_sign".
See https://github.com/ARMmbed/mbedtls/blob/development/programs/x509/cert_req.c#L208
and https://github.com/ARMmbed/mbedtls/blob/development/programs/x509/cert_write.c#L323.
=> Fix help message for cert_req/cert_write programs

programs/x509/cert_write.c
This commit fixes the `Destination buffer is too small` error returned
by `mbedtls_cert_write` command when the values of `subject_name` or
`issuer_name` parameters exceed 128 characters.
I have increased the size of these varaibles from 128 to 256 characters,
but I don't know if it's the best way to solve this issue...
Fixes #315.
=> cert_write : fix "Destination buffer is too small" error

ChangeLog, library/rsa.c
Fix in mbedtls_rsa_rsassa_pkcs1_v15_sign() in rsa.c. Github bug #372
=> Fix for memory leak in RSA-SSA signing

scripts/config.pl, scripts/footprint.sh
This fixes #449 - 'Script footprint.sh failing'.
This PR adds an option to the script `scripts/config.pl` of `--force` to allow configurations to be set and `#define`'d in the `config.h` file even if they are not present, and also adds to the script `scripts/footprint.sh` the additional configuration of `MBEDTLS_NO_PLATFORM_ENTROPY` which is now required for all baremetal builds.
=> Fix for #449 - Script footprint.sh failing

tests/CMakeLists.txt, tests/suites/helpers.function
During my testing of Curve448, I tried running the test suites on Windows, but found that they don't compile, and can't be built without a bit of tweaking.
The compile error with Visual Studio is due to strcasecmp being missing.  Secondly, on Windows Perl scripts aren't executable and have to be run using the Perl interpreter directly; thankfully CMake is able to find cygwin Perl straight away without problems.
=> Allow test suites to be run on Windows

library/bignum.c, library/pkcs12.c, library/rsa.c, library/ssl_cli.c, library/ssl_tls.c, library/x509_csr.c, programs/hash/generic_sum.c
Some fixes to shut up clang-analyze warnings.
While running it, I found two actual bugs, a double-free in ssl_tls.c and a memory leak in rsa.c, but thankfully it looks like both of those have been fixed since the release I was testing.
=> Clang analyze fixes

include/mbedtls/bn_mul.h, library/aesni.c
This PR fixes build errors and segfaults when building with the x32 ABI (x86-64 with 4-byte pointers). The test-suite now passes on x32 (and still passes on normal x86-64).
You can test x32 by installing a multilib gcc and passing `-mx32` when building. You'll probably have to enable `CONFIG_X86_X32` in your kernel as well if you want to run anything.
=> Support for x32

library/Makefile
Support for CMAC was added to the Cmake build system, but not to the Make build system.
=> Added cmac.o to libary/Makefile

tests/ssl-opt.sh
In order to reduce debugging time, allows you to only run interesting
tests (by number) from the commandline.
e.g. the command 'tests/ssl-opt.sh -n 246,258' will only run test 246
and 258 (as per the number in the log file names)
=> Update ssl-opt.sh capabilities to help with debugging

library/rsa.c
The indention is broken in the output of `selftest.c`:
```
PKCS#1 decryption : passed
PKCS#1 data sign  : passed
PKCS#1 sig. verify: passed
```
This pull request fixes the alignment.
=> fix indentation in output of selftest.c

tests/ssl-opt.sh
Provides graceful exit rather than fail silently if valgrind isn't installed.
=> Adds check for valgrind to ssl-opt.sh

library/error.c, programs/pkey/dh_client.c, programs/pkey/dh_genprime.c, programs/pkey/dh_server.c, programs/ssl/dtls_client.c, programs/ssl/dtls_server.c, programs/ssl/ssl_fork_server.c, scripts/data_files/error.fmt
Add missing mbedtls_time_t definitions to sample applications and the error.c generation script.
Fixes #490.
=> Add missing mbedtls_time_t definitions

include/mbedtls/ssl.h
This corrects numerous typos, spelling mistakes, tense mistakes, and re-wraps some >80 col lines.
=> ssl.h: tidy up the documentation comments

library/rsa.c
In `rsa.c`, there are several unchecked calls to `mbedtls_md_setup()`.  If the call fails, the MGF routine is passed an invalid `&md_ctx`.  
We found this bug while attempting to generate a RSA OAEP cryptogram on an embedded system with limited heap.  The existing code returns success but generates an invalid cryptogram.
Thanks to @sergbuslovsky for helping to find and diagnose this bug.
=> Fixed unchecked calls to mbedtls_md_setup in rsa.c

include/mbedtls/config.h, yotta/data/adjust-config.sh
This pull request changes back the use of `YOTTA_CFG_MBEDTLS_USER_CONFIG_FILE` to allow user or third party configurations, and provides a new, yotta specific way of specifying the target header `target_config.h`.
=> Fix issue with reuse of custom yotta configs for target_config.h

Makefile
Modify the main Makefile so that post_build target is not started in
parallel with tests and programs recipe.
=> Fix main Makefile to allow parallel builds

programs/aes/aescrypt2.c
Warning was being generated by call to `sscanf()`at line 170 by implicit cast of unsigned int to signed int.
=> Fix warning on implicit casting in aescrypt.c

scripts/footprint.sh
Ideally, Makefile targets should be called irrespectively of their
execution order. In this sense, `clean` and `lib` should not be
passed both as target command line arguments in the same make
invocation. This is because out-of-order execution could cause a
failure. This change ensures that `clean` and `lib` are called in
separate executions of make in scripts/footprint.sh.
=> Fix footprint.sh call to makefile

include/mbedtls/entropy.h, library/entropy.c
Ensure that the entropy self test always fails whenever
MBEDTLS_TEST_NULL_ENTROPY is defined. This is because the option is
meant to be for testing and development purposes rather than production
quality software. Also, this patch enhances the documentation for
mbedtls_entropy_source_self_test() and mbedtls_entropy_self_test().
Documentation improvements by @sbutcher-arm
=> Documentation and entropy self test changes

library/entropy.c, tests/scripts/all.sh, tests/suites/test_suite_entropy.data, tests/suites/test_suite_entropy.function
This pull request:
* fixes the test suite test for the entropy module self-test for MBEDTLS_TEST_NULL_ENTROPY builds. The test must always fail in such builds and the test suite should check as much
* removes redundant self-tests in tests/scripts/all.sh
* fixes compiler warnings for unused variables in MBEDTLS_TEST_NULL_ENTROPY builds
=> Fix for entropy self-test in MBEDTLS_TEST_NULL_ENTROPY builds

library/cmac.c
The bracketing in some expressions where an assignment was being made in an `if` statement in cmac.c had been accidentally broken and was causing compiler warnings with armcc.
=> Fix bracketing in cmac.c

ChangeLog, programs/x509/cert_req.c, programs/x509/cert_write.c
The sample applications programs/pkey/cert_req.c and programs/pkey/cert_write.c use the library functions mbedtls_pk_write_csr_pem() and mbedtls_pk_write_crt_pem() respectively which are dependent on the configuration option MBEDTLS_PEM_WRITE_C. If the option isn't defined the build breaks.
This change adds the compilation condition MBEDTLS_PEM_WRITE_C to these sample application.
This issue is a variant of #559 but on other sample applications.
=> Add extra compilation conditions to X.509 samples

ChangeLog, library/threading.c
Due to inconsistent freeing strategy in pkparse.c the sample mutex
implementation in threading.c could lead to undefined behaviour by
destroying the same mutex several times.
This fix prevents mutexes from being destroyed several times in the
sample threading implementation.
=> Add safety check to sample mutex implementation

library/sha256.c, library/sha512.c
Reduce the stack usage of the testing framework by dynamically
allocating the memory used for the test.
=> Use allocated memory for SHA self tests

ChangeLog, library/x509.c
This PR fixes mbedtls_x509_get_sig() so that it only updates the output parameter `sig` until after the checks by `mbedtls_asn1_get_bitstring_null()` succeed.
This fixes the issue [#622](https://github.com/ARMmbed/mbedtls/issues/622).
=> Fix sig->tag update in mbedtls_x509_get_sig()

ChangeLog, library/ssl_cli.c
This PR fixes a potential overread in `ssl_parse_hello_verify_request()` when parsing a SERVER_HELLO incoming message whose `cookie_len` does not match the actual size received. This issue was found by @guidovranken.
=> Fix overread when verifying SERVER_HELLO in DTLS

ChangeLog, library/x509.c, tests/suites/test_suite_x509parse.data, tests/suites/test_suite_x509parse.function
Add a check to mbedtls_x509_get_time() to ensure that the parsed date is valid.
This fix is related to https://github.com/ARMmbed/mbedtls/issues/604.
=> Add check for validity of date in x509_get_time()

include/mbedtls/config.h
This fixes many incorrect references to filenames in the comments in config.h.
=> Fix multiple erroneously named source files in comments

include/mbedtls/config.h
This fixes many incorrect references to filenames in the comments in config.h, as a backport to the mbedtls 2.1 branch.
=> Fix multiple erroneously named source files in comments - 2.1 backport

include/mbedtls/rsa.h, include/mbedtls/x509.h, library/cmac.c, library/net_sockets.c, library/pkparse.c, library/ssl_tls.c, library/x509.c, scripts/config.pl
The existing comment is unclear and has grammatical errors.
=> Clarify Comments and Fix Typos

CMakeLists.txt, library/cmac.c, library/platform.c, library/x509_crt.c, tests/CMakeLists.txt
This PR fixes various compiler warnings found with Microsoft Visual Studio 2015 (and earlier versions), and also fixes a problem where the switch for compiler warnings was being configured twice on the test suites with Microsoft Visual Studio.
=> Microsoft Visual C Compiler Warning Fixes

CMakeLists.txt, library/x509_crt.c, tests/CMakeLists.txt, tests/suites/helpers.function
This PR fixes a compiler warning found with Microsoft Visual Studio 2015 (and earlier versions), and also fixes a problem where the switch for compiler warnings was being configured twice on the test suites with Microsoft Visual Studio.
It is a backport of #670, and also contains a backport of @NWilson's pull request #353.
=> Microsoft Visual C Compiler Warning Fixes - backport to 2.1

library/ccm.c, library/ssl_srv.c, library/ssl_tls.c, library/x509_crt.c
This PR fixes various compiler warnings found with Microsoft Visual Studio 2015 (and earlier versions).
Note, it does not fix *all* compiler warnings in the 1.3 branch - just some, and those in #670 which were broken in 1.3.
=> Microsoft Visual C Compiler Warning Fixes - backport to 1.3

tests/suites/main_test.function
This PR removes unused variable warnings when compiling the test_suite_* programs by conditionally compiling the definition of a variable `stdout_fd` that is used in the output redirection. The original changes were introduced in https://github.com/ARMmbed/mbedtls/commit/2573136fa8147abeddcdc8c49b7a3d3a284f7170.
=> Remove unused var warnings in windows tests

include/mbedtls/ssl.h
I think this comment is misleading, because it makes a difference if MBEDTLS_SSL_PRESET_SUITEB or another value is passed as "preset".
Off-topic: as this is my first contribution I am thankful for any hints, about contributing.
=> removed outdated comment

tests/CMakeLists.txt
Changes use of `mklink` in Windows test builds, to create junctions instead of directory symbolic links. This removes the need for an elevated command prompt when running `cmake` to create the Visual Studio project files.
Fixes #686.
=> Remove need for elevated command line in Windows

tests/CMakeLists.txt
Changes use of `mklink` in Windows test builds, to create junctions instead of directory symbolic links. This removes the need for an elevated command prompt when running `cmake` to create the Visual Studio project files.
Fixes #686 - backport to 2.1.
=> Remove need for elevated command line in Windows - backport to 2.1

include/mbedtls/cmac.h
Added additional text to cmac.h to make the API clearer, on what the expected cipher type should be.
=> Clarify CMAC interface

tests/scripts/all.sh
Modify the script at tests/scripts/all.sh to export the variable
MAKEFLAGS with -j if it was not set before. This should decrease the
total runtime of tests/scripts/all.sh by letting make run multiple jobs
in parallel. Also, add a check at the top of the script to cause a
failure if the environment is not Linux.
=> Use MAKEFLAGS to pass args to make in all.sh

scripts/output_env.sh, tests/scripts/all.sh
I would like to point out that the script `tests/script/yotta-build.sh` actually uses armcc. However, I do not think there are yotta targets for ARM Compiler 6. Furthermore, we might need to evaluate how to force yotta to use a specific arm compiler binary.
=> Add ARM Compiler 6 build tests to all.sh

library/debug.c, library/net_sockets.c, tests/scripts/all.sh, tests/scripts/curves.pl, tests/scripts/test-ref-configs.pl
This pull request changes the configuration of compiler warnings in the `all.sh` test script, and for some test builds enforces compilation against the C99 standard. In addition, it also makes the mingw test build a mandatory step in the test script and no longer optional, and fixes some minor bugs that were throwing up warnings.
As an improvement on test quality, this does not need back porting.
=> Tighten compiler warning configurations in the release script

programs/test/CMakeLists.txt
The example `o_p_test` uses OpenSSL. On some platforms that fails to build
unless the dl library is included as a static link library.
Note this fix is only required on the mbedtls 1.3 branch as the `o_p_test` example was removed in later versions of mbed TLS.
=> Adds dl link library to OpenSSL example builds

scripts/config.pl
The variable `$config_file` was being referenced without being defined in the script `config.pl`.
* This issue does not apply to `development`, `mbedtls-2.4` nor `mbedtls-1.3` branches.
=> Fix undefined variable in scripts/config.pl

tests/scripts/curves.pl
The script, `tests/scripts/curves.pl` was broken, and did not build due to the make command not having been updated with the change from polarssl to mbed TLS.
This pull request changes the build command to `make lib` from `make polarssl`.
=> Fix curves.pl script to build

ChangeLog, library/pem.c, library/x509_crt.c, library/x509_csr.c
This PR fixes a number of unused variable/function compilation warnings
that arise when using a config.h that does not define the macro
MBEDTLS_PEM_PARSE_C.
=> Fix unused variable/function compilation warnings

ChangeLog, library/pem.c, library/x509_csr.c
This PR fixes a number of unused variable/function compilation warnings
that arise when using a config.h that does not define the macro
MBEDTLS_PEM_PARSE_C.
=> Backport 2.1: Fix unused variable/function compilation warnings

ChangeLog, library/pem.c, library/x509_csr.c
This PR fixes a number of unused variable/function compilation warnings
that arise when using a config.h that does not define the macro
POLARSSL_PEM_PARSE_C.
=> Backport 1.3: Fix unused variable/function compilation warnings

ChangeLog, include/mbedtls/ssl.h, library/ssl_tls.c, programs/ssl/ssl_server2.c, tests/ssl-opt.sh
Fix an incorrect condition in ssl_check_ctr_renegotiate() that compared
64 bits of record counter instead of 48 bits as described in RFC 6347
Section 4.3.1. This would cause the function's return value to be
occasionally incorrect and the renegotiation routines to be triggered
at unexpected times.
=> Fix renegotiation at incorrect times in DTLS

ChangeLog, include/mbedtls/ssl.h, library/ssl_tls.c, programs/ssl/ssl_server2.c, tests/ssl-opt.sh
This PR is a backport to mbed TLS 2.1 for https://github.com/ARMmbed/mbedtls/pull/729
=> Backport 2.1: Fix renegotiation at incorrect times in DTLS

programs/ssl/dtls_client.c, programs/ssl/ssl_mail_client.c
Fix a bug in `programs/ssl/ssl_mail_client.c` and `programs/ssl/dtls_client.c` that caused compilation to fail if `MBEDTLS_PEM_PARSE_C` was not defined.
This is a backport for https://github.com/ARMmbed/mbedtls/pull/785.
=> Fix examples that failed to compile without PEM - mbed TLS-2.1

ChangeLog, tests/suites/test_suite_ecjpake.function
__Changes:__ This PR corrects in invalid use of size zero arrays in the ECJPAKE test suite that triggers a compilation error on Visual Studio 2015 (but can also be observed with GCC or Clang when using the compilation flag `-Wpedantic`).
__Internal reference:__ IOTSSL-1242
__Backports:__ ECJPAKE not present in mbed TLS 1.3 or mbed TLS 2.1, so no backports needed.
=> Remove use of size zero array in ECJPAKE test suite

ChangeLog, include/polarssl/ssl.h, include/polarssl/ssl_ciphersuites.h, library/ssl_ciphersuites.c, library/ssl_srv.c, library/ssl_tls.c
This is the backport of https://github.com/ARMmbed/mbedtls/pull/888 to mbed TLS 1.3.
Please review. Though it's functionally a subset of https://github.com/ARMmbed/mbedtls/pull/888, rebasing was done manually and needed adaption at some places. In particular, the lack of an `ssl_internal.h` makes this structurally different from the original PR.
=> Backport 1.3: Enhance support for signature-hash-algorithm extension

ChangeLog, include/mbedtls/ssl.h, include/mbedtls/ssl_ciphersuites.h, include/mbedtls/ssl_internal.h, library/ssl_ciphersuites.c, library/ssl_cli.c, library/ssl_srv.c, library/ssl_tls.c
__Context:__ Fixes #823.
__Summary:__ This PR improves our support for the signature-hash-algorithm extension. During parsing, we now remember one suitable hash algorithm per signature algorithm, and we pick a cipher suite only if there is at least one suitable hash algorithm available.
__Changes on more detail:__ This PR is split in five commits which have detailed explanations in their respective commit messages. Roughly, we proceed in three steps:
* _Commit 1:_ Change use of PK abstraction layer; clarify the way signatures are treated as PK types.
* _Commit 2:_ Introduce helper functions and macros related to the encoding and decoding of signature and hash algorithms, and do some simplifications to ease overlooking the `ServerKeyExchange` write.
* _Commit 3:_ Change …
=> Enhance support for signature-hash-algorithm extension

ChangeLog, include/mbedtls/ssl.h, include/mbedtls/ssl_ciphersuites.h, include/mbedtls/ssl_internal.h, library/ssl_ciphersuites.c, library/ssl_cli.c, library/ssl_srv.c, library/ssl_tls.c
This is the backport of #888 to mbed TLS 2.1.
=> Backport 2.1: Enhance support for signature-hash-algorithm extension 

library/ssl_cli.c, library/ssl_srv.c, library/ssl_tls.c, tests/scripts/run-test-suites.pl, tests/ssl-opt.sh
* Balanced braces a source file to make it easier to move around in editors.
* Added an option to `ssl-opt.sh` to use a fixed port (a lot easier to observe with Wireshark).
* Added explicit tests where a server requests a certificate but the client does not offer one.
=> Minor dev and test improvements

ChangeLog, library/ssl_cli.c, library/ssl_srv.c, library/ssl_tls.c, tests/scripts/run-test-suites.pl, tests/ssl-opt.sh
Send a fatal alert in many more cases where we were just closing the connection.
Triggered by internal request IOTSSL-1330
=> Send fatal alerts in many more cases

ChangeLog, library/ssl_srv.c, tests/scripts/tcp_client.pl, tests/ssl-opt.sh
Fixed a bug in ssl_srv.c when parsing TLS_FALLBACK_SCSV in the
ciphersuite list that caused it to miss it sometimes. Reported by Hugo
Leisink as issue #810. Fix initially by @andreasag01 (PR #816); this commit
isolates the bug fix and adds a non-regression test.
Internal ref: IOTSSL-1223
Needs backports
=> Fix FALLBACK_SCSV parsing

tests/scripts/tcp_client.pl, tests/ssl-opt.sh
This is a backport of a non-regression test for issue #810 which affected
the current release of mbed TLS, but not the 1.3 branch.
I'm not sure if it's worth adding a non-regression test to a branch that never had this bug, but I had the patch anyway.
Original PR (with these tests plus a bug fix that doesn't apply to 1.3): #924 
Internal ref: IOTSSL-1223
=> Backport 1.3: Fix FALLBACK_SCSV parsing (only tests in this backport)

ChangeLog, library/ssl_srv.c, tests/scripts/tcp_client.pl, tests/ssl-opt.sh
Fixed a bug in ssl_srv.c when parsing TLS_FALLBACK_SCSV in the
ciphersuite list that caused it to miss it sometimes. Reported by Hugo
Leisink as issue #810. Fix initially by @andreasag01; this commit
isolates the bug fix and adds a non-regression test.
Backport of #924
=> Backport 2.1: Fix FALLBACK_SCSV parsing

ChangeLog, include/polarssl/x509.h, library/ssl_tls.c, library/x509_crt.c, programs/ssl/ssl_client2.c, programs/ssl/ssl_server2.c, tests/ssl-opt.sh
This is the backport of #903 to mbed TLS 1.3.
=> Backport 1.3: Fix implementation of optional verification mode

ChangeLog, library/ssl_tls.c, programs/ssl/ssl_client2.c, programs/ssl/ssl_server2.c, tests/ssl-opt.sh
This is the backport of #903 to mbed TLS 2.1.
=> Backport 2.1: Fix implementation of optional verification mode

ChangeLog, library/ssl_tls.c, programs/ssl/ssl_client2.c, programs/ssl/ssl_server2.c, tests/ssl-opt.sh
This PR changes the behaviour of `mbedtls_ssl_parse_certificate` to put the two verification modes `MBEDTLS_SSL_VERIFY_REQUIRED` and `MBEDTLS_SSL_VERIFY_OPTIONAL` in the relationship that using `MBEDTLS_SSL_VERIFY_REQUIRED` is equivalent to using `MBEDTLS_SSL_VERIFY_OPTIONAL` + checking the verification result.
Also, it changes the behaviour to perform the certificate chain verification even if the trusted CA chain is empty. Previously, the function failed in this case, even when using optional verification, which was brought up in #864.
__Please review.__ In particular, it needs to be validated that the user provided verification function `f_vrfy` is indeed supposed to report verification failures _only_ through the `flags` field, reserving nonzero return values for fatal errors. …
=> Fix implementation of optional verification mode

ChangeLog, include/mbedtls/ecdsa.h, programs/pkey/ecdsa.c
In the ecdsa.c sample application we don't use hashing, we use ecdsa
directly on a buffer containing plain text. Although the text explains
that it should be the message hash it still can be confusing.
Any misunderstandings here are potentially very dangerous, because ECDSA
truncates the message hash if necessary and this can lead to trivial
signature forgeries if the API is misused and the message is passed
directly to the function without hashing.
This commit adds a hash computation step to the ecdsa.c sample
application and clarification to the doxygen documentation of the
ECDSA functions involved.
=> Clarify the use of ECDSA API

tests/ssl-opt.sh
Straightfoward backport of #954
=> Fix issue in testing SHA-1 compile-time option (2.1 backport)

ChangeLog, include/mbedtls/bignum.h, library/bignum.c
__Summary:__ When provided with an empty line, `mpi_read_file` causes a numeric underflow resulting in a stack underflow. This PR fixes this and adds some documentation to `mpi_read_file`.
__Backports:__ Backports to mbed TLS 1.3 and 2.1 needed. Ready for the current version of the PR.
=> Fix potential stack underflow in mpi_read_file

ChangeLog, include/polarssl/bignum.h, library/bignum.c
This is the backport of #885 to mbed TLS 1.3.
=> Backport 1.3: Fix potential stack underflow in mpi_read_file.

ChangeLog, include/mbedtls/bignum.h, library/bignum.c
This is the backport of #885 to mbed TLS 2.1.
=> Backport 2.1: Fix potential stack underflow in mpi_read_file.

ChangeLog, library/ssl_srv.c
__Summary:__ In mbed TLS 1.3 a check went missing disabling the use of extensions in `SERVER_HELLO` for SSLv3, causing the "SSLv3 with extensions" test case from `ssl-opt.sh` to fail. This commit fixes that and adds a dump of all extensions present in the `CLIENT_HELLO` that the same test case also checks for.
=> Don't parse or write extensions in SSLv3

programs/ssl/ssl_client2.c, programs/ssl/ssl_server2.c
This is the backport of #958 to mbed TLS 2.1.
=> Backport 2.1: Simplify ECC and ALPN list size handling in ssl_client2 and ssl_server2

programs/ssl/ssl_client2.c, programs/ssl/ssl_server2.c
This is the backport of #958 to mbed TLS 1.3.
=> Backport 1.3: Simplify ECC and ALPN list size handling in ssl_client2 and ssl_server2

programs/ssl/ssl_client2.c, programs/ssl/ssl_server2.c
__Summary:__ This PR simplifies some code in `ssl_client2` and `ssl_server2` handling the sizes of ALPN and ECC curve lists, in particular removing the use of the `%zu` format qualifier which doesn't seem to be generally supported.
=> Simplify ECC and ALPN list size handling in ssl_client2 and ssl_server2

include/mbedtls/asn1.h
**READY**
This is a backport of https://github.com/ARMmbed/mbedtls/pull/1065 to mbed TLS 2.1
=> Backport 2.1: Fix typo in asn1.h

include/polarssl/asn1.h
**READY**
This is a backport of https://github.com/ARMmbed/mbedtls/pull/1065 to mbed TLS 1.3
=> Backport 1.3: Fix typo in asn1.h

ChangeLog, library/ssl_tls.c, programs/ssl/ssl_client2.c, tests/scripts/all.sh, tests/ssl-opt.sh
__Summary:__ This PR extends PR #1022, provided by [Florin Petriuc](https://github.com/FlorinPetriuc) and fixing #707, by a ChangeLog entry and tests that would have caught the issue.
__Internal Reference:__ IOTSSL-1670
=> Check application data buffer size if MFL extension is disabled

ChangeLog, library/ssl_tls.c, programs/ssl/ssl_client2.c, tests/scripts/all.sh, tests/ssl-opt.sh
__Summary:__ This is the backport of #1094 to Mbed TLS 2.1.
__Internal Reference:__ IOTSSL-1670
=> Backport 2.1: Check application data buffer size if MFL extension is disabled

ChangeLog, library/ssl_cli.c
When either of MBEDTLS_KEY_EXCHANGE_RSA_ENABLED, MBEDTLS_KEY_EXCHANGE_ECDH_RSA_ENABLED and MBEDTLS_KEY_EXCHANGE_ECDH_ECDSA_ENABLED are defined, the IAR compiler throws a variable use before set warning because of the statements:
```
((void) p);
((void) end);
```
These lines are included because it is possible that in some configurations the variables `p` and `end` are defined and assigned to but never referenced, which could cause yet more warnings in some compilers. Therefore, I have initialized them the value `NULL` when defining to remove the IAR compiler warning.
This PR fixes issue https://github.com/ARMmbed/mbedtls/issues/875
=> Initialise pointers to avoid IAR compiler warnings

include/mbedtls/entropy.h, library/entropy.c, tests/scripts/generate_code.pl, tests/suites/helpers.function, tests/suites/main_test.function, tests/suites/test_suite_entropy.data, tests/suites/test_suite_entropy.function, tests/suites/test_suite_rsa.function
__Context:__ Fixes #1023 and #1024.
__Summary:__ This PR addresses the following problems:
1. The RSA key generation test initializes the RSA context after seeding the CTR DRBG random number generator. If no strong entropy is present on the system, e.g. because the configuration flag `MBEDTLS_NO_PLATFORM_ENTROPY` is set and no other sources are provided, the seeding fails and leads to an attempt to free the uninitialized RSA context in the cleanup section - this most likely results in a segmentation fault, as originally observed in #1023 and #1024.
2. The entropy self-test should also catch the problem but doesn't because the conditional `depends_on:!MBEDTLS_TEST_NULL_ENTROPY` is not parsed correctly leading to the test case being dropped.
3. In light of the _expected_ failure of the RSA …
=> Correct RSA key generation test in case of missing entropy

ChangeLog, include/mbedtls/md.h
include *`config.h`* in md.h as MACROS in the header file get ignored.
Fix for #1001.
**READY**
Yes  
mbedtls-2.1
NO
=> Add configuration file in md.h

ChangeLog, include/mbedtls/md.h
include *`config.h`* in md.h as MACROS in the header file get ignored.
Fix for #1001.
Backport of #1055 to mbedtls-2.1
**READY**
=> Backport 2.1:Add configuration file in md.h

library/entropy.c, tests/scripts/generate_code.pl, tests/suites/helpers.function, tests/suites/test_suite_entropy.data, tests/suites/test_suite_entropy.function, tests/suites/test_suite_rsa.function
This is the backport of #1025 to Mbed TLS 2.1.
Differences from development PR: 
1. `NV_SEED` not present, hence removed from `ENTROPY_HAVE_STRONG`
1. `TEST_NULL_ENTROPY` not present, hence removed from `ENTROPY_HAVE_STRONG`.
1. `DEPENDENCY_[NOT_]SUPPORTED` not present, instead `0/1` used in test files.
1. Omitted some style changes.
1. `entropy_seed_file` test needed guard by `ENTROPY_HAVE_STRONG` that wasn't needed in development as it is already guarded by `MBEDTLS_ENTROPY_NV_SEED` there.
__Internal reference:__ IOTSSL-1580.
=> Backport 2.1: Correct RSA key generation test in case of missing entropy

ChangeLog, include/polarssl/md.h
include *`config.h`* in md.h as MACROS in the header file get ignored. Backport to
Backport of #1055 to mbedtls-1.3
=> Backport 1.3:Add configuration file in md.h

library/entropy.c, tests/scripts/generate_code.pl, tests/suites/helpers.function, tests/suites/test_suite_entropy.data, tests/suites/test_suite_entropy.function, tests/suites/test_suite_rsa.function
This is the backport of #1025 to Mbed TLS 1.3.
Differences from development PR: 
1. `NV_SEED` not present, hence removed from `ENTROPY_HAVE_STRONG`
1. `TEST_NULL_ENTROPY` not present, hence removed from `ENTROPY_HAVE_STRONG`.
1. `DEPENDENCY_[NOT_]SUPPORTED` not present, instead `0/1` used in test files.
1. Omitted some style changes.
1. `entropy_seed_file` test needed guard by `ENTROPY_HAVE_STRONG` that wasn't needed in development as it is already guarded by `MBEDTLS_ENTROPY_NV_SEED` there.
1. No distinction between strong and weak entropy sources. Renamed `ENTROPY_HAVE_STRONG` to `ENTROPY_HAVE_DEFAULT`.
__Internal Reference:__ IOTSSL-1580
=> Backport 1.3: Correct RSA key generation test in case of missing entropy

ChangeLog, library/net_sockets.c
__Context:__ This PR corrects a bug in `net_would_block` from `net_sockets.c` raised in #845. 
__Changes:__ Safe and restore the current value of `errno` in `net_would_block` to ensure it's not affected by the guarding call to `fcntl`. 
__Backports:__ Needs backport to mbed TLS 1.3 and 2.1.
=> Backup errno in net_would_block

ChangeLog, library/net.c
This is the backport of #895 to mbed TLS 2.1.
=> Backport 2.1: Backup errno in net_would_block

ChangeLog, library/ssl_tls.c, tests/scripts/all.sh, tests/ssl-opt.sh
__Summary:__ This is the backport of #1141 to Mbed TLS 2.1, obtained manually.
__Internal Reference:__ IOTSSL-1707.
=> Backport 2.1: Correctly handle handshake messages in ssl_read if renegotiation is disabled

ChangeLog, include/mbedtls/config.h, library/ssl_cli.c, library/ssl_tls.c, tests/scripts/all.sh, tests/ssl-opt.sh
__Context:__ Unexpected handshake messages lead to connection failure in `mbedtls_ssl_read` when `MBEDTLS_SSL_RENEGOTIATION` is disabled. In the presence of package duplication, this can constitute a severe problem, as e.g. duplicated and delayed `Finished` messages would bring down the connection after the initial handshake has completed and application data is expected next. This was observed [here](https://github.com/openthread/openthread/issues/2176).
__Changes:__ This PR fixes the issue by restricting the `MBEDTLS_SSL_RENEGOTIATION`-guard in `mbedtls_ssl_read` to the code-path accepting renegotiations and the code-path aborting pending renegotiations. Further, it adds missing dependencies on `MBEDTLS_SSL_RENEGOTIATION` to some tests in `ssl-opt.sh` and includes a build and test run …
=> Correctly handle handshake messages in ssl_read if renegotiation is disabled

ChangeLog, library/net.c
This is the backport of #895 to mbed TLS 1.3.
=> Backport 1.3: Backup errno in net_would_block

ChangeLog, library/ssl_tls.c, tests/scripts/all.sh, tests/ssl-opt.sh
__Summary:__ This is the backport of #1141 to Mbed TLS 1.3, obtained manually. There is a slight difference to the head and 2.1 PR's in that in Mbed TLS 1.3 the config used `SSL_DISABLE_RENEGOTIATION` instead of the later `SSL_RENEGOTIATION`. As `ssl.h` adds `SSL_RENEGOTIATION` as `! SSL_DISABLE_RENEGOTIATION`, the changes in `ssl_read` read the same as for the head and 2.1 PR's, but the test changes to `ssl-opt.sh` and `all.sh` use `SSL_DISABLE_RENEGOTIATION`.
__Internal Reference:__ IOTSSL-1707.
=> Backport 1.3: Correctly handle handshake messages in ssl_read if renegotiation is disabled

programs/test/benchmark.c, yotta/data/example-benchmark/README.md, yotta/data/example-benchmark/main.cpp
The benchmark application prints the performance in Kb/s,
While it actually calculates KB/s.
Resolves issue #850
=> Fix wrong output in the benchmark application

library/pk.c, library/pk_wrap.c
There were preprocessor directives in pk.c and pk_wrap.c that cheked
whether the bit length of size_t was greater than that of unsigned int.
However, the check relied on the MBEDTLS_HAVE_INT64 macro being defined
which is not directly related to size_t. This might result in errors in
some platforms. This change modifies the check to use the macros
SIZE_MAX and UINT_MAX instead making the code more robust.
**NOTE:**
* This is a backport of https://github.com/ARMmbed/mbedtls/pull/1043 to mbed TLS 2.1
**READY**
=> Backport 2.1: Change PK module preprocessor check on word size

library/pk.c, library/pk_wrap.c
There were preprocessor directives in pk.c and pk_wrap.c that cheked
whether the bit length of size_t was greater than that of unsigned int.
However, the check relied on the MBEDTLS_HAVE_INT64 macro being defined
which is not directly related to size_t. This might result in errors in
some platforms. This change modifies the check to use the macros
SIZE_MAX and UINT_MAX instead making the code more robust.
**NOTE:**
* This change is related to https://github.com/ARMmbed/mbedtls/pull/900
**READY**
**Yes**
Which branch?
* mbedtls-2.1
* mbedtls-1.3
NO
=> Change PK module preprocessor check on word size

library/pk.c, library/pk_wrap.c
There were preprocessor directives in pk.c and pk_wrap.c that checked
whether the bit length of size_t was greater than that of unsigned int.
However, the check relied on the POLARSSL_HAVE_INT64 macro being
defined which is not directly related to size_t. This might result in
errors in some platforms. This change modifies the check to use the
macros SIZE_MAX and UINT_MAX instead making the code more robust.
**NOTE:**
* This is a backport of https://github.com/ARMmbed/mbedtls/pull/1043 to mbed TLS 1.3
**READY**
=> Backport 1.3: Change PK module preprocessor check on word size

library/pkparse.c
Fix build with `MBEDTLS_PKCS12_C` or `MBEDTLS_PKCS5_C` but without `MBEDTLS_FS_IO` (missing definition of `mbedtls_zeroize` in `library/pkparse.c`).
Issue introduced by #1112, caught by `all.sh`. This commit passes `all.sh` on my machine.
Backport of #1184
=> Backport 2.1: Fix build without MBEDTLS_FS_IO

library/x509_crl.c
Fix misleading indentation. This was just bad indentation, the behavior was correct.
This matters because it breaks the build with `gcc-6 -Werror`.
This issue is only present on the 2.1 branch, not in 1.3 or in development.
Tested locally with `all.sh` using gcc 6.4.0.
=> 2.1 only: Fix build error with gcc6 (misleading indentation)

library/pkparse.c
Fix build with `POLARSSL_PKCS12_C` or `POLARSSL_PKCS5_C` but without `POLARSSL_FS_IO` (missing definition of `polarssl_zeroize` in `library/pkparse.c`).
Issue introduced by #1113, caught by `all.sh`.
Backport of #1184
=> Backport 1.3: Fix build without MBEDTLS_FS_IO

library/pkparse.c, tests/scripts/all.sh
Fix build with `MBEDTLS_PKCS12_C` or `MBEDTLS_PKCS5_C` but without `MBEDTLS_FS_IO` (missing definition of `mbedtls_zeroize` in `library/pkparse.c`).
Issue introduced by #1062, caught by `all.sh`. This commit passes `all.sh` on my machine.
Backports: #1185 #1186
=> Fix build without MBEDTLS_FS_IO

ChangeLog, library/ssl_cache.c
Backport of #1145 to 1.3 branch
=> Backport 1.3: Fix crash when calling `mbedtls_ssl_cache_free` twice

ChangeLog, library/ssl_cache.c
Set `cache` to zero at the end of `mbedtls_ssl_cache_free` 
fixes #1104
**READY**
Yes 
Which branch?
mbedtls-2.1
mbedtls-1.3
call ``mbedtls_ssl_cache_free` when session has been set to the chain
=> Fix crash when calling `mbedtls_ssl_cache_free` twice

ChangeLog, library/ssl_cache.c
Backport of https://github.com/ARMmbed/mbedtls/pull/1145 to 2.1 branch
=> Backport 2.1: Fix crash when calling `mbedtls_ssl_cache_free` twice

tests/ssl-opt.sh
In `ssl-opt.sh`, support `--seed` and `$SEED` to set the seed for random tests. This already exists in development but not in 2.1.
Partial backport of commit 7770ea82d5772612f6ae9afc2a1b931079bd4eb0.
This makes `tests/scripts/all.sh --release-test` be actually repeatable — the part in `all.sh` had already been backported, but it had no effect without the part in `ssl-opt.sh`.
=> 2.1 only: ssl-opt.sh: support fixed seed for random tests

Makefile, tests/Makefile
Modify the mbedtls/Makefile and tests/Makefile files to avoid executing
POSIX shell commands. Furthermore, ensure that perl scripts explicitly
invoke the interpreter instead of relying on the environment to read
the shebang and find the interpreter, which can cause failures in
Windows.
**NOTES:**
* This change does not need to be included in either mbed TLS 2.1 or development as the problem was previously resolved there.
* Instead of hardcoding `perl` explicitly as in the test/Makefile in mbedtls 2.1 and development, I have used a variable that can be overwritten from the environment.
=> mbed TLS 1.3: Fix project Makefiles to work in Windows

tests/compat.sh, tests/ssl-opt.sh
Fix a race condition in `compat.sh`: instead of using `sleep 1` to detect whether the server has started, call `lsof` if available, as was already done in `ssl-opt.sh`. In addition to fixing this race condition, which causes CI runs to fail when the machine is heavily loaded, this makes the script faster on a lightly-loaded machine.
I also made some minor improvements to the way `lsof` is called so that on the platforms we care about, there is no tight loop and the detection tends to be a little faster.
Internal ref: IOTSSL-1831
Straight backport of #1210
=> Backport 2.1: Fix race condition in compat.sh

tests/compat.sh, tests/ssl-opt.sh
Fix a race condition in `compat.sh`: instead of using `sleep 1` to detect whether the server has started, call `lsof` if available, as was already done in `ssl-opt.sh`. In addition to fixing this race condition, which causes CI runs to fail when the machine is heavily loaded, this makes the script faster on a lightly-loaded machine (I observed -25% on a fast PC).
I also made some minor improvements to the way `lsof` is called so that on the platforms we care about, there is no tight loop and the detection tends to be a little faster.
Internal ref: IOTSSL-1831
Backports: #1216 #1217
=> Fix race condition in compat.sh

scripts/config.pl
Back port from https://github.com/ARMmbed/mbedtls/pull/1230
This PR aligns script ```scripts/config.pl``` with development branch and enhances it script with a ```baremetal``` option to produce a bare metal configuration. This would help in CI where bare metal configuration is part of CI script and same is applied to all branches. Though all branches may not have same symbols. Having bare metal config using this script will enable keep separate steps for different release branches. Hence making CI script simple.
It is planned to use it in all.sh too. But in a separate PR to reduce merging conflicts.
Yes to enable bare metal IAR build on other branches.
2.1 and 1.3
NO
Run 
```
./script/config.pl baremetal
```
=> Backport 2.1: Enhance config.pl to do baremetal configuration.

scripts/config.pl
Back port from https://github.com/ARMmbed/mbedtls/pull/1230
This PR aligns script ```scripts/config.pl``` with development branch and enhances ```config.pl``` script with a ```baremetal``` option to produce a bare metal configuration. This would help in CI where bare metal configuration is part of CI script and same is applied to all branches. Though all branches may not have same symbols. Having bare metal config using this script will enable keep separate steps for different release branches. Hence making CI script simple.
It is planned to use it in all.sh too. But in a separate PR to reduce merging conflicts.
Yes to enable bare metal IAR build on other branches.
2.1 and 1.3
NO
Run 
```
./script/config.pl baremetal
```
=> Backport 1.3: Enhance config.pl to do baremetal configuration.

ChangeLog, library/timing.c
This is a partial backport of #1136 . Included:
* Fix read from an uninitialized integer object in `mbedtls_timing_get_timer` on Windows (internal ref: IOTSSL-1822)
* Fix `mbedtls_set_alarm(0)` on Unix/POSIX.
* The timing self-test is more tolerant and shorter.
I omitted the rest because 1.3 is on its way out and I don't think the rest of the original PR is worth it.
Internal ref: IOTSSL-1798
=> Backport 1.3: More robust timing tests

ChangeLog, include/mbedtls/timing.h, library/timing.c, programs/test/selftest.c, tests/suites/test_suite_timing.data, tests/suites/test_suite_timing.function
The primary objective of this PR is to fix the issue we have with `test_suite_timing` and the TIMING selftest on the CI, which sometimes fail due to heavy load. I also fixed some minor bugs in the timing module.
This PR introduces new timing tests that test the functions in the timing module mostly independently. The old self-test is still present in the code but will not be executed by the test suite, like other self-tests that we judge to be too time-consuming. CI still runs it once through `programs/test/selftest`.
Compared with the self-tests:
* The new tests are more modular and print some detailed information when they fail.
* I don't test `mbedtls_set_alarm` with delays of more than 1 second, which makes the test run for about 2s instead of 8s.
* The timing self-test is more …
=> More robust timing tests

ChangeLog, include/mbedtls/timing.h, library/timing.c, programs/test/selftest.c
This is a partial backport of #1136 . Included:
* Fix read from an uninitialized integer object in `mbedtls_timing_get_timer` on Windows (internal ref: IOTSSL-1822)
* Improved documentation of the timing API.
* Fix `mbedtls_set_alarm(0)` on Unix/POSIX.
* In the `selftest` program, support running a subset of the tests with command line arguments.
* The timing self-test is more tolerant and shorter.
Not included:
* New unit tests — there were no unit tests for the timing module in 2.1.
Internal ref: IOTSSL-1798
=> Backport 2.1: More robust timing tests

tests/scripts/all.sh
Keep-going mode for `tests/scripts/all.sh` so that even if one of the tests fails, the other tests run. Print a report at the end and return a nonzero status code if anything failed.
The reason to have this mode is to get complete feedback so that this script can be used for regular testing and not as a last-minute check that we don't expect to fail.
Also added options to skip yotta and armcc usage.
Backports: #1221 #1222
=> all.sh --keep-going

tests/scripts/all.sh
Keep-going mode for `tests/scripts/all.sh` so that even if one of the tests fails, the other tests run. Print a report at the end and return a nonzero status code if anything failed.
The reason to have this mode is to get complete feedback so that this script can be used for regular testing and not as a last-minute check that we don't expect to fail.
Also added an option to skip armcc usage (this version doesn't run yotta).
Backport of #1207
=> Backport 1.3: all.sh --keep-going

tests/scripts/all.sh
Keep-going mode for `tests/scripts/all.sh` so that even if one of the tests fails, the other tests run. Print a report at the end and return a nonzero status code if anything failed.
The reason to have this mode is to get complete feedback so that this script can be used for regular testing and not as a last-minute check that we don't expect to fail.
Also added an option to skip armcc usage (this version doesn't run yotta).
Backport of #1207
=> Backport 2.1: all.sh --keep-going

ChangeLog, include/mbedtls/config.h, include/mbedtls/gcm.h, library/gcm.c, library/version_features.c
Provide the ability to use an alternative implementation of GCM in place
of the library provide implementation.
NOTES:
- This is a new feature and does not need to be backported.
- This does not follow Ron's `ALT` style (https://github.com/ARMmbed/mbedtls/pull/867)
- Tested with "alternate" software implementation of GCM that's actually just the library implementation (https://github.com/Patater/mbedtls/commits/gcm-alt-test)
```
test_suite_aes.cbc ................................................ PASS
test_suite_aes.cfb ................................................ PASS
test_suite_aes.ecb ................................................ PASS
test_suite_aes.rest ............................................... PASS
test_suite_arc4 ................................................... PASS …
```
=> Allow alternate implementation of GCM

ChangeLog, programs/pkey/rsa_genkey.c, tests/suites/test_suite_mpi.function
__Summary:__ This is the backport of #1265 addressing two minor issues found by Coverity.
@mpg @Patater Please review.
=> Backport 1.3: Address coverity issues

ChangeLog, programs/pkey/rsa_genkey.c, tests/suites/test_suite_mpi.function
__Summary:__ This is the backport of #1265 addressing two minor pre-existing issues found by Coverity.
@mpg @Patater Please review.
=> Backport 2.1: Address coverity issues

programs/pkey/dh_server.c
The example programs `dh_server` and `dh_client` do not work out of the box. The client sends 256 bytes, the length of the public key, but the server (wrongly) expects 519 bytes, which is the total length of the DH parameters structure.
This fixes initialises the value of `n` in `dh_server.c` in a similar fashion as is done in `dh_client.c`.
=> Fix for dh_server example program

library/ssl_srv.c
__Summary:__ This PR fixes a comparison of `ssl_session->encrypt_then_mac` against the ETM-unrelated constant `MBEDTLS_SSL_EXTENDED_MS_DISABLED`. Instead, `MBEDTLS_SSL_ETM_DISABLED` should be used.
The typo is has no functional effect since both constants have value `0`.
=> Wrong identifier used to check Encrypt-then-MAC flag

programs/pkey/gen_key.c
Fix copy paste error in the error message of mbedtls_ecp_gen_key in gen_key.c
**READY**
NO
NO
=> Fix copy paste error in the error message of mbedtls_ecp_gen_key in gen_key.c

include/mbedtls/x509_crt.h
Fix documentation typos and alignment issues for the function mbedtls_x509_crt_check_extended_key_usage() in include/mbedtls/x509_crt.h
**READY**
=> Fix x509 ext key usage typos

library/ssl_srv.c
This is the backport of #1150 to Mbed TLS 2.1.
=> Backport 2.1: Wrong identifier used to check Encrypt-then-MAC flag

library/ssl_srv.c
This is the backport of #1150 to Mbed TLS 1.3.
=> Backport 1.3: Wrong identifier used to check Encrypt-then-MAC flag

library/cipher.c, tests/suites/test_suite_cipher.padding.data
The function get_one_and_zeros_padding() accepts invalid padded data.
This commit fixes the bug and adds a test case (“0000000082”) which fails with the old implementation.
**READY**
Yes
NO
=> fix bug in get_one_and_zeros_padding()

ChangeLog, library/cipher.c, tests/suites/test_suite_cipher.padding.data
The function get_one_and_zeros_padding() accepts invalid padded data.
Straightforward backport of the original PR by @mickrau : #1236
=> Backport 2.1: fix bug in get_one_and_zeros_padding()

ChangeLog, include/mbedtls/config.h, include/mbedtls/ecjpake.h, library/ecjpake.c, library/version_features.c
__Summary:__ This PR adds support for alternative implementation of the entire ECJPAKE module, controlled as usual by a configuration flag `MBEDTLS_ECJPAKE_ALT`. 
__Internal Reference:__ IOTSSL-2042
@Patater @yanesca Please review.
=> Add support for alternative ECJPAKE implementation

CMakeLists.txt, Makefile, doxygen/mbedtls.doxyfile
When the Doxywizzard GUI is used and the doxyfile is loaded, the
workind directory for doxygen is set to the location of the doxyfile.
However the Make and CMake build systems expect doxygen to be ran
from the top level directory.
This commit unifies the build system and the Doxywizzard GUI so that
all of them expect doxygen to be executed in the doxygen directory.
**READY**
This change may be considered backporting, but it's impact is limited to the user experience while generating documentation.
NO
NONE
NONE
Perform all of the following, deleting the apidoc directory in the top level directory after each step:
1. Create the documentation using `make apidoc` command in the top level directory; verify the documentation in the apidoc directory.
2. Create the documentation using CMake; …
=> Have doxygen run in the doxygen directory

programs/test/benchmark.c
Backport of #1036 to mbed TLS 2.1 branch.
Remove duplicate definition of PRINT_ERROR
in the benchmark sample application
**READ**
=> Backport 2.1:Remove duplicated def. of PRINT_ERROR

programs/test/benchmark.c
Backport of #1036 to mbed TLS1.3 branch.
Remove duplicated definition of PRINT_ERROR
in the benchmark sample application
**READY**
=> Backport 1.3:Remove duplicated def. of PRINT_ERROR

tests/CMakeLists.txt
generate add ctest test-suites, with the --verbose argument to be given
to the test suites.
The verbose output will be shown **only** if ctest is run with `-v` parameter
The verbose argument is to the test-suites, only when run through `ctest`
=> Support verbose output of the test suites

programs/test/benchmark.c
The PRINT_ERROR macros are already defined exactly the same in line
101ff, so we can remove them here.
**READY**
NO
NO
None
Done - Username: PeterHuewe
=> Remove duplicated definition of PRINT_ERROR

ChangeLog, include/mbedtls/aes.h, include/mbedtls/arc4.h, include/mbedtls/blowfish.h, include/mbedtls/camellia.h, include/mbedtls/ccm.h, include/mbedtls/cipher.h, include/mbedtls/cmac.h, include/mbedtls/des.h, include/mbedtls/dhm.h, include/mbedtls/ecp.h, include/mbedtls/error.h, include/mbedtls/gcm.h, include/mbedtls/md.h, include/mbedtls/pk.h, include/mbedtls/rsa.h, include/mbedtls/xtea.h, library/error.c, scripts/generate_errors.pl
Add MBEDTLS_ERR_XXX_HW_ACCEL_FAILED error codes for all cryptography
modules where the software implementation can be replaced by a hardware
implementation.
This does not include the individual message digest modules since they
currently have no way to return error codes. That part is done in #1294
This does include the higher-level md, cipher and pk modules since
alternative implementations and even algorithms can be plugged in at
runtime.
[added by mpg]: no backports required, hardware acceleration is a new feature
Internal reference: IOTSSL-2039
=> Error codes for hardware accelerator failures

programs/ssl/ssl_server2.c
Backport of https://github.com/ARMmbed/mbedtls/pull/1287
=> Backport 2.1: Fix race condition in error printing in ssl_server2.c

ChangeLog, library/timing.c
Bacport of https://github.com/ARMmbed/mbedtls/pull/1328
=> Backport 2.1: Fix alarm(0) failure on mingw32

programs/ssl/ssl_server2.c
Backport of https://github.com/ARMmbed/mbedtls/pull/1287
Note: compared to 2.x, 1.3 didn't have any `ERR_NET_ACCEPT_INVALID_CONTEXT` error, but returned `NET_RECV_FAILED` when trying to read from a closed socket. This is less specific so could in principle hide errors, but:
- those errors were already hidden anyway, so this PR is an improvement,
- the errors that could in principle be hidden are not those that we are actually interested in, so this PR solves the problem it's trying to solve.
=> Backport 1.3 : Fix race condition in error printing in ssl_server2.c

ChangeLog, library/timing.c
Backport of https://github.com/ARMmbed/mbedtls/pull/1328
=> Backport 1.3: Fix alarm(0) failure on mingw32

tests/compat.sh, tests/ssl-opt.sh
This tries to address the slow start issues we're seeing with compat.sh and ssl-opt.sh on CI machines that don't have lsof yet.
It is a replacement for https://github.com/ARMmbed/mbedtls/pull/1269 addressing only the slow start issue (the issue with incomplete server logs will be addressed in a separate PR).
I believe this is not worth a ChangeLog entry as this is hardly visible / of importance to users other than us.
**READY**
Yes
[x] Mbed TLS 2.1 https://github.com/ARMmbed/mbedtls/pull/1288
[x] Mbed TLS 1.3 https://github.com/ARMmbed/mbedtls/pull/1289
=> Iotssl 2005 slow start

programs/ssl/ssl_server2.c
Fix a race condition in `ssl_server2.c` that caused spurious failures of `ssl-opt.sh` especially on hghly-loaded CI machines where it is likely for a process to not get a slice of CPU often enough.
This is part 2 of the replacement for https://github.com/ARMmbed/mbedtls/pull/1269 - addressing the "incomplete server logs" issue.
I believe this is not worth a ChangeLog entry as this is hardly visible / of importance to users other than us.
**READY**
Yes
[x] Mbed TLS 2.1 https://github.com/ARMmbed/mbedtls/pull/1290
[x] Mbed TLS 1.3 https://github.com/ARMmbed/mbedtls/pull/1291
=> Fix race condition in error printing in ssl_server2.c

ChangeLog, library/timing.c
A new test for mbedtls_timing_alarm(0) was introduced in PR 1136, which also
fixed it on Unix. Apparently test results on MinGW were not checked at that
point, so we missed that this new test was also failing on this platform.
This PR fixes the function in order to make the new test pass, in a way similar to the fix introduce in by #1136 for Unix.
**READY**
Yes
[x] Mbed TLS 2.1 https://github.com/ARMmbed/mbedtls/pull/1329
[x] Mbed TLS 1.3 https://github.com/ARMmbed/mbedtls/pull/1330
=> Fix alarm(0) failure on mingw32

ChangeLog, include/mbedtls/arc4.h, include/mbedtls/cipher.h, include/mbedtls/config.h, include/mbedtls/des.h, include/mbedtls/md.h, include/mbedtls/md2.h, include/mbedtls/md4.h, include/mbedtls/md5.h, include/mbedtls/sha1.h
This PR is a subset of #1110. It only adds the documentation warnings introduced by #1110 and no other changes.
Backport to 2.1 of #1336
=> Backport 2.1: Add documentation warnings for weak algorithms

ChangeLog, include/polarssl/arc4.h, include/polarssl/cipher.h, include/polarssl/config.h, include/polarssl/des.h, include/polarssl/md.h, include/polarssl/md2.h, include/polarssl/md4.h, include/polarssl/md5.h, include/polarssl/sha1.h
This PR is a subset of #1111. It only adds the documentation warnings introduced by #1111 and no other changes.
Backport to 1.3 of #1336
=> Backport 1.3: Add documentation warnings for weak algorithms

ChangeLog, include/mbedtls/arc4.h, include/mbedtls/cipher.h, include/mbedtls/config.h, include/mbedtls/des.h, include/mbedtls/md.h, include/mbedtls/md2.h, include/mbedtls/md4.h, include/mbedtls/md5.h, include/mbedtls/sha1.h
This PR is a subset of #1100. It only adds the documentation warnings introduced by #1100 and no other changes.
Backports: #1337 #1338
=> Add documentation warnings for weak algorithms

include/mbedtls/ccm.h
Fix valid IV length values for mbedtls_ccm_encrypt_and_tag() function.
Signed-off-by: Mathieu Briand <mbriand@witekio.com>
Hi,
I believe the range currently described for the mbedtls_ccm_encrypt_and_tag() function is wrong.
It is said that the iv_len parameter (nonce size) must be in the [2, 8] range.
https://github.com/ARMmbed/mbedtls/blob/888fedea06bfa267b81237ab4d2f336621b536da/include/mbedtls/ccm.h#L81
However, according to rfc3610, nonce is "15-L" bytes where L must be in [2, 8] range, thus nonce size must be in [7, 13] range. This seems to be confirmed by the following line in ccm_auth_crypt() where the given iv_len is verified to be in the [7, 13] range.
https://github.com/ARMmbed/mbedtls/blob/888fedea06bfa267b81237ab4d2f336621b536da/library/ccm.c#L162
=> Fix doxygen documentation for CCM encryption

include/mbedtls/dhm.h
We accidentally named the constant MBEDTLS_DHM_RFC5114_MODP_P instead of
MBEDTLS_DHM_RFC5114_MODP_2048_P.
Fixes #1358
**READY**
NO
=> dhm: Fix typo in RFC 5114 constants

ChangeLog, tests/scripts/all.sh, tests/suites/test_suite_pk.function
1. Rebase of #900: Add a build and a test runs to `all.sh` to ensure that mbed TLS builds and works with the GCC flags `-m32` and `-mx32`. Fixes #849
2. Fix tests with forced 64-bit or 32-bit bignum limb size: execute them once, regardless of the architecture.
Internal ref: IOTSSL-1300
Note to reviewers: the first three commits are from #900 (previously approved), rebased on top of current development, which meant adjusting to the changes in `all.sh`. The subsequent commits are new, to fix issue 2 which I noticed.
Backports (of (1) + other ILP32 fixes as applicable; (2) does not apply): #1334, #1335
=> Fix ILP32 issues

ChangeLog, include/mbedtls/bn_mul.h, library/aesni.c, tests/scripts/all.sh, tests/suites/test_suite_pk.function
Rebase of #901 on top of current mbedtls-2.1:
> This PR does the following things:
> * Backports the changes in https://github.com/ARMmbed/mbedtls/pull/376
> * Fixes the tests `pk_rsa_overflow()` and `pk_rsa_alt()` in `test_suite_pk.function` that previously caused segfaults when building with `-mx32`.
> * Adds a build and tests to `all.sh` to compile and run mbed TLS with the flags `-m32` and `mx32` (backport of #900).
> These changes fixes the library problems when building with the 64-bit ILP32 ABI and addresses the issue at https://github.com/ARMmbed/mbedtls/issues/849
Internal ref: IOTSSL-1300
Note to reviewers: this is #901 (previously approved) rebased on top of current mbedtls-2.1, which meant adjusting to the changes in `all.sh`.
Backport of #1333, with additional bug fixes …
=> Backport 2.1: Fix ILP32 issues

programs/x509/cert_write.c
Note: This PR will be relevant after #1293 is merged.
This PR adds support for using opaques to sign a certificate. Physical interface to a SE (secure element) is based on an mbed-os implementation (PR coming soon) that exposes a serial communication interface.
With a mbed device connected. Following command line can be used to generated a self signed certificate:
```
cert_write.exe subject_key=remote0COM18 issuer_key=remote0COM18 issuer_name=CN=Cert,O=mbed TLS,C=UK authority_identifier=0
```
Above, subject_key and issuer_key is specified with format ```remote<key ID><serial port>```. The format helps the app to differentiate between files and SE interface. Issuer name is supplied to match default subject name to indicate self signing.
This PR is essential for testing opaque keys with a …
=> Add support for using opaque keys in cert_write.c to sign a certificate

ChangeLog, include/mbedtls/md2.h, include/mbedtls/md4.h, include/mbedtls/md5.h, include/mbedtls/ripemd160.h, include/mbedtls/sha1.h, include/mbedtls/sha256.h, include/mbedtls/sha512.h, library/md2.c, library/md4.c, library/md5.c, library/ripemd160.c, library/sha1.c, library/sha256.c, library/sha512.c
In 2.7.0, we replaced a number of MD functions with deprecated inline
versions. This causes ABI compatibility issues, as the functions are no
longer guaranteed to be callable when built into a shared library.
Instead, deprecate the functions without also inlining them, to help
maintain ABI backwards compatibility.
Backport of #1382 to 2.7
=> Backport 2.7: MD: Make deprecated functions not inline

library/md2.c, library/md4.c, library/md5.c, library/sha1.c, library/sha256.c, library/sha512.c
Wrappers ```mbedtls_.*_process``` are as good for _ALT implementations as they are for internal software implementation. Hence moved outside ```!MBEDTLS_.*_PROCESS_ALT``` flags.
Very urgent as blocks PR https://github.com/ARMmbed/mbed-os/pull/6176
=> Enable deprecated API wrappers for _ALT implementation

library/md2.c, library/md4.c, library/md5.c, library/sha1.c, library/sha256.c, library/sha512.c
Reverting as this temporary change can be done directly to mbed-os PR. That way this branch can stay clean. In future once mbed-os _ALT implementations are fixed this branch can again be imported in mbed-os feature-opaque-key branch.
=> Revert "Merge pull request #1399 from mazimkhan/feature-opaque-keys"

tests/scripts/all.sh
Fix `all.sh --keep-going` not working if TERM is unset (e.g. in Docker).
Follow-up to https://github.com/ARMmbed/mbedtls/pull/1221
Backport of #1249
=> Backport 2.1: all.sh --keep-going: work if TERM is unset

ChangeLog, library/debug.c, library/platform.c
This is a backport of https://github.com/ARMmbed/mbedtls/pull/1079 to mbedtls-2.1
=> Backport 2.1:Fix compilation error with Mingw32

library/net.c
Robustness fix in `library/net.c`.
Backport of #1012
=> Backport 2.1: Fix typo and bracketing in macro args

ChangeLog, tests/suites/test_suite_pk.function
backport of #1407 to branch 2.1
=> Backport 2.1: Test suite test_suite_pk test pk_rsa_overflow passes valid parameters

ChangeLog, tests/suites/test_suite_pk.function
backport of #1407 to branch 2.7
=> Backport 2.7: Test suite test_suite_pk test pk_rsa_overflow passes valid parameters

ChangeLog, include/mbedtls/ssl.h
Note that the configuration structure must remain accessible. The
previous wording could have been taken as implying that it's ok to
change the structure but changes wouldn't be taken into account.
Also note that calling this function twice is not supported (it would
at least be a memory leak).
Internal ref: IOTSSL-1416
=> Clarified documentation of mbedtls_ssl_setup

library/net_sockets.c
This is a forwardport of two fixes from https://github.com/ARMmbed/mbedtls/pull/999:
* Bracketing around arguments to function macros in net_sockets.c
* Typo in net_sockets.c comment.
=> Fix typo and bracketing in macro args

ChangeLog, library/debug.c, library/platform.c
Fix compilation error on Mingw32 when `_TRUNCATE` is defined. Use
`_TRUNCATE` only if `__MINGW32__` not defined. Fix suggested by
Thomas Glanzmann and Nick Wilson on issue and closes #355
As mentioned in #355:
> It is used because _TRUNCATE is defined in
/usr/i686-w64-mingw32/include/_mingw.h
**READY**
Yes 
Which branch?
mbedtls-2.1
NO
I don't have the right environment and couldn't test it. The fix was taken from issue #355 
I suspect this change affects all mingw32 builds
=> Fix compilation error with Mingw32

tests/scripts/all.sh
Fix `all.sh --keep-going` not working if TERM is unset (e.g. in Docker).
Follow-up to https://github.com/ARMmbed/mbedtls/pull/1207
Backports: #1250 #1251
=> all.sh --keep-going: work if TERM is unset

ChangeLog, tests/suites/test_suite_pk.function
Test suite `test_suite_pk` test `pk_rsa_overflow` passing valid parameters for hash/hash_len and sig/sig_len. Resolves #1179 
**READY**
Yes
Which branch?
mbedtls 2.1
mbedtls 2.7
=> Test suite test_suite_pk test pk_rsa_overflow passes valid parameters

ChangeLog, library/memory_buffer_alloc.c, library/pem.c, library/pkparse.c, library/x509_crl.c, tests/suites/test_suite_memory_buffer_alloc.data, tests/suites/test_suite_memory_buffer_alloc.function
This change fixes the following corner cases in memory_buffer_alloc.c:
* Calling `verify_chain()` on an uninitialized chain. Would previously cause a `NULL` dereference.
* Allocating a memory block large enough to overflow the length variable.
* Initializing the allocator with a buffer smaller than the size of a memory header.
This PR is based on the information recorded in https://github.com/ARMmbed/mbedtls/issues/639.
**NOTES:**
* This PR includes tests.
* The changes need to be backported to 2.7 (use this PR) and 2.1 (#1009)
=> Fix corner case uses of memory_buffer_alloc.c

ChangeLog, library/ssl_cli.c
Change location of log, to fit the correct number of used ciphersuites
Fixes #918
**READY**
Yes | NO  
mbedtls-1.3
mbedtls-2.1
NO
use a small amount of ciphersuites, enable SSL_RENEGOTIATION and\or SSL_FALLBACK_SCSV and look at log
=> Write correct number of ciphersuites in log

README.md
Improve cmake usage notes in Readme
**READY**
2.7: this PR can be merged in 2.7 too
2.1: https://github.com/ARMmbed/mbedtls/pull/1431
NO - documentation change only
=> Improve cmake usage notes in Readme

ChangeLog, library/memory_buffer_alloc.c, library/pem.c, library/pkparse.c, library/x509_crl.c, tests/scripts/generate_code.pl, tests/suites/helpers.function, tests/suites/main_test.function, tests/suites/test_suite_memory_buffer_alloc.data, tests/suites/test_suite_memory_buffer_alloc.function
This change fixes the following corner cases in memory_buffer_alloc.c:
* Calling `verify_chain()` on an uninitialized chain. Would previously cause a `NULL` dereference.
* Allocating a memory block large enough to overflow the length variable.
* Initializing the allocator with a buffer smaller than the size of a memory header.
This PR is based on the information recorded in https://github.com/ARMmbed/mbedtls/issues/639.
**NOTES:**
* This PR includes tests.
* This is a backport for #778
* This PR backports a number of changes from @redtangent to mbed TLS 2.1 to support the additional tests in test/suites/test_suite_memory_buffer_alloc.{function,data}
=> Backport 2.1: Fix corner case uses of memory_buffer_alloc.c

ChangeLog, library/entropy.c
This is the backport of #1275 to Mbed TLS 2.1.
Found and fix suggested by @ccli8 in https://github.com/ARMmbed/mbed-os/issues/5853.
=> Backport 2.1: Properly initialize and free entropy mixing hash contexts

README.md
Improve cmake usage notes in Readme.
Straightforward backport of #1241 + one commit of mine to show build modes in code font
=> Backport 2.1: Improve cmake usage notes in Readme

ChangeLog, include/mbedtls/check_config.h, include/mbedtls/config.h, include/mbedtls/ssl.h
__Summary:__ This PR deprecates the use of compression (configuration option `MBEDTLS_ZLIB_SUPPORT`). Support for compression is likely to be removed in the next major release of the library.
__Internal Reference:__ IOTSSL-2153
@mpg @gilles-peskine-arm Please review.
=> Deprecate support for record compression

ChangeLog, library/ssl_cli.c
This PR prevents two buffer overflow errors from happening in the ssl_parse_server_key_exchange function.
**READY**
YES
This fix should most probably be backported to all supported branches as the vulnerabilities aren't version speciffic.
NO
None
None prepared
=> IOTSSL-1879 buffer overflow in server key exchange parsing

ChangeLog, library/ssl_cli.c
This PR prevents two buffer overflow errors from happening in the ssl_parse_server_psk_hint function.
**READY**
YES
This fix should most probably be backported to all supported branches as the vulnerabilities aren't version speciffic.
NO
None
None prepared
=> IOTSSL-1878 buffer overflow in server psk hint parsing

ChangeLog, library/aes.c
Add missing `MBEDTLS_DEPRECATED_REMOVED` guards around the definitions
of `mbedtls_aes_decrypt` and `mbedtls_aes_encrypt`.
This fixes the build under `-Wmissing-prototypes -Werror`.
Fixes #1388
This is just the first commit of #1390, with only the bug fix and not the additional test for which rework is needed.
Needs to be merged into 2.7 and development (does not apply to 2.1).
=> Add missing MBEDTLS_DEPRECATED_REMOVED guards

ChangeLog, library/ssl_cli.c
=> Backport 2.1: IOTSSL-1878 buffer overflow in server psk hint parsing

ChangeLog, library/ssl_cli.c
=> Backport 2.1: IOTSSL-1879 buffer overflow in server key exchange parsing

ChangeLog, library/ssl_cli.c
Change location of log, to fit the correct number of used ciphersuites
Fixes #918
Backport of #1064
=> Backport 2.1: Write correct number of ciphersuites in log

ChangeLog, library/ssl_cli.c
=> Backport 2.7: IOTSSL-1878 buffer overflow in server psk hint parsing

ChangeLog, library/ssl_cli.c
=> Backport 2.7: IOTSSL-1879 buffer overflow in server key exchange parsing

library/cmac.c
In certain circumstances, some versions of GCC 4.* produce spurious compiler warnings related to uninitialized variables in conditional statements.  For details, see the [GCC bug report](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=42145).
This pull request initializes two variables in `cmac.c` as a work around to the GCC issue.
=> Workaround for GCC Bug

include/mbedtls/rsa_internal.h
Backport of #1441 
Internal ref: IOTSSL-2167
=> Add a missing bracket in ifdef for __cplusplus - 2.7

CMakeLists.txt
Cmake works nicely with subproject by simply dropping said project in a subdirectory and using the add_subdirectory() command on it, then using the targets in the top-level project. This works almost with mbedtls:  if you try to use mbedtls in a subdirectory and use add_subdirectory(), you would get issues with perl script being not found in top level of the project:
```
[...]
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Found Perl: /usr/bin/perl (found version "5.20.2") 
Can't open perl script "/path/myproject/scripts/config.pl": No such file or directory
```
This can be resolved by simply using the relative project path variable when looking for config.pl and the header template, not the toplevel ones.
READY
NO, enhancement.
NO
Contributor agreement …
=> Use current source paths for config file creation command

library/ssl_cli.c
This is only the fix of a typo in a comment (which is saying that compression is not supported with DTLS)
**READY/IN DEVELOPMENT/HOLD**
=> corrected a typo in a comment

library/pem.c
=> fix typo in pem.c

include/mbedtls/rsa_internal.h
Fix #1426
Internal ref: IOTSSL-2167
Needs backport: to 2.7 (the file didn't exist in 2.1)
=> Add a missing bracket in ifdef for __cplusplus

ChangeLog, programs/test/benchmark.c
Notes:
or for companies or those that do not wish to create an mbed account, a slightly different agreement can be found [here](https://www.mbed.com/en/about-mbed/contributor-license-agreements/)
**DONE**
- The PR follows the [mbed TLS coding standards](https://tls.mbed.org/kb/development/mbedtls-coding-standards)
Initializing arrays using non-constant expressions is not permitted in
C89, and was causing errors when compiling with Metrowerks CodeWarrior
(for classic MacOS) in C89 mode. Clang also produces a warning when
compiling with '-Wc99-extensions':
test/benchmark.c:670:42: warning: initializer for aggregate is …
=> benchmark: Fix incompatibility with C89 compilers

ChangeLog, programs/test/benchmark.c
Backport of #1435 to Mbed TLS 2.7
=> Backport 2.7: benchmark: Fix incompatibility with C89 compilers

ChangeLog, library/Makefile
This PR is the same as https://github.com/ARMmbed/mbedtls/pull/1383 but adds a ChangeLog entry.
Note that this PR fixes the immediate problem which is that the Makefile does not build a dynamic library for Mbed TLS in Mac OS X, but I have created the ticket https://github.com/ARMmbed/mbedtls/issues/1466 as the DLEXT cannot be set to `dylib` without editing the Makefile.
**READY**
Yes
Which branch?
mbedlts-2.1: https://github.com/ARMmbed/mbedtls/pull/1469
mbedtls-2.7: https://github.com/ARMmbed/mbedtls/pull/1468
To test this you need a Mac OS X system and then run:
```
SHARED=1 make -C library
```
However, note that the Makefile must be edited to set `DLEXT=dylib`
=> Fix dynamic library builds for Mac OS X

ChangeLog, include/mbedtls/threading.h, library/threading.c
This PR is the same as https://github.com/ARMmbed/mbedtls/pull/1058 but adds a ChangeLog entry. The idea is to avoid initialising and defining global mutexes for directory reads and gmtime when their corresponding features are not enabled in the config.h.
**READY**
Yes
Which branch?
Mbed TLS 2.1: https://github.com/ARMmbed/mbedtls/pull/1481
Mbed TLS 2.7: https://github.com/ARMmbed/mbedtls/pull/1479
Just continue using the library as normal. This change does not have any effect on the API and is more of an optimisation than a bugfix.
=> Avoid defining and initialising global mutexes when not needed

ChangeLog, library/pkcs5.c, tests/suites/test_suite_pkcs5.function
This PR superseeds https://github.com/ARMmbed/mbedtls/pull/680. The changes provides an empty implementation of `mbedtls_pkcs5_pbes2()` whenever `MBEDTLS_ASN1_PARSE_C` is not enabled. This makes it possible to compile and use PBES2 in PKCS5 without satisfying all the dependencies for PBES2.
**READY**
Yes
Which branch?
Mbed TLS 2.7: https://github.com/ARMmbed/mbedtls/pull/1524
Mbed TLS 2.1: https://github.com/ARMmbed/mbedtls/pull/1525
=> Compile PBES2 in PKCS5 only if ASN1 is enabled

ChangeLog, library/Makefile
This is a backport of #1467 to Mbed TLS 2.7
=> Mbedtls 2.1: Fix dynamic library builds for Mac OS X

ChangeLog, include/mbedtls/threading.h, library/threading.c
This is a backport for #1477 to Mbed TLS 2.1. Please refer to that PR for details.
Note that this PR also backports to Mbed TLS 2.1 another fix that was in development and Mbed TLS 2.7 which added the preprocessor guard MBEDTLS_THREADING_C around the definitions of the mutexes and function pointers for threading so that they are not defined when the feature is not present.
**READY**
=> Backport 2.1: Avoid defining and initialising global mutexes when not needed

ChangeLog, library/pkcs5.c, tests/suites/test_suite_pkcs5.function
This PR is a backport of #1523. Please refer to that PR for details.
**READY**
=> Backport 2.1: Compile PBES2 in PKCS5 only if ASN1 is enabled

ChangeLog, library/Makefile
This is a backport of https://github.com/ARMmbed/mbedtls/pull/1467 to Mbed TLS 2.7
=> Backport 2.7: Fix dynamic library builds for Mac OS X

ChangeLog, include/mbedtls/threading.h, library/threading.c
This is a backport for https://github.com/ARMmbed/mbedtls/pull/1477 to Mbed TLS 2.7. Please refer to that PR for details.
**READY**
=> Backport 2.7: Avoid defining and initialising global mutexes when not needed

ChangeLog, library/pkcs5.c, tests/suites/test_suite_pkcs5.function
This PR is a backport of https://github.com/ARMmbed/mbedtls/pull/1523. Please refer to that PR for details.
**READY**
=> Backport 2.7: Compile PBES2 in PKCS5 only if ASN1 is enabled

ChangeLog, include/mbedtls/net_sockets.h
This currently works and is used in example programs, but not explicitly documented (unlike mbedtls_net_bind).
Since only the official documentation and headers are the contract that developers are expected to adhere to and digging the source to gather information about library behavior might be relying on implementation details, I would like to clarify if mbedtls_net_accept is supposed to accept a NULL client_ip argument.
If passing client_ip=NULL is supported, would you please accept this PR?
=> mbedtls_net_accept: client_ip can be NULL

scripts/generate_errors.pl
Change the script generate_errors.pl to call the grep function in Perl
instead of calling the external tool grep directly as this causes
problems when ANSI escape sequences are included in the grep output
string.
This PR fixes https://github.com/ARMmbed/mbedtls/issues/504 and #1057
READY
The problem is also present in mbedtls-2.1 (see https://github.com/armmbed/mbedtls/blob/mbedtls-2.1/scripts/generate_errors.pl#L49), but this is only a change in one of the tool scripts, so I do not think we should backport it. However, I am happy to do so if necessary.
- [n/a] Tests
- [n/a] Documentation
- [n/a] Changelog updated
- [?] Backported (maybe)
Refer to original issue https://github.com/ARMmbed/mbedtls/issues/504
=> Change generate_errors.pl to call perl grep

ChangeLog, include/mbedtls/net.h
This currently works and is used in example programs, but not explicitly documented (unlike mbedtls_net_bind).
Since only the official documentation and headers are the contract that developers are expected to adhere to and digging the source to gather information about library behavior might be relying on implementation details, I would like to clarify if mbedtls_net_accept is supposed to accept a NULL client_ip argument.
**READY**
This is #758 done against `mbedtls-2.1` branch as requested by @gilles-peskine-arm.
Don't know, but only documentation is modified.
**NO**
None
=> Backport 2.1: mbedtls_net_accept: client_ip can be NULL

ChangeLog, library/Makefile, programs/Makefile, tests/Makefile, tests/scripts/run-test-suites.pl
This PR is a backport of https://github.com/ARMmbed/mbedtls/pull/1499 to Mbed TLS 2.7. Please refer to that PR for details.
**READY**
=> Backport 2.7: Add AR_DASH and make DLEXT variable configurable

ChangeLog, include/mbedtls/ssl.h
Backport of #1539 for 2.7 branch.
=> Backport 2.7: Improve documentation of mbedtls_ssl_write()

ChangeLog, library/cipher.c, tests/suites/test_suite_cipher.aes.data, tests/suites/test_suite_cipher.arc4.data, tests/suites/test_suite_cipher.blowfish.data, tests/suites/test_suite_cipher.camellia.data, tests/suites/test_suite_cipher.des.data, tests/suites/test_suite_cipher.function, tests/suites/test_suite_cipher.gcm.data, tests/suites/test_suite_cipher.null.data
When doing symmetric decryption, the code buffers some output data because it might need to strip the padding later. If there is no padding, this buffering is unnecessary. This patch changes the behavior of `mbedtls_cipher_update` so that as much decrypted data as possible is returned.
This change is submitted under CLA with Fortanix, Inc.
READY
NO
NO
Documentation for `mbedtls_cipher_update` says that “[`output`] should be able to hold at least ilen + block_size.” This patch does not change this requirement.
=> return plaintext data faster on unpadded decryption

ChangeLog, library/Makefile, programs/Makefile, tests/Makefile, tests/scripts/run-test-suites.pl
This PR is a backport of https://github.com/ARMmbed/mbedtls/pull/1499 to Mbed TLS 2.1. Please refer to that PR for details.
**READY**
=> Backport 2.1: Add AR_DASH and make DLEXT variable configurable

ChangeLog, include/mbedtls/ssl.h
Backport of #1539 for 2.1 branch.
=> Backport 2.1: Improve documentation of mbedtls_ssl_write()

ChangeLog, library/cipher.c, tests/suites/test_suite_cipher.aes.data, tests/suites/test_suite_cipher.arc4.data, tests/suites/test_suite_cipher.blowfish.data, tests/suites/test_suite_cipher.camellia.data, tests/suites/test_suite_cipher.des.data, tests/suites/test_suite_cipher.function, tests/suites/test_suite_cipher.gcm.data, tests/suites/test_suite_cipher.null.data
This PR is a backport of #1180 to Mbed TLS 2.1. Please refer to that PR for details.
=> Backport 2.1: return plaintext data faster on unpadded decryption

ChangeLog, include/mbedtls/bignum.h, library/bignum.c
Based on #405 as per https://github.com/ARMmbed/mbedtls/pull/405/files#r176091367 plus a few clarifications in the documentation of the functions.
No backport since this is an enhancement, not a bug fix.
=> Optimize unnecessary zeorizing in mbedtls_mpi_copy

ChangeLog, library/Makefile, programs/Makefile, tests/Makefile, tests/scripts/run-test-suites.pl
This PR makes the following changes to the `library/Makefile`:
1. Allow configuring the DLEXT variable by using the command line instead of having to edit the Makefile itself. This addresses: https://github.com/ARMmbed/mbedtls/issues/1466
2. Allow configuring the prefix operator for the command line arguments for the AR utility. This PR supersedes https://github.com/ARMmbed/mbedtls/pull/706.
**READY**
Yes
Which branch?
Mbed TLS 2.7: https://github.com/ARMmbed/mbedtls/pull/1500
Mbed TLS 2.1: https://github.com/ARMmbed/mbedtls/pull/1501
=> Add AR_DASH and make DLEXT variable configurable

ChangeLog, include/mbedtls/ssl.h
This PR is based on #1370 and aims to clarify the behavior of mbedtls_ssl_write() when MBEDTLS_ERR_SSL_WANT_WRITE is received.
=> Improve documentation of mbedtls_ssl_write()

ChangeLog, library/ssl_tls.c
backport of #1395 to branch 2.7
=> Backport 2.7: Add guard to out_left to avoid negative values

include/mbedtls/rsa_internal.h
Added additional clarification to the use of the rsa_internal.h interface and as and when it can be used by whom. The policy hasn't changed, but it needed to be clearer who can and can't use it and the level of support for the interface by the project.
**READY**
This is the backport.
NO
=> Backport 2.7: Add clarity to use of the rsa_internal.h interface

ChangeLog, library/ssl_tls.c
In `mbedtls_ssl_derive_keys`, don't call `mbedtls_md_hmac_starts` in ciphersuites that don't use HMAC. This doesn't change the behavior of the code, but avoids relying on an uncaught error when attempting to start an HMAC operation that hadn't been initialized.
This is the root cause for #1437, see https://github.com/ARMmbed/mbedtls/pull/1421/files#r175520310. While #1437 could be best resolved as part of #1421, we can make this robustness fix independently, more for documentation than anything else since it doesn't change the behavior.
Backport of #1547
=> Backport 2.7: Robustness fix in mbedtls_ssl_derive_keys

ChangeLog, programs/pkey/pk_sign.c
This PR is a backport of #1142 to Mbed TLS 2.7. Please refer to that PR for details.
=> Backport 2.7: Fix for returning correct error code

tests/compat.sh, tests/ssl-opt.sh
Back port of:
Enable SSL test scripts to dump logs on stdout #1535
=> Backport 2.7: Enable SSL test scripts to dump logs on stdout #1535

ChangeLog, programs/pkey/pk_sign.c
I was receiving "!  Last error was: UNKNOWN ERROR CODE (0001)" during builds.  Looking into it, I found that the return value `ret` is being suppressed by writing 1 to it, causing it to be an unknown error code.  This is not helpful. 
By not overwriting the value of `ret`, the tool should now provide better feedback to developers running into issues.
READY/IN DEVELOPMENT/**HOLD**
Yes | NO  
Which branch?
Provide `mbedtls_pk_parse_keyfile` and invalid DER key …
=> Fix for returning correct error code

ChangeLog, library/ssl_tls.c
Return error when f_send return a value greater than out_left
Fixes #1245 
**READY**
Yes
Which branch?
mbedtls 2.1
mbedtls 2.7
=> Add guard to out_left to avoid negative values

include/mbedtls/rsa_internal.h
Added additional clarification to the use of the rsa_internal.h interface and as and when it can be used by whom. The policy hasn't changed, but it needed to be clearer who can and can't use it and the level of support for the interface by the project.
**READY**
Yes  
Which branch? `mbedtls-2.7`
NO
- [] Backported
=> Add clarity to use of the rsa_internal.h interface

ChangeLog, library/ssl_tls.c
backport of #1395 to branch 2.1
=> Backport 2.1: Add guard to out_left to avoid negative values

ChangeLog, library/ssl_tls.c
In mbedtls_ssl_derive_keys, don't call mbedtls_md_hmac_starts in
ciphersuites that don't use HMAC. This doesn't change the behavior of
the code, but avoids relying on an uncaught error when attempting to
start an HMAC operation that hadn't been initialized.
This is the root cause for #1437, see https://github.com/ARMmbed/mbedtls/pull/1421/files#r175520310. I think #1437 is best resolved as part of #1421, but it's best to backport this robustness fix, more for documentation than anything else since it doesn't change the behavior.
* 2.1: #1461
* 2.7: #1464
* development: best included in #1421
=> Backport 2.1: Robustness fix in mbedtls_ssl_derive_keys

include/mbedtls/ecdsa.h, include/mbedtls/ecp.h, include/mbedtls/pk.h, library/ecdsa.c, library/error.c, library/pk_wrap.c
Backport of #1543, we might as well keep the documentation aligned.
=> Backport 2.1: Clarify the use of MBEDTLS_ERR_PK_SIG_LEN_MISMATCH

tests/compat.sh, tests/ssl-opt.sh
Back port of:
Enable SSL test scripts to dump logs on stdout #1535
=> Backport 2.1: Enable SSL test scripts to dump logs on stdout #1535

ChangeLog, programs/pkey/pk_sign.c
This PR is a backport of #1142 to Mbed TLS 2.1. Please refer to that PR for details.
=> Backport 2.1: Fix for returning correct error code

tests/compat.sh, tests/ssl-opt.sh
This PR changes ```ssl-opts.sh``` and ```compat.sh``` to dump logs in ```stdout``` if ```LOG_FAILURE_ON_STDOUT``` is set.
It partly implements IOTSSL-1957.
=> Enable SSL test scripts to dump logs on stdout

include/mbedtls/ecdsa.h, include/mbedtls/ecp.h, include/mbedtls/pk.h, library/ecdsa.c, library/error.c, library/pk_wrap.c
Clarify what MBEDTLS_ERR_ECP_SIG_LEN_MISMATCH and
MBEDTLS_ERR_PK_SIG_LEN_MISMATCH mean. Add comments to highlight that
this indicates that a valid signature is present, unlike other error
codes. See
https://github.com/ARMmbed/mbedtls/pull/1149#discussion_r178130705
=> Clarify the use of MBEDTLS_ERR_PK_SIG_LEN_MISMATCH

ChangeLog, library/ssl_tls.c
In `mbedtls_ssl_derive_keys`, don't call `mbedtls_md_hmac_starts` in ciphersuites that don't use HMAC. This doesn't change the behavior of the code, but avoids relying on an uncaught error when attempting to start an HMAC operation that hadn't been initialized.
This is the root cause for #1437, see https://github.com/ARMmbed/mbedtls/pull/1421/files#r175520310. While #1437 could be best resolved as part of #1421, we can make this robustness fix independently, more for documentation than anything else since it doesn't change the behavior.
* Backport 2.1: #1461
* Backport 2.7: #1464
* A similar fix was contributed independently in #1377.
Fixes #1437
=>  Robustness fix in mbedtls_ssl_derive_keys

library/net_sockets.c
Clang-MSan does not recognize that `FD_ZERO(fdset)` initializes `fdset` on Glibc/x86_64 (because it's implemented in assembly). This can lead to false-positive reports of uninitialized memory. In #946 (https://github.com/ARMmbed/mbedtls/pull/946/commits/f4e5b7e87de2484f0e3dbb9d11e87dd275874cd0) this was resolved by adding a `memset` call before the call to `FD_ZERO`.
This PR makes the `memset` code conditional on using Msan, to save a bit of code size and time in production.
=> Make the memset call prior to FD_ZERO conditional to needing it

library/aesni.c
Clang-Msan is known to report spurious errors when MBEDTLS_AESNI_C is
enabled (which is the case in the default configuration), due to the use of assembly code. The error reports don't
mention AES, so they can be difficult to trace back to the use of
AES-NI. Warn about this potential problem at compile time.
This would make sense in backports too, but it has a risk of breaking somebody's build, so I lean towards not backporting.
=> Warn if using a memory sanitizer on AESNI

doxygen/mbedtls.doxyfile
We don't use symbolic links as part of our build process, so tell
Doxygen not to traverse them. In particular, if I have a symbolic link
to a directory outside the build tree, I don't want Doxygen to follow
it.
Backports: should be applied identically to all versions.
=> Doxygen: don't traverse symbolic links

ChangeLog, library/bignum.c, library/rsa.c, tests/suites/test_suite_mpi.data
This PR makes several security enhancements to RSA key generation. The enhancements also make mbedTLS's RSA implementation compliant with FIPS 186-4. It's not clear to me if it's a goal for mbedTLS to be compliant, but considering all the self-tests are clearly implemented according to FIPS, I'm assuming it is. Some of the improvements are useful outside of FIPS 186-4, though.
The enhancements don't touch primality testing, which is the most time-consuming part of RSA key generation. Therefore, I expect the performance impact to be minimal.
The changes are:
* Avoid small private exponents during RSA key generation
* Generate primes according to FIPS 186-4
* Generate RSA keys according to FIPS 186-4
See the individual commit messages for detailed information on each change.
This …
=> RSA key generation security improvements

doxygen/mbedtls.doxyfile
We don't use symbolic links as part of our build process, so tell
Doxygen not to traverse them. In particular, if I have a symbolic link
to a directory outside the build tree, I don't want Doxygen to follow
it.
Backport of #1234
=> Backport 2.1: Doxygen: don't traverse symbolic links

ChangeLog, tests/suites/helpers.function, tests/suites/main_test.function
This PR adds platform setup and teardown calls to test suites and a global platform context object.
This enables running tests on custom targets requiring an additional setup, and is a step towards accessing the platform context in test suites which will need it.
=> Platform setup and teardown calls addition to test suites

ChangeLog, library/ssl_tls.c
This PR fixes the sizes of available buffers passed to zlib by reducing them by an amount of already written bytes.
More information available in IOTSSL-1401.
=> Fix invalid buffer sizes during compression / decompression

ChangeLog, library/ssl_tls.c
=> Backport 2.1: Fix invalid buffer sizes during compression / decompression

ChangeLog, library/ssl_tls.c
=> Backport 2.7: Fix invalid buffer sizes during compression / decompression

scripts/output_env.sh, tests/scripts/all.sh
In `all.sh`, support `--no-foo` to negate `--foo` and vice versa. This makes it easier to write wrapper scripts.
Backports: #1487 #1488
=> all.sh dual boolean options

include/mbedtls/platform.h
platform.h defines MBEDTLS_PLATFORM_STD_SNPRINTF based on _WIN32. But while defining macro mbedtls_snprintf it sets it to STD C snprintf that is deprecated on Windows.
=> Use correct version of snprintf on Windows

tests/scripts/all.sh
In `all.sh`, support `--no-foo` to negate `--foo` and vice versa. This makes it easier to write wrapper scripts.
Backport of #1486. Also accept and ignore a few options that aren't relevant to 2.1, to make it easier to write version-independent wrapper scripts and CI jobs.
=> Backport 2.1: all.sh dual boolean options

include/mbedtls/platform.h
=> Backport 2.1: Use correct version of snprintf on Windows

scripts/output_env.sh, tests/scripts/all.sh
In `all.sh`, support `--no-foo` to negate `--foo` and vice versa. This makes it easier to write wrapper scripts.
Backport of #1486
=> Backport 2.7: All.sh dual boolean options

scripts/abi_check.py
This script is a wrapper around the abi-dumper and abi-compliance-checker tools to easily check ABI/API compatibility between two git references of the Mbed TLS library.
**READY**
NO  
This script cannot be used for Windows compatibility testing due to limitations with abi-dumper.
=> Add script for ABI compatibility checking

ChangeLog, library/memory_buffer_alloc.c
=> Backport 2.1: Fix braces in mbedtls_memory_buffer_alloc_status()

ChangeLog, include/mbedtls/config.h, include/mbedtls/x509_crt.h, library/x509_crt.c
Allow the size of the entry_name character array in `x509_crt.c` to be configurable through a macro in `config.h`. entry_name holds a path/filename string. The macro introduced in `MBEDTLS_X509_MAX_FILE_PATH_LEN`.
This addresses issue #492, and is a backport of #592 to `mbedtls-2.1` to address issue #1188.
**READY**
NO
=> Backport 2.1: Allow the entry_name size to be set in config.h

ChangeLog, include/mbedtls/ssl.h
Remove double declaration of mbedtls_ssl_list_ciphersuites.
Fixes  #1359 
Internal ref: IOTSSL-2091
**READY**
Yes 
Which branch?
mbedtls 2.1
mbedtls 2.7
=> Redundant declaration of mbedtls_ssl_list_ciphersuites

CMakeLists.txt, ChangeLog, include/CMakeLists.txt, tests/CMakeLists.txt, tests/scripts/all.sh
Support SSL testing in out-of-tree builds with CMake. This requires creating some extra symbolic links. Validate that this works in `all.sh`.
Note that the out-of-tree build uses `config.h` from the original source directory, so you can do multiple out-of-tree builds with different toolchains or targets, but not with different configurations. Supporting different configurations in different build directories would be a logical follow-up but is out of scope of this PR.
Fixes #1193 
This PR can be merged into both `development` and `mbedtls-2.7`. Backport for 2.1: #1465
=> Support out-of-tree testing with cmake

ChangeLog, include/mbedtls/ssl.h
backport of #1402 to branch 2.7
=> Backport 2.7: Redundant declaration of mbedtls_ssl_list_ciphersuites

ChangeLog, include/mbedtls/ssl.h
backport of #1402 to branch 2.1
=> Backport 2.1: Redundant declaration of mbedtls_ssl_list_ciphersuites

configs/config-no-entropy.h
This PR introduces a commented out CMAC option in the no-entropy configuration file.
This option is needed downstream in the cases when the option needs to be enabled automatically also in the no entropy variant.
**READY**
NO  
NO
None
None
=> Add a disabled CMAC define in the no-entropy configuration

ChangeLog, doxygen/input/doc_mainpage.h, doxygen/mbedtls.doxyfile, include/mbedtls/version.h, library/CMakeLists.txt, tests/suites/test_suite_version.data
Update the version number of the library on the `development` branch to 2.10.0 ready for release.
**READY**
NO  
This release will go into Mbed OS 5.9, and will not be released as a normal Mbed TLS release.
=> Updated version number to 2.10.0 for release

CMakeLists.txt
Some of the symlinks in PR #1470 were being accidentally created as directory symlinks on Windows, this adds a check to create the symlink of the correct type. 
Backports will be needed for 2.7 and 2.1
=> Fix out-of-tree testing symlinks on Windows

programs/x509/cert_write.c
use mbedtls_pk_check_pair to verify if issuer certificate and issuer key match,
instead of explicitly comparing RSA public component.
Raised and fix suggested by dbedev in #777
=> check matching issuer crt and key for all algs

CMakeLists.txt, include/mbedtls/ssl_internal.h, library/asn1write.c, library/pkcs5.c
Treat warnings as errors for IAR in cmake build. Changes made on lines of ```MSVC``` as both are different from ```clang``` and ```gcc``` and can not perform ```ASan, MemSan``` etc.
=> Treat warnings as errors for IAR

include/mbedtls/gcm.h
* Warn that `mbedtls_gcm_crypt_and_tag` in decrypt mode does not authenticate the data and recommend using `mbedtls_gcm_auth_decrypt` instead. This was my original motivation for the PR.
* Remove an incorrect statement about input size restrictions that was added shortly before 2.7 due to overeager copy-pasting.
* Other clarifications and precisions about parameters and errors.
Backports: #1670 , #1671
=> Correct and clarify the documentation of GCM whole-message functions

programs/test/zeroize.c
Coverity reported error in line ```while( ( c = fgetc( fp ) ) != EOF && p < end - 1 )```:
```
>*** CID 278842:  API usage errors  (CHAR_IO)
>/programs/test/zeroize.c: 85 in main()
>79         if( fp == NULL )
>80         {
>81             mbedtls_printf( "Could not open file '%s'\n", argv[1] );
>82             return( exit_code );
>83         }
>84     
>>>>     CID 278842:  API usage errors  (CHAR_IO)
>>>>     Assigning the return value of "fgetc" to char "c" truncates its
>>>>value.
>85         while( ( c = fgetc( fp ) ) != EOF && p < end - 1 )
>86             *p++ = c;
>87         *p = '\0';
>88     
>89         if( p - buf != 0 )
>90         {
```
It is clear that check ```!= EOF``` will not work as the ```int``` return is first truncated and then compared to ```EOF```.
=> Fix coverity defects

CMakeLists.txt, include/mbedtls/ssl_internal.h, library/asn1write.c, library/pkcs5.c
Backport of: Treat warnings as errors for IAR #1646
=> Backport 2.7: Treat warnings as errors for IAR

include/mbedtls/gcm.h
* Warn that `mbedtls_gcm_crypt_and_tag` in decrypt mode does not authenticate the data and recommend using `mbedtls_gcm_auth_decrypt` instead. This was my original motivation for the PR.
* Remove an incorrect statement about input size restrictions that was added shortly before 2.7 due to overeager copy-pasting.
* Other clarifications and precisions about parameters and errors.
Backport of #1668
=> Backport 2.7: Correct and clarify the documentation of GCM whole-message functions

.travis.yml, tests/git-scripts/pre-push.sh, tests/scripts/all.sh, tests/scripts/check-files.py
This is a backport of #1434, 'Add script for source integrity checking'.
The script introduces checks to qualify the quality of the source code, and confirm common mistakes and errors aren't present, such as incorrect newlines, file permissions, trailing whitespace etc.
This PR does not change or impact the library and is just another test for maintenance.
**READY**
=> Backport 2.7: Add script for source integrity checking

include/mbedtls/gcm.h
* Warn that `mbedtls_gcm_crypt_and_tag` in decrypt mode does not authenticate the data and recommend using `mbedtls_gcm_auth_decrypt` instead. This was my original motivation for the PR.
* Other clarifications and precisions about parameters and errors.
Backport of #1668
=> Backport 2.1: Correct and clarify the documentation of GCM whole-message functions

ChangeLog, library/memory_buffer_alloc.c
IOTSSL-960: This is a code style fix for braces in mbedtls_memory_buffer_alloc_status.
=> Fix braces in mbedtls_memory_buffer_alloc_status()

library/net_sockets.c
**READY**
Yes (bugfix)
Which branch?
`mbedtls-2.7`, `mbedtls-2.8` (why is it not branched yet?!)
NO
`net_sockets.c` was redefining the `_WIN32_WINNT` to ensure `getaddrinfo()` and the like to work.
This should only be done when `_WIN32_WINNT < 0x0501` or it might break builds when embedding in projects that require higher `_WIN32_WINNT` minimum version.
=> Only redefine _WIN32_WINNT macro when < 0x0501

library/entropy_poll.c
When `MBEDTLS_TIMING_C` was not defined in config.h, but the MemSan
memory sanitizer was activated, `entropy_poll.c` used `memset` without
declaring it. Fix this by including `string.h` unconditionally.
This PR should be merged into development and mbedtls-2.7. Backport to 2.1: #1673
=> Fix MSan build without MBEDTLS_TIMING_C

library/aes.c
The AES OFB self-test made use of a variable `offset` but failed to have a preprocessor condition around it, so unless CTR and CBC were enabled, the variable would be undeclared.
**READY**
NO  
OFB is not present in the maintained branches.
=> Fix missing preprocessor condition in AES self-test

ChangeLog, library/memory_buffer_alloc.c
=> Backport 2.7: Fix braces in mbedtls_memory_buffer_alloc_status()

tests/ssl-opt.sh
This PR is a backport for https://github.com/ARMmbed/mbedtls/pull/710. It reproduces the original SNI tests in ssl-opt.sh but using DTLS instead.
The change is related to IOTSSL-1114.
**READY**
=> Backport 2.7: Add SNI with DTLS tests to ssl-opt.sh script

ChangeLog, library/net_sockets.c
This is a backport of #1555.
`net_sockets.c` was redefining the `_WIN32_WINNT` to ensure `getaddrinfo()` and the like to work.
This should only be done when `_WIN32_WINNT < 0x0501` or it might break builds when embedding in projects that require higher `_WIN32_WINNT` minimum version.
**READY**
=> Backport 2.7: Only redefine _WIN32_WINNT macro when < 0x0501

ChangeLog, library/ssl_srv.c
This PR fixes a compilation warning with the IAR toolchain, on 32 bit platforms, originally reported by rahmanih in #683.
This is based on work by Ron Eldor in PR #750, some of which was independently fixed by Azim Khan and already merged in PR #1646.
This PR adds the missing fix, and corrects the ChangeLog.
This is a backport of PR #1727.
**READY**
=> Backport 2.7: Compilation warning fix on 32-bit platform with IAR

tests/ssl-opt.sh
This PR adds 3 tests for SNI with DTLS to the script ssl-opt.sh.
The change is related to IOTSSL-1114.
=> Add SNI with DTLS tests to ssl-opt.sh script

include/mbedtls/platform.h, library/platform.c
When MBEDTLS_PLATFORM_MEMORY is defined but MBEDTLS_PLATFORM_FREE_MACRO
or MBEDTLS_PLATFORM_CALLOC_MACRO are not defined then the actual functions
used to allocate and free memory are stored in function pointers.
These pointers are exposed to the caller, and it means that the caller
and the library have to share a data section. These function pointer
interfaces make it difficult to share the mbedtls library between images
that access the mbedtls functions using jump tables and they don't share
the data section.
READY
This PR is a new feature\enhancement
NO
=> Convert mbedtls_free and mbedtls_calloc into functions

ChangeLog, library/ssl_srv.c
This PR fixes a compilation warning with the IAR toolchain, on 32 bit platforms, originally reported by rahmanih in #683.
This is based on work by Ron Eldor in PR #750, some of which was independently fixed by Azim Khan and already merged in PR #1646.
This PR adds the missing fix, and corrects the ChangeLog.
**READY**
Yes  
Which branch?
`mbedtls-2.7`
=> Compilation warning fix on 32-bit platform with IAR

include/mbedtls/config.h, tests/scripts/all.sh
This reverts commit 5ffe41c8f9e53ddde74e63d58bd05fb5e67abca0.
Turn off MBEDTLS_SSL_ASYNC_PRIVATE by default because we don't want to
change the ABI yet.
**READY**
=> Revert "Turn on MBEDTLS_SSL_ASYNC_PRIVATE by default"

library/aes.c
The AES XTS self-test was using a variable len, which was declared only when CTR
was enabled. Changed the declaration of len to be conditional on CTR and XTS.
**READY**
NO
=> Fix for undeclared len variable used in AES-XTS self-test

CMakeLists.txt, ChangeLog, include/mbedtls/ssl_internal.h, library/pkcs5.c, library/ssl_cli.c, library/ssl_srv.c
Backport of: Treat warnings as errors for IAR #1646
=> Backport 2.1: Treat warnings as errors for IAR

tests/ssl-opt.sh
This PR is a backport for https://github.com/ARMmbed/mbedtls/pull/710. It reproduces the original SNI tests in ssl-opt.sh but using DTLS instead.
The change is related to IOTSSL-1114.
**READY**
=> Backport 2.1: Add SNI with DTLS tests to ssl-opt.sh script

library/entropy_poll.c
When `MBEDTLS_TIMING_C` was not defined in config.h, but the MemSan
memory sanitizer was activated, `entropy_poll.c` used `memset` without
declaring it. Fix this by including `string.h` unconditionally.
Backport of #1672
=> Backport 2.1: Fix MSan build without MBEDTLS_TIMING_C

ChangeLog, library/net.c
This is a backport of #1555.
`net_sockets.c` was redefining the `_WIN32_WINNT` to ensure `getaddrinfo()` and the like to work.
This should only be done when `_WIN32_WINNT < 0x0501` or it might break builds when embedding in projects that require higher `_WIN32_WINNT` minimum version.
**READY**
=> Backport 2.1: Only redefine _WIN32_WINNT macro when < 0x0501

ChangeLog, scripts/config.pl, scripts/generate_errors.pl, scripts/generate_features.pl, scripts/generate_visualc_files.pl, scripts/massif_max.pl, scripts/rename.pl, tests/scripts/check-doxy-blocks.pl, tests/scripts/curves.pl, tests/scripts/depends-hashes.pl, tests/scripts/depends-pkalgs.pl, tests/scripts/gen_ctr_drbg.pl, tests/scripts/gen_gcm_decrypt.pl, tests/scripts/gen_gcm_encrypt.pl, tests/scripts/gen_pkcs1_v21_sign_verify.pl, tests/scripts/key-exchanges.pl, tests/scripts/list-enum-consts.pl, tests/scripts/recursion.pl, tests/scripts/run-test-suites.pl, tests/scripts/test-ref-configs.pl
Some exotic operating systems have perl in another directory than `/usr/bin/`.
~I don't really have the time to read the contributor agreement for such a trivial change, so~ please feel free to change the authorship of this commit or close this PR and make the change directly.
Of course, in case you merge this commit, I won't ever claim any rights. (That would be ridiculous, btw :)
Thanks!
BTW, three perl scripts already have the prefered shebang line:
```
tests/data_files/print_c.pl
tests/scripts/generate_code.pl
tests/scripts/tcp_client.pl
```
While these have `#!/usr/bin/perl`:
```
scripts/config.pl
scripts/generate_errors.pl
scripts/generate_features.pl
scripts/generate_visualc_files.pl
scripts/massif_max.pl
scripts/rename.pl
tests/scripts/check-doxy-blocks.pl
tests/scripts/curves.pl …
```
=> Use "#!/usr/bin/env perl" as shebang line.

ChangeLog, scripts/config.pl, scripts/generate_errors.pl, scripts/generate_features.pl, scripts/generate_visualc_files.pl, scripts/massif_max.pl, scripts/rename.pl, tests/scripts/check-doxy-blocks.pl, tests/scripts/curves.pl, tests/scripts/depends-hashes.pl, tests/scripts/depends-pkalgs.pl, tests/scripts/gen_ctr_drbg.pl, tests/scripts/gen_gcm_decrypt.pl, tests/scripts/gen_gcm_encrypt.pl, tests/scripts/gen_pkcs1_v21_sign_verify.pl, tests/scripts/key-exchanges.pl, tests/scripts/list-enum-consts.pl, tests/scripts/recursion.pl, tests/scripts/run-test-suites.pl, tests/scripts/test-ref-configs.pl
Backport of #1533 for 2.7 branch.
=> Backport 2.7: Use "#!/usr/bin/env perl" as shebang line.

ChangeLog, include/mbedtls/ssl.h, library/ssl_tls.c
This patch modifies the documentation for mbedtls_ssl_write() to allow
0 as a valid return value as this is the correct number of bytes that
should be returned when an empty TLS Application record is sent.
This is a backport for https://github.com/ARMmbed/mbedtls/pull/1006
=> Backport 2.7: Allow 0 as a valid ret value for mbedtls_ssl_write

ChangeLog, library/x509_csr.c
Fixes a memory leak in `mbedtls_x509_csr_parse()`.
This is a backport to `mbedtls-2.7` of PR #1621.
**READY**
=> Backport 2.7: Fix memory leak in mbedtls_x509_csr_parse

tests/scripts/all.sh
Backport of the test added in #1390. The corresponding issue does not apply to 2.1.
There is no bug to fix in 2.1 but I am backporting to keep the tests aligned.
=> 2.1 only: all.sh: add test with MBEDTLS_DEPRECATED_REMOVED

ChangeLog, scripts/config.pl, scripts/generate_errors.pl, scripts/generate_features.pl, scripts/generate_visualc_files.pl, scripts/massif_max.pl, scripts/rename.pl, tests/scripts/check-doxy-blocks.pl, tests/scripts/curves.pl, tests/scripts/depends-hashes.pl, tests/scripts/depends-pkalgs.pl, tests/scripts/gen_ctr_drbg.pl, tests/scripts/gen_gcm_decrypt.pl, tests/scripts/gen_gcm_encrypt.pl, tests/scripts/gen_pkcs1_v21_sign_verify.pl, tests/scripts/key-exchanges.pl, tests/scripts/list-enum-consts.pl, tests/scripts/recursion.pl, tests/scripts/run-test-suites.pl, tests/scripts/test-ref-configs.pl
Backport of #1533 for 2.1 branch.
=> Backport 2.1: Use "#!/usr/bin/env perl" as shebang line.

ChangeLog, include/mbedtls/ssl.h, library/ssl_tls.c
This patch modifies the documentation for mbedtls_ssl_write() to allow
0 as a valid return value as this is the correct number of bytes that
should be returned when an empty TLS Application record is sent.
This is a backport for #1006
=> Backport 2.1: Allow 0 as a valid ret value for mbedtls_ssl_write

ChangeLog, library/x509_csr.c
Fixes a memory leak in `mbedtls_x509_csr_parse()`.
This is a backport to `mbedtls-2.1` of PR #1621.
**READY**
=> Backport 2.1: Fix memory leak in mbedtls_x509_csr_parse

ChangeLog, include/mbedtls/ssl.h, library/ssl_tls.c
This patch modifies the documentation for mbedtls_ssl_write() to allow
0 as a valid return value as this is the correct number of bytes that
should be returned when an empty TLS Application record is sent.
**NOTES:**
* This fix is related to https://github.com/ARMmbed/mbedtls/issues/839
* The change needs to be backported to mbed TLS 2.7 and 2.1.
=> Allow 0 as a valid ret value for mbedtls_ssl_write

programs/pkey/key_app_writer.c
The key_app writer writes wrong public key, in der format.
The reason is a leading zero byte, which is not a valid ASN1 tag
Fixes #1257 
**READY**
NO  
This is only in a sample application
- Generate a key pair
- use `key_app_writer` to write a public key in der format
- try parsing the public key
~~~
./gen_key type=rsa rsa_keysize=4096 filename=rsa_4096_private.der format=der
./key_app_writer mode=private filename=rsa_4096_private.der output_mode=public output_format=der output_file=rsa_4096_public.der
./key_app mode=public filename=rsa_4096_public.der
~~~
=> remove additional zero byte when writing pub der

library/x509_csr.c
Fix memory leak in mbedtls_x509_csr_parse
READY
Yes
Which branch? I did not check
No
Found using oss-fuzz
Allocated memory in previous call to mbedtls_pem_read_buffer does not get freed without this patch
=> Fix memory leak in mbedtls_x509_csr_parse

ChangeLog, library/ssl_tls.c
Based on issue #1782 
Replace ```*new``` to ```*new_cert``` in ```ssl_append_key_cert``` function at ```ssl_tls.c```.
READY
NO
NO
=> Renaming "new" variable

programs/pkey/key_app_writer.c
Backport of #1258 to mbedtls-2.7
**READY**
=> Backport 2.7: remove additional zero byte when writing pub der

.travis.yml, tests/scripts/all.sh, tests/scripts/check-files.py
This is a backport of #1434, 'Add script for source integrity checking'.
The script introduces checks to qualify the quality of the source code, and confirm common mistakes and errors aren't present, such as incorrect newlines, file permissions, trailing whitespace etc.
This PR does not change or impact the library and is just another test for maintenance.
**READY**
=> Backport 2.1: Add script for source integrity checking

programs/pkey/key_app_writer.c
Backport of #1258 to mbedtls-2.1
**READY**
=> Backport 2.1: remove additional zero byte when writing pub der

ChangeLog, library/x509.c
Notes:
**DONE**: username is `bkshanks`
- The PR follows the [mbed TLS coding standards](https://tls.mbed.org/kb/development/mbedtls-coding-standards)
x509.c: Remove unused includes guarded by MBEDTLS_FS_IO, which doesn't appear
anywhere else in the file. Part of a fix for #992 
**READY** …
=> x509.c: Remove unused includes

ChangeLog, include/mbedtls/cipher.h, include/mbedtls/cipher_internal.h, library/cipher.c
fix compilation error when ARC4 not MBEDTLS_CIPHER_NULL_CIPHER defined.
`MBEDTLS_CIPHER_MODE_STREAM` was defined in `cipher.c`, but it is already used in `cipher_internal.h`
resolves #1719 
**READY**
Yes   
Which branch?
mbedtls-2.1
mbedtls-2.7
NO
=> fix compilation error when MBEDTLS_CIPHER_NULL_CIPHER defined

tests/ssl-opt.sh
Fix #1536 
Backports: #1822 #1823
=> Fix ssl-opt.sh not starting when lsof is not available

ChangeLog, include/mbedtls/cipher.h, include/mbedtls/cipher_internal.h, library/cipher.c
Backport of #1737 to mbedtls-2.7
**READY**
=> Backport 2.7: fix compilation error when MBEDTLS_CIPHER_NULL_CIPHER defined

ChangeLog, library/ssl_tls.c
Backport of #1783 to `mbedtls-2.7`.
Renames a variable called `new` to `new_cert` to avoid using a C++ keyword.
Fixes issue #1782.
**READY**
=> Backport 2.7: Renaming "new" variable

tests/ssl-opt.sh
=> Backport 2.7: Fix ssl-opt.sh not starting when lsof is not available

ChangeLog, library/x509.c
This is a backport of #1563, which is part of a fix for #992.
The PR removes unused headers included in x509.c, guarded by MBEDTLS_FS_IO, which doesn't appear anywhere else in the file. 
**READY**
=> Backport 2.7: x509.c: Remove unused includes 

ChangeLog, library/ssl_cli.c, library/ssl_srv.c, library/ssl_tls.c
Fixes different off by one overreads
**READY**
I guess so
Which branch? do not know
NO
These do not seem security issues as the orignal buffer is overgrown.
But they are bad coding practices, and the checks are already performed most of the times.
Some previously similar bugs from the ones reported by mail have already been corrected like 
https://github.com/ARMmbed/mbedtls/commit/740b218386083dc708ce98ccc94a63a95cd5629e
=> Fixes different off by ones

ChangeLog, include/mbedtls/bn_mul.h
This is a fix for GitHub issue #1550.
The `ebx` register was used by the assembly code but not listed in the clobber list, so when the compiler chose to also use it, `ebx` was getting corrupted. I'm surprised this wasn't spotted sooner.
The fix is very simply to add the `ebx` register to the clobber list for the i386 inline assembly
for the multiply helper function.
This fixes both i386 and its SSE2 variant which was also broken.
**READY**
Yes
Which branch?
`mbedtls-2.1` and `mbedtls-2.7`. I'll backport once this one's been approved.
This should have been caught by the CI, so I suggest `all.sh` needs to be extended. (I haven't checked where or how yet).
=> Fix the i386 MPI multiply helper assembly code

ChangeLog, library/ssl_cli.c, library/ssl_srv.c, library/ssl_tls.c
Fixes different off by one overreads
This is a backport to `mbedtls-2.7` of PR #1663.
**READY**
=> Backport 2.7: Fixes different off by ones

ChangeLog, include/mbedtls/bn_mul.h
This is a backport of #1778 to the `mbedtls-2.7` branch, to fix GitHub issue #1550.
The ebx register was used by the assembly code but not listed in the clobber list, so when the compiler chose to also use it, ebx was getting corrupted. I'm surprised this wasn't spotted sooner.
The fix is very simply to add the ebx register to the clobber list for the i386 inline assembly
for the multiply helper function.
This fixes both i386 and its SSE2 variant which was also broken.
**READY**
=> Backport 2.7: Fix the i386 MPI multiply helper assembly code

ChangeLog, library/ssl_cli.c, library/ssl_srv.c, library/ssl_tls.c
Fixes different off by one overreads
This is a backport to `mbedtls-2.1` of PR #1663.
**READY**
=> Backport 2.1: Fixes different off by ones

ChangeLog, include/mbedtls/bn_mul.h
This is a backport of #1778 to the `mbedtls-2.1` branch, to fix GitHub issue #1550.
The ebx register was used by the assembly code but not listed in the clobber list, so when the compiler chose to also use it, ebx was getting corrupted. I'm surprised this wasn't spotted sooner.
The fix is very simply to add the ebx register to the clobber list for the i386 inline assembly
for the multiply helper function.
This fixes both i386 and its SSE2 variant which was also broken.
**READY**
=> Backport 2.1: Fix the i386 MPI multiply helper assembly code

tests/scripts/all.sh
Fix the all.sh testing script so that it fails when full executable paths of tools are not valid.
=> Fix all.sh check_tools function to handle paths

ChangeLog, include/mbedtls/ssl.h
Fix Documentation error in `mbedtls_ssl_get_session`.
This function supports deep copying of the session,
and the peer certificate is not lost anymore, Resolves #926
=> Documentation error in `mbedtls_ssl_get_session`

ChangeLog, include/mbedtls/threading.h, library/entropy_poll.c, library/net_sockets.c, library/threading.c, library/x509.c, programs/aes/aescrypt2.c, programs/aes/crypt_and_hash.c, programs/ssl/ssl_mail_client.c, tests/CMakeLists.txt, tests/Makefile, tests/suites/helpers.function
This PR fixes a couple of issues:
* mbedTLS should not be calling gmtime_r. Even with a mutex, the call is simply unsafe (other threads in the application could be calling it, obviously without holding mbedTLS's mutex). It's simply not appropriate to be using non-thread-safe APIs in a security library.
* On Windows, the `mbedtls_time` platform abstraction does not work, because for some reason the `time()` API is not used on Windows? I can't think of any reason not to use it, the Windows time implementation ought to go through the same platform abstraction layer as any other feature.
* The second commit fixes the build with `-std=c99`. There are a couple of existing places in the code where this is broken, plus `gmtime_r` adds another one.
Issue: …
=> gmtime_r and mbedtls_time on Windows

tests/scripts/all.sh
The main goal of this patch is to fix the problem reported in #1723. Namely, that GDB does not return a failure code to the system when the command script passed to it fails to complete successfully. Instead of relying on GDB, this change dumps the GDB output to a file and uses grep to scan the output for success and failure strings.
This patch also integrates the zeroize test in all.sh with the --keep-going option. It fixes the following two problems:
* The zeroize test would cause all.sh to exit even if --keep-going was set
* When --keep-going was set, the `make` command was overridden to call a shell function before invoking make. This would cause some options to make to be discarded and the library for the zeroize test would be compiled without symbols, which causes a failure in the …
=> Reliably detect GDB script failures in all.sh for zeroize test.

include/mbedtls/bn_mul.h, tests/scripts/all.sh
The i386 test builds were only building the default configuration and had no address sanitisation. This pull request expands the test configuration to the full configuration in `all.sh` and generates ASan builds for test suite execution.
This pull request extends test coverage sufficiently that issue #1550, where the MPI assembly code on i386 which was fundamentally broken, would have been caught.
It also fixes the inline assembly which was previously only being included in builds with no optimisation, which was the opposite of what it should have been doing.
Once reviewed, this PR needs backporting.
**READY**
Yes
Which branch?
`mbedtls-2.7` and `mbedtls-2.1`
=> Expand i386 all.sh tests to include full configuration ASan builds

CONTRIBUTING.md, README.md
The `CONTRIBUTING.md` file referred to 'legacy' branches instead of LTS branches, and also referenced `mbedtls-1.3` which is no longer maintained, and omitted `mbedtls-2.7` which is.
This PR updates the language and also removed the `mbedtls-1.3` reference.
**READY**
NO
=> Update the CONTRIBUTING.md file for LTS branches

ChangeLog, library/hkdf.c
There was an ugly merge PR #1781. I don't like rewriting history, so I'm opening a duplicate PR with a clean commit log.
The changes are the same as in #1781. I updated `mbedtls_hkdf_extract()` to return an error when calling with a NULL salt and non-zero `salt_len`. I also made some minor improvements to the comments.
=> Minor HKDF changes (2)

ChangeLog, library/ssl_tls.c, programs/ssl/ssl_client2.c, tests/ssl-opt.sh
This patch addresses https://github.com/ARMmbed/mbedtls/issues/1833.
It fixes the ssl_client2 application so that its implementation matches the documentation and it can send empty application data records. It also adds 4 tests to ssl-opt.sh (2 with TLS and 2 with DTLS) for checking empty application data records.
**NOTE:** Two of the tests fail at the moment until https://github.com/ARMmbed/mbedtls/pull/1835 is merged
**READY**
Yes
Mbed TLS 2.1 and 2.7
=> Fix sending empty application data records in ssl_client2

ChangeLog, library/pkparse.c
`ret` is used always at line 1305 in statement:
`if( ( ret = pk_parse_key_pkcs8_unencrypted_der( pk, key, keylen ) ) == 0 )`
READY
NO
NO
=> Remove unnecessary mark as unused #1098

include/mbedtls/net_sockets.h
The purpose of the networking module can sometimes be misunderstood. This adds a definition and explanation of what the networking module is and what it can be used for.
This PR changes the doxygen documentation only. 
**READY**
NO  
Whilst the change only clarifies the purpose of the networking module, it is restrictive, and it seems unnecessary to retrospectively say what the module can or can't be used for on maintained branches.
=> Add to the networking module header a definition of the purpose and use of the module

tests/scripts/all.sh
When calling all.sh from a script and using "--keep-going", errors were
sometimes missed due to all.sh always returning 0 "success" return
code. Return 1 if there is any failure encountered during a "keep-going"
run.
**READY**
Testing done: ran `all.sh` with two failures. Then, did `echo $?` and got `1` (error) back.
Yes
=> all.sh: Return error on keep-going failure

programs/ssl/ssl_server2.c
This pull request fixes issue #1874.
Newer features in the library have increased the overall RAM usage of the library, when all features are enabled. `ssl_server2.c`, with all features enabled was running out of memory for the `ssl-opt.sh` test 'Authentication: client max_int chain, server required'.
This commit increases the memory buffer allocation for `ssl_server2.c` to allow the test to work with all features enabled.
**READY**
NO  
The memory allocation was big enough for all tests in `mbedtls-2.11.0` and previous releases.
=> Increase the memory buffer size for ssl_server2.c

ChangeLog, include/mbedtls/ssl.h
Backport of #927 to mbedtls-2.7
**READY**
=> Backport 2.7: Documentation error in `mbedtls_ssl_get_session`

ChangeLog, library/ssl_tls.c, programs/ssl/ssl_client2.c, tests/ssl-opt.sh
This is a backport of https://github.com/ARMmbed/mbedtls/pull/1852 and https://github.com/ARMmbed/mbedtls/pull/1835. The first is a change in ssl_client2 and ssl-opt.sh to add tests for sending empty application data records, while the changes in the second PR fix some issues with this functionality.
**READY**
=> Backport 2.7: Fix sending empty application data records in ssl_client2

ChangeLog, library/pkparse.c
=> Backport 2.7: Remove unnecessary mark as unused #1098 (backport)

include/mbedtls/bn_mul.h, tests/scripts/all.sh
This is a backport of PR #1810.
The i386 test builds were only building the default configuration and had no address sanitisation. This pull request expands the test configuration to the full configuration in all.sh and generates ASan builds for test suite execution.
This pull request extends test coverage sufficiently that issue #1550, where the MPI assembly code on i386 which was fundamentally broken, would have been caught.
It also fixes the inline assembly which was previously only being included in builds with no optimisation, which was the opposite of what it should have been doing.
**READY**
=> Backport 2.7: Expand i386 all.sh tests to include full configuration ASan builds

tests/scripts/all.sh
When calling all.sh from a script and using "--keep-going", errors were
sometimes missed due to all.sh always returning 0 "success" return code.
Return 1 if there is any failure encountered during a "keep-going" run.
Backport of #1871
=> Backport 2.7: all.sh: Return error on keep-going failure

ChangeLog, include/mbedtls/ssl.h
Backport of #927 to mbedtls-2.1
**READY**
=> Backport 2.1: Documentation error in `mbedtls_ssl_get_session`

ChangeLog, library/ssl_tls.c, programs/ssl/ssl_client2.c, tests/ssl-opt.sh
This is a backport of https://github.com/ARMmbed/mbedtls/pull/1852 and https://github.com/ARMmbed/mbedtls/pull/1835. The first is a change in ssl_client2 and ssl-opt.sh to add tests for sending empty application data records, while the changes in the second PR fix some issues with this functionality.
**READY**
=> Backport 2.1: Fix sending empty application data records in ssl_client2

include/mbedtls/bn_mul.h, tests/scripts/all.sh
This is a backport of PR #1810.
The i386 test builds were only building the default configuration and had no address sanitisation. This pull request expands the test configuration to the full configuration in all.sh and generates ASan builds for test suite execution.
This pull request extends test coverage sufficiently that issue #1550, where the MPI assembly code on i386 which was fundamentally broken, would have been caught.
It also fixes the inline assembly which was previously only being included in builds with no optimisation, which was the opposite of what it should have been doing.
**READY**
=> Backport 2.1: Expand i386 all.sh tests to include full configuration ASan builds

tests/scripts/all.sh
When calling all.sh from a script and using "--keep-going", errors were
sometimes missed due to all.sh always returning 0 "success" return code.
Return 1 if there is any failure encountered during a "keep-going" run.
Backport of #1871
=> Backport 2.1: all.sh: Return error on keep-going failure

include/mbedtls/cipher.h, tests/suites/test_suite_pkparse.data
This PR fixes #1890.
Chacha20 was using a stream wrapper function which was being compiled out if `MBEDTLS_ARC4_C` and `MBEDTLS_CIPHER_NULL_CIPHER` weren't defined. This fixes that.
The PR also fixes some dependencies in the `pkparse` test suites which were dependent on DES and yet used RC2.
**READY**
Yes  
The test fixes will need backporting.
=> Fix dependencies on RC4

tests/suites/test_suite_pkparse.data
Backport of the test fixes in #1891 to Mbed TLS 2.7.
=> Backport 2.7: Fix RC4 dependencies

tests/suites/test_suite_pkparse.data
Backport of the test fixes in #1891 to Mbed TLS 2.1.
=> Backport 2.1: Fix RC4 dependencies

ChangeLog, library/ssl_ciphersuites.c, library/ssl_cli.c, library/ssl_srv.c, tests/ssl-opt.sh
Fix compliancy to RFC4492. ECC extensions should be included
only if ec ciphersuites are used. Interoperability issue with
bouncy castle. Resolves #1157
Yes 
Which branch?
Missing tests, ChangeLog
=> Add ecc extensions only if ecc ciphersuite is used

library/ccm.c
In `mbedtls_ccm_self_test()`, enforce input and output
buffers sent to the ccm API to be contigous and aligned,
by copying the test vectors to buffers on the stack.
**READY**
Yes   
Which branch?
Possibly need to backport to `mbedtls-2.7`
An issue in the test, so I don't think there is a need yo update ChangeLog.
=> enforce input and output of ccm selftest on stack

Makefile
Notes:
-  The submitter has [accepted the online agreement here with a click through](https://developer.mbed.org/contributor_agreement/) .
- account created: **xueruini@gmail.com**
I am building `curl` with `mbedtls` for an embedded device. One interesting phenomenon is `make curl` always rebuild its source files even no single `curl` file is edited. After debugging, I found the root cause is: the build system in my device will build and install mbedtls first, and then curl. During installing mbedtls, all mbedtls headers will be **copied** to the DESTDIR. However, on copying, the headers' mtime are updated even no mbedtls file is updated, so `make curl` thinks the dependencies are updated, so the entire `curl` will be rebuilt.
The fix is very …
=> Use preserve mode to copy headers.

ChangeLog, library/ecp.c
In ecp_mul_comb(), if (!p_eq_g && grp->T == NULL) and ecp_precompute_comb() fails (which can
happen due to OOM), then the new array of points T will be leaked (as it's newly allocated, but
hasn't been assigned to grp->T yet).
Symptom was a memory leak in ECDHE key exchange under low memory conditions.
READY
Yes? This is quite a subtle and uncommon bug. Will follow advice from maintainers about whether it should be backported or not (and to where).
NO
Submission is from Espressif Systems and falls under corporate CLA..
This is quite difficult to reproduce easily (or write a unit test for) as there needs to be enough free memory that the calloc() inside ecp_mul_comb() succeeds, but then later allocations in ecp_precompute_comb() will fail. It was only reported under very certain …
=> Fix memory leak in ecp_mul_comb() if ecp_precompute_comb() fails

ChangeLog, library/ssl_cli.c, library/ssl_srv.c, tests/ssl-opt.sh
Backport of #1378 to mbedtls-2.1
**READY**
=> Backport 2.1: Add ecc extensions only if ecc ciphersuite is used

ChangeLog, library/ecp.c
Backport of #1834 to `mbedtls-2.1`
**READY**
=> Backport 2.1: Fix memory leak in ecp_mul_comb() if ecp_precompute_comb() fails

ChangeLog, library/ssl_ciphersuites.c, library/ssl_cli.c, library/ssl_srv.c, tests/ssl-opt.sh
Backport of #1378 to mbedtls-2.7
**READY**
=> Backport 2.7: Add ecc extensions only if ecc ciphersuite is used

ChangeLog, library/ecp.c
Backport of #1834 to `mbedtls-2.7`
**READY**
=> Backport 2.7: Fix memory leak in ecp_mul_comb() if ecp_precompute_comb() fails

library/ccm.c
Backport of #1598 to `mbedtls-2.7`
**READY**
=> Backport 2.7: enforce input and output of ccm selftest on stack

programs/ssl/ssl_mail_client.c
sprintf( (char *) buf, "%s\r\n", base );
Above code generates Wformat-overflow warning since both buf and base
are of same size. buf should be sizeof( base ) + characters added in
the format. In this case format adds 2 bytes for "\r\n".
**READY**
Yes
Which branch?
development
mingw32 build produces this warning.
=> Fix Wformat-overflow warning in ssl_mail_client.c

ChangeLog, library/aria.c
Replace usages of `printf()` with `mbedtls_printf()` in `aria.c`
which were accidentally merged. Fixes #1908
=> Use mbedtls_printf instead of printf

ChangeLog, library/ssl_tls.c
=> Reset session in/out pointers in mbedtls_ssl_session_reset()

ChangeLog, library/ssl_tls.c
Backport of #1942 to Mbed TLS 2.1, fixing #1941.
=> Backport 2.1: Reset session in/out pointers in mbedtls_ssl_session_reset()

programs/ssl/ssl_mail_client.c
=> Backport 2.1: Fix Wformat-overflow warning in ssl_mail_client.c

ChangeLog, library/ssl_tls.c
Backport of #1942 to Mbed TLS 2.7, fixing #1941.
=> Backport 2.7: Reset session in/out pointers in mbedtls_ssl_session_reset()

programs/ssl/ssl_mail_client.c
=> Backport 2.7: Fix Wformat-overflow warning in ssl_mail_client.c

ChangeLog, programs/pkey/pk_decrypt.c, programs/pkey/pk_encrypt.c
__Summary:__ This PR fixes the #1128 on memory leaks and free-without-initialization in the example program `pk_encrypt`. The same issue was found to exist `pk_decrypt` and is also fixed. Also, some minor style improvements have been made along the way.
=> Memory leak in example programs pk_encrypt and pk_decrypt

ChangeLog, library/ssl_cli.c, library/x509_crt.c
Fixes Undefined behavior with exponent shift #1624
**READY**
Yes
Which branch? Do not know
NO
Found using oss-fuzz
See #1624
=> Fix undefined shift in x509_profile_check_pk_alg

ChangeLog, library/ssl_tls.c
__Summary:__ This PR fixes miscalculations of the maximum record expansion in `mbedtls_ssl_get_record_expansion()` in the case of ChachaPoly ciphersuites, as well as CBC ciphersuites in (D)TLS versions 1.1 or higher. Fixes #1913 and #1914.
This PR has high relevance for the ongoing fragmentation work #1879, which uses `mbedtls_ssl_get_record_expansion()` to deduce from the configured MTU the maximum record payload.
=> Fix miscalculations of maximum record expansion in mbedtls_ssl_get_record_expansion()

ChangeLog, include/mbedtls/ssl.h, include/mbedtls/ssl_internal.h, library/ssl_cli.c, library/ssl_srv.c, library/ssl_tls.c, programs/ssl/ssl_client2.c, programs/ssl/ssl_server2.c, tests/ssl-opt.sh
__Summary:__ This PR adds support for stacking multiple records in a single datagram, based on the ongoing work to support outgoing handshake fragmentation in #1939. The first new commit is https://github.com/ARMmbed/mbedtls/pull/1918/commits/5aa4e2cedd819b4fd307531eaa64f4f5ca8a01d4.
=> Add support for datagram packing

ChangeLog, include/mbedtls/ssl.h, include/mbedtls/ssl_internal.h, library/ssl_cli.c, library/ssl_srv.c, library/ssl_tls.c, programs/ssl/ssl_client2.c, programs/ssl/ssl_server2.c, tests/ssl-opt.sh
Add support for fragmenting of DTLS handshake messages based on maximum fragment length and/or an explicit MTU setting.
Supersedes and continues  https://github.com/ARMmbed/mbedtls/pull/1879 
Partially fixes https://github.com/ARMmbed/mbedtls/issues/387 (for DTLS only).
**Note to gatekeeper:** please close internal ref IOTSSL-592 when merging this.
Based on #1942 and merging #1915 and #1955 along the way as they're all necessary for tests to pass here.
Reviewers, please only review new commits in this branch.
**Note to gatekeeper:** you probably want to merge #1942, #1915 and #1955 before this one for clarity.
**READY**
NO
Compatible API extensions
ABI change in libmbedtls (added `mtu` field to `stuct mbedtls_ssl_config`).
=> Add support for fragmenting of DTLS handshake messages

tests/suites/test_suite_nist_kw.data, tests/suites/test_suite_nist_kw.function
Enhance the nist_kw test suite, with setting zero length input\output
buffers. Resolves #1882.
Increasing test coverage, by testing NULL pointers with zero length
**READY**
NO  
=> Enhance nist_kw with some NULL buffers tests

ChangeLog, library/ecp.c
Remove `else` statement, as it is redundant. resolves #1776
**READY**
No
~~~Yes~~~
~~~Although it is a trivial fix, I would backport it.~~~
=> Remove redundant `else` statement

ChangeLog, include/mbedtls/ssl.h, include/mbedtls/ssl_internal.h, library/ssl_cli.c, library/ssl_srv.c, library/ssl_tls.c, programs/ssl/ssl_client2.c, programs/ssl/ssl_server2.c, tests/ssl-opt.sh
Note: this is based on #1939.
**Note to reviewers:** please only review commits starting from "Implement PMTU auto-reduction in handshake". (So far, this is a two-commits PR.)
**Note to gatekeeper:** you probably want to merge #1939 first, and want to merge it independently anyway as it contains commits newer than this PR.
This implements a very basic version of the last paragraph of section 4.1.1.1 of RFC 6347 by lowering the MTU to a safe value until the end of the handshake if a flight needs to be retransmitted more than once.
This is necessary for example in the following scenario: a server communicates with many clients, some of which have a nice solid connection that allows large datagrams, while others have a restricted link and IP stack that doesn't allow UDP datagrams larger than …
=> DTLS: MTU auto-reduction during handshake

tests/ssl-opt.sh
__Summary:__ `ssl-opt.sh` allows the option `--preserve-logs` to keep log files on test successes. However, the option currently only applies to the client and server logs, but not to the UDP proxy log.  This PR adapts `ssl-opt.sh` to also keep the proxy log if `--preserve-logs` is specified.
=> ssl-opt.sh: Preserve proxy log if --preserve-logs is specified

ChangeLog, library/ssl_cli.c, library/x509_crt.c
Backport of #1625.
Fixes Undefined behavior with exponent shift #1624
**READY**
=> Backport 2.7: Fix undefined shift in x509_profile_check_pk_alg

ChangeLog, library/ssl_cli.c, tests/ssl-opt.sh
Backport of #1955 to Mbed TLS 2.7, fixing #1954.
=> Backport 2.7: Fix bounds check in ssl_parse_certificate_request()

ChangeLog, library/ssl_tls.c
This is the backport of #1915 to Mbed TLS 2.7, fixing #1914.
=> Backport 2.7: Fix miscalculations of maximum record expansion in mbedtls_ssl_get_record_expansion()

tests/ssl-opt.sh
This is the backport of #1967 to Mbed TLS 2.7.
=> Backport 2.7: ssl-opt.sh: Preserve proxy log if --preserve-logs is specified

ChangeLog, programs/pkey/pk_decrypt.c, programs/pkey/pk_encrypt.c
This is the backport of #1129 to Mbed TLS 2.7.
=> Backport 2.7: Memory leak in example programs pk_encrypt and pk_decrypt

programs/x509/cert_write.c
This is the backport of #1979 to Mbed TLS 2.7, fixing #1922.
=> Backport 2.7: Fix typos in programs/x509/cert_write.c

ChangeLog, programs/pkey/pk_decrypt.c, programs/pkey/pk_encrypt.c
This is the backport of #1129 to Mbed TLS 2.1.
=> Backport 2.1: Memory leak in example programs pk_encrypt and pk_decrypt

ChangeLog, library/ssl_cli.c, library/x509_crt.c
Backport of #1625.
Fixes Undefined behavior with exponent shift #1624
**READY**
=> Backport 2.1: Fix undefined shift in x509_profile_check_pk_alg

ChangeLog, library/ssl_cli.c, tests/ssl-opt.sh
Backport of #1955 to Mbed TLS 2.1, fixing #1954.
=> Backport 2.1: Fix bounds check in ssl_parse_certificate_request()

ChangeLog, library/ssl_tls.c
This is the backport of #1915 to Mbed TLS 2.1, fixing #1914.
=> Backport 2.1: Fix miscalculations of maximum record expansion in mbedtls_ssl_get_record_expansion()

programs/x509/cert_write.c
This is the backport of #1979 to Mbed TLS 2.1, fixing #1922.
=> Backport 2.1: Fix typos in programs/x509/cert_write.c

ChangeLog, include/mbedtls/config.h, include/mbedtls/platform_util.h, include/mbedtls/threading.h, library/platform_util.c, library/threading.c, library/x509.c
This patch is a first attempt at fixing https://github.com/ARMmbed/mbedtls/issues/1907. The build failure is caused by https://github.com/ARMmbed/mbedtls/pull/1198, which replaces the use of gmtime() with gmtime_r() (POSIX) and gmtime_s() (Windows). However, Mbed TLS is also used on platforms which are neither Windows nor POSIX, such as some targets in Mbed OS that only have gmtime().
The idea in this patch is to keep the majority of the changes from https://github.com/ARMmbed/mbedtls/pull/1198, but to fall back to using gmtime() if the target platform is neither POSIX nor Windows. Unfortunately, the code becomes slightly convoluted because we also need to use a mutex as gmtime() is not thread-safe and it is not particularly straight forward to check at compile-time if the target platform …
=> Use gmtime() when neither gmtime_r nor gmtime_s are available

ChangeLog, programs/ssl/ssl_server2.c, tests/ssl-opt.sh
The “large packet” tests in `ssl-opt.sh` only test how the server copes with large packets. Add corresponding tests in the client, and suitable code to generate the test packets to `ssl_server2`.
Internal ref: IOTSSL-1703
=> Added buffer_size and response_size options for ssl-server2.

ChangeLog, programs/test/benchmark.c
Remove redunadnat calls to `hmac_drbg_free()` between seeding operations,
which make the mutex invalid. Fixes #1095
**READY**
Yes
Which branch?
mbedtls-2.1
mbedtls-2.7
NO
=> Fix hmac_drbg failure in benchmark, with threading

ChangeLog, library/ssl_ticket.c, tests/ssl-opt.sh
__Summary:__ This PR fixes #1968 and #1969.
=> Add DTLS session resumption tests and fix a bug in SSL ticket key update

ChangeLog, programs/test/benchmark.c
Backport of #1758 to `mbedtls-2.7`
**READY**
=> Backport 2.7:Fix hmac_drbg failure in benchmark, with threading

ChangeLog, library/ssl_ticket.c, tests/ssl-opt.sh
This is the backport of #1970 to Mbed TLS 2.7, fixing #1968 and #1969.
=> Backport 2.7: Add DTLS session resumption tests and fix a bug in SSL ticket key update

programs/ssl/ssl_server2.c, tests/ssl-opt.sh
=> Backport Mbedtls 2.1 - Added buffer_size and response_size options for ssl-server2.

ChangeLog, programs/test/benchmark.c
Backport of #1758 to `mbedtls-2.1`
**READY**
=> Backport 2.1:Fix hmac_drbg failure in benchmark, with threading

ChangeLog, library/ssl_ticket.c, tests/ssl-opt.sh
This is the backport of #1970 to Mbed TLS 2.1, fixing #1968 and #1969.
=> Backport 2.1: Add DTLS session resumption tests and fix a bug in SSL ticket key update

programs/ssl/ssl_server2.c, tests/ssl-opt.sh
=> Backport mbedtls 2.7 - Added buffer_size and response_size options for ssl-server2.

tests/ssl-opt.sh
Disable interop tests that (may) run into openssl bugs, for all of the versions we have installed in the CI.
**READY**
NO
NO
=>  Disable interop tests without a working OpenSSL version

ChangeLog, programs/ssl/dtls_client.c, programs/ssl/dtls_server.c
Changes the IP address to bind to for dtls_server.c to be "::" or optionally "0.0.0.0" if the preprocessor symbol FORCE_IPV4 is defined.
Also changes the destinaton IP address for dtls_client.c to be "::1" or if FORCE_IPV4 symbol is defined "127.0.0.1".
This change allows `dtls_server.c` and `dtls_client.c` to be configured to use either IPv4 or IPv6 at build time, so out of the box they will work together.
Previously `dtls_server.c` might bind to IPv6 and `dtls_client.c` connect over IPv4, leading to a failure.
**READY**
Yes
This is a configuration of the build and doesn't materially change the logic. There is definitely a bug here, as this issue is causing the sample to fail to work on OSX and possibly Windows.
I think the decision to back port should be part of the review of this PR …
=> Change the default IP addresses for DTLS samples

tests/scripts/run-test-suites.pl
The run-test-suites.pl script was executing all files of the form `test_suite*` which were either executable or ended with a `.exe` extension.
On some filesystems, such as through network shares or VMs, which are abstracting one set of file permissions to Unix permissions, the executable permission on files could be set, whether they're executable or not.
That was leading to the `run-test-suites.pl` script to attempt to execute the `.c` intermediate files because they followed the form `test_suite_*.c`. This change now excludes them, just in case they accidentally have execute permissions.
This is a trivial PR, for a minor issue which is really a corner case, that annoyed me, and doesn't deserve any priority.
**READY**
YES - Mbed TLS 2.7 - but not Mbed TLS 2.1
NO
=> Adds a filter to run-test-suites.pl to exclude source code and data files

include/mbedtls/error.h, include/mbedtls/platform.h, library/error.c, scripts/generate_errors.pl
Add error codes for the platform module, to be used by
the setup \ terminate API, as suggested in https://github.com/ARMmbed/mbed-os/pull/7099#discussion_r192698898
**READY**
NO
=> Add platform error codes

doxygen/mbedtls.doxyfile, tests/Makefile, tests/scripts/all.sh, tests/scripts/check-files.py, tests/scripts/test_zeroize.gdb
Fix some issues that don't break `all.sh` on a pristine checkout, but make it fragile in a tree where you've been doing development.
* Fix `make WINDOWS_BUILD=1 clean` on non-Windows hosts.
* In keep-going mode, don't hard-fail on some auxiliary script or test.
* Fix #1691 fix #1713: `check-files.py` complaining about files in `.git` or in third-party subtrees.
* Fix `make apidoc` looking for files in unintended subdirectories.
* Don't fail on a spurious error if ASLR can't be disabled (not an issue on developer machines, but this would let us remove the don't-enforce-ASLR configuration from some CI jobs).
Backports: #2032 for 2.7, #2033 for 2.1.
Precursor to PSA.
=> Fix fragility issues in all.sh

include/mbedtls/ecp.h, library/ecp.c
__Context:__ The macro `MBEDTLS_ECP_BUDGET()` is called before performing a number of potentially time-consuming ECC operations. If restartable ECC is enabled, it wraps a call to `mbedtls_ecp_check_budget()` which in turn checks if the requested number of operations can be performed without exceeding the maximum number of consecutive ECC operations.
__Issue:__ The function `mbedtls_ecp_check_budget()` expects the number of requested operations to be given as a value of type `unsigned`, while some calls of the wrapper macro `MBEDTLS_ECP_BUDGET()` use
expressions of type `size_t`. This rightfully leads to warnings about implicit truncation from `size_t` to `unsigned` on some compilers, and was reported in #2141.
__Fix:__ Commit abdf67e makes the truncation explicit by adding an explicit …
=> Remove integer conversion warning in non-blocking ECC

doxygen/mbedtls.doxyfile, tests/scripts/all.sh, tests/scripts/check-files.py
Fix some issues that don't break `all.sh` on a pristine checkout, but make it fragile in a tree where you've been doing development.
* In keep-going mode, don't hard-fail on some auxiliary script or test.
* Fix #1691 #1713: `check-files.py` complaining about files in `.git` or in third-party subtrees.
* Fix `make apidoc` looking for files in unintended subdirectories.
Backport of #2031. Differences with the original:
* “Fix `make WINDOWS_BUILD=1 clean` on non-Windows hosts.” is not applicable since it fixes an issue introduced by #930. It should be fixed in the backport of #930.
* The ALSR issue does not apply since we don't use gdb in the 2.7 tests.
=> Backport 2.7: Fix fragility issues in all.sh

tests/scripts/run-test-suites.pl
This is a backport of #1806.
The run-test-suites.pl script was executing all files of the form `test_suite*` which were either executable or ended with a `.exe` extension.
On some filesystems, such as through network shares or VMs, which are abstracting one set of file permissions to Unix permissions, the executable permission on files could be set, whether they're executable or not.
That was leading to the `run-test-suites.pl` script to attempt to execute the `.c` intermediate files because they followed the form `test_suite_*.c`. This change now excludes them, just in case they accidentally have execute permissions.
This is a trivial PR, for a minor issue which is really a corner case, that annoyed me, and doesn't deserve any priority.
**READY**
NO
=> Backport 2.7: Adds a filter to run-test-suites.pl to exclude source code and data files

ChangeLog, programs/ssl/dtls_client.c, programs/ssl/dtls_server.c
This is a backport of #1627 to `mbedtls-2.7`.
Changes the IP address to bind to for dtls_server.c to be "::" or optionally "0.0.0.0" if the preprocessor symbol FORCE_IPV4 is defined.
Also changes the destinaton IP address for dtls_client.c to be "::1" or if FORCE_IPV4 symbol is defined "127.0.0.1".
This change allows `dtls_server.c` and `dtls_client.c` to be configured to use either IPv4 or IPv6 at build time, so out of the box they will work together.
Previously `dtls_server.c` might bind to IPv6 and `dtls_client.c` connect over IPv4, leading to a failure.
**READY**
=> Backport 2.7: Change the default IP addresses for DTLS samples

tests/scripts/all.sh, tests/scripts/check-files.py
Fix some issues that don't break `all.sh` on a pristine checkout, but make it fragile in a tree where you've been doing development.
* In keep-going mode, don't hard-fail on some auxiliary script or test.
* Fix #1691 #1713: `check-files.py` complaining about files in `.git` or in third-party subtrees.
Backport of #2031. Differences with the original:
* “Fix `make WINDOWS_BUILD=1 clean` on non-Windows hosts.” is not applicable since it fixes an issue introduced by #930. It should be fixed in the backport of #930.
* “Fix `make apidoc`” interacts with #2011 and I'll handle it there instead of here.
* The ALSR issue does not apply since we don't use gdb in the 2.1 tests.
=> Backport 2.1: Fix fragility issues in all.sh

ChangeLog, programs/ssl/dtls_client.c, programs/ssl/dtls_server.c
This is a backport of #1627 to `mbedtls-2.1`.
Changes the IP address to bind to for dtls_server.c to be "::" or optionally "0.0.0.0" if the preprocessor symbol FORCE_IPV4 is defined.
Also changes the destinaton IP address for dtls_client.c to be "::1" or if FORCE_IPV4 symbol is defined "127.0.0.1".
This change allows `dtls_server.c` and `dtls_client.c` to be configured to use either IPv4 or IPv6 at build time, so out of the box they will work together.
Previously `dtls_server.c` might bind to IPv6 and `dtls_client.c` connect over IPv4, leading to a failure.
**READY**
=> Backport 2.1: Change the default IP addresses for DTLS samples

include/mbedtls/bn_mul.h
These two patches improve the bignum code (used in particular for RSA computation) on ARM CPU which have the DSP extension, that is the ARMv7E-M like the Cortex M4 and Cortex M7, or the ARMv7-A, like the Cortex A series. It has been originally developed for a Cortex M4 application, but I have done all the tests on a Cortex A8.
READY
NO (enhancement)
NO (this is just a different code path on supported CPU)
=> Improve bignum speed on ARM with DSP instructions

ChangeLog, programs/x509/cert_write.c
Fixes #1422.
__Needs backports:__ Yes, available at #2058 and #2057.
=> Fix memory leak in `cert_write` example program.

tests/suites/test_suite_ecdsa.function
__Summary:__ The test case `ecdsa_det_test_vectors` from the ECDSA test suite called `mbedtls_md()` without checking its return value. This PR fixes this.
__Internal Reference:__ IOTSSL-2492.
=> Add missing return value check in ECDSA test suite

ChangeLog, library/ssl_tls.c
__Summary:__ This PR changes the behavior of the record decryption routine `ssl_decrypt_buf()` in the following situation:
1. A CBC ciphersuite with Encrypt-then-MAC is used.
2. A record with valid MAC but invalid CBC padding is received.
In this situation, the previous code would not raise and error but instead forward the decrypted packet, including the wrong padding, to the user.
This PR changes this behaviour to return the error `MBEDTLS_ERR_SSL_INVALID_MAC` instead.
__Note:__ While erroneous, the previous behaviour does not constitute a security flaw since it can only happen for properly authenticated records.
__Internal Reference:__ IOTSSL-1919
=> Reject properly authenticated but improperly padded records in CBC with EtM

ChangeLog, programs/x509/cert_write.c
Backport of #2056 fixing #1422.
=> Backport 2.7: Fix memory leak in cert_write example program

ChangeLog, programs/ssl/ssl_server2.c
Backport of #2070 to Mbed TLS 2.7, fixing #2069.
=> Backport 2.7: Fix memory leak in ssl_server2 when buffer allocator and backtracing enabled

tests/suites/test_suite_ecdsa.function
This is the backport to Mbed TLS 2.7 of #2107.
=> Backport 2.7: Add missing return value check in ECDSA test suite

ChangeLog, library/ssl_tls.c
This is the backport to Mbed TLS 2.7 of #2111.
=> Backport 2.7: Reject properly authenticated but improperly padded records in CBC with EtM

ChangeLog, library/timing.c
In Visual C/C++ programs that use CRT library, should do threading with `_beginthread`, `_beginthreadex` and `_endthread`, `_endthreadex` functions instead of Windows API functions `CreateThread`, `ExitThread` and `CloseHandle`.
Otherwise some CRT funtions could fail, and memory leaks are possible.
Timer tests in `selftest.c` with the new code were successful.
**READY**
Yes
development
NO
More information could be found in
- Microsoft KnowledgeBase Article Q104641
- Microsoft online documentation for _beginthread, _beginthreadex and _endthread, _endthreadex function
=> Replace Windows API threading with CRT functions

ChangeLog, library/ssl_tls.c, programs/aes/aescrypt2.c, programs/aes/crypt_and_hash.c
__Summary:__ This PR addresses the following two issues:
1. The example programs `programs/aes/aescrypt2` and `programs/aes/crypt_and_hash` used `memset()` to zeroize sensitive data at the end of the application run. While not a security issue because the programs are examples only, this shows bad practice and should therefore be fixed.
2. Zeroize buffers used for reassembled or buffered handshake messages after use.
=> Fix missing or improper zeroization

ChangeLog, library/timing.c
Backport of #1777.
In Visual C/C++ programs that use CRT library, should do threading with _beginthread, _beginthreadex and _endthread, _endthreadex functions instead of Windows API functions CreateThread, ExitThread and CloseHandle.
Otherwise some CRT funtions could fail, and memory leaks are possible.
Timer tests in selftest.c with the new code were successful.
**READY**
NO
=> Backport 2.7: Replace Windows API threading with CRT functions

ChangeLog, library/ssl_tls.c, programs/aes/aescrypt2.c, programs/aes/crypt_and_hash.c
This is the backport of #2095 to Mbed TLS 2.7.
=> Backport 2.7: Fix missing or improper zeroization

programs/ssl/ssl_server2.c
This is the backport of #1875 to Mbed TLS 2.7, fixing #1874.
__Internal Reference:__ IOTSSL-2025.
=> Backport 2.7: Increase the memory buffer size for ssl_server2.c

ChangeLog, library/timing.c
Backport of #1777.
In Visual C/C++ programs that use CRT library, should do threading with _beginthread, _beginthreadex and _endthread, _endthreadex functions instead of Windows API functions CreateThread, ExitThread and CloseHandle.
Otherwise some CRT funtions could fail, and memory leaks are possible.
Timer tests in selftest.c with the new code were successful.
**READY**
NO
=> Backport 2.1: Replace Windows API threading with CRT functions

ChangeLog, library/ssl_tls.c, programs/aes/aescrypt2.c, programs/aes/crypt_and_hash.c
This is the backport to Mbed TLS 2.1 of #2095.
=> Backport 2.1: Fix missing or improper zeroization

programs/ssl/ssl_server2.c
This is the backport to Mbed TLS 2.1 of #1875, fixing #1874.
__Internal Reference:__ IOTSSL-2025.
=> Backport 2.1: Increase the memory buffer size for ssl_server2.c

library/x509_crt.c
`stdio.h` was being included both conditionally if `MBEDTLS_FS_IO` was defined, and also unconditionally, which made at least one of them redundant.
This change removes the unconditional inclusion of stdio.h and makes it conditional on `MBEDTLS_PLATFORM_C`.
**READY**
Yes
Which branch?
`mbedtls-2.7` and `mbedtls-2.1`
=> Make inclusion of stdio.h conditional in x509_crt.c

library/pkparse.c
__Context:__ This commit makes a change to `mbedtls_pk_parse_key()` which
is responsible for parsing of private keys. The function doesn't know
the key format in advance (PEM vs. DER, encrypted vs. unencrypted) and
tries them one by one, resetting the PK context in between.
__Issue:__ The previous code resets the PK context through a call to
`mbedtls_pk_free()` along, lacking the accompanying `mbedtls_pk_init()`
call. Practically, this is not an issue because functionally
`mbedtls_pk_free() + mbedtls_pk_init()` is equivalent to `mbedtls_pk_free()`
with the current implementation of these functions, but strictly
speaking it's nonetheless a violation of the API semantics according
to which `xxx_free()` functions leave a context in uninitialized state.
(yet not entirely random, because …
=> Reinitialize PK ctx in `mbedtls_pk_parse_key()` before reuse are free

ChangeLog, library/platform.c, tests/scripts/all.sh
__Summary:__ This PR fixes #1642, the issue being a build failure in configurations that use the compile time configuration macros `MBEDTLS_PLATFORM_{CALLOC/FREE}_MACRO` to set custom `calloc()` and `free()` functions. If these macros are defined, the API for runtime configurations `mbedtls_platform_set_calloc_free()` should be omitted from `platform.c` (as in `platform.h`) but it's not. For the development branch, this leads to compilation warning (hence failure in some build modes) about function definition without prior declaration, while in the LTS branches Mbed TLS 2.1 and Mbed TLS 2.7, the compilation fails due to multiple function definitions (the reason for the different symptoms is commit https://github.com/ARMmbed/mbedtls/commit/7decfe8c1ed6a5da39fffb547a1b27ef0bb04ee1 was …
=> Fix build failure if MBEDTLS_PLATFORM_{CALLOC/FREE}_MACRO are set

include/mbedtls/config.h
__Summary:__ The configuration option `MBEDTLS_SSL_RENEGOTIATION` is a 'positive' option in the sense that setting it _enables_ the feature of renegotiation. However, the macro was previously documented as 'Disable support for TLS renegotiation'. This PR fixes this.
=> Correct typo in documentation of MBEDTLS_SSL_RENEGOTIATION

include/mbedtls/check_config.h, include/mbedtls/config.h, library/ecdh.c, library/ecdsa.c
Return the condition compilation flags surrounding
`mbedtls_ecdh_compute_shared()`, `mbedtls_ecdh_gen_public()`,
`mbedtls_ecdsa_sign()` and `mbedtls_ecdsa_verify()` that were accidentally
removed in a previous merge.
Resolves #2163
**READY**
NO  
The bug was introduced on a recent PR, that is not in the LTS branches
NO
May be fixed in a simpler way, having a restartable and a non restartable path, when only the non-restartable path can be hw accelerated. Requires architectural discussion 
Compile the on target tests with the development branch with `NRF52840_DK` target
=> conditionaly compile ECDH and ECDSA alt functions

ChangeLog, library/platform.c, tests/scripts/all.sh
This is the backport to Mbed TLS 2.7 of #2079 fixing #1642 and #1706.
=> Backport 2.7: Fix build failure if MBEDTLS_PLATFORM_{CALLOC/FREE}_MACRO are set

library/pkparse.c
This is the backport of #2077 to Mbed TLS 2.7.
=> Backport 2.7: Reinitialize PK ctx in `mbedtls_pk_parse_key()` before reuse are free

library/x509_crt.c
`stdio.h` was being included both conditionally if `MBEDTLS_FS_IO` was defined, and also unconditionally, which made at least one of them redundant.
This change removes the unconditional inclusion of stdio.h and makes it conditional on `MBEDTLS_PLATFORM_C`.
This is a backport of #2052.
**READY**
=> Backport 2.7: Make inclusion of stdio.h conditional in x509_crt.c

ChangeLog, include/mbedtls/ssl.h
This is the backport to Mbed TLS 2.7 of #2127, fixing #517.
=> Backport 2.7: Improve documentation of mbedtls_ssl_get_verify_result()

include/mbedtls/config.h
This is the backport to Mbed TLS 2.7 of #2140.
=> Backport 2.7: Correct typo in documentation of MBEDTLS_SSL_RENEGOTIATION

ChangeLog, library/platform.c, tests/scripts/all.sh
This is the backport of #2079 to Mbed TLS 2.1, fixing #1642 and #1706.
=> Backport 2.1: Fix build failure if MBEDTLS_PLATFORM_{CALLOC/FREE}_MACRO are set

library/pkparse.c
This is the backport of #2077 to Mbed TLS 2.1.
=> Backport 2.1: Reinitialize PK ctx in `mbedtls_pk_parse_key()` before reuse are free

library/x509_crt.c
`stdio.h` was being included both conditionally if `MBEDTLS_FS_IO` was defined, and also unconditionally, which made at least one of them redundant.
This change removes the unconditional inclusion of stdio.h and makes it conditional on `MBEDTLS_PLATFORM_C`.
This is a backport of #2052.
**READY**
=> Backport 2.1: Make inclusion of stdio.h conditional in x509_crt.c

ChangeLog, include/mbedtls/ssl.h
This is the backport to Mbed TLS 2.1 of #2127, fixing #517.
=> Backport 2.1: Improve documentation of mbedtls_ssl_get_verify_result()

include/mbedtls/config.h
This is the backport to Mbed TLS 2.1 of #2140.
=> Backport 2.1: Correct typo in documentation of MBEDTLS_SSL_RENEGOTIATION

programs/Makefile, tests/Makefile
Programs and tests need to be able to use PSA header files when
USE_CRYPTO_SUBMODULE and MBEDTLS_USE_PSA_CRYPTO are set. Add the crypto
submodule include folder, which contains psa headers, after the main
include folder so that psa headers can be found and crypto submodule
headers don't take precedence over mbedtls headers.
=> psa: Include PSA headers for tests and programs

ChangeLog, doxygen/input/doc_mainpage.h, doxygen/mbedtls.doxyfile, include/mbedtls/version.h, library/CMakeLists.txt, tests/suites/test_suite_version.data
Updates the Mbed TLS library version to 2.15.0.
**READY**
NO
=> Update the Mbed TLS Library version to 2.15.0

tests/suites/test_suite_ecdsa.function
Change the size of `buf` to a valid hash size, in `ecdsa_prim_random()`
Tested on NRF52840_DK and on PC Linux
**READY**
No, since the On Target Tests are not in the LTS branches
Run the test_suite_ecdsa function in NRF62840_DK platform
=> Change ecdsa hash buf size to a valid hash length

tests/scripts/check-files.py
The check-files script contains the strings "TODO" and "todo" in order to
search for files that contain TODO items. So, any check-files script would
need to be excluded from the list of files that gets checked for "TODO".
Normally, the script excludes itself from checks, but with the addition of
the crypto submodule, there is another copy of the script present from the
project root. We must avoid checking check-files scripts for TODO items.
This also helps if you run check-files from another working tree in your
working tree.
=> check-files: Don't check same-named files

ChangeLog, include/mbedtls/check_config.h, include/mbedtls/config.h, library/ecp.c
We initialised the ECC hardware before calling
mbedtls_ecp_mul_shortcuts(). This in turn calls
mbedtls_ecp_mul_restartable(), which initialises and frees the hardware
too. This issue has been introduced by recent changes and caused some
accelerators to hang.
We move the initialisation after the mbedtle_ecp_mul_shortcuts() calls
to avoid double initialisation.
**READY**
NO
=> Fix ecc hardware double init

ChangeLog, include/mbedtls/ccm.h, library/ccm.c, tests/suites/test_suite_ccm.data, tests/suites/test_suite_ccm.function
This PR adds parameter validation to the CCM module.
It is based on #1643, the first relevant commit is 9ca2615724641090d191072fac8a478a3a55cc37
=> Add parameter validation for CCM module

include/mbedtls/chacha20.h, include/mbedtls/chachapoly.h, include/mbedtls/poly1305.h, library/chacha20.c, library/chachapoly.c, library/poly1305.c, tests/suites/test_suite_chacha20.function, tests/suites/test_suite_chachapoly.function, tests/suites/test_suite_poly1305.function
__Summary:__ This PR moves the existing parameter validation for the ChaCha/Poly modules to the framework provided in #1643.
__Important:__ This PR is different from parameter validation work in other modules because the ChaCha20, Poly1305 and ChaChaPoly modules _do_ already have _unconditional_ parameter validation, and this PR only moves it into the framework of #1643. In particular, the previously unconditional parameter checks are now conditional on the (by default disabled) `MBEDTLS_CHECK_PARAMS` configuration option, which is strictly speaking an API break, and it need to be discussed whether this is an acceptable change or not. Ping @mpg @sbutcher-arm.
=> Add parameter validation for ChaCha/Poly modules

include/mbedtls/aria.h, library/aria.c, tests/suites/test_suite_aria.data, tests/suites/test_suite_aria.function
__Summary:__ Based on #1643, this PR adds parameter validation for the ARIA module.
__Work left:__ Allocate free error code for `MBEDTLS_ERR_ARIA_BAD_INPUT_DATA`. Slightly annoying because there are already two similar error codes `MBEDTLS_ERR_ARIA_INVALID_KEY_LENGTH` and `MBEDTLS_ERR_ARIA_INVALID_INPUT_LENGTH`, and we're running out of low level error codes.
=> Add parameter validation for ARIA modules

include/mbedtls/camellia.h, library/camellia.c, tests/suites/test_suite_camellia.data, tests/suites/test_suite_camellia.function
__Summary:__ Based on #1643, this PR adds parameter validation for the Camellia module.
__Work left:__ Allocate free error code for `MBEDTLS_ERR_CAMELLIA_BAD_INPUT_DATA`. Slightly annoying because there are already two similar error codes `MBEDTLS_ERR_CAMELLIA_INVALID_KEY_LENGTH` and `MBEDTLS_ERR_CAMELLIA_INVALID_INPUT_LENGTH`, and we're running out of low level error codes.
=> Add parameter validation for Camellia module

include/mbedtls/blowfish.h, library/blowfish.c, tests/suites/test_suite_blowfish.data, tests/suites/test_suite_blowfish.function
__Summary:__ Based on #1643, this PR adds parameter validation for the Blowfish module.
__Work left:__ Allocate free error code for `MBEDTLS_ERR_BLOWFISH_BAD_INPUT_DATA`. Slightly annoying because there are already two similar error codes `MBEDTLS_ERR_BLOWFISH_INVALID_KEY_LENGTH` and `MBEDTLS_ERR_BLOWFISH_INVALID_INPUT_LENGTH`, and we're running out of low level error codes.
=> Add parameter validation for Blowfish module

library/dhm.c, library/pem.c, library/pk.c, library/rsa.c
These changes were made after closer look into existing context freeing and zeroing functions.
`pk.c`: `ctx->pk_info` could remain non-zeroed
`pem.c`: minor optimization
`rsa.c` and `dhm.c `: As in coding standards requirements, every code statement should be on its own line
**READY**
Yes
development
NO
=> Clear pk context and other minor changes in *_free() procedures

include/mbedtls/config.h
__Summary:__ This PR  improves the documentation of the compile time configurations `MBEDTLS_SSL_{MAX/IN/OUT}_CONTENT_LEN`, fixing #2062.
__Internal Reference:__ IOTSSL-2565.
=> Clarify documentation of MBEDTLS_SSL_{MAX/IN/OUT}_CONTENT_LEN

tests/scripts/basic-build-test.sh
The invocation of `compat.sh` that runs those tests was added in all.sh but
not here, resulting in our reported coverage figures being slightly lower than
what we actually test. Fixing that omission change the figures reported from:
```
Lines Tested       : 19105 of 22623 84.4%
Functions Tested   : 1392 of 1460 95.3%
```
to:
```
Lines Tested       : 19126 of 22623 84.5%
Functions Tested   : 1399 of 1460 95.8%
```
It requires `$OPENSSL_NEXT` to be set and point to an OpenSSL version in the
1.1.1 line or later.
**READY**
NO - the features are not present in maintained branches.
NO
Run `tests/basic-build-test.sh` before and after the PR.
=> Add ARIA and ChachaPoly to basic-build-test

tests/ssl-opt.sh
This is a continuation of what was done in #1990 and #1988 but we missed those two at the time: even though the underlying bug was known, we didn't notice at that time that those test could trigger it too.
Whether the bug is triggered or not depends not only on the seed used, but also on subtle timing differences, so using a fixed seed is not enough.
This is temporary until we fix the GnuTLS version available in our CI.
While not strictly related to PSA, it supports it in that, at least on my machine, the random failure seems to happen more often in the builds used to test the submodule PR in `all.sh` (perhaps because they're debug which slightly influences the timing). It has been confirmed that those more frequent failures are indeed occurence of the known old-GnuTLS bug, and nothing …
=> PSA: support: Disable test that trigger bug in old GnuTLS

ChangeLog, include/mbedtls/ssl.h
=> Backport 2.1: Clarify documentation of ssl_set_own_cert()

ChangeLog, include/mbedtls/ssl.h
=> Backport 2.7: Clarify documentation of ssl_set_own_cert()

ChangeLog, include/mbedtls/aes.h, include/mbedtls/arc4.h, include/mbedtls/base64.h, include/mbedtls/bignum.h, include/mbedtls/camellia.h, include/mbedtls/ctr_drbg.h, include/mbedtls/des.h, include/mbedtls/dhm.h, include/mbedtls/gcm.h, include/mbedtls/md2.h, include/mbedtls/md4.h, include/mbedtls/md5.h, include/mbedtls/pkcs5.h, include/mbedtls/ripemd160.h, include/mbedtls/rsa.h, include/mbedtls/sha1.h, include/mbedtls/sha256.h, include/mbedtls/sha512.h, include/mbedtls/x509.h, include/mbedtls/xtea.h
Add the `MBEDTLS_SELF_TEST` precompilation surrounding the self test functions,
which were missing this check in the header files. ( most of the header files were missing this check).
Addresses issue #971
=> Add `MBEDTLS_SELF_TEST` check in header files

ChangeLog, library/bignum.c
__Context:__ The function `mbedtls_mpi_fill_random()` uses a large temporary stack buffer to hold the random data before importing it into the target MPI.
__Problem:__ This is inefficient both computationally and memory-wise. Memory-wise, it may lead to a stack overflow on constrained devices with limited stack.
__Fix:__ This commit introduces the following changes to get rid of the temporary stack buffer entirely:
1. It modifies the call to the PRNG to output the random data directly into the target MPI's data buffer.
This alone, however, constitutes a change of observable behaviour: The previous implementation guaranteed to interpret the bytes emitted by the PRNG in a big-endian fashion, while rerouting the PRNG output into the target MPI's limb array leads to an interpretation that …
=> Remove temporary stack-buffer from mbedtls_mpi_fill_random()

ChangeLog, tests/suites/test_suite_ccm.data
As described in https://github.com/ARMmbed/mbedtls/issues/1996#issuecomment-441077715 , The test for AD too long should run only when `MBEDTLS_CCM_ALT` is not defined, as this is a limitation in Mbed TLS.
**READY**
Perhaps.
Although the On Target Tests haven't been ontroduced until version 2.13, We may consider backporting this fix
=> Test AD too long only when CCM_ALT not defined

CONTRIBUTING.md
1. Remove the reference to `mbedtls-2.1` since it's End Of Life.
2. Add reference to `mbedtls-2.16` since it's a new LTS branch.
=> Update the LTS branch list in the contributing doc

ChangeLog, include/mbedtls/ecp.h
As there are some definitions that are defined regardless of
whether MBEDTLS_ECP_RESTARTABLE is defined or not, these definitions
need to be moved outside the MBEDTLS_ECP_ALT guards. This is a simple
move as MBEDTLS_ECP_ALT and MBEDTLS_ECP_RESTARTABLE are mutually
exclusive options.
**READY**
To Mbed TLS 2.16 https://github.com/ARMmbed/mbedtls/pull/2336
=> Move ecp_restartable definitions out of the MBEDTLS_ECP_ALT guards

ChangeLog, include/mbedtls/ecp.h
This is the backport to Mbed TLS 2.16 of #2334.
=> Backport 2.16: Move ecp_restartable definitions out of the MBEDTLS_ECP_ALT guards

tests/suites/helpers.function
Fix leak of file descriptor in test code on failure (found by coverity).
This is a backport of https://github.com/ARMmbed/mbedtls/pull/2232
**READY**
=> Backport 2.7: Fix resource leak of file desc in test code

ChangeLog, tests/suites/test_suite_ccm.data
Backport of #2228 to `mbedtls-2.7`
**READY**
=> Backport2.7: Test AD too long only when CCM_ALT not defined

ChangeLog, include/mbedtls/cipher.h, include/mbedtls/platform_util.h, include/mbedtls/poly1305.h
**READY**
Fix for file not found, which was reporting in header files. In header files at mbedlts/include folder, The include path has prefix  "mbedtls/" may cause the header file not be found in the case of  mbedtls as a dynamic/static library.
=> Remove "mbedtls/" prefix in include file path

ChangeLog, programs/pkey/rsa_sign_pss.c
Signed-off-by: Masashi Honma <masashi.honma@gmail.com>
READY
NO  
NO
None
None
make check passed
=> Remove duplicate #include

ChangeLog, library/ecdsa.c
As described in https://github.com/ARMmbed/mbedtls/pull/2124#discussion_r  mbedtls_gen_key() returned a boolean 1 in case there was an error in one of the called functions, which might result in failures for the calling functions, expecting negative error codes .
**READY**
Yes 
`mbedtls-2.7`
`mbedtls-2.16`
=> Ecdsa genkey return proper error

ChangeLog, library/ecdsa.c
This is a backport of a bug fixed as part of #2124 
As described in https://github.com/ARMmbed/mbedtls/pull/2124#discussion_r `mbedtls_gen_key()` returned a boolean `1` in case there was an error in one of the called functions, which might result in failures for the calling functions, expecting negative error codes .
**READY**
=> Backport 2.7: ecdsa genkey return proper error

.gitmodules, include/mbedtls/cipher_internal.h, include/mbedtls/pk.h, include/mbedtls/psa_util.h, include/mbedtls/ssl.h, include/mbedtls/ssl_internal.h, library/cipher.c, library/pk.c, library/pk_wrap.c, library/pkwrite.c, library/ssl_tls.c, programs/ssl/ssl_client2.c, programs/ssl/ssl_server2.c, tests/suites/test_suite_pk.function, tests/suites/test_suite_x509write.function
This PR adapts MbedTLS to the new key slot allocation mechanism. It covers the library, includes, programs and tests. In a separate commit the submodule is updated.
=> PSA: Adapting to the new PSA key slot allocation mechanism

.gitmodules, include/mbedtls/cipher_internal.h, include/mbedtls/pk.h, include/mbedtls/psa_util.h, include/mbedtls/ssl.h, include/mbedtls/ssl_internal.h, library/cipher.c, library/pk.c, library/pk_wrap.c, library/pkwrite.c, library/ssl_tls.c, programs/ssl/ssl_client2.c, programs/ssl/ssl_server2.c, tests/suites/test_suite_pk.function, tests/suites/test_suite_x509write.function
__Summary:__ This PR is based on #2339 and updates the Crypto submodule to the merge commit https://github.com/ARMmbed/mbed-crypto/commit/0b6b87105624b52f1c7c2f9ac4e8e2ff977a58f9 of the sibling https://github.com/ARMmbed/mbed-crypto/pull/22 of #2339. 
This merge introduces the following API changes to the PSA API:
- New hash clone API.
- Modified key policy initialization API: The signature of `psa_key_policy_init` has changed.
- Modified key slot allocation API: `psa_allocate_key()` no longer takes key type and length as arguments.
No changes to the code are yet necessary for the hash clone API, as we haven't used it so far (still to come). The key policy and key slot allocation API change require changes to the code, and this PR makes the necessary adaptations.
__Dependencies:__ 
- …
=> PSA: Update crypto submodule (Hash clone, Key Policy Init, Key slot alloc)

library/ctr_drbg.c
__Summary:__ This PR applies style corrections to `library/ctr_drbg.c`, removing lines above 80 characters in length (apart from an overly long URL which shouldn't be broken up).
__Backports:__ No backports needed.
__Internal Reference:__ IOTSSL-2048
=> Remove lines above 80 characters in library/ctr_drbg.c

programs/ssl/ssl_server2.c
__Summary:__ This PR adds documentation for the (pre-existing) `psk_list` command line parameter of `programs/ssl/ssl_server2` which allows to specify the PSKs+Identities that the server should know.
=> Document `psk_list` parameter of ssl_server2 example program

tests/scripts/mbedtls_test.py
When specific tests fail in a test suite, the test suite would have still returned success in the on Target Tests, and the green tea would mark the test suite as succeeded. This fix adds a member for holding a failed result, and notify_complete with this member value, when finished.
**READY**
NO  
The On Target Tests feature was not introduced on Any LTS branches
NO
Run a test suite using the on Target Tests feature on Green Tea, and have a specific test return error. The whole test suite should be marked as failed
=> Fix false positive result when on Target Tests should fail

tests/scripts/mbedtls_test.py
Fix parsing error that contains special character.
The previous implementation replaced the `:` char with `\n`,
and split on `\n`. Test data containing strings with `\n`
were split as well. Resolves #2193.
The split function caused strings containing `\:` to add
another escape char, resulting in `\\:`. This caused the
tests with the `\:` in the string data to fail.
The fix doesn't replace with `\n`, but splits all `:` that
are not preceded with `\`. After that, removes the preceding `\` char.
**READY**
NO  
=> Fix parsing error of test data

ChangeLog, library/x509_crt.c
=> Fix signed-to-unsigned integer conversion warning in X.509 module

ChangeLog, library/bignum.c
Refactor `mpi_write_hlp()` to not be recursive, to fix stack overflows.
Iterate over the `mbedtls_mpi` division of the radix requested,
until it is zero. Each iteration, put the residue in the next LSB
of the output buffer. Fixes #2190
**READY**
Yes
Which branch?
`mbedtls-2.1`
`mbedtls-2.7`
NO
Tested on Linux machine, K64F, NRF52840_DK
Run the `test_suite_mpi` on embedded platforms.
=> Refactor mpi_write_hlp to not be recursive 

ChangeLog, library/bignum.c
Backport of #2214 to `mbedtls-2.7`
**READY**
=> Backport 2.7: Refactor mpi_write_hlp to not be recursive

library/CMakeLists.txt, tests/scripts/all.sh
This is a backport to `mbedtls-2.7` of #2325 and #2332. The history is slightly different because I went directly for an automatic listing of components.
Tip for reviewers: review the first three commits individually, then the rest of the PR, to make sure that no components got lost or corrupted. Compare the end state of `all.sh` with the state on 2.16 to see that the differences are justified (yotta removal, new components, new tools).
----
Here is a full list of commits from https://github.com/ARMmbed/mbedtls/pull/2325 and the original version of https://github.com/ARMmbed/mbedtls/pull/2332 (saved on the branch https://github.com/gilles-peskine-arm/mbedtls/tree/all_sh-component_detection-2.16-1) and how I backported them:
* 8f073121248d8af5f3b51c0a0f74fd81c3a14a34 "Move the code into …
=> [backport 2.7] all.sh: make it possible to run a subset of the components

programs/ssl/ssl_server2.c
This is the backport to Mbed TLS 2.7 of #2137.
=> Backport 2.7: Document `psk_list` parameter of ssl_server2 example program

ChangeLog, library/x509_crt.c
This is the backport to Mbed TLS 2.16 of #2213, fixing #2212.
=> Backport 2.16: Fix signed-to-unsigned integer conversion warning in X.509 module

include/mbedtls/ssl_internal.h, library/ssl_tls.c, tests/ssl-opt.sh
This PR adapts the mbedtls_ssl_get_key_exchange_md_tls1_2  function to use PSA hashing. 
Note: psa_hash_finish expects a length of the hash buffer. We can either change the API to supply it to mbedtls_ssl_get_key_exchange_md_tls1_2, or expect a buffer of at least MBEDTLS_MD_MAX_SIZE  length and document it. I've decided to use the second option, to avoid API changes. 
I have tested this PR using ssl-opt.sh with a config that had TLS 1 and TLS1_1 commented out, leaving TLS1_2 in. Unfortunately I wasn't able to fully run compat.sh due to a faulty environment configuration - I'm expecting to get these results from the CI.
=> PSA: Adapt mbedtls_ssl_get_key_exchange_md_tls1_2 to PSA hashing

library/ssl_tls.c
This PR introduces a tls_prf_generic implementation using the PSA API. 
I have tested this PR using ssl-opt.sh with a config that had TLS 1 and TLS1_1 commented out, leaving TLS1_2 in. Unfortunately I wasn't able to fully run compat.sh due to a faulty environment configuration - I'm expecting to get these results from the CI.
=> PSA: Implement tls_prf_generic using the PSA API

include/mbedtls/psa_util.h, library/pk_wrap.c, library/pkwrite.c, tests/suites/test_suite_pk.function
__Summary:__ This PR is based on #2376. It updates the crypto submodule to the tip of https://github.com/ARMmbed/mbed-crypto/pull/28, introducing and adapting to the new EC/RSA public key format in PSA.
Sibling https://github.com/ARMmbed/mbed-crypto/pull/28
=> PSA: Update crypto submodule to new RSA/EC public key format

include/mbedtls/ssl_internal.h, library/ssl_tls.c, tests/ssl-opt.sh
This PR introduces running handshake hash computation for TLS 1.2. If MBEDTLS_USE_PSA_CRYPTO is defined, the standard contexts are replaced with PSA ones. I've tested this PR by running ssl-opt.sh tests with a configuration using PSA and tls1.2 only. For SHA384, I'll inspect the CI logs of compat.sh.
=> PSA: ssl_tls: use PSA to compute running handshake hash for TLS 1.2

ChangeLog, tests/suites/test_suite_timing.data, tests/suites/test_suite_timing.function
=> Backport 2.7: Reduce the timing tests complexity

include/mbedtls/check_config.h, include/mbedtls/psa_util.h, include/mbedtls/ssl_internal.h, library/ssl_cli.c, library/ssl_tls.c, tests/scripts/all.sh, tests/ssl-opt.sh, visualc/VS2010/mbedTLS.vcxproj
__Summary:__ This PR adds support for client-side PSA-based pure ECDHE (that is, excluding ECDHE-PSK).
Please see the commit messages for more information.
__Points of discussion:__ So far, the PR cuts corners on efficiency and code sharing in some respects: 
* The peer's public key is stored within the `mbedtls_ssl_handshake_params` structure between the receipt of the `ServerKeyExchange` message and the derivation of the key material in `mbedtls_ssl_derive_keys()` at the end of the handshake. In principle, the premaster secret could be generated straight away when reading the `ServerKeyExchange` message.
* The legacy ECDH context is still unconditionally contained as a field of `mbedtls_ssl_handshake_params`. We might consider adding a bunch of `#define`'s around this to ensure that in …
=> PSA Integration: Add support for client-side PSA-based ECDHE

ChangeLog, tests/suites/test_suite_timing.data, tests/suites/test_suite_timing.function
This PR reduces the complexity of the timing tests to account to the degree to which we may trust underlying platforms.
Fixes https://github.com/ARMmbed/mbedtls/issues/1517
**READY**
YES - 2.16: #2385 - 2.7: #2384
=> Reduce the timing tests complexity

ChangeLog, tests/scripts/all.sh
When all.sh invokes check_headers_in_cpp, a backup config.h exists. This
causes a stray difference vs cpp_dummy_build.cpp. Fix by only collecting
the *.h files in include/mbedtls.
Fixes #2406.
**READY**
[edited by mpg]
- to mbedtls-2.16 - https://github.com/ARMmbed/mbedtls/pull/2412
- mbedtls-2.7 does not have the cpp check so does not need a backport
NO
./tests/scripts/all.sh build_default_make_gcc_and_cxx
=> all.sh: Fix check_headers_in_cpp

tests/suites/test_suite_ecp.function
This PR handles the case of an unused variable warning/error when compiling with parameter validation but without ecp_restartable.
=> Move a restartable ecp context to a conditional compilation block

library/cipher.c, library/ssl_tls.c, library/x509_crt.c, library/x509write_csr.c
It is now required to initialize PSA Crypto operation contexts before
calling psa_*_setup(). Otherwise, one gets a PSA_ERROR_BAD_STATE error.
This PR fixes a few places where missing initialization was noticed, but may not fix all instances (in particular, there may be some initialization issues with operation contexts like `psa_hash_operation_t fin_sha256_psa;` inside `struct mbedtls_ssl_handshake_params`).
**READY**
NO
NO
These missing initializations were noticed when running `./tests/scripts/all.sh -f -r test_use_psa_crypto_full_cmake_asan` after adding state validation type checks to Mbed Crypto. See https://github.com/ARMmbed/mbed-crypto/pull/58 for the PR that adds state validation checks.
=> Initialize PSA Crypto operation contexts

ChangeLog, tests/suites/test_suite_timing.data, tests/suites/test_suite_timing.function
=> Backport 2.16: Reduce the timing tests complexity

ChangeLog, tests/scripts/all.sh
Backport of https://github.com/ARMmbed/mbedtls/pull/2407 to mbedtls-2.16.
CC @pkolbus
=> Backport 2.16: all.sh: Fix check_headers_in_cpp

tests/suites/test_suite_ecp.function
This PR is a backport of https://github.com/ARMmbed/mbedtls/pull/2427.
=> Backport 2.16: Move a restartable ecp context to a conditional compilation block

ChangeLog, tests/ssl-opt.sh
This PR reenables certain tests in `ssl-opt.sh` that have been previously added, but had to be disabled due to issues with 3rd-party software. As a new version of GnuTLS has been installed in the CI infrastructure, we may reliably test Mbed TLS features agains it.
**READY**
Yes
Only 2.16 backport is needed, as 2.7 did not have a relevant feature yet.
NO
None
None
=> Reenable GnuTLS next based tests

ChangeLog, tests/ssl-opt.sh
=> Backport 2.16: Reenable GnuTLS next based tests

ChangeLog, library/certs.c, tests/ssl-opt.sh
closes #1519 
**READY**
`ssl_client1.c` when running with `ssl_server.c` output before:
```
. Seeding the random number generator... ok
. Loading the CA root certificate ... ok (0 skipped)
. Connecting to tcp/localhost/4433... ok
. Setting up the SSL/TLS structure... ok
. Performing the SSL/TLS handshake.../home/iluxonchik/Documents/GitHub/mbedtls/library/ssl_tls.c:4641: x509_verify_cert() returned -9984 (-0x2700)
ok
. Verifying peer X.509 certificate... failed
! The certificate is signed with an unacceptable hash.
```
`ssl_client1.c` when running with `ssl_server.c` output after:
```
. Seeding the random number generator... ok
. Loading the CA root certificate ... ok (0 skipped)
. Connecting to tcp/localhost/4433... ok
. Setting up the SSL/TLS structure... ok
. Performing the SSL/TLS …
```
=> update test RSA certificate to use SHA-256 instead of SHA-1

ChangeLog, library/debug.c
The debugging functions
- `mbedtls_debug_print_ret`,
- `mbedtls_debug_print_buf`,
- `mbedtls_debug_print_ecp`,
- `mbedtls_debug_print_mpi`,
- `mbedtls_debug_print_crt`
return immediately if the SSL configuration bound to the passed SSL context is `NULL`, has no debugging functions configured, or if the debug threshold is below the debugging level. However, they do not check whether the provided SSL context is not `NULL` before accessing the SSL configuration bound to it, therefore leading to a segmentation fault if it is. 
In contrast, the debugging function `mbedtls_debug_print_msg` does check for `ssl != NULL` before accessing `ssl->conf`.
This PR unifies the checks by always returning immediately if `ssl == NULL`.
**Note to gatekeeper:** This should be merged in both development and …
=> Return from debugging routines immediately if SSL context is unset

library/ccm.c, library/gcm.c, library/pkcs5.c
It's easier and more telling to rename the globals used only for test,
rather than rename all the shadowing function arguments.
**READY**
NO
=> Rename globals to avoid shadowing by various function arguments

ChangeLog, programs/pkey/key_app_writer.c
The same bug as reported in #1257 and fixed in #1258 for public key output also exists in the private key output: When writing the private key in DER format, the contents of the file are shifted by one byte, which makes it an invalid DER file.
**READY**
Yes: mbedtls-2.1, mbedtls-2.7
NO
```
programs/pkey/gen_key
programs/pkey/key_app_writer mode=private filename=keyfile.key output_mode=private output_file=keyfile.der output_format=der
programs/pkey/key_app mode=private filename=keyfile.der 
```
Expected result:
```
. Loading the private key ... ok
. Key information    ...
...
```
Actual result:
```
. Loading the private key ... failed
!  mbedtls_pk_parse_keyfile returned -0x3d00
!  Last error was: PK - Invalid key tag or value
```
=> key_app_writer writes invalid private key DER file

ChangeLog, library/bignum.c, tests/scripts/all.sh
Address a finding from Coverity's DEADCODE checker in bignum.c when the default MBEDTLS_MPI_WINDOW_SIZE is used. This doesn't result in incorrect code, but depending on the compiler there may be a very tiny ROM and performance improvement. It also makes for one less finding that users of Coverity & mbed TLS need to look at.
Resolves #2309 
**READY**
NO
NO
n/a
Existing tests cover the default window size. Added test to all.sh for coverage in the case a different size is used.
=> Fix dead code in mbedtls_mpi_exp_mod()

ChangeLog, library/debug.c
This is the backport of #1818 to Mbed TLS 2.7.
=> Backport 2.7: Return from debugging routines immediately if SSL context is unset

tests/CMakeLists.txt, tests/Makefile, tests/scripts/run-test-suites.pl
Backport of #2293.
In 2.7, the list of test suites in `tests/CMakeLists.txt` is fine.
=> Backport 2.7: Add a facility to skip running some test suites

ChangeLog, library/bignum.c, tests/scripts/all.sh
=> Backport 2.7: Fix dead code in mbedtls_mpi_exp_mod()

library/ssl_tls.c, tests/ssl-opt.sh
This is a backport of a particular commit #52c6dc64c675d24b1be65e06d43dd67dc111e762 added in #946.
Before submitting this PR I have reviewed the original commit and ran `ssl-opt` and `compat.sh` locally, having both of them pass.
=> Backport 2.7: Correct length check for DTLS records from old epochs.

ChangeLog, programs/pkey/key_app_writer.c
Backport of #2239 to `mbedtls-2.7`
**READY**
=> Backport 2.7: key_app_writer writes invalid private key DER file

ChangeLog, library/certs.c, tests/ssl-opt.sh
Backport of #1520 to `mbedtls-2.7`
**READY**
=> Backport 2.7: update test RSA certificate to use SHA-256 instead of SHA-1

ChangeLog, library/bignum.c, tests/scripts/all.sh
=> Backport 2.16: Fix dead code in mbedtls_mpi_exp_mod()

ChangeLog, programs/pkey/key_app_writer.c
Backport of #2239 to `mbedtls-2.16`
**READY**
=> Backport 2.16: key_app_writer writes invalid private key DER file

ChangeLog, library/certs.c, tests/ssl-opt.sh
Backport of #1520 to `mbedtls-2.16`
**READY**
=> Backport 2.16: update test RSA certificate to use SHA-256 instead of SHA-1

ChangeLog, library/x509.c
When the time on the target board is not set, the X.509 verification step self-test may fail. When I checked the memory before and after this test, I could see that there was a leak in some memory.
Similar to other self tests, this PR changes using the `goto` command so that buffer free can be performed before returning.
=> x509.c: fix memory leak on self-test

ChangeLog, tests/suites/test_suite_hkdf.function
`test_hkdf` in the hkdf test suites consumed stack of ~6KB with
6 buffers of ~1KB each. This causes stack overflow on some platforms
with smaller stack. The buffer sizes were reduced. By testing, the sizes
can be reduced even further, as the largest seen size is 82 bytes(for okm).
Fixes #2195 
**READY**
HKDF was introduced on version 2.11 , and no LTS branch was created since, so no need for backporting
[edited by mpg] 2.16 backport here: https://github.com/ARMmbed/mbedtls/pull/2364
Run the hkdf test on platforms with stack size of < 6KB
=> Reduce Stack usage of hkdf test function

README.md
Change references to Perl when mentioning building the tests, to Python,
as this is now the script that builds the tests. Fixes #2078.
**READY**
NO  
the legacy branches still use Perl for both building and running the tests. `mbedtls-2.16` needs backporting, but this PR can be merged there as is.
=> Change Perl to Python in test builds documentation

ChangeLog, programs/ssl/ssl_mail_client.c
Fixes the issue  #2337
`Usage` output of `ssl_mail_client` example program has the default port `4433` while the code uses `465` as the correct default for SMTP.
String concatenation helps to avoid such copy-paste mistakes.
**READY
NO
Which branch?
All
NO
=> Fix the default port number in `usage`

ChangeLog, library/bignum.c, tests/suites/test_suite_mpi.data, tests/suites/test_suite_mpi.function
=> Fix 1-byte buffer overflow in mbedtls_mpi_write_string() for negative MPIs

tests/scripts/check-files.py
Backport the changes in `check-files.py` from #2464, to keep the file in synch. All other changes are not applicable: there's no test script in 2.7 that runs pylint, `check-files.py` is the only Python file here, and it's meant to be kept aligned with the version from `development` so there's no point in linting it here.
=> Backport 2.7: Pass Pylint with a reasonable configuration

ChangeLog, programs/ssl/ssl_mail_client.c
Backport of #2368 to `mbedtls-2.7`
**READY**
=> Backport 2.7: Fix the default port number in `usage`

ChangeLog, library/bignum.c, tests/suites/test_suite_mpi.data, tests/suites/test_suite_mpi.function
=> Backport 2.7: Fix 1-byte buffer overflow in mbedtls_mpi_write_string() for negative MPIs

ChangeLog, library/x509.c
Backport of #2106 to `mbedtls-2.7`
**READY**
=> Backport 2.7: x509.c: fix memory leak on self-test

ChangeLog, tests/suites/test_suite_cipher.function
Backport of bugfix from #2463 to `mbedtls-2.7`
**READY**
=> Backport 2.7: Fixes in AEAD cipher test

ChangeLog, tests/suites/test_suite_hkdf.function
Backport of #2192 to `mbedtls-2.16`
**READY**
=> Backport 2.16: Reduce Stack usage of hkdf test function 

ChangeLog, programs/ssl/ssl_mail_client.c
Backport of #2368 to `mbedtls-2.16`
**READY**
=> Backport 2.16: Fix the default port number in `usage`

README.md
Backport of #2366 to `mbedtls-2.16`
**READY**
=> Backport 2.16: Change Perl to Python in test builds documentation

ChangeLog, library/bignum.c, tests/suites/test_suite_mpi.data, tests/suites/test_suite_mpi.function
=> Backport 2.16: Fix 1-byte buffer overflow in mbedtls_mpi_write_string() for negative MPIs

ChangeLog, library/x509.c
Backport of #2106 to `mbedtls-2.16`
**READY**
=> Backport 2.16: x509.c: fix memory leak on self-test

ChangeLog, tests/suites/test_suite_cipher.function
Backport of bugfix from #2463 to `mbedtls-2.16`
**READY**
=> Backport 2.16: Fixes in AEAD cipher test

library/x509_crt.c
Skip extensions that have support in the `oid` layer`, but
no parser found in the x509 layer, in case these are not critical.
**READY**
NO  
Tested with #2536 with the following command:
~~~
./cert_app mode=ssl server_name=os.mbed.com debug_level=3 server_port=443
~~~
`os.mbed.com` certificate has a non critical certificate policies extensions.
This PR is related to #2530 and #2535, so I don't think a ChangeLog entry is required
=> Skip uncritical unsupported extensions

.travis.yml
This is what we do in Jenkins, so it only makes sense to do it here as well.
This will avoid random failures for no other reason than the proxy was
dropping all the messages due to an unlucky PRNG seed.
See https://docs.travis-ci.com/user/environment-variables/ for syntax
**READY**
Yes - all branches (will wait for this one to pass Travis and have at least one approval before backporting)
NO
=> Fix the proxy seed in Travis runs

tests/data_files/Makefile
The file to generate is `server10_int3-bs.pem`, not
`server10-bs_int3-bs.pem`.
**READY**
mbedtls-2.16 - Yes
mbedtls-2.7 - No, no server10_int3-bs.pem present.
NO
=> Fix typo in data_file generator code

tests/scripts/all.sh
This PR handles the removal of crypto-only components from all.sh tests.
More details [here](https://jira.arm.com/browse/IOTSSL-2800).
=> Remove crypto-only related components from all.sh

include/mbedtls/ssl.h, library/ssl_tls.c, programs/ssl/ssl_client2.c, tests/ssl-opt.sh
__Summary:__ This PR adds a new SSL API `mbedtls_ssl_set_verify()` which is analogous to the existing `mbedtls_ssl_conf_verify()` but binds the configured CRT verification callback to the SSL context and not to the SSL configuration.
This is useful for example when the verification callback not only performs generic checks but also needs to remember parts of the peer's CRT chain in a connection-specific location.
__Note:__ I suggest we add a compile-time option guarding the entire CRT verification callback functionality (passing callbacks to `mbedtls_x509_crt_verify()`, `mbedtls_ssl_conf_verify()`, and `mbedtls_ssl_set_verify()`) in order to save code on constrained systems that don't any variant of the verification callback feature, but that can be discussed and implemented elsewhere.
=> Allow context-specific CRT verification callbacks

ChangeLog
Add "Credit to OSS-Fuzz", in addition to Guido Vranken, for identifying
bug #2404.
=> Give credit to OSS-Fuzz for #2404

tests/scripts/all.sh
* Add an out-of-box component to `all.sh`: just run `make`, `make test` and `programs/test/selftest`, without any fancy configuration.
* Run `ssl-opt.sh` on a 32-bit build with ASan.
Internal ref: IOTSSL-2792
=> CI improvements: add out-of-box, more 32-bit

library/ssl_tls.c, tests/ssl-opt.sh
This PR changes the debug level from 1 to 3 for some purely informational PSA-related debug messages. Level 1 should only be used for error messages.
=> Fix debug level in informational log messages

ChangeLog, programs/test/cpp_dummy_build.cpp
Add missing header so that all.sh can run to completion. Fixes #2579.
**READY**
NO
NO
Run `./tests/scripts/all.sh build_default_make_gcc_and_cxx`
=> cpp_dummy_build: Add missing header psa_util.h

ChangeLog
Backport of https://github.com/ARMmbed/mbedtls/pull/2555
Add "Credit to OSS-Fuzz", in addition to Guido Vranken, for identifying
bug #2404.
=> Backport 2.7: Give credit to OSS-Fuzz for #2404

tests/scripts/all.sh
* Add an out-of-box component to `all.sh`: just run `make`, `make test` and `programs/test/selftest`, without any fancy configuration.
* Run `ssl-opt.sh` on a 32-bit build with ASan.
Internal ref: IOTSSL-2792
Backport of https://github.com/ARMmbed/mbedtls/pull/2559
=> Backport 2.7: CI improvements: add out-of-box, more 32-bit

ChangeLog
Backport of https://github.com/ARMmbed/mbedtls/pull/2555
Add "Credit to OSS-Fuzz", in addition to Guido Vranken, for identifying
bug #2404.
=> Backport 2.16: Give credit to OSS-Fuzz for #2404

tests/scripts/all.sh
* Add an out-of-box component to `all.sh`: just run `make`, `make test` and `programs/test/selftest`, without any fancy configuration.
* Run `ssl-opt.sh` on a 32-bit build with ASan.
Internal ref: IOTSSL-2792
Backport of https://github.com/ARMmbed/mbedtls/pull/2559
=> Backport 2.16: CI improvements: add out-of-box, more 32-bit

ChangeLog, library/oid.c, tests/suites/test_suite_oid.data, tests/suites/test_suite_oid.function
Add oid x509 extensions support and add the certificate policy oid.
**READY**
NO
=> Add certificate policy oid x509 extension

tests/suites/test_suite_cipher.function
The documentation doesn't explicitly say whether it's allowed or not.
This currently works with the default software implementation, but
only by accident. It isn't guaranteed to work with new ciphers or with
alternative implementations of individual ciphers, and it doesn't work
with the PSA wrappers. So don't do it.
Alternative to https://github.com/ARMmbed/mbedtls/pull/2581
Follow-up that documents that this is forbidden and add a check and a test: https://github.com/ARMmbed/mbedtls/pull/2584
=> Don't call mbedtls_cipher_setkey twice

ChangeLog, include/mbedtls/asn1write.h, include/mbedtls/bignum.h, include/mbedtls/padlock.h, include/mbedtls/x509_crt.h, library/aes.c, library/ccm.c, library/chacha20.c, library/des.c, library/ecp.c, library/ecp_curves.c, library/havege.c, library/md4.c, library/md5.c, library/oid.c, library/poly1305.c, library/ripemd160.c, library/sha1.c, library/sha256.c, library/sha512.c, library/x509.c, library/x509_crt.c, programs/ssl/ssl_server2.c, programs/test/benchmark.c
__Summary:__ This PR improves hygiene and formatting of macro definitions throughout the library. Specifically:
- It adds brackets around parameters to avoid unintended interpretation of arguments, e.g. due to operator precedence.
- It adds uses of the `do { ... } while( 0 )` idiom for macros that can be used as commands.
__Internal Reference:__ IOTSSL-1834.
__Backports:__ Backported missing parentheses is public, documented macro `MBEDTLS_X509_ID_FLAG` in #2094 and #2093.
=> Add missing brackets around macro parameters

ChangeLog, programs/ssl/ssl_server2.c
Add checks in `ssl_server2` that `MBEDTLS_X509_CRL_PARSE_C` is defined
to fix compilation issue. Fixes #560.
**READY**
Yes
* The bug reporter supplied a patch, but hasn't accepted the CLA yet, so I haven't looked at the patch.
* I have checked unsetting other configurations in the sni_entry (`MBEDTLS_X509_CRT_PARSE_C` and `MBEDTLS_PK_C`), but both of the are dependencies, wither direct or indirect of `MBEDTLS_SSL_SERVER_NAME_INDICATION` causing `check_config.h` to fail, so no problem in this case.
* unset `MBEDTLS_X509_CRL_PARSE_C` in the configuration
* build the sample applications
=> Add guards for MBEDTLS_X509_CRL_PARSE_C in sample

tests/scripts/list-identifiers.sh
When doing ABI/API checking, its useful to have a list of all the identifiers that are defined in the internal header files, as we do not promise compatibility for them. This option allows for a simple method of getting them for use with the ABI checking script.
**READY**
Yes, to 2.16 and 2.7
=> Add --internal option to list-identifiers.sh

tests/scripts/all.sh
Require mingw gcc version 6 or greater in order to ensure
BCryptGenRandom() is available.
This should enable https://github.com/ARMmbed/mbedtls/pull/1453 to pass CI after it is rebased.
Along with merging this PR, CI must be updated to run all.sh's mingw64 job on a supported platform, like Ubuntu 18.04.
**READY**
NO  - LTS branches don't depend on BCryptGenRandom(), so they can run mingw tests fine with older gcc.
NO
=> all.sh: Require i686-w64-mingw32-gcc version >= 6

ChangeLog, include/mbedtls/x509_crt.h
__Summary:__ 
The `id` parameter of the public `MBEDTLS_X509_ID_FLAG` macro was used in a subtraction without being surrounded by parentheses. Since some operators bind less strongly than subtraction, this could lead to erroneous evaluation of `MBEDTLS_X509_ID_FLAG`. For example, `MBEDTLS_X509_ID_FLAG( 1 << 2 )` would evaluate evaluate to
`1 << ( 1 << 2 - 1 ) == 1 << ( 1 << 1 ) == 4`
instead of the intended
`1 << ( ( 1 << 2 ) - 1 ) == 1 << ( 4 - 1 ) == 8`.
This PR fixes this by adding parentheses about the `id` parameter in the definition of `MBEDTLS_X509_ID_FLAG`.
__Internal Reference:__ IOTSSL-1834
Partial backport of #2092 to Mbed TLS 2.7.
=> Backport 2.7: Add missing parentheses around parameter in MBEDTLS_X509_ID_FLAG

ChangeLog, programs/ssl/ssl_server2.c
Backport of #2540 to `mbedtls-2.7`
**READY**
=> Backport 2.7: Add guards for MBEDTLS_X509_CRL_PARSE_C in sample

scripts/abi_check.py
Backport of #1433, plus two abi checking commits from #2146 and a backport of #2480. This should add the abi checking script to mbedtls-2.7 and bring it up to date with development.
**READY**
=> Backport 2.7 Extend abi check functionality

ChangeLog, programs/ssl/ssl_server2.c
Backport of #2540 to `mbedtls-2.16`
**READY**
=> Backport 2.16: Add guards for MBEDTLS_X509_CRL_PARSE_C in sample

ChangeLog, include/mbedtls/asn1write.h, include/mbedtls/bignum.h, include/mbedtls/padlock.h, include/mbedtls/x509_crt.h, library/aes.c, library/ccm.c, library/chacha20.c, library/des.c, library/ecp.c, library/ecp_curves.c, library/havege.c, library/md4.c, library/md5.c, library/oid.c, library/poly1305.c, library/ripemd160.c, library/sha1.c, library/sha256.c, library/sha512.c, library/x509.c, library/x509_crt.c, programs/ssl/ssl_server2.c, programs/test/benchmark.c
This is a straightforward backport of https://github.com/ARMmbed/mbedtls/pull/2092 .
I made a full backport, not just a backport of the one user-facing macros that was actually broken (`MBEDTLS_X509_ID_FLAG`), because this is a very low-risk change and keeping the code aligned will make future backports easier.
=> Backport 2.16: Add missing brackets around macro parameters

CMakeLists.txt
Fixes https://github.com/ARMmbed/mbedtls/issues/1496 
Edited by roneld to use [github key words](https://help.github.com/en/articles/closing-issues-using-keywords)
**READY
YES
Since this issue introduce from 2.7.x, so if some one want build it on windows platform with Cmake, this patch should be apply. 
[Edit] Since this issue is introduced since 2.7.x, this PR requires bacporting to `mbedtls-2.7` and `mbedtls-2.16`
NO
Test on
- Ubuntu 16.04.2  cmake version 3.10.2 
- Cygwin cmake version 3.11.1
- Windows mingw-w6 x86_64-8.1.0-posix-seh-rt_v6-rev0 and  cmake version 3.11.1
=> Fix CMake build error on Windows platform

CMakeLists.txt
=> Backport 2.7: Fix CMake build error on Cygwin and minGW platforms

CMakeLists.txt
=> Backport 2.16: Fix CMake build error on Cygwin and minGW platforms

scripts/abi_check.py
Enabling the USE_CRYPTO_SUBMODULE option causes problems if the
crypto submodule isn't present. Only enable it if the submodule
actually exists.
**READY**
Yes, to 2.16 and 2.7
=> Only use the crypto submodule if present in ABI check

scripts/abi_check.py
This is the 2.7 backport of #2636.
=> [Backport 2.7] Only use the crypto submodule if present in ABI check 

scripts/abi_check.py
This is the 2.16 backport of #2636.
=> [Backport 2.16] Only use the crypto submodule if present in ABI check 

ChangeLog, include/mbedtls/ssl.h
=> Backport 2.7: Reword ssl_conf_max_frag_len documentation to clarify its necessity

ChangeLog, include/mbedtls/ssl.h
=> Backport 2.16: Reword ssl_conf_max_frag_len documentation to clarify its necessity

ChangeLog, include/mbedtls/ssl.h
This PR is supposed to fix #2258 by increasing precision of the max fragment length API documentation.
YES - 2.16 and 2.7
=> Reword ssl_conf_max_frag_len documentation to clarify its necessity

tests/scripts/all.sh, tests/scripts/check-names.sh, tests/scripts/list-symbols.sh
We've observed that sometimes check-names.sh exits unexpectedly with
status 2 and no error message. The failure is not reproducible. This
commits makes the script print a trace if it exits unexpectedly.
=> Print a command trace if the check-names.sh exits unexpectedly

tests/scripts/list-symbols.sh
When running make with parallelization, running both "clean" and "lib"
with a single make invocation can lead to each target building in
parallel. It's bad if lib is partially done building something, and then
clean deletes what was built. This can lead to errors later on in the
lib target.
$ make -j9 clean lib
CC    aes.c
CC    aesni.c
CC    arc4.c
CC    aria.c
CC    asn1parse.c
CC    ./library/error.c
CC    ./library/version.c
CC    ./library/version_features.c
AR    libmbedcrypto.a
ar: aes.o: No such file or directory
Makefile:120: recipe for target 'libmbedcrypto.a' failed
make[2]: *** [libmbedcrypto.a] Error 1
Makefile:152: recipe for target 'libmbedcrypto.a' failed
make[1]: *** [libmbedcrypto.a] Error 2
Makefile:19: recipe for target 'lib' failed
make: *** [lib] Error 2
make: *** …
=> test: Always use `make clean` by itself

tests/scripts/list-symbols.sh
Backport of https://github.com/ARMmbed/mbedtls/pull/2664
=> Backport 2.7: test: Always use `make clean` by itself

tests/scripts/list-symbols.sh
Backport of https://github.com/ARMmbed/mbedtls/pull/2664
=> Backport 2.16: test: Always use `make clean` by itself

CMakeLists.txt, include/CMakeLists.txt
For projects that do not require testing, creating  symbolic links prevents the source tree from being placed in a network drive and causes issues when building on Windows with MSYS.
=> Create symbolic links only when ENABLE_TESTING is ON

CMakeLists.txt, include/CMakeLists.txt
Backports #2654 to mbedtls 2.7
=> Backport 2.7: Create symbolic links only when ENABLE_TESTING is ON

CMakeLists.txt, include/CMakeLists.txt
Backports https://github.com/ARMmbed/mbedtls/pull/2654 to mbedtls 2.16
=> Backport 2.16: Create symbolic links only when ENABLE_TESTING is ON

library/ssl_tls.c, tests/scripts/all.sh, tests/suites/test_suite_ssl.function
When MBEDTLS_SSL_ENCRYPT_THEN_MAC is enabled, but not
MBEDTLS_SSL_SOME_MODES_USE_MAC, mbedtls_ssl_derive_keys() and
build_transforms() will attempt to use a non-existent `encrypt_then_mac`
field in the ssl_transform.
```
Compile [ 93.7%]: ssl_tls.c
[Error] ssl_tls.c@865,14: 'mbedtls_ssl_transform {aka struct mbedtls_ssl_transform}' ha
s no member named 'encrypt_then_mac'
[ERROR] ./mbed-os/features/mbedtls/src/ssl_tls.c: In function 'mbedtls_ssl_derive_keys'
:
./mbed-os/features/mbedtls/src/ssl_tls.c:865:14: error: 'mbedtls_ssl_transform {aka str
uct mbedtls_ssl_transform}' has no member named 'encrypt_then_mac'
transform->encrypt_then_mac = session->encrypt_then_mac;
^~
```
Change mbedtls_ssl_derive_keys() and build_transforms() to only access
`encrypt_then_mac` if `encrypt_then_mac` is …
=> ssl: Don't access non-existent encrypt_then_mac field

ChangeLog, programs/ssl/ssl_client2.c, programs/ssl/ssl_server2.c
This is a very partial backport of #2260 to Mbed TLS 2.7, fixing #2254. Because the backporting the original changes lead to conflicts I didn't have the time to resolve, I restricted to fixing the part which goes beyond a test enhancement, namely fixing `ssl_client2`'s and `ssl_server2`'s behaviour in case `MBEDTLS_CERTS_C` is enabled but `MBEDTLS_PEM_PARSE_C` is disabled (as @RonEld requested).
=> Backport 2.7: Add DER encoded test CRTs to library/certs.c 

scripts/abi_check.py
Backport of #2661 to mbedtls-2.7
=> Backport 2.7: Remove all abi dumps, not just ones shared between versions

programs/test/udp_proxy.c
This is the backport of #2694 to Mbed TLS 2.7, fixing #2693 (the other issue #2692 which #2694 fixes does not apply to 2.7).
=> Backport 2.7: Fix UDP proxy incorrectly dissecting CID-based datagrams into records

scripts/abi_check.py
Backport of #2661 to mbedtls-2.16
=> Backport 2.16: Remove all abi dumps, not just ones shared between versions

scripts/abi_check.py
While the abi-checking script handled comparing only the modules that were shared between the old and new versions correctly, the cleanup of the abi dumps only removed what was shared. Change the cleanup logic to remove all abi dumps instead.
**READY**
Yes, to 2.16 and 2.7
=> Remove all abi dumps, not just ones shared between versions

scripts/abi_check.py
The abi checking script was mistakenly removing removed symbols from the output. This fixes issue #2672.
=> Show removed symbols in abi check

programs/test/udp_proxy.c
__Background:__ This PR fixes a memory corruption in the UDP proxy that showed up for the first time in a CI run for the unrelated internal PR r567. @gilles-peskine-arm has independently documented it in #2692 #2693.
__Summary:__ To prevent dropping the same message over and over again, the UDP proxy test application `programs/test/udp_proxy` _logically_ maintains a mapping from records to the number of times the record has already been dropped, and stops dropping once a configurable threshold (currently 2) is passed.
However, the actual implementation deviates from this logical view in two crucial respects:
- To keep the implementation simple and independent of implementations of suitable map interfaces, it only counts how many times a record of a given _size_ has been dropped, and stops …
=> Fix UDP proxy incorrectly dissecting CID-based datagrams into records

ChangeLog, doxygen/input/doc_mainpage.h, doxygen/mbedtls.doxyfile, include/mbedtls/version.h, library/CMakeLists.txt, library/Makefile, tests/suites/test_suite_version.data
Increase the SO versions of libmbedx509 and libmbedtls due to the
addition of fields in publicly visible (non-opaque) structs:
- mbedtls_ssl_config
- mbedtls_ssl_context
- mbedtls_x509_crt
**READY**
NO
NO
=> Update library version to 2.18.0

ChangeLog, tests/Makefile, tests/suites/helpers.function
This is a backport of #2053.
Dependent on configured options, not all of the helper functions were being used, which was leading to warning of unused functions with Clang.
To avoid any complex compile time options, or adding more logic to `generate_test_code.py` to screen out unused functions, those functions which were provoking the warning were changed to remove static, remove them from file scope, and expose them to the linker.
Fixes #2051.
**READY**
- [ n/a ] Tests
- [ n/a ] Documentation
=> Backport 2.7: Change file scoping of test helper functions

tests/scripts/all.sh
For unit tests and sample programs, CFLAGS=-m32 is enough to get a
32-bit build, because these programs are all compiled directly
from *.c to the executable in one shot. But with makefile rules that
first build object files and then link them, LDFLAGS=-m32 is also
needed.
This is the one commit of #2697 that is applicable to 2.7.
=> 2.7 only: Pass -m32 to the linker as well

ChangeLog, tests/Makefile, tests/suites/helpers.function
Dependent on configured options, not all of the helper functions were being used, which was leading to warning of unused functions with Clang.
To avoid any complex compile time options, or adding more logic to `generate_test_code.py` to screen out unused functions, those functions which were provoking the warning were changed to remove static, remove them from file scope, and expose them to the linker.
Fixes #2051.
**READY**
NO
=> Change file scoping of test helper functions

tests/scripts/all.sh
This is the 2.16 backport of https://github.com/ARMmbed/mbedtls/pull/2614
=> [Backport 2.16] Use 'config.pl baremetal' in all.sh

tests/scripts/all.sh
We added some time ago a `baremetal` target to `scripts/config.pl` for the purpose of using that in testing, but we aren't taking advantage of it in `all.sh`, resulting in duplicated code. This PR fixes that.
**READY**
Yes, as this touches tests. 
- 2.16: #2615
- 2.7: #2616
=> Use 'config.pl baremetal' in all.sh

programs/ssl/ssl_client2.c, programs/ssl/ssl_server2.c
Improve maintenance and usage of SSL test programs by adding a reproducible mode to sample programs :
- initialize the PRNG to a constant seed 
- using a faketime
**READY**
NO  
NO
See #1272 and https://github.com/ARMmbed/mbedtls/pull/1622#issuecomment-499592417 cc @gilles-peskine-arm 
- [?] Tests
- [?] Documentation
=> SSL reproducible test mode

ChangeLog, library/havege.c
The elements of the [HAVEGE](https://www.irisa.fr/caps/projects/hipsor/publications/havege-rr.pdf) state are manipulated with bitwise operations, with the expectations that the elements are 32-bit unsigned integers (or larger). But they are declared as `int`, and so the code has undefined behavior. Clang with Asan correctly points out some shifts that reach the sign bit.
Use `unsigned` internally, which violates strict aliasing rules but is less likely to be compiled in an unintended manner than overflowing a signed integer.
Backport of #2699 to fix #2598. Same approach as the 2.16 backport in https://github.com/ARMmbed/mbedtls/pull/2700.
=> Backport 2.7: Fix misuse of signed ints in the HAVEGE module

ChangeLog, library/havege.c
The elements of the [HAVEGE](https://www.irisa.fr/caps/projects/hipsor/publications/havege-rr.pdf) state are manipulated with bitwise operations, with the expectations that the elements are 32-bit unsigned integers (or larger). But they are declared as `int`, and so the code has undefined behavior. Clang with Asan correctly points out some shifts that reach the sign bit.
Use `unsigned` internally, which violates strict aliasing rules but is less likely to be compiled in an unintended manner than overflowing a signed integer.
Backport of #2699 to fix #2598. Unlike https://github.com/ARMmbed/mbed-crypto/pull/149, this pull request doesn't change the API at all, since it's for a long-time support branch.
=> Backport 2.16: Fix misuse of signed ints in the HAVEGE module

ChangeLog, include/mbedtls/havege.h
The elements of the [HAVEGE](https://www.irisa.fr/caps/projects/hipsor/publications/havege-rr.pdf) state are manipulated with bitwise operations, with the expectations that the elements are 32-bit unsigned integers (or larger). But they are declared as `int`, and so the code has undefined behavior. Clang with Asan correctly points out some shifts that reach the sign bit.
Since these are supposed to be 32-bit unsigned integers, declare them as `uint32_t`.
This is technically an API break, since the type `mbedtls_havege_state` is exposed in a public header. However normal applications should not be affected.
Fix https://github.com/ARMmbed/mbedtls/issues/2598
PR extracted from https://github.com/ARMmbed/mbedtls/pull/2684 which combined this with other things needed to pass Clang+Asan with …
=> Fix misuse of signed ints in the HAVEGE module

ChangeLog, tests/compat-in-docker.sh, tests/docker/bionic/Dockerfile, tests/docker/xenial/Dockerfile, tests/make-in-docker.sh, tests/scripts/all-in-docker.sh, tests/scripts/basic-in-docker.sh, tests/scripts/docker_env.sh, tests/ssl-opt-in-docker.sh
Adds a Dockerfile and some test scripts per #2313 
**READY**
NO  
NO
I picked Ubuntu 16.04 LTS since it's an older release that I'm familiar with, and one with some support left in it. If you'd be happier with a different base distribution let me know. I'm also not sure if there would be more preferred versions of openssl and gnutls.
This is my first PR, so there's probably something else I'm missing about the contribution process or patch too. Happy to take care of anything you flag in review.
Backporting to 2.16 may be useful but not required.
On a Linux x86_64 box with a recent Docker properly installed, run tests/scripts/all-in-docker.sh or tests/scripts/basic-in-docker.sh.
=> Add docker-based test scripts

CMakeLists.txt, ChangeLog, README.md, library/CMakeLists.txt, programs/test/cmake_subproject/.gitignore, programs/test/cmake_subproject/CMakeLists.txt, programs/test/cmake_subproject/cmake_subproject.c, tests/scripts/all.sh
Remove use of CMAKE_SOURCE_DIR in case mbedtls is built from within
another CMake project. Define MBEDTLS_DIR to ${CMAKE_CURRENT_SOURCE_DIR}
in the main CMakeLists.txt file and refer to that when defining target
include paths to enable mbedtls to be built as a sub project.
Fixes #2609
Signed-off-by: Ashley Duncan <ashes.man@gmail.com>
Signed-off-by: Jaeden Amero <jaeden.amero@arm.com>
* Will need to point to a crypto submodule containing https://github.com/ARMmbed/mbed-crypto/pull/152 on the mbed-crypto/development branch
NO  - but may be useful in a 2.18.1
NO
=> Enable use of Mbed TLS as a CMake subproject

ChangeLog, library/x509_crt.c
=> Deref pointer when using sizeof in x509_get_other_name

scripts/abi_check.py
Show the commit ID in the ABI checker output. This is useful in logs like we get for the “ABI/API checking” CI job where the versions that are being compared are currently only reported as `FETCH_HEAD` and `HEAD`.
Also, pass Pylint.
=> ABI checker: show the commit ID

tests/scripts/all.sh
We accidentally disabled testing with MBEDTLS_ECP_RESTARTABLE. Re-enable
testing with restartable ECP when MBEDTLS_USE_PSA_CRYPTO is not set.
Fixes 971dea37453c ("Enable USE_PSA_CRYPTO with config.pl full")
Internal Reference: https://jira.arm.com/browse/IOTSSL-2848
**READY**
NO 
NO
- ~[ ] Changelog updated~
=> Test with MBEDTLS_ECP_RESTARTABLE

tests/compat.sh, tests/ssl-opt.sh
Backport of https://github.com/ARMmbed/mbedtls/pull/2727/
=> Backport 2.7: tests: Limit each log to 10 GiB

tests/compat.sh, tests/ssl-opt.sh
Backport of https://github.com/ARMmbed/mbedtls/pull/2727/
=> Backport 2.16: tests: Limit each log to 10 GiB

tests/scripts/mbedtls_test.py, tests/suites/target_test.function
Update `mbedtls_test.py` script to work with Python 3.7.
resolves #2653
**READY**
Possibly, since this is in our test infrastructure, but the On Target Tests is not introduced yet in `mbedtls-2.7` ( It will be in #2075 )
The CI will possibly need to change
Ran the script with the entropy on target test
=> update the test script

tests/compat.sh, tests/ssl-opt.sh
Limit log output in compat.sh and ssl-opt.sh, in case of failures with these
scripts where they may output seemingly unlimited length error logs.
**READY**
Yes - 2.16, 2.7
- ~[ ] Changelog updated~
=> tests: Limit log output to 10 GiB

CMakeLists.txt, ChangeLog, README.md, include/mbedtls/platform.h, library/CMakeLists.txt, programs/test/cmake_subproject/.gitignore, programs/test/cmake_subproject/CMakeLists.txt, programs/test/cmake_subproject/cmake_subproject.c, tests/scripts/all.sh
This PR aims to make Mbed TLS 2.18.1 comprising:
- Minimal cherry-pick from https://github.com/ARMmbed/mbedtls/pull/2711 for including `stdarg.h` where needed
- Cherry-pick of all commits from https://github.com/ARMmbed/mbedtls/pull/2706 to enable building Mbed TLS as a CMake subproject
Cherry-pick is used because #2711 and #2706 are based on commits beyond 2.18.0 and would bring in too many other changes if merged. The aim is to bring in the two above mentioned changes without anything else.
**READY**
NO  
NO
=> Backport 2.18: CMake subproject and stdarg.h

scripts/abi_check.py
Due to how the checking script is run in docker, worktree_rev is
ambiguous when running rev-parse. We're running it in the checked
out worktree, so we can use HEAD instead, which is unambiguous.
=> Change worktree_rev to HEAD for rev-parse

scripts/abi_check.py
=> Backport 2.16: Change worktree_rev to HEAD for rev-parse

scripts/abi_check.py
=> Backport 2.7: Change worktree_rev to HEAD for rev-parse

tests/suites/helpers.function, tests/suites/host_test.function, tests/suites/main_test.function
__Summary:__ This PR adds a macro `TEST_ASSUME` to the test infrastructure which allows to skip tests based on unmet conditions determined at runtime.
Backports: 2.16 (#2735), not directly applicable to 2.7 which has the old test framework.
=> Add TEST_ASSUME macro to allow skipping tests at runtime

tests/suites/helpers.function, tests/suites/host_test.function, tests/suites/main_test.function
This is the backport to 2.16 of #2734.
=> 2.16: Add TEST_ASSUME macro to allow skipping tests at runtime

ChangeLog
Add changelog entry for #2418 to acknowledge #2357. Backport of #2773.
=> Backport 2.7: Changelog entry for test certificates update

ChangeLog
Add changelog entry for #2419 to acknowledge #2357. Backport of #2773.
=> Backport 2.16: Changelog entry for test certificates update

programs/fuzz/onefile.c, tests/scripts/all.sh
Test build modes that we document.
I believe that with this PR, we're testing all the non-debug build modes that we document in `README.md` or `configs/README.txt`.
* `-DMBEDTLS_CONFIG_FILE="…"`
* Shared library build with cmake (we were only testing a shared library build with make)
=> Test documented builds

ChangeLog, library/ecdsa.c
Forward-port of #2751 to `development`. Mirrored in Mbed Crypto as https://github.com/ARMmbed/mbed-crypto/pull/184.
=> Fix fragile method for passing from ECDSA to ECP restart contexts

ChangeLog, include/mbedtls/bn_mul.h, tests/scripts/all.sh
Fix the build on ARMv5TE in ARM mode. The assembly code in `bn_mul.h` uses DSP instructions that are not available on this particular architecture, so set the conditional compilation directives to exclude them.
Fix originally contributed in #2169 by @aurel32. I rebased to current development to facilitate testing and added a changelog entry and a non-regression test.
Needs backport to 2.16: #2778. The offending code is not present in 2.7.
=> bn_mul.h: require at least ARMv6 to enable the ARM DSP code

tests/compat.sh
Old versions of OpenSSL didn't support DTLS 1.2, but our default version has been 1.0.2g for over two years, and it does support DTLS 1.2.
Our reference legacy OpenSSL (1.0.1j) doesn't support DTLS 1.2, and we do invoke it in some tests that include DTLS 1.2 and legacy ciphers. So check whether the version of OpenSSL we're using supports DTLS 1.2, and skip it only if it isn't supported.
Internal ref: IOTSSL-2892
=> Don't exclude DTLS1.2 in OpenSSL

tests/scripts/all.sh
Test build modes that we document.
I believe that with this PR, we're testing all the non-debug build modes that we document in `README.md` or `configs/README.txt`.
* `-DMBEDTLS_CONFIG_FILE="…"`
* Shared library build with cmake (we were only testing a shared library build with make)
Straightforward backport of #2728
=> Backport 2.16: Test documented builds

ChangeLog, library/ecdsa.c
All modules using restartable ECC operations support passing `NULL` as the restart context as a means to not use the feature.
The restart contexts for ECDSA and ECP are nested, and when calling restartable ECP operations from restartable ECDSA operations, the address of the ECP restart context to use is calculated by adding
the to the address of the ECDSA restart context the offset the of the ECP restart context.
If the ECP restart context happens to not reside at offset `0`, this leads to a non-`NULL` pointer being passed to restartable ECP operations from restartable ECDSA-operations; those ECP operations
will hence assume that the pointer points to a valid ECP restart address and likely run into a segmentation fault when trying to dereference the non-NULL but close-to-NULL address.
The …
=> 2.16: Fix fragile method for passing from ECDSA to ECP restart contexts

ChangeLog, tests/suites/test_suite_entropy.function, tests/suites/test_suite_nist_kw.function
Backport of the applicable parts of https://github.com/ARMmbed/mbed-crypto/pull/144 (entropy tests, NIST_KW tests).
=> Backport 2.16: test fixes not revealed by existing builds

ChangeLog, include/mbedtls/bn_mul.h, tests/scripts/all.sh
Fix the build on ARMv5TE in ARM mode. The assembly code in `bn_mul.h` uses DSP instructions that are not available on this particular architecture, so set the conditional compilation directives to exclude them.
Fix originally contributed in #2169 by @aurel32. I rebased to mbedtls-2.16 to facilitate testing and added a changelog entry and a non-regression test.
=> Backport 2.16: bn_mul.h: require at least ARMv6 to enable the ARM DSP code

tests/compat.sh
Exclude DTLS 1.2 only with older OpenSSL. Backport of #2779.
=> Backport 2.16: Don't exclude DTLS1.2 in OpenSSL

tests/scripts/all.sh
Test build modes that we document.
I believe that with this PR, we're testing all the non-debug build modes that we document in `README.md` or `configs/README.txt`.
* `-DMBEDTLS_CONFIG_FILE="…"`
* Shared library build with cmake (we were only testing a shared library build with make)
Straightforward backport of #2728
=> Backport 2.7: Test documented builds

ChangeLog, tests/suites/test_suite_entropy.function
Backport of the applicable parts of https://github.com/ARMmbed/mbed-crypto/pull/144 (entropy tests).
=> Backport 2.7: test fixes not revealed by existing builds

tests/compat.sh
Exclude DTLS 1.2 only with older OpenSSL. Backport of #2779.
=> Backport 2.7: Don't exclude DTLS1.2 in OpenSSL

library/ssl_cli.c, library/ssl_tls.c, programs/ssl/ssl_client2.c, programs/ssl/ssl_server2.c, visualc/VS2010/mbedTLS.vcxproj
This PR updates PSA API as used by Mbed TLS to version 1.0 beta 3. The only exception to this is the multipart key derivation API, which for now is turned off in Mbed Crypto as default.
(See https://armmbed.github.io/mbed-crypto/html/index.html in section Document History.)
Prerequisites:
- https://github.com/ARMmbed/mbed-crypto/pull/212
After the prerequisite has been merged, this PR still needs updating the submodule. I would like to rebase to have 1 commit updating the submodule, instead of 3.
**READY**
NO  
NO
=> Update to PSA 1.0 beta 3
