Mbed-TLS/mbedtls

ChangeLog, include/mbedtls/ssl.h, library/debug.c, library/ssl_tls.c, programs/ssl/ssl_client2.c, programs/ssl/ssl_server2.c, tests/ssl-opt.sh, tests/suites/test_suite_debug.function
See commits. The max_frag_len thing is motivated by Kalle's email.
=> Misc improvements

ChangeLog, library/rsa.c, library/ssl_cli.c, library/ssl_cli.c.orig
Merge of polarssl-1.2-restricted branch, including:
* iotssl-469 - RSA-CRT fix
* Fix for possible client-side NULL pointer dereference
=> Merge of polarssl-1.2-restricted

ChangeLog, include/mbedtls/ctr_drbg.h, include/mbedtls/hmac_drbg.h, include/mbedtls/pkcs11.h, include/mbedtls/ssl.h, include/mbedtls/timing.h, library/ssl_tls.c
=> Fix a fairly common typo in comments

include/mbedtls/config.h
Found by Nicholas Wilson
fixes #288
=> Add missing warning in doc

ChangeLog, include/mbedtls/cipher.h, include/mbedtls/md.h, include/mbedtls/pkcs11.h, include/mbedtls/ssl_internal.h, library/debug.c, library/ecp.c, library/ecp_curves.c
=> Stop macroizing inline in C++

ChangeLog, library/ssl_tls.c
=> Fix handling of non-fatal alerts

include/mbedtls/config.h, include/mbedtls/ssl.h, library/entropy_poll.c, library/net.c, library/timing.c
Improve documentation and error messages around the "semi-portable" parts.
=> Iotssl 591 glue layers

include/mbedtls/rsa.h
This pull request corrects a minor typo in a comment.
=> Fix minor typo in comments

programs/aes/crypt_and_hash.c
=> Fix for #441 - crypt and hash gcm

tests/ssl-opt.sh
The test in `all.sh` that runs `ssl-opt.sh -f SHA-1` with `MBEDTLS_TLS_DEFAULT_ALLOW_SHA1_IN_CERTIFICATES` enabled was failing due to `ssl-opt.sh` assuming that this flag is unset. This commit fixes that.
I'm aware of a problem with this fix: it doesn't ensure that the SHA1 flag in config.h has the correct value. However, this is consistent with other tests in ssl-opt.sh: for example, none of them check that SSLv3 is compile-time disabled by default. We might want to address this at some point in the future, but we should probably treat that as a separate issue from the current one.
=> Fix issue in testing SHA-1 compile-time option

programs/ssl/dtls_client.c
Should be "DTLS" handshake instead of "SSL/TLS"
Make it consistent with dtls_server.c
=> Correct the printf message of the handshake type.

include/mbedtls/asn1.h
**READY**
**Yes**
Which branch?
mbed TLS 2.1 and 1.3
=> Fix typo in asn1.h

.github/issue_template.md, README.md
Change the Arm Trademarks according to updated Trademarks
**READY**
NO  
NO
Addresses #1158
=> Change Arm Trademarks

tests/CMakeLists.txt, tests/suites/helpers.function
Back port from ARMmbed:development
=> Allow test suites to be run on Windows

tests/compat.sh, tests/ssl-opt.sh
Fix a race condition in `compat.sh`: instead of using `sleep 1` to detect whether the server has started, call `lsof` if available, as was already done in `ssl-opt.sh`. In addition to fixing this race condition, which causes CI runs to fail when the machine is heavily loaded, this makes the script faster on a lightly-loaded machine.
I also made some minor improvements to the way `lsof` is called so that on the platforms we care about, there is no tight loop and the detection tends to be a little faster.
Internal ref: IOTSSL-1831
Backport of #1210 minus the DTLS support
=> Backport 1.3: Fix race condition in compat.sh

include/mbedtls/config.h, include/mbedtls/dhm.h, library/dhm.c, library/version_features.c
Add the 'MBEDTLS_DHM_ALT' #Define in order to support the alternate DHM.
**READY/IN DEVELOPMENT/HOLD**
=> cc dhm alt

tests/compat.sh, tests/ssl-opt.sh
=> Backport 2.1: Iotssl 2005 slow start

tests/compat.sh, tests/ssl-opt.sh
Backport of https://github.com/ARMmbed/mbedtls/pull/1286
=> Backport 1.3: Iotssl 2005 slow start

doxygen/mbedtls.doxyfile, include/mbedtls/aes.h, include/mbedtls/ccm.h, include/mbedtls/cipher.h, include/mbedtls/cmac.h, include/mbedtls/ctr_drbg.h, include/mbedtls/dhm.h, include/mbedtls/ecdh.h, include/mbedtls/ecdsa.h, include/mbedtls/gcm.h, include/mbedtls/md.h, include/mbedtls/platform.h, include/mbedtls/rsa.h, include/mbedtls/sha1.h, include/mbedtls/sha256.h, include/mbedtls/sha512.h, library/error.c
All documentation improvement PRs from @RosZad, with minor fixes applied to pass all.sh and resolve merge conflicts
=> Documentation improvements

library/ctr_drbg.c
Signed-off-by: Paul Sokolovsky <paul.sokolovsky@linaro.org>
Notes:
**My developer.mbed.org username is "pfalcon" (the same as on github), and I accepted the CLA by the link above.** This patch, I contribute as a private person, if there're concerns with the email used, I can resubmit the patch with another email.
or for companies or those that do not wish to create an mbed account, a slightly different agreement can be found [here](https://www.mbed.com/en/about-mbed/contributor-license-agreements/)
- The PR follows the [mbed TLS coding standards](https://tls.mbed.org/kb/development/mbedtls-coding-standards)
* This is …
=> ctr_drbg: Typo fix in the file description comment.

library/memory_buffer_alloc.c, library/version.c
This is my first contribution so apologies in advance if I am violently ignoring any guidelines.
=> Fix missing void argument declarations #678

scripts/footprint.sh
Remove Yotta module configuration usd in footprint.sh script
=> Remove Yotta module from footprint.sh script

library/bignum.c
Doesn't matter performance-wise, but still...
=> Remove redundant i increments

ChangeLog, include/mbedtls/ssl.h, library/ssl_tls.c
=> Separate psk and psk_identity buffers free

ChangeLog, include/mbedtls/ecp.h, library/ecp_curves.c
=> Curve25519 order rework 481

scripts/generate_errors.pl
=> Backport 2.1:  Change generate_errors.pl to call perl grep

.github/issue_template.md, README.md
Update the link to the new Mbed TLS forum since it migrated to the new location
**READY**
NO
=> Update the Mbed TLS forum link

.github/issue_template.md, README.md
Backport of #1793 to mbedtls-2.7
**READY**
=> Backport2.7: update forum link

README.md
Backport of #1793 to mbedtls-2.1
**READY**
=> Backport2.1: update forum link

library/CMakeLists.txt, library/entropy_poll.c, library/net_sockets.c, library/timing.c
@sbutcher-arm, @gilles-peskine-arm, sorry about that, here's the new (rebased) PR from #819.
=> library: Port to Haiku.

programs/pkey/key_app.c
This resolves #852. Print the error message, in `key_app`
only if there was an error.
=> Show error message only if there was an error

programs/pkey/key_app.c
Backport of #919 to mbedtls-2.7
**READY**
=> Backport2.7: Show error message only if there was an error

programs/pkey/key_app.c
Backport of #919 to mbedtls-2.1
**READY**
=> Backport2.1: Show error message only if there was an error

ChangeLog, library/ssl_cli.c, tests/ssl-opt.sh
=> Fix bounds check in ssl_parse_certificate_request()

programs/x509/cert_write.c
=> Fix typos in programs/x509/cert_write.c

tests/.jenkins/Jenkinsfile
This PR adds a Jenkinsfile for PR testing.
=> Backport 2.1: Add Jenkinsfile for PR job

tests/.jenkins/Jenkinsfile
This PR adds a Jenkinsfile for PR testing.
=> Backport 2.7: Add Jenkinsfile for PR job

tests/.jenkins/Jenkinsfile
This PR adds a Jenkinsfile for PR testing.
=> Add Jenkinsfile for PR job

README.md, programs/README.md
This is basically a table of contents for the `programs` directory tree.
Backports? Not really needed since people using old versions of the library have already built their app and don't need samples anymore, but would be easy to do.
=> Readme with a short description of each sample program

ChangeLog, include/mbedtls/ssl.h
Fixes #517.
__Internal Reference:__ IOTSSL-835.
=> Improve documentation of mbedtls_ssl_get_verify_result()

tests/scripts/basic-build-test.sh, tests/scripts/run-test-suites.pl
Backport of https://github.com/ARMmbed/mbedtls/pull/2061
=> Backport 2.7: Make the test runner support multiple verbosity modes

include/mbedtls/bignum.h, library/bignum.c, tests/suites/test_suite_mpi.data, tests/suites/test_suite_mpi.function
__Summary:__ Based on #1643, this PR adds parameter validation to the bignum module.
=> Add parameter validation for bignum module

include/mbedtls/dhm.h, library/dhm.c, tests/suites/test_suite_dhm.data, tests/suites/test_suite_dhm.function
__Summary:__ Based on #1643, this PR implements parameter validation for the DHM module.
=> Add parameter validation for the DHM module

include/mbedtls/ecdsa.h, library/ecdsa.c, tests/suites/test_suite_ecdsa.data, tests/suites/test_suite_ecdsa.function
__Summary:__ Based on #1643, this PR adds parameter validation for the ECDSA module.
=> Add parameter validation for ECDSA module

include/mbedtls/ecjpake.h, library/ecjpake.c, tests/suites/test_suite_ecjpake.data, tests/suites/test_suite_ecjpake.function
__Summary:__ Based on #1643, this PR adds parameter validation for the ECJPAKE module.
=> Add parameter validation for ECJPAKE module

include/mbedtls/ecdh.h, library/ecdh.c, tests/suites/test_suite_ecdh.data, tests/suites/test_suite_ecdh.function
__Summary:__ Based on #1643, this PR adds parameter validation for the ECDH module.
=> Add parameter validation for the ECDH module

ChangeLog, include/mbedtls/ssl.h
fixes #507 - see issue description
=> Clarify documentation of ssl_set_own_cert()

tests/suites/helpers.function
Fix leak of file descriptor in test code on failure (found by coverity).
**READY**
Yes
Which branch?
2.7
=> Fix resource leak of file desc in test code

ChangeLog, include/mbedtls/aesni.h, include/mbedtls/asn1write.h, include/mbedtls/base64.h, include/mbedtls/bn_mul.h, include/mbedtls/ccm.h, include/mbedtls/certs.h, include/mbedtls/cmac.h, include/mbedtls/compat-1.3.h, include/mbedtls/ctr_drbg.h, include/mbedtls/ecdh.h, include/mbedtls/ecdsa.h, include/mbedtls/ecjpake.h, include/mbedtls/ecp.h, include/mbedtls/ecp_internal.h, include/mbedtls/error.h, include/mbedtls/gcm.h, include/mbedtls/havege.h, include/mbedtls/hmac_drbg.h, include/mbedtls/net.h, include/mbedtls/padlock.h, include/mbedtls/pem.h, include/mbedtls/pkcs12.h, include/mbedtls/pkcs5.h, include/mbedtls/ssl_cache.h, include/mbedtls/ssl_ciphersuites.h, include/mbedtls/ssl_cookie.h, include/mbedtls/ssl_internal.h, include/mbedtls/ssl_ticket.h
Backport of #1375 to mbedtls 2.7
**READY**
=> Backport 2.7: Include configuration file to headers

ChangeLog, programs/pkey/rsa_sign_pss.c
This is a backport of #2326.
**READY**
=> Backport 2.7: Remove duplicate #include

doxygen/input/doc_mainpage.h, doxygen/mbedtls.doxyfile, include/mbedtls/version.h, library/CMakeLists.txt, tests/suites/test_suite_version.data
This PR changes the library-wide version to 0.0.0
=> Unbump version to 0.0.0

ChangeLog, doxygen/input/doc_mainpage.h, doxygen/mbedtls.doxyfile, include/mbedtls/version.h, library/CMakeLists.txt, tests/suites/test_suite_version.data
=> Update library version to 2.17.0

ChangeLog, doxygen/input/doc_mainpage.h, doxygen/mbedtls.doxyfile, include/mbedtls/version.h, library/CMakeLists.txt, tests/suites/test_suite_version.data
=> Update library version to 2.7.10

ChangeLog, doxygen/input/doc_mainpage.h, doxygen/mbedtls.doxyfile, include/mbedtls/version.h, library/CMakeLists.txt, tests/suites/test_suite_version.data
=> Update library version to 2.16.1

ChangeLog, include/mbedtls/oid.h, library/oid.c, tests/suites/test_suite_oid.data, tests/suites/test_suite_oid.function
Add the Wisun Fan device extended key usage, and tests for extended key usage oid.
**READY**
NO
=> Add Wisun extended key usage

.travis.yml
=> Backport 2.7: Fix the proxy seed in Travis runs

.travis.yml
=> Backport 2.16: Fix the proxy seed in Travis runs

tests/data_files/Makefile
Backport of https://github.com/ARMmbed/mbedtls/pull/2477
=> Backport 2.16: Fix typo in data_file generator code

scripts/abi_check.py
This aims to extend the ABI checking script in a number of ways to more easily check we don't break the ABI with the Crypto submodule.
- Add ability to compare between different repositories.
- Add skipping internal identifiers.
- Add handling for the Crypto submodule.
**READY**
=> Extend abi check functionality

tests/scripts/list-identifiers.sh
=> Backport 2.7 Add --internal option to list-identifiers.sh

scripts/abi_check.py
Backport of #2480, along with two other abi checking commits from #2146. This should bring the abi checking script up to date with development.
**READY**
=> Backport 2.16 extend abi check functionality

tests/scripts/list-identifiers.sh
=> Backport 2.16 Add --internal option to list-identifiers.sh

library/error.c
**READY**
No, LTS branches don't use crypto via a submodule.
NO
=> Update crypto submodule to remove SSL, NET, and X.509 duplication 

tests/scripts/all.sh, tests/scripts/check-names.sh, tests/scripts/list-symbols.sh
Backport of https://github.com/ARMmbed/mbedtls/pull/2647
=> Backport 2.7: Print a command trace if the check-names.sh exits unexpectedly

tests/scripts/all.sh, tests/scripts/check-names.sh, tests/scripts/list-symbols.sh
Backport of https://github.com/ARMmbed/mbedtls/pull/2647
=> Backport 2.16: Print a command trace if the check-names.sh exits unexpectedly

scripts/abi_check.py
=> Backport 2.7: abi check show removed symbols

scripts/abi_check.py
=> Backport 2.16: abi check show removed symbols

programs/test/udp_proxy.c
This is the backport of #2694 to Mbed TLS 2.16, fixing #2693 (the other issue #2692 which #2694 fixes does not apply to 2.16).
=> Backport 2.16: Fix UDP proxy incorrectly dissecting CID-based datagrams into records

ChangeLog, doxygen/input/doc_mainpage.h, doxygen/mbedtls.doxyfile, include/mbedtls/version.h, library/CMakeLists.txt, tests/suites/test_suite_version.data
=> Update library version to 2.7.11

ChangeLog, doxygen/input/doc_mainpage.h, doxygen/mbedtls.doxyfile, include/mbedtls/version.h, library/CMakeLists.txt, tests/suites/test_suite_version.data
=> Update library to 2.16.2

tests/scripts/all.sh
This is the 2.7 backport of #2614
=> [Backport 2.7] Use 'config.pl baremetal' in all.sh

tests/scripts/check-files.py
Backport of https://github.com/ARMmbed/mbedtls/pull/2730
=> Backport 2.7: Allow TODO in code

scripts/abi_check.py
Show the commit ID in the ABI checker output. Straightforward backport of #2729.
=> Backport 2.7: ABI checker: show the commit ID

tests/scripts/check-files.py
Backport of https://github.com/ARMmbed/mbedtls/pull/2730
=> Backport 2.16: Allow TODO in code

scripts/abi_check.py
Show the commit ID in the ABI checker output. Straightforward backport of #2729.
=> Backport 2.16: ABI checker: show the commit ID

ChangeLog, include/mbedtls/pem.h, library/x509write_crt.c
Fixes https://github.com/ARMmbed/mbedtls/issues/2631.
=> Avoid use of large stack buffers in CRT writing

ChangeLog
ChangeLog-only change, to credit @catenacyber's contribution via #2681.
**READY**
NO  
NO
=> ChangeLog: Add ChangeLog entry for #2681

tests/scripts/check-files.py
=> Allow TODO in code

tests/scripts/mbedtls_test.py, tests/suites/target_test.function
Backport of #2660 to `mbedtls-2.16`
**READY**
=> Backport 2.16: update the test script

ChangeLog
Add changelog entry for #2417 to acknowledge #2357.
=> Changelog entry for test certificates update

library/ssl_tls.c
This PR replaces use of the legacy `psa_key_derivation()` function, with the new multipart API.
The solution has been derived from `mbedtls-crypto` test code by changing the variable naming and stripping an unused branch. However, I retained the structure, that allows handling other algorithm types by adding other branches.
Note, when ARMmbed/mbed-crypto#229 has been merged and made avalable for `mbedtls`, this PR will be necessary.
=> Use multipart PSA key derivation API

library/hmac_drbg.c
Backport of https://github.com/ARMmbed/mbed-crypto/pull/238/
=> Backport 2.16: HMAC DRBG: Split entropy-gathering requests to reduce request sizes

ChangeLog, doxygen/input/doc_mainpage.h, doxygen/mbedtls.doxyfile, include/mbedtls/version.h, library/CMakeLists.txt, tests/suites/test_suite_version.data
=> Update library version to 2.19.0

tests/ssl-opt.sh
=> ssl-opt.sh: wait for proxy to start before running the script further

ChangeLog, doxygen/input/doc_mainpage.h, doxygen/mbedtls.doxyfile, include/mbedtls/version.h, library/CMakeLists.txt, tests/suites/test_suite_version.data
=> Bump version to Mbed TLS 2.7.12

ChangeLog, doxygen/input/doc_mainpage.h, doxygen/mbedtls.doxyfile, include/mbedtls/version.h, library/CMakeLists.txt, tests/suites/test_suite_version.data
=> Bump version to Mbed TLS 2.16.3

scripts/config.pl, tests/scripts/basic-build-test.sh
fixed to work in xxx-arm-firmware repository
=> [baremetal] Fix basic-build-test.sh to work in different env

scripts/config.pl
=> config.pl: If python3 fails, make it clear that this isn't fatal

tests/scripts/check-test-cases.py, tests/scripts/mbedtls_test.py
Sideport of https://github.com/ARMmbed/mbed-crypto/pull/334
This PR fixes a few warnings that the check_python_files component of all.sh was complaining about
=> Sideport: Fix some pylint warnings

library/ssl_tls.c, tinycrypt/ecc_dsa.c
=> [baremetal] Coverity fixes

library/sha256.c
This PR adds SCA countermeasures to SHA-256 module on places where
get/put_uint32 on secret data is used.
When reading the input, the buffer will be initialised with random data
and the reading will start from a random offset. When writing the data,
the output will be initialised with random data and the writing will
start from a random offset.
**READY**
=> [baremetal] Add SCA countermeasures to SHA-256 module

doxygen/input/doc_mainpage.h, doxygen/mbedtls.doxyfile, include/mbedtls/version.h, library/CMakeLists.txt, library/Makefile, tests/suites/test_suite_version.data
Increase the version number to reflect the latest release.
**IN PROGRESS**
=> Bump version to Mbed TLS 2.20.0

doxygen/input/doc_mainpage.h, doxygen/mbedtls.doxyfile, include/mbedtls/version.h, library/CMakeLists.txt, tests/suites/test_suite_version.data
Increase the version number to reflect the latest release.
**READY**
=> Bump version to Mbed TLS 2.7.13

doxygen/input/doc_mainpage.h, doxygen/mbedtls.doxyfile, include/mbedtls/version.h, library/CMakeLists.txt, tests/suites/test_suite_version.data
Increase the version number to reflect the latest release.
**READY**
=> Bump version to Mbed TLS 2.16.4

ChangeLog
Update the crypto submodule to the latest head. Update the changelog accordingly. Also catch up on changelog updates from the previous submodule merge.
=> Update crypto submodule 2020-02-06

ChangeLog, doxygen/input/doc_mainpage.h, doxygen/mbedtls.doxyfile, include/mbedtls/version.h, library/CMakeLists.txt, tests/suites/test_suite_version.data
This PR has the following changes:
- Updates the crypto submodule
- Add ChangeLog entries for the changes brought in
- Bumps the version to 2.21.0
- Updates the release data in the ChangeLog header
=> Update submodule and version 2.21.0

ChangeLog, doxygen/input/doc_mainpage.h, doxygen/mbedtls.doxyfile, include/mbedtls/version.h, library/CMakeLists.txt, tests/suites/test_suite_version.data
This PR does the following two changes:
- Updates Mbed TLS version.
- Updates the release information in the ChangeLog header
=> Bump version 2.7.14

tests/suites/test_suite_ssl.data, tests/suites/test_suite_ssl.function
This pull request contains tests for data transfer via DTLS as a stream
**READY** - for review
NO
=> DTLS application data

tests/suites/test_suite_ssl.data, tests/suites/test_suite_ssl.function
This pull request contains tests for renegotiation
**READY** - for review; **HOLD** - for merge
This PR contains changes from another PR which is no merged yet. Please do review only the last commit
NO
=> DTLS renegotiation

ChangeLog.d/bugfix.txt, scripts/data_files/vs2010-main-template.vcxproj, visualc/VS2010/mbedTLS.vcxproj
This is the 2.7 backport of #2853
=> [backport 2.7] Finalize fixing bugs in .vcxproj files

ChangeLog.d/bugfix.txt, scripts/data_files/vs2010-main-template.vcxproj, visualc/VS2010/mbedTLS.vcxproj
This is the 2.16 backport of ARMmbed#2853
=> [backport 2.16] Finalize fixing bugs in .vcxproj files

ChangeLog.d/midipix-support.txt, library/entropy_poll.c, library/net_sockets.c, library/timing.c
This PR brings support for midipix, a new POSIX layer for windows, like cygwin.
=> midipix platform support

scripts/output_env.sh
=> Backport 2.7: Add output of make, cmake and python3 versions

ChangeLog.d/error-asn1.txt, library/error.c, scripts/generate_errors.pl
Straightforward backport of #3350
=> Backport 2.16: Include asn1.h in error.c

ChangeLog.d/error-asn1.txt, library/error.c, scripts/generate_errors.pl
Straightforward backport of #3350
=> Backport 2.7: Include asn1.h in error.c

library/platform_util.c, tinycrypt/ecc.c
This PR adds flow monitor to the function mbedtls_platform_memcmp() and a start form a random location in function uECC_vli_equal() to increase resistance to fault injection
**READY**
Yes
=> Increasing resistance to fault injection attacks related with memory operations.

library/ccm.c, library/entropy.c, library/hmac_drbg.c, library/pk.c, library/ssl_cli.c, library/ssl_srv.c, library/ssl_tls.c, tinycrypt/ecc.c, tinycrypt/ecc_dh.c, tinycrypt/ecc_dsa.c
Update a couple of status variables to start with an error value.
=> Change the default value of status variables to an error

3rdparty/everest/CMakeLists.txt, CMakeLists.txt, ChangeLog.d/use-find-python3-cmake.txt, programs/psa/CMakeLists.txt, tests/CMakeLists.txt
Fix https://github.com/ARMmbed/mbed-crypto/issues/389
**READY**
NO
NO
=> Use FindPython3 when cmake version >= 3.15.0

include/tinycrypt/ecc.h, library/ssl_tls.c, tinycrypt/ecc.c, tinycrypt/ecc_dh.c, tinycrypt/ecc_dsa.c
This PR introduces a couple of Hamming distance improvements for return values in Mbed TLS baremetal.
=> Hamming distance improvements

library/sha256.c
This PR adds flow control to sha256.
=> Add flow control to sha256

library/ssl_tls.c
This PR contains FI attacks countermeasures for security-sensitive switch instructions
**REDY**
=> Add FI countermeasures for sensitive switch instructions

library/aes.c, library/ccm.c, library/entropy.c, library/hmac_drbg.c, library/sha256.c, library/ssl_cli.c, library/ssl_srv.c, library/ssl_tls.c, tinycrypt/ecc.c, tinycrypt/ecc_dh.c, tinycrypt/ecc_dsa.c
This PR supersedes and is a subset of https://github.com/ARMmbed/mbedtls/pull/3434.
The original code is available here: https://github.com/AndrzejKurek/mbedtls/tree/fi-duplicate-buffers.
=> Duplicate sensitive buffer and buffer length information

library/aes.c, library/ccm.c, library/ssl_cli.c, library/ssl_srv.c, library/ssl_tls.c, tinycrypt/ecc.c, tinycrypt/ecc_dh.c, tinycrypt/ecc_dsa.c
=> Revert a part of the sensitive information duplication changes

library/x509.c
=> x509.c: Remove one unnecessary cast

include/mbedtls/sha256.h, library/sha256.c
=> Introduce sha256 security review fixes

include/mbedtls/hmac_drbg.h, library/ecdsa.c, library/hmac_drbg.c, tests/suites/test_suite_hmac_drbg.function
This PR introduces changes related to FI in hmac_drbg. It also fixes a bug introduced in https://github.com/ARMmbed/mbedtls/pull/2934.
=> Fi-related hmac_drbg fixes

tests/git-scripts/pre-commit.sh, tests/scripts/check-generated-files.sh
This is the 2.16 backport of #3495 - all straightforward.
=> [Backport 2.16] Add update option to check-generated-files

tests/git-scripts/pre-commit.sh, tests/scripts/check-generated-files.sh
This is the 2.7 backport of #3495 - all straightforward.
=> [Backport 2.7] Add update option to check-generated-files

tests/suites/helpers.function, tests/suites/test_suite_mpi.function
Backport of https://github.com/ARMmbed/mbedtls/pull/3625
=> Backport 2.16: Report the first unit test failure, not the last one

ChangeLog.d/getrandom.txt, library/entropy_poll.c
Fixes #3432
Signed-off-by: okhowang(王沛文) <okhowang@tencent.com>
Notes:
READY
NO  
NO
=> Use glibc's getrandom when glibc > 2.25

ChangeLog.d/android-socklen_t.txt, library/net_sockets.c
Fixes #2977
Signed-off-by: okhowang(王沛文) <okhowang@tencent.com>
Notes:
Use socklen_t on Android
READY
NO  
NO
=> Use socklen_t on Android

programs/ssl/ssl_client2.c, programs/ssl/ssl_server2.c
=> Force cleanup by using goto exit instead of direct return

include/mbedtls/config.h, library/ssl_tls.c
Extract a common part of the code to a function.
=> [baremetal] Refactor the buffer resize feature to reduce codesize

library/psa_crypto_its.h, programs/test/cpp_dummy_build.cpp
CPP inclusion guard was missing a closing bracket
**READY**
=> Add missing bracket for CPP guard

library/ccm.c
This PR introduces shuffling and masking to CCM.
=> [Baremetal] CCM countermeasures - shuffling and masking

library/sha256.c
=> [baremetal] Add random delays to sha256 to protect against fault injection

include/mbedtls/config.h, tinycrypt/ecc.c
This PR supersedes https://github.com/ARMmbed/mbedtls/pull/3983.
=> [baremetal] Introduce a platform fault on bad input in uECC_vli_mmod

library/ssl_tls.c
This PR introduces additional FI protection to ssl_parse_certificate. Please note that the approach is not standard, since I didn't want to add a call for double verification.
=> [baremetal] Improved fi protection in ssl_parse_certificate

docs/architecture/testing/psa-storage-format-testing.md
Save-compare-load approach: the test case data contains attributes of the object under test and the expected file content. Create the object, save it, check that the file has the expected content, load the file and check that the new object has the expected attributes.
FIx https://github.com/ARMmbed/mbedtls/issues/3739
=> Keystore format stability test strategy

tests/suites/test_suite_psa_crypto.function
Fix https://github.com/ARMmbed/mbedtls/issues/4122
=> Remove trail check in the generate_random test

ChangeLog.d/getentropy.txt, library/entropy_poll.c
=> Implements getrandom's wrapper for handful of BSD.

ChangeLog.d/add_const_parameters.txt
Add changelog in new directory, as requested in #4114
Partially implements #4033
=> Add changelog for applying missing const attributes to the API.

Makefile
Backport of https://github.com/ARMmbed/mbedtls/pull/4019
=> Backport 2.16: TAGS: Fix lookup in test/suites/!(test_suite_*).function

ChangeLog.d/remove_allow_sha1_in_certificates, configs/config-psa-crypto.h, include/mbedtls/config.h, library/x509_crt.c, programs/test/query_config.c, tests/scripts/all.sh, tests/ssl-opt.sh, tests/suites/test_suite_x509parse.data
=> Remove optional SHA-1 in the default TLS configuration.

ChangeLog.d/fix_bignum_unchecked_return.txt, library/bignum.c
Fix an unchecked return valueiin bignum.c - issue found by coverity
**READY**
NO
NO
=> Fix unchecked return value in bignum

ChangeLog.d/one-shot-mac.txt, library/psa_crypto.c, library/psa_crypto_mac.c, tests/suites/test_suite_psa_crypto.function, tests/suites/test_suite_psa_crypto_driver_wrappers.function
Straightforward backport of #4316 to development_2.x.
=> Backport 2.x: Implement one-shot mac in PSA

ChangeLog.d/out_size.txt, docs/3.0-migration-guide.d/out_size.md, include/mbedtls/ecdsa.h, include/mbedtls/pk.h, library/ecdsa.c, library/pk.c, library/pk_wrap.c, library/pk_wrap.h, library/psa_crypto.c, library/ssl_cli.c, library/ssl_srv.c, library/x509write_crt.c, library/x509write_csr.c, programs/pkey/ecdsa.c, programs/pkey/pk_sign.c, programs/pkey/rsa_sign_pss.c, programs/ssl/ssl_server2.c, programs/test/benchmark.c, tests/suites/test_suite_ecdsa.function, tests/suites/test_suite_pk.function
=> Add output size parameter to signature functions

tests/scripts/generate_psa_tests.py
=> Backport 2.x: Speed up the generation of storage format test cases

tests/scripts/generate_psa_tests.py
Restore the optimization done in 45f2a40fa4363bc017937396a04240fb4b320e51 which was lost during refactoring made when adding support for implicit usage flags.
Backport: [2.27](https://github.com/ARMmbed/mbedtls/pull/4757)
=> Speed up the generation of storage format test cases

programs/test/udp_proxy.c
This is the 2.x backport of #4754 - entirely straightforward.
=> [Backport 2.x] Fix bug with UDP proxy not forwarding enough

docs/architecture/testing/psa-storage-format-testing.md
Trivial forward-port of https://github.com/ARMmbed/mbedtls/pull/4480
=> 3.0: Updates to the storage format test strategy after starting implementation

include/mbedtls/check_config.h
"This is the 2.16 backport of #4659"
Signed-off-by: Spencer Burke info.spencer.burke@gmail.com
=> 2.16 Backport of #4659

ChangeLog.d/remove_default_alllow_sha1.txt, include/mbedtls/config.h, library/x509_crt.c, programs/test/query_config.c, tests/scripts/all.sh, tests/ssl-opt.sh, tests/suites/test_suite_x509parse.data
=> Remove MBEDTLS_TLS_DEFAULT_ALLOW_SHA1_IN_CERTIFICATES in 2.28

include/mbedtls/ssl.h, library/ecdh.c, library/ecdh_misc.h, library/ssl_misc.h, library/ssl_tls13_client.c, library/ssl_tls13_generic.c, tests/scripts/all.sh, tests/ssl-opt.sh
Add  extensions
- supported groups
- key_share
- signature algorithms
Add test case to check ServerHello message is sent by openssl s_server
This PR depends on #4882 and #4811 
**REAY**
NO  
NO
=> TLS1.3: Client Hello : Add  extensions and test case.

docs/architecture/tls13-experimental.md
Fixes #4951 
IN DEVELOPMENT
NO
=> Define TLS 1.3 MVP and document coding rules

scripts/code_size_compare.py
This pr is to add a script for comparing the size of the library files from two different git revisions.
**READY**
=> Add code size comparison script.

library/ssl_misc.h, library/ssl_tls13_client.c, library/ssl_tls13_generic.c, library/ssl_tls13_keys.h, tests/ssl-opt.sh
Add handler of client Certificate Verify and depended functions
**READY**
=> TLS1.3: CertificateVerify:add tls13 read certificate verfify

library/ssl_cli.c, library/ssl_misc.h, library/ssl_tls13_client.c
Add function to write hostname extension in client hello body.
**READY**
=> TLS1.3 Add hostname extension

library/ssl_misc.h, library/ssl_tls13_client.c, library/ssl_tls13_generic.c, library/ssl_tls13_keys.c
Add client finish processing in client side.
On client side, after preparing client finish message, send to server side.
Implements #4422 - part 1/2
=> Add client finished

library/ssl_misc.h, library/ssl_tls13_client.c, library/ssl_tls13_generic.c, tests/ssl-opt.sh
- Implement `HANDSHAKE_WRAPUP` state 
- Add whole flow tests.
=> TLS1.3 MVP: Add finialize states and simplest test

BRANCHES.md, CONTRIBUTING.md
=> Fix list of LTS braches in CONTRIBUTING.md, and back link from BRANCHES.md

docs/getting_started.md
Rename the key id variables to not clash with the raw key data.
This was introduced in cf56a0a.
Trivial backport of https://github.com/ARMmbed/mbedtls/pull/5199.
=> Backport 2.x: Fix duplicate variable name in getting_started.md

docs/getting_started.md
Rename the key id variables to not clash with the raw key data.
This was introduced in cf56a0a3.
2.x backport: https://github.com/ARMmbed/mbedtls/pull/5200
=> Fix duplicate variable name in getting_started.md

programs/ssl/ssl_client2.c, programs/ssl/ssl_server2.c, tests/compat.sh, tests/scripts/all.sh, tests/scripts/test-ref-configs.pl, tests/ssl-opt.sh
Fix (d)tls1_2 into (d)tls12 in version options and related test scripts.
Partial backport of #5166.
**READY**
=> Backport 2.x: Fix (d)tls1_2 into (d)tls12 in version options

programs/aes/crypt_and_hash.c, tests/suites/test_suite_cipher.function
=> Backport 2.16: Missing error checks + test bug on unlikely failure

programs/aes/crypt_and_hash.c, tests/suites/test_suite_cipher.function
=> Backport 2.x: Missing error checks + test bug on unlikely failure

BRANCHES.md
Update out-of-date info in BRANCHES.md.
=> Update information in BRANCHES.md

CONTRIBUTING.md, SUPPORT.md
Backport of https://github.com/ARMmbed/mbedtls/pull/5420
=> Update mailing list links [Backport]

include/mbedtls/asn1.h, include/mbedtls/ctr_drbg.h, include/mbedtls/ecp.h, include/mbedtls/entropy.h, include/mbedtls/hkdf.h, include/mbedtls/hmac_drbg.h, include/mbedtls/mbedtls_config.h, include/mbedtls/memory_buffer_alloc.h, include/mbedtls/pem.h, include/mbedtls/platform.h, include/mbedtls/platform_time.h, include/mbedtls/ssl.h, include/mbedtls/ssl_cache.h, include/mbedtls/ssl_cookie.h, include/mbedtls/x509.h, include/mbedtls/x509_crl.h, include/mbedtls/x509_crt.h, include/mbedtls/x509_csr.h
Clarify section names next to closing braces
Partially fixing Issue https://github.com/ARMmbed/mbedtls/issues/3497
Related PRs: #5371, #5372
=> doxygen: add missing asterisk to group closures

tests/ssl-opt.sh
Trivial backport of https://github.com/ARMmbed/mbedtls/pull/5395
=> Backport 2.28: Add positive test case with self-signed certificates

library/ssl_tls13_client.c
`ssl->client_auth` is moved to `ssl->handshake->client_auth`
=> BUG fix :fix client_auth fail

tests/scripts/analyze_outcomes.py, tests/scripts/check_test_cases.py
Add `--list` option to `check_test_cases.py`. In `development` this was done as part of investigation into a bug and is in the same pull request as the bug fix https://github.com/ARMmbed/mbedtls/pull/5393. This PR is a trivial cherrypick of the relevant commits.
=> Backport 2.28: check_test_cases.py --list

ChangeLog.d/raw-agreement-destroy-missing.txt, library/ssl_cli.c
Issue found in https://github.com/ARMmbed/mbedtls/pull/5525.
Backport: https://github.com/ARMmbed/mbedtls/pull/5577
=> Add missing key destruction calls in ssl_write_client_key_exchange

library/ssl_misc.h, library/ssl_tls13_client.c, library/ssl_tls13_generic.c, tests/ssl-opt.sh
Add write client CertificateVerify handler.
Preceding PRs: #5080, #5472
=> TLS1.3: Add write client Certificate and CertificateVerify

tests/scripts/check-python-files.sh
Trivial backport of https://github.com/ARMmbed/mbedtls/pull/5588
=> Backport 2.28: Make mypy unconditional

library/ssl_srv.c, library/ssl_tls.c, tests/compat.sh
=> Backport 2.28: Restore full compat testing

library/ssl_tls.c
Remove md_info in ssl_tls12_populate_transform() when USE_PSA_CRYPTO is defined
Follow-up to #5573
See https://github.com/ARMmbed/mbedtls/issues/5179#issuecomment-1066520054
**READY**
NO 
NO
N/A
ssl-opt.sh & test_suite_pk must run clean
=> Remove md_info in ssl_tls12_populate_transform() when USE_PSA_CRYPTO is defined

ChangeLog.d/fix-windows-cmake-build-with-shared-libraries.txt, library/CMakeLists.txt
=> Backport 2.28: Fix Shared Library compilation issue with Cmake

tests/scripts/curves.pl
Triviail backport of https://github.com/Mbed-TLS/mbedtls/pull/5739
=> Backport 2.28: Don't test with all-but-one elliptic curves

library/ssl_misc.h, library/ssl_tls13_client.c, library/ssl_tls13_generic.c, library/ssl_tls13_server.c, tests/ssl-opt.sh
Add server-side ServerHello handler
Preceding PR: #5539
=> TLS1.3: Add server-side ServerHello handler

library/ssl_tls13_client.c, library/ssl_tls13_generic.c, library/ssl_tls13_keys.c, library/ssl_tls13_keys.h, library/ssl_tls13_server.c, tests/ssl-opt.sh
fixes #5497 
fixes #5498
preceding PR: #5748
=> TLS 1.3: Add Finished Message and wrapup

include/mbedtls/aes.h, include/mbedtls/aria.h, include/mbedtls/bignum.h, include/mbedtls/blowfish.h, include/mbedtls/camellia.h, include/mbedtls/chachapoly.h, include/mbedtls/config.h, include/mbedtls/ecp.h, include/mbedtls/oid.h, include/mbedtls/platform_util.h, include/mbedtls/rsa.h, include/mbedtls/ssl.h, include/mbedtls/x509_crt.h
=> Backport 2.28: Fix spelling and typographical errors found by cspell

ChangeLog.d/fix-x25519-program.txt, programs/pkey/ecdh_curve25519.c
=> [2.28] Rewrite x25519 example program

ChangeLog.d/x509_ext_types_accessor.txt, include/mbedtls/x509_crt.h, tests/suites/test_suite_x509parse.data, tests/suites/test_suite_x509parse.function
=> Add accessor for x509 certificate extension types

library/ssl_misc.h, library/ssl_tls.c, library/ssl_tls12_server.c, library/ssl_tls13_server.c, tests/ssl-opt.sh
This will add alpn extension support the server side.
Also make the exist alpn cases available for both tls1.2 and tls1.3
=> Add ALPN extension to the server side

include/mbedtls/config_psa.h
Resolves https://github.com/Mbed-TLS/mbedtls/issues/5890
**READY**
=> Add comment to config_psa.h about enabling PSA_HKDF/-EXTRACT/-EXPAND

ChangeLog.d/tls13-misc-changelogs.txt, docs/architecture/tls13-support.md
Add missing change logs and update TLS 1.3 support documentation for 3.2 release
Fix #5570
READY
=> TLS 1.3: Add missing change logs and update doc for 3.2 release

include/mbedtls/ssl.h, library/ssl_tls13_server.c, tests/ssl-opt.sh
=> TLS 1.3: PSK: Add parser of psk kex mode ext on server side

library/ssl_misc.h, library/ssl_tls13_client.c, library/ssl_tls13_keys.c, library/ssl_tls13_server.c
=> TLS 1.3: Add specific field to store the selected key exchange mode

library/ssl_client.c, library/ssl_misc.h, library/ssl_tls.c, library/ssl_tls13_client.c, library/ssl_tls13_generic.c, tests/ssl-opt.sh
Add  psk code to tls13 client side
Write psk extenstion in ClientHello
Parse the psk extention from the server side.
=> Add psk code to tls13 client side

include/mbedtls/ssl.h, programs/ssl/ssl_server2.c
Just some fixes for minor typos.
**READY**
=> Fix minor typos

ChangeLog.d/remove_ssl_session_compression.txt, include/mbedtls/ssl.h, library/ssl_tls.c, library/ssl_tls12_client.c, library/ssl_tls12_server.c, library/ssl_tls13_client.c, library/ssl_tls13_server.c, tests/suites/test_suite_ssl.function
=> Remove use of SSL session compression

library/ecdh.c, library/ecdsa.c, library/ecjpake.c, library/ecp.c, tests/suites/test_suite_ecdh.function, tests/suites/test_suite_ecjpake.function, tests/suites/test_suite_ecp.function
This PR re-introduce enum check in files related to curve in library.
NO  
NO
=> Validation remove and change in files related to curve in library

include/mbedtls/bignum.h, library/constant_time.c
=> Be explicit about constant time bignum functions that must take a 0 or 1 condition value

tests/opt-testcases/tls13-kex-modes.sh
Fix #6053 
It has been supported, but there are no tests for it . 
**READY**
=> TLS 1.3:Add multiple pre-configured psk test for server

CONTRIBUTING.md
=> Clarify legal requirements for contributions

include/mbedtls/mbedtls_config.h, include/mbedtls/ssl.h, library/ssl_misc.h, library/ssl_tls.c, library/ssl_tls13_server.c, programs/ssl/ssl_client2.c, programs/ssl/ssl_server2.c, tests/ssl-opt.sh
=> TLS 1.3: NewSessionTicket: Add support for sending multiple tickets per session.

CONTRIBUTING.md, ChangeLog, README.md, SUPPORT.md, docs/3.0-migration-guide.md, docs/architecture/alternative-implementations.md, docs/architecture/testing/test-framework.md, docs/architecture/tls13-support.md, include/mbedtls/mbedtls_config.h, include/mbedtls/ssl.h
See also: https://github.com/Mbed-TLS/mbedtls-docs/pull/55
Backport: #6414 
=> Update documentation links

CONTRIBUTING.md, README.md, SUPPORT.md, docs/architecture/testing/test-framework.md, include/mbedtls/config.h, include/mbedtls/ssl.h
=> Update documentation links 2.28

library/bignum_core.h, library/bignum_mod.h, library/bignum_mod_raw.h
Spell out some established or emerging conventions of the bignum core internal interface. This codifies things that we've previously discussed and a few more things that were implicit. I am not trying to impose anything new, but I may have unwittingly described something as established when it's actually controversial, so don't hesitate do holler if you disagree.
=> Spell out bignum core conventions

library/bignum.c, library/bignum_core.c, library/bignum_core.h, scripts/mbedtls_dev/bignum_core.py, tests/suites/test_suite_bignum_core.function
Create and test `mbedtls_mpi_core_shift_r`.
I need this auxiliary function for https://github.com/Mbed-TLS/mbedtls/issues/6239.
Changelog: no (internal function)
Backport: no (new feature)
=> Bignum core: shift_r

ChangeLog.d/tls13-misc.txt, docs/architecture/tls13-support.md, library/ssl_tls13_client.c, library/ssl_tls13_server.c, tests/opt-testcases/tls13-compat.sh, tests/opt-testcases/tls13-kex-modes.sh, tests/scripts/generate_tls13_compat_tests.py, tests/ssl-opt.sh
=> TLS 1.3: Update documentation for the coming release and misc

ChangeLog.d/fix_zeroization.txt, library/ssl_tls.c
Trivial backport of #6521 
Changelog: yes, present
=> Fix zeroization at NULL pointer - 2.28 backport

ChangeLog.d/fix_zeroization.txt, library/ssl_tls.c
Fixes #6516
Backport: #6523 
Changelog: yes, present
=> Fix zeroization at NULL pointer

library/psa_crypto_aead.c, library/psa_crypto_cipher.h, library/psa_crypto_core.h, library/psa_crypto_mac.c
=> Remove duplicate function prototype - 2.28 backport

library/psa_crypto_aead.c, library/psa_crypto_cipher.h, library/psa_crypto_core.h, library/psa_crypto_mac.c
Fixes #6520 
Changelog: not needed - this is an internal header
Backport: #6525
=> Remove duplicate function prototype

library/bignum_core.c, library/bignum_core.h, scripts/mbedtls_dev/bignum_core.py, tests/suites/test_suite_bignum_core.function
First PR in a series to extract modular exponentiation from the prototype (#6293).
=> Implement mbedtls_mpi_core_ct_uint_table_lookup()

scripts/mbedtls_dev/bignum_common.py
Forgot to add merge slots to bignum_common.py in #6530
=> Add merge slots to bignum_common.py

library/bignum_mod_raw.c, library/bignum_mod_raw.h, scripts/mbedtls_dev/bignum_mod_raw.py, tests/suites/test_suite_bignum_mod_raw.function
This pr is importing the conversion functions from the prototype, is refactoring them to fit the needs of current design and is adding tests using the automatic generation frameworks.
=> Bignum: Add Montgomery conversion from/to cannonical form

include/mbedtls/mbedtls_config.h, include/mbedtls/ssl.h, tests/scripts/all.sh
Some adjustments in the TLS 1.3 implementation for the coming release.
=> TLS 1.3: Adjustments for the coming release

.github/pull_request_template.md
Fix a broken link in the PR template - note that the link to contributing guidelines at the bottom of this text does not currently work.
=> Fix broken link

include/psa/crypto_values.h
=> Backport 2.28: Update documenation of PSA_ALG_RSA_PSS

ChangeLog.d/fix_arm_compile_erorr.txt
Add missing Changelog entry for #6090
=> Add Changelog for Arm compile fix

library/bignum_core.h, library/bignum_mod_raw.c, library/bignum_mod_raw.h, scripts/mbedtls_dev/bignum_common.py, scripts/mbedtls_dev/bignum_data.py, scripts/mbedtls_dev/bignum_mod_raw.py, tests/suites/test_suite_bignum_core.function, tests/suites/test_suite_bignum_mod_raw.function
=> Bignum: Implement mbedtls_mpi_mod_raw_inv_prime()

library/bignum_mod_raw.c, library/bignum_mod_raw.h, scripts/mbedtls_dev/bignum_mod_raw.py, tests/suites/test_suite_bignum_mod_raw.function
This pr is importing the modular negation logic from Hanno's prototype and is adding standard tests for it.
=> Bignum: Implement fixed width modular negation

library/bignum_mod.c, library/bignum_mod.h, library/bignum_mod_raw.c, library/bignum_mod_raw.h, scripts/mbedtls_dev/bignum_common.py, scripts/mbedtls_dev/bignum_mod_raw.py, tests/include/test/bignum_helpers.h, tests/include/test/helpers.h, tests/scripts/generate_bignum_tests.py, tests/src/bignum_helpers.c, tests/src/helpers.c, tests/suites/helpers.function, tests/suites/test_suite_bignum_mod_raw.function, tests/suites/test_suite_bignum_random.data, tests/suites/test_suite_bignum_random.function
Implement `mbedtls_mpi_mod_raw_random` and `mbedtls_mpi_mod_random`. Resolves https://github.com/Mbed-TLS/mbedtls/issues/6239. Also:
* New test helper `mbedtls_test_read_mpi_modulus`
Status: ready
=> Bignum mod random

include/mbedtls/ssl.h, library/ssl_client.c, library/ssl_misc.h, library/ssl_msg.c, library/ssl_tls.c, library/ssl_tls13_client.c, library/ssl_tls13_generic.c, library/ssl_tls13_server.c, tests/ssl-opt.sh
This PR include some small fix and some better code from `prototype`
fix #6311 
=> TLS 1.3: Upstream misc fix from prototype

ChangeLog.d/fix-iar-warnings.txt, library/bignum.c
Thanks to @gstrauss for providing the fix. This fixes #3835
=> Fix IAR warning

scripts/code_style.py
=> code_style.py: Support restyling only the specified files

docs/getting_started.md
=> Backport 2.28 - Getting started

scripts/mbedtls_dev/crypto_knowledge.py, tests/scripts/generate_psa_tests.py
=> [Backport 2.28] Fix check python errors

.uncrustify.cfg, scripts/code_style.py
Miscellaneous improvements to the code style script, following up feedback on #6705. Not all improvements are covered in this PR, a future PR will solve the rest of the issues.
Fixes #6755 (partially)
=> Improvements to code style script

library/ccm.c, library/ecp_curves.c, library/entropy.c, library/ripemd160.c, library/x509_crt.c, programs/pkey/ecdh_curve25519.c, programs/pkey/ecdsa.c, tests/suites/test_suite_ctr_drbg.function, tests/suites/test_suite_mdx.function, tests/suites/test_suite_pk.function, tests/suites/test_suite_x509parse.function
Almost trivial backport of #7028
=> Backport 2.28 - Sizeof brackets

library/ccm.c, library/ecp_curves.c, library/entropy.c, library/ripemd160.c, library/x509_crt.c, programs/pkey/ecdh_curve25519.c, programs/pkey/ecdsa.c, tests/suites/test_suite_ctr_drbg.function, tests/suites/test_suite_mdx.function, tests/suites/test_suite_pk.function, tests/suites/test_suite_x509parse.function
=> Fix use of sizeof without brackets

ChangeLog.d/c-build-helper-hostcc.txt, scripts/mbedtls_dev/c_build_helper.py
=> [Backport 2.28] Minor improvements to `c_build_helper.py`

tests/scripts/doxygen.sh
=> [Backport 2.28] Fix typos

tests/ssl-opt.sh
=> Extend test framework for Record Size Limit Extension

include/mbedtls/mbedtls_config.h, library/aesce.c, library/bignum_core.h, library/ecp_curves.c, library/pkcs7.c, library/sha256.c, library/ssl_tls13_client.c, programs/ssl/ssl_client2.c
=> Fix typos in development prior to release

include/mbedtls/config.h
=> Fix typos in LTS prior to release

ChangeLog
=> Update ChangeLog to make "fix" explicit

library/aesce.c, library/sha256.c, library/sha512.c
=> Improve macro naming

library/platform_util.c
On some platforms, including modern Linux, Clang with Msan does not recognize that explicit_bzero() writes well-defined content to its output buffer. For us, this causes CMAC operations to fail in Msan builds when mbedtls_platform_zeroize() is implemented over explicit_bzero(). Fix this.
The CI didn't complain because we run Msan only on an ancient Linux that doesn't have `explicit_bzero`.
=> Fix Msan failure with explicit_bzero

library/aesce.c, library/aesce.h, library/gcm.c
=> Add GCM  with armv8 crypto extension

docs/architecture/Makefile, docs/architecture/psa-crypto-implementation-structure.md
When you implement a new algorithm, key type, operation type, or similar feature in the PSA crypto API, there are a number of places to look, not all of them obvious. This is intended as a guide to the typical places.
Based on my memory, grep, https://github.com/Mbed-TLS/mbedtls/pull/5834 and https://github.com/Mbed-TLS/mbedtls/pull/5871.
=> Check list for implementing a new mechanism in PSA crypto

library/x509.c
Add do-while loops around various macros.
=> Add a do-while loop around macros.

docs/architecture/psa-storage-resilience.md
Explore possibilities for implementing stateful secure elements with storage. Choose one.
=> Storage resilience with stateful secure elements: design document

ChangeLog.d/fix-win32-llvm-build.txt, library/aesni.c
=> Support compilation using CLang on Windows

library/ssl_client.c
=> Improve write supported group ext

README.md
This is a test PR to see if we've correctly configured our Jenkins instance for using Github's merge queues.
=> Test PR for Github merge queues

programs/ssl/dtls_server.c
Fixes the numbered order of steps in the DTLS server example program.
=> Fix order of steps in DTLS server example program

library/ecp.c, tests/suites/test_suite_ecp.function
Fix for testing and building the cloned ecp module.
=> [Bignum] Fixes for the ecp module cloning

tests/scripts/all.sh
This is a test PR to see if we've correctly configured our Jenkins instance for using Github's merge queues, including sequencing multiple PRs.
=> Test PR for Github merge queues #2

README.md
This is a test PR to see if we've correctly configured our Jenkins instance for using Github's merge queues, including sequencing multiple PRs.
=> Test PR for Github merge queues #1

scripts/code_style.py
Backport of code_style improvement from #8003 
=> backport 2.28 - Make code_style.py --since more precise

docs/proposed/psa-driver-developer-guide.md, docs/proposed/psa-driver-integration-guide.md, docs/proposed/psa-driver-interface.md, docs/proposed/psa-driver-wrappers-codegen-migration-guide.md, docs/psa-driver-example-and-guide.md, scripts/data_files/driver_jsons/mbedtls_test_transparent_driver.json
Make the document that describes the current reality of driver development more discoverable, and fix an error in it.
(See also [this thread on slack](https://arm-ce.slack.com/archives/C01CC4Y1T1P/p1691400500094489).)
=> Driver guide/examples: fix an error and improve discoverability

docs/architecture/psa-thread-safety.md
Thread safety requirements inspired by our discussion from last week, plus some older design notes that I'd previously shared with Andrzej.
=> PSA thread safety requirements

CMakeLists.txt, library/psa_crypto.c, library/psa_crypto_storage.h
=> Backport 2.28: Small fixes for IAR support

tests/scripts/analyze_outcomes.py
=> Backport 2.28: Implement allowlist of test cases that are legitimately not executed

scripts/driver.requirements.txt
Hotfix for the issues encountered in the internal and Open CIs. Should help prevent new issues introduced by updating these packages. Fixes https://github.com/Mbed-TLS/mbedtls/issues/8250
=> Set explicit version for the typing packages

include/mbedtls/mbedtls_config.h, include/psa/crypto_platform.h, tests/scripts/all.sh
Fix https://github.com/Mbed-TLS/mbedtls/issues/8259.
=> Fix include path to psa/crypto_spe.h

library/bignum.c, library/pk.c, library/pk_wrap.c, library/psa_crypto_rsa.c, library/sha256.c, library/sha512.c, scripts/data_files/driver_templates/psa_crypto_driver_wrappers.h.jinja
Along with #8271, this gets us a clean build under IAR 9.40.1
=> Fix IAR warnings

scripts/assemble_changelog.py
=> 2.28 backport - Check changelog extensions

tests/scripts/analyze_outcomes.py
This PR improves `analyze_outcomes.py` output and resolves #8301
=> Fix error reporting in driver testing parity

programs/demo_common.sh, programs/psa/key_ladder_demo.sh, programs/test/dlopen_demo.sh, tests/scripts/all.sh, tests/scripts/check_files.py, tests/scripts/run_demos.py
Trivial backport of https://github.com/Mbed-TLS/mbedtls/pull/7982
=> Backport 2.28: Run sample program demo scripts in all.sh

library/pkcs12.c, library/pkcs5.c, library/x509_create.c
=> Stop IAR warning about goto skipping variable definition

docs/architecture/psa-thread-safety.md
This PR adds a design proposal for providing threading support in PSA Crypto.
=> Add the PSA threading design to the documentation

programs/ssl/ssl_client2.c, tests/suites/test_suite_ctr_drbg.function, tests/suites/test_suite_entropy.function, tests/suites/test_suite_pkwrite.function, tests/suites/test_suite_psa_crypto_se_driver_hal.function, tests/suites/test_suite_ssl.function, tests/suites/test_suite_x509parse.function, tests/suites/test_suite_x509write.function
Fix various issues in test code found by Coverity.
=> Cleanups in test code

docs/proposed/psa-driver-wrappers-codegen-migration-guide.md
=> Fix broken link to psa-driver-example-and-guide in psa-driver-wrappers-codegen-migration-guide.md

ChangeLog
=> Typo fixes in Changelog

include/mbedtls/ssl.h, library/ssl_misc.h, programs/ssl/ssl_server2.c, tests/scripts/all.sh, tests/ssl-opt.sh
Depends on #6322 (indeed the 1st commit summaries commits from #8495)
Resolves #6323
=> [G3] Driver-only cipher+aead: TLS: ssl-opt.sh

tests/scripts/all.sh
=> [G3] Driver-only cipher+aead: TLS: compat.sh 

programs/test/metatest.c
Trivial backport of https://github.com/Mbed-TLS/mbedtls/pull/8549
=> Backport 2.28: Fix metatest.c with gcc-12 -Wuse-after-free

programs/test/metatest.c
Fix the build of `metatest.c` under `gcc-12 -Wall`: `-Wuse-after-free` detects the deliberate use-after-free that we want to occur at runtime (because we're testing the runtime detection by Asan).
Although we do run GCC 12 on the CI, we only run it in `all.sh test_gcc_latest`, and that uses the `full` configuration. In that configuration, `mbedtls_free` is a function pointer variable in `platform.o` so the compiler doesn't see what's going on. In the  default configuration, `mbedtls_free` is a macro that expands to `free`, so the compiler can see that there's a use-after-free.
=> Fix metatest.c with gcc-12 -Wuse-after-free

include/mbedtls/check_config.h, include/mbedtls/config_adjust_psa_from_legacy.h, tests/scripts/all.sh
Resolves #8483.
Depends on: ~#8540 and #8489~ (merged)
=> [G2] Make PSA-AEAD work with cipher-light

library/pk_wrap.c
Instead of extracting key's properties in order to check whether it supports deterministic or non-deterministic ECDSA, we try both.
Resolves #8600
=> Quit using enrollment alg in for ECDSA in PK

tests/scripts/all.sh
=> [Backport 2.28] all.sh: Parse arguments before checking if a test is supported

ChangeLog.d/8060.txt, ChangeLog.d/8357.txt, ChangeLog.d/8358.txt, ChangeLog.d/driver-only-cipher.txt, ChangeLog.d/no-cipher.txt, docs/architecture/psa-migration/md-cipher-dispatch.md, docs/driver-only-builds.md, tests/scripts/all.sh, tests/scripts/analyze_outcomes.py
=> Driver-only ciphers wrapup

library/entropy_poll.c, library/platform_util.c
=> [backport 2.28] fix build for midipix

.github/pull_request_template.md
A couple of hints to contributors to help make PRs more easily reviewable
=> Remind contributors not to force-push

tests/src/helpers.c
Calling mbedtls_test_fail() attempts to lock the test data mutex. Unfortunately we were calling this from places where we already held this mutex, and this mutex is not recursive, so this deadlocks. Split out mbedtls_test_fail() into mbedtls_test_fail_internal() in order to address this.
=> Fix deadlock with test failures

library/sha3.c
This saves ~160 bytes of code size, at the cost of a bit of localized complexity in the code. The impact on performance is measurable but small (<5% observed on x86_64) and can go either way (there's a calculation vs memory bandwidth compromise).
From [an idea by Dave](https://github.com/Mbed-TLS/mbedtls/pull/8801#discussion_r1487726873) which I tweaked. See that thread for a discussion of possible variations.
Regarding correctness, I can report that the unit tests do a good job of catching typos in the table.
=> SHA3: Pack the iota round constants

library/psa_crypto.c
There is a period of time in `psa_destroy_key` between registering to read a key slot and locking the mutex to actually do the destruction. It is possible that during this period a rival thread can complete a `psa_destroy_key` call on the same key.
Previously, this would result in both callers returning `PSA_SUCCESS` (one would goto exit having failed the state transition, and then have status overwritten by `PSA_SUCCESS` in the exit logic, where status is set to `psa_unregister_read`).
This PR changes this so that exactly one thread will return `PSA_SUCCESS`. Double destruction is not behaviour defined by the PSA spec, but doing the right thing here allows us to have better testing. This fix lets us run multi-threaded tests in which we can have many threads operating and destroying the …
=> Fix threading bug when multiple destroy_key calls run on the same key

library/sha3.c, tests/scripts/all.sh
Improve SHA-3 performance and code-size.
Fixes #8819
=> SHA-3 performance & code size

include/mbedtls/pk.h, library/pk.c, tests/scripts/all.sh, tests/src/psa_crypto_stubs.c
~Depends on #8774~
Resolves #8919.
=> Generalize some PK functions from MBEDTLS_PSA_CRYPTO_C to MBEDTLS_PSA_CRYPTO_CLIENT

include/mbedtls/ssl.h, library/ssl_misc.h, library/ssl_tls.c, library/ssl_tls13_server.c, tests/src/test_helpers/ssl_helpers.c, tests/suites/test_suite_ssl.function
Add ALPN information in session tickets
Add support for ALPN in session save/load
fix #6355 
=> Add ALPN information in session tickets

ChangeLog.d/add_threading_changelog.txt
Wrap up of threading MVP. Add a changelog covering the work done in brief detail, and link to the threading doc.
=> Add changelog entry for threading MVP

tests/ssl-opt.sh
=> ssl-opt.sh: Improve version selection test titles

tests/compat.sh, tests/scripts/all.sh, tests/scripts/basic-build-test.sh
This is the forward-port to development of the relevant bits of #9019
=> [dev] Small fixes to compat.sh (partial forward-port) 

tests/psa-client-server/README.md
This PR is introducing a work-directory for the psa-crypto-client-server testing. 
=> [Crypto_Client_Test] Added work directory for the psa client/server testing epic

tests/psa-client-server/psasim/src/psa_ff_server.c, tests/psa-client-server/psasim/src/server.c, tests/psa-client-server/psasim/test/run_test.sh
Fix some bugs and other niggles in the PSA simulator. Needed for continuation of PSA crypto client work.
=> Some fixes to the PSA simulator

library/ssl_tls12_server.c
Trivial backport of https://github.com/Mbed-TLS/mbedtls/pull/8643
=> Backport 3.6: Guard configuration-specific code in ssl_tls12_server.c

tests/include/test/psa_test_wrappers.h, tests/scripts/all.sh, tests/src/psa_test_wrappers.c
Partial backport (only fixes) of #9185.
=> [Backport 3.6] Partial backport of PR 9185

docs/architecture/psa-keystore-design.md
Trivial forward-port of https://github.com/Mbed-TLS/mbedtls/pull/9309
- **tests**  no (doc only)
=> Document the key store design

ChangeLog.d/fix-legacy-compression-issue.txt, library/ssl_tls13_server.c, tests/ssl-opt.sh
=> Fix issue in handling legacy_compression_methods in ssl_tls13_parse_client_hello()

docs/psa-transition.md
=> [Backport 3.6] Fix typo in psa-transition.md

tests/ssl-opt.sh
Skip 6144-bit and 8192-bit FFDH tests in MSan or Valgrind test configurations. These test cases are slow and sometimes trigger GnuTLS's built-in timeout (which cannot be configured until more recent versions) on the internal CI.
Resolves #9742.
=> Skip slowest FFDH tests against GnuTLS with MSan or Valgrind

CMakeLists.txt, Makefile, scripts/make_generated_files.bat, tests/Makefile, tests/scripts/check-generated-files.sh, tests/suites/test_suite_pk.function
Companion PR of #9828 and https://github.com/Mbed-TLS/mbedtls-framework/pull/99
- **tests**  not required because: just changing the way things are done
=> Move test_keys.h to include/test

.github/pull_request_template.md
This PR is adding a checkbox for TF-PSA-Crypto in the PR template for mbedtls
Please also check [PR113](https://github.com/Mbed-TLS/mbedtls-framework/pull/133)
=> PR-Template: Updated the PR template with TF-PSA-Crypto checkbox

library/ssl_msg.c
This is the development forward-port of #10046
- **tests**  not required because: deferred to #9976
=> Fix defrag interleave dev

tests/scripts/components-build-system.sh
Resolves https://github.com/Mbed-TLS/TF-PSA-Crypto/issues/137
=> [development] Add components to components-build-system.sh

include/mbedtls/config.h
Document https://github.com/Mbed-TLS/mbedtls/issues/9991
Backport of [3.6](https://github.com/Mbed-TLS/mbedtls/pull/10004), removing the parts that are not applicable to 2.28 (driver-only, TLS 1.3).
- **tests**  not required because: doc only
=> Backport 2.28: Document PSA's need for threading

include/mbedtls/mbedtls_config.h
Document https://github.com/Mbed-TLS/mbedtls/issues/9991
I don't think we can help by adding code in `check_config.h`, since the library can be built in a single-threaded environment.
- **tests**  not required because: doc only
=> Backport 3.6: Document PSA's need for threading

library/Makefile, scripts/config.py, tests/psa-client-server/psasim/src/psa_sim_generate.pl, tests/scripts/components-configuration.sh, tests/scripts/components-sanitizers.sh
Resolves #8151 
- **tests**  no
=> [development] Remove the dynamic SE interface in 4.0

CMakeLists.txt, scripts/generate_visualc_files.pl, scripts/make_generated_files.bat, tests/.gitignore, tests/CMakeLists.txt, tests/Makefile, tests/scripts/check-generated-files.sh, tests/scripts/components-basic-checks.sh, tests/src/certs.c
Companion PR of https://github.com/Mbed-TLS/TF-PSA-Crypto/pull/201.
Adapt to the changes in the framework done for https://github.com/Mbed-TLS/TF-PSA-Crypto/pull/201.
Use make_generated_files.py to check make and cmake generated files instead of `check-generated-files.sh`.
- **tests**  not required because: only internal changes
=> Companion PR of "Add check generated files and check code style test components"

include/mbedtls/debug.h, library/debug.c, library/debug_internal.h, programs/ssl/ssl_client2.c, tests/suites/test_suite_pkcs7.function, tests/suites/test_suite_x509parse.function
Adding some fixes which will make CI of https://github.com/Mbed-TLS/TF-PSA-Crypto/pull/299 green.
Workflow:
- add a last commit which updates `tf-psa-crypto` reference and point it to the HEAD of https://github.com/Mbed-TLS/TF-PSA-Crypto/pull/299
- make the CI fully happy and complete the review process
- remove the last commit
- ensure the CI is green again and re-approve this PR
- merge this PR
- re-run CI on https://github.com/Mbed-TLS/TF-PSA-Crypto/pull/299 and, if OK (as it should be after this PR), add it to the merge queue
- **tests** not required because: nothing changes in tests
=> [development] Some pre-requisites for psa#299

scripts/generate_visualc_files.pl
Resolve #10226 
- **tests** not required because: no code change
=> Remove temporary path fixes introduced in mbedtls#10225

ChangeLog.d/remove_mbedtls_pk_type.txt, include/mbedtls/x509_crl.h, include/mbedtls/x509_crt.h, include/mbedtls/x509_csr.h, library/ssl_tls12_client.c, library/ssl_tls13_generic.c, library/x509.c, library/x509_create.c, library/x509_crt.c, library/x509_internal.h, library/x509_oid.c, library/x509_oid.h, library/x509write_crt.c, library/x509write_csr.c, tests/suites/test_suite_x509write.function
Switch to mbedtls pk sigalg t resolves https://github.com/Mbed-TLS/mbedtls/issues/10264
- **tests**  not required because: No changes
=> Switch to mbedtls pk sigalg t

ChangeLog.d/9322.txt, library/ssl_tls.c
Progresses Mbed-TLS/mbedtls#9322.
=> Replace psa_pake_get_implicit_key() with psa_pake_get_shared_key()

BRANCHES.md, README.md, SECURITY.md, configs/README.txt
Address https://github.com/Mbed-TLS/mbedtls/issues/10252
- **tests**  not required because: only updating documentation
=> Update documentation at repo root
