Mbed-TLS/mbedtls

include/mbedtls/ssl_internal.h, library/ssl_cli.c, library/ssl_srv.c, library/ssl_tls.c, tests/ssl-opt.sh
This is a side-port to development of PR https://github.com/ARMmbed/mbedtls-restricted/pull/563 that has already been merged to baremetal.
The primary goal of the PR is to extract a new function `ssl_populate_transform()` from existing function `ssl_derive_key()`. Later (see "background" below") this new function can be used to restore a tranform from serialised info (master secret, hello randoms, plus administrative data). In order to facilitate that future use, the function uses explicit arguments rather than accessing everything implicitly through the SSL context.
Along the way, the PR attempts small cleanups of related code, mostly along the lines of dividing stuff in smaller functions and trying to make it clear what parts of the (huge) SSL state are used or not by a particular …
=> [s11n 1/7] Refactor derive keys (side-port)

ChangeLog, doxygen/input/doc_mainpage.h, doxygen/mbedtls.doxyfile, include/mbedtls/version.h, library/CMakeLists.txt, library/Makefile, tests/suites/test_suite_version.data
Bring Mbed TLS 2.18.0 and 2.18.1 release changes back into the
development branch. We had branched to release 2.18.0 and 2.18.1 in
order to allow those releases to go out without having to block work on
the `development` branch.
**READY**
NO  
NO
=> Update with changes from the mbedtls-2.18 release branch

library/hmac_drbg.c
Backport of ARMmbed/mbed-crypto#238
=> Backport 2.7: HMAC DRBG: Split entropy-gathering requests to reduce request sizes

library/ssl_tls.c, tests/ssl-opt.sh
The SSL context maintains a set of 'out pointers' indicating the address at which to write the header fields of the next outgoing record. Some of these addresses have a static offset from the beginning of the record header, while other offsets can vary depending on the active record encryption mechanism: For example, if an explicit IV is in use, there's an offset between the end of the record header and the beginning of the encrypted data to allow the explicit IV to be placed in between; also, if the DTLS Connection ID (CID) feature is in use, the CID is part of the record header, shifting all subsequent information (length, IV, data) to the back. When setting up an SSL context, the out pointers are initialized according to the identity transform + no CID, and it is important to keep them …
=> Restore outgoing record header pointers during context deserialization

ChangeLog, library/bignum.c
Backport of #2363 to `mbedtls-2.7`
**READY**
=> Backport 2.7: fix memory leak in mpi_miller_rabin()

ChangeLog, library/bignum.c
Backport of #2363 to `mbedtls-2.16`
**READY**
=> Backport 2.16: fix memory leak in mpi_miller_rabin()

include/mbedtls/hkdf.h
Backport of #2769 to `mbedtls-2.16`
**READY**
=> Backport 2.16: fix license header of hkdf

ChangeLog, library/x509_crt.c
This patch fixes an issue we encountered with more stringent compiler
warnings.  The signature_is_good variable has a possibility of being
used uninitialized.  This patch moves the use of the variable to a
place where it cannot be used while uninitialized.
Signed-off-by: Andy Gross <andy.gross@linaro.org>
This is a backport to 2.16 of https://github.com/ARMmbed/mbedtls/pull/2795
Notes:
or for companies or those that do not wish to create an mbed account, a slightly different agreement can be found [here](https://www.mbed.com/en/about-mbed/contributor-license-agreements/)
- The PR follows the [mbed TLS coding …
=> Backport 2.16: Fix uninitialized variable in x509_crt

ChangeLog, library/bignum.c
Fixes memory leak in mpi_miller_rabin() that occurs when the function has
failed to obtain a usable random 'A' 30 turns in a row.
Signed-off-by: Jens Wiklander <jens.wiklander@linaro.org>
Notes:
or for companies or those that do not wish to create an mbed account, a slightly different agreement can be found [here](https://www.mbed.com/en/about-mbed/contributor-license-agreements/)
- The PR follows the [mbed TLS coding standards](https://tls.mbed.org/kb/development/mbedtls-coding-standards)
A few sentences describing the overall goals of the …
=> fix memory leak in mpi_miller_rabin()

ChangeLog, library/x509_crt.c
This patch fixes an issue we encountered with more stringent compiler
warnings.  The signature_is_good variable has a possibility of being
used uninitialized.  This patch moves the use of the variable to a
place where it cannot be used while uninitialized.
Signed-off-by: Andy Gross <andy.gross@linaro.org>
**Backport status:** this has been backported to 2.16 in https://github.com/ARMmbed/mbedtls/pull/2813 and is not applicable to 2.7.
Notes:
or for companies or those that do not wish to create an mbed account, a slightly different agreement can be found [here](https://www.mbed.com/en/about-mbed/contributor-license-agree …
=> Fix uninitialized variable in x509_crt (#2392 resubmit)

ChangeLog, include/mbedtls/net_sockets.h, library/net_sockets.c, programs/ssl/ssl_fork_server.c
When building a forking server the parent process should close the client socket and continue accepting, while the child process should close the listening socket and handle the client socket.
Overwriting the file descriptor does not close it, so `mbedtls_net_init` is not enough.
`mbedtls_net_shutdown` will close down the socket for writes which also affects the child process so this cannot be used either.
The forking server simply overwrites the socket file descriptor in userspace which does not disassociate the socket from the process as can be seen here:
```
$ ./ssl_fork_server >/dev/null &
[1] 25071
$ for i in {1..10}; do timeout .1 nc localhost 4433; done
$ ls -l /proc/$(pidof ssl_fork_server)/fd | grep socket
lrwx------ 1 user user 64 Aug 23 10:53 10 -> socket:[69247]
lrwx------ 1 …
```
=> Added mbedtls_net_close

tests/ssl-opt.sh
This is a backport of https://github.com/ARMmbed/mbedtls/pull/2815.
=> Backport 2.7: ssl-opt.sh: wait for proxy to start before running the script further

tests/ssl-opt.sh
This is a backport of https://github.com/ARMmbed/mbedtls/pull/2815.
=> Backport 2.16: ssl-opt.sh: wait for proxy to start before running the script further

ChangeLog, library/bignum.c
The previous implementation of `mpi_uint_bigendian_to_host_c()` did a byte-swapping regardless of the endianness of the system. Fixes #2622 found by @mrpippy.
Still needs a ChangeLog entry.
=> Fix mpi_bigendian_to_host() on bigendian systems that don't have BYTE_ORDER defined

tests/scripts/all.sh
Disable `MBEDTLS_PSA_CRYPTO_C` since it isn't supposed to be used. Disable `MBEDTLS_MEMORY_BUFFER_ALLOC_C` which makes ASan mostly ineffective (in all the tests that were enabling it and compiling with ASan).
Backports: no. `test_no_use_psa_crypto_full_cmake_asan` does not exist in 2.7 and 2.16. There are tests with MEMORY_BUFFER_ALLOC+ASan, but I'm planning an overhaul of those soon anyway as part of the ventilation of #2684.
=> Fix test_no_use_psa_crypto_full_cmake_asan in all.sh

ChangeLog, library/platform_util.c
In reference to issue https://github.com/ARMmbed/mbed-crypto/issues/49
Straight forward backport of https://github.com/ARMmbed/mbed-crypto/pull/222
=> Backport 2.16: Check for zero length and NULL buffer pointer

ChangeLog, library/bignum.c
This is the backport to Mbed TLS 2.16 of #2623.
=> Backport 2.16: Fix mpi_bigendian_to_host() on bigendian systems that don't have BYTE_ORDER defined

programs/ssl/ssl_client2.c, programs/ssl/ssl_server2.c
__Summary:__ This PR adds command line options `nss_keylog=0/1` and `nss_keylog_file=PATH` to `ssl_client2` and `ssl_server2` which allow to print and export session keys in the NSS keylog format used e.g. by Wireshark for decryption of TLS traffic. 
The feature is implemented using @RonEld's recent extended key export feature.
__Wireshark usage:__ 
* Set a NSS keylog file `FILE` in Wireshark ( _Edit -> Preferences -> Protocol -> (Pre)-Master-Secret log filename_).
* Run `ssl_client2` or `ssl_server2` with `nss_keylog=1 nss_keylog_file=FILE` while Wireshark is listening.
* Use the _Decrypted Traffic_ tab in Wireshark to inspect the decrypted traffic.
=> Add support for NSS key log export to ssl_client2/ssl_server2 for Wireshark debugging

include/mbedtls/ssl.h, library/ssl_tls.c, programs/ssl/ssl_client2.c, programs/ssl/ssl_server2.c
Make client_random and server_random const in
mbedtls_ssl_export_keys_ext_t, so that the key exporter is discouraged
from modifying the client/server hello.
Fixes #2759
**READY**
NO  
YES - but not for any released versions. We want to update the API to something sane before this API is released for the first time.
=> ssl: Disallow modification of hello.random by export

visualc/VS2010/mbedTLS.vcxproj
This brings in the removal of md_wrap.c and regenerates the generated
files to accommodate the change.
Note that this will fix the Mbed Crypto PR job's TLS testing.
**READY**
NO
NO
- ~[ ] Changelog updated~
=> crypto: Update submodule to 3f20efc03016

ChangeLog, doxygen/input/doc_mainpage.h, doxygen/mbedtls.doxyfile, include/mbedtls/version.h, library/CMakeLists.txt, tests/suites/test_suite_version.data
Update ChangeLog and version number for 2.19.1, which includes a late-breaking API change.
**READY**
NO
NO
- ~[ ] Tests~
=> Bump Mbed TLS version to 2.19.1

library/ssl_tls.c
Fix the `ssl-opt.sh` test case `export keys functionality` which fails when using the latest version of Mbed Crypto (since https://github.com/ARMmbed/mbed-crypto/pull/257 was merged).
Updates the crypto submodule to the result of the merge of https://github.com/ARMmbed/mbed-crypto/pull/276.
=> Fix "export keys functionality" with the latest mbed-crypto

ChangeLog, library/bignum.c
Backport of #2577 to `mbedtls-2.16`
**READY**
=> Backport 2.16: Remove a redundant function call 

library/error.c, tests/suites/test_suite_x509parse.data
Update crypto submodule:
* ARMmbed/mbed-crypto#277: Improve speed of PBKDF2 by caching the digest state of the passphrase
* ARMmbed/mbed-crypto#269: Add PSA API versioning
* ARMmbed/mbed-crypto#278: Fix on target test issues
* ARMmbed/mbed-crypto#286: Fix defgroup syntax for API version section
* ARMmbed/mbed-crypto#75: ASN.1 tests without x509
Update `error.c`; this fixes `check-generated-files` breaking in the TLS testing on Mbed Crypto.
Uncomment a test case that was broken until ARMmbed/mbed-crypto#75 fixed it.
=> Update crypto 2019-10-04

library/Makefile, programs/Makefile, tests/Makefile, tests/scripts/all.sh
Issue raised here.
This fixes two issues:
- incorrect dependency which made parallel jobs fail for shared targets;
- parallel building of the .so and .a versions of libmbedcrypto (which made the .o files being built twice).
Detailed descriptions can be found in commits.
This PR is a newer version of https://github.com/ARMmbed/mbedtls/pull/2879, and there's a difference in how libmbedcrypto with a path prefix is handled. Since the previous approach was wrong (subsequent calls to make without changes made libmbedcrypto.so to be relinked), this PR handles it differently.
=> Fix parallel make jobs for shared target 

ChangeLog, include/mbedtls/config.h, include/mbedtls/ctr_drbg.h, include/mbedtls/hmac_drbg.h
Improve the documentation of the CTR_DRBG and HMAC_DRBG module, in particular in relation to NIST SP 800-90A.
When using and SHA-256 in the entropy module, CTR_DRBG can only achieve the maximum possible strength (256 bits) if you pass a nonce as the `custom` parameter of `mbedtls_ctr_drbg_seed`. State this explicitly.
In addition, I reviewed the documentation and made various improvements (more detailed about requirements on function parameters, better presentation, etc.). I ported these improvements to HMAC_DRBG.
Backport of #2860 (and also https://github.com/ARMmbed/mbed-crypto/pull/287).
Internal ref: IOTCRYPT-180, IOTCRYPT-457
=> Backport 2.7: DRBG documentation improvements

library/ssl_srv.c
Warnings are treated as errors in Mbed TLS test. An error
"ssl_parse_client_hello_v2’ defined but not used" can occur in some
specific configurations and therefore tests will break.
Use similar flags for static function "ssl_parse_client_hello_v2" as
what is used when calling the function to prevent the compilation
warning/error.
**READY**
=> [Baremetal] Harmonize static function compiler flags

programs/test/selftest.c, tests/configs/config-wrapper-malloc-0-null.h, tests/scripts/all.sh
On our main test platforms (Linux, FreeBSD), malloc(0) returns a non-NULL pointer. With `MBEDTLS_MEMORY_BUFFER_ALLOC_C`, `calloc(0,_)` does return NULL, but memory_buffer_alloc doesn't play well with UBSan. Add a test component with UBSan where `calloc` returns NULL when asked to allocate 0 bytes, wrapping around the platform `calloc`.
Straightforward backport of https://github.com/ARMmbed/mbed-crypto/pull/264.
=> Backport 2.7: Test the library when malloc(0) returns NULL

programs/test/selftest.c, tests/configs/config-wrapper-malloc-0-null.h, tests/scripts/all.sh
On our main test platforms (Linux, FreeBSD), malloc(0) returns a non-NULL pointer. With `MBEDTLS_MEMORY_BUFFER_ALLOC_C`, `calloc(0,_)` does return NULL, but memory_buffer_alloc doesn't play well with UBSan. Add a test component with UBSan where `calloc` returns NULL when asked to allocate 0 bytes, wrapping around the platform `calloc`.
Straightforward backport of https://github.com/ARMmbed/mbed-crypto/pull/264.
=> Backport 2.16: Test the library when malloc(0) returns NULL

tests/scripts/all.sh, tests/scripts/run-test-suites.pl
Make sure that all defects reported by Asan, including memory leaks, are treated as failures. This was not the case when running `make test`: we could see the Asan messages in the logs, but only if we went looking for them, because the tests were recorded as passing.
On `mbedtls/development`, no test failure was uncaught because of this.
TLS port of https://github.com/ARMmbed/mbed-crypto/pull/304
=> Make sure Asan failures are detected in 'make test'

tests/scripts/all.sh, tests/scripts/run-test-suites.pl
Make sure that all defects reported by Asan, including memory leaks, are treated as failures. This was not the case when running `make test`: we could see the Asan messages in the logs, but only if we went looking for them, because the tests were recorded as passing.
On `mbedtls-2.7`, no test failure was uncaught because of this.
Backport of https://github.com/ARMmbed/mbedtls/pull/2898
=> Backport 2.7: Make sure Asan failures are detected in 'make test'

tests/scripts/all.sh, tests/scripts/run-test-suites.pl
Make sure that all defects reported by Asan, including memory leaks, are treated as failures. This was not the case when running `make test`: we could see the Asan messages in the logs, but only if we went looking for them, because the tests were recorded as passing.
On `mbedtls-2.16`, no test failure was uncaught because of this.
Backport of https://github.com/ARMmbed/mbedtls/pull/2898
=> Backport 2.16: Make sure Asan failures are detected in 'make test'

library/ssl_tls.c
Record checking fails if `mbedtls_ssl_check_record()` is called with
external buffer. Received record sequence number is available in the
incoming record but it is not available in the ssl contexts `in_ctr`-
variable that is used when decoding the sequence number.
To fix the problem, temporarily update ssl context `in_ctr` to
point to the received record header and restore value later.
**READY**
Yes, development branch: 
Done in PR: https://github.com/ARMmbed/mbedtls/pull/2909
=> [baremetal] Fix mbedtls_ssl_check_record usage with ext buf

tests/scripts/all.sh, tests/ssl-opt.sh
This PR enables running the ssl_opt.sh when built using the baremetal.sh script by running
`./scripts/baremetal.sh --ram --build-only` and adds a specific all.sh-component for it.
DONE
- Add all.sh entry
=> [Baremetal] Make ssl_opt.sh run with baremetal-configuration

library/x509write_crt.c, library/x509write_csr.c, programs/pkey/pk_sign.c, programs/pkey/pk_verify.c, tests/scripts/all.sh
Use the new constant `MBEDTLS_PK_SIGNATURE_MAX_SIZE` introduced by a crypto submodule update, rather than rolling our own incomplete definition.
Remove a test component from `all.sh` that was a regression test for the maximum signature size being calculated incorrectly, which is now covered via unit tests in `config-suite-b.h`.
Update the crypto submodule to https://github.com/ARMmbed/mbed-crypto/pull/315. The submodule update commit will need to be amended once that PR is merged.
Internal ref: IOTSSL-2943
=> Use MBEDTLS_PK_SIGNATURE_MAX_SIZE

library/x509write_csr.c
Using 4096 bytes of stack for the temporary buffer used for holding a
throw-away DER-formatted CSR limits the portability of generating
certificate signing requests to only devices with lots of stack space.
To increase portability, use the mbedtls_pem_write_buffer() in-place
capability instead, using the same buffer for input and output. This
works since the DER encoding for some given data is always smaller than
that same data PEM-encoded.
PEM format is desirable to use even on stack-constrained devices as the
format is easy to work with (for example, copy-pasting from a tiny
device's serial console output, for CSRs generated on tiny devices
without the private key leaving said tiny device).
**READY**
NO  
NO
- ~[ …
=> x509write_csr: Reduce stack usage of mbedtls_x509write_csr_pem()

library/platform_util.c
This is a temporary work-around for an integration issue.
A future task will re-integrate randomness into these functions are their
entire point is to be randomized; this is really just temporary.
**READY**
=> [baremetal] Disable use of HRNG in SCA-hardened mem-functions

include/tinycrypt/ecc.h, tinycrypt/ecc.c, tinycrypt/ecc_dh.c, tinycrypt/ecc_dsa.c
The TinyCrypt code already includes counter-measures against a number of side-channels. However, internal analysis has identified a number of additional counter-measures that could help protect against more attacks. This PR implements them.
Since the counter-measures add a non-trivial amount of code, the PR then looks at easy ways to save code size. One of them is implemented (hardcoding numwords internally), the other (hardcoding curve internally) might be deferred to a later PR.
Size of `libmbedcrypto.a` in bytes, measured with `scripts/baremetal.sh --rom --armc5`.
| | size (bytes) | diff (prev. line) | diff (first line) |
| --- | --- | --- | --- |
| before | 18699 | | |
| after counter-measures | 19099 | +400 | |
| after hardcoding numwords | 18427 | -672 | -272 |
Time in ms for a …
=> [baremetal] TinyCrypt: addtional SCA counter-measures

programs/ssl/ssl_server2.c
One of the execution paths in sslserver2 doesn't release a file handle.
=> Fix potential resource leak in sslserver2 example

ChangeLog, library/ssl_tls.c
Fix issues:
Resolve #2717 - remove erroneous `sizeof` (the operator was applied to constant integer number)
Resolve #2800 - move declaration to avoid unused variable warning in case `MBEDTLS_SSL_PROTO_DTLS` was undefined
Resolve #2801 - remove repetitive assignment to `ssl->in_msg` (the first value was never used)
Additionally, `mbedtls_ssl_send_fatal_handshake_failure` was overcomplicated and could be written in one line.
**READY**
NO  
Which branch?
development
NO
Edit Ron: Add the "Resolve" magic word to automatically close the issues once merged
=> Fix issues in ssl_tls.c

library/ssl_tls.c, programs/ssl/ssl_client2.c, programs/ssl/ssl_server2.c
Support for mbedtls buffered allocator was added to ssl_client2
in development. This PR is related with future optimization works
calloc in mbedtls buffered allocator returns NULL when it is called with size 0, but others allocators could return regular pointer. That was causing different behavior inside mbedtls_ssl_conf_psk function depending on which allocator is used. In this PR was added checking if size is 0 before calloc call
=> Avoid allocating 0-length buffers for PSK. Add memory debug information to ssl_client2.

tests/suites/test_suite_memory_buffer_alloc.data, tests/suites/test_suite_memory_buffer_alloc.function
Backport of https://github.com/ARMmbed/mbed-crypto/pull/310
=> Backport 2.7: Clarify test descriptions in test_suite_memory_buffer_alloc

tests/suites/test_suite_memory_buffer_alloc.data, tests/suites/test_suite_memory_buffer_alloc.function
Backport of https://github.com/ARMmbed/mbed-crypto/pull/310
=> Backport 2.16: Clarify test descriptions in test_suite_memory_buffer_alloc

ChangeLog, include/mbedtls/ctr_drbg.h, include/mbedtls/hmac_drbg.h, library/ctr_drbg.c, library/hmac_drbg.c, programs/test/benchmark.c, tests/suites/test_suite_ctr_drbg.function
The functions `mbedtls_ctr_drbg_set_entropy_len()` and `mbedtls_hmac_drbg_set_entropy_len()` were only supported after the call to `mbedtls_ctr_drbg_seed()` and `mbedtls_hmac_drbg_seed()`, so the initial seeding always grabbed the amount of entropy defined at compile time (`MBEDTLS_CTR_DRBG_ENTROPY_LEN` for CTR_DRBG, calculated from the hash algorithm for HMAC_DRBG). There was no good reason for that and the documentation was not clear prior to https://github.com/ARMmbed/mbed-crypto/pull/287. Change the API to be intuitive: you can call `set_entropy_len()` after `init()`, and it will influence both the initial seeding (if you call it before `seed()`) and subsequent reseeds.
Keep the test-only function `mbedtls_ctr_drbg_seed_entropy_len` for strict ABI compatibility.
Backport of …
=> Backport 2.7: Allow xxx_drbg_set_entropy_len before xxx_drbg_seed

ChangeLog, include/mbedtls/ctr_drbg.h, include/mbedtls/hmac_drbg.h, library/ctr_drbg.c, library/hmac_drbg.c, programs/test/benchmark.c, tests/suites/test_suite_ctr_drbg.function
The functions `mbedtls_ctr_drbg_set_entropy_len()` and `mbedtls_hmac_drbg_set_entropy_len()` were only supported after the call to `mbedtls_ctr_drbg_seed()` and `mbedtls_hmac_drbg_seed()`, so the initial seeding always grabbed the amount of entropy defined at compile time (`MBEDTLS_CTR_DRBG_ENTROPY_LEN` for CTR_DRBG, calculated from the hash algorithm for HMAC_DRBG). There was no good reason for that and the documentation was not clear prior to https://github.com/ARMmbed/mbed-crypto/pull/287. Change the API to be intuitive: you can call `set_entropy_len()` after `init()`, and it will influence both the initial seeding (if you call it before `seed()`) and subsequent reseeds.
Keep the test-only function `mbedtls_ctr_drbg_seed_entropy_len` for strict ABI compatibility.
Backport of …
=> Backport 2.16: Allow xxx_drbg_set_entropy_len before xxx_drbg_seed

CMakeLists.txt, include/tinycrypt/ecc.h, include/tinycrypt/ecc_dh.h, include/tinycrypt/ecc_dsa.h, library/CMakeLists.txt, library/Makefile, tests/scripts/all.sh, tests/scripts/list-symbols.sh, tinycrypt/ecc.c, tinycrypt/ecc_dh.c, tinycrypt/ecc_dsa.c
This PR removes from the TinyCrypt header and source code files, the configuration condition on `MBEDTLS_USE_TINYCRYPT` to include the file contents.
This is to allow use of the library by the Factory Tool without enabling `MBEDTLS_USE_TINYCRYPT`, and also removes a modification we've made to make the code closer to the upstream TinyCrypt making it easier to maintain.
This change has already been made in the solution repo in PR #160 downstream, and needs to be reflected here.
**READY**
NO  
NO
=> [baremetal] Remove TinyCrypt config condition in source files

library/ssl_tls.c
One of `memcmp` calls may not be clearly valid due to the value used as the size argument. This PR choses another variable for that purpose. This happens right after an equality test, which guarantees that the code is effective equivalent after the change.
However, the new `memcmp` call no longer uses a value derived from external input.
=> Improve clarity of a memory operation call

tests/suites/helpers.function, tests/suites/target_test.function, tests/suites/test_suite_ssl.data, tests/suites/test_suite_ssl.function
In a unit test we want to avoid accessing the network. To test the handshake in the unit test suite we need to implement a connection between the server and the client.
This PR implements a ring buffer and uses them to provide mock TCP sockets and corresponding blocking and non-blocking callbacks.
Sanity tests for the mocks are also provided.
The first two commits are cherry-picked from Mbed Crypto and only introduce a test helper macro.
**READY**
NO
=> Mock TCP sockets and callbacks for SSL unit tests

visualc/VS2010/mbedTLS.vcxproj
Fixes the failure of `check-generates-files` in the TLS job on the Mbed Crypto repository.
* #321: Replace config.pl by config.py
* #322: Update Mbed Crypto with latest Mbed TLS changes as of 2019-11-15
* #308: Small performance improvement of mbedtls_mpi_div_mpi()
* #324: test_psa_constant_names: support key agreement, better code structure
* #320: Link to the PSA crypto portal page from README.md
* #293: Always gather MBEDTLS_ENTROPY_BLOCK_SIZE bytes of entropy
* #310: Clarify test descriptions in test_suite_memory_buffer_alloc
* #307: Add ASN.1 ENUMERATED tag support
* #328: Remove dependency of crypto_values.h on crypto_extra.h
* #325: Rename psa_asymmetric_{sign_verify} to psa_{sign,verify}_hash
Missed listing in the previous submodule update:
* #304: Make sure Asan failures are …
=> Update crypto submodule

library/platform_util.c
This reverts commit 1e96b46b032aa27d9388e395c3591b8c33005b4f from https://github.com/ARMmbed/mbedtls/pull/2930 that was created to temporarily disable usage of hardened SCA memory functions.
**READY**
=> [baremetal] Re-enable hardened SCA mem functions

README.md
Update the VS version in the README file to 2012, as this is the
minimal version supported.
**READY**
NO  - The Minimal VS version was updated since 2.18
NO
##additional comments
Partly addresses #2896
=> Update the VS version in the Readme file

include/mbedtls/error.h, library/debug.c, library/error.c, library/net_sockets.c, library/ssl_cli.c, library/ssl_cookie.c, library/ssl_srv.c, library/ssl_ticket.c, library/ssl_tls.c, library/x509.c, library/x509_create.c, library/x509_crl.c, library/x509_crt.c, library/x509_csr.c, library/x509write_crt.c, library/x509write_csr.c, scripts/data_files/error.fmt, scripts/generate_errors.pl
Initializing the return values to an error is best practice and makes the library more robust.
We already had an error code reserved for generic errors, this PR makes it explicit.
Needs to go in in tandem with https://github.com/ARMmbed/mbed-crypto/pull/323
**READY**
NO
=> Initialize return values to an error

tests/scripts/mbedtls_test.py
Backport of the relevant part of https://github.com/ARMmbed/mbed-crypto/pull/334
This PR fixes a warning that the check_python_files component of all.sh was complaining about.
=> Backport 2.16: Fix some pylint warnings

tinycrypt/ecc_dsa.c
Duplicating the g_rng_function variable in ecc_dsa.c means it's not the same
as set in ecc.c, resulting if no randomisation here. The proper way to access
the RNG function from outside ecc.c is uECC_get_rng(), so use that.
This is a side-port of upstream commit https://github.com/intel/tinycrypt/commit/87d74dd8d64a99aaa188961fe763d0841c5abfef
I've verified that there are no other occurrences (the duplication of
g_rng_function in ecc_dh.c had already been removed earlier when centralising
projective coordinate randomisation to mult_safer()).
**READY**
NO
=> [baremetal] [tinycrypt] fix bug in RNG access in ECDSA SCA counter-measure

tests/scripts/mbedtls_test.py
Sideport of #2967 
Fix a too-long line to meet PEP8 standards
=> [baremetal] Fix some pylint warnings

library/ssl_tls.c
Clear memory from internal decrypted buffers with memset.
=> [baremetal] Clear internal decrypted buffer after read

tinycrypt/ecc.c
Removed coverity finding of condition which is always false.
(num_n_bits < ((bitcount_t)num_n_words * uECC_WORD_SIZE * 8)
would always be
256 < 8 * 4 * 8
256 < 256
__Impact on code-size:__
| | ARMC5 |
| --- | --- |
| `libmbedcrypto.a` before | 18659|
| `libmbedcrypto.a` after | 18673|
| gain in bytes Crypto | -14 |
**READY**
=> [baremetal] Coverity fix: dead error condition removed from ecc.c

library/error.c, scripts/data_files/error.fmt
Defines MBEDTLS_ERR_SSL_WANT_READ and MBEDTLS_ERR_SSL_WANT_WRITE were more than 0xFF80 so raised value which error is ANDed to 0xFFFF80.
=> [baremetal] Fix mbedtls_strerror to work with all wanted codes

library/aes.c
This PR adds SCA countermeasures to AES module on places where
get/put_uint32 on secret data is used.
When reading the input, the buffer will be initialised with random data
and the reading will start from a random offset. When writing the data,
the output will be initialised with random data and the writing will
start from a random offset.
**READY**
Needs preceding PRs to be merged: ~~#2886 and #2948~~
=> [baremetal] Add SCA countermeasures to get/put -methods on secret data

include/mbedtls/platform_util.h, library/entropy.c, library/pk.c, library/platform_util.c, library/ssl_cli.c, library/ssl_srv.c, library/ssl_tls.c, library/x509_crt.c, tinycrypt/ecc.c, tinycrypt/ecc_dsa.c
Add delay function `mbedtls_platform_random_delay` to platform_utils. The function will delay
program execution by incrementing local variable and doing xor byte operations a randomised number of times.
This PR contains an API break, function `mbedtls_platform_enforce_volatile_reads` is removed. The same kind of behaviour is achieved by using function `mbedtls_platform_random_delay(0)`.
__Impact on code-size:__
| | ARMC5 |
| --- | --- |
| `libmbedcrypto.a` before | 18659 |
| `libmbedcrypto.a` after | 18699 |
| gain in bytes Crypto | -40 |
**READY**
=> [baremetal] Add random delay function to platform utils

ChangeLog, library/ecdsa.c
This is the backport to Mbed TLS 2.16 of https://github.com/ARMmbed/mbed-crypto/pull/354
In addition to the original, it has a ChangeLog entry. Reviewers, please review carefully that this entry correctly reflects the security impact of the issue.
=> [Backport 2.16] Fix incrementing pointer instead of value

ChangeLog
Describe changes between mbedcrypto-2.0.0 (version in Mbed TLS 2.19.0)
and mbedcrypto-3.0.0 (version in Mbed TLS 2.20.0).
Content also submitted in https://github.com/ARMmbed/mbed-crypto/pull/300 (in a slightly different format). 6a4c340c3626ec4c0947ef64b724e47f80aa8253 here is aligned with c26479c1af343aa74d2605bfbf5d37622014144a there.
=> Add changelog entries for the crypto changes in 2.20.0

tests/suites/test_suite_ssl.data, tests/suites/test_suite_ssl.function
This PR applies to IO callbacks used in ssl test suites and contains:
* Fixed segmentation fault for some of sequences realized with mbedtls_test_buffer
* Changed behavior for non-blocking read/write. Previously the blocking error was used depending on blocking_patern which was preset by test designer. Currently the blocking error for non-blocking functions is returned depending on whether buffer is empty or full
* Tests for both upper points
**READY**
NO  
NO
=> Changes in custom IO callbacks used in unit tests

ChangeLog, library/x509_crt.c
When mbedtls_x509_crt_parse_path() checks each object in the supplied path, it only processes regular files. This change makes it also accept a symlink to a file. Fixes #3005.
This was observed to be a problem on Fedora/CentOS/RHEL systems, where the ca-bundle in the default location is actually a symlink.
=> Allow loading symlinked certificates

ChangeLog, library/x509_crt.c
Backport of https://github.com/ARMmbed/mbedtls/pull/3008
CC @jp-bennett
=> Backport 2.7: Allow loading symlinked certificates

ChangeLog, library/x509_crt.c
Backport of https://github.com/ARMmbed/mbedtls/pull/3008
CC @jp-bennett
=> Backport 2.16: Allow loading symlinked certificates

ChangeLog
Follow-up to https://github.com/ARMmbed/mbedtls/pull/3007
=> [2.16] Fix contributor names in ChangeLog

ChangeLog, library/cipher.c, library/x509write_csr.c, tests/suites/test_suite_mpi.function
Straightforward backport of the applicable parts of https://github.com/ARMmbed/mbed-crypto/pull/349 and https://github.com/ARMmbed/mbedtls/pull/2995
=> Backport 2.7: Fix minor defects found by Coverity

ChangeLog, library/cipher.c, library/x509write_csr.c, tests/suites/test_suite_ecdsa.function, tests/suites/test_suite_mpi.function, tests/suites/test_suite_pk.function
Straightforward backport of the applicable parts of https://github.com/ARMmbed/mbed-crypto/pull/349 and https://github.com/ARMmbed/mbedtls/pull/2995
=> Backport 2.16: Fix minor defects found by Coverity

ChangeLog, library/x509write_csr.c, programs/ssl/ssl_client2.c, tests/suites/host_test.function
* A missing return code check in X509, which could happen on hardware accelerator failure.
* Some resource leaks in corner cases in test programs.
The missing return code check should be backported.
- 2.16 #3001 
- 2.7 #3002
=> Fix minor defects found by Coverity

ChangeLog, include/CMakeLists.txt
> Notes:
> * Pull requests cannot be accepted until:
> -  The submitter has [accepted the online agreement here with a click through](https://developer.mbed.org/contributor_agreement/) or for companies or those that do not wish to create an mbed account, a slightly different agreement can be found [here](https://www.mbed.com/en/about-mbed/contributor-license-agreements/)
> - The PR follows the [mbed TLS coding standards](https://tls.mbed.org/kb/development/mbedtls-coding-standards)
In CMake files, declare include headers as `PUBLIC` to propagate to project consumers.
**READY**
NO  
NO
This change only extends existing capabilities, and should have no risk of regression. This class of enhancement can be performed as needed/discovered, because each addition provides incremental value. This …
=> [cmake] Propagate public headers

tests/suites/test_suite_ssl.data, tests/suites/test_suite_ssl.function
This PR is an implementation of  IOTSSL-2958.
It adds tests for a message-based connection. An additional layer of metadata is laid on the base of I/O callbacks to perform as a message queue. The receive function had to be modified to enable data dropping.
The changes themselves can be divided into two (as are the tests for them):
- The metadata layer only, which can operate separately from the connection itself (this lets the developers to approach it in a more TDD way);
- The integration layer, which uses the underlying mocked sends/reads and the metadata layer to provide a compound functionality, hidden behind `mbedtls_message_socket_setup`, `mbedtls_mock_tcp_send_msg`, `mbedtls_mock_tcp_recv_msg`, and `mbedtls_message_socket_close`. 
The only function that's used from the lower, …
=> Message transport mocks in ssl tests

ChangeLog, library/ssl_tls.c
When `MBEDTLS_ZLIB_SUPPORT` is defined and `-DENABLE_ZLIB_SUPPORT=1` is enabled,  mbedtls will build with zlib support but now has an issue starting with 2.19.1.
100% tests passed, 0 tests failed out of 85 for both the current development branch and 2.19.1
Previous implementations of zlib did not use session_negotiate: [2.17.0](https://github.com/ARMmbed/mbedtls/blob/mbedtls-2.17.0/library/ssl_tls.c#L1348) [2.18.1](https://github.com/ARMmbed/mbedtls/blob/mbedtls-2.18.1/library/ssl_tls.c#L1594)
https://github.com/ARMmbed/mbedtls/blob/mbedtls-2.19.1/library/ssl_tls.c#L1842
```
#if defined(MBEDTLS_ZLIB_SUPPORT)
ssl->session_negotiate->compression,
#endif
```
[Problem line here](https://github.com/ARMmbed/mbedtls/blob/mbedtls-2.19.1/library/ssl_tls.c#L1862)
I don't understand why not just …
=> Fix definition error for the deprecated zlib support if enabled

ChangeLog, library/ssl_tls.c, tests/scripts/all.sh, tests/ssl-opt.sh
This PR fixes a gap in our testing: we didn't test any build with zlib (for TLS record compression) enabled. This is a deprecated option but it should nonetheless be tested until it's removed for real.
The usefulness of these tests is illustrated by the fact that in their absence, we introduced two bug in 2.19 that caused us to fail to build or run with zlib enabled: #2859 plus another one that was found by the tests and is fixed in this PR.
__Dependencies:__ This PR is based on #2963 which fixes a bug in building with zlib - the added test obviously wouldn't pass without that fix.
**READY**
Yes - for the tests (the bugfix is only applicable to development, the LTS branches are free from the bug as the tests show).
NO
No ChangeLog entry as this is only a change in tests, not in the …
=> Add zlib tests and fix runtime bug

tests/scripts/all.sh, tests/ssl-opt.sh
This PR fixes a gap in our testing: we didn't test any build with zlib (for TLS record compression) enabled. This is a deprecated option but it should nonetheless be tested until it's removed for real.
The usefulness of these tests is illustrated by the fact that in their absence, we introduced a bug in 2.19 that caused us to fail to build with zlib enabled: https://github.com/ARMmbed/mbedtls/issues/2859
**READY**
This is the 2.16 backport of https://github.com/ARMmbed/mbedtls/pull/2975
NO
No ChangeLog entry as this is only a change in tests, not in the library.
`tests/scripts/all.sh 'test_zlib*'`
=> [2.16] Add zlib tests

tests/scripts/all.sh, tests/ssl-opt.sh
This PR fixes a gap in our testing: we didn't test any build with zlib (for TLS record compression) enabled. This is a deprecated option but it should nonetheless be tested until it's removed for real.
The usefulness of these tests is illustrated by the fact that in their absence, we introduced a bug in 2.19 that caused us to fail to build with zlib enabled: https://github.com/ARMmbed/mbedtls/issues/2859
**READY**
This is the 2.7 backport of https://github.com/ARMmbed/mbedtls/pull/2975
NO
No ChangeLog entry as this is only a change in tests, not in the library.
`tests/scripts/all.sh 'test_zlib*'`
=> [2.7] Add zlib tests

include/mbedtls/config.h, library/aes.c
Move dummy rounds to the start/end of the AES calculations.
__Impact on code-size:__ with SCA_CM flag (MBEDTLS_AES_SCA_COUNTERMEASURES) disabled/enabled
| | GCC | ARMC5 | ARMC6 |
| --- | --- | --- | --- |
| `libmbedcrypto.a` with SCA_CM flag disabled | 18533 | 18781 | 21045 |
| `libmbedcrypto.a` with CSA_CM flag enabled | 18717 | 18733 | 21219 |
| gain Total | -184 | 48 | -174 |
**READY**
=> [baremetal] AES SCA countermeasures update

tests/suites/test_suite_ssl.data, tests/suites/test_suite_ssl.function
Description
This PR add test for prescribed states of handshake and gives endpoint structure which allows to future SSL communication simulation with the custom IO callbacks
**READY**
NO
=> Add test for prescribed states of handshake with the custom IO callbacks

include/mbedtls/ssl_internal.h, library/ssl_cli.c
Update the SSL client code for ECDH using PSA crypto to the new elliptic curve key type encoding in https://github.com/ARMmbed/mbed-crypto/pull/330.
This pull request and https://github.com/ARMmbed/mbed-crypto/pull/330 need to be merged close together because the crypto PR breaks mbedtls. To merge:
=> USE_PSA_CRYPTO: update elliptic curve encoding

ChangeLog, library/pkparse.c, library/rsa.c
Otherwise these values are recomputed in mbedtls_rsa_deduce_crt, which
currently suffers from side channel issues in the computation of QP
(see https://eprint.iacr.org/2020/055). By loading the pre-computed
values not only is the side channel avoided, but runtime overhead of
loading RSA keys is reduced.
Discussion in https://github.com/ARMmbed/mbed-crypto/issues/347
Backport of https://github.com/ARMmbed/mbed-crypto/pull/352
=> Backport 2.16: Parse RSA parameters DP, DQ and QP from PKCS1 private keys

ChangeLog, library/pkparse.c, library/rsa.c
Otherwise these values are recomputed in mbedtls_rsa_deduce_crt, which
currently suffers from side channel issues in the computation of QP
(see https://eprint.iacr.org/2020/055). By loading the pre-computed
values not only is the side channel avoided, but runtime overhead of
loading RSA keys is reduced.
Discussion in https://github.com/ARMmbed/mbed-crypto/issues/347
Backport of https://github.com/ARMmbed/mbed-crypto/pull/352
=> Backport 2.7: Parse RSA parameters DP, DQ and QP from PKCS1 private keys

programs/fuzz/fuzz_privkey.c, programs/fuzz/fuzz_pubkey.c
Checks `mbedtls_rsa_export` return in fuzz targets
It should always return 0
cf https://github.com/ARMmbed/mbedtls/pull/1622#discussion_r369109172
**READY**
NO  
NO
Should I add a Changelog entry ?
=> Checks mbedtls_rsa_export return in fuzz targets

tests/ssl-opt.sh
While the whole script makes (often implicit) assumptions about the version of
GnuTLS used, generally speaking it should work out of the box with the version
packaged on our reference testing platform, which is Ubuntu 16.04 so far.
With the update from Jan 8 2020 (3.4.10-4ubuntu1.6), the patches for rejecting
SHA-1 in certificate signatures were backported, so we should avoid presenting
SHA-1 signed certificates to a GnuTLS peer in ssl-opt.sh.
**READY**
Yes
Run `tests/ssl-opt.sh` on an up-to-date Ubuntu 16.04 machine before and after this PR.
=> Fix ssl-opt.sh for GnuTLS versions rejecting SHA-1

tests/ssl-opt.sh
This is the 2.16 backport of #3018.
=> [backport 2.16] Fix ssl-opt.sh for GnuTLS versions rejecting SHA-1

ChangeLog, include/mbedtls/check_config.h, include/mbedtls/config.h, include/mbedtls/pkcs11.h
This PR deprecates the feature MBEDTLS_PKCS11_C (and its associated functions).
**READY**
NO  
There are no hard/functional dependencies on other changes, but the use of the macros MBEDTLS_DEPRECATED_REMOVED and MBEDTLS_DEPRECATED_WARNING is according to the documentation changes in https://github.com/ARMmbed/mbedtls/pull/2236. Ideally this PR would be merged **AFTER** that other PR.
=> Deprecate feature MBEDTLS_PKCS11_C

scripts/config.py, tests/scripts/all.sh, tests/suites/test_suite_x509write.function
To build only the crypto parts of Mbed TLS, run
```
scripts/config.py crypto
make
```
This is essentially equivalent to building Mbed Crypto.
=> Add crypto-only preset configurations

ChangeLog, library/x509_crt.c
> The changes I suggested can be reverted. stat() will never return S_IFLNK as the file type, as stat() explicitly follows symlinks.
See #3005.
**READY**
Yes, 2.16 and 2.7
=> Revert "Merge pull request #3008 from jp-bennett/development"

library/bignum.c, tests/suites/test_suite_mpi.data, tests/suites/test_suite_mpi.function
Straightforward backport of https://github.com/ARMmbed/mbed-crypto/pull/346
=> Backport 2.16: Improve robustness and testing of mbedtls_mpi_copy

library/bignum.c, tests/suites/test_suite_mpi.data, tests/suites/test_suite_mpi.function
Backport of https://github.com/ARMmbed/mbed-crypto/pull/346. Same bug fix, same new tests, but with test functions using the data representation from the old test framework.
=> Backport 2.7: Improve robustness and testing of mbedtls_mpi_copy

tests/suites/test_suite_ssl.data, tests/suites/test_suite_ssl.function
This pull request contains tests for data transfer via TLS as a stream (Testing of datagram transfer will be added in other PR).
**READY**
NO  
NO
=> Add tests for data transfer to test suites

programs/ssl/ssl_server2.c, tests/scripts/all.sh
Fix #2851. The warning pointed to a genuine bug, but only in a corner case in a test program with a non-default build option.
Expand `all.sh` to ensure that similar bugs would be caught.
Backports: the buggy code didn't exist in the LTS branches, but I think the `all.sh` changes should be backported. [edited by mpg: #3029 #3030]
=> Fix and test the full config with gcc and clang

tests/scripts/all.sh
Expand `all.sh` to test the full configuration with gcc and clang with several optimization options.
CI passes, so there is nothing to fix on this branch.
Backport of https://github.com/ARMmbed/mbedtls/pull/2852, minus the fix that is not applicable in this branch.
=> Backport 2.16: Fix and test the full config with gcc and clang

tests/scripts/all.sh
Expand `all.sh` to test the full configuration with gcc and clang with several optimization options.
CI passes, so there is nothing to fix on this branch.
Backport of https://github.com/ARMmbed/mbedtls/pull/2852, minus the fix that is not applicable in this branch.
=> Backport 2.7: Fix and test the full config with gcc and clang

ChangeLog, library/x509_crl.c, library/x509_crt.c
Forward port of https://github.com/ARMmbed/mbedtls/pull/2663 contributed by @apple-ihack-geek. The runtime behavior was always correct, but some compilers warned that they weren't sure about it.
- mbedtls-2.16 #2663 
- mbedtls-2.7 #2897 
- mbed-crypto https://github.com/ARMmbed/mbed-crypto/pull/284 (merged)
=> Fix some possibly-undefined variable warnings

ChangeLog, doxygen/input/doc_mainpage.h, doxygen/mbedtls.doxyfile, include/mbedtls/version.h, library/CMakeLists.txt, tests/suites/test_suite_version.data
This PR does the following two changes:
- Updates Mbed TLS version.
- Updates the release information in the ChangeLog header
=> Bump version 2.16.5

ChangeLog, include/mbedtls/check_config.h, include/mbedtls/config.h, include/mbedtls/ssl.h
Deprecate the feature MBEDTLS_SSL_HW_RECORD_ACCEL and its associated global function pointers. This feature is largely undocumented, untested and its usefulness is not clear.
**READY**
NO  
There are no hard/functional dependencies on other changes, but the use of the macros MBEDTLS_DEPRECATED_REMOVED and MBEDTLS_DEPRECATED_WARNING is according to the documentation changes in https://github.com/ARMmbed/mbedtls/pull/2236. Ideally this PR would be merged **AFTER** that other PR.
=> Deprecate feature MBEDTLS_SSL_HW_RECORD_ACCEL

tests/suites/test_suite_ssl.data, tests/suites/test_suite_ssl.function
This PR is a continuation of https://github.com/ARMmbed/mbedtls/pull/3071. 
Due to CI failures, I have dropped the `static` keyword from before `log_pattern`, added a `MBEDTLS_DEBUG_C` dependency to tests due to log parsing, and added `MBEDTLS_DEBUG_C` guards around `mbedtls_debug_set_threshold` and `mbedtls_ssl_conf_dbg` calls.
Tested manually with and without `MBEDTLS_DEBUG_C`.
=> Add a DTLS handshake fragmentation test

programs/ssl/ssl_client2.c, tests/ssl-opt.sh
The ssl-opt.sh test cases using session resumption tend to fail occasionally
on the CI due to a race condition in how ssl_server2 and ssl_client2 handle
the reconnection cycle.
The server does the following in order:
- S1 send application data
- S2 send a close_notify alert
- S3 close the client socket
- S4 wait for a "new connection" (actually a new datagram)
- S5 start a handshake
The client does the following in order:
- C1 wait for and read application data from the server
- C2 send a close_notify alert
- C3 close the server socket
- C4 reset session data and re-open a server socket
- C5 start a handshake
If the client has been able to send the close_notify (C2) and if has been
delivered to the server before if closes the client socket (S3), when the
server reaches S4, the datagram …
=> Fix possible close_notify/ClientHello confusion

programs/ssl/ssl_client2.c, tests/ssl-opt.sh
This is the 2.16 backport of #3050
=> [backport 2.16] Fix possible close_notify/ClientHello confusion

programs/ssl/ssl_client2.c, tests/ssl-opt.sh
This is the 2.7 backport of #3050
It also has an extra commit to align some timeout values with the ones used in the 2.16 branch.
=> [backport 2.7] Fix possible close_notify/ClientHello confusion

.github/pull_request_template.md, CONTRIBUTING.md, README.md, dco.txt
This is the 2.7 backport of https://github.com/ARMmbed/mbedtls/pull/3051
Note, the 2.7 branch did not have a CONTRIBUTING.md so this PR backports the entire file.
=> [backport 2.7] Drop requirement for a CLA

.github/pull_request_template.md, CONTRIBUTING.md, README.md, dco.txt
This is the 2.16 backport of https://github.com/ARMmbed/mbedtls/pull/3051
=> [backport 2.16] Drop requirement for a CLA

programs/fuzz/fuzz_privkey.c, programs/fuzz/fuzz_pubkey.c
`fuzz_pubkey` was systematically failing on valid RSA keys, due to a bug in the sanity checks performed as part of the fuzzed code. Fix this.
Also improve the sanity checks on non-RSA keys.
=> Fix fuzz_pubkey on valid RSA keys

tests/scripts/all.sh
The .pl version is now a compat wrapper around the .py script. Better call the .py script directly.
This PR is intended to remove a few simple merge conflicts when merging crypto back, by making sure both sides use .py everywhere.
**READY**
NO - the TLS branches don't have config.py
=> Fix remaining occurrences of config.pl in all.sh

scripts/output_env.sh
This pull request adds additional information to be outputted by the `output_env.sh` script of:
* the Linux distribution version (if available)
* the GDB version (if available)
It also makes some information clearer:
* the type of OpenSSL/GNUTLS version (legacy/default/next)
* and whether certain versions are not installed, or not configured
And it simplifies the error messages for absent tools.
**READY**
Yes - this helps debug CI problems and doesn't impact the API or functionality of the product
Which branch? 2.16 #3083 and 2.7 #3084 
NO
=> Enhance the `output_env.sh` script with GBD and Distro version

scripts/output_env.sh
This is a backport of PR #3072.
This pull request adds additional information to be outputted by the `output_env.sh` script of:
* the Linux distribution version (if available)
* the GDB version (if available)
It also makes some information clearer:
* the type of OpenSSL/GNUTLS version (legacy/default/next)
* and whether certain versions are not installed, or not configured
And it simplifies the error messages for absent tools.
**READY**
NO
=> Backport 2.16: Enhance the `output_env.sh` script with GBD and Distro version

scripts/output_env.sh
This is backport of PR #3072.
This pull request adds additional information to be outputted by the `output_env.sh` script of:
* the Linux distribution version (if available)
* the GDB version (if available)
It also makes some information clearer:
* the type of OpenSSL/GNUTLS version (legacy/default)
* and whether certain versions are not installed, or not configured
And it simplifies the error messages for absent tools.
**READY**
NO
=> Backport 2.7: Enhance the `output_env.sh` script with GBD and Distro version

tests/suites/test_suite_ssl.function
This PR fixes gcc7 warnings about uninitialized queue members.
=> test_suite_ssl: check for errors during queue setup

tests/suites/test_suite_ssl.function
This PR adds variable initialization to NULL in test_suite_ssl. In case of a memory allocation failure, the freeing functions should now handle data properly.
=> test_suite_ssl: fix coverity issues with uninitialized members

scripts/output_env.sh
Add the versions of Python, Perl, and Pylint to the version dump provided by the `output_env.sh` script.
This is useful for when trying to diagnose CI or Dockerfile problems, particularly in the migration from Python 2 to Python 3.
Once this PR has been reviewed and approved, I'll provide backports.
**READY**
Yes 
Which branch?
`mbedtls-2.16` and `mbedtls-2.7`
=> Add Python, Perl and Pylint to output_env.sh

scripts/output_env.sh
This is a backport of PR #3086.
Add the versions of Python, Perl, and Pylint to the version dump provided by the `output_env.sh` script.
This is useful for when trying to diagnose CI or Dockerfile problems, particularly in the migration from Python 2 to Python 3.
Once this PR has been reviewed and approved, I'll provide backports.
**READY**
=> Backport 2.16: Add Python, Perl and Pylint to output_env.sh

scripts/output_env.sh
This is a backport of PR #3086.
Add the versions of Python, Perl, and Pylint to the version dump provided by the `output_env.sh` script.
This is useful for when trying to diagnose CI or Dockerfile problems, particularly in the migration from Python 2 to Python 3.
Once this PR has been reviewed and approved, I'll provide backports.
**READY**
=> Backport 2.7: Add Python, Perl and Pylint to output_env.sh

ChangeLog, library/ssl_tls.c, tests/scripts/all.sh, tests/ssl-opt.sh
This is a backport of PR #2975, 'Add zlib tests and fix runtime bug' to the `baremetal` branch. This is necessary as whilst the fix was already backported to `mbedtls2.16`, which will be merged into `baremetal`, that backport only included the extra tests, not the actual fix as the bug wasn't present in `mbedtls-2.16`.
For whatever reason the bug *is* present in `baremetal`, so this second backport of PR #2975 includes the fix as well as the tests.
Once that's merged, `mbedtls-2.16` can be merged into `baremetal`. Unfortunately it can't be merged before, as including the tests (already present on `mbedtls-2.16` branch) before the fix will just cause the CI to fail.
This PR fixes a gap in our testing: we didn't test any build with zlib (for TLS record compression) enabled. This is a …
=> Backport baremetal: Add zlib tests and fix runtime bug

tests/suites/test_suite_ssl.data, tests/suites/test_suite_ssl.function
This PR contains changes related with n/n-1 splitting of an app data in test suite. Test suites counts the sent fragments and in case of splitting their number is twice bigger. The fragments counting has been shifted from writing section in to reading. It was required because the splitting is realized during one call of the `mbedtls_ssl_write` function and the fragmentation could be omitted by test suites 
**READY**
NO
=> App data with 1/n-1 splitting in test suite

ChangeLog, library/ssl_msg.c, library/ssl_tls.c, tests/scripts/all.sh
Fix compilation failure when both MBEDTLS_SSL_HW_RECORD_ACCEL and MBEDTLS_SSL_PROTO_DTLS are enabled. The problem was caused because a fragment of code that is conditionally compiled into a function in ssl_tls.c depended on a variable `ret` that was not declared.
The problem was fixed by simply declaring the variable `ret` when MBEDTLS_SSL_HW_RECORD_ACCEL is defined.
This change also adds a build test to all.sh.
**READY**
Yes 
- mbedtls-2.16 https://github.com/ARMmbed/mbedtls/pull/2439
- mbedtls-2.7 https://github.com/ARMmbed/mbedtls/pull/2440
NO
=> Fix compilation failure when MBEDTLS_SSL_HW_RECORD_ACCEL is enabled

ChangeLog, library/ssl_tls.c, tests/scripts/all.sh
This is a backport of https://github.com/ARMmbed/mbedtls/pull/2262, please refer to that PR description for details.
**Note:** due to important changes in development in the meantime (most notably splitting `ssl_msg.c` out of `ssl_tls.c`, and other refactorings), the backport is quite different from the original PR. The ChangeLog entry and new component in `all.sh` are the same though.
**READY**
=> Backport 2.16: Fix compilation failure when MBEDTLS_SSL_HW_RECORD_ACCEL is enabled

ChangeLog, library/ssl_tls.c, tests/scripts/all.sh
This is a backport of https://github.com/ARMmbed/mbedtls/pull/2262, please refer to that PR description for details.
**Note:** due to important changes in development in the meantime (most notably splitting `ssl_msg.c` out of `ssl_tls.c`, and other refactorings), the backport is quite different from the original PR. The ChangeLog entry and new component in `all.sh` are the same though. (The changes in the library are closer to the 2.16 backport than to the PR against development, but still different too.)
**READY**
=> Backport 2.7: Fix compilation failure when MBEDTLS_SSL_HW_RECORD_ACCEL is enabled

scripts/output_env.sh, tests/scripts/all.sh, tests/scripts/check-python-files.sh
Pylint when installed as a distro package can be installed as `pylint3`, whilst as a PEP egg or directly from the `pylint` website, it can be installed as `pylint`.
This pull request changes the scripts to first use `pylint` if installed, and optionally look for `pylint3` if not installed. This is to allow a preference for the PEP version over the distro version, assuming the PEP one is more likely to be the correct one.
I'll do the back ports once this PR has been reviewed and approved, and thereby approving the approach.
**READY**
Yes
Which branch?
`mbedtls-2.16`and `baremetal`
These changes are necessary to use the most recent CI Dockerfiles. 
NO
=> Change the use of pylint to optionally use pylint3

scripts/output_env.sh, tests/scripts/all.sh, tests/scripts/check-python-files.sh
This is a backport of PR #3100 to `mbedtls-2.16`.
Pylint when installed as a distro package can be installed as `pylint3`, whilst as a PEP egg or directly from the `pylint` website, it can be installed as `pylint`.
This pull request changes the scripts to first use `pylint` if installed, and optionally look for `pylint3` if not installed. This is to allow a preference for the PEP version over the distro version, assuming the PEP one is more likely to be the correct one.
I'll do the back ports once this PR has been reviewed and approved, and thereby approving the approach.
**READY**
NO
=> Backport 2.16: Change the use of pylint to optionally use pylint3

library/ssl_srv.c
This PR fixes #2444.
Although the 'flags' variable is not checked or used after a call to mbedtls_ssl_check_cert_usage, it might be in the future. With this fix, after each iteration, the flags will apply only to the most recent certificate, not to any of the previous ones checked. This fix also stops any reads and writes via a '|=' from/to an uninitialized variable happening.
=> ssl_srv.c: initialize flags on each iteration of the loop

include/mbedtls/ssl.h
Add a description of MBEDTLS_ERR_SSL_PEER_CLOSE_NOTIFY to the documentation, as suggested by hanno-arm.
This fixes https://github.com/ARMmbed/mbedtls/issues/2173.
=> ssl - improve documentation on mbedtls_ssl_read and PEER_CLOSE_NOTIFY

README.md
Update `README.md` to mention Mbed Crypto and the PSA crypto API.
This is a companion to https://github.com/ARMmbed/mbedtls/pull/3085 which should be merged soon afterwards. I made it a separate pull request to reduce the review volume, group the commits in the history, and separate the CI feedback cycles.
=> Merge documentation from Mbed Crypto

tests/ssl-opt.sh
Remove "Default" from some test names:
- "Default" should only be used for tests that actually use the defaults (ie, not passing options on the command line, except maybe debug/dtls)
- All tests in the "Encrypt then MAC" group should start with that string as a common prefix
**READY**
Yes - keeping test scripts in sync between branches makes other backporting work easier
- 2.16 #3114 
- 2.7 #3115
=> Improve some test names in ssl-opt.sh

tests/ssl-opt.sh
This is the 2.16 backport of #3113
=> [Backport 2.16] Improve some test names in ssl-opt.sh

tests/ssl-opt.sh
This is the 2.7 backport of #3113
=> [Backport 2.7] Improve some test names in ssl-opt.sh

scripts/assemble_changelog.py
In `assemble_changelog.py`, sort changelog entries by their merge date. More precisely: look for the git commit where the entry file was created, and look where this commit was merged into the current branch. List older merges first. List never-merged commits in date order after all the merged ones. List never-committed files in file timestamp order after all the committed ones.
~Follow-up of https://github.com/ARMmbed/mbedtls/pull/3126, the first new commit is "Factor out list_files_to_merge".~ (#3126 has been merged.)
=> Sort changelog entries by their merge date

scripts/assemble_changelog.py
Follow-up to https://github.com/ARMmbed/mbedtls/pull/3128
=> assemble_changelog.py: Reformatting to pacify pylint

library/Makefile
This change was first introduced in 8af3923 - see this commit for more background.
After the removal of crypto directory, there are no targets that require a crypto library with the directory prefix, so there's also no need for the priority dependency to be declared. This PR removes it.
This PR resolves https://github.com/ARMmbed/mbedtls/issues/3109.
=> makefile: remove unneeded priority dependency from library makefile

programs/pkey/ecdsa.c
[edited by mpg] Backports:
- 2.16 #3106
- 2.7 #3107
=> Fix debug message by using the correct function name called

programs/pkey/ecdsa.c
This is the 2.16 backport of #3013
=> [backport 2.16] Fix function name in error message

programs/pkey/ecdsa.c
This is the 2.7 backport of #3013
=> [backport 2.7] Fix function name in error message

tests/suites/host_test.function
Fix an intermittent crash when running test suites in non-verbose
mode (i.e. with -v off) and with the outcome file enabled. The
array unmet_dependencies was only filled in verbose mode, but was used
in write_outcome_result regardless.
Since unmet_dependencies only ever contains strings that are integers
written out in decimal, store the integer instead. Do this
unconditionally since it doesn't cost any extra memory.
It would be better to record the dependency names, both in the verbose
output and in the outcome file. But the dependency names are not
currently available at runtime, and adding them would be beyond the scope of this PR.
Backports: not needed since the outcome file only exists on development. However I think we should make a partial 2.16 backport to change …
=> Fix intermittent crash in test suites with outcome file enabled

tests/suites/host_test.function
Since unmet_dependencies only ever contains strings that are integers
written out in decimal, store the integer instead. Do this
unconditionally since it doesn't cost any extra memory.
This commit saves a little memory and more importantly avoids a gotcha
with uninitialized pointers which caused a bug on development (the
array was only initialized in verbose mode).
Partial backport of https://github.com/ARMmbed/mbedtls/pull/3140: there's no bug in 2.16 but there is the fragile bit of code and small inefficiency.
=> [2.16 only] Since unmet_dependencies stores integers, represent them as int

doxygen/mbedtls.doxyfile
Previously, doxygen was unable to effectively use preprocessing to determine which parts of code should be documented. This was due to its inability to include headers during preprocessing, which was discovered by running it in preprocessing debug mode:
doxygen -d preprocessor mbedls.doxyfile 
An example of failure: `#include mbedtls/config.h: not found! skipping... `
With the following fix includes are properly preprocessed and the documentation is considerably larger.
The only downside I noticed so far are bigger include graphs, like so:
=> Add an include path to the doxyfile to fix preprocessing for docs

include/mbedtls/check_config.h, library/x509.c
This pull request adds additional sanity checks into `check_config.h` to ensure:
* if test certificates are included (`MBEDTLS_CERTS_C`) there must be also be public key algorithms (`MBEDTLS_PK_C`), as the certificates will either be signed by RSA or ECDSA, and therefore need to be part of the library.
* if any of the TLS protocols are defined (`MBEDTLS_SSL_PROTO_xxx`) then a key exchange method must also be defined (`MBEDTLS_KEY_EXCHANGE_xxx`).
Anyone who knows the library will probably not make these mistakes or will quickly diagnose and fix them, but it is possible to build combinations of both configurations (by only building the library, not the examples), and therefore users may not realise immediately that they've made a configuration mistake.
**READY**
Yes - it's really a fix, so …
=> Add additional sanity checks to check_config.h

include/mbedtls/check_config.h, library/x509.c
This is a backport of PR #2574 to the `mbedtls-2.16` branch.
This pull request adds additional sanity checks into `check_config.h` to ensure:
* if test certificates are included (`MBEDTLS_CERTS_C`) there must be also be public key algorithms (`MBEDTLS_PK_C`), as the certificates will either be signed by RSA or ECDSA, and therefore need to be part of the library.
* if any of the TLS protocols are defined (`MBEDTLS_SSL_PROTO_xxx`) then a key exchange method must also be defined (`MBEDTLS_KEY_EXCHANGE_xxx`).
Anyone who knows the library will probably not make these mistakes or will quickly diagnose and fix them, but it is possible to build (as in compile and link) combinations of both configurations (by only building the library, not the examples), and therefore users may not realise …
=> Backport 2.16: Add additional sanity checks to check_config.h

include/mbedtls/check_config.h, library/x509.c
This is a backport of PR #2574 to the `mbedtls-2.7` branch.
This pull request adds additional sanity checks into `check_config.h` to ensure:
* if test certificates are included (`MBEDTLS_CERTS_C`) there must be also be public key algorithms (`MBEDTLS_PK_C`), as the certificates will either be signed by RSA or ECDSA, and therefore need to be part of the library.
* if any of the TLS protocols are defined (`MBEDTLS_SSL_PROTO_xxx`) then a key exchange method must also be defined (`MBEDTLS_KEY_EXCHANGE_xxx`).
Anyone who knows the library will probably not make these mistakes or will quickly diagnose and fix them, but it is possible to build (as in compile and link) combinations of both configurations (by only building the library, not the examples), and therefore users may not realise …
=> Backport 2.7: Add additional sanity checks to check_config.h

tests/suites/test_suite_asn1write.function
This PR fixes #2782 , spotted by tmarti2.
This issue does not exist on development, it has been fixed in the so called meantime.
=> [mbedtls-2.16] Typo fix in test_suite_asn1write.function

.github/issue_template.md
Update issue template to direct questions to the TrustedFirmware.org
mailing list instead of using the GitHub issue tracker.
**READY**
Yes  
2.7/2.16
No
=> Direct questions to mailing list in issue template

tests/suites/main_test.function
Warn about a gotcha that caused a bug in development.
Even in non-verbose mode, unmet_dep_count can be 1. In this case
ensure that unmet_dependencies[0] is initialized (to NULL).
Partial backport of https://github.com/ARMmbed/mbedtls/pull/3140: there's no bug in 2.7 but there is the fragile bit of code.
=> [2.7 only] Note that unmet_dependencies is only filled in verbose mode

ChangeLog, library/ssl_msg.c, programs/test/udp_proxy.c, tests/ssl-opt.sh
This PR fixes several issues related to server-side handling of client re-connecting with the same UDP quartet while we already have an active established connection for that same UDP quartet (our `config.h` option `MBEDTLS_SSL_CLIENT_PORT_REUSE`, implementing [RFC 6347 Section 4.2.8](https://tools.ietf.org/html/rfc6347#section-4.2.8)):
1. We did not actually establish client reachability by verifying the ClientHello cookie before destroying the existing association, which violates the RFC and opens the door to a DoS - see the commit message for details.
2. An indirect side-effect of the previous point is we had a race condition in our tests for that feature in `ssl-opt.sh`, causing one of them to fail quite frequently in the CI (or indeed locally) - see below for details.
3. The timeout …
=> Fix issues in handling of client reconnecting from the same port

library/ssl_tls.c, programs/test/udp_proxy.c, tests/ssl-opt.sh
This is the 2.16 partial backport of #3132: since the bug fixed in the original PR isn't present in the 2.16 branch, this PR only contains improvements to testing and debugging.
=> [Backport 2.16] Improve testing of DTLS client hard reconnect

ChangeLog, library/ssl_tls.c, programs/test/udp_proxy.c, tests/ssl-opt.sh
This is the 2.16 partial backport of #3132: since the bug fixed in the original PR isn't present in the 2.16 branch, this PR only contains improvements to testing and debugging.
The new test uncovered a bug in 2.7 (that was fix unknowingly in 2.13), which this PR also fixes.
=> [backport 2.7] Fix issues in handling of client reconnecting from the same port

ChangeLog.d/00README.md, ChangeLog.d/README, scripts/assemble_changelog.py
Instead of working with Markdown format, keep the classic Mbed TLS ChangeLog format, with the classic category names. Keep the classic file name as well. This way there's no risk of breaking third-party scripts that may copy or even parse the changelog file.
I also added some guidance on writing a changelog entry.
=> Switch to the classic Mbed TLS ChangeLog format

ChangeLog, library/ssl_cli.c, library/ssl_srv.c
The algorithm in [RFC4279](https://tools.ietf.org/html/rfc4279#section-3) requires 16-bit value, and nothing more than 16 bits could be obtained from combining two 8-bit values.
Therefore it would be appropriate to use `uint16_t` instead of _possibly_ too wide `size_t`.
Then the range check (`n > 65535`) could go away together with the warning.
The same type change applies to `ssl_cli.c`, even though the mentioned check was in `ssl_srv.c` only.
**READY**
NO  
Which branch?
Development
NO
=> Fix warning in PSK parsing

include/mbedtls/config.h
Update references from drafts to RFCs in config.h - the remaining reference to a draft (DTLS connection ID) is because it's indeed not and RFC yet.
**READY**
NO  - minor documentation improvement in a file that's unlikely to change in LTS branches.
=> Update references from drafts to RFCs in config.h

library/hkdf.c
There's no behavior change. This just makes the code more robust and removes a potential false positive in static analysis.
Since there's no bug and this change increases the code size by a few bytes, I don't think this should be backported.
Originally reported in https://github.com/ARMmbed/mbedtls/pull/2942.
=> hkdf_expand: explicitly initialize t

Makefile
Adding .function was necessary, as otherwise ctags would have no idea what to do with those files.
Adding .h may not be necessary, as by default ctags considers them C++ which is probably good enough, but since we're tuning the mapping anyway...
**READY**
Yes - developer comfort should be available in all branches :)
=> Improve ctags invocation in Makefile

Makefile
This is the 2.16 backport of #3156.
=> [backport 2.16] Improve ctags invocation in Makefile

Makefile
This is the 2.7 backport of #3156.
=> [backport 2.7] Improve ctags invocation in Makefile

tests/scripts/basic-build-test.sh
* Fix #3178: make basic-build-test.sh exit with a failure status if some test cases fail
* Minor log readability improvements
* Fix #3179: enable SSL3 in basic-build-test.sh
Needs partial backports. This PR is release-critical, but the backports aren't (we can check the logs manually to verify that there are no failures).
Alternative that does change the full config: https://github.com/ARMmbed/mbedtls/pull/3180
=> Fix failure detection and failures in basic-build-test.sh with SSL3 in basic-build-test

include/mbedtls/ssl.h, include/mbedtls/ssl_internal.h, library/ssl_tls.c
In Mbed TLS, there are two types of PSKs:
* Configured, aka static PSK (`ssl->conf->psk...`): Essentially used client-side although nothing prevents the server from using it. It is set by `mbedtls_ssl_conf_psk()`
* Handshake PSK, aka dynamic PSK (`ssl->handshake->psk...`): Server-side only. That PSK is bound to the handshake hence doesn't survive renegotiation or session reset.
It is set by `mbedtls_ssl_set_hs_psk()`.
* Orthogonally, opaque PSKs used in PSA can be of any of the two aforementioned types (static or dynamic)
Since there are several types of PSKs, they are subject to a priority order. Dynamic PSKs precede static ones as showed in `mbedtls_ssl_psk_derive_premaster()` and `ssl_compute_master()`.
All this makes PSK management difficult to understand and prone to error.
The goal …
=> Clarify and simplify PSK

tests/suites/host_test.function
Fix a potential buffer overflow in the code executing the unit tests. When executing a test case, its dependencies are checked and the identifiers of unmet dependencies are stored in a statically allocated array. The PR adds a check to ensure that we don't overrun the array. It adds also indications in test reports when the array is too small to store all the unmet dependencies of a test case. 
READY
Yes
2.16 and 2.7
I have tested the changes in this PR by reducing the size of the unmet_dependencies[] array to two and running the test_suite_psa_crypto_se_driver_hal test suite.
=> Unmet dependencies buffer overflow fix

tests/suites/helpers.function, tests/suites/main_test.function
Fix a potential buffer overflow in the code executing the unit tests. When executing a test case, its dependencies are checked and the identifiers of unmet dependencies are stored in a statically allocated array. The PR adds a check to ensure that we don't overrun the array. It adds also indications in test reports when the array is too small to store all the unmet dependencies of a test case.
This is a partial backport of #3155: there is no outcome file support in 2.7.
READY
I have tested the changes in this PR by reducing the size of the unmet_dependencies[] array to one and running the x509parse test suite with PEM disabled (to get more than one unmet dependency).
=> [backport 2.7] Unmet dependencies buffer overflow fix

tests/suites/helpers.function, tests/suites/host_test.function
Fix a potential buffer overflow in the code executing the unit tests. When executing a test case, its dependencies are checked and the identifiers of unmet dependencies are stored in a statically allocated array. The PR adds a check to ensure that we don't overrun the array. It adds also indications in test reports when the array is too small to store all the unmet dependencies of a test case.
This is a partial backport of #3155: there is no outcome file support in 2.16.
READY
I have tested the changes in this PR by reducing the size of the unmet_dependencies[] array to one and running the x509parse test suite with PEM disabled (to get more than one unmet dependency).
=> [backport 2.16] Unmet dependencies buffer overflow fix

.pylintrc, scripts/abi_check.py, scripts/config.py, tests/scripts/all.sh, tests/scripts/check-files.py, tests/scripts/check-python-files.sh, tests/scripts/check-test-cases.py, tests/scripts/generate_test_code.py, tests/scripts/mbedtls_test.py, tests/scripts/test_config_script.py, tests/scripts/test_generate_test_code.py, tests/scripts/test_psa_constant_names.py
Until now we've only sanitized our Python scripts and set up our `.pylintrc` for the version of Pylint in Ubuntu 16.04 (Pylint 1.5.2). This pull request sanitizes our Python scripts for the latest version of Pylint. Fix #3087
I've tested locally that `check-python-files.sh` passes with Pylint 1.5.2, 1.8.3 and 2.4.4.
This pull request makes two other changes:
* In `all.sh`, run `check_python_files` systematically. The rationale for making it optional was that pylint wasn't available on our CI, but these days, it is.
* In `check-python-files.sh`, don't run `pylint` without checking that it isn't for Python 2. Fix #3111
Backports: 2.16 #3184 - 2.7 (partial) #3185
=> Pass Pylint up to 2.4

.pylintrc, scripts/abi_check.py, tests/scripts/all.sh, tests/scripts/check-files.py, tests/scripts/check-python-files.sh, tests/scripts/generate_test_code.py, tests/scripts/mbedtls_test.py, tests/scripts/test_generate_test_code.py
Backport of #3118, skipping files that don't exist in 2.16.
I chose to include the changes to `mbedtls_test.py` which effectively break compatibility with Python 2. This is debatable since we weren't clearly saying whether running that script under Python 2 was officially supported. However, at the time Mbed TLS 2.16 came out, Mbed OS tools including Greentea required Python 3, and `mbedtls_test.py` uses Greentea, so `mbedtls_test.py` in 2.16 should not have been used with Python 2 anymore.
=> Backport 2.16: Pass Pylint up to 2.4

scripts/abi_check.py, tests/scripts/check-files.py
This is a very partial backport of #3118. We don't run pylint on CI for 2.7 and I don't propose to start doing so. Furthermore we don't have many Python scripts in 2.7. This PR only contains the changes to the two Python scripts that have been backported to 2.7, to keep them close to 2.16/development for easier backporting.
I deliberately do not modify `mbedtls_test.py` in a way that breaks compatibility with Python 2 because this is a script that users of the library might be using, and at the time 2.7 came out, Python 2 was still required for Mbed OS.
=> Backport 2.7: Pass Pylint up to 2.4

programs/test/benchmark.c
When building with MBEDTLS_MEMORY_DEBUG enabled, and running the ecdh part, the benchmark program would start writing a very large number of space characters on stdout, and would have to be killed because it never seemed to terminate.
This was due to an integer overflow in computing how many space to leave after the title in order to get memory measurements aligned, which resulted in close to SIZE_MAX spaces being printed.
**READY**
(No ChangeLog entry as the bug is only in one of the example programs in a non-default config.)
Yes - I'll create backport once this PR has receive some review.
I used the following script:
```sh
#!/bin/sh
scripts/config.py set MBEDTLS_PLATFORM_MEMORY
scripts/config.py set MBEDTLS_MEMORY_BUFFER_ALLOC_C
scripts/config.py set MBEDTLS_MEMORY_DEBUG …
```
=> Fix arithmetic overflow in benchmark

programs/test/benchmark.c
This is the 2.16 backport of #3177.
=> [backport 2.16] Fix arithmetic overflow in benchmark

programs/test/benchmark.c
This is the 2.7 backport of #3177
=> [backport 2.7] Fix arithmetic overflow in benchmark 

tests/suites/host_test.function, tests/suites/main_test.function
This is the 2.16 backport of #2840
=> [Backport 2.16] Add lower bound check to function index lookup

tests/suites/host_test.function, tests/suites/main_test.function
The common test suites code looks up the test function in an array via an index obtained from the input data. The index's upper bound has already been checked, but as a signed type it could have been negative, which was not tested for.
The PR adds the missing lower bound check.
[edited by mpg] Backport to 2.16: #3207 - no backport needed for 2.7 as the test code is different so this is not applicable.
=> Add lower bound check to function index lookup

programs/ssl/ssl_client2.c, programs/ssl/ssl_server2.c, tests/ssl-opt.sh
This PR adds in the ssl_server2 and ssl_client2 programs the ability to save a serialized context to a file as base64 code. 
**READY**
NO
=> Saving the serialized context to a file

tests/suites/host_test.function, tests/suites/main_test.function
Straightforward backport of https://github.com/ARMmbed/mbedtls/pull/2840
=> Backport 2.16: Make negative function_id value impossible in test suites

include/mbedtls/error.h, library/error.c, scripts/data_files/error.fmt, scripts/generate_errors.pl
Problem
-------
```mbedtls_strerror``` is a utility function which converts an mbedTLS error code into a human readable string. It requires the caller to allocate a buffer every time an error code needs to be converted to a string. It is an overkill and a waste of RAM for resource constrained microcontrollers - where the most common use case is to use these strings for logging.
Solution
--------
The proposed commit adds two functions:
```c
const char * mbedtls_high_level_strerr( int error_code );
const char * mbedtls_low_level_strerr( int error_code );
```
The above two functions convert the high level and low level parts of an mbedTLS error code to human readable strings. They return a const pointer to an unmodifiable string which is not supposed to be modified by the caller and only to …
=> Add support for const error description strings

library/md.c
Remove duplication and use multiple case labels for the action.
Resolves #3202
**READY**
NO  
Which branch?
development
NO
=> Fix "same actions in two cases of a switch statement" warning

ChangeLog.d/00README.md, scripts/assemble_changelog.py
Combined backport of https://github.com/ARMmbed/mbed-crypto/pull/300, https://github.com/ARMmbed/mbedtls/pull/3128, https://github.com/ARMmbed/mbedtls/pull/3133 and https://github.com/ARMmbed/mbedtls/pull/3135. Because there were some design changes along the way, I don't see any value in backporting the history, so I'm just backporting the two new files as they are now.
=> Backport 2.16: assemble_changelog.py

ChangeLog.d/00README.md, scripts/assemble_changelog.py
Combined backport of https://github.com/ARMmbed/mbed-crypto/pull/300, https://github.com/ARMmbed/mbedtls/pull/3128, https://github.com/ARMmbed/mbedtls/pull/3133 and https://github.com/ARMmbed/mbedtls/pull/3135. Because there were some design changes along the way, I don't see any value in backporting the history, so I'm just backporting the two new files as they are now.
=> Backport 2.7: assemble_changelog.py

library/ssl_srv.c
Resolve #2916 - remove condition in the middle, because it is enough to do the strongest check only.
**READY**
NO
Which branch?
development
NO
=> Simplify checks in ssl_write_certificate_request

ChangeLog.d/fix-ecp_double_add_mxz.txt, library/ecp.c
ecp_double_add_mxz wrongly does an MPI addition followed by a call to
MOD_MUL instead of MOD_ADD. This is more visible since the
mbedtls_mpi_xxx_mod functions have been added in commit 3b3b34f60800
("Replace some macros by functions").
Fix that by using mbedtls_mpi_add_mod instead. The testsuite still
passes after that change.
READY
I am not sure it requires backporting, I don't think it as any real impact.
NO
=> Fix wrong modulo call in ecp_double_add_mxz

ChangeLog.d/error_const.txt, ChangeLog.d/max_pathlen.txt, ChangeLog.d/md_switch.txt, ChangeLog.d/ssl_context_info.txt, ChangeLog.d/ssl_write_certificate_request.txt
Some pull requests merged since the 2.22.0 release were missing changelog entries.
* :heavy_plus_sign: #3127: new utility program. Entry in this PR.
* :heavy_plus_sign: #3192: product bug fix. Entry in this PR.
* :heavy_minus_sign: #3155: bug fix in tests. No entry needed.
* :heavy_minus_sign: #3118: maintenance improvement. No entry needed.
* :heavy_minus_sign: #3162: maintenance improvement. No entry needed.
* :heavy_minus_sign: #3177: bug fix in sample program in an exotic configuration. No entry needed.
* :heavy_minus_sign: #3120: maintenance improvement. No entry needed.
* :heavy_minus_sign: #2840: bug fix in tests. No entry needed.
* :heavy_minus_sign: #3194: test program improvement. No entry needed.
* :heavy_minus_sign: #3210: maintenance fix. No entry needed.
* :heavy_plus_sign: …
=> Add missing changelog entries for PRs since 2.22.0

ChangeLog.d/max_pathlen.txt
Backport of https://github.com/ARMmbed/mbedtls/pull/3216. In 2.16 there has only been one PR that's missing a changelog entry, which is a backport of a PR that was missing a changelog entry in development too.
=> 2.16 only: Add missing changelog entry for PRs since 2.16.6

ChangeLog.d/max_pathlen.txt
Backport of https://github.com/ARMmbed/mbedtls/pull/3216. In 2.7 there has only been one PR that's missing a changelog entry, which is a backport of a PR that was missing a changelog entry in development too.
=> 2.7 only: Add missing changelog entry for PRs since 2.7.15

library/ssl_tls.c
Resolve #3182 - the variable was already initialized to zero.
**READY**
NO  
Which branch?
development
NO
=> Avoid re-assigning zero to `ret` variable.

library/error.c, scripts/data_files/error.fmt, scripts/generate_errors.pl
The definition of the newly added functions ```mbedtls_high_level_strerr``` and ```mbedtls_low_level_strerr``` were of the form:
```c
const char * mbedtls_high_level_strerr( int error_code )
{
const char * error_description = NULL;
switch( error_code )
{
case -(MBEDTLS_ERR_X509_FILE_IO_ERROR):
error_description = "X509 - Read/write of file failed";
break;
default:
break;
}
return error_description;
}
```
As suggested on this PR: https://github.com/ARMmbed/mbedtls/pull/3176, we can remove the use of ```error_description``` variable:
```c
const char * mbedtls_high_level_strerr( int error_code )
{
switch( error_code )
{
case -(MBEDTLS_ERR_X509_FILE_IO_ERROR):
return "X509 - Read/write of file failed";
default:
break;
}
return NULL;
}
```
This PR implements the suggestion.
**READY**
NO …
=> Remove error_description variable from strerr functions

.travis.yml, scripts/windows_msbuild.bat, tests/scripts/all.sh, tests/scripts/check-files.py
Change what we run on Travis to get better coverage for roughly as much processing power.
The goal of this pull request is to improve the chances that if something breaks on Jenkins, it also breaks on Travis. The advantage of Travis is that its logs are public.
This pull request is about cheap wins. Putting a lot of effort into quantitizing the maximization of coverage is out of scope. Installing new tools in the test environment is out of scope if it's more complicated than declaring a package to install.
We can't run the whole CI on Travis because it would take more processing power than we're willing to use on a free plan and because the full CI uses tools that are not present on Travis. For reference, our current Travis matrix runs two jobs, gcc and clang, which take about 24 min and …
=> Rationalize Travis builds

.travis.yml, scripts/windows_msbuild.bat, tests/scripts/all.sh, tests/scripts/check-files.py
Mostly straightforward backport of #3218. Differences:
* There's no `psa_constant_names` in 2.16, and so no need for Python on Windows.
First backport #2821 because it's easier to keep all LTS branches in synch.
=> Backport 2.16: Rationalize Travis builds

.travis.yml, scripts/windows_msbuild.bat, tests/scripts/all.sh, tests/scripts/check-files.py
Mostly straightforward backport of #3218. Differences:
* There's no `psa_constant_names` in 2.7, and so no need for Python on Windows.
* In `all.sh`, `build_arm_none_eabi_gcc_arm5vte` didn't exist in 2.7, so I added it.
Like in the 2.16 backport (#3247), first backport (the applicable part of) #2821 because it's easier to keep all LTS branches in synch.
=> Backport 2.7: Rationalize Travis builds

library/net_sockets.c
getaddrinfo() is not available on win2k. By including wspiapi.h (if _WIN32_WINNT is defined as value < 0x0501) then a compatibility layer will be used when running on win2k. For more details, refer to [Microsoft docs for getaddrinfo()](https://docs.microsoft.com/en-us/windows/win32/api/ws2tcpip/nf-ws2tcpip-getaddrinfo).
READY
NO
NO
Define _WIN32_WINNT as 0x0500, build, run on win2k VM. If you are cross compiling from linux to windows here's a sequence of commands to do this:
sudo apt-get install mingw-w64
CC=i686-w64-mingw32-gcc AR=i686-w64-mingw32-ar CFLAGS="-D_WIN32_WINNT=0x0500" LDFLAGS="-lws2_32" make
=> add support for win2k

CONTRIBUTING.md
Backport of https://github.com/ARMmbed/mbedtls/pull/3306.
=> Backport 2.7: Update link in contributing guide

CONTRIBUTING.md
Backport of https://github.com/ARMmbed/mbedtls/pull/3306.
=> Backport 2.16: Update link in contributing guide

CONTRIBUTING.md
The link pointed to the website, this information is out of date, the
correct place to start discussions is the mailing list.
=> Update link in contributing guide

ChangeLog.d/fix-masked-hw-record-init-error.txt, library/ssl_tls.c
Fix issue with variable shadowing.
Signed-off-by: sander-visser <github@visser.se>
**READY**
NO  
YES | NO
=> Expose SSL HW record acceleration error.

library/ssl_tls.c
Signed-off-by: sander-visser <github@visser.se>
Added variable initialization for maintainability. Reported as false positive by cpp-check 1.89
**READY**
No
NO
=> Add variable initialization to large SSL TLS function

ChangeLog.d/fix-null-ptr-deref-in-mbedtls_ssl_free.txt, library/ssl_tls.c
Signed-off-by: sander-visser <github@visser.se>
**READY**
NO
NO
=> Scope reduction to enable NULL check to protect dereferencing.

programs/test/benchmark.c
A typo in program benchmark. AES-XTS test should be called aes_xts not aes_ctx
**READY**
=> Fix typo in program benchmark.

ChangeLog.d/inline-mbedtls_gcc_group_to_psa.txt, include/psa/crypto_extra.h, library/psa_crypto.c
On dual world platforms, we want to run the PK module (pk.c) on the NS
side so TLS can use PSA APIs via the PK interface. PK currently has a
hard dependency on mbedtls_ecc_group_to_psa() which is declared in
crypto_extra.h, but only defined in psa_crypto.c, which is only built
for the S side.
Without this change, dual world platforms get error messages like the
following.
[Error] @0,0: L6218E: Undefined symbol mbedtls_ecc_group_to_psa (referred from BUILD/LPC55S69_NS/ARM/mbed-os/features/mbedtls/mbed-crypto/src/pk.o)
Make mbedtls_ecc_group_to_psa() inline within crypto_extra.h so that it
is available to both NS and S world code.
Fixes #3300
Signed-off-by: Darryl Green <darryl.green@arm.com>
Signed-off-by: Jaeden Amero <jaeden.amero@arm.com>
**READY**
NO  - PSA related change, and no LTS …
=> psa: Define mbedtls_ecc_group_to_psa() inline

CONTRIBUTING.md
Fix the link from 'adding a changelog' in the Contributing document so that it points to the readme on creating an in progress changelog, rather than the changelog itself.
READY
[2.7](https://github.com/ARMmbed/mbedtls/pull/3361)
[2.16](https://github.com/ARMmbed/mbedtls/pull/3362)
=> Fix contributing link to changelog howto

CONTRIBUTING.md
Fix the link from 'adding a changelog' in the Contributing document so that it points to the readme on creating an in progress changelog, rather than the changelog itself.
Status
READY
Backport of https://github.com/ARMmbed/mbedtls/pull/3341
=> Backport 2.16: Fix contributing link to changelog howto

CONTRIBUTING.md
Fix the link from 'adding a changelog' in the Contributing document so that it points to the readme on creating an in progress changelog, rather than the changelog itself.
READY
Backport of https://github.com/ARMmbed/mbedtls/pull/3341
=> Backport 2.7: Fix contributing link to changelog howto

scripts/output_env.sh
Add output of make, cmake and python3 versions to output_env.sh.
That way we can see their versions in the CI.
Fix #3298.
READY
Yes, 2.7 and 2.16
=> Add output of make, cmake and python3 versions

scripts/output_env.sh
=> Backport 2.16: Add output of make, cmake and python3 versions

ChangeLog.d/error-asn1.txt, library/error.c, scripts/generate_errors.pl
Fix #3328. Add a check in `generate_errors.pl` that serves as a non-regression test.
=> Include asn1.h in error.c

include/psa/crypto_sizes.h, include/psa/crypto_values.h
* Fix some copypasta (PSA Crypto API bug: private link: https://github.com/ARMmbed/psa-crypto-api/issues/404).
* Both “asymmetric signature/encryption” and “public key signature/encryption” were used indifferently. Prefer “asymmetric”, but mention “public-key” as a synonym.
=> PSA: Fix copypasta and align terminology about asymmetric encryption

tests/scripts/basic-build-test.sh
This is a partial backport of https://github.com/ARMmbed/mbedtls/pull/3181 which we merged before it was backported because it was holding up the release on development only.
* Fix #3178: make basic-build-test.sh exit with a failure status if some test cases fail
* Minor log readability improvements
* Added: create a seedfile explicitly, to align with development.
* Omitted: config changes.
CI run: https://jenkins-internal.mbed.com/job/mbedtls-release-new/733/ → PASS
=> Backport 2.16: Fix failure detection in basic-build-test.sh

tests/scripts/basic-build-test.sh
This is a partial backport of #3181. Same patch as the 2.16 backport in #3375.
CI run: https://jenkins-internal.mbed.com/job/mbedtls-release-new/734/ → PASS
=> Backport 2.7: Fix failure detection in basic-build-test.sh

programs/fuzz/common.c, programs/fuzz/fuzz_client.c, programs/fuzz/fuzz_dtlsclient.c, programs/fuzz/fuzz_dtlsserver.c, programs/fuzz/fuzz_server.c, tests/scripts/all.sh, tests/suites/test_suite_rsa.function, tests/suites/test_suite_ssl.function
People who prefer to rely on HMAC_DRBG (for example because they use it for deterministic ECDSA and don't want a second DRBG for code size reasons) should be able to build and run the tests suites without CTR_DRBG.
Ideally we should make sure the level of testing (SSL) is the same regardless of which DRBG modules is enabled, but that's a more significant piece of work. For now, just ensure everything builds and `make test` passes.
Question to reviewers: do you think this deserves a ChangeLog entry? I'm inclined to think it's not significant enough, but if you think otherwise I'll add one.
**READY**
Yes
NO
=> Fix undeclared dependencies on CTR_DRBG (and add test)

tests/scripts/all.sh, tests/suites/test_suite_rsa.function
This is the 2.16 backport of #3378. Differences from the main PR:
- first commit (test suites): the SSL test suite doesn't have the new stuff testing full handshakes, so nothing to change here
- second commit (programs/fuzz): skipped entirely as there is no `programs/fuzz` here
- third upstream commit (all.sh): apart form context conflicts, used `config.pl` instead of `config.py` which is not in 2.16.
=> [Backport 2.16] Fix undeclared dependencies on CTR_DRBG (and add test)

tests/scripts/all.sh, tests/suites/test_suite_rsa.function
This is the 2.7 backport of #3378, actually based on the 2.16 backport #3384 - it has the same diff except for a difference of context in `all.sh`.
=> [Backport 2.7] Fix undeclared dependencies on CTR_DRBG (and add test)

tests/scripts/all.sh
This is the 2.16 backport of #3400. Compared to the original, only the test is backported, as the issue fixed was the PSA test suite, and `config.py` is changed to `config.pl`.
=> [Backport 2.16] Fix undeclared dependencies on HMAC_DRBG

tests/scripts/all.sh
This is the 2.7 backport of #3400. It is identical to the 2.16 backport in #3401.
=> [Backport 2.7] Fix undeclared dependencies on HMAC_DRBG

Makefile, tests/scripts/basic-build-test.sh
Enable branch coverage output in basic_build_test.sh. This
includes enabling branch coverage output to the lcov make target,
which is disabled by default.
**READY**
Not sure - I heard we backport all tools changes. Is that right?
NO
=> Enable branch coverage in basic_build_test.sh

Makefile, tests/scripts/basic-build-test.sh
Backport of #3374 
Enable branch coverage output in basic_build_test.sh. This
includes enabling branch coverage output to the lcov make target,
which is disabled by default.
=> Backport 2.16: Enable branch coverage in basic_build_test.sh

Makefile, tests/scripts/basic-build-test.sh
Backport of #3374 
Enable branch coverage output in basic_build_test.sh. This
includes enabling branch coverage output to the lcov make target,
which is disabled by default.
=> Backport 2.7: Enable branch coverage in basic_build_test.sh

ChangeLog.d/montmul-cmp-branch.txt, library/bignum.c
Straightforward backport of https://github.com/ARMmbed/mbedtls/pull/3398
This includes all patches from the original, including the parts that are not strictly necessary to fix the security issue but that make the code more readable and (a little) smaller and faster.
This is a rebase of the original. There were conflicts, but not meaningful ones:
* Whitespace differences.
* No `CHECK_PARAMS` in 2.7.
* An `i++` in the carry propagation part of `mpi_sub_hlp` was dead code that was removed between 2.7 and 2.16. “Move carry propagation out of mpi_sub_hlp” removes it.
=> Backport 2.7: Remove a secret-dependent branch in Montgomery multiplication

ChangeLog.d/montmul-cmp-branch.txt, library/bignum.c
Straightforward backport of https://github.com/ARMmbed/mbedtls/pull/3398
This includes all patches from the original, including the parts that are not strictly necessary to fix the security issue but that make the code more readable and (a little) smaller and faster.
This is a rebase of the original. There were no conflicts.
=> Backport 2.16: Remove a secret-dependent branch in Montgomery multiplication

ChangeLog.d/montmul-cmp-branch.txt, library/bignum.c
Remove a secret-dependent branch in Montgomery multiplication that could expose some bits of a private RSA key.
The potential leak was documented in https://www.usenix.org/system/files/conference/usenixsecurity17/sec17-lee-sangho.pdf and again in https://arxiv.org/pdf/2005.11516.pdf and reported in https://github.com/ARMmbed/mbedtls/issues/3394.
Fix #3394.
In this pull request, I reverted commit 2cc69fffcf431085f18f4e59c3c5188297f97b87 from https://github.com/ARMmbed/mbedtls/pull/457, partly because the only real value of the check it added was to silence a false positive from clang-analyzer, and partly because half of the check was wrong anyway. I think this reversal should be backported with the rest, because it has the benefit that it more than compensates the additional code size from …
=> Remove a secret-dependent branch in Montgomery multiplication

library/pk.c, library/platform_util.c, library/ssl_cli.c, library/ssl_srv.c, library/ssl_tls.c, library/x509_crt.c
The calculations inside the mbedtls_platform_random_delay() function were not entirely clear. This PR add a comment explaining them.
Random delay is used to secure sensitive security operations against double synchronous FI attacks. When such an attack is detected, an appropriate error code should be returned. This PR adds returning MBEDTLS_ERR_PLATFORM_FAULT_DETECTED error code where it was missing..
**READY**
=> Add comment for mbedtls_platform_random_delay() and returning an FAULT_DETECTED error on potential FI attack detection

programs/test/zeroize.c, tests/scripts/test_zeroize.gdb
This is the 2.16 backport of #3363. The only changes are in the first commit, which was needed for the patch to apply cleanly. It reverts some superfluous changes introduced in #2710, as indicated in the commit message
=> [Backport 2.16] Remove hardcoded line number from the zeroize test

programs/test/zeroize.c, tests/scripts/test_zeroize.gdb
We can insert a comment in the line we want to break at, and let the gdb script search for it instead of using the hardcoded line number.
**READY**
Yes
Which branch?
2.16: #3415
=> Remove hardcoded line number from the zeroize test

ChangeLog.d/uniformize_bounds_checks.txt, include/mbedtls/error.h, include/mbedtls/ssl.h, include/mbedtls/ssl_internal.h, library/error.c, library/ssl_cli.c, library/ssl_cookie.c, library/ssl_ticket.c, library/ssl_tls.c
_Context:_ The function `ssl_write_client_hello` writing the `ClientHello` message to the output buffer does not include bounds checks. While there doesn't seem to be such a check missing on bounds not under control of the user, the system may crash if the user uses a faulty config. 
_Changes:_ This pull request introduces several bounds checks, regarding the static part of the `ClientHello` (which the compiler might optimize away) and the dynamic part involving the cipher suites and extensions.
It might need discussion in general to what extend the user should be prevented from the effects of malformed configurations, because the checks come at the cost of computation time and larger memory footprint. An alternative would be to include them for debugging only.
Yes
=> Bounds checks in ssl_write_client_hello

ChangeLog.d/uniformize_bounds_checks.txt, include/mbedtls/error.h, include/mbedtls/ssl.h, include/mbedtls/ssl_internal.h, library/error.c, library/ssl_cli.c, library/ssl_cookie.c, library/ssl_ticket.c, library/ssl_tls.c
This is the 2.16 backport of #873. The backport went quite smootly. Basically it was mainly a question of disregarding code that doesn't exist in 2.16.
Other issue:
- I backported d140d0828e9bf4cc7e59c015c74d9b1923746a96 (Introduce macros for constants in SSL ticket implementation) as well (first commit) to avoid a conflict when backporting the commit "Uniformize bounds checks using new macro" in ssl_ticket.c regarding a mnemonic.
READY
=> [Backport 2.16] Bounds checks in ssl_write_client_hello

ChangeLog.d/uniformize_bounds_checks.txt, include/mbedtls/error.h, include/mbedtls/ssl.h, include/mbedtls/ssl_internal.h, library/error.c, library/ssl_cli.c, library/ssl_cookie.c, library/ssl_ticket.c, library/ssl_tls.c
This is the 2.7 backport of #873. Same as the 2.16 backport but:
- Use of MBEDTLS_SSL_MAX_CONTENT_LEN and not MBEDTLS_SSL_OUT_CONTENT_LEN in ssl_cli.c:ssl_write_client_hello() in commit "Uniformize bounds checks using new macro".
Status
READY
=> [Backport 2.7] Bounds checks in ssl_write_client_hello 

programs/ssl/ssl_server2.c, tests/ssl-opt.sh
1. When `ssl_server2` export key functionality,
don't exit the server, but reset it.
2. Add text filters for `export keys functionality` test in sll-opts.sh
to check for additional output, for verifying export succeeded.
This PR will fix the false positive reported in #2662 , but it doesn't fix the root cause for the failure, which is reported in https://github.com/ARMmbed/mbed-crypto/issues/137
**READY**
NO  
This bug is on a new feature which isn't in any LTS branch
Once this PR wioll be merged, the CI will fail, until https://github.com/ARMmbed/mbed-crypto/issues/137 is fixed and merged!
=> Show failure in ssl-opts.sh  when key export fails

ChangeLog.d/bugfix_PR3405, library/ssl_tls.c, tests/ssl-opt.sh
This PR adds a fix for faulty behaviour when using the library with variable buffer lengths enabled, in a scenario with CID and MFL.
Certain fields in the ssl context might be shifted in `ssl_parse_record_header()` when receiving a connection with CID, so they require a manual update after calling the generic `mbedtls_ssl_reset_in_out_pointers()`.
This PR also adds a regression test which is run by all.sh.
=> Update iv and len context pointers manually when reallocating buffers

ChangeLog.d/bugfix_PR3421.txt, programs/aes/aescrypt2.c, programs/aes/crypt_and_hash.c, tests/suites/main_test.function
=> Define _POSIX_C_SOURCE to be 200112L, as a minimum for C99.

tests/suites/test_suite_psa_crypto_slot_management.function
When the persistent slot lifecycle test discovers a key of the wrong type (not exportable), it still throws it through the export function in order to check that it too will detect this as a not permitted action. For the buffer and buffer length arguments it passes in a local pointer (which will most likely be NULL), and the sizeof that pointer, as it knows that they will never be used. Coverity rightly (imho) flagged this as suspicious - if we are going to pass in incorrect parameters, at least make them obviously incorrect, and ones that will not potentially cause errors if the code later changes. There is, for example safety checks for zero length buffer, but less protection for an insufficiently sized one.
**READY**
NO  (Bug not present in other LTS branches)
NO
=> Remove Dangerous Parameter Passing

tests/scripts/all.sh, tests/scripts/basic-build-test.sh
This PR makes the invocations of `ssl-opt.sh` in `basic-build-test.sh` more deterministic by fixing the seed used by the proxy. The motivations for this include:
- avoid random failures in CI runs due to unlucky seeds that cause the proxy to drop too aggressively, resulting in timeouts
- avoid random variations in coverage stats
I think that was the only part of `basic-build-test.sh` that was non-deterministic in ways that could cause such variations. (Of course SSL tests all use entropy, but neither the result of the tests nor the coverage data should depend on the random values used here.)
**READY**
Yes
=> Make basic-build-test.sh more deterministic

tests/scripts/all.sh, tests/scripts/basic-build-test.sh
This is the straightforward 2.16 backport of #3410.
=> [Backport 2.16] Make basic-build-test.sh more deterministic

tests/scripts/all.sh, tests/scripts/basic-build-test.sh
This is the straightforward 2.7 backport of #3410.
=> [Backport 2.7] Make basic-build-test.sh more deterministic

ChangeLog.d/bugfix_PR3422.txt, library/net_sockets.c, programs/ssl/ssl_mail_client.c
- Define `_XOPEN_SOURCE` in specific files to get definitions of `gethostname` and `sockaddr_storage`
- Add another check for `socklen_t`'s definition. I'm not really happy adding to this since it's quite hacky/messy, but it seems like the least intrusive change I can make for now. (I'm not sure which platforms without socklen_t need special-casing).
Fixes #2310
=> NetBSD 9.0 build fixes

tests/git-scripts/pre-push.sh, tests/scripts/all.sh
Currently there is some level of duplication between all.sh and the pre-push hook: when a fast check is added to all.sh we have to remember to add it to the pre-push hook as well.
This commit adds five components that were previously not run:
- `check_recursion`
- `check_changelog`
- `check_test_cases`
- `check_python_files`
- `check_generate_test_code`
It also changes the behaviour in case in-tree cmake was enabled before pushing or otherwise running the pre-push hook: previously the script failed because check_names is not compatible with cmake, now it silently disables cmake (and succeeds unless there is an actual issue).
**READY**
Yes, as it's a test script.
NO
Though the most important case to test is `tests/scripts/all.sh -q -k 'check_*'` with and without errors, as that's what's …
=> Use all.sh and its component list in pre-push hook

tests/git-scripts/pre-push.sh, tests/scripts/all.sh
This is the 2.16 backport of #2639. It's mostly straighforward except for the following differences:
- invocation of dd not present in 2.16 (skipped 2 commits)
- `component_check_test_cases` not present in 2.16 (skipped 1 commit)
- `OUTCOME_FILE` not present in 2.16 (context only)
=> [backport 2.16] Use all.sh in pre-push hook

tests/git-scripts/pre-push.sh, tests/scripts/all.sh
This is the 2.7 backport of #2639, based on the 2.16 backport in #3446. Compared to the 2.16 backports, differences are:
- yotta option still present in 2.7 (context change only)
- `component_check_generate_test_code` not present in 2.7 (skipped 1 commit)
=> [backport 2.7] Use all.sh in pre-push hook

ChangeLog.d/sysctl-arnd-support.txt, library/entropy_poll.c
This is basically the same as reading from `/dev/urandom` on supported systems, only it has a limit of 256 bytes per call (just to stop programs from spending too much time in the kernel), and does not require an open file descriptor (so it can be used in chroots, when resource limits are in place, or are otherwise exhausted).
It's functionally equivalent to the comparable function `getentropy`, but has been around for longer. It's actually used to implement `getentropy` in FreeBSD's libc. Discussions about adding `getrandom` or `getentropy` to NetBSD are still ongoing.
Note: this is also *much* faster than reading from `/dev/urandom` on NetBSD-current (the performance increase may not be as significant on other platforms). `time(1)` reports unpatched mbedTLS `gen_entropy` as spending 2-3 …
=> entropy: Add support for BSD sysctl(KERN_ARND)

programs/ssl/CMakeLists.txt
This is a partial backport of #3438, covering only the one applicable bug fix in programs/*/CmakeLists.txt. It is smaller than the [2.16 backport](https://github.com/ARMmbed/mbedtls/pull/3460):
* “programs: ssl: cmake: Reorder declaration of executables”: similar to 2.16.
* “programs: ssl: cmake: Add missing executables”: as in 2.16.
* “programs: cmake: Fix relative path warnings”: not applicable.
=> Programs cmake cleanup 2.7

tests/suites/helpers.function, tests/suites/host_test.function, tests/suites/target_test.function, tests/suites/test_suite_aes.function, tests/suites/test_suite_aria.function, tests/suites/test_suite_ccm.function, tests/suites/test_suite_chacha20.function, tests/suites/test_suite_chachapoly.function, tests/suites/test_suite_cipher.function, tests/suites/test_suite_ecdh.function, tests/suites/test_suite_ecdsa.function, tests/suites/test_suite_hkdf.function, tests/suites/test_suite_nist_kw.function, tests/suites/test_suite_pk.function, tests/suites/test_suite_poly1305.function
Partial backport of #3438 
Fix #3459
To ease the partial backport I have also backported [72d628f](https://github.com/ARMmbed/mbedtls/commit/72d628f7f5a6014ededd3bff5f32d6b2f2109821) and [ff31eab](https://github.com/ARMmbed/mbedtls/commit/ff31eab9381496a8808c9affdf48dbe526ced887) (adding mbedtls_test_ prefix to unhexify and hexify and associated reformatting). 
The backport was almost straightforward but for:
test_suite_cipher.function:test_vec_crypt(): Removed `use_psa` parameter               
test_suite_ecdh.function:ecdh_start(): `rnd_buf_info` type instead of `mbedtls_test_rnd_buf_info`
test_suite_ccm.function:mbedtls_ccm_star_auth_decrypt: Changes TEST_EQUAL's to TEST_ASSERT's
CI check
=> [Backport 2.16] Get rid of mbedtls_test_unhexify() in unit test code

programs/ssl/CMakeLists.txt, programs/test/CMakeLists.txt
This is a partial backport of #3438, covering only the bug fixes in `programs/*/CmakeLists.txt`.
* “programs: ssl: cmake: Reorder declaration of executables” — not a bug fix, but harmless and facilitates maintenance (including applying the subsequent patches).
* “programs: ssl: cmake: Add missing executables” — adapted, only one executable is missing in 2.16.
* “programs: cmake: Fix relative path warnings”
Not backported:
* “programs: cmake: Use list of executables” — it would facilitate maintenance, but there are many merge conflicts because development links crypto programs with libmbedcrypto whereas 2.16 links everything with libmbedtls.
* “programs: psa: Link against mbedcrypto not mbedtls” — not applicable to 2.16.
Needs backport to 2.7.
=> 2.16 only: cmake cleanups under programs/

library/cipher_wrap.c
This reduces the code size by not compiling in unnecessary info structures when using only 128 bit AES.
Co-authored by: AnttiKauppila <antti.kauppila@arm.com>
=> Wrap AES 192 and 256 info structures in an !AES_ONLY_128_BIT_KEY_LENGTH define

ChangeLog.d/bugfix_PR3452.txt, library/padlock.c
=> Use local labels in padlock.c

ChangeLog.d/x509write_csr_heap_alloc.txt, library/x509write_csr.c
`x509write_csr_der_internal()` uses a fixed 2KB stack buffer for writing the CSR. This is problematic because:
- a 2KB stack allocation can produce a stack overflow on embedded devices with limited stack space.
- it arbitrarily constrains the maximum size of the CSR that mbedtls can produce to only 2KB where an app may require more complicated CSRs.
This PR revives #2118, which appears to be abandoned.
- The original PR modifies `x509write_csr_der_internal()` to dynamically allocate the requested CSR buffer size, which resolves both issues. 
- All outstanding review comments from that PR are addressed here.
**READY**
NO
NO
In reference to issue #2631, we were waiting on change #2118 in addition to the committed #2632. While nothing necessitates this change being backported, we would like …
=> Dynamically allocate requested CSR write buffer size

include/mbedtls/aes.h, library/aes.c
This PR is based on https://github.com/ARMmbed/mbedtls/pull/3456.
Please only review commit de506a8.
=> Use a fake random key in AES calculations

ChangeLog.d/bugfix_PR_2632.txt, include/mbedtls/pem.h, library/x509write_crt.c
Per [discussion with @mpg in PR #3464](https://github.com/ARMmbed/mbedtls/pull/3464#issuecomment-656569784), backporting the bugfix #2632 to mbedtls-2.16.
**READY**
NO
Backported changes are self-contained and exercised through existing `make` and `make check`.
=> Backport 2.16: PR #2632 Avoid use of large stack buffers in CRT writing

include/mbedtls/asn1.h, include/mbedtls/compat-1.3.h, include/mbedtls/platform_util.h, library/asn1parse.c, library/asn1write.c, library/des.c, library/oid.c, library/pem.c, library/pk.c, library/pkparse.c, library/platform_util.c, library/rsa.c, library/ssl_cache.c, library/ssl_cli.c, library/ssl_cookie.c, library/ssl_srv.c, library/ssl_ticket.c, library/ssl_tls.c, library/x509.c, library/x509_crl.c, library/x509_crt.c
This PR contains minor refactoring changes like:
* Renamed `mbedtls_platform_memcmp()` to `mbedtls_platform_memequal()`
* A few smaller changes
**READY**
=> Renamed mbedtls_platform_memcmp() to mbedtls_platform_memequal()

include/mbedtls/platform_util.h, library/platform_util.c
The earlier implementation had two problems: the random generator always returned 0 if the MBEDTLS_ENTROPY_HARDWARE_ALT flag was not defined and there was no protection needed if the HW RNG was malfunctioning. Both these problems have been solved in this PR by adding the linear congruential generator algorithm as a non-cryptographic random number generator.
**READY**
=> Expanded the random number generator in the `platform_util.c` file

ChangeLog.d/x509write_csr_heap_alloc.txt, library/x509write_csr.c
Per [discussion with @mpg in PR #3464](https://github.com/ARMmbed/mbedtls/pull/3464#issuecomment-656569784), backporting that PR to mbedtls-2.16.
**READY**
NO
Backported changes are self-contained and exercised through existing `make` and `make check`.
=> Backport 2.16: PR #3464 Dynamically allocate requested CSR write buffer size

include/mbedtls/platform_util.h, library/entropy.c, library/pkparse.c, library/platform_util.c, library/rsa.c, library/ssl_tls.c, tinycrypt/ecc_dh.c
This PR adds a flow monitor to the functions `mbedtls_platform_memset()`, `mbedtls_platform_memcpy()` and `mbedtls_platform_zeroize()`. Several checks have also been added in security-sensitive places to see if these functions performed correctly. 
**Note:** The first commit "Rename mbedtls_platform_memcmp() to mbedtls_platform_memequal()" come from another PR
**READY**
=> Add flow monitor for memory block operations

tests/git-scripts/pre-commit.sh, tests/scripts/check-generated-files.sh
This PR:
- adds an `-u` option to `check-generate-files.sh` that causes it to just update the damn files rather than moan about them being out-of-date ;)
- adds a pre-commit hook that people can install if they want generated files to be checked before commiting.
This PR _does not_ make the pre-commit hook automagically update the files for you. That would require making the appropriate calls to `git add / git rm` from the pre-commit hook and this was a bit more than I felt like doing. This PR is not meant to be perfect, just a minor but non-zero improvement over the existing.
Workflow before:
- make a change that would require updating some file, but naturally forget about it and commit
- do other changes, as some point push
- either the pre-push hook or the CI notices some file is …
=> Add update option to check-generated-files

ChangeLog.d/netbsd-rand-arc4random_buf.txt, library/rsa.c, tests/src/random.c
This older implementation of rand generates the same small set of random numbers (or rather their lower bits) over and over again. A number of tests do not complete because of this. There exists already a conditional for OpenBSD making use of arc4random_buf instead which is also included in the C standard Library of NetBSD.
Backports: #3559 #3560
=> Use arc4random_buf instead of rand on NetBSD

ChangeLog.d/netbsd-rand-arc4random_buf.txt, library/rsa.c, tests/suites/helpers.function
=> [Backport 2.16] Use arc4random_buf instead of rand on NetBSD

ChangeLog.d/netbsd-rand-arc4random_buf.txt, library/rsa.c, tests/suites/helpers.function
=> [Backport 2.7] Use arc4random_buf instead of rand on NetBSD

library/chacha20.c, library/chachapoly.c, library/poly1305.c, undef_assert_before_defining_it.txt
If a previous definition of ASSERT has sneaked in through included files an "ASSERT redefined" warnings would show up.
**READY**
Build with MBEDTLS_SELF_TEST enabled.
=> Ensure that only one definition of ASSERT is present

tests/compat.sh, tests/ssl-opt.sh
The main feature of this PR is to always use a proxy, which logs timing information, which is necessary to analyze some failures, for example #3377. While at it a minor clean-up and a minor improvement are done too.
**READY**
Yes, as this improves debuggability of some currently mysterious CI failures.
```
tests/ssl-opt.sh -p -f 'Default'
ls tests/o-*.log
```
Check that there's a proxy log for the DTLS case but not for the TLS case.
```
tests/ssl-opt.sh -p -f "client reconnect"
head -n2 tests/o-pxy-*.log
```
Check that the proxy was added in all cases with the expected arguments, and that in the last test case (attacker-injected) the proxy command has the expected additional arguments.
=> Improve ssl-opt.sh logs

tests/compat.sh, tests/ssl-opt.sh
This is the 2.7 backport of #3404 - all straightforward.
```
tests/ssl-opt.sh -p -f 'Default'
ls tests/o-*.log
```
Check that there's a proxy log for the DTLS case but not for the TLS case.
```
tests/ssl-opt.sh -p -f "client reconnect"
head -n2 tests/o-pxy-*.log
```
Check that the proxy was added in all cases with the expected arguments, and that in the last test case (attacker-injected) the proxy command has the expected additional arguments.
=> [Backport 2.7] Improve ssl-opt.sh logs

tests/compat.sh, tests/ssl-opt.sh
This is the 2.16 backport of #3404 - all straightforward.
```
tests/ssl-opt.sh -p -f 'Default'
ls tests/o-*.log
```
Check that there's a proxy log for the DTLS case but not for the TLS case.
```
tests/ssl-opt.sh -p -f "client reconnect"
head -n2 tests/o-pxy-*.log
```
Check that the proxy was added in all cases with the expected arguments, and that in the last test case (attacker-injected) the proxy command has the expected additional arguments.
=> [Backport 2.16] Improve ssl-opt.sh logs

ChangeLog.d/fix-build-netbsd.txt, library/net_sockets.c, programs/ssl/ssl_mail_client.c
NetBSD conditionals have been added because it was decided in #3422 not to backport the fix.
=> [Backport 2.16] NetBSD 9.0 build fixes

ChangeLog.d/fix-build-netbsd.txt, library/net_sockets.c
=> [Backport 2.7] NetBSD 9.0 build fixes

tests/git-scripts/pre-commit.sh
The file was not updated to include the GPL 2.0+ header as well when it was backported in #3548.
**READY**
Yes 
Which branch?
=> 2.16 only: Fix license header in pre-commit hook

tests/git-scripts/pre-commit.sh
This PR is the 2.7 backport of #3582.
=> Backport 2.7: Fix license header in pre-commit hook

ChangeLog.d/md_setup-leak.txt, library/md.c
Fix #3486.
There is no non-regression test because we don't have the infrastructure to test low memory conditions. You can check manually by building the library and the test program that Guido posted in #3486.
```
scripts/config.py set MBEDTLS_PLATFORM_MEMORY
make CLFAGS='-fsanitize=address,undefined -fno-sanitize-recover=all -fno-common -g3' lib
cc -fsanitize=address,undefined -fno-sanitize-recover=all -fno-common -g3 a.c
./a.out
```
Before: Asan detects a memory leak. After: Asan is happy.
Things I reviewed for similar issues:
* The md module doesn't call malloc anywhere else.
* cipher contexts have two parts: an encryption context and an optional CMAC context. They do setup differently, and if the second allocation fails, the context is in a correct state for `mbedtls_cipher_free()` …
=> Fix memory leak in mbedtls_md_setup with HMAC

ChangeLog.d/stdout-macro.txt, tests/suites/helpers.function, tests/suites/host_test.function
Otherwise it builds and tests fine on OpenBSD, builds fine on NetBSD but (edit: fixed in #3540) gets stuck in mbedtls_mpi_gen_prime (corner case limb size) of test_suite_mpi (both stable/x86_64).
=> Fix bug in redirection of unit test outputs

ChangeLog.d/stdout-macro.txt, tests/suites/helpers.function, tests/suites/host_test.function
=> [Backport 2.16] Fix bug in redirection of unit test outputs

ChangeLog.d/stdout-macro.txt, tests/suites/helpers.function, tests/suites/main_test.function
=> [Backport 2.7] Fix bug in redirection of unit test outputs

ChangeLog.d/e2k-support.txt, library/ssl_tls.c, programs/pkey/dh_genprime.c, tests/suites/helpers.function
Backport of https://github.com/ARMmbed/mbedtls/pull/3574
Signed-off-by: makise-homura <akemi_homura@kurisa.ch>
This pull request introduces support for building mbedtls 2.16 on Elbrus hardware platform (which is based on Russian [Elbrus](https://en.wikipedia.org/wiki/Elbrus-8S) CPU family) with its native lcc (eLbrus Compiler Collection) compiler.
**READY**
This is actually a backport.
NO
This PR fixes the issues causing `-Wsigned-one-bit-field` and `-Wsign-compare` warnings, and probably incorrect execution flow of `dh_genprime`.
Suggested in PR #3574 discussion.
To reproduce, you should have an Elbrus workstation with OS Elbrus >= 5.0-rc2 and CPU which is Elbrus-8C (Elbrus-8S) or newer (you may ask contributor for SSH access to demo station).
Building with `mkdir build; cd build; cmake …
=> Backport 2.16: Support building on e2k (Elbrus) architecture

ChangeLog.d/e2k-support.txt, library/ssl_tls.c, programs/pkey/dh_genprime.c, tests/suites/helpers.function
Backport of https://github.com/ARMmbed/mbedtls/pull/3574
Signed-off-by: makise-homura <akemi_homura@kurisa.ch>
This pull request introduces support for building mbedtls 2.7 on Elbrus hardware platform (which is based on Russian [Elbrus](https://en.wikipedia.org/wiki/Elbrus-8S) CPU family) with its native lcc (eLbrus Compiler Collection) compiler.
**READY**
This is actually a backport.
NO
This PR fixes the issues causing `-Wsigned-one-bit-field` and `-Wsign-compare` warnings, and probably incorrect execution flow of `dh_genprime`.
Suggested in PR #3574 discussion.
To reproduce, you should have an Elbrus workstation with OS Elbrus >= 5.0-rc2 and CPU which is Elbrus-8C (Elbrus-8S) or newer (you may ask contributor for SSH access to demo station).
Building with `mkdir build; cd build; cmake …
=> Backport 2.7: Support building on e2k (Elbrus) architecture

tests/suites/test_suite_psa_crypto.function
Resolve a major test gap in the PSA API: we had no negative tests at all for MAC.
=> PSA: add negative MAC tests

library/psa_crypto_storage.c, library/psa_its_file.c, tests/suites/test_suite_psa_crypto.data, tests/suites/test_suite_psa_crypto.function, tests/suites/test_suite_psa_crypto_hash.function, tests/suites/test_suite_psa_crypto_metadata.function, tests/suites/test_suite_psa_its.function
This is a small set of cleanups in PSA code, mostly prompted by Coverity.
* “Fix parity tests to actually fail the test on error” fixes a bug that causes a test gap.
* “xxx: Annotate file removal” and “Note that a failure in cleanup is intentional” annote code where we deliberately ignore the failure of a function call.
* “Add empty-output-buffer test cases for single-part hash functions” adds test cases that confirm experimentally that one particular Coverity issue is a false positive.
* “Add missing cleanup to some multipart operation tests” fixes something that isn't currently broken, but could become so with drivers.
=> Minor fixes in PSA code and tests

include/tinycrypt/ecc.h
Thanks to this change the produced ASM does not need an additional instruction to place the constant value in a register, but can compare it directly.
=> [Baremetal] Change the UECC_SUCCESS return value to 0xCC

tests/scripts/all.sh
GCC up to 4.x defaults to C89. On our CI, we run the arm-none-eabi-gcc
version from Ubuntu 16.04 on Travis, and that's 4.9, so the gcc-arm
builds started failing on Travis when we introduced a C99 construct in
the configurations that we test on arm on Travis. Other builds, and
Jenkins CI, are not affected because they use GCC 5.x or newer.
This fixes the urgent part of https://github.com/ARMmbed/mbedtls/issues/3631: failing CI (Travis). It doesn't fix the other part: cmake build not working out of the box with RHEL.
=> Fix arm-gcc bulds in Travis runs with 2.24.0

tests/suites/helpers.function, tests/suites/test_suite_mpi.function
If `test_fail` is called multiple times in the same test case, report the location of the first failure, not the last one.
With this change, you no longer need to take care in tests that use auxiliary functions not to fail in the main function if the auxiliary function has failed.
I can't think of any reason to preserve the old behavior of keeping the location of the last failure. We're currently avoiding double failures because the second call to `test_fail` would overwrite the location information. If we are currently calling `test_fail` twice on some code paths, it would be by mistake. `mbedtls_param_failed` is a special case that partially pre-records a non-failure, but even in that case we expect `test_fail` not to have been called before.
Demonstration:
```
git checkout …
```
=> Report the first unit test failure, not the last one

tests/suites/helpers.function, tests/suites/test_suite_mpi.function
Backport of https://github.com/ARMmbed/mbedtls/pull/3625
The old test framework had the same behavior and essentially the same code.
=> Backport 2.7: Report the first unit test failure, not the last one

ChangeLog.d/adjusting sliding_window_size_PR3592.txt, include/mbedtls/bignum.h, include/mbedtls/config.h, library/bignum.c
Backport of #3592 to the mbedtls-2.7 branch.
=> Backport 2.7: adjusting size of sliding window array to correct size

ChangeLog.d/adjusting sliding_window_size_PR3592.txt, include/mbedtls/bignum.h, include/mbedtls/config.h, library/bignum.c
Backport of #3592 to the mbedtls-2.16 branch.
=> Backport 2.16: adjusting size of sliding window array to correct size

ChangeLog.d/adjusting sliding_window_size_PR3592.txt, include/mbedtls/bignum.h, include/mbedtls/config.h, library/bignum.c
Probably the `W[2 << MBEDTLS_MPI_WINDOW_SIZE]` notation is based on a transcription of 2**MBEDTLS_MPI_WINDOW_SIZE.
This PR fixes #3591 [edited by mpg to use github keyword]
**READY**
This change is easy to backport, but is not strictly required.
I would recommend to backport it to all LTS branches.
No API changes
This change would improve stack usage significantly.
=> adjusting size of sliding window array to correct size.

.travis.yml, ChangeLog.d/bugfix_PR3294.txt, library/pk.c, library/pk_wrap.c, tests/scripts/all.sh, tests/suites/test_suite_pk.function
This commit is fixing an issue when an undefined reference occurs when using MBEDTLS_USE_PSA_CRYPTO and removing ECDSA support. New guards added to pk_wrap.c and updates to fix unused function parameter warnings in pk_wrap.c and pk.c. Also created two new tests in all.sh to verify basic features are working when MBEDTLS_USE_PSA_CRYPTO is enabled.
Fixes #3294 
READY
NO
NO
Reproduce:
Enable MBEDTLS_USE_PSA_CRYPTO and remove ECDSA_C and build setup. It will show the undefined reference warning without these changes. 
Test:
After these changes are applied the build will work properly. 
Added new tests to all.sh to easily confirm basics with USE_PSA_CRYPTO are working properly: test_depends_pkalgs_psa and test_depends_curves_psa
=> Fix the build with MBEDTLS_USE_PSA_CRYPTO without ECDSA

library/x509.c
Side-port of #3509 
**READY**
No - not a bug, just enhancing source readability by reducing noise.
NO
=> x509.c: Remove one unnecessary cast

library/md2.c, library/md4.c, library/md5.c, library/ripemd160.c, library/sha512.c
Wrap multi-line string literals in parentheses
to prevent a Clang 12 -Wstring-concatenation warning
(activated by -Wall), which caused the build to fail.
Fixes https://github.com/ARMmbed/mbedtls/issues/3586
Signed-off-by: Guido Vranken <guidovranken@gmail.com>
READY
Yes
NO
Compile mbed TLS under the OSS-Fuzz Docker image, which can be launched using:
```
docker run -t -i --rm gcr.io/oss-fuzz-base/base-builder:latest bash
```
=> Prevent triggering Clang 12 -Wstring-concatenation warning

ChangeLog.d/comment_typo_in_mbedtls_ssl_set_bio.txt, include/mbedtls/ssl.h
Description referred to mbedtls_ssl_sent_t callback,
but the callback is named mbedtls_ssl_send_t.
Signed-off-by: Christopher Moynihan <christophm@gmail.com>
=> Fix typo in mbedtls_ssl_set_bio description.

ChangeLog.d/comment_typo_in_mbedtls_ssl_set_bio.txt, include/mbedtls/ssl.h
This is a trivial backport of #3569.
=> Backport 2.16: Fix typo in mbedtls_ssl_set_bio description.

ChangeLog.d/comment_typo_in_mbedtls_ssl_set_bio.txt, include/mbedtls/ssl.h
This is a trivial backport of  #3569.
=> Backport 2.7: Fix typo in mbedtls_ssl_set_bio description.

docs/proposed/Makefile, docs/proposed/psa-conditional-inclusion-c.md
Proposed specification for conditional inclusion of cryptographic mechanism through the PSA API in Mbed TLS.
This is work in progress, presented for a first design discussion.
=> Pure C configuration of PSA crypto mechanisms

ChangeLog.d/add-aes-ecb-to-psa.txt, include/mbedtls/psa_util.h, include/psa/crypto_values.h, library/psa_crypto.c, tests/suites/test_suite_psa_crypto.data, tests/suites/test_suite_psa_crypto.function, tests/suites/test_suite_psa_crypto_metadata.data
This PR implements support for `PSA_ALG_ECB_NO_PADDING` as defined in the PSA Crypto API spec v1.0.0. Feature was requested in #3277.
**READY**
NO  
NO
Tested through the PSA Crypto test suite.
=> Added support for AES-ECB to the PSA Crypto implementation

include/mbedtls/platform_util.h, library/platform_util.c, tinycrypt/ecc.c
Signed-off-by: Shelly Liberman <shelly.liberman@arm.com>
Replace user random function by platform non cryptographic random generator in random delays  during ecc calculations.
This replacement improve run time of ecc calculations as non crypto random is much faster
READY
=> replace user rand by platform rand in ecc delays

include/mbedtls/ccm.h, include/mbedtls/gcm.h
I noticed this while reading the docs of some GCM functions. The `tag` buffer parameter, which is written into during the encrypt operation, is described as "readable" instead of "writable". Change it to "writable" where relevant (for encrypt ops) and keep it "readable" for the decrypt op.
Ready.
Maybe? I don't know if you bother to backport documentation fixes.
No.
=> Fix docs to desribe written-into buffer parameter as writable

include/mbedtls/ccm.h, include/mbedtls/gcm.h
This is a backport to 2.16 of https://github.com/ARMmbed/mbedtls/pull/3667.
=> Backport 2.16: Fix docs to desribe written-into buffer parameter as writable

library/pkparse.c
Fix #2512
Notes:
In all other cases, the invalid public key error, caused by an ASN1 length mismatch error, is calculated as:
https://github.com/ARMmbed/mbedtls/blob/5cb54f7b27e1ebc1602233f50c44c1ff05304852/library/pkparse.c#L638-L640
In the case this PR fixes, a `+` is missing: …
=> fix return code

library/pkparse.c
=> Backport 2.16: fix return code

library/pkparse.c
=> Backport 2.7: fix return code

ChangeLog.d/fix-rsa-blinding.txt, library/rsa.c
Starting with commit 406c7aedc474fd77ebc1a7baf1b86c6a8b0e7b62, the do/while loop in `rsa_prepare_blinding()` was changed to a `do...while(0)`, which prevents retry from being effective and leaves dead code.
Restore the while condition to retry, and lift the calls to finish the computation out of the while loop (by observing that they are
performed only when `mbedtls_mpi_inv_mod()` returns zero.)
**READY**
No
NO
Fixes #3647
This is a backport of #3717 
Credit to Synopsys Coverity for finding this.
Regression testing should be sufficient.
=> Backport 2.7: Restore retry in rsa_prepare_blinding()

ChangeLog.d/fix-rsa-blinding.txt, library/rsa.c
Starting with commit 49e94e3, the do/while loop in `rsa_prepare_blinding()` was changed to a `do...while(0)`, which prevents retry from being effective and leaves dead code.
Restore the while condition to retry, and lift the calls to finish the computation out of the while loop (by observing that they are
performed only when `mbedtls_mpi_inv_mod()` returns zero.)
**READY**
No
NO
Fixes #3647
This is a backport of #3717 
Credit to Synopsys Coverity for finding this.
Regression testing should be sufficient.
=> Backport 2.16: Restore retry in rsa_prepare_blinding()

ChangeLog.d/fix-rsa-blinding.txt, library/rsa.c
Starting with commit 750d3c76cbc1071774a7efd75d578c4b798d7cb6, the do/while loop in `rsa_prepare_blinding()` was changed to a `do...while(0)`, which prevents retry from being effective and leaves dead code.
Restore the while condition to retry, and lift the calls to finish the computation out of the while loop (by observing that they are
performed only when `mbedtls_mpi_inv_mod()` returns zero.)
**READY**
Yes  
Which branch? 2.16, 2.7
NO
Fixes #3647
Credit to Synopsys Coverity for finding this.
Regression testing should be sufficient.
=> Restore retry in rsa_prepare_blinding()

ChangeLog.d/00README.md, ChangeLog.d/comment_typo_in_mbedtls_ssl_set_bio.txt
Backport of https://github.com/ARMmbed/mbedtls/pull/3726
=> Backport 2.7: Only use ChangeLog to inform users, not for acknowledgement

ChangeLog.d/00README.md, ChangeLog.d/comment_typo_in_mbedtls_ssl_set_bio.txt
Backport of https://github.com/ARMmbed/mbedtls/pull/3726
=> Backport 2.16: Only use ChangeLog to inform users, not for acknowledgement

ChangeLog.d/00README.md, ChangeLog.d/comment_typo_in_mbedtls_ssl_set_bio.txt, ChangeLog.d/fix-typo.txt
[As announced on the mailing list](https://lists.trustedfirmware.org/pipermail/mbed-tls/2020-September/000190.html), we are no longer using the changelog file to credit external contributors. This is effective retroactively from the latest release (2.24). As a consequence:
* Remove pending changelog entries that were for acknowledgement only.
* Update the rules in the changelog readme file. I also wrote a summary of when (not) to write a changelog entry.
Backports: [2.16](https://github.com/ARMmbed/mbedtls/pull/3732), [2.7](https://github.com/ARMmbed/mbedtls/pull/3733)
=> Only use ChangeLog to inform users, not for acknowledgement

ChangeLog.d/_GNU_SOURCE-redefined.txt, library/entropy_poll.c
Backport of https://github.com/ARMmbed/mbedtls/pull/3734 (minus the revert, since the problematic commit was only applied to development).
=> Backport 2.16: Don't redefine _GNU_SOURCE if it's already defined

ChangeLog.d/_GNU_SOURCE-redefined.txt, ChangeLog.d/getrandom.txt, library/entropy_poll.c
* Revert https://github.com/ARMmbed/mbedtls/pull/3642 which [caused binaries compiled with a recent libc not to work with a slightly less recent libc anymore](https://github.com/ARMmbed/mbedtls/pull/3642/files#r497469871).
* Fix https://github.com/ARMmbed/mbedtls/issues/3432, specifically the core “`_GNU_SOURCE` redefined” part.
https://github.com/ARMmbed/mbedtls/issues/3432 also discusses generalizing to other libc. This is trickier and discussed in https://github.com/ARMmbed/mbedtls/pull/3731.
Backport: [2.16](https://github.com/ARMmbed/mbedtls/pull/3735). Not applicable to 2.7 because in 2.7 we didn't define `_GNU_SOURCE` automatically, it was up to the build environment.
=> Don't redefine _GNU_SOURCE if it's already defined

tests/suites/helpers.function, tests/suites/test_suite_aes.function, tests/suites/test_suite_arc4.function, tests/suites/test_suite_aria.function, tests/suites/test_suite_blowfish.function, tests/suites/test_suite_camellia.function, tests/suites/test_suite_ccm.function, tests/suites/test_suite_chacha20.function, tests/suites/test_suite_des.function, tests/suites/test_suite_ecp.function, tests/suites/test_suite_gcm.function, tests/suites/test_suite_hkdf.function, tests/suites/test_suite_md.function, tests/suites/test_suite_mdx.function, tests/suites/test_suite_mpi.function, tests/suites/test_suite_pkcs1_v15.function, tests/suites/test_suite_pkcs1_v21.function, tests/suites/test_suite_pkcs5.function, tests/suites/test_suite_poly1305.function, tests/suites/test_suite_rsa.function, tests/suites/test_suite_shax.function, tests/suites/test_suite_x509parse.function, tests/suites/test_suite_xtea.function
Partial backport of #3474
To ease the partial backport, I have also backported de70b16 and 2dbba99 (adding mbedtls_test_ prefix to hexcmp and associated reformatting).
The backport was almost straightforward. The conflict resolutions were essentially about removing code that is in development but not in 2.16.
READY
=> [Backport 2.16] Backport clean-up in tests done in #3474

library/psa_crypto_driver_wrappers.c, tests/include/test/drivers/size.h, tests/src/drivers/size.c, visualc/VS2010/mbedTLS.vcxproj
Added support for retrieving key context size from unified driver interface to PSA driver wrapper. This allows the PSA core to properly receive the key context size for opaque drivers. Not included are variations of drivers to validate all permutations of drivers to confirm sizing handled correctly.
Fix https://github.com/ARMmbed/mbedtls/issues/3289
READY
NO
=> PSA: support arbitrary data storage from opaque drivers

tests/scripts/all.sh
Set the CMake-observed variable `CTEST_OUTPUT_ON_FAILURE`, so that when
a "make test" run by CMake fails, verbose test output about the detail
of failure is available.
Backport of https://github.com/ARMmbed/mbed-crypto/pull/52. Rebase of https://github.com/ARMmbed/mbedtls/pull/2433.
=> Backport 2.7: all.sh: Enable verbose failure messages for CMake

tests/suites/helpers.function, tests/suites/test_suite_ccm.data, tests/suites/test_suite_ccm.function
The ccm tests were previously relying on unspecified behaviour in
the underlying implementation (i.e. that it rejects certain buffer
sizes without reading the buffer).
**READY**
NO. Probably not required; this cleans up the test code to eliminate a potential issue but there are no active bugs.
Run test_suite_ccm
=> Fix memory allocation in ccm tests

ChangeLog.d/fix_ccm_add_length_check.txt, library/ccm.c, tests/suites/test_suite_ccm.data
The CCM specification (NIST SP 800-38C) mandates that the formatting of
the additional data length l(a) changes when it is greater _or equal_ to
2^16 - 2^8 (>= 0xFF00). Since such lengths are not supported in mbed TLS,
the operation should fail in such cases.
This PR fixes an off-by-one error which allowed encryption/decryption
to be executed when l(a) was equal to 0xFF00, resulting in an
incorrect/non-standard length format being used.
Fixes #3719 
READY
Not sure. The bug is not critical.
NO
=> Fix additional data length field check for CCM

tests/scripts/all.sh
Set the CMake-observed variable `CTEST_OUTPUT_ON_FAILURE`, so that when
a "make test" run by CMake fails, verbose test output about the detail
of failure is available.
Backport of https://github.com/ARMmbed/mbed-crypto/pull/52. Rebase of https://github.com/ARMmbed/mbedtls/pull/2434.
=> Backport 2.16: all.sh: Enable verbose failure messages for CMake

library/ssl_msg.c, library/ssl_tls.c
Mbed TLS requires users of DTLS to configure timer callbacks needed to implement the wait-and-retransmit logic of DTLS.
Previously, the presence of these timer callbacks was checked at every invocation of `mbedtls_ssl_fetch_input()`, so lowest layer of the messaging stack interfacing with the underlying transport.
This PR removes this recurring check and instead checks the presence of timers once at the beginning of the handshake.
The main rationale for this change is that it is a step towards separating the various layers of the messaging stack more cleanly:
datagram layer, record layer, message layer, retransmission layer.
=> Check presence of DTLS retransmission timers only once

CMakeLists.txt, ChangeLog.d/minimum_cmake_version_PR3802.txt
Upgrade minimum cmake version to 3.15
* Patch for https://github.com/ARMmbed/mbedtls/issues/3801
* CMake will soon deprecate support for 2.x
Signed-off-by: Peter Toft <peter.toft@dirac.com>
=> Update mimimum required cmake version

tinycrypt/ecc.c
Restore original tinycrypt implementation of regularize_k() function . 
The fix provide more general solution to array overrun problem that found out by Kevin Bracey in https://github.com/ARMmbed/mbedtls/pull/3749
=> Restore tinycrypt implementation of regularize_k()

CMakeLists.txt
The current CMakeLists.txt has problems when making integration to other projects also running cmake. 
The current code traverses the CMAKE_BUILD_TYPE to the mother project, which can be anything - thus clearly problematic.
Especially if the mother project has their own sanitizers setup the current code invalidates that from the mother project.
With the patch the code will let the project using mbedtls control the build types.
Solves: https://github.com/ARMmbed/mbedtls/issues/3789
Signed-off-by: peter-toft-greve
=> Add fix for cmake control of CMAKE_BUILD_TYPE only if mbedtls is the root project

library/ssl_tls.c
This PR fixes a missing memory allocation check.
=> [baremetal] ssl_tls.c: Fix unchecked memory allocation

ChangeLog.d/aes-zeroize-pointer.txt, library/aes.c
Straightforward backport of #3609 but for the replacement of mbedtls_platform_zeroize() by mbedtls_zeroize().
=> Backport 2.7: Remove a useless zeroization

ChangeLog.d/aes-zeroize-pointer.txt, library/aes.c
Straightforward backport of #3609 in 2.16.
=> Backport 2.16: Remove a useless zeroization

ChangeLog.d/aes-zeroize-pointer.txt, library/aes.c
Remove a useless and misleading call to `mbedtls_platform_zeroize` in `aes.c`.
Running
```
clang-tidy -allow-enabling-analyzer-alpha-checkers -checks='-*,clang-analyzer-alpha.core.SizeofPtr' library/*.c -- -I include
```
with Clang 10.0.0 confirms that (according to this static checker) this was the only similar case, and in particular there wasn't another case where we zeroize `sizeof(pointer)` when `array_size` was meant.
2.16 backport: #3812
2.7 backport: #3813
=> Remove a useless zeroization

programs/ssl/ssl_server2.c
This way, even when an error is encountered early, the memory will be deallocated properly.
=> [baremetal] ssl_server2: move memory allocation to the beginning

programs/ssl/CMakeLists.txt, programs/test/CMakeLists.txt
CMake versions less than 3.0 do not support the `target_sources`
command.  In order to be able to support v2.8.12.2 of cmake, add the
extra targets directly to the target command.
This is a backport from the development branch, except that the uses in
this branch are simpler, and modifying the SOURCES property directly is
not needed.
Fixes #3801
Signed-off-by: David Brown <david.brown@linaro.org>
Backport of #3845. This backport follows the same spirit, but the uses of target_sources in the 2.16 branch are much simpler than in the development branch, and it is easier to just add the extra targets to the main executable command.
=> cmake: Avoid using target_properties for old cmake

ChangeLog.d/ecb_iv_fix.txt, library/cipher_wrap.c
This is the 2.7 backport of #3836. It is identical to the parent PR, except for omitting the changes to the ARIA ciphers, since those don't exist on 2.7.
=> Backport 2.7: Do not set IV size for ECB mode ciphers

ChangeLog.d/ecb_iv_fix.txt, library/cipher_wrap.c
This is the 2.16 backport of #3836. It is identical to the parent PR.
=> Backport 2.16: Do not set IV size for ECB mode ciphers

ChangeLog.d/ecb_iv_fix.txt, library/cipher_wrap.c
This PR fixes the `mbedtls_cipher_info_t` structures in `library/cipher_wrap.c` that erroneously declare that block ciphers in ECB mode use IVs. (The AES ECB mode ciphers were already correct).
**READY**
Yes  
Which branch?
- 2.7 #3862
- 2.16 #3861
NO
=> Do not set iv size for ECB mode ciphers

library/aes.c, library/ccm.c, library/cipher.c, library/ecp.c, library/ssl_tls.c, tinycrypt/ecc.c
Use `uint_fast8_t` instead of `unsigned char` in various loop-type situations. This avoids the need for a 16 or 32-bit system to insert explicit narrow-to-8-bit instructions.
Not the result of an exhaustive source analysis, rather inspecting the disassembly output for a cut-down Cortex-M0+ build looking for UXTB etc instructions, so there could well be more in the complete configuration.
=> [baremetal] Avoid narrow loop counters etc

library/aes.c
This is fix for the MBEDTLS_AES_SETKEY_DEC_ALT macro switch is including the aes xts methods
and building with a custom mbedtls_aes_setkey_dec function will disable the aes xts methods.
The fix is separating the aes xts methods and the MBEDTLS_AES_SETKEY_DEC_ALT can only
switch the presence of the mbedtls_aes_setkey_dec function.
Fixes #3818.
Yes
=> Make the aes xts methods independent from MBEDTLS_AES_SETKEY_DEC_ALT

library/aes.c
This is the 2.16 backport of #3823.
No changes made to the original PR.
This is fix for the MBEDTLS_AES_SETKEY_DEC_ALT macro switch is including the aes xts methods
and building with a custom mbedtls_aes_setkey_dec function will disable the aes xts methods.
The fix is separating the aes xts methods and the MBEDTLS_AES_SETKEY_DEC_ALT can only
switch the presence of the mbedtls_aes_setkey_dec function.
Fixes #3818.
=> [Backport 2.16] Make the aes xts methods independent from MBEDTLS_AES_SETKEY_DEC_ALT

ChangeLog.d/arc4random_buf-implicit.txt, tests/suites/main_test.function
This is a backport of #3571.
Edit: added OpenBSD counterpart (see [stdlib.h#L316-L319](https://github.com/openbsd/src/blob/master/include/stdlib.h#L316-L319) and [cdefs.h#L392-L395](https://github.com/openbsd/src/blob/master/sys/sys/cdefs.h#L392-L395))
=> [Backport 2.16] NetBSD/OpenBSD symbol availability fix

library/error.c, scripts/data_files/error.fmt, tests/scripts/all.sh, tests/scripts/test-ref-configs.pl
Partial backport of #3867. Almost identical to the 2.16 backport in #3886, the only difference is a slightly different set of configurations in `test-ref-configs.pl`.
=> Backport 2.7: Fix several configuration-related issues

ChangeLog.d/error-include-string.txt, include/mbedtls/config.h, include/psa/crypto_platform.h, library/error.c, programs/ssl/ssl_context_info.c, scripts/data_files/error.fmt, tests/scripts/all.sh, tests/scripts/test-ref-configs.pl
Bug fixes:
* Fix the build with user configuration files that have forked from the default `config.h` or have been written from scratch, and that enable `MBEDTLS_PSA_CRYPTO_C`. Such configurations broke when #3712 started using the new configuration mechanism `MBEDTLS_PSA_CRYPTO_CONFIG` and introduced the header `mbedtls/config_psa.h`. This new header must be included even with the old configuration mechanism, but we can't rely on `config.h` to do it.
* Fix the build when `MBEDTLS_ERROR_C` is defined but not `MBEDTLS_ERROR_STRERROR_DUMMY`. This was accidentally broken when tweaking header inclusions in https://github.com/ARMmbed/mbedtls/pull/2958/files#diff-b37646397b0ddf118d2813bff10075ce7f875bcd98aa708af43b096bf8bb6dd6. Fix #3866.
* Fix the build when X.509 is enabled but not TLS …
=> Fix several configuration-related issues

library/error.c, scripts/data_files/error.fmt, tests/scripts/all.sh, tests/scripts/test-ref-configs.pl
Backport of the applicable parts of https://github.com/ARMmbed/mbedtls/pull/3867. In 2.16 there were test gaps but no actual bug.
* Add `config-no-entropy.h` to `test-ref-configs.pl`.
* Clean up preprocessor conditionals in `error.c`. In 2.16 this wasn't buggy, but there were superfluous definitions.
* Ensure that `MBEDTLS_ERROR_C` without `MBEDTLS_ERROR_STRERROR_DUMMY` is tested (via `config-no-entropy.h` — not ideal but it'll do).
* Ensure that `MBEDTLS_ERROR_STRERROR_DUMMY` without `MBEDTLS_ERROR_C` is tested (new `all.sh` component).
=> Backport 2.16: Fix several configuration-related issues

library/ssl_srv.c
This is a complement to commit 0a8352b4, which initialized the beginning of `peer_pms`, but did not initialize `peer_pmslen`.
**READY**
NO (since the overall impact is low (removing a minor case of undefined behavior, and only in case decryption fails), I'd argue this is more of an enhancement and future-proofing than a fix per se, and thus backporting would not be necessary)
NO
I took the liberty of mentioning the `peer_pmslen` variable in the comments, and re-arranging them not to exceed 80 characters per line.
A different patch might be to simply initialize the variable during declaration, but it would lack the comment explaining why.
For reproduction, a fully-configured analysis with Frama-C/Eva would be necessary. Otherwise, you need to force a decryption failure in …
=> Fix another use of uinitialized memory in ssl_parse_encrypted_pms

library/ssl_srv.c
Backport of #3876.
Co-authored-by: Gilles Peskine <gilles.peskine@arm.com>
Signed-off-by: André Maroneze <maroneze@users.noreply.github.com>
=> Backport 2.16: Fix another use of uinitialized memory in ssl_parse_encrypted_pms

library/ssl_srv.c
Backport of #3876, with a more relevant comment.
Signed-off-by: André Maroneze <maroneze@users.noreply.github.com>
=> Backport 2.7: Fix use of uinitialized memory in ssl_parse_encrypted_pms

.gitignore
Added a pattern for CScope [http://cscope.sourceforge.net/] to .gitignore.
**READY**
Probably not, unless CScope is used heavily in the LTS versions.
NO  
NO
```
find . -type f | egrep ".*(h|c|function)$" > cscope.files
cscope -bq -u -Iinclude
ls cscope* 
git status 
```
=> [minor] Added Cscope to .gitignore

.gitignore, Makefile
=> Backport 2.16: Add makefile target for cscope.out + .gitignore

.gitignore, Makefile
=> Backport 2.7: Add makefile target for cscope.out + .gitignore

Makefile
Add a target for `cscope.out` in `Makefile`, similar to the rules for `TAGS` and such. https://github.com/ARMmbed/mbedtls/pull/3844 adds the corresponding `.gitignore` line.
While I'm at it, update the list of source files.
Needs backports: for the cscope rule. The list of source files is up-to-date in the LTS branches.
=> Add makefile target for cscope.out

library/platform_util.c, library/threading.c
Fixes two typos where '20112L' is used instead of '200112L'.
**READY**
Yes
Only 2.16 contains this typo (#3879).
All credit goes to @gufe44 as originally contributed in #3645.
=> Fix _POSIX_C_SOURCE typos

library/platform_util.c, library/threading.c
Backport of #3877 fixing some simple typos.
=> Backport 2.16: Fix _POSIX_C_SOURCE typos

include/mbedtls/platform_util.h, library/platform_util.c
Update the documentation to mention that calling it with zero as an argument will result in an undefined behavior.
=> [baremetal] Move size checks outside of mbedtls_platform_random_in_range

library/ssl_tls.c
Fixes memoryleak when MBEDTLS_SSL_VARIABLE_BUFFER_LENGTH  is defined.
Fixes https://armiot.atlassian.net/browse/IOTPMI-2276, see ticket for more details.
When mbedtls_ssl_free is called, ssl->in_buf is freed but not set as null.
mbedtls_ssl_free continues to call mbedtls_ssl_handshake_free -> handle_buffer_resizing and now ssl->in_buf is not allocated but as it's not nulled it's resized and new buffer set to ssl->in_buf
Now next time mbedtls_ssl_setup is called it will alloc ssl->in_buf over the resized buffer.
**IN DEVELOPMENT
Yes
Which branch?
baremetal
NO
See Description.
=> Fix possible memory leak when MBEDTLS_SSL_VARIABLE_BUFFER_LENGTH defined

library/ccm.c
This PR adds buffer clearing on top of https://github.com/ARMmbed/mbedtls/pull/3840.
=> [baremetal] ccm - clean temp data

include/mbedtls/sha512.h
The sentence was placed in the wrong function's documentation in 27ff120a6121528de9f9a726dfd80a209ee05a1a.
A similar edit was made in `sha256.c` but the sentence was placed correctly there.
Backport: [2.16](https://github.com/ARMmbed/mbedtls/pull/3908), [2.7](https://github.com/ARMmbed/mbedtls/pull/3920)
=> Move "internal use" sentence attached to the wrong function

include/mbedtls/sha512.h
=> Backport 2.16: Move "internal use" sentence attached to the wrong function

include/mbedtls/sha512.h
Backport of https://github.com/ARMmbed/mbedtls/pull/3907
=> Backport 2.7: Move "internal use" sentence attached to the wrong function

Makefile
Uninstall psa header files which installed to DESTDIR.
Signed-off-by: Wu, Jheng-Jhong <goodwater.wu@gmail.com>
Signed-off-by: Victor Wu <victor_wu@bizlinktech.com>
Notes:
When installing mbedtls, psa headers install to DESTDIR, but it doesn't uninstall when doing uninstalling.
Therefore, add a line to uninstall psa header files which …
=> Remove psa header files in uninstall part

include/psa/crypto_compat.h
Due to a misplaced `#endif`, the (non-functional) macro definitions were not
properly removed from `crypto_compat.h` if `MBEDTLS_DEPRECATED_REMOVED` was
declared.
**READY**
No, PSA only
NO
=> Fix removal of deprecated PSA constants

docs/proposed/psa-driver-interface.md
* Fix copypasta in some entry point prototypes.
* Add an entry point for key validation. Fix #3617.
* Make transparent key import call an `import_key` entry point (and not just `validate_key` as initially requested), since it may require conversion of the representation.
* Add a `bits` argument to the `import_key` entry point, since the driver needs to determine the key size.
=> PSA unified driver specification: key validation and transparent key import

ChangeLog.d/bugfix_3782.txt, library/cmac.c, library/ssl_tls.c, programs/test/selftest.c, tests/suites/main_test.function
Backport of #3848 .
Extra changes:
* One declaration moved to comply with C90;
* The definition of `test_snprintf` was fixed in `main_test.function`, and not in `host_test.function` as done in the development branch.
=> Backport 2.7: Fix build failure on gcc-11

ChangeLog.d/bugfix_3782.txt, library/cmac.c, library/ssl_tls.c, programs/test/selftest.c, tests/suites/host_test.function
Backport of #3848 . One extra change was needed to comply with C90.
=> Backport 2.16: Fix build failure on gcc-11

ChangeLog.d/bugfix_3782.txt, library/cmac.c, library/ssl_tls.c, programs/test/selftest.c, tests/suites/host_test.function
Function prototypes changed to use array parameters instead of
pointers.
Signed-off-by: Rodrigo Dias Corrêa <rodrigo@correas.us>
Fixes #3782
**READY**
I don't know.
NO
=> Fix build failure on gcc-11

ChangeLog.d/missing-debug-message-arguments_mbedtls_ssl_decrypt_buf.txt, library/ssl_msg.c
Add missing values for a debug message in mbedtls_ssl_decrypt_buf
Found by [CodeQL](https://securitylab.github.com/tools/codeql)
**READY**
Yes (?), as this bug might leak 8 arbitrary bytes to the (debug) console.
Edit: No, as this was introduced only 7 months ago, so it is not part of 2.16 or 2.7
NO
=> Fix: Add missing arguments to debug message.

ChangeLog.d/bugfix-2927.txt, include/mbedtls/ctr_drbg.h, include/mbedtls/hmac_drbg.h, library/ctr_drbg.c, library/hmac_drbg.c, tests/suites/test_suite_ctr_drbg.function, tests/suites/test_suite_hmac_drbg.function
Fixes ARMmbed/mbedtls#2927
`mbedtls_hmac_drbg_seed()` and `mbedtls_ctr_drbg_seed()` were setting the entropy context `reseed_interval` to the default value of 10 000 even when `set_reseed_interval()` had been called prior to `seed()`. The documentation did not describe the API behaving this way, and it doesn't make sense that `seed()` would remove any prior preference for `reseed_interval` so this behavior has been fixed. Now, the value set by `set_reseed_interval()` will persist through after a call to `seed()`.
This change would break any application that
- set the `reseed_interval` and expected it to be reset to the default value once they called `seed()`
- set the `reseed_interval` and was unknowingly using the default value for the lifetime of the `DRBG` object
The first situation …
=> Support set *_drbg reseed interval before seed

ChangeLog.d/bugfix-2927.txt, include/mbedtls/ctr_drbg.h, include/mbedtls/hmac_drbg.h, library/ctr_drbg.c, library/hmac_drbg.c, tests/suites/test_suite_ctr_drbg.function, tests/suites/test_suite_hmac_drbg.function
=> Backport to Mbedtls 2.7: Support set *_drbg reseed interval before seed

ChangeLog.d/bugfix-2927.txt, include/mbedtls/ctr_drbg.h, include/mbedtls/hmac_drbg.h, library/ctr_drbg.c, library/hmac_drbg.c, tests/suites/test_suite_ctr_drbg.function, tests/suites/test_suite_hmac_drbg.function
=> Backport to Mbedtls 2.16:  Support set *_drbg reseed interval before seed

ChangeLog.d/clean_pem_buffers.txt, library/pem.c, tests/suites/test_suite_pkwrite.function, tests/suites/test_suite_x509write.function
In order to remove some big (4k) buffers from being created on the stack, the output buffer was re-used - in this case the raw der data is written to the buffer prior to being base64 encoded into an allocated buffer, and then overwritten with the pem data. However, even though the pem data is zero terminated, usually der data will remain in the buffer after the terminator.
Should this buffer get passed into mbedtls_x509_crt_parse() then it will likely fail to parse, as it decides whether or not a buffer is pem by checking the last byte of the buffer for being zero - if it isn't zero, it will attempt to parse as der, which will obviously fail.
This just ensures the buffer is cleaned to avoid the regression, there may be future work around this subject to make the area safer and tests to …
=> Remove Extraneous bytes from buffer post pem write

ChangeLog.d/clean_pem_buffers.txt, library/pem.c, tests/suites/test_suite_pkwrite.function, tests/suites/test_suite_x509write.function
In order to remove some big (4k) buffers from being created on the stack, the output buffer was re-used - in this case the raw der data is written to the buffer prior to being base64 encoded into an allocated buffer, and then overwritten with the pem data. However, even though the pem data is zero terminated, usually der data will remain in the buffer after the terminator.
Should this buffer get passed into mbedtls_x509_crt_parse() then it will likely fail to parse, as it decides whether or not a buffer is pem by checking the last byte of the buffer for being zero - if it isn't zero, it will attempt to parse as der, which will obviously fail.
This just ensures the buffer is cleaned to avoid the regression, there may be future work around this subject to make the area safer and tests to …
=> Backport 2.16: Remove Extraneous bytes from buffer post pem write

library/pem.c, tests/suites/test_suite_pkwrite.function, tests/suites/test_suite_x509write.function
In order to remove some big (4k) buffers from being created on the stack, the output buffer was re-used - in this case the raw der data is written to the buffer prior to being base64 encoded into an allocated buffer, and then overwritten with the pem data. However, even though the pem data is zero terminated, usually der data will remain in the buffer after the terminator.
Should this buffer get passed into mbedtls_x509_crt_parse() then it will likely fail to parse, as it decides whether or not a buffer is pem by checking the last byte of the buffer for being zero - if it isn't zero, it will attempt to parse as der, which will obviously fail.
Please note that although this bug does not affect this branch, I wanted to add the tests anyway, to ensure this regression did not happen again. In …
=> Backport 2.7: Add tests for buffer corruption after PEM write

tests/scripts/test_psa_constant_names.py
Documentation improvements suggested by @mpg in #3948
**READY**
No, PSA only
No, Documentation only.
=> Improve documentation in test_psa_constant_names.py

include/psa/crypto_types.h, include/psa/crypto_values.h
* Fix a mistake in the description of locations. This change is also being made in the spec draft.
* Replace specification language discussing possible implementations by documentation of Mbed TLS discussing possible integrations and omitting some things that don't apply to Mbed TLS.
Follow-up to https://github.com/ARMmbed/mbedtls/pull/3302. No behavior change, just documentation improvements.
=> Tweak documentation about lifetimes

CMakeLists.txt
Make sure that CMake policy CMP0012 is set to NEW, without which FindPython3 and FindPython2 functionality becomes broken with CMake 3.18.2 if searching by location. This will be fixed in CMake 3.18.3, however this policy will remain the default, so this is a safe change. Ensure CMP0011 is set to NEW to avoid warnings being issued about policy push / pop with CMake 3.18.0 or newer.
This closes #3690
**READY**
No (Newer version of FindPython3 not used in either LTS branch)
Project should now build with CMake version 3.18.2, which it won't without this patch.
=> Set CMake Max Version

ChangeLog.d/programs-ssl-use-after-scope.txt, programs/ssl/ssl_client2.c, programs/ssl/ssl_server2.c
This PR fixes a use-after-scope error in `programs/ssl/ssl_client2.c` and `programs/ssl/ssl_server2.c`.
**READY**
NO
NO
=> Fix use-after-scope error in programs/ssl

library/ssl_cli.c, library/ssl_tls.c, library/x509_crt.c
Add missing volatile keywords before several fi-related variables.
=> [baremetal] FI variables missing 'volatile'

library/ssl_tls.c
Previously, it was possible to access a null pointer even though the given configuration (with MBEDTLS_SSL_DTLS_CONNECTION_ID) should work.
=> [baremetal] Fix the usage of ssl context after its nullified

ChangeLog.d/psa_close_key_memory_leak_fix.txt, library/psa_crypto.c
Closing a wrapped key with the new SE driver interface while
MBEDTLS_PSA_CRYPTO_SE_C is also enabled leads to the key material not
being freed, even though an old SE driver is not in use, leading to a
memory leak. This is because a wrapped key is also considered external.
This commit extends the check for skipping by checking whether an
old-style SE driver is registered with the provided slot, in addition to
checking whether the key is external.
**READY**
NO  
NO
The following snippet reproduces the leak:
```C
#define PSA_KEY_LOCATION_SLI_SE_OPAQUE   ((psa_key_location_t)0x000001UL)
static void close_opaque_key_target(void)
{
psa_key_handle_t handle = 0;
psa_key_attributes_t attributes = PSA_KEY_ATTRIBUTES_INIT;
psa_set_key_algorithm(&attributes, 0);
psa_set_key_type( &attributes, …
```
=> PSA Crypto: Don't skip key data removal when SE driver is not in use

ChangeLog.d/rsa_private-ret.txt, library/rsa.c
`mbedtls_rsa_private()` could return the sum of two RSA error codes instead of a valid error code in some rare circumstances. Fix this.
There is no non-regression test because the circumstances are too hard to arrange in a unit test.
I found the bug while working on a bigger feature, so the fix for `development` is in the pull request for that feature: #3912.
=> Backport 2.16: Fix an incorrect error code if RSA private operation glitched

tests/ssl-opt.sh
One of the tests fairly consistently failed on the CI due to unreliable network, timeouting on client-side of recv.
Accodring to `mbedtls_ssl_conf_handshake_timeout` documentation:
```
* \note           The 'min' value should typically be slightly above the
*                 expected round-trip time to your peer, plus whatever time
*                 it takes for the peer to process the message. For example,
*                 if your RTT is about 600ms and you peer needs up to 1s to
*                 do the cryptographic operations in the handshake, then you
*                 should set 'min' slightly above 1600. Lower values of 'min'
*                 might cause spurious resends which waste network resources,
*                 while larger value of 'min' will increase overall latency
* …
```
=> [baremetal] fix spurious resend in one of the ssl-opt.sh tests.

include/mbedtls/check_config.h, include/mbedtls/config.h, include/mbedtls/ssl_internal.h, library/ssl_tls.c
This PR fixes #3534. 
The variable buffer sizes feature duplicated some code in two places, and had a missing hidden dependency - this PR addresses both of these issues.
As it is just a refactor, I believe that it doesn't need a changelog entry.
=> Refactor variable I/O buffers feature to reduce code duplication

tests/ssl-opt.sh
One of the tests fairly consistently failed on the CI due to unreliable network, timeouting on client-side of recv.
Accodring to mbedtls_ssl_conf_handshake_timeout documentation:
```
* \note           The 'min' value should typically be slightly above the
*                 expected round-trip time to your peer, plus whatever time
*                 it takes for the peer to process the message. For example,
*                 if your RTT is about 600ms and you peer needs up to 1s to
*                 do the cryptographic operations in the handshake, then you
*                 should set 'min' slightly above 1600. Lower values of 'min'
*                 might cause spurious resends which waste network resources,
*                 while larger value of 'min' will increase overall latency
* …
```
=> [baremetal] Further fixes - spurious resend in one of the ssl-opt.sh tests. 

library/aes.c
MBEDTLS_AES_128_BIT_MASKED configuration  improvements 
1. Skip local variables initialization to improve performance on restricted targets
2. Remove unneeded buffer cleanup in a loop 
**READY**
NO  
NO
=> Baremetal aes masking speedup

library/ecjpake.c
Backport of #4007 to mbed TLS 2.16 LTS
=> [backport 2.16] Skip known entropy tests for ECJPAKE ALT implementations

library/ecjpake.c
These implementations don't necessarily consume entropy the same way the mbed TLS internal software implementation does, and the 'reference handshake' test vectors can thus not be applied to an ALT implementation.
**READY**
NO  
NO
=> Don't self-test ECJPAKE ALT implementations against known entropy

programs/fuzz/CMakeLists.txt, programs/ssl/CMakeLists.txt, programs/test/CMakeLists.txt
In cmake version < 3.0, the SOURCES property on targets cannot be
modified after the target is defined.  There are several instances in
the code that were using `target_properties()`, which is not available
in the older versions of cmake.  Unfortunately, the workaround in #3801
(381c1078fc) assumes that this SOURCES property can be modified.
Work around this by building up any necessary sources before declaring
the target.  This is more awkward, but needed to continue to be able to
support the old versions of cmake.
Fixes #3788
Signed-off-by: David Brown <david.brown@linaro.org>
**READY**
Yes, but I don't think it applies.
NO
```bash
$ mkdir build
$ cd build
$ cmake-2.18.12.2 ..
$ make
```
=> cmake: Fix added sources to targets

programs/ssl/ssl_client2.c, programs/ssl/ssl_server2.c, programs/ssl/ssl_test_lib.c, programs/ssl/ssl_test_lib.h, tests/Makefile, tests/include/test/fake_external_rng_for_test.h, tests/include/test/helpers.h, tests/include/test/psa_crypto_helpers.h, tests/scripts/all.sh, tests/src/fake_external_rng_for_test.c, tests/src/psa_crypto_helpers.c, visualc/VS2010/mbedTLS.vcxproj
* Unify the RNG-related code of `ssl_client2` and `ssl_server2` into `ssl_test_lib`. This is a continuation of #3986.
* Add support for HMAC_DRBG in `ssl_test_lib`. Exercise the HMAC_DRBG support in `all.sh`.
* Do run SSL tests when HMAC_DRBG is disabled: this exercises non-deterministic ECDSA. This part does not depend on the rest and should be backported.
A follow-up will add support for the PSA external RNG in SSL test programs, fulfilling #3883.
=> Support HMAC_DRBG in SSL test programs

tests/scripts/all.sh
Do run SSL tests when HMAC_DRBG is disabled: this exercises non-deterministic ECDSA.
Partial backport of #4020.
=> Backport 2.16: Test SSL with non-deterministic ECDSA

ChangeLog.d/psa-crypto-rename-output-buffer-size-macros.txt, docs/getting_started.md, include/psa/crypto.h, include/psa/crypto_compat.h, include/psa/crypto_sizes.h, include/psa/crypto_values.h, library/psa_crypto.c, library/psa_crypto_driver_wrappers.c, programs/psa/crypto_examples.c, tests/suites/test_suite_psa_crypto.function, tests/suites/test_suite_psa_crypto_driver_wrappers.function, tests/suites/test_suite_psa_crypto_metadata.function, tests/suites/test_suite_psa_crypto_se_driver_hal.function
This PR contains only the renames of the buffer size macros.
The newly introduced macros are in #3386.
Fixes parts of #3268
=> Rename existing support macros for output buffer sizes for PSA Crypto API 1.0.0

library/ecdsa.c
=> [Backport 2.16] Avoid unreferenced items in ECDSA when ALT is in use

library/cmac.c
This is the same type of logic as was already applied in e.g. AES and GCM self tests. When the underlying primitive returns 'not supported' (either through the cipher interface or because there is an _ALT implementation), the relevant test is skipped instead of failing the selftest routine.
**READY**
NO  
NO
Covered by existing testing. _ALT interfaces are currently not generally tested, that would be outside the scope of this PR.
=> Allow CMAC self test to skip tests for unsupported primitives

library/psa_crypto.c, library/psa_crypto_slot_management.c, library/psa_crypto_storage.c, library/psa_crypto_storage.h, tests/suites/test_suite_psa_crypto_slot_management.data
This appears to be a bug related to handling how keys get loaded from storage. If the library is configured to include support for both the old-style SE interface and the new PSA driver interface, external keys wouldn't get loaded from storage.
I fixed a testing flaw related to external keys as well (probably an oversight during the openless changeover)
**READY**
NO  
NO
=> Allow loading external wrapped keys

ChangeLog.d/mpi_sub_abs.txt, library/bignum.c, tests/suites/test_suite_mpi.data
Fix a buffer overflow in `mbedtls_mpi_sub_abs()` when calculating |A| - |B| where |B| is larger than |A| and has more limbs (so the function should return `MBEDTLS_ERR_MPI_NEGATIVE_VALUE`).
This is a regression introduced in Mbed TLS 2.7.18. Fix #4042.
Backport of https://github.com/ARMmbed/mbedtls/pull/4096
=> Backport 2.7: Fix buffer overflow in mbedtls_mpi_sub_abs negative case

ChangeLog.d/mpi_sub_abs.txt, library/bignum.c, tests/suites/test_suite_mpi.data
Fix a buffer overflow in `mbedtls_mpi_sub_abs()` when calculating |A| - |B| where |B| is larger than |A| and has more limbs (so the function should return `MBEDTLS_ERR_MPI_NEGATIVE_VALUE`).
This is a regression introduced in Mbed TLS 2.16.9. Fix #4042.
Backport of https://github.com/ARMmbed/mbedtls/pull/4096
=> Backport 2.16: Fix buffer overflow in mbedtls_mpi_sub_abs negative case

ChangeLog.d/mpi_sub_abs.txt, library/bignum.c, tests/suites/test_suite_mpi.data
Fix a buffer overflow in `mbedtls_mpi_sub_abs()` when calculating |A| - |B| where |B| is larger than |A| and has more limbs (so the function should return `MBEDTLS_ERR_MPI_NEGATIVE_VALUE`).
This is a regression introduced in Mbed TLS 2.16.9. Fix #4042.
Backports: [2.16](https://github.com/ARMmbed/mbedtls/pull/4097), [2.7](https://github.com/ARMmbed/mbedtls/pull/4077).
=> Fix buffer overflow in mbedtls_mpi_sub_abs negative case

ChangeLog.d/issue4093.txt, library/pkwrite.c
This is a backport to the mbedtls v2.7 branch of PR #4094 regarding issue #4093
=> Backport 2.7: wrong RSA_PRV_DER_MAX_BYTES for odd MBEDTLS_MPI_MAX_SIZE

ChangeLog.d/issue4093.txt, library/pkwrite.c
This is a backport to the mbedtls v2.16 branch of PR #4094 regarding issue #4093
=> Backport 2.16: wrong RSA_PRV_DER_MAX_BYTES for odd MBEDTLS_MPI_MAX_SIZE

ChangeLog.d/issue4093.txt, library/pkwrite.c
This is the PR for issue #4093
It adds parenthesis to fix the computation of `RSA_PRV_DER_MAX_BYTES` and also adds parenthesis to other macros to make them safer to use.
=> wrong RSA_PRV_DER_MAX_BYTES for odd MBEDTLS_MPI_MAX_SIZE

tests/include/test/helpers.h, tests/src/helpers.c, tests/suites/helpers.function, tests/suites/host_test.function, tests/suites/main_test.function, tests/suites/target_test.function, tests/suites/test_suite_asn1parse.function, tests/suites/test_suite_asn1write.function, tests/suites/test_suite_psa_crypto.function, tests/suites/test_suite_psa_crypto_se_driver_hal.function, tests/suites/test_suite_ssl.function
This PR moves the test infrastructure code from `tests/suites/helpers.function` to `tests/src/helpers.c`. Specifically it makes `test_fail`, `test_set_step` and `test_skip` available via the testing API: `tests/include/test/helpers.h`. This allows other functions in the test infrastructure to access and use these functions while still maintaining the previous behaviour.
`test_info` and `test_result_t` are also currently made available via the API however this may change.
This PR partially implements the changes described in #4028.
**READY**
No
This PR is still very much a work in progress and I have not finalised a design for making these changes, I very much expect this design to change over time due to feedback from reviews.
=> Move test infrastructure from `tests/suites/helpers.function` into `tests/src/helpers.c`

include/psa/crypto_struct.h, library/psa_crypto.c
A minor bug I discovered while working on something else:
* Add a `PSA_` prefix to some identifiers that are declared publicly, but not meant for use in application code.
=> Fix some PSA-related identifiers

ChangeLog
**READY**
No, #3948, which introduced this mistake didn't affect any LTS branches.
None
As this is a documentation-only typo fix, one review should be enough.
=> Fix mistake in 2.25.0 Changelog

tests/suites/test_suite_ssl.function
In the error case build_transforms() was returning directly rather than jumping to cleanup, despite having allocated two buffers.
Found via Coverity analysis
**READY**
NO (Bug does not exist in 2.7 or 2.16 (new code was added)
NO
=> Fix for memory leak in ssl tests

include/mbedtls/pk.h, library/pkwrite.c
Partially implements #4033, where possible - add const attribute to public key api functions' parameters (in scope of 3.0 release).
**READY**
=> Add missing const attribute to Public Key API

include/mbedtls/asn1.h, library/asn1parse.c, tests/suites/test_suite_asn1parse.function
Partially implements #4033, where possible - add const attribute to asn1 api functions' parameters (in scope of 3.0 release).
**READY**
=> Add missing const attribute to asn1 api

tests/ssl-opt.sh
This used to be the case a long time ago but was accidentally broken.
After investigation (see PR comments), openssl and gnutls servers don't report success if we kill them after one connection. But `ssl_server2` does, and that's the important case where we want to detect errors. So this PR checks the return code of `ssl_server2` only.
Fix, for `ssl-opt.sh` only, #4103. Useful for https://github.com/ARMmbed/mbedtls/pull/4104.
Backports: #4134 #4135
=> ssl-opt.sh: if the server fails, do treat it as a test failure

tests/ssl-opt.sh
=> Backport 2.16: ssl-opt.sh: if the server fails, do treat it as a test failure

tests/ssl-opt.sh
=> Backport 2.7: ssl-opt.sh: if the server fails, do treat it as a test failure

include/mbedtls/asn1write.h, library/asn1write.c, tests/suites/test_suite_asn1write.function
Partially implements #4033, where possible - add const attribute to asn1write api functions' parameters (in scope of 3.0 release).
**READY**
=> Add missing const attribute to asn1write api

ChangeLog.d/fix_psa_crypto_leak.txt, library/psa_crypto.c
In psa_generate_derived_key_internal() an error case was returning directly rather than jumping to the exit label, which meant that an allocated buffer would not be free'd.
Found via coverity.
**READY**
NO  
(New code, bug does not exist in LTS branches)
NO
=> Fix memory leak in error case in psa_crypto

tests/suites/test_suite_psa_crypto.function
All compile-time switches on `PSA_WANT_` are constructed with `defined(...)`. There's one exception that was introduced in `test_suite_psa_crypto.function`, and it triggers a compiler error/warning when the symbol in question isn't defined (expands to `#if &&` which obviously isn't a valid preprocessor statement).
**READY**
NO  
NO
=> Fix a malformed define guard

ChangeLog.d/psa_allow_tweaking_library_configuration.txt, include/mbedtls/config.h, include/psa/crypto_extra.h, library/psa_crypto_slot_management.c, library/psa_crypto_slot_management.h, library/psa_crypto_storage.h, programs/test/query_config.c, tests/suites/test_suite_psa_crypto_slot_management.function
For an easy tweak to the static RAM usage of PSA Crypto on constrained devices, I'd like to add the capability to override `PSA_KEY_SLOT_COUNT` and `PSA_MAX_KEY_BITS`. These are both declared as 'compile time constants' and their usage suggests that they are meant to be tweaked, however, the library did not provide a way to do so yet.
**READY**
NO  
NO
Covered by existing tests when running the test suite with the overridden defines.
=> Allow tweaking PSA_KEY_SLOT_COUNT

tests/ssl-opt.sh
For calls to gnutls-serv where --priority is not specified, explicitly
add the default value: --priority=normal. This is needed for some tests
on Ubuntu 20.04 (gnutls-serv 3.6.13).
./ssl-opt.sh -f "DTLS fragmenting: gnutls server, DTLS 1.0"
=> ssl-opt.sh: add --priority=normal to gnutls-serv

tests/suites/test_suite_ccm.function
Check that the source address and the frame counter have the expected length. Otherwise, if the test data was invalid, the test code could build nonsensical inputs, potentially overflowing the iv buffer.
The primary benefit of this change is that it also silences a warning from compiling with `gcc-10 -O3` (observed with GCC 10.2.0 on Linux/amd64). GCC unrolled the loops and complained about a buffer overflow with warnings like:
```
suites/test_suite_ccm.function: In function 'test_mbedtls_ccm_star_auth_decrypt':
suites/test_suite_ccm.function:271:15: error: writing 1 byte into a region of size 0 [-Werror=stringop-overflow=]
271 |         iv[i] = source_address->x[i];
|         ~~~~~~^~~~~~~~~~~~~~~~~~~~~~
suites/test_suite_ccm.function:254:19: note: at offset [13, 14] to object 'iv' with …
```
=> Silence gcc-10 warning in test_suite_ccm

tests/suites/test_suite_ccm.function
Straightforward backport of #4126.
=> Backport 2.16: Silence gcc-10 warning in test_suite_ccm

docs/proposed/psa-conditional-inclusion-c.md
Give the rationale for why ECC curves deviate from the basic pattern. Fix a wrong example. Explain why FFDH groups have no symbols.
=> PSA conditional inclusion: add rationale about ECC curves and FFDH groups

programs/test/cpp_dummy_build.cpp
Part of build_default_make_gcc_and_cxx compares the list of headers
included by `programs/test/cpp_dummy_build.cpp` and the actual headers
present.  Add in the missing `mbedtls/psa_config.h` file to this list so
that this test passes.
**READY**
NO: This is for PSA config support
=> Add missing header to cpp_dummy_build.cpp test

library/psa_crypto.c
According to the doc: `retval = PSA_ERROR_NOT_SUPPORTED if alg is not supported`. 
**READY**
NO  
NO
=> Return NOT_SUPPORTED according to the API contract for psa_key_derivation_setup

tests/suites/test_suite_psa_crypto.function
Test cases `aead_encrypt` and `aead_decrypt` were changed in #4010 to allow ALT-implemented GCM to return `NOT_SUPPORTED` for AES-192 and/or non-12-byte GCM IVs.
There's a third test case (`aead_encrypt_decrypt`) where the same construct should apply, but was forgotten in the PR. This PR is thus a fixup for #4010.
**READY**
NO  
NO
=> Add missing test skip for ALT-implemented GCM (#4010 fix-up)

tests/scripts/all.sh
In component_test_no_hmac_drbg, the fact that HMAC_DRBG is disabled
doesn't affect the SSL code, but the fact that deterministic ECDSA is
disabled does. So run some ECDSA-related SSL tests.
Backport of #4021
=> Test SSL with non-deterministic ECDSA

ChangeLog.d/net_poll-fd_setsize.txt, include/mbedtls/net_sockets.h, library/net_sockets.c
Partial backport of the bug fix in #4173: 2.7 doesn't have `mbedtls_net_poll`, but it has `mbedtls_net_recv_timeout` which has the same bug. As with 2.16, I didn't backport the new tests because they're in a new test suite and there's a mild but nonzero concern about the test code's portability.
=> Backport 2.7: Fix stack corruption in mbedtls_net_poll with large file descriptor

ChangeLog.d/net_poll-fd_setsize.txt, include/mbedtls/net_sockets.h, library/net_sockets.c
Straightforward backport of the bug fix in #4173. I didn't backport the new tests because they're in a new test suite and there's a mild but nonzero concern about the test code's portability.
=> Backport 2.16: Fix stack corruption in mbedtls_net_poll with large file descriptor

ChangeLog.d/rsa_private-ret.txt, library/rsa.c
mbedtls_rsa_private() could return the sum of two RSA error codes
instead of a valid error code in some rare circumstances:
* If rsa_prepare_blinding() returned  MBEDTLS_ERR_RSA_RNG_FAILED
(indicating a misbehaving or misconfigured RNG).
* If the comparison with the public value failed (typically indicating
a glitch attack).
Make sure not to add two high-level error codes.
Signed-off-by: Gilles Peskine <Gilles.Peskine@arm.com>
This is a backport of #3988
=> Backport 2.7: Fix an incorrect error code if RSA private operation glitched

library/ecp.c
Applies the reasoning from #4008 to the flag implemented in #3992
**READY**
NO  (touchup for new feature)
NO
Not tested since the entirety of _ALT is untested.
=> Remove unreferenced static functions when ECP_NO_FALLBACK is used

ChangeLog.d/build-without-certs.txt, programs/ssl/ssl_client2.c, programs/ssl/ssl_server2.c
Fixes #4206
Build of the 2.7 branch fails when MBEDTLS_CERTS_C is disabled.
This only happens with the 2.7 LTS versions. Not affected: 2.16.6 LTS, 2.25.0, development and master, as far as I tested.
Reason: Caused by wrongfully placed closing brackets between #ifdef's, copy & paste hell unleashed ;-)
Origin: The bug was introduced in PR #2498
**READY**
NO / This problem only applies to the `mbedtls-2.7` branch.
NO
=> Fix build of 2.7 with MBEDTLS_CERTS_C disabled in config (fixes #4206)

ChangeLog.d/fix_memsan_build_clang11.txt, library/x509_crt.c
X509_crt.c, line 1616
```
struct stat sb;
...
while( ( entry = readdir( dir ) ) != NULL )
{
snp_ret = mbedtls_snprintf( entry_name, sizeof entry_name,
"%s/%s", path, entry->d_name );
if( snp_ret < 0 || (size_t)snp_ret >= sizeof entry_name )
{
ret = MBEDTLS_ERR_X509_BUFFER_TOO_SMALL;
goto cleanup;
}
else if( stat( entry_name, &sb ) == -1 )
{
ret = MBEDTLS_ERR_X509_FILE_IO_ERROR;
goto cleanup;
}
if( !S_ISREG( sb.st_mode ) )
continue;
```
With Clang 11 The above use of S_ISREG is marked as acting on uninitialised data. 
The man page says:
> Unless otherwise specified, the structure members st_mode, st_ino, st_dev, st_uid, st_gid, st_atime, st_ctime, and st_mtime shall have meaningful values for all file types defined in this volume of IEEE Std 1003.1-2001. The value of the member st_nlink …
=> Fix memsan build with Clang 11

include/psa/crypto_sizes.h
Both the original change, and its incomplete revert were introduced in #3386.
**READY**
No, PSA only.
No
=> Fix revert of PSA_AEAD_UPDATE_OUTPUT_SIZE

include/psa/crypto.h, include/psa/crypto_compat.h, include/psa/crypto_se_driver.h, include/psa/crypto_sizes.h, include/psa/crypto_values.h
Fix places in `include/psa/*.h` where Doxygen documentation uses `\p` to refer to a parameter name and where the name used did not match the actual parameter name.
Fix, for `include/psa` only, https://github.com/ARMmbed/mbedtls/issues/4209.
=> Fix parameter names after \p in include/psa

ChangeLog.d/dtls_sample_use_read_timeout.txt, programs/ssl/dtls_client.c, programs/ssl/dtls_server.c
Backport of #4075.
`programs/ssl/dtls_client.c` and `programs/ssl/dtls_server.c` each contain a `#define READ_TIMEOUT_MS` that was previously used to specify the read timeout. Since 97fd52c529e293f98674f313fb2da9a9f8b85fbc, those defines have been useless / not serving their intended purpose. This PR makes those defines serve their purpose again.
=> 2.16: Actually use the READ_TIMEOUT_MS in the example DTLS client and server

ChangeLog.d/dtls_sample_use_read_timeout.txt, programs/ssl/dtls_client.c, programs/ssl/dtls_server.c
`programs/ssl/dtls_client.c` and `programs/ssl/dtls_server.c` each contain a `#define READ_TIMEOUT_MS` that was previously used to specify the read timeout. Since 97fd52c529e293f98674f313fb2da9a9f8b85fbc, those defines have been useless / not serving their intended purpose. This PR makes those defines serve their purpose again.
**READY**
~I don't know~ Yes
NO
=> Actually use the READ_TIMEOUT_MS in the example DTLS client and server

ChangeLog.d/make_assemble_changelog_enforce_line_length.txt, scripts/assemble_changelog.py
As I descovered the hard way, a changelog entry with a line length greater than 80 characters would still pass CI, although technically being invalid. This is a quick change to the script to make it detect these descrepancies and fail them.
**READY**
YES
NO
scripts/assemble_changelog.py should now enforce the 80 character line length limit
=> Make assemble changelog script enforce line length

include/mbedtls/config_psa.h, include/psa/crypto_config.h, library/psa_crypto.c, tests/ssl-opt.sh
[Curve448](https://github.com/ARMmbed/mbedtls/issues/4249) and [secp224k1](https://github.com/ARMmbed/mbedtls/issues/3541) currently don't work through the PSA crypto API. Don't enable them in the configuration.
Urgent because CI broke due to the combination of https://github.com/ARMmbed/mbedtls/pull/4214 (adding systematically generated test cases for all curves including these, but the test cases didn't run because the dependency symbols weren't declared) and https://github.com/ARMmbed/mbedtls/pull/4158 (adding the dependency symbols for all curves including these).
=> PSA: don't run tests for unsupported curves

tests/suites/test_suite_psa_crypto.function
Fix likely harmless undefined behavior in cipher tests pointed out by UBSan with recent Clang. When the complete output is empty, the output buffer is NULL. Adding an integer to a null pointer is undefined behavior even when the integer is 0, so make a special case for that.
This fixes `make test CC=clang-10 CFLAGS="-fsanitize=address,undefined -fno-sanitize-recover=all -fno-common"`.
=> Fix NULL+0 in test code

library/ssl_srv.c
remove ssl_parse_client_hello redundant conditions
ext_len is unsigned and the loop over the extensions checks
```
while( ext_len != 0 )
{
if ( ext_len < 4 ) {
```
so additional checks are redundant.
**READY**
NO  
NO
=> remove ssl_parse_client_hello redundant conditions

Makefile
tests/suites/helpers.function and tests/suites/*_test.function contain "#line" directives. This causes the TAGS file to contain references pointing to the file path named in the "#line" directives, which is relative to the "tests" directory rather than to the toplevel. Fix this by telling etags to ignore "#line" directives, which is ok since we aren't actually running it on any generated code.
=> TAGS: Fix lookup in test/suites/!(test_suite_*).function

include/mbedtls/psa_util.h
Clang 11 has stopped using the old comment system (/* fallthrough */ on the line before) to mark deliberate fallthrough, and now demands marking of such with  __attribute(fallthrough). Given not every compiler supports such attributes and these are the only two deliberate fallthrough cases in the project at the minute, take the easy route and just remove the fallthrough.
**READY**
No: the affected files are not present in any LTS.
NO
Build PSA enabled build with clang 11
=> Remove deliberate fallthrough

.github/issue_template.md, BRANCHES.md, BUGS.md, CONTRIBUTING.md, README.md, SECURITY.md, SUPPORT.md
Currently it's a bit hard for a user or contributor coming to the project on github to discover some basic information such as:
- how to report security bugs (is on the tf.org wiki, which itself was not linked anywhere from the source tree)
- what branches are currently maintained
This PR tries to improve the situation by adding a few files with explicit names (some recognized by github) and cross-referencing with existing documents.
Some of this information is version-independent and arguably should be maintained out-of-tree. However I'm adding them here without waiting for our version-independent docs repo to be ready, in the spirit of incremental improvement: I believe this PR is a strict improvement over the status quo and that it does not make future improvements harder. (When the …
=> Improve the visibility of some informations

library/bignum.c, library/ecp_curves.c, programs/test/benchmark.c
Results from https://github.com/ARMmbed/mbedtls/pull/3511 show that the ECP code is where the library is at it worst when it comes to calls to `calloc()`. The goal of this PR is to make a few easy improvements.
I think there are more low-hanging fruit, but there's already a significant reduction in the number of allocations (~halved the allocations in `test_suite_ecp`). Some of the improvements result in a performance improvements, others have no measurable impact on performance. The code size is almost unchanged.
Also:
* `mbedtls_ecp_curve_list()` now lists Montgomery curves. This was done in https://github.com/ARMmbed/mbed-crypto/pull/140 but accidentally reverted in the same PR.
* The benchmark program can now run on a single curve.
An earlier version of this PR included a framework …
=> Reduce the number of allocations in ECP operations

tests/ssl-opt.sh
Backport of #3615. Some chunks are omitted because they change code that didn't exist in 2.16, other than that this is a straightforward backport.
=> Backport 2.16: Speed up ssl-opt.sh when running a small number of test cases

docs/architecture/testing/invasive-testing.md
Remove a missed reference to deprecated (now removed in 3.0 branch) internal header files as `include/mbedtls/*_internal.h`. 
Follow up from https://github.com/ARMmbed/mbedtls/pull/4164#issuecomment-811712160.
**READY**
=> Remove missing reference

tests/scripts/check-names.sh
check-names.sh works fine with GNU and with modern FreeBSD grep
so remove the check for GNU grep.
Backport of #4308
=> Make check-names.sh accept any grep

tests/scripts/check-names.sh
check-names.sh works fine with the version of FreeBSD grep used on OS X,
so permit this to be used.
=> Forwardport 3.0: Make check-names.sh accept FreeBSD grep

tests/scripts/check-names.sh
check-names.sh works fine with GNU and with modern FreeBSD grep
so remove the check for GNU grep.
Backport of #4308.
=> Backport 2.16: Make check-names.sh accept any grep

library/mps_common.h, library/mps_reader.c, library/mps_trace.c, library/mps_trace.h, tests/scripts/list-enum-consts.pl
Capitalise the MPS trace macros, as per the coding style (and make a slight
change to naming convention to avoid a name collision).
NO  
NO
=> Capitalise MPS trace macros

include/psa/crypto.h
Fix reference to deprecated macro in documentation
The reference was introduced in #4174.
**READY**
No, PSA only
=> Fix reference to deprecated macro in documentation

doxygen/mbedtls.doxyfile
A tiny follow-up to #4164 that I noticed while reviewing something else.
=> [3.0] Remove obsolete reference to internal headers under include/

ChangeLog.d/make_assemble_changelog_enforce_line_length.txt, scripts/assemble_changelog.py
Straightforward backport of #4202.
=> Backport 2.16: Make assemble changelog script enforce line length

ChangeLog.d/mpi_read_negative_zero.txt
Since #4297, `mbedtls_mpi_read_string("-0")` no longer produces a "negative zero". I hadn't realize that this edge case had changed. The timeline:
* Mbed TLS releases up to 2.26.0, before https://github.com/ARMmbed/mbedtls/pull/3512: `"-01"` parses as -1, `"-0"` parses as -0 which is not fully supported.
* Between https://github.com/ARMmbed/mbedtls/pull/3512 and https://github.com/ARMmbed/mbedtls/pull/4297 (never released): `"-01"` parses as an invalid MPI which is almost 1 but has the sign bit set to 0 which breaks a few functions.
* After https://github.com/ARMmbed/mbedtls/pull/4297: `"-01"` parses as -1, `"-0"` parses as 0 (same as `"0"`).
Since this is a behavior change, document it in the changelog. It has been backported in https://github.com/ARMmbed/mbedtls/pull/4322.
=> Changelog entry for mbedtls_mpi_read_string("-0")

configs/config-psa-crypto.h, include/mbedtls/config.h, include/mbedtls/ssl.h, programs/test/query_config.c
Removes a long unused config option.
Fixes #4321.
**READY**
NO  
This change is for Mbed TLS 3.0 and contains API changes.
=> Remove MBEDTLS_SSL_DEFAULT_TICKET_LIFETIME

ChangeLog.d/issue4280.txt, include/mbedtls/md.h, include/mbedtls/md2.h, include/mbedtls/md4.h, include/mbedtls/md5.h, include/mbedtls/ripemd160.h, include/mbedtls/sha1.h, include/mbedtls/sha256.h, include/mbedtls/sha512.h, library/error.c, library/md.c, library/md2.c, library/md4.c, library/md5.c, library/psa_crypto.c, library/ripemd160.c, library/sha1.c, library/sha256.c, library/sha512.c
Signed-off-by: TRodziewicz <tomasz.rodziewicz@mobica.com>
Remove the functions that are currently marked as \\deprecated from the hashing modules, namely: md, md2, md4, md5, ripemd160, sha1, sha256, sha512.
Fix: #4280 
READY
NO  
=> Remove deprecated things from hashing modules

scripts/assemble_changelog.py
Sometimes it's useful to use a URL in the changelog entry. However - splitting the URL into multiple lines would force
the user to "recreate" the URL instead of simply following the hyper-link.
It is common for the URL to be longer the 80 characters.
This PR adds an exception from the 80 char limit for URLs.
=> Allow changelog entries to have URLs exceeding 80 char limit.

scripts/assemble_changelog.py
=> Backport 2.16: Allow changelog entries to have URLs exceeding 80 char limit.

ChangeLog.d/issue4280.txt, include/mbedtls/md.h, include/mbedtls/md2.h, include/mbedtls/md4.h, include/mbedtls/md5.h, include/mbedtls/ripemd160.h, include/mbedtls/sha1.h, include/mbedtls/sha256.h, include/mbedtls/sha512.h, library/error.c, library/md.c, library/md2.c, library/md4.c, library/md5.c, library/psa_crypto.c, library/ripemd160.c, library/sha1.c, library/sha256.c, library/sha512.c
Revert #4334 that was incorrectly merged in development instead of development_3.0.
=> Revert 4334 from development

docs/architecture/psa-crypto-implementation-structure.md
Just a tiny typo in the architecture docs :)
=> Fix typo in architecture docs

include/mbedtls/check_config.h, tests/scripts/check-names.sh
If the compile-time configuration enables an option that was removed in Mbed TLS 3.0, and the effect of removing the option would likely not be detected at build time, `#error` out in `check_config.h`.
I didn't add `#error` clauses if the use of the feature would be detected at compile time. For example, if an application uses the test certificates that were formerly enabled by `MBEDTLS_CERTS_C`, it will fail to link, so no extra error detection is necessary.
=> Error on removed options

ChangeLog.d/issue4280.txt, include/mbedtls/md.h, include/mbedtls/md2.h, include/mbedtls/md4.h, include/mbedtls/md5.h, include/mbedtls/ripemd160.h, include/mbedtls/sha1.h, include/mbedtls/sha256.h, include/mbedtls/sha512.h, library/error.c, library/md.c, library/md2.c, library/md4.c, library/md5.c, library/psa_crypto.c, library/ripemd160.c, library/sha1.c, library/sha256.c, library/sha512.c
#4334 was merged in development instead of development_3.0 by mistake, this is a revival of it now targeting the correct branch :)
I rebased the over development_3.0 but kept the same commit structure, in order to make it easy to check that this indeed equivalent to the original using something like `git range-diff development..public/pr/4334 development_3.0..public/pr/4349` (after checking that the command is correct and adapting names to your local setup).
Fixes #4280
=> Apply 4334 to development-3.0

scripts/config.pl
The baremetal configuration is, among other things, our default reference point for code size measurements. So disable debugging features that would not be enabled in production where code size is limited. In particular, this shrinks the core SSL modules by about half. Keep debugging features that are solely in their own modules (MBEDTLS_ERROR_C, MBEDTLS_VERSION_FEATURES) since it's easy to filter them out.
Backport of https://github.com/ARMmbed/mbedtls/pull/4358
=> Backport 2.16: Disable debugging features in baremetal

ChangeLog.d/add-missing-parenthesis.txt, library/ecp.c
=> [backport 2.x] Add missing parenthesis when MBEDTLS_ECP_NORMALIZE_MXZ_ALT is declared

ChangeLog.d/add-missing-parenthesis.txt, library/ecp.c
As reported in, and fixes #4217
**READY**
Part of the _ALT interface, and therefore not tested.
=> Add missing parenthesis when MBEDTLS_ECP_NORMALIZE_MXZ_ALT is declared

ChangeLog.d/add-missing-parenthesis.txt, library/ecp.c
=> [backport 2.16] Add missing parenthesis when MBEDTLS_ECP_NORMALIZE_MXZ_ALT is declared

ChangeLog.d/fix-pk-parse-key-error-code.txt, library/pkparse.c
Just a minor bug fix which was discovered and fixed in #4006.
=> Backport 2.16: Add macro to check error code additions/combinations

ChangeLog.d/allow_alt_cmac_without_des.txt, include/mbedtls/cmac.h, include/mbedtls/config.h, library/cmac.c
Follow-up / extension of PR #3994, this time for 3DES.
If CMAC is overridden with an alternative / hardware implementation (`MBEDTLS_CMAC_ALT`), it's not a given that the hardware is able to support 3DES operations, even though `MBEDTLS_DES_C` might still be turned on (since it's in the default configuration).
**READY**
NO  
NO
=> Allow CMAC self-test to skip tests for unsupported primitives (2)

ChangeLog.d/allow_alt_cmac_without_des.txt, include/mbedtls/cmac.h, include/mbedtls/config.h, library/cmac.c
Backport of #4146, which was approved by @gilles-peskine-arm and @ronald-cron-arm 
**READY**
NO
Clean rebase of #4146 on top of development_2.x
=> [Backport 2.x] Allow CMAC_ALT implementations to not support 3DES

library/ssl_msg.c
The field `cur_out_ctr` in the SSL context keeps track of the record sequence number for the next outgoing record.
For TLS, this sequence number is implicit and not transmitted on the wire, while for DTLS, it's part of of the record header.
For DTLS, the position of the record sequence number of the next outgoing record in that record's header is tracked in the pointer `out_ctr`. This pointer moves forward along with other pointers such as `out_hdr` or `out_msg` within the outgoing data buffer `out_buf` as multiple records are written in the same datagram.
For TLS, the `out_ctr` pointer is logically superfluous, but for some reason, we're still maintaining it by having it point
to the 8 Bytes prior to the header of the next outgoing record, and always copying `cur_out_ctr` to this …
=> Keep pointer to TLS record sequence number static

ChangeLog, ChangeLog.d/rm-ticket-lifetime-option, docs/3.0-migration-guide.d/00README, docs/3.0-migration-guide.md
Resolve #4287 
Sources used:
- `git diff development..development_3.0 ChangeLog.d`
- `git log --abbrev-commit --pretty=oneline --merges development..development_3.0` to double-check for missing ChangeLog entries (found only one)
=> Migration guide for 3.0

library/ssl_msg.c
Handling the receipt of a handshake record after the initial handshake requires non-trivial logic depending on the protocol version and the endpoint. This logic is currently embedded in `mbedtls_ssl_read()`.
With the introduction of support for [D]TLS 1.3, the logic will become even more complex, since [D]TLS 1.3 drops support for renegotiation -- which in [D]TLS 1.2 is the main purpose of post-handshake handshake messages -- but instead introduces numerous other post-handshake handshake messages.
In order to pave the way for those changes, this PR improves readability and maintainability of `mbedtls_ssl_read()` by moving the TLS <=1.2 logic for handling post-handshake handshake messages into a separate helper function 
`ssl_handle_hs_message_post_handshake()`.
The logic of the code …
=> Introduce helper for handling of post-handshake handshake messages in TLS <=1.2

ChangeLog.d/posix-define.txt, library/net_sockets.c
Zephyr's native posix port define _POSIX_C_SOURCE with a higher value
during the build, so when mbedTLS defines it with a different value
breaks the build.
As Zephyr is already defining a higher value is guaranteed that mbedTLS
required features will be available. So, just define it in case it was
not defined before.
[taken from Zephyr mbedtls module:
https://github.com/zephyrproject-rtos/mbedtls/commit/76dcd6eecae4c1b556a52b1b9ef66e75fc538bc5]
Signed-off-by: Flavio Ceolin <flavio.ceolin@intel.com>
Signed-off-by: David Brown <david.brown@linaro.org>
**READY**
Yes: 2.16, 2.26
NO
=> Check if feature macro is defined before define it

include/mbedtls/config.h, include/mbedtls/ecp.h, include/mbedtls/error.h, include/mbedtls/ssl.h, include/mbedtls/ssl_ticket.h, include/psa/crypto_compat.h, include/psa/crypto_se_driver.h
The applicable parts of #4473.
=> Backport 2.x: Fix typos in C header files

include/mbedtls/config.h, include/mbedtls/ssl_ticket.h
The applicable parts of #4473.
=> Backport 2.16: Fix typos in C header files

include/mbedtls/config.h, include/mbedtls/ecp.h, include/mbedtls/error.h, include/mbedtls/ssl.h, include/mbedtls/ssl_ticket.h, include/psa/crypto_compat.h, include/psa/crypto_se_driver.h
This commit fixes a few typos in the `include` directory.
=> Fix typos in C header files

ChangeLog.d/ssl-error-code-cleanup.txt, docs/3.0-migration-guide.d/ssl-error-code-cleanup.md, include/mbedtls/error.h, include/mbedtls/ssl.h, library/error.c, library/ssl_tls.c
__Context:__ This PR continues #4446 in pursuit of cleaning up the SSL error code space for Mbed TLS 3.0.
__Dependency:__ Based on #4446.
__This PR:__
* Replaces the single use of `MBEDTLS_ERR_SSL_CERTIFICATE_REQUIRED` by `MBEDTLS_ERR_SSL_INTERNAL_ERROR` (https://github.com/ARMmbed/mbedtls/commit/9cfe6e977d14bdc56f80e6f06a757ca7ccd42da2) and removes `MBEDTLS_ERR_SSL_CERTIFICATE_REQUIRED` (https://github.com/ARMmbed/mbedtls/commit/3268d84313e16297b4f21ab251d5c5436e72d04c)
* Removes internal-only uses of `MBEDTLS_ERR_SSL_INVALID_VERIFY_HASH` (https://github.com/ARMmbed/mbedtls/commit/6c780469609da63915ec9930efb2a8ee0985799c) and removes the latter from the public error space (https://github.com/ARMmbed/mbedtls/commit/56ee9e5f141bb5cf3d0468fa09b6de7f5b19daf6).
* Replaces the single use of …
=> Avoid and remove some SSL error codes for Mbed TLS 3.0

include/mbedtls/error.h, include/mbedtls/ssl.h, library/error.c
The following SSL error codes are not used anywhere within the library:
* `MBEDTLS_ERR_SSL_UNKNOWN_CIPHER`
* `MBEDTLS_ERR_SSL_PEER_VERIFY_FAILED`
This PR removes them from the public API for Mbed TLS 3.0.
__Note:__ `MBEDTLS_ERR_SSL_PEER_VERIFY_FAILED` being unused comes as a surprise, at is seems to be reasonable to report it to the user upon peer CRT verification failure. However, this study (can potentially re-introduction of the code) can be left for 3.x, while the error code removal can only happen in 3.0.
=> Remove two unused SSL error codes for Mbed TLS 3.0

ChangeLog.d/posix-define.txt, library/net_sockets.c
=> Backport 2.x: Check if feature macro is defined before define it

ChangeLog.d/posix-define.txt, library/net_sockets.c
=> Backport 2.16: Check if feature macro is defined before define it

ChangeLog.d/remove-max-content-len.txt, configs/config-ccm-psk-tls1_2.h, configs/config-suite-b.h, docs/3.0-migration-guide.d/remove-max-content-len.md, include/mbedtls/config.h, include/mbedtls/ssl.h, library/ssl_misc.h, library/ssl_tls.c, programs/ssl/ssl_server2.c, programs/test/query_config.c, tests/ssl-opt.sh
Signed-off-by: David Horstmann <david.horstmann@arm.com>
Removes the MBEDTLS_SSL_MAX_CONTENT_LEN option from config.h
[added by mpg] Fixes #4362 
NO  
Which branch?
NO
=> Remove MBEDTLS_SSL_MAX_CONTENT_LEN option

ChangeLog.d/make-generate-tests-python.txt, tests/Makefile, tests/scripts/all.sh, tests/scripts/generate_test_code.py
Backport of https://github.com/ARMmbed/mbedtls/pull/4393.
Since 2.16 is a long-time support branch, I think that it's ok to change our scripts to default to Python 3, but we should ensure that the code remains compatible with Python 2. So I've added a CI check (which means we need to keep Python 2 on the CI). Compared to 2.x/3.0, I also tweaked the changelog entry to say that Python 2 still works.
=> Generate tests python3 make 2.16

ChangeLog.d/make-generate-tests-python.txt, programs/fuzz/Makefile, tests/Makefile
Python 2 is no longer officially supported, but we were still using it to generate test suite .c files from .function files when using GNU make. Switch to looking for Python 3.
This change was done for CMake a long time ago.
Backports: [2.x](https://github.com/ARMmbed/mbedtls/pull/4460), [2.16](https://github.com/ARMmbed/mbedtls/pull/4461)
=> Use Python 3 instead of Python 2 to generate test files

ChangeLog.d/make-generate-tests-python.txt, programs/fuzz/Makefile, tests/Makefile
Identical patch to https://github.com/ARMmbed/mbedtls/pull/4393
=> Backport 2.x: Use Python 3 instead of Python 2 to generate test files

ChangeLog.d/psa_sign_message.txt
We forgot a changelog entry in #4510 (`psa_sign_message`). Forward-port of #4525.
=> Add changelog entry for #4510

ChangeLog.d/psa_sign_message.txt
We forgot a changelog entry in #4357 (`psa_sign_message`). Forward-ported in #4526.
=> Backport 2.x: Add changelog entry for #4357

ChangeLog.d/sha512-output-type.txt, docs/3.0-migration-guide.d/sha512-output-type.md, include/mbedtls/sha256.h, include/mbedtls/sha512.h, library/sha256.c, library/sha512.c, library/ssl_tls.c
This is the critical part of https://github.com/ARMmbed/mbedtls/issues/4452, fixing https://github.com/ARMmbed/mbedtls/issues/4130 in a clean way.
The SHA512 part is important because the array parameter broke our build with GCC-11. The SHA256 part is less important because SHA-224 is very rarely used and the extra cost is 4 extra bytes, but it could hurt with code that systematically calculates each hash into a tight-sized buffer.
I had a quick look at other functions with array parameters and I didn't spot others where the array size is not always correct. While I think that it is best to avoid array parameters, there would not be much benefit in changing the existing APIs, so I don't think it's worth expending the limited time we have for 3.0 on that.
=> Change sha256 and sha512 output type from an array to a pointer

library/padlock.h
Fix a slight inaccuracy in the docs for the return value of
mbedtls_padlock_has_support.
Backports: [2.x](https://github.com/ARMmbed/mbedtls/pull/4537), [2.16](https://github.com/ARMmbed/mbedtls/pull/4540)
=> Fix docs for mbedtls_padlock_has_support

include/mbedtls/padlock.h
Fix a slight inaccuracy in the docs for the return value of
mbedtls_padlock_has_support.
Backport of #4536
=> Fix docs for mbedtls_padlock_has_support: 2.16 backport

include/mbedtls/padlock.h
=> 2.x backport: Fix docs for mbedtls_padlock_has_support

docs/proposed/psa-driver-interface.md, tests/suites/test_suite_psa_crypto_entropy.function
Deprecated constants should only be used to test them specifically.
Remove a few stragglers.
I used the following command to find problematic occurrences:
```
sed -nE 's/^#define (\w+).*/\1/p' include/psa/crypto_compat.h | grep -vx PSA_KEY_HANDLE_INIT | git grep -wF -f - '*' ':!ChangeLog*' ':!include/psa/crypto_compat.h'
```
The remaining occurrences in `tests/suites/test_suite_psa_crypto.function` are legitimate: they are testing the deprecated constants themselves.
=> [2.x only] Remove some remaining uses of deprecated constants

library/x509_crt.c
mbed-os doesn't provide `dirent.h`; replace it with `mbed_retarget.h` in case MBEDTLS_FS_IO is defined
Part of https://github.com/ARMmbed/mbed-os/pull/13863.
Fixes https://github.com/ARMmbed/mbed-os/pull/13863/files#r601617986
=> mbed-os: allow storing certificates in filesystem

library/ecdsa.c, library/ssl_tls.c, library/x509write_crt.c, library/x509write_csr.c, programs/test/udp_proxy.c, tests/suites/test_suite_ssl.function
Successfully compile with gcc11
**READY**
NO  
NO
$ gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/libexec/gcc/x86_64-redhat-linux/11/lto-wrapper
OFFLOAD_TARGET_NAMES=nvptx-none
OFFLOAD_TARGET_DEFAULT=1
Target: x86_64-redhat-linux
Configured with: ../configure --enable-bootstrap --enable-languages=c,c++,fortran,objc,obj-c++,ada,go,d,lto --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=http://bugzilla.redhat.com/bugzilla --enable-shared --enable-threads=posix --enable-checking=release --enable-multilib --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-linker-build-id --with-gcc-major-version-only --with-linker-hash-style=gnu --enable-plugin --enable-initfini-array …
=> Backport 2.x: build with gcc11

library/ecdsa.c, library/x509write_crt.c, library/x509write_csr.c, programs/test/udp_proxy.c, tests/suites/test_suite_ssl.function
Successfully compile with gcc11
**READY**
2.x: #4493; 2.16: #4498
NO
$ gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/libexec/gcc/x86_64-redhat-linux/11/lto-wrapper
OFFLOAD_TARGET_NAMES=nvptx-none
OFFLOAD_TARGET_DEFAULT=1
Target: x86_64-redhat-linux
Configured with: ../configure --enable-bootstrap --enable-languages=c,c++,fortran,objc,obj-c++,ada,go,d,lto --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=http://bugzilla.redhat.com/bugzilla --enable-shared --enable-threads=posix --enable-checking=release --enable-multilib --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-linker-build-id --with-gcc-major-version-only --with-linker-hash-style=gnu --enable-plugin …
=> build with gcc11

ChangeLog.d/undefined_reference_without_psa.txt, library/psa_crypto_driver_wrappers.c
Fix #4411.
Description and 2.x backport: https://github.com/ARMmbed/mbedtls/pull/4412
=> Fix missing compilation guard around psa_crypto_driver_wrappers.c

ChangeLog.d/undefined_reference_without_psa.txt, library/psa_crypto_driver_wrappers.c
Fix #4411.
No non-regression because I'd like a discussion on how to do it. Replace some/most static builds by shared builds? Do both a static and a shared build? I filed the wish for testing at https://github.com/ARMmbed/mbedtls/issues/4545.
[3.0 version](https://github.com/ARMmbed/mbedtls/pull/4543)
=> Backport 2.x: Fix missing compilation guard around psa_crypto_driver_wrappers.c

ChangeLog.d/session-cache.txt, library/ssl_cache.c, library/ssl_srv.c
This is the backport of the robustness improvement https://github.com/ARMmbed/mbedtls/pull/4347/commits/64ce9741800526fcf62151245f61af10bf269a1e plus later fixes from #4347 to `development_2.x`.
=> Backport 2.x: Add session ID as an explicit parameter to SSL session cache API

ChangeLog.d/fix-mingw-build.txt, include/mbedtls/debug.h
Signed-off-by: eugene <eugene.kobyakov@netfoundry.io>
Fixed build failure with MinGW toolchain
READY
NO. the build has been broken since 2.26.0 but had no reports
NO
build with mingw toolchain
=> Backport 2.x : Use proper formatting macros when using MinGW provided stdio

ChangeLog.d/fix-mingw-build.txt, include/mbedtls/debug.h
use proper formatting macros when using MinGW provided stdio
READY
Yes
development_2.x PR: https://github.com/ARMmbed/mbedtls/pull/4491
NO
=> Use proper formatting macros when using MinGW provided stdio

tests/compat.sh, tests/ssl-opt.sh
=> Backport 2.16: Fix SSL tests scripts with recent OpenSSL server with Diffie-Hellman

tests/compat.sh, tests/ssl-opt.sh
`compat.sh` and `ssl-opt.sh` don't work with a modern OpenSSL (e.g. the system one on Ubuntu 20.04) because they force the use of a small DH prime. We do this for compatibility with ancient versions of OpenSSL which we still use for legacy features. Only do it for those ancient versions, not for modern versions. This way you can run the SSL test scripts with the system version of OpenSSL on a modern system (barring other issues which I haven't checked).
Back/forward ports: [2.16](https://github.com/ARMmbed/mbedtls/pull/4326), [3.0](https://github.com/ARMmbed/mbedtls/pull/4429)
=> Backport 2.x: Fix SSL tests scripts with recent OpenSSL server with Diffie-Hellman

tests/compat.sh, tests/ssl-opt.sh
`compat.sh` and `ssl-opt.sh` don't work with a modern OpenSSL (e.g. the system one on Ubuntu 20.04) because they force the use of a small DH prime. We do this for compatibility with ancient versions of OpenSSL which we still use for legacy features. Only do it for those ancient versions, not for modern versions. This way you can run the SSL test scripts with the system version of OpenSSL on a modern system (barring other issues which I haven't checked).
This may turn out not to be needed in 3.0 if we remove everything that requires legacy OpenSSL for interoperability testing. If so we can either revert the patch or keep it for similarity with LTS branches.
Backports:
* 2.x: https://github.com/ARMmbed/mbedtls/pull/4289
* 2.16: https://github.com/ARMmbed/mbedtls/pull/4326
=> Fix SSL tests scripts with recent OpenSSL server with Diffie-Hellman

ChangeLog.d/session-cache-api.txt, docs/3.0-migration-guide.d/session-cache-api.md, include/mbedtls/ssl.h, include/mbedtls/ssl_cache.h, library/ssl_cache.c, library/ssl_srv.c, library/ssl_tls.c
__Context:__ This PR aims to address #4333 - see there for a problem description.
__Changes:__ 
* Move consistency check for ciphersuite and compression outside of the session cache implementation. In particular, session cache implementations need not access those fields anymore, which is a step towards making `mbedtls_ssl_session` opaque.
* Add the session ID as an explicit parameter to the SSL session cache API (API break). In particular, session cache implementation need not access the session ID field anymore, which is another step towards making `mbedtls_ssl_session` opaque.
* Simplify SSL session cache reference implementation by using session serialization.
__Backports:__ (partial)
- 2.x #4529 
- ~2.16 #4539~
=> Add session ID as an explicit parameter to SSL session cache API

ChangeLog.d/host_test-int32.txt, tests/suites/host_test.function
=> Backport 2.16: Fix build error in host_test.function when int32_t is not int

ChangeLog.d/host_test-int32.txt, tests/suites/host_test.function
=> Backport 2.x: Fix build error in host_test.function when int32_t is not int

ChangeLog.d/host_test-int32.txt, tests/suites/host_test.function
Fix https://github.com/ARMmbed/mbedtls/issues/4530.
This is not checked by the CI because we don't build the unit tests on the CI on any platform where `int32_t` and `int` are distinct types. On Arm Cortex-M, `int32_t` is `long int`, so the build fails, although the code would run correctly (I think — there may be bugs due to aliasing, but I haven't checked whether bugs are actually possible). We can't easily build `test_suite_*.o` because it would require more build script changes than I care to do now, and we can't easily build the executables because the only toolchain for Cortex-M we have on the CI is for bare metal and lacks necessary standard library functions.
Backports: #4533, #4534.
=> Fix build error in host_test.function when int32_t is not int

ChangeLog.d/aria-alt.txt, include/mbedtls/aria.h, library/aria.c, library/camellia.c
Fix https://github.com/ARMmbed/mbed-os/issues/14694
Backports: 2.x (#4557), 2.16 (#4558)
=> Fix ARIA_ALT header and self-test and CAMELLIA_ALT self-test

ChangeLog.d/aria-alt.txt, include/mbedtls/aria.h, library/aria.c, library/camellia.c
=> Backport 2.16: Fix ARIA_ALT header and self-test and CAMELLIA_ALT self-test

ChangeLog.d/aria-alt.txt, include/mbedtls/aria.h, library/aria.c, library/camellia.c
=> Backport 2.x: Fix ARIA_ALT header and self-test and CAMELLIA_ALT self-test

include/mbedtls/oid.h, library/oid.c
Signed-off-by: Micah N Gorrell <micah.gorrell@venafi.com>
Notes:
Adds the OID for User ID
**READY**
NO  
NO
=> Add OID for User ID

library/aes.c
Sometime user may forget to call mbedtls_aes_setkey_enc or mbedtls_aes_setkey_dec before mbedtls_aes_crypt_ecb and then
the code normally crash inside the assembly code. With this patch, the code will stop inside the C source code which is more convenient to locate the problem.
**READY**
NO  
Which branch?
NO
Outline the steps to test or …
=> aes: Check aes_padlock_ace > 0 before calling padlock

ChangeLog.d/relaxed-psk-semantics.txt, docs/3.0-migration-guide.d/relaxed-psk-semantics.md, include/mbedtls/ssl.h, library/ssl_tls.c, tests/suites/test_suite_ssl.data, tests/suites/test_suite_ssl.function
This implements and fixes #4191 - see the issue description for more details.
=> Implement relaxed semantics for static PSK configuration in Mbed TLS 3.0

ChangeLog.d/issue4055.txt, docs/3.0-migration-guide.d/csr-add-critical-extension.md, include/mbedtls/x509_csr.h, library/x509write_csr.c
Changes the API to enable creating X.509 CSRs with critical extensions. Fixes https://github.com/ARMmbed/mbedtls/issues/4055
**READY**
NO
I didn't find any test cases for `mbedtls_x509write_csr_set_extension` so I'm not sure if this is needed.
=> Expose flag for critical extensions

ChangeLog.d/cipher-delayed-output.txt, docs/3.0-migration-guide.d/cipher-delayed-output.md, include/mbedtls/cipher.h
Resolves #4355 - turns out a documentation-only change was enough, as the Cipher module already allowed delayed output. Felt the need to clarify the documentation a bit, though, as it didn't say a thing (on way or the other) about whether calling `cipher_finish()` was mandatory for AEAD ciphers as well - now it's explicit.
Considering that it's unclear if we're making a change or just making the documenting the status quo, I'm not sure if we should have a ChangeLog entry and/or migration guide about that.
=> Clarify multi-part AEAD calling sequence in Cipher module

library/nist_kw.c, tests/suites/helpers.function, tests/suites/test_suite_ecp.function, tests/suites/test_suite_pkparse.data
* Remove a few spurious test case dependencies on PEM as in https://github.com/ARMmbed/mbedtls/pull/4596.
* Backport the definitions of `TEST_EQUAL` and `ASSERT_ALLOC` to 2.16, so that it's easier to backport tests.
* Fix a bad dependency in a test function that caused it never to be executed (it was a mistake when backporting from 2.2x to 2.16 so other maintained branches are not affected).
* Fix #4025 as in https://github.com/ARMmbed/mbedtls/pull/4596.
=> Backport 2.16: Fix null pointer arithmetic in NIST_KW

library/nist_kw.c, tests/include/test/macros.h, tests/suites/test_suite_pkparse.data
* Remove a duplicated definition of `ASSERT_ALLOC` (due to some bad merging along the line of the Mbed Crypto fork/merge).
* Remove a few spurious test case dependencies on PEM (minor but I noticed this when looking at something unrelated).
* Fix #4025.
* I didn't write a changelog entry because although it was flagged by recent a UBSan, I think this is benign on today's hardware (but probably not on tomorrow's hardware!).
* No non-regression because I couldn't find a way to trigger UBSan with the older compiler versions on the CI. You can test locally that an UBSan build with Clang 10 now passes the unit tests.
Backports: [2.x](https://github.com/ARMmbed/mbedtls/pull/4593), [2.16](https://github.com/ARMmbed/mbedtls/pull/4598)
=> Fix null pointer arithmetic in NIST_KW

library/nist_kw.c, tests/include/test/macros.h, tests/suites/test_suite_pkparse.data
Trivial backport of https://github.com/ARMmbed/mbedtls/pull/4596
=> Backport 2.x: Fix null pointer arithmetic in NIST_KW

ChangeLog.d/m-ccm-api.txt, docs/3.0-migration-guide.d/ccm-alt.md, include/mbedtls/ccm.h
Define CCM multi-part API along the lines of the GCM multi-part API. The two APIs are not exactly the same as, contrary to GCM, CCM needs the size of the additional data and plaintext/ciphertext from the start.
Fixes #4352
READY
NO
=> Define CCM multi-part API

ChangeLog.d/issue4286.txt, docs/3.0-migration-guide.d/remove_support_for_tls_1.0_1.1_and_dtls_1.0.md, include/mbedtls/ssl.h, library/ssl_ciphersuites.c, library/ssl_cli.c, library/ssl_misc.h, library/ssl_srv.c, library/ssl_tls.c, programs/ssl/ssl_server2.c, tests/ssl-opt.sh
This is a follow-up to #4495 and fixes #4285 (as the remaining parts are already tracked elsewhere). It removes the constants related to TLS 1.0 and TLS 1.1 from the public API and keeps them in a private header, as some code is still using them until we execute #4564.
Edit: turns out it was inconvenient to do that while `mbedtls_ssl_conf_ciphersuites_for_version()` was still part of the public API . It was already being removed in #4442, so I cherry-picked and completed #4442 (after discussing with Hanno) as that seem more convenient that having a dependency between two small PRs.
=> Hide ssl deprecated constants

ChangeLog.d/fix-ssl-cf-hmac-alt.txt, library/ssl_msg.c
Fixes #4118
The sequence of calls starts-update-starts-update-finish is not a
guaranteed valid way to abort an operation and start a new one. Our
software implementation just happens to support it, but alt
implementations may very well not support it.
**READY**
Yes
NO
See #4524 for how to avoid similar bugs in the future.
=> Fix misuse of MD API in SSL constant-flow HMAC

ChangeLog.d/fix-ssl-cf-hmac-alt.txt, library/ssl_msg.c
This is the 2.x backport of #4522 
Note: the backport was trivial, so I think this only needs a single reviewer.
=> [Backport 2.x] Fix misuse of MD API in SSL constant-flow HMAC

ChangeLog.d/fix-ssl-cf-hmac-alt.txt, library/ssl_tls.c
This is the 2.16 backport of #4522
Note: the backport was trivial, so I think this only needs a single reviewer.
=> [Backport 2.16] Fix misuse of MD API in SSL constant-flow HMAC

library/ssl_tls13_keys.c, library/ssl_tls13_keys.h, tests/suites/test_suite_ssl.data, tests/suites/test_suite_ssl.function
__Context:__ This PR is part of the upstreaming of the TLS 1.3 prototype from https://github.com/hannestschofenig/mbedtls/, Specifically, it continues the upstreaming of the TLS 1.3 key schedule functionality, started in https://github.com/ARMmbed/mbedtls/pull/3568.
__Details:__ Recall the TLS 1.3 key schedule form RFC 8448:
```
0
|
v
PSK ->  HKDF-Extract = Early Secret
|
+-----> Derive-Secret(., "ext binder" | "res binder", "")
|                     = binder_key
|
+-----> Derive-Secret(., "c e traffic", ClientHello)
|                     = client_early_traffic_secret
|
+-----> Derive-Secret(., "e exp master", ClientHello)
|                     = early_exporter_master_secret
v
Derive-Secret(., "derived", "")
|
v
(EC)DHE -> HKDF-Extract = Handshake Secret
|
+-----> Derive-Secret(., "c hs …
```
=> TLS 1.3 Key schedule: Second level secret generation

ChangeLog.d/max-record-payload-api.txt, docs/3.0-migration-guide.d/max-record-payload-api.md, docs/3.0-migration-guide.d/remove_deprecated_functions_and_constants.md, include/mbedtls/ssl.h, library/ssl_misc.h, library/ssl_tls.c, programs/ssl/ssl_client2.c, programs/ssl/ssl_server2.c, tests/ssl-opt.sh
Fixes #4381 - see the issue description for more information.
=> Remove MFL query API and add API for maximum plaintext size of incoming records

BRANCHES.md
Give some concrete examples of what is not covered by backward compatibility.
For example, according to this description, https://github.com/ARMmbed/mbedtls/issues/4167 is explicitly not a compatibility break (“Changing which error code is returned in a case where multiple error conditions apply”). Adding a new cryptographic algorithm to the default certificate acceptance profile isn't (“Changing the behavior of a function from failing to succeeding, when the change is a reasonable extension of the current behavior”). But removing an algorithm from the default profile would be (no success can change to an error unless it was undocumented behavior or security requires the change).
=> Document what we mean by backward compatibility

ChangeLog.d/rsa-padding.txt, docs/3.0-migration-guide.d/rsa-padding.md, include/mbedtls/rsa.h, library/pk_wrap.c, library/psa_crypto.c, library/psa_crypto_rsa.c, library/rsa.c, programs/pkey/dh_client.c, programs/pkey/dh_server.c, programs/pkey/rsa_decrypt.c, programs/pkey/rsa_encrypt.c, programs/pkey/rsa_genkey.c, programs/pkey/rsa_sign.c, programs/pkey/rsa_sign_pss.c, programs/pkey/rsa_verify.c, programs/pkey/rsa_verify_pss.c, programs/test/benchmark.c, tests/suites/test_suite_pk.function, tests/suites/test_suite_pkcs1_v15.function, tests/suites/test_suite_pkcs1_v21.function, tests/suites/test_suite_rsa.data, tests/suites/test_suite_rsa.function
=> Remove mbedtls_rsa_init() padding parameters

.travis.yml
Disable OS X builds on Travis due to changes in our plan & billing
=> Disable OS X builds on Travis

.travis.yml
Disable OS X builds on Travis due to changes in our plan & billing
=> Backport 2.x: Disable OS X builds on Travis

.travis.yml
Disable OS X builds on Travis due to changes in our plan & billing
=> Backport 2.16: Disable OS X Travis builds

ChangeLog.d/mbed-can-do-timing.txt, include/mbedtls/check_config.h
Direct backport of https://github.com/ARMmbed/mbedtls/pull/4634 for fixing #4633
**READY**
NO
- ~[ ] Tests~
=> Backport 2.x: config: Allow Mbed to implement TIMING_C

ChangeLog.d/mbed-can-do-timing.txt, include/mbedtls/check_config.h
Mbed OS now provides POSIX-like time functions, although not alarm() nor
signal(). It is possible to implement MBEDTLS_TIMING_ALT on Mbed OS, so
we should not artificially prevent this in check-config. Remove the the
check that prevents implementing MBEDTLS_TIMING_ALT on Mbed OS.
Note that this limitation originally was added in the following commit,
although there isn't much context around why the restriction was
imposed: 63e7ebaaa184 ("Add material for generating yotta module"). In
2015, Mbed OS was quite a different thing: no RTOS, no threads, just an
asynchronous event loop model. I'd suppose the asynchronous event loop
model made it difficult before to implement MBEDTLS_TIMING_C on Mbed OS,
but that is no longer the case.
Fixes #4633
Signed-off-by: Jaeden Amero <jaeden.amero@arm.com> …
=> config: Allow Mbed to implement TIMING_C

ChangeLog.d/issue4398.txt, docs/3.0-migration-guide.d/turn_SSL_SRV_RESPECT_CLIENT_PREFERENCE_config_opt_to_runtime_opt.md, include/mbedtls/config.h, include/mbedtls/ssl.h, library/ssl_srv.c, library/ssl_tls.c
Signed-off-by: TRodziewicz <tomasz.rodziewicz@mobica.com>
The configuration option MBEDTLS_SSL_SRV_RESPECT_CLIENT_PREFERENCE allows during TLS handshake to select the ciphersuite according to the client's preferences rather than the server's preferences. Change it into runtime option available as an API function.
Fixes #4398 
IN DEVELOPMENT
NO  
NO
=> Turn _SSL_SRV_RESPECT_CLIENT_PREFERENCE config opt to a runtime opt

ChangeLog.d/random-range.txt, library/dhm.c, library/ecp.c, tests/suites/test_suite_dhm.data, tests/suites/test_suite_dhm.function
=> dhm: Fix bias in private key generation

docs/3.0-migration-guide.d/remove-ssl-get-session_pointer.md, docs/3.0-migration-guide.d/ssl-ticket-api.md, include/mbedtls/ssl.h, library/ssl_tls.c, programs/ssl/ssl_client2.c
This PR fixes #4184, removing `mbedtls_ssl_get_session_pointer()` and modifying the semantics of `mbedtls_ssl_{set,get}_session()` in preparation for the forthcoming support of TLS 1.3.
See #4184, https://lists.trustedfirmware.org/pipermail/mbed-tls/2020-April/000049.html and the commit messages for details.
=> Implement 3.0-API for SSL session resumption

ChangeLog.d/winsock.txt, library/net_sockets.c
Fix https://github.com/ARMmbed/mbedtls/issues/4465: `mbedtls_net_poll()` and `mbedtls_net_recv_timeout()` became unusable on Windows in Mbed TLS 2.26 and 2.16.10. No intended behavior change on other platforms.
Backports:
* 2.x: https://github.com/ARMmbed/mbedtls/pull/4688
* 2.16: https://github.com/ARMmbed/mbedtls/pull/4689
=> Fix net_sockets regression on Windows

ChangeLog.d/winsock.txt, library/net_sockets.c
Fix #4465. Straightforward backport of #4687.
=> Backport 2.x: Fix net_sockets regression on Windows

ChangeLog.d/winsock.txt, library/net_sockets.c
Fix #4465. Straightforward backport of #4687.
=> Backport 2.16: Fix net_sockets regression on Windows

ChangeLog.d/issue4176.txt, tests/suites/test_suite_aes.function
in file tests/suite/test_suite_aes.function, aes_crypt_xts_size()
did not free the context upon the function exit.
The function now frees the context on exit.
This Closes #4176
**READY**
Yes 
[development_2.x](https://github.com/ARMmbed/mbedtls/pull/4678)
[mbedtls-2.16](https://github.com/ARMmbed/mbedtls/pull/4684)
NO
test_suite_aes
=> Add missing free context in at the end of aes_crypt_xts_size()

ChangeLog.d/issue4176.txt, tests/suites/test_suite_aes.function
in file tests/suite/test_suite_aes.function, aes_crypt_xts_size()
did not free the context upon the function exit.
The function now frees the context on exit.
Issue also resolved in [development](https://github.com/ARMmbed/mbedtls/pull/4676)
and [mbedtls-2.16](https://github.com/ARMmbed/mbedtls/pull/4684)
Closes #4176
**READY**
NO 
NO
test_suite_aes
=> Backport 2.x: Add missing free context at the end of aes_crypt_xts_size()

ChangeLog.d/issue4176.txt, tests/suites/test_suite_aes.function
in file tests/suite/test_suite_aes.function, aes_crypt_xts_size()
did not free the context upon the function exit.
The function now frees the context on exit.
This modification has also taken place in:
- [development](https://github.com/ARMmbed/mbedtls/pull/4676) 
- [2.x](https://github.com/ARMmbed/mbedtls/pull/4678)
Closes #4176
**READY**
NO  
There is already a backport for 2.x, and the change has been made on 2.16 (here) and the development branch
NO …
=> Backport 2.16: Add Free context at the end of aes_crypt_xts_size()

tests/scripts/all.sh
I was getting failures that went away when running `make neat` before invoking `all.sh`.
=> all.sh: Clean up old files before generating them

ChangeLog.d/ecp-window-size.txt, include/mbedtls/config.h, include/mbedtls/ecp.h, include/mbedtls/ssl.h, include/mbedtls/x509_crt.h, library/x509_crt.c
This is a partial backport of #4604:
* Documentation clarifications in some places that I noticed while updating the documentation for curve and hash selection in #4604.
* Change the default ECP window size as discussed in https://github.com/ARMmbed/mbedtls/issues/4127.
The fix for https://github.com/ARMmbed/mbedtls/issues/4608 will be backported separately.
=> Backport 2.x: Curve and hash selection for X.509 and TLS

include/mbedtls/ssl.h, include/mbedtls/x509_crt.h, library/x509_crt.c
This is a partial backport of #4604, a subset of #4621: only documentation updates for the LTS branch.
* Documentation clarifications in some places that I noticed while updating the documentation for curve and hash selection in #4604.
The fix for https://github.com/ARMmbed/mbedtls/issues/4608 will be backported separately.
=> Backport 2.16: Curve and hash selection for X.509 and TLS

ChangeLog.d/one-shot-mac.txt, library/psa_crypto.c, library/psa_crypto_mac.c, tests/suites/test_suite_psa_crypto.function, tests/suites/test_suite_psa_crypto_driver_wrappers.function
Implement one-shot MAC APIs introduced in PSA Crypto API 1.0 beta1 (ARMmbed/mbed-crypto#17).
Resolves #3258
This PR is depends on the MAC driver rework (#4247)
=> Implement one-shot MAC

.travis.yml
Since PR #3709, programs/psa/psa_constant_names_generated.c is checked into version control, so it is no longer necessary to generate it.
This pull request is for 2.2x only: in 2.16 we never generated files automatically, and [in 3.0 we will be generating this file and others on the CI](https://github.com/ARMmbed/mbedtls/pull/4395).
=> 2.2x only: No longer generate psa_constant_names_generated.c on Windows on Travis

include/mbedtls/ccm.h
Function ccm_set_lengths requires tag_len argument for
the B[0] calculation.
=> Add missing tag_len in ccm api.

include/mbedtls/x509_crt.h, library/x509_crt.c
These fields are supposed to be manipulated directly, that's how people
create custom profiles.
Evidence: we recommend direct manipulation of those fields [right in the migration guide](https://github.com/ARMmbed/mbedtls/pull/4604/files#diff-88d0e814bb6d367c041ee4e48cc7dc9480f0900060f2f73ccb254921995e2407R13)
Fixes #4603
=> Make the fields of mbedtls_x509_crt_profile public

include/mbedtls/gcm.h, library/cipher.c, library/gcm.c, tests/suites/test_suite_gcm.function
Fix a mistake in #4332 — see https://github.com/ARMmbed/mbedtls/pull/4342/files#r657410184. Needs to be merged before the 3.0 API freeze.
=> Add output_length parameter to mbedtls_gcm_finish

tests/suites/test_suite_rsa.function
A test was added in prior to the mpi initialisation. If that test failed, it would cause a jump to exit, which would then free the uninitialised pointer in the mpi struct.
Found by coverity
**READY**
NO
(bug not present in 2.x)
NO
=> Fix potential free of uninitialised pointer

library/psa_crypto.c, tests/suites/test_suite_psa_crypto.function
Backport of #4712 for 2.x. Fixes #4709. Ensure that psa_cipher_abort and psa_mac_abort are called on error in some psa_cipher_xxx() and psa_mac_xxx() functions.
=> Backport 2.x: Psa cipher and mac abort on error

library/psa_crypto.c, tests/suites/test_suite_psa_crypto.function
Addresses #4709 . Ensure that psa_cipher_abort and psa_mac_abort are called on error in some psa_cipher_xxx() and psa_mac_xxx() functions.
Yes, for 2.x
=> Psa cipher and mac abort on error

3rdparty/CMakeLists.txt, 3rdparty/everest/CMakeLists.txt, CMakeLists.txt, ChangeLog.d/add-cmake-package-config.txt, README.md, cmake/MbedTLSConfig.cmake.in, library/CMakeLists.txt, programs/test/cmake_package/.gitignore, programs/test/cmake_package/CMakeLists.txt, programs/test/cmake_package/cmake_package.c, programs/test/cmake_package_install/.gitignore, programs/test/cmake_package_install/CMakeLists.txt, programs/test/cmake_package_install/cmake_package_install.c, tests/scripts/all.sh
This change enables automatic detection and consumption of Mbed TLS library targets from within other CMake projects. By generating an `MbedTLSConfig.cmake` file, consuming projects receive a more complete view of these targets, allowing them to be used as dependencies which properly inherit the transitive dependencies of the libraries.
Resolves #298. Probably useful for #2857.
READY
NO
NO
Build and install Mbed TLS as usual. Create a new CMake project, use `find_package(MbedTLS)` to create a dependency on the MBed TLS package, and set `MbedTLS_DIR` to `${MBEDTLS_INSTALL_DIR}/cmake`. You can then use the following targets from your own CMake build system:
- `MbedTLS::TLS` (TLS library)
- `MbedTLS::Crypto` (Crypto library)
- `MbedTLS::X509` (X509 library)
=> Add CMake package config file

include/psa/crypto.h, include/psa/crypto_values.h
Fix typos in the PBKDF2 documentation
Correct the constraints on PSA_KEY_USAGE_DERIVE and PSA_KEY_USAGE_VERIFY_DERIVATION, aligning them with the note against psa_key_derivation_input_key(). All key inputs must have the required usage flag to permit output or verification.
Correct the constraints on PSA_KEY_DERIVATION_INPUT_SECRET and PSA_KEY_DERIVATION_INPUT_PASSWORD, aligning them with 4feb611. psa_key_derivation_verify_key() does not require the secret/password input to be a key.
**READY**
NO
NO
=> Fixes for PBKDF2 documentation

ChangeLog.d/ensure_hash_len_is_valid.txt, library/pk.c, tests/suites/test_suite_pk.function
This is a direct backport from #4561.
Not relevant for 3.0 because the semantics changed in https://github.com/ARMmbed/mbedtls/pull/4707.
[2.16 backport](https://github.com/ARMmbed/mbedtls/pull/4719)
=> Backport 2.x: pk.c: Ensure min hash_len in pk_hashlen_helper

ChangeLog.d/ensure_hash_len_is_valid.txt, library/pk.c
Backport of #4561 . Related to other backport for `development_2.x` #4718.
Very similar except rather than requiring the given `hashlen` to be equal to `mbedtls_md_get_size( md_info )`, it must be at least `mbedtls_md_get_size( md_info )`. This will not break the current `pk` tests so no commits were added like they were in #4561 and #4718 to address test failures.
=> Backport 2.16: pk.c: Ensure min hash_len in pk_hashlen_helper

ChangeLog.d/fix_tls_alert_codes.txt, library/ssl_cli.c, library/ssl_tls.c, tests/ssl-opt.sh
Backport of the bugfix part of #4724.
=> Backport 2.16: Fix alert raised for invalid fragment length

ChangeLog.d/fix_tls_alert_codes.txt, library/ssl_cli.c, library/ssl_tls.c, tests/ssl-opt.sh
Backport of the bugfix part of #4724.
=> Backport 2.x: Fix alert raised for invalid fragment length

ChangeLog.d/fix_fragment_len_return.txt, ChangeLog.d/fix_tls_alert_codes.txt, ChangeLog.d/update_ssl_error_codes.txt, docs/3.0-migration-guide.d/ssl-error-code-cleanup.md, include/mbedtls/error.h, include/mbedtls/ssl.h, library/ssl_cli.c, library/ssl_msg.c, library/ssl_srv.c, library/ssl_tls.c, tests/ssl-opt.sh, tests/suites/test_suite_ssl.function
This PR removes all message-specific `MBEDTLS_ERR_SSL_BAD_HS_XXX` error codes and introduces error codes which instead give the generic reason of the failure, rather than the location of failure. Those new error codes are aligned with TLS alert codes, and the most important ones are `MBEDTLS_ERR_SSL_DECODE_ERROR` for _syntactic_ failures during parsing, and `MBEDTLS_ERR_SSL_ILLEGAL_PARAMETER`, for _semantic_ failures during parsing.
Partial backports (for the alert changes that are non-ambiguously bug fixes, and the test cases where the `MBEDTLS_KEY_EXCHANGE_ECJPAKE_ENABLED` is missing `_ENABLED`): #4736, #4735.
=> Cleanup SSL error code space

programs/ssl/ssl_test_common_source.c
Found by @mstarzyk-mobica in the process of developing #4708, but this is an independent bug.
Needs backporting:
=> Fix memory leak on failure path in test code

programs/ssl/ssl_test_common_source.c
This is the 2.x backport of #4752 - entirely straightforward.
=> [backport 2.x] Fix memory leak on failure path in test code

library/rsa.c
Remove a check in rsa_rsassa_pkcs1_v15_encode() that
is not needed because the same check is performed
earlier. This check was added in #4707.
Signed-off-by: David Horstmann <david.horstmann@arm.com>
Notes:
This PR removes a bounds check on `hashlen` that was added in #4707. This check is already performed in line 1965 on all code paths that also reach this check. As a result, it is redundant and can be …
=> Remove redundant hash len check

programs/test/udp_proxy.c
(This is also a bug that @mstarzyk-mobica noticed by accident while investigating an unrelated issue in #4748.)
We previously introduced a safety check ensuring that if a datagram had
already been dropped twice, it would no longer be dropped or delayed
after that.
This missed an edge case: if a datagram is dropped once, it can be
delayed any number of times. Since "delay" is not defined in terms of
time (x seconds) but in terms of ordering with respect to other messages
(will be forwarded after the next message is forwarded), depending on
the RNG results this could result in an endless loop where all messages
are delayed until the next, which is itself delayed, etc. and no message
is ever forwarded.
The probability of this happening n times in a row is (1/d)^n, where d
is the value passed …
=> Fix bug with UDP proxy not forwarding enough

programs/test/udp_proxy.c
This is the 2.16 backport of #4754 - entirely straightforward.
=> [Backport 2.16] Fix bug with UDP proxy not forwarding enough

docs/architecture/testing/psa-storage-format-testing.md
These are minor updates to the storage format test strategy, clarifying and tweaking a few points based on my experience acquired as I was implementing it.
Needs to go into both 2.x and 3.0.
=> Backport 2.x: Updates to the storage format test strategy after starting implementation

tests/suites/test_suite_psa_crypto_metadata.function
Extended `test_suite_psa_crypto_metadata` as per Gilles suggestion to check the block size is a power of 2.
This is done by shifting a bit repeatedly until the value of the number is greater than or equal to the `block_size` to evaluate if it is a power of 2 or not
Closes #4228
**READY**
NO
This is a backport from [development](https://github.com/ARMmbed/mbedtls/pull/4753)
NO
Run `test_suite_psa_crypto_metadata` and it will pass. 
If you insert `block_size = 12` (or any non power of 2 number) above the power of 2 check, then it will fail.
=> Backport 2.x: Test block sizes are powers of 2

tests/suites/test_suite_psa_crypto_metadata.data, tests/suites/test_suite_psa_crypto_metadata.function
Extended `test_suite_psa_crypto_metadata` as per Gilles suggestion to check the block size is a power of 2.
This is done by shifting a bit repeatedly until the value of the number is greater than or equal to the block_size to evaluate if it is a power of 2 or not
Closes #4228
**READY**
Yes
[development_2.x](https://github.com/ARMmbed/mbedtls/pull/4768)
NO
Run `test_suite_psa_crypto_metadata` and it will pass. 
If you insert `block_size = 12` (or any non power of 2 number) above the power of 2 check, then it will fail.
=> Test block sizes are powers of 2

ChangeLog.d/issue4630.txt, include/mbedtls/bignum.h, library/bignum.c
Closes #4630. C unconditionally reserves identifiers that either begin with two underscore, or a single underscore followed by a capital letter. MbedTLS has a few of these, and they could cause unwanted effects if the compilers decide to use these identifiers.
A slightly modified version of the grep in the issue was used to find all matches.
```
grep -P '^(?!#| \*| *!?\(? *defined\(| *(__asm|__attribute__|__GNUC__)).*\b(?!__FILE__|__LINE__|__ARMCC_VERSION|__ARM_ARCH|__TARGET_ARCH.*|__APPLE__|__MACH__|__GNUC__|_POSIX_*|__WATCOMC__)_[A-Z_]' library/*.c tests/suites/*.function programs/*/*.c
```
- `_B` was replaced with `B` since it was safe to do so.
- `_RR` (representing the precomputed value of R squared) was replaced with `prec_RR` since `RR` is defined in the same scope. The header file …
=> Replace reserved identifier clashes with suitable replacements

ChangeLog.d/issue4630.txt, include/mbedtls/bignum.h, library/bignum.c
This is a backport of #4750, and it fixes #4630 for the 2.x maintenance branch. Identical edits were made by cherry-picking the commits, and verifying with a grep that the pattern existed nowhere.
It is a bug fix (and has a corresponding entry in the ChangeLog) because reserved identifiers had undefined behavior that could depend on the compiler. We eliminate any uncertainty in its behavior by making variable names conform to the requirements set by C.
=> Backport 2.x: Replace reserved identifier clashes with suitable replacements

ChangeLog.d/issue4630.txt, include/mbedtls/bignum.h, library/bignum.c
This is a backport of #4750, and it fixes #4630 for the 2.16 maintenance branch. Identical edits were made by cherry-picking the commits, and verifying with a grep that the pattern existed nowhere.
(Note: `mbedtls_mpi_mul_int` has a reserved `_B` in 2.16 only, this has been addressed too.)
It is a bug fix (and has a corresponding entry in the ChangeLog) because reserved identifiers had undefined behavior that could depend on the compiler. We eliminate any uncertainty in its behavior by making variable names conform to the requirements set by C.
=> Backport 2.16: Replace reserved identifier clashes with suitable replacements

scripts/mbedtls_dev/c_build_helper.py
Fix #4699
3.0 only: the corresponding script exists in 2.x, but there it's only a CI script and doesn't even work with MSVC.
=> psa_generate_test: tweak MSVC detection to work with non-English Visual Studio

library/md2.c, library/md4.c, library/md5.c, library/ripemd160.c, library/sha512.c
Trivial backport of https://github.com/ARMmbed/mbedtls/pull/3588. Closes https://github.com/ARMmbed/mbedtls/issues/3666.
=> Backport 2.16: Prevent triggering Clang 12 -Wstring-concatenation warning

ChangeLog.d/makefile-python-windows.txt, tests/Makefile, tests/ssl-opt.sh
Backport of the applicable parts of https://github.com/ARMmbed/mbedtls/pull/4776.
=> Backport 2.16: Fix python in tests/Makefile, etc.

ChangeLog.d/session_export_private.txt, include/mbedtls/ssl.h
The fact that those fields were not explicitly marked private currently is an oversight due to concurrent merging of PRs during the run-up to the release of Mbed TLS 3.0.
=> Explicitly mark fields as private via MBEDTLS_PRIVATE(...)

include/mbedtls/ssl.h, library/ssl_cli.c, library/ssl_srv.c, library/ssl_tls.c, tests/suites/test_suite_ssl.function
Instances of `mbedtls_ssl_session` represent data enabling session resumption.
With the introduction of TLS 1.3, the format of this data changes. We therefore
need TLS-version field as part of `mbedtlsl_ssl_session` which allows distinguish
1.2 and 1.3 sessions.
This commit introduces such a TLS-version field to mbedtls_ssl_session.
The change has a few ramifications:
- Session serialization/deserialization routines need to be adjusted.
This is achieved by adding the TLS-version after the header of
Mbed TLS version+config, and by having the subsequent structure
of the serialized data depend on the value of this field.
The details are described in terms of the RFC 8446 presentation language.
The 1.2 session (de)serialization are moved into static helper functions,
while the top-level …
=> Store TLS version in SSL session structure

include/mbedtls/check_config.h
"This is the 2.x backport of #4659"
Signed-off-by: Spencer Burke <info.spencer.burke@gmail.com>
=> Backport of #4659

include/mbedtls/check_config.h
Removing the extra preprocessor directives found within the specified source file. Specifically, removing the duplicate code found within the source file mbedtls/include/mbedtls/check_config.h. Fixes #4222 
[ ] Patch update
[ ] No Tests required for this change
=> Remove duplicated check in `check_config.h`

tests/ssl-opt.sh
Closes #4471.
- Replaced all occurrences of `config.py` with `get_config_value_or_default`.
- Remove `exit 1` hard abort and replaced with `requires_config_value_at_least` when `MBEDTLS_X509_MAX_INTERMEDIATE_CA` != `MAX_IM_CA`. The explanation given on hard exit was reworded and put in a comment.
- Remove `exit 1` hard abort when `MAX_IN_LEN` or `MAX_OUT_LEN` < 4096. This was replaced with `requires_config_value_at_least` + `requires_max_content_len`, and the threshold was adjusted for each test:
- For the "Max Fragment Length" suite, it requires an amount that can fit both party's MFLs.
- For two tests in the "Connection ID" suite, it requires MFL+1 so it triggers a buffer reallocation
- For the "DTLS fragmenting" suite, it requires an amount that can fit both party's MFLs.
With this …
=> ssl-opt.sh: Skip tests instead of conditional hard abort

tests/ssl-opt.sh
This is a relatively straightforward backport of https://github.com/ARMmbed/mbedtls/pull/4695 for 2.16.
Fixes #4471.
=>  Backport 2.16: ssl-opt.sh: Skip tests instead of conditional hard abort 

tests/ssl-opt.sh
This is a relatively straightforward backport of https://github.com/ARMmbed/mbedtls/pull/4695 for 2.x.
Fixes #4471.
=> Backport 2.x: ssl-opt.sh: Skip tests instead of conditional hard abort

scripts/bump_version.sh, tests/scripts/check-generated-files.sh
* Adapt `bump_versions.sh` for the places where the version number appears in 3.0. Fix #4744.
* `check-generated-files -l` now lists the generated files, which would have been useful when preparing the release.
No backports needed since none of the changes are required on 2.27.
=> Fix release scripts for 3.0

library/CMakeLists.txt, library/Makefile, library/ssl_misc.h, library/ssl_tls.c, library/ssl_tls13_client.c, library/ssl_tls13_server.c, programs/ssl/ssl_client2.c, programs/ssl/ssl_server2.c, tests/ssl-opt.sh, tests/suites/test_suite_debug.function
This PR add TLS1.3 main dispatch dummy functions to verify basic flow. 
It includes below changes
- Add ssl structure setup check.
- Add dummy dispatches
- Add two test cases
Fixes #4844 
**READY**
NO  
NO
=> TLS1_3:add tls13 config check and dummy handshake

library/ssl_misc.h, library/ssl_msg.c
The helper `mbedtls_ssl_write_handshake_msg` writes a handshake message and updates the handshake transcript.
With TLS 1.3, we need finer control over the checksum: updating at message granularity is not sufficient. To allow for manual maintenance of the checksum in those cases, refine `mbedtls_ssl_write_handshake_msg()` into `mbedtls_ssl_write_handshake_msg_ext()` which takes a parameter determining whether the checksum should be updated.
=> Add handshake message writing variant that doesn't update checksum

library/ssl_tls.c
This PR extracts the messaging layer reset from `mbedtls_ssl_session_reset_int()` into a static helper function:
- Improves readability
- Will be useful when we introduce MPS as an alternative messaging layer.
- Will be useful when we need to reset the messaging layer upon receipt of a `HelloRetryRequest` in TLS 1.3.
=> Move messaging related session reset into separate helper function

include/mbedtls/ssl.h, library/ssl_misc.h, library/ssl_tls.c
This PR fixes #4857, adding `mbedtls_ssl_transform`-typed fields to `mbetls_ssl_context` (for application data) and `mbedtls_ssl_handshake_params` (for 0-RTT and encrypted handshake data), as freeing logic in `mbedtls_ssl_free()` and `mbedtls_ssl_handshake_free()`. No allocation is done: This will be done lazily at the time where the respective key material becomes available.
The PR improves the documentation of existing transform fields along the way.
=> Upstream TLS 1.3 record transformations structure fields

.travis.yml, tests/scripts/all.sh
Add a build with arm-linux-gnueabi-gcc - compared to existing Arm builds, this allows building the programs and tests, in order to catch platform-dependent issues there too (previously we only cross-built the library to Arm).
See https://github.com/ARMmbed/mbedtls/pull/3449#issuecomment-675313720
See also. https://github.com/ARMmbed/mbedtls/issues/3299
**READY**
Yes - testing improvement
=> Add arm-linux-gnueabi-gcc build

.travis.yml, tests/scripts/all.sh
This is the 2.x backport of https://github.com/ARMmbed/mbedtls/pull/3572 - entirely straightforward except for one contextual difference: `test-ref-configs.pl` was invoked directly rather than via `all.sh`, so I changed that as well while at it, to better align things across branches.
=> Backport 2.x: Add arm-linux-gnueabi-gcc build

.travis.yml, tests/scripts/all.sh
This is the 2.16 backport of #3572, based on the 2.x backport in #4855 - the only difference is 2.16 is using `config.pl` while more recent branches use `config.py`.
=> Backport 2.16: Add arm-linux-gnueabi-gcc build

tests/ssl-opt.sh
Add functions and test cases to make sure tls1.3 is available in openssl/gnutls.
Relative issues: #4417 
NO  
NO
=> Add openssl/gnutls tls1.3 feature tests.

ChangeLog.d/tls_ext_cid-config.txt, include/mbedtls/mbedtls_config.h, include/mbedtls/ssl.h
The numerical identifier of the CID extension hasn't been settled yet and different implementations use values from different drafts. Allow configuring the value at compile time as discussed in https://github.com/ARMmbed/mbedtls/issues/3892#issuecomment-757523779.
This PR is for 3.0. [2.x PR](https://github.com/ARMmbed/mbedtls/pull/4427)
=> Allow configuring MBEDTLS_TLS_EXT_CID at compile time

ChangeLog.d/tls_ext_cid-config.txt, include/mbedtls/config.h, include/mbedtls/ssl.h, programs/test/query_config.c
The numerical identifier of the CID extension hasn't been settled yet and different implementations use values from different drafts. Allow configuring the value at compile time as discussed in https://github.com/ARMmbed/mbedtls/issues/3892#issuecomment-757523779.
This PR is for 2.x. [3.0 PR](https://github.com/ARMmbed/mbedtls/pull/4413)
=> Backport 2.x: Allow configuring MBEDTLS_TLS_EXT_CID at compile time

include/mbedtls/ssl.h
Mbed TLS' messaging layer interprets the return value `0` from the underlying BIO receive callback as connection closure, which is not documented. This PR fixes this.
Backport: 2.x = #4873 - 2.16 = #4874
=> Document that returning 0 from the recv callback means EOF

include/mbedtls/ssl.h
This is the 2.x backport of #4807, entirely straightforward.
=> Backport 2.x: Document that returning 0 from the recv callback means EOF

include/mbedtls/ssl.h
This is the 2.16 backport of #4807, entirely straightforward.
=> Backport 2.16: Document that returning 0 from the recv callback means EOF

CMakeLists.txt
Summary:
[CMP0090](https://cmake.org/cmake/help/latest/policy/CMP0090.html) was introduced in CMake version 3.15. The CMake version guard should be greater or equal to 3.15. Greater than `3.14` may not work because `3.14.x` is greater than `3.14`.
My cmake version is `3.14.5`, and run into the following `cmake` error.
```
cmake --version
cmake version 3.14.5
```
```
CMake Error at CMakeLists.txt:338 (cmake_policy):
Policy "CMP0090" is not known to this version of CMake.
-- Configuring incomplete, errors occurred!
```
Test Plan:
```
cmake
```
=> Update CMake version for CMP0090

include/mbedtls/ssl.h
Small misprint in the description of `mbedtls_ssl_recv_timeout_t` typedef was fixed.
=> Misprint was fixed

library/pkparse.c
Warning reported with IAR compiler:
"mbedtls\library\pkparse.c",1167  Warning[Pe550]: variable "ret" was set but never used
Backports: https://github.com/ARMmbed/mbedtls/pull/4903, https://github.com/ARMmbed/mbedtls/pull/4904
=> Remove compiler warning if only MBEDTLS_PK_PARSE_C is defined

tests/compat-in-docker.sh, tests/docker/bionic/Dockerfile, tests/ssl-opt-in-docker.sh, tests/ssl-opt.sh
Upgrade gnutls-next from 3.6.5 to 3.7.2.
TLS1.3 tests depend on new features in 3.7.2. 
v3.7.2 introduce DISABLE_TLS13_COMPAT_MODE, that can disable compatible middle box. And we will add options for same purpose. That will need test cases for it.
Also, in our development progress, SESSION TICKET and TLS13 COMPATIBLE will not be available at beginning. and the issue target is finish client flow first. we should prepare a well configured server for test
issues: #4417 
**READY**
NO  
NO
=> Upgrade gnutls next

ChangeLog.d/psa_cipher_update_ecp.txt, library/psa_crypto_cipher.c
Trivial backport of #4938. Needed for oss-fuzz.
=> Backport 2.x: Fix parameter set but unused on psa_cipher_update_ecb

ChangeLog.d/muladdc-amd64-memory.txt, include/mbedtls/bn_mul.h
=> Backport 2.16: Fix x86_64 assembly for bignum multiplication

ChangeLog.d/muladdc-amd64-memory.txt, library/bn_mul.h
Add missing declarations of memory accesses in the x86_64 assembly code for multiplication. We got away without those for a long time, but Clang 12 needs them. Fix #4116, #4786, #4917.
I have not looked for similar bugs in any other assembly code.
Backports: #4941 (had two reviewers), #4948
=> Fix x86_64 assembly for bignum multiplication

ChangeLog.d/muladdc-amd64-memory.txt, include/mbedtls/bn_mul.h
=> Backport 2.x: Fix x86_64 assembly for bignum multiplication

ChangeLog.d/do-not-use-obsolete-header.txt, tests/suites/test_suite_net.function
Signed-off-by: joseph <joseph@jc-lab.net>
When build via cmake on alpine linux, cause the following error: This PR fix the error.
```
[ 99%] Building C object tests/CMakeFiles/test_suite_net.dir/test_suite_net.c.o
In file included from .../tests/suites/test_suite_net.function:12:
/usr/include/sys/fcntl.h:1:2: error: #warning redirecting incorrect #include <sys/fcntl.h> to <fcntl.h> [-Werror=cpp]
1 | #warning redirecting incorrect #include <sys/fcntl.h> to <fcntl.h>
|  ^~~~~~~
cc1: all warnings being treated as errors
```
**READY**
NO  
NO
https://github.com/jclab-joseph/mbedtls/actions/runs/1264843158
The build succeeds in ubuntu but fails in alpine.
https://github.com/jclab-joseph/mbedtls/actions/runs/1264845085
Both …
=> Fix test code to can be built on alpine

ChangeLog.d/do-not-use-obsolete-header.txt, tests/suites/test_suite_net.function
**This is backporting for 2.x about #4969 pr.**
When build via cmake on alpine linux, cause the following error: This PR fix the error.
```
[ 99%] Building C object tests/CMakeFiles/test_suite_net.dir/test_suite_net.c.o
In file included from .../tests/suites/test_suite_net.function:12:
/usr/include/sys/fcntl.h:1:2: error: #warning redirecting incorrect #include <sys/fcntl.h> to <fcntl.h> [-Werror=cpp]
1 | #warning redirecting incorrect #include <sys/fcntl.h> to <fcntl.h>
|  ^~~~~~~
cc1: all warnings being treated as errors
```
**READY**
NO  
NO
https://github.com/jclab-joseph/mbedtls/actions/runs/1264843158
The build succeeds in ubuntu but fails in alpine.
https://github.com/jclab-joseph/mbedtls/actions/runs/1264845085 …
=> Backport 2.x: Fix test code to can be built on alpine #4969

docs/use-psa-crypto.md, include/mbedtls/mbedtls_config.h
The existing documentation contains not detail about what have been done yet and what's still left to do. Curious users would have to grep and read the source, which is sub-optimal. Also, for our own planning it was necessary to know exactly where we stand, so let's make this newly consolidated knowledge available to everyone.
Related to: https://github.com/ARMmbed/mbedtls/issues/4836
**READY**
I'm suggesting to backport to 2.2x as this fills a documentation gap. 
No backport for 2.16 as there's no PSA there.
For people who have access to the old planning documents, it looks like we executed everything from phases 1 to 5 included (with the revised definition of phase 4 from part 2) and nothing from later phases, so this is a pretty clean state with regard to the previous planning.
The …
=> Document effects of  `MBEDTLS_USE_PSA_CRYPTO`

docs/use-psa-crypto.md, include/mbedtls/config.h
Trivial backport of https://github.com/ARMmbed/mbedtls/pull/4961
=> Backport 2.x: Document effects of MBEDTLS_USE_PSA_CRYPTO

ChangeLog.d/muladdc-aarch64-memory.txt, ChangeLog.d/muladdc-amd64-memory.txt, ChangeLog.d/muladdc-memory.txt, include/mbedtls/bn_mul.h
Backport of #4968. Fixes #4962 
Add missing memory constraint in aarch64 bignum multiplication code to remedy Clang 12+ issues. Fixes #4962.
Part of the larger super-issue #4943.
Tested with the following steps:
```
mkdir build && cd build
CC=clang CFLAGS="--target=aarch64-linux-gnu" cmake -DCMAKE_BUILD_TYPE=Release ..
make -j8
cd tests
qemu-aarch64 -L /usr/aarch64-linux-gnu ./test_suite_mpi
```
**READY**
=> Backport 2.x: Fix aarch64 assembly for bignum multiplication

ChangeLog.d/muladdc-aarch64-memory.txt, ChangeLog.d/muladdc-amd64-memory.txt, ChangeLog.d/muladdc-memory.txt, library/bn_mul.h
Add missing memory constraint in aarch64 bignum multiplication code to remedy Clang 12+ issues. Fixes #4962.
Part of the larger super-issue #4943.
Tested with the following steps:
```
mkdir build && cd build
CC=clang CFLAGS="--target=aarch64-linux-gnu" cmake -DCMAKE_BUILD_TYPE=Release ..
make -j8
cd tests
qemu-aarch64 -L /usr/aarch64-linux-gnu ./test_suite_mpi
```
**READY**
Yes
Only to [2.x](https://github.com/ARMmbed/mbedtls/pull/4978) as `2.16` does not have this aarch64 assembly
=> Fix aarch64 assembly for bignum multiplication

include/mbedtls/ssl.h, library/ssl_misc.h, library/ssl_msg.c, library/ssl_tls.c
`MBEDTLS_SSL_PEND_FATAL_ALERT` is replacement of  `SSL_PEND_FATAL_ALERT` in `prototye`.
`SSL_PEND_FATAL_ALERT` is  delay sending alert message feature in `prototype`. It is defined at [`ssl.h`](https://github.com/hannestschofenig/mbedtls/blob/ae6624780fba2d9256072b73338c67b84f9b9793/include/mbedtls/ssl.h#L1841). It introduces `SSL_PEND_FATAL_ALERT` , [new members of context](https://github.com/hannestschofenig/mbedtls/blob/ae6624780fba2d9256072b73338c67b84f9b9793/include/mbedtls/ssl.h#L1693) and [new function](https://github.com/hannestschofenig/mbedtls/blob/ae6624780fba2d9256072b73338c67b84f9b9793/library/ssl_msg.c#L6205)
There are `ABI-API checking` fail in CI. Due to we add 3 members in `mbedtls_ssl_context`
**READY**
NO  
NO
=> Add send alert message macro

include/mbedtls/asn1.h, include/mbedtls/cipher.h, include/mbedtls/ecp.h, include/mbedtls/net_sockets.h, include/mbedtls/pk.h, include/mbedtls/psa_util.h, include/mbedtls/x509.h, include/mbedtls/x509_crl.h, include/mbedtls/x509_crt.h, include/mbedtls/x509_csr.h, library/ssl_ticket.c, library/ssl_tls.c, programs/aes/crypt_and_hash.c, programs/pkey/ecdsa.c, programs/pkey/gen_key.c, programs/ssl/dtls_server.c, programs/ssl/mini_client.c, programs/ssl/ssl_fork_server.c, programs/ssl/ssl_server.c, programs/x509/cert_app.c, programs/x509/cert_write.c, tests/suites/test_suite_cipher.function
This pull request declares a number of fields as public. In particular:
* Make the fields of `mbedtls_ecp_curve_info` public, which is necessary for ecfuzzer (see https://github.com/ARMmbed/mbedtls/issues/4790).
* Make fields that expose the result of ASN.1 and X.509 parsing public. Fixes https://github.com/ARMmbed/mbedtls/issues/4839. I'm not 100% sure of my choices in the X.509 structures regarding what should be public (e.g. for callbacks) and what should be private (because the library has functions for that, e.g. signature verification), opinions welcome. Resolves #4885.
* Make the `fd` in `mbedtls_net_context` public, but document that this is only guaranteed on platforms where it actually is a file descriptor (on Windows, there shouldn't be an `fd` field, but I've left that for …
=> Make some structure fields public: key info, ASN.1 and X.509 parsing, socket fd

library/ssl_misc.h, library/ssl_tls13_generic.c
This function is one common function in generic file, get it from
the encrypted extension and submit one patch independently.
Extracted from the PR #4937
Signed-off-by: XiaokangQian <xiaokang.qian@arm.com>
=> Add fetch_hand_message in generic

tests/Makefile, tests/scripts/all.sh
Backport of #4955 (just the `make test` part, not the PSA part which doesn't apply to 2.16).
=> Backport 2.16: Facilitate reproducing unit tests from all.sh

tests/scripts/all.sh
Don't default to unbridled -j, which causes a load spike and isn't really faster.
=> Limit make parallelism to the number of CPUs in all.sh

tests/scripts/all.sh
=> Backport 2.16: Limit make parallelism to the number of CPUs in all.sh

tests/scripts/all.sh
=> Backport 2.x: Limit make parallelism to the number of CPUs in all.sh

README.md
=> Backport 2.16: Add contact information directly on the home page

include/mbedtls/ecp.h, include/mbedtls/platform_util.h, include/mbedtls/ssl.h, library/ssl_cli.c, library/ssl_misc.h, library/ssl_srv.c, library/ssl_tls.c, library/ssl_tls13_client.c, programs/ssl/ssl_client2.c, programs/ssl/ssl_server2.c, tests/suites/test_suite_ssl.data, tests/suites/test_suite_ssl.function
Adds mbedtls_ssl_conf_group to API. It works on supported_groups, which is a static array with a size controlled by a macro. mbedtls_ssl_conf_curves has been amended to work on this array too.
**IN DEVELOPMENT **
Yes | **NO**  
Which branch?
**YES** | NO
API change is needed to enable uses of groups outside of ECDHE.
- [] Tests
- [] …
=> Add mbedtls_ssl_conf_groups to API

tests/suites/test_suite_psa_crypto.data
Dropped here: https://github.com/ARMmbed/mbedtls/commit/71b0567c87e07ba7376b991f46d94bcac8afbfa8#diff-cc82e7d511f22a0a29b24a8ad0c62d6c62b5f8c84ad67e55ea71d7fc035101aeL1421
=> Add a missing psa_crypto test suite test name

tests/suites/test_suite_psa_crypto.data
Trivial backport of https://github.com/ARMmbed/mbedtls/pull/5124.
Add missing test name.
=> Backport 2.x: Add a missing psa_crypto test suite test name

library/base64_invasive.h
Trivial backport of https://github.com/ARMmbed/mbedtls/pull/5128
=> Backport 2.x: Fix copypasta in #endif comment

library/base64_invasive.h
This mistake will cause `check_names.py` to fail when https://github.com/ARMmbed/mbedtls/pull/4866 is merged. Let's fix it first.
Backports: [2.x](https://github.com/ARMmbed/mbedtls/pull/5129); not applicable to 2.16.
=> Fix copypasta in #endif comment

ChangeLog.d/psa_crypto_api_macros.txt, include/psa/crypto.h, include/psa/crypto_sizes.h, include/psa/crypto_values.h, library/psa_crypto.c, library/psa_crypto_mac.c, tests/src/psa_exercise_key.c, tests/suites/test_suite_psa_crypto.function, tests/suites/test_suite_psa_crypto_metadata.data, tests/suites/test_suite_psa_crypto_metadata.function
Resolves #3278, #4906
This is a continuation of https://github.com/ARMmbed/mbedtls/pull/4896 which I don't have permission to push to. Status:
Backport: [2.x](https://github.com/ARMmbed/mbedtls/pull/5050)
=> Add missing PSA macros

ChangeLog.d/psa_crypto_api_macros.txt, include/psa/crypto.h, include/psa/crypto_sizes.h, include/psa/crypto_values.h, library/psa_crypto.c, library/psa_crypto_mac.c, programs/psa/psa_constant_names_generated.c, tests/src/psa_exercise_key.c, tests/suites/test_suite_psa_crypto.function, tests/suites/test_suite_psa_crypto_metadata.data, tests/suites/test_suite_psa_crypto_metadata.function
Backport of https://github.com/ARMmbed/mbedtls/pull/4966
Differences with the 3.x version:
* Add/add conflict in "Add missing PSA_ALG_NONE macro."
* Update stored generated file in "Add missing PSA_ALG_NONE macro."
* Add support for MD2 and MD4 in "Add missing PSA_HASH_BLOCK_LENGTH macro."
* Remove the MD2/MD4 lines as well in "Use the new macro PSA_HASH_BLOCK_LENGTH"
=> Backport 2.x: Add missing PSA macros

ChangeLog.d/fix-needed-shared-libraries-linux.txt, README.md, library/Makefile
The makefile build specifies `-L. -lmbedx509 -lmbedcrypto` flags first,
and only then object files referencing symbols from those libraries.
In this order the linker will not add the linked libraries to the
DT_NEEDED section because they are not referenced yet (at least that
happens for me on ubuntu 20.04 with the default gnu compiler tools).
By first specifying the object files and then the linked libraries, we
do end up with libmbedx509 and libmbedcrypto in the DT_NEEDED sections.
This way running dlopen(...) on libmedtls.so just works.
Note that the CMake build does this by default.
~Also fixes a bug (?) where there is no whitespace between `-lmbedx509$(LOCAL_LDFLAGS)`~ (this was not the case)
It could be seen as a bug fix, since the cmake and makefile builds are inconsistent right …
=> DT_NEEDED for shared builds in makefile

ChangeLog.d/fix-needed-shared-libraries-linux.txt, README.md, library/Makefile
=> Backport 2.x: DT_NEEDED for shared builds in makefile

library/Makefile
This is a workaround for an issue with mkstemp() in older MinGW releases that
causes simultaneous creation of .a files in the same directory to fail.
Fixes #5146
**READY**
Yes
=> Serialise builds of the .a files on Windows

library/Makefile
This is a workaround for an issue with mkstemp() in older MinGW releases that
causes simultaneous creation of .a files in the same directory to fail.
Fixes #5146
Backport of #5147
=> Backport 2.16: Serialise builds of the .a files on Windows

library/Makefile
This is a workaround for an issue with mkstemp() in older MinGW releases that
causes simultaneous creation of .a files in the same directory to fail.
Fixes #5146
Backport of #5147
=> Backport 2.x: Serialise builds of the .a files on Windows
