scripts/mbedtls_dev/test_case.py
tests/scripts/generate_psa_tests.py
tests/suites/test_suite_psa_crypto_generate_key.function
tests/suites/test_suite_psa_crypto_not_supported.function

- add another family of test cases: attempting to generate key. Positive and negaive (generation is impossible for public key types) test cases,
- move the existing support for key generation for public key types from `NotSupported` class
Resolves https://github.com/ARMmbed/mbedtls/issues/5060
**READY**
2.x PR #5142
NO

Generate test cases for PSA key generation

---

library/ssl_msg.c
library/ssl_tls.c

Fix issues found in #5075.
- memory leak: Handshake free should be done before zeroize . Otherwise, it cause memory leak.
- According to TLS1.3 spec(RFC8446) , version header should be 0x0303, not 0x0304

TLS1.3 :fix memory leak and version header

---

programs/ssl/ssl_client2.c
programs/ssl/ssl_server2.c
tests/include/test/psa_crypto_helpers.h
tests/src/psa_crypto_helpers.c
tests/src/psa_exercise_key.c

Backport of PR https://github.com/ARMmbed/mbedtls/pull/5111
**READY**

(Backport 2x) ssl_client2, ssl_server2: add check for psa memory leaks

---

programs/ssl/ssl_client2.c
programs/ssl/ssl_server2.c
tests/include/test/psa_crypto_helpers.h
tests/src/psa_crypto_helpers.c
tests/src/psa_exercise_key.c

Add check for psa memory leaks in ssl test apps.
Fix for:
https://github.com/ARMmbed/mbedtls/issues/5099
Related PR:
https://github.com/ARMmbed/mbedtls/pull/5007 - this PR adds key destruction after the test is done.
No memory leak detected. 
I confirmed that during the test (when keys are in use) memory leak is indicated by `mbedtls_test_helper_is_psa_leaking()`. 
After calling `mbedtls_psa_crypto_free()` no leaks are detected, but the potential problem is that `mbedtls_psa_crypto_free()` is called twice: :
- directly,
- few lines earlier `rng_free()` is called and it calls also `mbedtls_psa_crypto_free()`.
I didn't add separate header file as I didn't found optimal solution for this (consistent with the proposition):
> One solution would be to split In psa_crypto_helpers.h in two parts: …

ssl_client2, ssl_server2: add check for psa memory leaks

---

.gitignore
tests/scripts/all.sh
tests/scripts/test_psa_compliance.py

This PR adds a component to all.sh which clones, builds and runs the
compliance test suite.
The psa-arch-tests repo is cloned and deleted every time the component is run, which I'm not sure is desirable for a component enabled by default. Looking for feedback in that department.
Closes #4108
**In Development**
Yes
Which branch?
development_2.x: #5169 
None

Run the PSA Compliance test suite in all.sh

---

.gitignore
tests/scripts/all.sh
tests/scripts/test_psa_compliance.py

This is the development_2.x backport of #5094.
This commits up to and including 340352a are faithful backports of the original commits, with the subsequent commits containing the development_2.x specific changes.

Backport 2.x: Run the PSA Compliance test suite in all.sh

---

tests/scripts/test_psa_compliance.py

This PR is the trivial development_2.x backport of #5195.

Backport 2.x: Remove superfluous expected failure from test_psa_compliance

---

include/mbedtls/aes.h
include/mbedtls/sha256.h

Remove description of non-existing "mode" parameter from the docs of mbedtls_aes_crypt_ctr
Backport of #5105

Backport 2.16: doc improvement in aes include

---

include/mbedtls/aes.h
include/mbedtls/sha256.h

- Add return value description to the docs of mbedtls_sha256
- Remove description of non-existing "mode" parameter from the docs of mbedtls_aes_crypt_ctr
Backport of #5105

Backport 2.x: doc improvements in aes and sha256 includes

---

include/mbedtls/aes.h
include/mbedtls/sha256.h

1. Add return value description to the docs of `mbedtls_sha256`
2. Remove description of non-existing "mode" parameter from the docs of `mbedtls_aes_crypt_ctr`

doc improvements in aes and sha256 includes

---

ChangeLog.d/bugfix-for-gcm-long-iv-size.txt
library/gcm.c

Fixes #4884
An initialization vector IV can have any number of bits between 1 and
2^64. So it should be filled to the lower 64-bit in the last step
when computing ghash.
Notes:
**READY/IN DEVELOPMENT/HOLD**
Changes do not have to be backported …

Backport 2.16: Fix GCM calculation with very long IV

---

ChangeLog.d/bugfix-for-gcm-long-iv-size.txt
library/gcm.c

Trivial backport of https://github.com/ARMmbed/mbedtls/pull/4950

Backport 2.x: Fix GCM calculation with very long IV

---

ChangeLog.d/fix_compilation_ssl_tests.txt
tests/suites/test_suite_ssl.function

Under gcc11(+) both message and received would cause errors for potentially being used uninitialised. We fixed many of these issues in another PR (fixing #3782), but this one is only seen under certain configs.
**READY**
Yes 
[2.x](#5235 )
NO
Run the all.sh "test_cmake_out_of_source" with GCC11

Fix test_suite_ssl compilation errors with GCC11

---

ChangeLog.d/fix_compilation_ssl_tests.txt
tests/suites/test_suite_ssl.function

Under gcc11(+) both message and received would cause errors for potentially being used uninitialised. We fixed many of these issues in another PR (fixing #3782), but this one is only seen under certain configs.
This is a backport of #5222 
**READY**
NO
Run the all.sh "test_cmake_out_of_source" with GCC11

Backport 2.x: Fix test_suite_ssl compilation errors with GCC11

---

library/psa_crypto.c

Clean-up about checks regarding whether a key is opaque or not in PSA code. The checks are updated/modified to take into account that now opaque keys are not necessarily to be used by drivers registered at run time, driver implementing the unified driver interface can also handle opaque keys. Changes driven by the review and testing of #4766.
READY
Yes
2.x

PSA opaque key checks

---

library/psa_crypto.c

Straightforward backport of #4895, no conflict.

Backport 2.x: PSA opaque key checks

---

ChangeLog.d/additional_cipher_info_getters.txt
include/mbedtls/cipher.h
tests/suites/test_suite_cipher.function

While trying to add mbedtls 3 support to OpenVPN, we found that we need some additional getter functions that are not yet in the dev branch. This pull request adds functions that get the IV and block size from a `cipher_info` struct and functions that check if the IV or key size of a cipher are variable.
We also need some more getter functions in other parts of the library, but I figured it's easier if I keep the pull requests small.
**READY**
NO  
NO

Additional cipher_info getters

---

include/psa/crypto.h

`psa/crypto.h` and `psa/crypto_struct.h` have a declaration and a definition of static function `mbedtls_set_key_owner_id` using a different parameter name as second parameter (`owner` vs `owner_id`). This can be picked by static analysis code checking tools that might trigger [funcArgNamesDifferent], for example in latest versions of cppcheck.
READY
Yes 
Which branch?
`development_2.x`
Run cppcheck (e.g. version 2.7-dev) with --enable=all --inconclusive

Align function parameter names for mbedtls_set_key_owner_id

---

include/psa/crypto.h

This is a backporting of #5246 to `development_2.x`

Backport 2.x: Align function parameter names for mbedtls_set_key_owner_id

---

.travis.yml
README.md
scripts/basic.requirements.txt
scripts/ci.requirements.txt
scripts/driver.requirements.txt
scripts/maintainer.requirements.txt
scripts/min_requirements.py
tests/docker/bionic/Dockerfile

Add in-tree pip `requirements.txt` files, and a script to install minimum versions of the requirements for testing.
Why do it that way: we have a single source of truth for Python package requirements, rather than have to do separate installations on Travis, each Jenkins Docker image, Jenkins FreeBSD hosts and Jenkins Windows hosts.
Rationale for having multiple `requirements.txt` files: there's one for each target audience. This helps document what each package is used for, and gives users a simple way to only install what they need.
Testing with an additional requirement (this PR plus an adjusted version of https://github.com/ARMmbed/mbedtls/pull/5193):
* Travis: see https://app.travis-ci.com/github/ARMmbed/mbedtls/branches, job on `codegen_1.0-pip`
* Jenkins: see …

In-tree Python package requirements

---

.travis.yml
scripts/ci.requirements.txt
scripts/maintainer.requirements.txt
scripts/min_requirements.py
tests/docker/bionic/Dockerfile

Backport of https://github.com/ARMmbed/mbedtls/pull/5197. Differences with the 3.x version:
* In 2.x, we don't need Python in most builds, and never on Windows. So I kept the changes in `.travis.yml` to a minimum.
* In 2.x, we do not and will not have Python requirements for drivers.

Backport 2.x: In-tree Python package requirements

---

docs/architecture/tls13-experimental.md

TLS1.3 MVP would benefit from a different curve group preference order in order to avoid a HelloRetryRequest (which are not yet handled), however, changing the curve group preference order would affect both TLS1.2 and TLS1.3, which is undesirable for something rare that can be relatively easily worked around.
This will close #5026, as we do not intend to implement the change described there (and this is the documentation change to explain why)
**READY**
NO  
NO

TLS1.3: Edit docs to explain not changing curve order.

---

ChangeLog.d/build-without-sha.txt
include/mbedtls/entropy.h
library/bignum.c

Trivial backport of https://github.com/ARMmbed/mbedtls/pull/5167 + changelog entry

Backport 2.16: Fix builds when config.h only defines MBEDTLS_BIGNUM_C

---

ChangeLog.d/build-without-sha.txt
include/mbedtls/entropy.h
library/bignum.c
programs/fuzz/common.c

Backport of https://github.com/ARMmbed/mbedtls/pull/5269

Backport 2.x: Fix builds when config.h only defines MBEDTLS_BIGNUM_C

---

ChangeLog.d/build-without-sha.txt
include/mbedtls/entropy.h
library/bignum.c
programs/fuzz/common.c

Fixes #4929 and #4930
Backports: #5167, #5271.

Fix builds when config.h only defines MBEDTLS_BIGNUM_C

---

library/ssl_tls.c

fix a possible double reference on 'ticket'
when peer_cert/peer_cert_digest calloc failed.

[session] fix a session copy bug

---

include/mbedtls/ssl.h
include/psa/crypto_driver_common.h
include/psa/crypto_extra.h
include/psa/crypto_struct.h
library/psa_crypto.c
library/ssl_misc.h
tests/scripts/check_names.py

Resolve part of #4747: PSA crypto and TLS. This is a forward port of #5189.
Also fix #5191.
Supersedes #4821 with refinements to the TLS and PSA crypto parts, but without the classic crypto and X.509 parts.
Compared with #5189, the changes are similar, but there are differences.
* The commits are not in the same order: here, I grouped the changes to `check_names.py` at the beginning, instead of mixed with others near the end.
* The changes in headers could not be rebased due to the extensive presence of `MBEDTLS_PRIVATE`. I applied similar changes manually and re-did the code size measurements. I didn't spend much time experimenting to see if other variations might be better in 3.x. I consider it an objective to align the field types between the branches where possible, but I don't think …

Reorder structure fields to maximize usage of immediate offset access

---

ChangeLog.d/semi-public-structure-fields.txt
include/mbedtls/ssl.h
include/mbedtls/ssl_internal.h
include/psa/crypto_driver_common.h
include/psa/crypto_extra.h
include/psa/crypto_struct.h
library/psa_crypto.c
library/psa_crypto_aead.c
tests/scripts/check_names.py

Resolve #4747 for 2.x, i.e. without breaking the API.
This is a backport of https://github.com/ARMmbed/mbedtls/pull/4821. The two currently differ significantly; I propose to rework https://github.com/ARMmbed/mbedtls/pull/4821 to be a forward-port of this plus the crypto parts that are not suitable for 2.x due to being API breaks.
Also fix https://github.com/ARMmbed/mbedtls/issues/5191.
----
Code size for  2290afc2d4419c34fd58f0894670d01cb756ac3c → c0656b43f1e1489f247777be336ae57121efe99f (arm-none-eabi-gcc 7.3.1, build_arm_none_eabi_gcc_m0plus build):
* `baremetal` config: 435089 → 433521 (save 1568 bytes)
* `config-suite-b.h` + `MBEDTLS_ECDH_LEGACY_CONTEXT` + `MBEDTLS_ECP_RESTARTABLE` + `MBEDTLS_NO_PLATFORM_ENTROPY` - `MBEDTLS_NET_C`: 131083 → 130555 (save 528 bytes)

Backport 2.x: Reorder structure fields to maximize usage of immediate offset access

---

include/mbedtls/cmac.h

Improve the wording of the documentation of some of the CMAC operations. This should make these functions easier to use, and prevent misunderstandings (see #5241, for example).
Backports: #5280, #5281

Reword documentation of CMAC operations

---

include/mbedtls/cmac.h

Backport 2.x: Reword documentation of CMAC operations

---

programs/aes/crypt_and_hash.c

Add missing checks for return values in the crypt and hash sample programs. As coverity spotted we usually check these, as they can error.
Backport to 2.x of #5295
**READY**
NO

Backport 2.x: Add checks for return values to md functions in crypt and hash

---

programs/aes/crypt_and_hash.c

Add missing checks for return values in the crypt and hash sample programs. As coverity spotted we usually check these, as they can error.
**READY**
Yes 
[2.x](https://github.com/ARMmbed/mbedtls/pull/5299)
[2.16 ](https://github.com/ARMmbed/mbedtls/pull/5300)
NO

Add checks for return values to md functions in crypt and hash

---

tests/suites/test_suite_cipher.function

Found by coverity, a missed checked return on mbedtls_cipher_setup()
**READY**
Yes 
[2.x](https://github.com/ARMmbed/mbedtls/pull/5301)
[2.16](https://github.com/ARMmbed/mbedtls/pull/5302)
NO

Add checked return to cipher setup in Cipher tests

---

tests/suites/test_suite_cipher.function

Found by coverity, a missed checked return on mbedtls_cipher_setup()
Backport of #5297 
**READY**
NO

Backport 2.x : Add checked return to cipher setup in Cipher tests

---

tests/suites/test_suite_cipher.function

Found by coverity, a missed checked return on mbedtls_cipher_setup()
Backport of #5297 
**READY**
NO

Backport 2.16: Add checked return to cipher setup in Cipher tests

---

programs/aes/crypt_and_hash.c
tests/suites/test_suite_cipher.function

Errors caught by Coverity.
Backports: [2.x](https://github.com/ARMmbed/mbedtls/pull/5306), [2.16](https://github.com/ARMmbed/mbedtls/pull/5307)

Missing error checks + test bug on unlikely failure

---

ChangeLog.d/twos_complement_representation.txt
README.md

Backport of https://github.com/ARMmbed/mbedtls/pull/5290
Aligning documentation changes with the ask for #5264. This change is adding wording to state expliciticly what has already been assumed in the code before.
There are no functional changes in the code-base
Ready

Backport 2.x: Document platform architecture portability constraints

---

ChangeLog
ChangeLog.d/twos_complement_representation.txt
README.md

Aligning documentation changes with the ask for #5264. This change is adding wording to state expliciticly what has already been assumed in the code before. 
There are no functional changes in the code-base
**Ready**
[2.x backport](https://github.com/ARMmbed/mbedtls/pull/5308) (not applicable to 2.16 LTS)

Document platform architecture portability constraints

---

ChangeLog.d/check-return.txt
ChangeLog.d/ssl-mac-zeroize.txt
include/mbedtls/md.h
library/ssl_msg.c
library/ssl_tls.c

Check the return values of HMAC functions. This fixes low-severity Coverity defects. We had done a pass on `mbedtls_md_` hash functions, but not on `mbedtls_md_hmac_` functions. Declare HMAC functions as check-return-typical, so that compilers warn if we forget.
Also zeroize some intermediate variables, which is something I noticed when looking at this part of the code.
Needs backports: [2.x](https://github.com/ARMmbed/mbedtls/pull/5314), [2.16](https://github.com/ARMmbed/mbedtls/pull/5315)

Check HMAC return values

---

ChangeLog.d/check-return.txt
ChangeLog.d/ssl-mac-zeroize.txt
include/mbedtls/md.h
library/ssl_msg.c
library/ssl_tls.c

Backport of https://github.com/ARMmbed/mbedtls/pull/5313.
The principle is the same, but there are more places to modify and the same places don't all port seamlessly due to the extra code in 2.x for TLS 1.0/1.1 and SSLv3.

Backport 2.x: Check HMAC return values

---

ChangeLog.d/mac-zeroize.txt
ChangeLog.d/ssl-mac-zeroize.txt
library/cipher.c
library/psa_crypto.c
library/rsa.c
library/ssl_cookie.c
library/ssl_tls.c

As suggested by @mpg, when we do a constant-time comparison, usually at least one of the values is sensitive and should be zeroized. Typically in `ct_memcmp(mac, expected_mac, …)`, leaking `expected_mac` through a memory disclosure vulnerability allows the attacker to send data with an invalid MAC learn the correct MAC value and send the same data again with the correct MAC.
My audit of constant-time comparisons:
```
grep -n -w -e mbedtls_ct_memcmp -e mbedtls_psa_safer_memcmp *.c
cipher.c:1197:        if( mbedtls_ct_memcmp( tag, check_tag, tag_len ) != 0 )
#1 tag: parameter
#2 check_tag: local variable, fixed
cipher.c:1219:        if( mbedtls_ct_memcmp( tag, check_tag, tag_len ) != 0 )
#1 tag: parameter
#2 check_tag: local variable, fixed
constant_time.c:49:int mbedtls_ct_memcmp( const …
```

Zeroize expected MAC/tag intermediate variables

---

ChangeLog.d/mac-zeroize.txt
ChangeLog.d/ssl-mac-zeroize.txt
library/cipher.c
library/psa_crypto.c
library/rsa.c
library/ssl_cookie.c
library/ssl_tls.c

Backport of https://github.com/ARMmbed/mbedtls/pull/5325.
Audit of constant-time comparisons: `grep -n -w -e mbedtls_ct_memcmp -e mbedtls_psa_safer_memcmp *.c` found the same spots as in `development`, and the zeroization status was the same in each location. So the fix is a rebase of the fix on `development`.
Differences in rebase:
* `mbedtls_ssl_parse_finished`: several merge conflicts due to removed SSL3 code and changed error codes. The resolution is to manually apply the same idiom for each chunk: take the 2.28- code and change `return( foo );` to `ret = foo; goto exit;`.

Backport 2.2x: Zeroize expected MAC/tag intermediate variables

---

ChangeLog.d/mac-zeroize.txt
ChangeLog.d/ssl-mac-zeroize.txt
library/cipher.c
library/rsa.c
library/ssl_cookie.c
library/ssl_tls.c

Backport of #5325.
Audit of constant-time comparisons:
```
$ grep -n -e _memcmp *.c
cipher.c:104:static int mbedtls_constant_time_memcmp( const void *v1, const void *v2, size_t len )
cipher.c:983:        if( mbedtls_constant_time_memcmp( tag, check_tag, tag_len ) != 0 )
cipher.c:1005:        if( mbedtls_constant_time_memcmp( tag, check_tag, tag_len ) != 0 )
nist_kw.c:86:static inline unsigned char mbedtls_nist_kw_safer_memcmp( const void *a, const void *b, size_t n )
nist_kw.c:451:        diff = mbedtls_nist_kw_safer_memcmp( NIST_KW_ICV1, A, KW_SEMIBLOCK_LENGTH );
nist_kw.c:500:        diff = mbedtls_nist_kw_safer_memcmp( NIST_KW_ICV2, A, KW_SEMIBLOCK_LENGTH / 2 );
rsa.c:107:static inline int mbedtls_safer_memcmp( const void *a, const void *b, size_t n )
rsa.c:2142:    if( …
```

Backport 2.16: Zeroize expected MAC/tag intermediate variables

---

library/CMakeLists.txt
library/Makefile
tests/scripts/check-generated-files.sh

Fix intermittent failure of parallel builds from a fresh checkout, as seen recently in the `code-coverage` nightly CI job (https://jenkins-mbedtls.oss.arm.com/job/mbed-tls-nightly-tests/2281/, https://jenkins-mbedtls.oss.arm.com/job/mbed-tls-nightly-tests/2284/).
A few code-coverage runs to test: [1](https://jenkins-mbedtls.oss.arm.com/job/mbedtls-release-new/781/) [2](https://jenkins-mbedtls.oss.arm.com/job/mbedtls-release-new/782/) [3](https://jenkins-mbedtls.oss.arm.com/job/mbedtls-release-new/783/)
Not applicable to older branches.

List ssl_debug_helpers_generated.h in generated files

---

CMakeLists.txt

A common use case (see for example the TF-M project [here](https://git.trustedfirmware.org/TF-M/trusted-firmware-m.git/)) is to build mbed TLS as as subproject in a bigger project by including the mbed TLS CMakeLists.txt using the `add_subdirectory(...)` function in the outer project CMakeLists.txt. Several operations that are currently performed in the mbed TLS CMakeLists.txt (e.g. Package configuration, Target export, and Target installation) are not suited for this scenario. With this PR, the CMakeLists.txt of mbed TLS is amended so it's capable to detect if it's being included by some other project CMakeLists.txt. In that case, it will disable the Target export/installation and package configuration. The default behaviour remains unchanged (i.e. in all other cases the build system …

Make CMakeLists.txt discover if mbed TLS is being built as subproject

---

scripts/generate_ssl_debug_helpers.py

Change 'tranlation' -> 'translation' in the name of a
method in `scripts/generate_ssl_debug_headers.py`.

Fix typo in python script method name

---

scripts/bump_version.sh

Quick fix to repair `bump_version.sh` in 3.x.
Backports: no, `build_info.h` was introduced in 3.0.
ChangeLog: no, internal script.

bump_version: Fix spurious replacement in build_info.h

---

tests/scripts/test_psa_compliance.py

This PR [updates our fork of psa-arch-tests](https://github.com/bensze01/psa-arch-tests/compare/fixes-for-mbedtls-2..fix-multipart-aead) to a version that fixes several defects in the multipart AEAD tests, and removes these tests from the expected  failures list.
**READY**
No, Mbed TLS 2.28 does not support multipart AEAD

Fix the multipart AEAD compliance tests

---

ChangeLog.d/mbedtls_ssl_comfig_defaults-memleak.txt
library/ssl_tls.c

Reset dhm_P and dhm_G if call to mbedtls_ssl_config_defaults() repeated
to avoid leaking memory.
Signed-off-by: Glenn Strauss <gstrauss@gluelogic.com>
**READY**
Not required, IMHO, but could be backported.  In mbedtls 3.0.0, `mbedtls_ssl_config` members `dhm_P` and `dhm_G` are private, so routines underlying `mbedtls_ssl_config_defaults()` should avoid leaking memory if `mbedtls_ssl_config_defaults()` is called more than once.  If `mbedtls_ssl_config_defaults()` is called more than once by an application, then with earlier versions of mbedtls, the application could call `mbedtls_mpi_free()` on `dhm_P` and `dhm_G`.
Test for memory leak not provided.
Observe that `mbedtls_ssl_config_free()` calls `mbedtls_mpi_free()` on `dhm_P` and `dhm_G` conf members.
Observe that …

Reset dhm_P and dhm_G if config call repeated; avoid memory leak

---

ChangeLog.d/mbedtls_ssl_config_defaults-memleak.txt
library/ssl_tls.c

Reset dhm_P and dhm_G if call to mbedtls_ssl_config_defaults() repeated
to avoid leaking memory.
Signed-off-by: Glenn Strauss <gstrauss@gluelogic.com>
**READY**
Branch 2.28 (this PR)
Development PR (#5353)
Test for memory leak not provided.
Observe that `mbedtls_ssl_config_free()` calls `mbedtls_mpi_free()` on `dhm_P` and `dhm_G` conf members.
Observe that `mbedtls_ssl_config_defaults()` calls `mbedtls_ssl_conf_dh_param_bin()`, and if `mbedtls_ssl_config_defaults()` is called more than once, then `mbedtls_ssl_conf_dh_param_bin()` is called more than once, and inside `mbedtls_ssl_conf_dh_param_bin()`, conf members `dhm_P` and `dhm_G` are overwritten.  They should be freed before being overwritten.  Observer in `mbedtls_ssl_conf_dh_param_bin()` that if there is an error, then …

Backport 2.28: Reset dhm_P and dhm_G if config call repeated

---

include/mbedtls/check_config.h
include/mbedtls/pk.h
include/mbedtls/ssl.h
library/cipher_wrap.h
library/pk.c
library/pk_wrap.c
library/pkwrite.c
library/ssl_misc.h
library/ssl_tls.c
programs/ssl/ssl_client2.c
programs/ssl/ssl_server2.c
programs/ssl/ssl_test_lib.h
tests/scripts/all.sh
tests/suites/test_suite_ssl.function

Fix library references, tests and programs.
Testing is performed in the already present all.sh test.
Fixes #5259.

Make KEY_ID_ENCODES_OWNER compatible with USE_PSA_CRYPTO

---

include/mbedtls/check_config.h

PKCS5 depends on MD, but is missing a config check resulting in
obscure errors on invalid configurations.
Signed-off-by: Sebastian Bøe <sebastian.boe@nordicsemi.no>
Backport: #5439

Add missing config check for PKCS5.

---

include/mbedtls/check_config.h

PKCS5 depends on MD, but is missing a config check resulting in
obscure errors on invalid configurations.
Backport of #5438.

Backport 2.28: Add missing config check for PKCS5.

---

ChangeLog.d/ssl_erver_ticket_aead_option.txt
programs/ssl/ssl_server2.c
tests/ssl-opt.sh

Session tickets can be protected using any AEAD construct according to the documentation but we only ever test the default value. Since we're going to change that part, it needs to be tested.
Resolve #5181

TLS Cipher 1a: extend testing of tickets

---

ChangeLog.d/pkparse-pkcs8-unencrypted-no-alloc.txt
library/pkparse.c

Resolve #5304.
This is an optimization, so I don't think we should backport to 2.28 LTS.

mbedtls_pk_parse_key: don't allocate if not needed

---

ChangeLog.d/mbedtls_ssl_get_ciphersuite_id.txt
include/mbedtls/ssl.h
include/mbedtls/ssl_ciphersuites.h
library/ssl_ciphersuites.c
library/ssl_tls.c
programs/ssl/ssl_client2.c
programs/ssl/ssl_server2.c
programs/ssl/ssl_test_lib.h
tests/ssl-opt.sh

Add accessors for ciphersuite info
Signed-off-by: Glenn Strauss <gstrauss@gluelogic.com>
**READY**
NO  
YES
follow-up from #5331 migration issues
alternative to #5417 proposal

Add accessors for ciphersuite info

---

include/mbedtls/asn1.h
include/mbedtls/config.h
include/mbedtls/ctr_drbg.h
include/mbedtls/ecp.h
include/mbedtls/entropy.h
include/mbedtls/hkdf.h
include/mbedtls/hmac_drbg.h
include/mbedtls/memory_buffer_alloc.h
include/mbedtls/pem.h
include/mbedtls/platform.h
include/mbedtls/platform_time.h
include/mbedtls/ssl.h
include/mbedtls/ssl_cache.h
include/mbedtls/ssl_cookie.h
include/mbedtls/x509.h
include/mbedtls/x509_crl.h
include/mbedtls/x509_crt.h
include/mbedtls/x509_csr.h

Clarify section names next to closing braces.
Backport of https://github.com/ARMmbed/mbedtls/pull/5367
Partially fixing Issue #3497
Related PRs: #5371, #5372

Backport 2.28: doxygen: add missing asterisk to group closures

---

tests/ssl-opt.sh

Add a TLS test case where both the client and the server require authentication and both use a non-CA self-signed certificate. This came up in a recent support request and I couldn't find a TLS test that ensured that trusting a self-signed certificate without the CA flag works.

Add positive test case with self-signed certificates

---

library/bignum.c

This PR removes code from the Montgomery multiplication routine
`mpi_montmul()` which seems to serve no purpose.
Details: `mpi_montmul()` uses a temporary storage `T` for intermediate
results which is assumed to be of twice the size as the inputs to be
multiplied, and which is used as follows: After the i-th (i=0,1,...)
iteration, the n-limb word starting at `T->p + i + 1` contains the
Montgomery multiplication of B with the limbs 0,..,i of A, and the
variable `d` points to `T->p + i + 1`. In particular, after `n` iterations,
`T->p + n` holds the full multiplication
(subject to conditional subtraction).
As a consequence of this way of using the temporary `T`, the contents
of `{T->p, ..., T->p + i}` are irrelevant after the i-th iteration. Nonetheless, 
the code copies `A[i]` to `T->p[i]` …

Remove redundant write operation in Montgomery multiplication

---

include/mbedtls/mbedtls_config.h

Missed during https://github.com/ARMmbed/mbedtls/pull/5380. Local `check_files.py` passed.

Remove incorrect incompatibility information about `MBEDTLS_PSA_CRYPTO_KEY_ID_ENCODES_OWNER` from mbedtls_config.h

---

library/ssl_misc.h

Found by Coverity, but some compilers could also be unhappy about it.
**READY**
NO  - this is new in development.

Avoid dead code in some configurations

---

ChangeLog.d/tls13_f_export_keys.txt
library/ssl_tls13_keys.c

Summary:
For TLS 1.3, the client random is in the [first part](https://github.com/ARMmbed/mbedtls/blob/development/library/ssl_tls13_client.c#L709-L711) of `randbytes`, while the server random is the [second part](https://github.com/ARMmbed/mbedtls/blob/development/library/ssl_tls13_client.c#L1112-L1115).
When we do the `f_export_keys`, the [order of client random and server random](https://github.com/ARMmbed/mbedtls/blob/development/library/ssl_tls13_keys.c#L1013-L1014) is not matching the definition of [mbedtls_ssl_export_keys_t](https://github.com/ARMmbed/mbedtls/blob/development/include/mbedtls/ssl.h#L1207-L1208). Fix it by swapping the order.
Test Plan:
Check the log to make sure the NSS log (`CLIENT_RANDOM`) is aligned with actual `client hello, random bytes`.
```
diff --git …
```

Swap the client and server random for TLS 1.3 f_export_keys

---

library/constant_time.c

Don't inline mbedtls_mpi_safe_cond_assign on MSVC/ARM64 to avoid a compiler bug. This addresses https://github.com/ARMmbed/mbedtls/issues/5467.
READY
YES
Backport to 2.28: https://github.com/ARMmbed/mbedtls/pull/5468
This was introduced in 2.27 and I don't think that's maintained anymore? So 2.28 is the furthest the backport is needed.

Don't inline mbedtls_mpi_safe_cond_assign on MSVC/ARM64 to avoid a compiler bug

---

library/constant_time.c

Don't inline mbedtls_mpi_safe_cond_assign on MSVC/ARM64 to avoid a compiler bug. This addresses https://github.com/ARMmbed/mbedtls/issues/5467. Backport of #5469 
READY
NO  
This was introduced in 2.27 and I don't think that's maintained anymore? So 2.28 is the furthest the backport is needed.

Backport 2.28: Don't inline mbedtls_mpi_safe_cond_assign on MSVC/ARM64 to avoid a compiler bug

---

programs/ssl/ssl_client2.c
programs/ssl/ssl_server2.c
tests/ssl-opt.sh

Small tweak to a message in test programs that I found misleading.
The message is only misleading when there's no second key (“none” vs “unknown”), so this is mostly about the server. The server doesn't print this message in 2.28, so no backport needed.

Clarify key types message from ssl_client2 and ssl_server2

---

include/mbedtls/ssl.h
library/ssl_cli.c
library/ssl_misc.h
library/ssl_tls.c

`ssl->client_auth` is used to indicate CertificateRequest received from server. If received, CertificateVerfiy and Certificate MUST be sent by client. The variable is used only in handshake stage.
- Guard it with `MBEDTLS_SSL_PROTO_TLS1_2`
- Move it to `ssl->handshake`
**READY**

Move client_auth to handshake

---

ChangeLog.d/mbedtls_ssl_ticket_rotate.txt
include/mbedtls/ssl_ticket.h
library/ssl_ticket.c
programs/ssl/ssl_server2.c
tests/ssl-opt.sh

Add `mbedtls_ssl_ticket_rotate()` for ticket rotation
#5421 Add access to some fields of `mbedtls_ssl_ticket`
**READY**
NO  
NO

Add mbedtls_ssl_ticket_rotate() for ticket rotation

---

docs/architecture/psa-migration/psa-limitations.md

This is a quick follow-up to #5004 with simple fixes for things that were reported after it was merged.

Fixup psa migration documentation

---

ChangeLog.d/use-psa-ecdhe-curve.txt
include/mbedtls/psa_util.h
library/ssl_cli.c
library/ssl_misc.h
library/ssl_tls.c

Resolves #5291 
**READY**
Partial: the bug fix should be backported to 2.28 - https://github.com/ARMmbed/mbedtls/pull/5536
NO - the API/ABI checker will complain about changes in `psa_util.h`, but there's a warning at the top of the file saying it's not part of the public API.
The bug can be reproduced by applying the following patch to make the server misbehave:
```diff
diff --git a/library/ssl_srv.c b/library/ssl_srv.c
index a8b1e7de6c2e..0e52a1edb893 100644
--- a/library/ssl_srv.c
+++ b/library/ssl_srv.c
@@ -3097,9 +3097,10 @@ curve_matching_done:
}
MBEDTLS_SSL_DEBUG_MSG( 2, ( "ECDHE curve: %s", (*curve)->name ) );
+        MBEDTLS_SSL_DEBUG_MSG( 0, ( "ECDHE curve overide: P-192" ) );
if( ( ret = mbedtls_ecdh_setup( &ssl->handshake->ecdh_ctx,
- …
```

Cleanup PSA-based ECDHE in TLS 1.2

---

ChangeLog.d/use-psa-ecdhe-curve.txt
include/mbedtls/ssl_internal.h
library/ssl_cli.c
library/ssl_tls.c

This is the 2.28 backport of the relevant part of #5456 - just the bug fix. See commit messages for details of the differences between branches.

[Backport 2.28] Fix PSA-based ECDH in TLS 1.2

---

scripts/ci.requirements.txt
scripts/maintainer.requirements.txt

Backport of a commit from https://github.com/ARMmbed/mbedtls/pull/5218. Documentation only, but useful to have here to facilitate future backports.

2.28 only: Any package used in a script must be listed in ci.requirements.txt

---

tests/scripts/analyze_outcomes.py
tests/scripts/check_test_cases.py
tests/ssl-opt.sh

Test cases in `tests/opt-testcases` report themselves in the outcome file as being from the test suite `ssl-opt`. But the outcome analysis bases the test suite name on the file that the test case is in. (https://github.com/ARMmbed/mbedtls/issues/5391#issuecomment-1007453643) Reconcile the two.
https://jenkins-mbedtls.oss.arm.com/job/mbed-tls-pr-head/job/PR-5393-head/2/execution/node/5326/log/ shows that all of the not-executed TLS 1.3 test cases were false positives due to the test suite name mismatch. Thus this fixes #5391.
Also fix a potential bug in `ssl-opt.sh` whereby an error while listing `opt-testcases/*.sh` was ignored. This could lead to silently skipping test cases in an insufficiently populated out-of-tree build where `opt-testcases` isn't available.
Needs backports: for the …

Fix test suite name reporting of opt-testcases/tls13-compat.sh

---

programs/fuzz/common.c
programs/fuzz/fuzz_dtlsserver.c
programs/fuzz/fuzz_privkey.c

In fuzz_privkey, we switched over to using the dedicated dummy_rand() function, which uses ctr_drbg internally, and thus requires an initialised ctr_drbg_context to be passed in via p_rng when calling mbedtls_pk_parse_key(). Leaving the context as null will cause a null pointer dereference.
**READY**
NO  
NO
Test case from https://oss-fuzz.com/testcase?key=5126567532036096 should run clean. I have managed this locally using docker.

Fix null context when using dummy_rand with mbedtls_pk_parse_key()

---

ChangeLog.d/tls13_and_use_psa_crypto.txt
docs/architecture/tls13-support.md
library/ssl_tls.c
tests/opt-testcases/tls13-compat.sh
tests/scripts/generate_tls13_compat_tests.py
tests/ssl-opt.sh

Fix the incompatibility of the TLS 1.3 implementation with MBEDTLS_USE_PSA_CRYPTO.
READY
No, TLS 1.3 only.

Make TLS 1.3 compatible with MBEDTLS_USE_PSA_CRYPTO

---

library/ecp.c

This PR makes a number of small improvements to ECC arithmetic subroutines:
* https://github.com/ARMmbed/mbedtls/pull/5377/commits/5c8ea307b878a9860996972c5890c53d8655c525, https://github.com/ARMmbed/mbedtls/pull/5377/commits/76f897d6994ca95c64edf527127ecb9b82a0d071, https://github.com/ARMmbed/mbedtls/pull/5377/commits/0d629791e9143056d9b2c2eca793a02256054211, https://github.com/ARMmbed/mbedtls/pull/5377/commits/28ccb1cc90101bed8befcdfbdb961b5413975a2e, https://github.com/ARMmbed/mbedtls/pull/5377/commits/02a999b91a02144ba34ca9352d297408d37c67e8 and https://github.com/ARMmbed/mbedtls/pull/5377/commits/b8442cd9c6323a6a8255eecc94617becee5056ae remove local MPIs from ECP arithmetic subroutines
* https://github.com/ARMmbed/mbedtls/pull/5377/commits/ce29ae84dd425877178b81ee9fdf1491ef623943, …

Minor improvements to ECC arithmetic subroutines

---

scripts/driver.requirements.txt

Fix CI breakage on FreeBSD due to the release of a new version of a Python package (`markupsafe`, dependency of `Jinja2`):
```
Gen   psa_crypto_driver_wrappers.c
Traceback (most recent call last):
File "../scripts/generate_driver_wrappers.py", line 26, in <module>
import jinja2
File "/home/ec2-user/.local/lib/python3.8/site-packages/jinja2/__init__.py", line 33, in <module>
from jinja2.environment import Environment, Template
File "/home/ec2-user/.local/lib/python3.8/site-packages/jinja2/environment.py", line 15, in <module>
from jinja2 import nodes
File "/home/ec2-user/.local/lib/python3.8/site-packages/jinja2/nodes.py", line 19, in <module>
from jinja2.utils import Markup
File "/home/ec2-user/.local/lib/python3.8/site-packages/jinja2/utils.py", line 647, in <module>
from markupsafe …
```

Require an older version of markupsafe for the sake of older Jinja2

---

library/ssl_tls13_invasive.h
library/ssl_tls13_keys.c
tests/suites/test_suite_hkdf.function
tests/suites/test_suite_ssl.data
tests/suites/test_suite_ssl.function

TLS 1.3 code (ssl_tls13_keys.c) currently uses HKDF from the legacy API, mbedtls_hkdf_. The PSA API currently only provides the full HKDF, which TLS 1.3 uses its components HKDF-Extract and HKDF-Expand separately. As a temporary measure, we'll be implementing those within TLS 1.3 based on the psa_mac_ API, which waiting for PSA to be extended.
Resolve #5402

HKDF 1b: Implement Expand in TLS 1.3 based on PSA HMAC

---

ChangeLog.d/ssl_context-user_data.txt
ChangeLog.d/ssl_context-version_number.txt
ChangeLog.d/ssl_get_version_1_3.txt
include/mbedtls/ssl.h
library/ssl_debug_helpers.h
library/ssl_tls.c
tests/ssl-opt.sh
tests/suites/test_suite_ssl.function

I went through the private fields of `mbedtls_ssl_context` and found that there are three pieces of data that are conveyed only through private fields and lack accessor functions.
* No way to access context data outside of that callback's specific context. This prevents communicating between callbacks. I'm introducing a more general solution using a new field.
* No convenient way to access the version (https://github.com/ARMmbed/mbedtls/issues/5407). I added one.
* No way to access the handshake state (https://github.com/ARMmbed/mbedtls/issues/4383). I'm not resolving this here because I think we should not expose the state, we should instead expose high-level properties of the state, and the set of properties requires further discussion.
* I'm not convinced by …

Add accessors to mbedtls_ssl_context: user data, version

---

ChangeLog.d/raw-agreement-destroy-missing.txt
library/ssl_cli.c

Backport of https://github.com/ARMmbed/mbedtls/pull/5576.

Backport 2.28: Add missing key destruction calls in ssl_write_client_key_exchange

---

include/mbedtls/check_config.h

Trivial backport of https://github.com/ARMmbed/mbedtls/pull/4910

Backport 2.28: Add check_config checks for AEAD

---

include/psa/crypto.h
include/psa/crypto_extra.h

Backport of https://github.com/ARMmbed/mbedtls/pull/5371, except docs for some functions that don't exist in 2.28.
Also organize some of the errors in a better way.

Backport 2.28: doxygen: merge multiple descriptions of the same return codes

---

tests/CMakeLists.txt
tests/suites/test_suite_ssl.function

This was previously done for make in #2053. To avoid builds passing with one build system and failing with the other, align cmake with make.
Backport: I think not. It could break the way users run unit tests in a custom configuration. Having fewer warnings in the LTS version is not going to make future backports harder, so there's no significant advantage to backporting.

Build tests with -Wunused-function with cmake

---

tests/suites/test_suite_psa_crypto.function

When working with block cipher modes like GCM(PSA_ALG_IS_AEAD_ON_BLOCK_CIPHER),
aead_multipart_internal_func() should calculate the offset in the output buffer based on output_length, not using the offset of the input buffer(part_offset).
Backport: no (multipart AEAD didn't exist in 2.28)

Fix AEAD multipart incorrect offset in test_suite_psa_crypto.function

---

docs/proposed/psa-driver-interface.md

A few tweaks prompted by #5396.
The implementation-specific namespace syntax and the comment syntax may change depending on the resolution of an Arm-internal discussion to standardize this across all PSA JSON formats.

PSA driver description spec: minor tweaks to the JSON format

---

tests/scripts/check-python-files.sh

Running mypy was optional for a transition period when it wasn't installed on the CI. Now that it is, make it mandatory, to avoid silently skipping an expected check if mypy doesn't work for some reason.
This resolves a bug that for a while, mypy has been running on Travis but not on Jenkins, because `can_mypy` was returning false on Jenkins because the `packaging` package was not installed:
```
$ ./tests/scripts/check-python-files.sh 
Running pylint ...
--------------------------------------------------------------------
Your code has been rated at 10.00/10 (previous run: 10.00/10, +0.00)
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
ImportError: No module named 'packaging'
```
Backport: https://github.com/ARMmbed/mbedtls/pull/5589

Make mypy unconditional

---

library/pk_wrap.c
library/pkwrite.c
library/pkwrite.h

The max sizes of RSA & EC DER keys are used in `pk_wrap.c`, and in #5518, #5519, #5525, #5568, #5571
It's simpler to move & rename the defines separately in this PR.
**READY**
NO  
NO
`make test` must complet without fail.

Move max sizes of RSA & EC DER keys into public header

---

CMakeLists.txt
ChangeLog.d/cmake_msvc_utf8.txt

2.28 backport - build(msvc): always assume source files are in UTF-8

---

ChangeLog.d/md_info_from_ctx.txt
include/mbedtls/md.h
library/md.c
tests/suites/test_suite_md.function

I wanted to add getter functions to get details of the message digest from a `message_digest_context_t` struct. The existing getters operate on `md_info_t`, so if you only have the context, you can't get the details of the message digest.
I figured that the simplest solution is just to add a function that extracts the `md_info` member from the context. I'm open to instead implement functions that get the name, type, size, etc. from the context individually, if you prefer that.
**READY**
NO
NO

Add function to get message digest info from context

---

docs/architecture/testing/psa-storage-format-testing.md
scripts/abi_check.py
scripts/assemble_changelog.py
scripts/mbedtls_dev/macro_collector.py
scripts/min_requirements.py
tests/scripts/generate_psa_tests.py

Trivial backport of #4408. Before that, two commits from #4395 to re-align `assemble_changelog.py`.

Backport 2.28: Check storage format tests for regressions

---

docs/architecture/testing/psa-storage-format-testing.md
scripts/abi_check.py
scripts/assemble_changelog.py
scripts/mbedtls_dev/macro_collector.py
tests/scripts/generate_psa_tests.py

We validate the stability of the storage format through tests that ensure that a key produced by an older version can still be read by a newer version. Expand `abi_check.py` to complain if such tests are removed. Resolves #4481.
Design: make a list of the test data lines (lines with `function_name:parameter1:parameter2:…`) of generated PSA test cases in the old version and in the new version. Complain about lines in the old version that are missing from the new version.
Known issue: storage format test comparisons are reported in a simple text format, independent of `--brief`. I'm not sure it's worth the effort to align the reporting on the ABI/API comparisong.
Needs backport to 2.28: #5605. It's less critical there because the outputs are in the repository, but still useful because it …

Check storage format tests for regressions

---

ChangeLog.d/zeroize_key_buffers_before_free.txt
library/psa_crypto_storage.c

The PSA Crypto storage module uses dynamically-allocated buffers to buffer sensitive key material during the process of loading said key material from NVM, or storing it to NVM. To avoid leaking the key material through the heap, zero out the buffer before freeing it.
**READY**
Unsure, maintainer can make a decision
NO

Erase secrets in allocated memory before freeing said memory

---

library/pk_wrap.c
tests/suites/test_suite_x509write.function

In `library/pk_wrap.c`, provide an implementation of `rsa_sign_wrap` to use `psa_sign_hash()` instead of `mbedtls_rsa_pkcs1_sign()`.
Resolves #5162 
**READY**
NO
NO
test_suite_pk should run clean

PK: RSA signing

---

include/mbedtls/psa_util.h
library/ssl_misc.h
library/ssl_tls13_client.c
library/ssl_tls13_generic.c
library/ssl_tls13_keys.c
programs/ssl/ssl_client2.c

Implement the ECDHE computation in the TLS 1.3 ephemeral key exchange (as it is in MVP, so client-side only) using PSA.
**READY**
NO  
NO

TLS ECDH 2c: ECHDE in TLS 1.3 (client-side)

---

ChangeLog.d/add-mbedtls_md_starts-to-mbedtls_md_process-test.txt
tests/suites/test_suite_md.function

Add a call to `mbedtls_md_starts()` in the `mbedtls_md_process()`
test, as it violates the API usage. Fixes #2227.
**READY**
Yes 
Which branch?
`mbedtls-2.28`
This was discovered by running the test suite on NRF52840_DK target

Fix test md api violation

---

ChangeLog.d/add-mbedtls_md_starts-to-mbedtls_md_process-test.txt
tests/suites/test_suite_md.function

Backport 2.28: Fix test md api violation 2.28

---

ChangeLog.d/mbedtls_ssl_cert_cb.txt
include/mbedtls/ssl.h
library/ssl_misc.h
library/ssl_srv.c
library/ssl_tls.c
programs/ssl/ssl_server2.c
tests/ssl-opt.sh
tests/suites/test_suite_ssl.function

This PR sketches out a server certificate selection callback which is run unconditionally near the end of ClientHello (and right before mbedtls internals choose and use server certificate)
**READY**
Depends on: #5426
NO  
> If there is any API change, what's the incentive and logic for it.
#5430: "Add an unconditonnal (sic) end-of-ClientHello callback"
This PR sketches out a server certificate selection callback which is run unconditionally near the end of ClientHello (and right before mbedtls internals choose and use server certificate)
This leverages #5426: Add accessors to mbedtls_ssl_context: user data, version and is currently rebased onto that (not-yet-committed) branch.
Optional and included in this PR for interface discussion:
* reset/clear certificate list already set in …

server certificate selection callback

---

ChangeLog.d/MD-X.509-hashing.txt
library/x509_crt.c
library/x509write_crt.c
library/x509write_csr.c

Make x.509 use PSA for hashing (conditionally on MBEDTLS_USE_PSA_CRYPTO). This resolves #5157.
**READY**
NO  
NO
using psa_hash_compute() instead of mbedtls_md() in:
-x509_crt_verifycrl() in x509_crt.c
-mbedtls_x509write_crt_der() in x509write_crt.c
-mbedtls_x509write_crt_set_subject_key_identifier() in x509write_crt.c
-mbedtls_x509write_crt_set_authority_key_identifier() in x509write_crt.c
Changed psa_hash_operation_t to psa_hash_compute() in:
-x509_crt_check_signature()
-mbedtls_x509write_csr_der_internal()
run test_suite_x509parse and test_suite_x509write with MBEDTLS_USE_PSA_CRYPTO

feat: MD: X.509 hashing

---

ChangeLog.d/mbedtls_sha256_a64_crypto_acceleration.txt
include/mbedtls/check_config.h
include/mbedtls/mbedtls_config.h
library/sha256.c
scripts/config.py
tests/scripts/all.sh

Provide an additional pair of #defines, `MBEDTLS_SHA256_USE_A64_CRYPTO_IF_PRESENT` and `MBEDTLS_SHA256_USE_A64_CRYPTO_ONLY`. At most one of them may be specified. If used, it is necessary to compile with `-march=armv8-a+crypto`.
The `MBEDTLS_SHA256_PROCESS_ALT` and `MBEDTLS_SHA256_ALT` mechanisms continue to work, and are mutually exclusive with A64_CRYPTO.
There should be minimal code size impact if no A64_CRYPTO option is set.
**READY**
NO  
The coding standards say "a preferred maximum line length of 80 characters" rather than "a maximum line length of 80 characters" - in a very few places I had exceeded 80 characters by a small amount to improve readability (especially where a sequence of consecutive lines are similar).
Define either `MBEDTLS_SHA256_USE_A64_CRYPTO_IF_PRESENT` or …

SECLIB-667: Accelerate SHA-256 with A64 crypto extensions

---

ChangeLog.d/timeless.txt
include/mbedtls/platform.h
library/net_sockets.c
library/timing.c
library/x509_crl.c
library/x509_crt.c
programs/fuzz/common.c
programs/fuzz/common.h
programs/ssl/ssl_context_info.c
programs/ssl/ssl_server2.c
programs/ssl/ssl_test_lib.c
programs/ssl/ssl_test_lib.h
programs/test/query_config.c
programs/test/udp_proxy.c
scripts/data_files/query_config.fmt
tests/configs/config-wrapper-malloc-0-null.h
tests/include/baremetal-override/time.h
tests/scripts/all.sh
tests/suites/test_suite_timing.data

Backport of #3624. 
Fix builds that use `time.h` without `MBEDTLS_HAVE_TIME`. 
Changes compared to the original:
- `programs/fuzz/common.h` using `config.h` directly instead of `build_info.h`;
- `programs/test/query_config.c` uploaded.

Backport 2.28: Fix builds with MBEDTLS_HAVE_TIME disabled and test

---

library/ssl_srv.c

Implement the ECDHE part of the ECDHE-ECDSA and ECDHE-RSA key exchanges in (D)TLS 1.2 based on PSA when MBEDTLS_USE_PSA_CRYPTO is defined.
**READY**
NO  
Which branch?
NO

TLS ECDH 2a: server-side ECDHE-ECDSA and ECDHE-RSA (1.2)

---

include/mbedtls/ssl_ticket.h
library/ssl_ticket.c
tests/ssl-opt.sh

In `ssl_ticket.c`, use `psa_aead` instead of `mbedtls_cipher` in order to protect tickets when `MBEDTLS_USE_PSA_CRYPTO` is enabled.
Resolve #5203

TLS Cipher 2a: tickets: use PSA for protection

---

library/pk_wrap.c
tests/suites/test_suite_pk.function

In `library/pk_wrap.c`, provide an implementation of `rsa_decrypt_wrap` using `psa_asymmetric_decrypt()` instead of `mbedtls_rsa_pkcs1_decrypt()` when `MBEDTLS_USE_PSA_CRYPTO` is enabled.
Resolves #5160 
**READY**
NO  
NO
test_suite_pk should run clean

PK: RSA decryption

---

library/ssl_cli.c

Implement client-side the ECDH part of the ECDH-ECDSA and ECDH-RSA key exchange(s) in (D)TLS 1.2 based on PSA when MBEDTLS_USE_PSA_CRYPTO is defined.
**READY**
NO  
NO

TLS ECDH 2b: client-side static ECDH (1.2)

---

library/ssl_misc.h
library/ssl_msg.c
library/ssl_tls.c
library/ssl_tls13_client.c
library/ssl_tls13_generic.c

Fix #5499  by removing unnecessary flush of the output buffer, then expand the move of state changes from state handler sub-routines to the main handler (write states only).
READY
No, changes in TLS 1.3. 
We are not in a position where we can trigger easily asynchronous writes on the network in TLS 1.3 testing. Thus not in a position to add easily non regression tests for the changes done by this PR. Some tests in the prototype with both the client and the server being Mbed TLS implementation do provide regression tests though.
Thus to mitigate the absence of regression tests in this PR, I have created a [companion PR](https://github.com/hannestschofenig/mbedtls/pull/393) on the prototype branch with changes similar to the ones in this PR. We will merge it in the prototype when we merge …

TLS 1.3: One flush output

---

library/pk_wrap.c
tests/suites/test_suite_x509write.function

In `library/pk_wrap.c`, provide an implementation of `ecdsa_sign_wrap` to use `psa_sign_hash()` instead of `mbedtls_ecdsa_write_signature()`.
Resolves #5274
**READY**
NO 
NO
X509write suite failed:
```
Certificate Request check Server5 ECDSA, key_usage ................ FAILED
memcmp( buf, check_buf, pem_len - 1 ) == 0
at line 135, /home/narmstrong/projects/nordic/mbedtls/tests/suites/test_suite_x509write.function
```
because reference vector is calculated with `mbedtls_test_rnd_pseudo_rand`.
Using PSA DETERMINISTIC ECDSA in `pk_wrap` makes the test PASS, the only viable solution
is to disable the reference check and verify the signature instead.
test_suite_x509write and test_suite_pk should run clean

PK: ECDSA signing

---

include/mbedtls/ssl_cookie.h
library/ssl_cookie.c

In `ssl_cookie.c`, when `MBEDTLS_USE_PSA_CRYPTO` is enabled, move from using the `mbedtls_md_hmac` API to the `psa_mac` API, and from using the user-provided RNG for key generation to using `psa_generate_key()`.
Resolves #5174
**READY**
NO  
NO
N/A
`tests/ssl-opt.sh` must run clean

MD: HMAC in DTLS cookies

---

ChangeLog.d/add_final_delay_accessor
include/mbedtls/timing.h
library/timing.c
tests/suites/test_suite_ssl.data
tests/suites/test_suite_ssl.function

Add an accessor for mbedtls_timing_delay_context final delay (fin_ms) as requested in #5183 
Add a simple test for this in test_suite_ssl
This closes #5183 
**READY**
NO  
NO
test_suite_ssl should run clean.

Accessor for mbedtls_timing_delay_context final delay

---

library/ssl_srv.c
library/ssl_tls.c
tests/compat.sh

Restore full TLS compatibility testing that was broken in #5166 / #5262. Fixes #5629.
IN DEVELOPMENT
Yes
Which branch: [2.28](https://github.com/ARMmbed/mbedtls/pull/5660)

Restore full TLS compatibility testing

---

ChangeLog.d/mbedtls_sha512_a64_crypto_acceleration.txt
include/mbedtls/check_config.h
include/mbedtls/mbedtls_config.h
library/sha256.c
library/sha512.c
scripts/config.py
tests/scripts/all.sh

Provide an additional pair of #defines, `MBEDTLS_SHA512_USE_A64_CRYPTO_IF_PRESENT` and `MBEDTLS_SHA512_USE_A64_CRYPTO_ONLY`. At most one of them may be specified. If used, it is necessary to compile with `-march=armv8.2-a+sha3`.
The `MBEDTLS_SHA512_PROCESS_ALT` and `MBEDTLS_SHA512_ALT` mechanisms continue to work, and are mutually exclusive with `A64_CRYPTO`.
There should be minimal code size impact if no A64_CRYPTO option is set.
Note that the Neon-accelerated implementation was originally written by Simon Tatham for PuTTY, under the MIT licence; it is dual-licensed as Apache 2 with his kind permission. I have restructured it to match the Mbed TLS implementation; any mistakes are mine, not his.
**READY**
NO  
The coding standards say "a preferred maximum line length of 80 characters" …

SECLIB-667: Accelerate SHA-512 with A64 crypto extensions

---

library/threading.c

[Backport 2.28] Fix comment typo in threading.c

---

library/threading.c

Fixes #5349
sorry about the exessive pull requests, its my first issue fix i have done.
Signed-off-by: Artur Allmann <Artur.Allmann@tptlive.ee>
Notes:
fixed typo in /library/threading.c
**READY**
- This PR contains changes in the API. If this …

Fix comment typo in threading.c

---

ChangeLog.d/add_handshake_completion_accessor
include/mbedtls/ssl.h
library/ssl_msg.c
library/ssl_tls.c
tests/suites/test_suite_ssl.function

Add an accessor function so that the user can tell at what point the SSL handshake is over, and thus at what point they should stop calling mbedtls_ssl_handshake_step().
Change over all internal and test checks to use this function.
**READY**
NO  
NO
test_suite_ssl and ssl_opt.sh should both run clean.

Add mbedtls_ssl_is_handshake_over()

---

.travis.yml
BRANCHES.md
BUGS.md
CONTRIBUTING.md
README.md
include/mbedtls/config_psa.h
include/psa/crypto_config.h
scripts/ci.requirements.txt
tests/compat.sh
tests/scripts/all.sh
tests/ssl-opt.sh
tests/suites/test_suite_pk.data
tests/suites/test_suite_pk.function

Replace references to ARMmbed organisation with the new
org, Mbed-TLS, following project migration.
Backport of #5681

Update references to old Github organisation

---

ChangeLog.d/add_own_cid_accessors
include/mbedtls/mbedtls_config.h
include/mbedtls/ssl.h
library/ssl_tls.c
tests/suites/test_suite_ssl.data
tests/suites/test_suite_ssl.function

Add accessors to own CID within mbedtls_ssl_context, as per request in #5184
Add sanity tests for all of the own CID set / get/config functions.
**READY**
NO  
NO
test_suite_ssl should run clean

Accessors to own CID within mbedtls_ssl_context

---

library/pk_wrap.c
tests/suites/test_suite_pk.function

In `library/pk_wrap.c`, provide an implementation of `rsa_verify_wrap` to use `psa_verify_hash()` instead of `mbedtls_rsa_pkcs1_verify()` when `MBEDTLS_USE_PSA_CRYPTO` is enabled.
Resolves #5159 
**READY**
NO  
NO
test_suite_pk should run clean

PK: RSA verification

---

scripts/config.py
tests/scripts/all.sh

The `baremetal` configuration is, among other things, our default reference point for code size measurements. It includes debugging features that would not be enabled in production where code size is limited, which reduces the value code size reports on this configuration. Create a variant `baremetal_size` which excludes these debugging features.
This is a replacement for https://github.com/ARMmbed/mbedtls/pull/4428. I propose to backport it to 2.2x, but not to 2.16 which doesn't have `config.pl` and which is nearing end-of-life.
Backport (2.2x): https://github.com/ARMmbed/mbedtls/pull/5542

Disable debugging features in the primary code size measurement job

---

scripts/config.py
tests/scripts/all.sh

Backport of #4907. Identical except for a couple of options that exist in 2.28 but not in 3.x.

Backport 2.28: Disable debugging features in the primary code size measurement job

---

tests/suites/test_suite_pk.function

In one of the Pk RSA tests, it was possible (in an unlikely error case) for some `mbedtls_mpi` variables to be free'd without first being initialised, which could potentially cause an uninitialised pointer to used (for clearing memory) and/or heap damage.
Found by coverity.
**READY**
NO  
NO
test_suite_pk should run clean.

Prevent free of uninitialised MPI  variables

---

CONTRIBUTING.md

The LTS branch hasn't been updated in the contributing guidelines.
Deleting it instead of updating as the information is available at the
link above and deleting prevents similar mistakes in the future.

Fix LTS version in contributing guidelines

---

library/ssl_misc.h
library/ssl_tls13_client.c

This check can be removed as if the buffer is too small for the key, then export will fail.
Resolves: conversation https://github.com/Mbed-TLS/mbedtls/pull/5524#pullrequestreview-930492605 .

ssl_tls13_generate_and_write_ecdh_key_exchange(): remove redundant check

---

include/mbedtls/pk.h
library/pk.c
library/ssl_misc.h
library/ssl_tls.c
library/ssl_tls12_client.c
library/ssl_tls12_server.c
library/ssl_tls13_client.c
tests/ssl-opt.sh

This task is to implement server-side the ECDH part of the ECDH-ECDSA and ECDH-RSA key exchange(s) in (D)TLS 1.2 based on PSA when `MBEDTLS_USE_PSA_CRYPTO` is defined.
Resolves: #5320 
**READY**
NO 
NO
~Depends on #5613 to be merged first, will need to be rebased on top~ done
tests/ssl-opt.sh must run clean

TLS ECDH 3b: server-side static ECDH (1.2)

---

tests/ssl-opt.sh

Explain and fix the number of test runs in ssl-opt.sh, as was originally intended.
Probably fixes https://github.com/Mbed-TLS/mbedtls/issues/5279.
Backport of https://github.com/Mbed-TLS/mbedtls/pull/5686

Backport 2.28 - Fix an off-by-one error in ssl-opt.sh

---

ChangeLog.d/mbedtls_ssl_hs_cb_t.txt
include/mbedtls/ssl.h
library/ssl_tls.c

* Introduce mbedtls_ssl_hs_cb_t typedef
* Inline func for mbedtls_ssl_conf_cert_cb()
Follow-up PR from discussion with @mpg in #5454.
https://github.com/ARMmbed/mbedtls/pull/5454#discussion_r823488484
https://github.com/ARMmbed/mbedtls/pull/5454#discussion_r823549312
This PR aims to slightly improve the interface.  This PR is lower priority as this is not a fix to anything.
Related question: should all *new* interfaces which are simple getter/setter functions be inlined in the header when struct definition is visible, even if the inline func uses MBEDTLS_PRIVATE?  (e.g. setter/getter for `mbedtls_ssl_config` and `mbedtls_ssl_context` are available, but `struct mbedtls_ssl_handshake_params` (library/ssl_misc.h) is not visible.)  Note: This should not be done for older interfaces (until …

Introduce mbedtls_ssl_hs_cb_t typedef

---

include/mbedtls/config.h
library/timing.c
programs/test/udp_proxy.c
tests/suites/test_suite_timing.data

Allow the timing module to include time.h if the platform is suitable, even when MBEDTLS_HAVE_TIME is disabled.
Remove the dummy timing implementation.
Backport of https://github.com/Mbed-TLS/mbedtls/pull/5708
Follow-up after https://github.com/Mbed-TLS/mbedtls/pull/5563

Backport 2.28: Remove the dependency on MBEDTLS_TIME_H from the timing module

---

include/mbedtls/mbedtls_config.h
library/timing.c
programs/test/udp_proxy.c
tests/suites/test_suite_timing.data

Allow the timing module to include `time.h` if the platform is suitable, even when MBEDTLS_HAVE_TIME is disabled.
Remove the dummy timing implementation.
Follow-up after https://github.com/Mbed-TLS/mbedtls/pull/3624.

Remove the dependency on MBEDTLS_TIME_H from the timing module

---

ChangeLog.d/fix-windows-cmake-build-with-shared-libraries.txt
library/CMakeLists.txt

Fix link error on windows using cmake, when building a shared
Set the Library path as the current Binary Dir
This PR relates to #1130
The issue reporter notes this doesn't fix the said issue. This PR fixes an issue with similar symptom
**READY**
??
CMake biuld error
Checked on linux as well
~~~
mkdir build
cd build
cmake -DENABLE_TESTING=Off -DUSE_SHARED_MBEDTLS_LIBRARY=On ..
cmake --build .
~~~

Fix Shared Library compilation issue with Cmake

---

include/mbedtls/mbedtls_config.h
include/mbedtls/ssl.h

Based on #2831 - rebased and with signed-off-by line added; original author information is retained.
One of the original typos was already fixed independently as part of PR #5501.

Fix spelling of 'reasonable' in comments

---

include/mbedtls/config.h
include/mbedtls/ssl.h
include/mbedtls/ssl_ticket.h

Backport 2.28: Fix spelling of 'reasonable' in comments

---

configs/config-no-entropy.h

Fix typo, reatures -> features
READY
NO  
NO

Fix typo in config-no-entropy.h

---

ChangeLog.d/alert_reentrant.txt
library/ssl_msg.c

Backport 2.28 - make mbedtls_ssl_send_alert_message() reentrant

---

library/ssl_tls12_client.c
library/ssl_tls12_server.c

This task is to implement (both client-side and server-side) the ECDHE part of the ECDHE-PSK key exchange in (D)TLS 1.2 based on PSA when `MBEDTLS_USE_PSA_CRYPTO` is defined.
Resolves: #5318
NO 
NO
Depends on #5613 to be merged first, will need to be rebased on top
tests/ssl-opt.sh must run clean

TLS ECDH 3a: ECDHE-PSK (both sides, 1.2)

---

tests/compat.sh
tests/scripts/all.sh
tests/scripts/basic-build-test.sh

Clean up tests/compat.sh to improve maintainability by:
removing cipher suites we no longer support
remove checks on which cipher suites to use, now that we don't support anything lower than (D)TLS 1.2
Closes #4818
**READY**
Partial - https://github.com/Mbed-TLS/mbedtls/pull/5737
NO
This is a redo of #4863 as the branch it was based off evolved quite a bit and made rebasing or merging unecessarily complicated. This PR just cherry-picked the relevant commits.
- with config full: `tests/compat.sh -e '^$' -p mbedtls` no longer skips any test
- with config full: `tests/compat.sh` has the same output (modulo ordering) before and after

clean up compat.sh

---

tests/compat.sh
tests/scripts/basic-build-test.sh

This is a partial backport of #5006 - just the last two commits, which are the only part applicable to 2.28.

[backport 2.28] clean up compat.sh

---

library/bignum.c
library/bignum_internal.h
library/bn_mul.h
library/ecp_curves.c

__Context:__ The helper `mpi_mul_hlp()` performs a multiply-accumulate operation `d += s * b`, where `d,b` are MPIs represented as plain integer arrays, and `b` is a scalar.
Previously, only the length of `s` was specified, while `d` was assumed to be 0-terminated of unspecified length.
This was leveraged at the end of the core multiplication steps computing the first `limb(s)` limbs of `d + s*b`: Namely, the routine would keep on adding the current carry to `d` until none was left. This can, in theory, run for an arbitrarily long time if `d` has a tail of `0xFF`s, and hence the assumption of `0`-termination.
This solution is both fragile and insecure -- the latter because the carry-loop depends on the result of the multiplication.
__Changes:__ This PR ... 
* ... changes the signature of …

Make size of output in mpi_mul_hlp() explicit

---

library/bignum.c
library/bn_mul.h

__Dependencies:__ ~Based on #5701~ merged
This PR follows @mpg's patch in #5360 to simplify organization and use of our bignum inline assembly routines:
* `MULADDC_X1_[INIT|CORE|STOP]` must be defined 
* `MULADDC_X[2,4,8]_[INIT|CORE|STOP]` _can_ be defined if it offers speedup potential. If it is not defined, it is auto-derived from the next lower `MULADDC` macros.
* Instances of `MULADDC_HUIT` are thus renamed to `MULADDC_X8_CORE`.
* The x8-variants did not have their own `STOP`-macros previously, which made the code harder to read. This gets simpler now that every `MULADDC_Xi_xxx` family has their own `INIT` and `STOP`.
* The core multiplication routine `mpi_mul_hlp()` is simplified to always call the 8-fold code and then the 1-fold code. Since `MULADDC_X8_xxx` is always defined (even …

Simplify structure of bignum inline assembly

---

CMakeLists.txt

Signed-off-by: Anton Komlev <anton.komlev@arm.com>
Notes:
CMake build script has a condition depending on the building platform by checking WIN32 variable. That variable designates the target platfomr and the check result will be incorrect in cross-compiling. For the host platform, CMAKE_HOST_WIN32 variable shall be used.
**READY**
NO  
NO
Any …

Fix Windows build host detection

---

ChangeLog.d/dtls-cid-null.txt
configs/config-ccm-psk-dtls1_2.h
configs/config-ccm-psk-tls1_2.h
configs/config-suite-b.h
programs/ssl/ssl_server2.c
programs/test/dlopen.c
tests/scripts/all.sh
tests/scripts/test-ref-configs.pl
tests/ssl-opt.sh
tests/suites/test_suite_ssl.function

This is an incremental improvement to the ability to run `tests/ssl-opt.sh` in reduced configurations. The main completeness goals is for it to pass on `config/config-ccm-psk-dtls1_2.h` and `config-suite-b.h`, and to be roughly aligned with the 2.28 backport. Beyond that, there are a few miscellaneous improvements in automatic requirement detection.
* Add some missing `requires_xxx` statements.
* Deduce a few more requirements automatically from the parameters passed to the client and the server.
* In PSK-only builds, run some tests. (I don't seek to improve builds with PSK + asymmetric key exchange, but I don't think I'm making anything worse.)
* New configuration `config-ccm-psk-dtls1_2.h`, based on `config-ccm-psk-dtls1_2.h` but with a few more DTLS options and a smaller SSL buffer, so …

Run ssl-opt.sh in more reduced configurations

---

tests/scripts/curves.pl

Following a chat discussion with @mpg, resolve #5729 by removing testing of all-but-one curves.
Backport 2.28: https://github.com/Mbed-TLS/mbedtls/pull/5741

Don't test with all-but-one elliptic curves

---

programs/ssl/ssl_server2.c
tests/ssl-opt.sh

Test use of `MBEDTLS_PK_OPAQUE` RSA keys in the TLS library for TLS 1.2.
Resolves #5628 
**READY**
NO  
NO
Depends on #5634 
tests/ssl-opt.sh must run clean

RSA sign 3b: TLS 1.2 integration testing

---

library/ssl_misc.h
library/ssl_tls.c
library/ssl_tls12_client.c
library/ssl_tls12_server.c

Now that all the code uses PSA for ECDH(E) in 1.2 and 1.3, we can remove the `mbedtls_ecdh_context` field from `struct mbedtls_ssl_handshake_params` when it's not needed. (It is only needed when 1.2 is enabled and `USE_PSA_CRYPTO` is disabled.)
Resolves #5322 
**READY**
NO  
NO
Depends on #5611
test_suite_ssl, ssl-opt.sh and compat.sh must run clean

TLS ECDH 4: remove legacy context

---

tests/suites/test_suite_x509write.data
tests/suites/test_suite_x509write.function

Test use of MBEDTLS_PK_OPAQUE RSA keys in the X.509 library. A large part of X.509 (parsing and verification) is only concerned with public keys; since opaque keys are private, there are only a few places to test.
Resolves #5627 
**READY**
NO  
NO
Depends on #5634
test_suite_x509write must run clean

RSA sign 3a: X.509 integration testing

---

include/mbedtls/memory_buffer_alloc.h
library/memory_buffer_alloc.c
programs/test/benchmark.c
scripts/ecc-heap.sh

This PR improves benchmarking of ECC heap usage, by printing out the number of calls to alloc/free (in addition to peak heap usage) in the benchmark program when `MBEDTLS_MEMORY_DEBUG` is enabled.
This is used, for example, by `scripts/ecc-heap.sh`.
This PR also fixes one bug and does a clean-up while at it.
Related: #5377 
**READY**
The bug fixed is not present in 2.28, and the rest are test script improvements. Backport of the test script improvements: https://github.com/Mbed-TLS/mbedtls/pull/5744
No ChangeLog as the bug and changes are only in a utility program.

Improve benchmarking of ECC heap usage

---

tests/suites/test_suite_ecdsa.function

This is the 2.28 backport of #5755 - entirely straighforward.

[Backport 2.28]  Expand negative coverage of ECDSA verification

---

tests/suites/test_suite_ecdsa.function

Motivated by CVE-2022-21449, to which we're not vulnerable, but we didn't have a test for it. So here it is.
**READY**
Yes - testing improvement
```
make CFLAGS='--coverage -g3 -Og' LDFLAGS=--coverage -C tests test_suite_ecdsa
(cd tests && ./test_suite_ecdsa)
$FAVOURITE_BROWSER Coverage/library/ecdsa.c.gcov.html#560
```

Expand negative coverage of ECDSA verification

---

library/sha256.c
library/sha512.c

Hide unnecessarily public functions in SHA-256 and SHA-512 A64 acceleration

---

library/ssl_misc.h
library/ssl_msg.c
library/ssl_ticket.c
library/ssl_tls.c
library/ssl_tls12_server.c

This task is to create that enum and any helper function that's useful, and using them to simplify all the places in the code that currently use `MBEDTLS_MODE_xxx` / `cipher_get_mode()`.
Resolves #5668 
**READY**
NO 
NO
test_suite_ssl & ssl-opt.sh must run clean

Cipher cleanup: abstract TLS mode

---

ChangeLog.d/doc-x509-profile-pk.txt
include/mbedtls/x509_crt.h

This is the 2.28 backport of #2082 - entirely straightforward.

[Backport 2.28] Fix documentation of allowed_pks field in mbedtls_x509_crt_profile

---

ChangeLog.d/doc-x509-profile-pk.txt
include/mbedtls/x509_crt.h

This PR fixes the documentation bug #1992; see there for more information.
2.28 backport: https://github.com/Mbed-TLS/mbedtls/pull/5778

Fix documentation of allowed_pks field in mbedtls_x509_crt_profile

---

ChangeLog.d/psk_to_ms_mixed_psk.txt

Add change log for mixed-psk that is missing here https://github.com/Mbed-TLS/mbedtls/pull/5726.
**READY**

Add change log entry for mixed-psk

---

tests/ssl-opt.sh

Test use of RSA opaque keys for client authentication with TLS 1.3.
Resolved #5712
**READY**
NO 
NO
Depends on #5709 && #5728
ssl-opt.sh must run clen

RSA-PSS sign 2: TLS 1.3 integration testing

---

ChangeLog.d/psa_crypto_config_file.txt
include/mbedtls/config.h
include/mbedtls/config_psa.h
programs/test/query_config.c
scripts/config.py
tests/scripts/all.sh

Complete backport of https://github.com/Mbed-TLS/mbedtls/pull/5654 with the new PSA config file macros as well as the documentation and test improvements.
We don't normally backport new features, but this one has no impact on users who don't use it (e.g. no impact on code size) and minimal risk of bugs (unlikely to cause a bug if you don't use it). In maintenance terms, it's an additional thing, but we want to use it to simplify testing in a way that applies to both 3.x and 2.28, so it's easier on balance to have the feature in 2.28.

Backport 2.28: Support alternative MBEDTLS_PSA_CRYPTO_CONFIG_FILE

---

ChangeLog.d/psa_crypto_config_file.txt
include/mbedtls/config_psa.h
include/mbedtls/mbedtls_config.h
scripts/config.py
tests/scripts/all.sh

Support an alternative `MBEDTLS_PSA_CRYPTO_CONFIG_FILE`, and an additional `MBEDTLS_PSA_CRYPTO_USER_CONFIG_FILE`, on the model of `MBEDTLS_CONFIG_FILE` and `MBEDTLS_USER_CONFIG_FILE`.
I added tests to `all.sh`. Using the new macros in other test components (e.g. accel ones) is out of scope of this pull request.
Backport: https://github.com/Mbed-TLS/mbedtls/pull/5740. I decided to backport the new feature and not just the documentation improvements because we'd like to use that to simplify the accelerator tests, which are present in 2.28.

Support alternative MBEDTLS_PSA_CRYPTO_CONFIG_FILE

---

include/mbedtls/config_psa.h
include/psa/crypto_builtin_primitives.h
include/psa/crypto_config.h
scripts/mbedtls_dev/crypto_knowledge.py
scripts/mbedtls_dev/macro_collector.py
tests/scripts/generate_psa_tests.py
tests/scripts/test_psa_constant_names.py
tests/src/psa_exercise_key.c
tests/suites/test_suite_psa_crypto.data
tests/suites/test_suite_psa_crypto.function
tests/suites/test_suite_psa_crypto_storage_format.function

When testing that a stored key can be read back, don't just export it, also perform operations with the key.
This is a rework of #4444.
This is a continuation of #5635.
Resolves #4738 While `generate_psa_tests.py` could use more refactoring and restructuring or simplification, it isn't specifically about key usage.
Backport: [2.28](https://github.com/Mbed-TLS/mbedtls/pull/5754)

PSA storage format: exercise key

---

tests/suites/test_suite_x509parse.function

Resolves #5756 
**READY**
Yes  
Which branch? 2.28

Set flag to proper value in x509 parse tests

---

tests/suites/test_suite_x509parse.function

Complete 2.28 backport of #5759 
**READY**

[Backport 2.28] Set flag to proper value in x509 parse tests

---

library/ssl_tls.c
library/ssl_tls12_client.c
library/ssl_tls12_server.c
programs/ssl/ssl_client2.c
programs/ssl/ssl_server2.c
tests/ssl-opt.sh

Add support for RSA-PSK, ECDHE-PSK, DHE-PSK using PSA-held (aka opaque) keys, that is, keys provisioned with mbedtls_ssl_conf_psk_opaque() or mbedtls_ssl_set_hs_psk_opaque() (used in the PSK callback).
Resolves:
https://github.com/Mbed-TLS/mbedtls/issues/5663
https://github.com/Mbed-TLS/mbedtls/issues/5664
https://github.com/Mbed-TLS/mbedtls/issues/5665
**READY**
NO  
NO
Needs preceding PR: https://github.com/Mbed-TLS/mbedtls/pull/5726

Mixed PSK 2a, 2b, 2c: enable client/server support opaque RSA-PSK, ECDHE-PSK, DHE-PSK

---

include/mbedtls/pk.h
library/pk.c
programs/ssl/ssl_client2.c
programs/ssl/ssl_server2.c
tests/suites/test_suite_pk.function
tests/suites/test_suite_x509write.function

The function `mbedtls_pk_wrap_as_opaque()` is a test utility that was initially working only for ECDSA keys, but now needs to handle more key types; as a result, it's desirable for it to have more parameters.
Resolves #5761 
**READY**
NO  
NO
test_suite_pk, test_suite_x509write & ssl-opt must run clean

RSA decrypt 0: Rework `mbedtls_pk_wrap_as_opaque()`

---

ChangeLog.d/fix-undefined-memcpy-mbedtls_asn1_named_data.txt
library/asn1write.c
tests/suites/test_suite_asn1write.data
tests/suites/test_suite_asn1write.function

Removes a case in mbedtls_asn1_named_data() where memcpy() could be
called with a null pointer and zero length. A test case is added for
this code path, to catch the undefined behavior when running tests with
UBSan.
This fix was previously included/described in PRs #5607 and #3710. The undefined behavior is prevented by only calling `memcpy()` when `val_len` is greater than zero.
A test case is added in this PR to cover this code path. The test suite has been ran locally by building with `-fsanitize= undefined` compiler/linker flags, which causes failure without the change in `mbedtls_asn1_named_data()` and passing with the change.
**READY**
Yes 2.28
NO
None
Build mbedtls with scan-build
`scan-build make`
Or, with test suite changes, run tests with:
`make check …

Fix memcpy() UB in mbedtls_asn1_named_data()

---

ChangeLog.d/fix-undefined-memcpy-mbedtls_asn1_named_data.txt
library/asn1write.c
tests/suites/test_suite_asn1write.data
tests/suites/test_suite_asn1write.function

Backport of #5801, tested locally with the same commands.

[Backport 2.28] Fix memcpy() UB in mbedtls_asn1_named_data()

---

.travis.yml

Travis stopped being able to push builds to coverity due to the token apparently being no longer valid (could have to do with either the project rename or other apps rotating their travis tokens)
This PR rotates our coverity token to see if that fixes things.
This is a backport to 2.28 of #5803
**READY**
NO
Note that travis secrets are encrypted using a project-based public key encryption - this is not the bare token. See https://docs.travis-ci.com/user/encryption-keys/
Note also that this secret is *only* used for pushes to coverity from Travis, therefore nothing in the CI run will test this functionality before it is merged. However, the push is currently already broken, so this won't make anything worse.
See Additional comments. Testing will have to take place after merge.

Backport 2.28: Rotate coverity secret token in travis

---

.travis.yml

Travis stopped being able to push builds to coverity due to the token apparently being no longer valid (could have to do with either the project rename or other apps rotating their travis tokens)
This PR rotates our coverity token to see if that fixes things.
**READY**
YES 
[2.28](#5805)
NO
Note that travis secrets are encrypted using a project-based public key encryption - this is not the bare token. See https://docs.travis-ci.com/user/encryption-keys/
Note also that this secret is *only* used for pushes to coverity from Travis, therefore nothing in the CI run will test this functionality before it is merged. However, the push is currently already broken, so this won't make anything worse.
See Additional comments. Testing will have to take place after merge.

Rotate coverity secret token in travis

---

.travis.yml

Although Coverity have now changed their URL to point at the newproject, they did not change the project name, it would seem.
**READY**
Yes 
[2.28](#5186)
NO
This cannot unfortunately be tested by CI, as only the coverity push uses this, and this is only done manually or via nightlies.
See additional comments.

Revert Coverity project name change in Travis

---

.travis.yml

Although Coverity have now changed their URL to point at the newproject, they did not change the project name, it would seem. This is a backport of #5814
**READY**
NO
NO
This cannot unfortunately be tested by CI, as only the coverity push uses this, and this is only done manually or via nightlies.
See additional comments.

Backport 2.28: Revert Coverity project name change in Travis

---

library/ssl_client.c
library/ssl_misc.h
library/ssl_tls.c
library/ssl_tls13_server.c
tests/ssl-opt.sh

Add functions for writing certificate request message on tls1.3 server side.
**READY**
server-side state machine is currently incomplete, and this pr cannot be verified at the moment.

TLS1.3: Add writing CertificateRequest msg on server side

---

include/mbedtls/ssl.h
library/psa_crypto.c
library/ssl_misc.h
library/ssl_tls.c
library/ssl_tls12_client.c
library/ssl_tls12_server.c
tests/ssl-opt.sh
tests/suites/test_suite_ssl.function

Currently there are up to three code paths for handling PSKs in TLS:
the non-PSA case
the PSA case with transparent (non-opaque) keys
the PSA case with opaque keys
This task is to merge cases 2 and 3
Resolves #5788
**READY**
NO 
NO
test_suite_ssl, ssl-opt.sh & compat.sh must run clean

Unify non-opaque and opaque PSKs

---

programs/ssl/ssl_client2.c
programs/ssl/ssl_server2.c
programs/ssl/ssl_test_lib.c
programs/ssl/ssl_test_lib.h

Add Add a new command-line option key_opaque_algs to `ssl_server2` and `ssl_client2`.
Resolves https://github.com/Mbed-TLS/mbedtls/issues/5763 
**READY**

RSA decrypt 1b: prepare for TLS testing

---

include/mbedtls/check_config.h
include/mbedtls/mbedtls_config.h
library/rsa.c
tests/scripts/all.sh
tests/scripts/generate_psa_tests.py
tests/suites/test_suite_oid.function
tests/suites/test_suite_psa_crypto_se_driver_hal.function
tests/suites/test_suite_x509parse.function

Adapt dependencies on `MBEDTLS_MD_C`.
Resolves: https://github.com/Mbed-TLS/mbedtls/issues/5715
Starting from full config to disable `MBEDTLS_MD_C` we need to disable the following dependent features:
- `[MBEDTLS_MD_C]`
- `['MBEDTLS_ECJPAKE_C', 'MBEDTLS_PKCS5_C', 'MBEDTLS_PKCS12_C', 'MBEDTLS_PKCS1_V15', 'MBEDTLS_PKCS1_V21', 'MBEDTLS_HKDF_C', 'MBEDTLS_HMAC_DRBG_C', 'MBEDTLS_PK_C', 'MBEDTLS_SSL_TLS_C']`
- `['MBEDTLS_ECDSA_DETERMINISTIC', 'MBEDTLS_KEY_EXCHANGE_DHE_RSA_ENABLED', 'MBEDTLS_KEY_EXCHANGE_ECDHE_RSA_ENABLED', 'MBEDTLS_KEY_EXCHANGE_RSA_PSK_ENABLED', 'MBEDTLS_KEY_EXCHANGE_RSA_ENABLED', 'MBEDTLS_PK_PARSE_C', 'MBEDTLS_PK_WRITE_C', 'MBEDTLS_RSA_C', 'MBEDTLS_X509_RSASSA_PSS_SUPPORT', 'MBEDTLS_SSL_CLI_C', 'MBEDTLS_SSL_SRV_C', 'MBEDTLS_SSL_DTLS_ANTI_REPLAY']`
- …

Fix undeclared dependencies: MD

---

include/psa/crypto_values.h

The accessor macros for `key_id` and `owner_id` in the `mbedtls_svc_key_id_t`
type need to have the `MBEDTLS_PRIVATE()` specifier as these fields are private
Signed-off-by: Antonio de Angelis <antonio.deangelis@arm.com>
**READY**
**NO** - `MBEDTLS_PRIVATE()` was added in 3.0
YES | NO
Using those two macros results in build failures without this patch.

Fix key_id and owner_id accessor macros

---

include/mbedtls/check_config.h
include/mbedtls/mbedtls_config.h
tests/scripts/all.sh

Adapt dependencies on `MBEDTLS_CIPHER_C`.
Resolves: https://github.com/Mbed-TLS/mbedtls/issues/5716
**READY**
Yes
2.28
NO

Fix undeclared dependencies: CIPHER

---

scripts/driver.requirements.txt
scripts/min_requirements.py

Add minimum requirements, so that `min_requirements.py` installs a working version of `jinja2` on Python 3.10+.
**READY**
No, Jinja 2 is not required by mbedtls 2.28  
No

Add minimum requirements for Python 3.10 support

---

ChangeLog.d/mingw.txt
library/platform_util.c
tests/suites/helpers.function

Fixes #2087. MinGW-w64 should be unaffected by this change.
READY
No - not worth backporting to an LTS
NO

Fix compilation with MinGW32

---

library/ecp.c
library/gcm.c
library/pkcs12.c
library/pkparse.c
library/rsa.c
library/ssl_ticket.c

These issues were flagged by Coverity static code analyzer for
instances that a local variable may be used prior to being initialized.
Partially continuing from https://github.com/Mbed-TLS/mbedtls/pull/5700.

Add missing local variable initialization

---

tests/ssl-opt.sh

Test use of RSA Opaque keys with TLS 1.2 server for decryption (RSA and RSA-PSK key exchanges).
Resolves: https://github.com/Mbed-TLS/mbedtls/issues/5764
**READY**
NO  
NO
Probably more tests are required.
Should this be tested with all supported ciphersuites?

RSA decrypt 2: TLS 1.2 integration testing

---

3rdparty/everest/include/everest/everest.h
CMakeLists.txt
docs/architecture/psa-migration/strategy.md
docs/architecture/testing/driver-interface-test-strategy.md
include/mbedtls/check_config.h
include/mbedtls/ssl.h
include/psa/crypto_extra.h
include/psa/crypto_sizes.h
library/ccm.c
library/ctr_drbg.c
library/ecdh.c
library/mps_common.h
library/ssl_tls13_server.c
programs/ssl/ssl_test_lib.h

I used an [automated typo-finding tool](https://github.com/crate-ci/typos) to locate several typos in constants and documentation in various files in mbedtls. (I accidentally found these in mbedtls after a [library that depended on it](https://github.com/Infineon/optiga-trust-m) tripped a CI step.)

Fix typos in documentation and constants with typo finding tool

---

library/ssl_ciphersuites.c
library/ssl_misc.h
library/ssl_tls.c
library/ssl_tls13_keys.c

Now that all uses of Cipher for cryptographic computations have been removed from TLS when USE_PSA is enabled, it is desirable to also remove non-cryptographic uses, such as getting sizes from a cipher ID (often from a ciphersuite definition).
This task is to remove such uses and replace them with versions based on PSA or at least independent from cipher.c.
Resolves: #5797 
**READY**
NO  
NO
N/A
ssl-opt.sh must run clean

Remove Cipher dependencies in TLS

---

include/psa/crypto_config.h

Signed-off-by: Summer Qin <summer.qin@arm.com>
Notes:
PSA_WANT_ALG_CMAC is defined twice in crypto_config.h
Backport of #5875
**READY**

Backport 2.28: Remove duplicated PSA_WANT_ALG_CMAC in crypto_config.h

---

library/ssl_tls12_server.c

Several call sites flagged by Coverity that may potentially cause
a pointer argument to be NULL.
In two cases the issue is using a function call as a parameter to
a second function, where the first function may return NULL, while
the second function does not check for the NULL argument value.
Remaining case is when static configuration is mixed with run-time
decision, that could result in a data buffer argument being NULL.
Partially continuing from https://github.com/Mbed-TLS/mbedtls/pull/5700.

Avoid potentially passing NULL arguments

---

include/psa/crypto_extra.h

Fixup PSA J-PAKE API against PSA Cryptography API 1.1 PAKE Extension.
Resolves https://github.com/Mbed-TLS/mbedtls/issues/4745
NO  
NO
N/A
- "the password is read as a byte array" - might be better to describe the 'key material' or 'key content'.
- ".. must be non-empty" - redundant, keys cannot have size zero.
- "The psa_pake_set_password_xxx() functions - there is only one for now, psa_pake_set_password_key(). 
psa_pake_set_peer() results in PSA_ERROR_BAD_STATE instead of PSA_ERROR_NOT_SUPPORTED if the algorithm does not use peer identities.
-   `psa_pake_side_t` -> `psa_pake_role_t`
-   `psa_pake_set_side()` -> `psa_pake_set_role()`
-   `PSA_PAKE_SIDE_XXX` -> `PSA_PAKE_ROLE_XXX`
N/A

PSA J-PAKE API has missing elements and confusing documentation

---

ChangeLog.d/fix-x25519-program.txt
programs/pkey/ecdh_curve25519.c

Resolves #4901 and #3191
2.28 Backport available: #5848 
This PR rewrites the ecdh_curve25519 using the high-level ECDH API. This is both to fix the issue mentioned in the above issue and also to demonstrate best practices when using the ECDH API.
*READY*

Rewrite x25519 example program

---

library/constant_time.c
library/constant_time_internal.h
library/ssl_msg.c

Fix an issue reported by Coverity whereby some constant time functions called from the ssl decrypt code could potentially access uninitialised memory, by zeroing memory in two of the places where this function is used.
Add a note to mbedtls_ct_memcpy_if_eq() documentation to warn that it reads from the buffer as well as writing to it. Note that no decisions are taken as a result of the uninitialised data, but obviously its still not best practice.
This is a backport of #5829 
**READY**
NO
As we are not trying to hide the length that will be copied, I used memset to zero the target buffers. I hope this is not too out of place in constant_time.c, and will re-write if people feel that it is.
test_suite_ssl should run clean.

Backport 2.28: Fix uninitialised memory access in constant time functions

---

library/constant_time.c
library/constant_time_internal.h
library/ssl_msg.c

Fix an issue reported by Coverity whereby some constant time functions called from the ssl decrypt code could potentially access uninitialised memory, by zeroing memory in two of the places where this function is used.
Add a note to mbedtls_ct_memcpy_if_eq() documentation to warn that it reads from the buffer as well as writing to it. Note that no decisions are taken as a result of the uninitialised data, but obviously its still not best practice.
**READY**
YES 
[2.28]( https://github.com/Mbed-TLS/mbedtls/pull/5859 )  
NO
As we are not trying to hide the length that will be copied, I used memset to zero the target buffers. I hope this is not too out of place in constant_time.c, and will re-write if people feel that it is.
test_suite_ssl should run clean.

Fix uninitialised memory access in constant time functions

---

ChangeLog.d/cmake_add_subdirectory_support.txt
library/CMakeLists.txt

Allow building as a subdirectory (like with cmake FetchContent) 
Fixes #5688
Signed-off-by: Robert Shade <robert.shade@gmail.com>
**READ**
NO  
NO

Allow building as a subdir

---

library/ssl_tls13_generic.c

There are a number of places in the TLS 1.3 handshake where hashes/HMACs are computed. This should be done using psa_hash_/psa_mac_ functions rather than mbedtls_md_ or mbedtls_shaNNN functions. (Regardless of the value of MBEDTLS_USE_PSA_CRYPTO, which only affects 1.2, as 1.3 should always use PSA.) this PR addresses:
- In `ssl_tls13_parse_certificate_verify()`: use `psa_hash_compute()` instead of `mbedtls_shaNNN()`.
- In `mbedtls_ssl_tls13_derive_secret()`: use `psa_mac_compute()` instead of `mbedtls_md_hmac()`.
**READY**
NO  
Fixes #5326

Feature psec-3207 move TLS13 hashing and hmac to psa

---

ChangeLog.d/fix-time-format-pre-2000.txt
library/x509write_crt.c
tests/suites/test_suite_x509write.data
tests/suites/test_suite_x509write.function

Closes #5645. 
ASN1 UTC time format is valid for dates between 1950 and 2049, existing checks only support 2000 to 2049. Tests are added to check the UTC time tag is used when valid for various combinations of `not_before` and `not_after`.
**READY**
Yes 2.28 #5828 
Write an X509 certificate with `not_before` set to 1/1/1970. The tag for the date will be 0x18 (`GENERALIZED_TIME`) instead of 0x17 (`UTC_TIME`).

Use ASN1 UTC tags for dates before 2000

---

ChangeLog.d/fix-time-format-pre-2000.txt
library/x509write_crt.c
tests/suites/test_suite_x509write.data
tests/suites/test_suite_x509write.function

Closes #5645. Backport of #5827.
ASN1 UTC time format is valid for dates between 1950 and 2049, existing checks only support 2000 to 2049. Tests are added to check the UTC time tag is used when valid for various combinations of `not_before` and `not_after`.
**READY**
Write an X509 certificate with `not_before` set to 1/1/1970. The tag for the date will be 0x18 (`GENERALIZED_TIME`) instead of 0x17 (`UTC_TIME`).

[Backport 2.28] Use ASN1 UTC tags for dates before 2000

---

tests/ssl-opt.sh

When executing eval in the background, the next "$!" gives the eval PID, not the ssl-client2 pid. This causes problems when a client times out and the script tries to kill it. Instead, it kills the parent eval call. This caused problems with subsequent proxy tests receiving old packets from a client from a previous test. Moving the "&" to inside the eval call fixes the problem.

Fix a bug with executing ssl-client2 in ssl-opt.sh in a subshell

---

library/ssl_misc.h
library/ssl_tls.c
library/ssl_tls12_server.c
library/ssl_tls13_client.c
library/ssl_tls13_generic.c
library/ssl_tls13_server.c
tests/ssl-opt.sh

Add support for the server_name extension on server side.
This include:
Parsing of the server_name extension in the ClientHello
Support of sni_authmode to decide if a CertificateRequest message needs to be sent or not
ssl-opt.sh test cases.
Fixes #5799

Tls13 add server name

---

ChangeLog.d/add_dn_get_next.txt
include/mbedtls/x509.h
library/x509.c
tests/suites/test_suite_x509parse.data
tests/suites/test_suite_x509parse.function

Multi-valued relative DNs are handled by setting `mbedtls_x509_name.next_merged` to indicate that the next node is part of the same RDN. As `next_merged` is private in 3.x, it is not possible to correctly walk an X.509 name which contains multi-value RDNs, as each node will be treated as separate.
The added function returns a pointer to the first node belonging to the next RDN in the linked list, to allow walking without requiring direct access to `next_merged`. Fixes #5431.
**READY**
NO 
Load an X.509 certificate with a subject containing a multi-value RDN and walk the subject name manually. Accessing `next_merged` will cause a compilation error, otherwise unable to confirm where an RDN ends.

Add mbedtls_x509_dn_get_next function

---

library/ssl_tls.c
library/ssl_tls13_client.c
library/ssl_tls13_generic.c
library/ssl_tls13_server.c
tests/ssl-opt.sh
tests/suites/test_suite_ssl.function

Fix #5897 
Ready
No, TLS 1.3 only

TLS 1.3: Enable and add tests

---

include/mbedtls/x509.h
library/x509.c

Inline mbedtls_x509_dn_get_next() in x509.h and improve header documentation
for new interface (#5954) added for now-private member.
**READY**
NO  
NO

Inline mbedtls_x509_dn_get_next() in x509.h

---

docs/architecture/tls13-support.md
library/ssl_tls13_client.c
library/ssl_tls13_generic.c
library/ssl_tls13_server.c
tests/suites/test_suite_ssl.function

A few fixes in TLS 1.3 code that has not been released yet. Then a documentation of the high level organization of the TLS 1.3 handshake implementation followed by a few commits re-organizing the code in line with the documentation.
Fix #5897 (partial)
CI check
No, TLS 1.3 only

TLS 1.3: Fixes and add documentation

---

ChangeLog.d/add_final_delay_accessor
ChangeLog.d/add_handshake_completion_accessor
ChangeLog.d/add_own_cid_accessors
ChangeLog.d/cmake_add_subdirectory_support.txt
ChangeLog.d/cmake_fix_dll_install.txt
ChangeLog.d/deprecate_mbedtls_cipher_setup_psa.txt
ChangeLog.d/fix-parllel-cmake-build-fail.txt
ChangeLog.d/fix-windows-cmake-build-with-shared-libraries.txt
ChangeLog.d/fix-x25519-program.txt
ChangeLog.d/mbedtls_ecp_export.txt
ChangeLog.d/mbedtls_sha256_a64_crypto_acceleration.txt
ChangeLog.d/mbedtls_sha2_a64_crypto_acceleration.txt
ChangeLog.d/mbedtls_sha512_a64_crypto_acceleration.txt
ChangeLog.d/mbedtls_ssl_comfig_defaults-memleak.txt
ChangeLog.d/mbedtls_ssl_tls13_client.txt
ChangeLog.d/mbedtls_tlsver_enum.txt
ChangeLog.d/md_info_from_ctx.txt
ChangeLog.d/psa_aead_singleshot_error.txt
ChangeLog.d/psa_crypto_reduced_configs.txt
ChangeLog.d/psk_to_ms_mixed_psk.txt
ChangeLog.d/raw-agreement-destroy-missing.txt
ChangeLog.d/tls13-fix-finished-fetch.txt
ChangeLog.d/use-psa-ecdhe-curve.txt
include/mbedtls/mbedtls_config.h

Miscellaneous improvements to changelog entries, including:
* Consolidating changelog entries from #5632 and #5547. Also update the documentation to list SHA-224 and SHA-384.
* Removing the bugfix entry added in https://github.com/Mbed-TLS/mbedtls/pull/5576, because upon further analysis there wasn't actually a bug.
* The clarification I requested in https://github.com/Mbed-TLS/mbedtls/pull/5837/files#r880337653.
I have only reviewed existing entries. I have not looked for missing entries.
Needs backport for a few entries.

Changelog improvements before the 3.2 release

---

library/ssl_tls13_generic.c
library/x509.c

Remove MD dependencies from `mbedtls_x509_sig_alg_gets(), ssl_tls13_parse_certificate_verify()`.
Resolves https://github.com/Mbed-TLS/mbedtls/issues/5795 and resolves https://github.com/Mbed-TLS/mbedtls/issues/5796
**READY**
NO  
NO

Remove MD dependencies from mbedtls_x509_sig_alg_gets(), ssl_tls13_parse_certificate_verify()

---

ChangeLog.d/selftest-gcc12.txt
programs/test/selftest.c

Backport of https://github.com/Mbed-TLS/mbedtls/pull/5976. Fixes https://github.com/Mbed-TLS/mbedtls/issues/5974.

Backport 2.28: Remove largely useless bit of test log to silence GCC 12

---

ChangeLog.d/selftest-gcc12.txt
programs/test/selftest.c

Remove largely useless bit of test log to silence GCC 12

---

ChangeLog.d/tls13_and_keep_certificates.txt
docs/architecture/tls13-support.md
include/mbedtls/check_config.h
include/mbedtls/mbedtls_config.h

And have check_config.h enforce it
Fixes #5610 
**READY**
NO - TLS 1.3 doesn't get backported to 2.x

Document that MBEDTLS_SSL_KEEP_PEER_CERTIFICATE is required by MBEDTLS_SSL_PROTO_TLS1_3

---

docs/architecture/mbed-crypto-storage-specification.md

I haven't updated the historical information. That would be nice to do, but I ran out of time collecting information.
Fulfils https://github.com/Mbed-TLS/mbedtls/issues/3737 with respect to the current (and only supported) format.
Backport: https://github.com/Mbed-TLS/mbedtls/pull/5996

Update storage format specification for Mbed TLS 2.25.0+

---

docs/architecture/mbed-crypto-storage-specification.md

Backport of https://github.com/Mbed-TLS/mbedtls/pull/5994. Identical text except that I removed the list of 3.x versions.

Backport 2.28: Update storage format specification for Mbed TLS 2.25.0+

---

ChangeLog.d/mbedtls_ssl_dn_hint.txt
include/mbedtls/ssl.h
library/ssl_misc.h
library/ssl_tls.c
library/ssl_tls12_client.c
library/ssl_tls12_server.c
programs/ssl/ssl_server2.c
tests/ssl-opt.sh

Add accessors to config DN hints for cert request   
* mbedtls_ssl_conf_dn_hints()
* mbedtls_ssl_set_hs_dn_hints()
**READY**
NO  
YES
#5541

Add accessors to config DN hints for cert request

---

docs/3.0-migration-guide.md

A section is added to the migration guide which refers readers to the 2.x documentation when upgrading code. The 2.x docs will often explain how to upgrade code which uses deprecated functions and macros, but this was not apparent previously in the guide.
Removal PRs related to 3.0 have also been reviewed to find any changes which were not documented in either the 2.x docs or the migration guide, and these have been added to the guide. Fixes #5032.
**READY**

Add guidance for deprecated functions and macros to migration guide

---

tests/src/psa_exercise_key.c

Fix an issue reported by Coverity whereby an input buffer is uninitialized in test code.

Fix uninitialised memory access in test

---

ChangeLog.d/fix_some_resource_leaks.txt
library/pkparse.c

Partial backport of https://github.com/Mbed-TLS/mbedtls/pull/5765 - only the `mbedtls_pk_parse_public_key` part applies.

Fix `mbedtls_pk_parse_public_key` resource leaks

---

ChangeLog.d/resumption_cid.txt
library/ssl_cli.c
tests/ssl-opt.sh

Straightforward backport of https://github.com/Mbed-TLS/mbedtls/pull/5915, no conflicts.
I have verified that the bug exists, the `ssl-opt.sh` test fails without the fix, and that the fix works.

[Backport 2.28] Fix DTLS 1.2 session resumption

---

ChangeLog.d/resumption_cid.txt
library/ssl_tls12_client.c
tests/ssl-opt.sh

Previously, the transforms were populated before extension parsing, which resulted in the client rejecting a server hello that contained a connection ID.
Fixes https://github.com/Mbed-TLS/mbedtls/issues/5872.

Fix DTLS 1.2 session resumption

---

scripts/generate_ssl_debug_helpers.py

The file 'ssl_debug_helpers_generated.c' was being generated using tabs rather than spaces, which breaks release builds. This problem is normally hidden, as this file is referenced as part of the .gitignore, however in a release build it gets checked in.
Resolves https://github.com/Mbed-TLS/mbedtls/issues/6075
**READY**
NO  
(This script was only added in 3.0)
NO
Release build should not complain about check_files failing on 'ssl_debug_helpers_generated.c'

Fix generation of ssl_debug_helpers

---

scripts/generate_ssl_debug_helpers.py

The emergency fix of  `generate_ssl_debug_helpers.py` to fix the release build ( https://github.com/Mbed-TLS/mbedtls/pull/6076 ) unfortunately fell foul of pylint on the CI, this fixes that. 
In order to fix the second line too long issue I had to split out the second part into another variable.
**READY**
NO  
NO
CI (check_python_files.py) should pass.

Fix formatting of generate_ssl_debug_helpers.py

---

scripts/assemble_changelog.py

Backport of #6081 - fixes #6080

Fix case of Mbed TLS in assemble_changelog.py - backport 2.28

---

include/psa/crypto_values.h

Currently documenation of PSA_ALG_RSA_PSS doesn't reflect the change in code.
This closes #5856 
**IN REVIEW**
Yes 
Which branch?
2.28
NO
Note regarding issue #5856, positive test case already exist in test_suite_psa_crypto.
PSA verify hash: RSA-1024 PSS SHA-512, slen=62
Thus, no need to add new positive test case
See documentation for PSA_ALG_RSA_PSS in include/psa/crypto_values.h file.

Update documentation of PSA_ALG_RSA_PSS

---

CMakeLists.txt
ChangeLog.d/fix_cmake_gen_files

If generation of files is turned off, and a file is missing, when building in tree with cmake, you can end up with the generated file being turned into a symlink to itself. This will also break any future attempt at building with make. Fix this by testing if the file exists prior to attempting to link it.
**READY**
NO  
NO
This was found by (and contributed to) the breakage of the recent release.
CMake both in and out of tree should work with GEN_FILES off and although it should fail with missing files, should not create a self referential symlink.

Fix linking of generated files in cmake

---

tests/suites/host_test.function

Add missing break - backport 2.28

---

ChangeLog.d/bn_mul-fix-x86-pic-compilation-for-gcc-4.txt
library/bn_mul.h

Fixes #1910
With ebx added to the MULADDC_STOP clobber list to fix #1550, the inline
assembly fails to build with GCC < 5 in PIC mode with the following error:
include/mbedtls/bn_mul.h:46:13: error: PIC register clobbered by ‘ebx’ in ‘asm’
This is because older GCC versions treated the x86 ebx register (which is
used for the GOT) as a fixed reserved register when building as PIC.
This is fixed by an improved register allocator in GCC 5+.  From the release
notes:
Register allocation improvements: Reuse of the PIC hard register, instead of
using a fixed register, was implemented on x86/x86-64 targets.  This
improves generated PIC code performance as more hard registers can be used.
https://www.gnu.org/software/gcc/gcc-5/changes.html
As a workaround, detect this situation and disable the …

bn_mul.h: fix x86 PIC inline ASM compilation with GCC < 5

---

ChangeLog.d/bn_mul-fix-x86-pic-compilation-for-gcc-4.txt
include/mbedtls/bn_mul.h

Backport 2.28: bn_mul.h: fix x86 PIC inline ASM compilation with GCC < 5

---

include/mbedtls/ssl.h
library/ssl_misc.h
library/ssl_tls.c
library/ssl_tls13_server.c
tests/ssl-opt.sh

fix #5564
fix #5988 
Know issues:
-   Export `psk_opaque` to fix it.  
- Hash algorithm is selected base on binder length now.
- https://github.com/tlswg/tls13-spec/issues/1227 , the issue is discussed .
preceding-pr: #6112 

TLS 1.3: PSK: Add parser/writer of pre_shared_key extension on server side.

---

include/mbedtls/ssl.h
library/ssl_tls.c
library/ssl_tls13_client.c
library/ssl_tls13_server.c
tests/ssl-opt.sh
tests/suites/test_suite_ssl.data
tests/suites/test_suite_ssl.function

This task's target is to create `ssl_session_{save,load}_tls13` and relative tests. That's preparing for tls13 session ticket.
Client side does not depend on it. But server side will depend on it. And session load/save can be separately tests.
For server side session tickets(#5557 ), #6069 add an empty  `session_save_tls13` function.
The initial commit is moved from #5913 . Below are previous feedback about session save.
- https://github.com/Mbed-TLS/mbedtls/pull/5913#discussion_r917947772
- https://github.com/Mbed-TLS/mbedtls/pull/5913#discussion_r918116944
- https://github.com/Mbed-TLS/mbedtls/pull/5913#discussion_r918811302
- https://github.com/Mbed-TLS/mbedtls/pull/5913#discussion_r918811541
- https://github.com/Mbed-TLS/mbedtls/pull/5913#discussion_r918968896
- …

TLS 1.3: Add serialize session save load

---

ChangeLog.d/extend-query_compile_time_config-to-psa_want.txt
scripts/data_files/query_config.fmt
scripts/generate_query_config.pl

**READY**
**NO** - this is an enhancement 
Note that if `query_compile_time_config` is run with files specified, the PSA config file is an optional additional argument. This will allow existing scripts to continue to function.
Future enhancements could have us using `MBEDTLS_PSA_CRYPTO_CONFIG` and `MBEDTLS_PSA_CRYPTO_CONFIG_FILE`, but let's only add those if found to be necessary.

Extend query_compile_time_config to PSA_WANT_xxx macros

---

include/mbedtls/asn1write.h
include/mbedtls/mbedtls_config.h
include/mbedtls/md.h
include/mbedtls/ripemd160.h
include/mbedtls/rsa.h
include/mbedtls/ssl.h
include/psa/crypto.h
include/psa/crypto_compat.h
include/psa/crypto_extra.h
include/psa/crypto_platform.h
include/psa/crypto_se_driver.h
include/psa/crypto_types.h
include/psa/crypto_values.h
library/bignum.c
library/pk_wrap.c
library/ssl_tls12_client.c
scripts/data_files/error.fmt

**Yes** #6143 
No ChangeLog entry, as typos aren't interesting unless they impact semantics, which none of these do.

Fix a/an typos in doxygen and other comments

---

include/mbedtls/asn1write.h
include/mbedtls/config.h
include/mbedtls/md.h
include/mbedtls/ripemd160.h
include/mbedtls/rsa.h
include/mbedtls/ssl.h
include/psa/crypto.h
include/psa/crypto_compat.h
include/psa/crypto_extra.h
include/psa/crypto_platform.h
include/psa/crypto_se_driver.h
include/psa/crypto_types.h
include/psa/crypto_values.h
library/bignum.c
library/error.c
library/pk_wrap.c
library/ssl_cli.c
library/xtea.c
scripts/data_files/error.fmt

Backport 2.28: Fix a/an typos in doxygen and other comments

---

ChangeLog.d/muladdc_microblaze.txt
library/bn_mul.h

Fixed a bug that the little-endian Microblaze does not work when MBEDTLS_HAVE_ASM is defined.
I accidentally closed #4586.... sorry.
Signed-off-by: Kazuyuki Kimura <kim@wing.ocn.ne.jp>
Fixes #2020

Fixed a bug that the little-endian Microblaze does not work when MBEDTLS_HAVE_ASM is defined

---

ChangeLog.d/muladdc_microblaze.txt
include/mbedtls/bn_mul.h

Almost-trivial backport of #4686

Microblaze littleendian backport 2.28

---

SECURITY.md
docs/3.0-migration-guide.md
docs/architecture/psa-crypto-implementation-structure.md
docs/architecture/psa-migration/psa-limitations.md
docs/architecture/psa-migration/strategy.md
docs/proposed/psa-driver-interface.md
docs/proposed/psa-driver-wrappers-codegen-migration-guide.md
tests/git-scripts/README.md

Can't remember which of these I noticed first, then sent cspell to look for more.
**READY**
**Yes** - #6160

Fix typographical errors in .md files found by cspell

---

SECURITY.md
docs/architecture/psa-crypto-implementation-structure.md
docs/proposed/psa-driver-interface.md
tests/git-scripts/README.md

Backport 2.28: Fix typographical errors in .md files found by cspell

---

ChangeLog.d/fix_psa_crypto_cipher_h_include.txt
library/psa_crypto_cipher.c

Signed-off-by: Martin Man <mman@martinman.net>
`psa_crypto_cipher.h` is a private header file located within the `library` directory and should therefore be always included with double quotes instead of angle brackets like this: `#include "psa_crypto_cipher.h"`.
This PR fixes the problem where code fails to compile under:
```
Apple clang version 14.0.0 (clang-1400.0.28.1)
Target: x86_64-apple-darwin21.5.0
```
with error message reported:
```
mbedtls/library/psa_crypto_cipher.c:25:10: error: 'psa_crypto_cipher.h' file not found with <angled> include; use "quotes" instead
#include <psa_crypto_cipher.h>
^~~~~~~~~~~~~~~~~~~~~
"psa_crypto_cipher.h"
1 error generated.
```
**READY**
Yes
mbedtls-2.28
mbedtls-3.2
NO

Use double quotes to include private header file psa_crypto_cipher.h

---

ChangeLog.d/fix_psa_crypto_cipher_h_include.txt
library/psa_crypto_cipher.c

Signed-off-by: Martin Man <mman@martinman.net>
Co-authored-by: Tom Cosgrove <81633263+tom-cosgrove-arm@users.noreply.github.com>
Backport of https://github.com/Mbed-TLS/mbedtls/pull/6114 for `mbedtls-2.28`.
**READY**

Backport 2.28: Use double quotes to include private header file psa_crypto_cipher.h

---

ChangeLog.d/x509-broken-symlink-handling.txt
library/x509_crt.c

On non-windows environments, when loading certificates from a given
path through mbedtls_x509_crt_parse_path() function, if a symbolic
link is found and is broken (meaning the target file don't exists),
the function is returning MBEDTLS_ERR_X509_FILE_IO_ERROR which is
not honoring the default behavior of just skip the bad certificate file
and increase the counter of wrong files.
The problem have been raised many times in our open source project
called Fluent Bit which depends on MbedTLS:
https://github.com/fluent/fluent-bit/issues/843#issuecomment-486388209
The expected behavior is that if a simple certificate cannot be processed,
it should just be skipped.
This patch implements a workaround with lstat(2) and stat(2) to determinate
first, if the entry found in the directory is a symbolic …

x509_crt: handle properly broken links when looking for certificates

---

ChangeLog.d/x509-broken-symlink-handling.txt
library/x509_crt.c

Almost trivial backport of #2602

Backport 2.28: x509_crt: handle properly broken links when looking for certificates

---

tests/suites/test_suite_x509write.function

test_suite_x509write: use psa_hash_compute() instead mbedtls_md().
**READY**
NO  
NO

Avoid use of MD in X.509 write test suite

---

tests/suites/test_suite_ssl.function

Avoid use of MD in SSL test suite.
Resolves https://github.com/Mbed-TLS/mbedtls/issues/6120
**READY**
NO  
Which branch?
NO

Avoid use of MD in SSL test suite

---

CMakeLists.txt
ChangeLog.d/fix_cmake_using_iar_toolchain.txt

IAR toolchain makes some warning, forcing 'warning as error' is not for sure.
Signed-off-by: savent savent_gate@outlook.com
**READY**

cmake: IAR support option( MBEDTLS_FATAL_WARNINGS)

---

ChangeLog.d/fix_build_error_for_mbedtls_deprecated_removed.txt
library/ssl_tls.c

Currently mbedtls fails to build when `MBEDTLS_DEPRECATED_REMOVED` config option is enabled.
Reason: In latest version the function prototypes `mbedtls_ssl_conf_max_version` and `mbedtls_ssl_conf_min_version` from `ssl.h` file were deprecated and added under `MBEDTLS_DEPRECATED_REMOVED` config option. But their respective function declarations were not added under the same config option. While building, `mbedtls/CMakeLists.txt` enables `-Wmissing-prototypes` compile option and thus the build currently fails with following error:
`/Users/flying_raijin/espressif/mbedtls/library/ssl_tls.c:2505:6: error: no previous prototype for function 'mbedtls_ssl_conf_max_version' [-Werror,-Wmissing-prototypes]`
This MR adds those function declarations under respective macro
**READY**
NO - the bug was …

Fix build error due to  missing prototype warning when `MBEDTLS_DEPRECATED_REMOVED` is enabled

---

CMakeLists.txt
ChangeLog.d/fix_cmake_using_iar_toolchain.txt

Trivial backport of #5950 : IAR toolchain makes some warning, forcing 'warning as error' is not for sure.

Backport 2.28: cmake: IAR support option( MBEDTLS_FATAL_WARNINGS)

---

programs/test/query_compile_time_config.c
tests/ssl-opt.sh

This is for checking `MBEDTLS_KEY_EXCHANGE_SOME_PSK_ENABLED` which is not defined in `mbedtls_config.h` . #6135 will use it . 
Beside that, it also includes a fix for removing output message in Ubuntu22.04.
**READY**

Add ability to check if any/all configs are enabled/disabled for ssl-opt

---

library/ssl_tls.c

Looking at the bigger picture it is clear that if `ssl->session` is NULL,
there will be a failure much earlier, and that is well protected from,
however, the practice of dereferencing a pointer which has not been
verified in prior for validity goes against secure coding practices.
See #6183 
READY
NO  
NO

ssl_tls: avoid the appearance of a potential NULL dereferencing

---

ChangeLog.d/nonversioned-library-soname.txt
library/Makefile
scripts/bump_version.sh

On Android, you can include shared libraries by dropping them in the jniLibs directory. However, Android Studio ignores file names that don't match *.so, like libmbedtls.so.17. So developers typically build non-versioned libraries.
This patch allows me to do this:
SOEXT_TLS=so SOEXT_X509=so SOEXT_CRYPTO=so make lib
Note that `?=` is necessary because make variables declared like this:
SOEXT_TLS=so.17
can only be changed with an argument to make:
make lib SOEXT_TLS=so
and these arguments are not passed on to a recursive call to make (`make -C library`), whereas `?=` allows me to use an environment variable, like so:
SOEXT_TLS=so make lib
Signed-off-by: Mansour Moufid

Allow non-versioned library soname.

---

tests/suites/test_suite_ecdsa.function

Only deterministic tests require SHA256 now.
Fixes https://github.com/Mbed-TLS/mbedtls/issues/6126

Adjust hash dependencies in `test_suite_ecdsa`

---

library/bn_mul.h
tests/scripts/all.sh

Within the M-profile of the Arm architecture, some instructions admit both a 16-bit and a 32-bit encoding. For those instructions,
some assemblers support the use of the .n (narrow) and .w (wide) suffixes to force a choice of instruction encoding width.
Forcing the size of encodings may be useful to ensure alignment of code, which can have a significant performance impact on some microarchitectures.
It is for this reason that a previous commit introduced explicit .w suffixes into what was believed to be M-profile only assembly
in library/bn_mul.h.
This change, however, introduced two issues:
- First, the assembly block in question is used also for Armv7-A systems, on which the .n/.w distinction is not meaningful (all instructions are 32-bit). This was reported in #6089.
- Second, compiler …

Remove encoding width suffix from Arm bignum assembly

---

library/ssl_tls.c
tests/suites/test_suite_ssl.function

Fix #6122 
Address left comments in #6087 
**READY**

TLS 1.3:finalize tls13 serialize session save and load

---

library/ssl_srv.c

Backprort: ssl_tls12_server: fix potential NULL-dereferencing

---

include/mbedtls/bignum.h
library/constant_time.c

Backport 2.28: Be explicit about constant time bignum functions that must take a 0 or 1 condition value

---

tests/suites/test_suite_ssl.function

`MBEDTLS_SSL_IANA_TLS_GROUP_SECP192R1` and friends are not members of the `mbedtls_ecp_group_id` enum
Found by clang's -Wassign-enum
Signed-off-by: Tom Cosgrove <tom.cosgrove@arm.com>
**READY**
**NO** (not applicable to 2.28)

Fix incorrect use of mbedtls_ecp_group_id in test_suite_ssl.function

---

include/mbedtls/check_config.h
include/mbedtls/ecjpake.h
include/mbedtls/mbedtls_config.h
library/ecjpake.c
tests/scripts/all.sh
tests/suites/test_suite_ecjpake.function

The EC J-PAKE module uses MD in order to compute a hash at various points. This doesn't work when hashes are only provided by drivers; this is task is to make it work.
Resolves #6149
```
*** Comparing before-default -> after-default ***
ecjpake: total  79; skipped   0 ->   0
*** Comparing before-full -> after-full ***
ecjpake: total  79; skipped   0 ->   0
*** Comparing reference -> drivers ***
ecjpake: total  79; skipped   0 ->   0
```
**READY**
NO  
NO
test_suite_ecjpake and all.sh must run clean

Driver-only hashes: EC J-PAKE

---

ChangeLog.d/fix-ctr-drbg-may-free-invalid-aes-context.txt
library/ctr_drbg.c

Application may enabled `AES_ALT` and define `mbedtls_aes_context` by its own.
The initial state of user-defined `mbedtls_aes_context` may not all byte zero.
In `mbedtls_ctr_drbg_init`, the code set all byte to zero, including the AES
context nested in the ctr_drbg context.
And in `mbedtls_ctr_drbg_free`, the code calls `mbedtls_aes_free` on an AES
context without calling `mbedtls_aes_init`.
If user-defined AES context requires an non-zero init, the `mbedtls_aes_free`
call in `mbedtls_ctr_drbg_free` is illegal.
This patch fix this issue by add `mbedtls_aes_init` in `mbedtls_ctr_drbg_init`.
So aes context will always be initialized to correct state.
READY
Yes  
mbedtls-2.28
NO
1. Define `AES_ALT` in `config.h`
2. implement AES byself:
*  Adding a `fd` field to aes context
* in …

ctr_drbg: fix free uninitialized aes context

---

include/mbedtls/ssl_ticket.h
library/ssl_ticket.c

Address Coverity warnings
Changelog not required IMO - the bug is a non-issue until 2038.
Backport not required: 2.28 will be out of support in 2038, and the fix is an API break.

Fix type used for capturing TLS ticket generation time

---

programs/ssl/ssl_context_info.c

An `mbedtls_md_info_t` variable is not used in builds without MD.
This PR fixes a test failure introduced in the combination of https://github.com/Mbed-TLS/mbedtls/pull/6111 and https://github.com/Mbed-TLS/mbedtls/pull/6208.

Add a missing guard in an example program

---

tests/suites/test_suite_x509write.function

Steps to reproduce:
```
find . -name seedfile -exec rm {} +
scripts/config.py config full
(cd tests && make test_suite_x509write && ./test_suite_x509write)
```
Observed behaviour: the first few tests fail, then eventually there's a bus error and a core dump is produced. If we just add the seedfile again (`dd if=/dev/urandom of=./tests/seedfile bs=64 count=1`) everything passes and there is no crash.
Cause:
When USE_PSA_INIT() failed because lack of seedfile, `mbedtls_x509write_csr_free()`
crashed when called on an unitialized `mbedtls_x509write_csr` struct.
This moves `mbedtls_x509write_csr_init` before calling USE_PSA_INIT(),
which could probably fail, and use the same flow in `x509_csr_check()`
and `x509_csr_check_opaque()`.
Resolves #6100 
**Gatekeeping note:** I (mpg) think this …

Crash in test suite x509write config full no seedfile

---

tests/suites/test_suite_x509write.function

Backport of #6109:
Steps to reproduce:
```
find . -name seedfile -exec rm {} +
scripts/config.py config full
(cd tests && make test_suite_x509write && ./test_suite_x509write)
```
Observed behaviour: the first few tests fail, then eventually there's a bus error and a core dump is produced. If we just add the seedfile again (`dd if=/dev/urandom of=./tests/seedfile bs=64 count=1`) everything passes and there is no crash.
Cause:
When USE_PSA_INIT() failed because lack of seedfile, `mbedtls_x509write_csr_free()`
crashed when called on an unitialized `mbedtls_x509write_csr` struct.
This moves `mbedtls_x509write_csr_init` before calling USE_PSA_INIT(),
which could probably fail, and use the same flow in `x509_csr_check()`
and `x509_csr_check_opaque()`.
**READY**
NO  
NO
N/A

[Backport 2.28]Crash in test suite x509write config full no seedfile

---

tests/scripts/all.sh

**Gatekeeping notes:**
- no backport - this is a new feature
- no ChangeLog entry - a grouped one will be added later, see #6146 
This PR is a follow-up for https://github.com/Mbed-TLS/mbedtls/pull/6208 and should report any issues from compat.sh.
An additional component was temporarily added to all.sh:
```
scripts/config.py -f include/psa/crypto_config.h unset PSA_WANT_ALG_STREAM_CIPHER
scripts/config.py -f include/psa/crypto_config.h unset PSA_WANT_ALG_ECB_NO_PADDING
scripts/config.py set MBEDTLS_PSA_CRYPTO_CONFIG
scripts/config.py set MBEDTLS_USE_PSA_CRYPTO
scripts/config.py unset MBEDTLS_HKDF_C
scripts/config.py unset MBEDTLS_HMAC_DRBG_C
scripts/config.py unset MBEDTLS_ECDSA_DETERMINISTIC
scripts/config.py -f include/psa/crypto_config.h unset PSA_WANT_ALG_DETERMINISTIC_ECDSA
make …
```

TLS without MD - compat.sh addition to all.sh hash acceleration tests

---

programs/ssl/ssl_client2.c
programs/ssl/ssl_server2.c
programs/ssl/ssl_test_common_source.c
tests/scripts/all.sh
tests/ssl-opt.sh

This PR adds a run of ssl-opt.sh with PSA-based hashing in `component_test_psa_crypto_config_accel_hash_use_psa`, and fixes any problems that were found by running it.
Fixes https://github.com/Mbed-TLS/mbedtls/issues/6130.
[edit by mpg]
No ChangeLog entry - a grouped one will be added in #6146.
No backport - this is testing for a new feature.

ssl-opt.sh with PSA-based hashing

---

tests/include/spe/crypto_spe.h

Backport: #6276 
Changelog: no

Correct copyright and license in crypto_spe.h

---

tests/include/spe/crypto_spe.h

Backport from #6275 
Changelog: no

Backport 2.28: Correct copyright and license in crypto_spe.h

---

library/ecjpake.c
library/hash_info.h
library/pkcs12.c
library/rsa.c
library/ssl_tls12_client.c
library/ssl_tls12_server.c
library/x509_crt.c
library/x509write_crt.c
library/x509write_csr.c
tests/suites/test_suite_ecdsa.function

Create MBEDTLS_MAX_HASH_SIZE macro and use it in library and tests.
Resolves https://github.com/Mbed-TLS/mbedtls/pull/6252
**READY**
NO  - refactoring development-only changes
NO - internal refactoring

Create MBEDTLS_MAX_HASH_SIZE in hash_info.h

---

include/mbedtls/build_info.h
include/mbedtls/check_config.h
include/mbedtls/ssl.h
library/ssl_misc.h
library/ssl_tls13_generic.c
library/ssl_tls13_keys.h
tests/scripts/all.sh

Build and run TLS 1.3 in a configuration where all hashes are provided by drivers.
Resolves: https://github.com/Mbed-TLS/mbedtls/issues/6132
```
*** Comparing before-default -> after-default ***
ssl: total 892; skipped 478 -> 478
mps: total  42; skipped  42 ->  42
*** Comparing before-full -> after-full ***
ssl: total 892; skipped  96 ->  96
mps: total  42; skipped   0 ->   0
*** Comparing reference -> drivers ***
ssl: total 892; skipped 445 -> 392
> Test mbedtls_endpoint sanity for the client                           : !MBEDTLS_SSL_PROTO_TLS1_3
> Test mbedtls_endpoint sanity for the server                           : !MBEDTLS_SSL_PROTO_TLS1_3
> DTLS Handshake with serialization, tls1_2                             : !MBEDTLS_SSL_PROTO_TLS1_3
> DTLS Handshake fragmentation, MFL=512 …
```

Driver-only hashes: TLS 1.3

---

CONTRIBUTING.md

Add a note about requiring contributors to specify "Copyright the Mbed TLS Contributors" as the preferred form of copyright acknowledgement.
Separate out the legal requirements on contributions (license, copyright, sign-off) into a separate section from the technical parts.
Backport: #6290 
Changelog: no

Clarify legal requirements for contributions

---

include/mbedtls/mbedtls_config.h
library/ssl_misc.h
library/ssl_tls13_client.c
library/ssl_tls13_generic.c
library/ssl_tls13_keys.c
library/ssl_tls13_keys.h
library/ssl_tls13_server.c
programs/ssl/ssl_client2.c
tests/ssl-opt.sh

preceding PR: ~~#6135~~
Finalize  NewSessionTicket parser/writer. 
This PR is to add session ticket identify and handshake psk setting. Also some tests.
NOTE:
- OpenSSL client test is removed. It can not send pre_shared_key when reconnection. NEED HELP to dig how to let openssl send session ticket.

TLS 1.3: NewSessionTicket: Finalize TLS 1.3 session tickets flow.

---

.gitattributes

Backport: #6302
Add a .gitattributes file that tells GitHub to highlight all `.function` files as if they were `.c` files. This aids in reviewing changes to tests.
To see the effect in GitHub, see [a function file in this branch](https://github.com/davidhorstmann-arm/mbedtls/blob/syntax-highlighting-function-files/tests/suites/helpers.function).
**READY**
NO although it can be backported if desired
NO

Use GitHub C syntax highlighting on test files

---

library/aes.c
library/camellia.c
library/chacha20.c
library/cipher.c
library/gcm.c
tests/suites/test_suite_aes.function
tests/suites/test_suite_camellia.function
tests/suites/test_suite_cipher.function
tests/suites/test_suite_gcm.function

This PR re-introduce enum check in files related to cipher in library.
NO  
NO

Validation remove and change in files related to cipher in library

---

library/sha1.c
library/sha256.c
library/sha512.c
tests/suites/test_suite_shax.function

This PR re-introduce enum check in files related to hash function in library.
NO  
NO

Validation remove change hash

---

library/ssl_tls13_server.c
tests/opt-testcases/tls13-kex-modes.sh

`pre_shared_key` extension is not allowed for HRR message. 
**READY**

TLS 1.3: PSK: Exclude pre_shared_key for HRR

---

library/pk.c
library/pkparse.c
library/pkwrite.c
tests/suites/test_suite_pk.data
tests/suites/test_suite_pk.function

This PR re-introduce enum check in files related to public key in library.
NO  
NO

Validation remove change pk

---

CMakeLists.txt
ChangeLog.d/fix_hard_link_across_drives

Fixes an issue on Windows where when the source and build directory are on different drives hard-linking to files or directory fails as it doesn't work across filesystem boundaries. 
Note also that symlinking is also not possible because it requires administrator privileges on Windows.
~~The solution copies the files using the built-in cmake `file(COPY)` command.~~
The solution copies the files using the built-in cmake `configure_file(src dest COPYONLY)` command.
As this command only operates on files, if a directory is specified the files will be globbed recursively
and through symlinks.
**READY**
Fixes #5751

Copy files instead of hard-linking on Windows

---

tests/scripts/all.sh

Fix https://github.com/Mbed-TLS/mbedtls/issues/6247
Backport: https://github.com/Mbed-TLS/mbedtls/pull/6309

Fix all.sh --force

---

tests/scripts/all.sh

Trivial backport of https://github.com/Mbed-TLS/mbedtls/pull/6248

Backport 2.28: Fix all.sh --force

---

library/dhm.c
library/rsa.c
tests/suites/test_suite_rsa.function

This PR re-introduce enum check in files related to key agreement in library.
NO  
NO

Validation remove change key agree

---

library/chachapoly.c
library/poly1305.c

This PR re-introduce enum check in files related to authenticated encryption in library.
NO  
NO

Validation remove change auth enc

---

ChangeLog.d/tls13_sig_alg_selection.txt
library/ssl_tls13_generic.c
library/ssl_tls13_server.c
programs/ssl/ssl_client2.c
programs/ssl/ssl_server2.c
programs/ssl/ssl_test_lib.c
tests/ssl-opt.sh

TLS 1.3: Take into account key policy while picking a signature algorithm.
Resolves https://github.com/Mbed-TLS/mbedtls/issues/5844
@mpg @ronald-cron-arm Do we need extra tests for this change?
NO  
NO

Permissions 2b: TLS 1.3 sigalg selection

---

tests/suites/test_suite_ecdh.function
tests/suites/test_suite_ecdsa.function
tests/suites/test_suite_ecjpake.function
tests/suites/test_suite_ecp.function

Straightforward backport of #6325 with an addition of initialization in ecdsa_invalid_param function in test_suite_ecdsa.function.
Resolve #6308.

[Backport 2.28]  Add initialization for structures in test

---

tests/suites/test_suite_ecdh.function
tests/suites/test_suite_ecjpake.function
tests/suites/test_suite_ecp.function

Add missing initialization that cause build error.
Fix #6308

Add initialization for structures in test

---

scripts/config.py

See https://github.com/Mbed-TLS/mbedtls-docs/pull/51#discussion_r972217817
Changelog: no (comment only)
Backport: https://github.com/Mbed-TLS/mbedtls/pull/6402

Add a note that config.py must remain compatible with Python 3.4

---

tests/include/test/helpers.h
tests/src/helpers.c
tests/suites/test_suite_mpi.data
tests/suites/test_suite_mpi.function

This is a continuation of https://github.com/Mbed-TLS/mbedtls/pull/6386 which allows bignum-core inputs to have an odd number of hex digits. (This is allowed for legacy bignums.) This is backward compatible for test data, but test functions now need to take a `char*` input instead of `data_t*`.
This pull request also adds tests for `mbedtls_mpi_core_bitlen` (I wanted a little more validation of the new auxiliary function). If we decide to merge https://github.com/Mbed-TLS/mbedtls/pull/6386, these commits are still useful.
Changelog: no (test only)
Backport: no (test framework, but only related to a new library feature)

mbedtls_test_read_mpi_core: support an odd number of hex digits

---

ChangeLog.d/fix_build_tls1_2_with_single_encryption_type.txt
include/mbedtls/check_config.h
include/mbedtls/mbedtls_config.h
library/constant_time.c
library/constant_time_internal.h
library/psa_crypto.c
library/ssl_msg.c
library/ssl_ticket.c
programs/fuzz/fuzz_server.c
programs/ssl/ssl_server2.c
tests/scripts/all.sh
tests/suites/test_suite_cipher.function
tests/suites/test_suite_cmac.data

Resolves https://github.com/Mbed-TLS/mbedtls/issues/6313
**READY**
Yes/2.28
https://github.com/Mbed-TLS/mbedtls/pull/6394
NO

Test TLS 1.2 builds with each encryption type

---

tests/scripts/run-test-suites.pl

This is a quality-of-life improvements for `run-test-suites.pl` (used by `make test`).
In verbose mode, the full output of each failing suite is printed out, which for some suites runs in the 1000s of lines. If you didn't redirect output to a file that you could grep, this is a lot to scroll and can make it hard to quickly identify which test suites failed, as you need to identify the boundaries of each suite's output.
So, let's print out that information at the end. This is useful information for starting to figure out what went wrong.
**READY**
Yes - tooling improvement
2.28: #6412 
Nope, this only matters to developers, not normal users.

Print the list of failed suites in verbose mode

---

tests/scripts/run-test-suites.pl

This is the 2.28 backport of #6403

[backport 2.28] Print the list of failed suites in verbose mode

---

tests/suites/test_suite_asn1parse.function

This is the 2.28 backport of #6419

backport 2.28 - Fix usage of ASSERT_ALLOC()

---

tests/suites/test_suite_lmots.function

Fixes https://github.com/Mbed-TLS/mbedtls/issues/6428
Note to reviewers: approving not only means that the patch is correct, but also that it handles all the [issues reported by Coverity](https://scan4.scan.coverity.com/reports.htm#v27693/p10660). That is, approvers must confirm that my Coverity triaging is correct.
* [381498](https://scan4.scan.coverity.com/reports.htm#v27693/p10660/fileInstanceId=122899021&defectInstanceId=14522571&mergedDefectId=381498): intentional
* [381499](https://scan4.scan.coverity.com/reports.htm#v27693/p10660/fileInstanceId=122899021&defectInstanceId=14522571&mergedDefectId=381499): fixed here
* [381500](https://scan4.scan.coverity.com/reports.htm#v27693/p10660/fileInstanceId=122899019&defectInstanceId=14522560&mergedDefectId=381500): false positive
* …

LMS: Fix memory leak if unit test fails

---

docs/architecture/psa-migration/outcome-analysis.sh
tests/scripts/all.sh

Improve outcome analysis by using an exclude list rather than an include list for test suites to compare, and making the reference configuration closer to the driver-based configuration.
**READY**
NO  - the script is in development only, to test development-only features
NO - this is a developer-only script

Improve outcome analysis for driver-only builds

---

scripts/mbedtls_dev/bignum_core.py
tests/suites/test_suite_bignum_core.function

Depends on https://github.com/Mbed-TLS/mbedtls/pull/6399
The commits presenting the idea about improving the test cases are: 719f6af102d48cc017aab7974f9f3c7ee5f1f505 and 0d6b79b1cc15c6e5d96125f3e47c1c37b17b45c3

Add split arch tests to bignum core

---

tests/suites/test_suite_bignum_mod_raw.function

Fixes Coverity issues 381527 and 381526.
**READY**
No
No changelog entry; this is in tests

mbedtls_mpi_mod_modulus_init() must be called before any 'goto exit' in tests

---

library/aria.c
library/asn1write.c
library/ecdh.c
library/ecp.c
library/sha256.c
library/sha512.c
library/ssl_client.c
library/ssl_msg.c
library/ssl_tls.c
library/ssl_tls12_client.c
library/ssl_tls12_server.c
library/ssl_tls13_server.c
programs/ssl/ssl_client2.c
programs/ssl/ssl_server2.c

Fix macros that either expand to or guard partial statements. This includes idioms like
```c
#if defined(MBEDTLS_SOME_OPTION)
if( some_condition )
#else
if( some_other_condition )
#endif
{
/* Body of if statement */
}
```
This change improves readability and allows us to use auto-formatting tools that will balk at unusual uses of macros.
[Script to look for problematic macro-spanning ifs](https://github.com/Mbed-TLS/mbedtls/pull/6397/commits/04fda377a77ac25994a2b22f7f476d79089453f1)
**READY**
Yes
Which branch? 2.28

Fix unusual macros

---

include/mbedtls/mbedtls_config.h
tests/suites/test_suite_psa_crypto_storage_format.function

The storage format tests (`test_suite_psa_crypto_storage_format.function`) try to exercise keys after loading them, in order to make sure everything is OK. However, this part is skipped if the configuration doesn't have what it takes to exercise that key. This is done with `can_exercised()` which in turn calls `is_builtin_calling_md()` in order to determine if we are using a built-in algorithm like RSA that's itself calling MD, hence requiring the hash used to also be built-in.
The conditions under which RSA is calling MD changed recently, but `is_builtin_calling_md()` wasn't updated. This PR fixes that.
- No backport (fix in a new feature).
- No ChangeLog entry (tests only, and also hasn't been in a release yet anyway).

Fix can_exercise() for RSA and hashes

---

library/ecp.c

Trivial backport of #5841 
Changelog: Not needed

Fix a timing leak in ecp_mul_mxz() - 2.28 backport

---

library/ecp.c

The bit length of m is leaked through through timing in ecp_mul_mxz().
Initially found by Manuel Pégourié-Gonnard on ecp_mul_edxyz(), which has
been inspired from ecp_mul_mxz(), during initial review of the EdDSA PR.
See: https://github.com/Mbed-TLS/mbedtls/pull/3245#discussion_r490827996
Fix that by using grp->pbits instead, which anyway is very close to the
length of m, which means there is no significant performance impact.
**READY**
Yes to maintained branches: development and mbedtls-2.28 - see #6492 
NO

Fix a timing leak in ecp_mul_mxz()

---

include/mbedtls/constant_time.h
include/mbedtls/legacy_or_psa.h

Exclude `mbedtls/legacy_or_psa.h` and its contents from the official API. We're [seriously considering reworking it](https://github.com/Mbed-TLS/mbedtls/issues/6471) but still discussing how, so do the minimum change so that it doesn't create an obligation on us.
I've reviewed the [changelog entry](https://github.com/Mbed-TLS/mbedtls/pull/6283/files#diff-e5017d84507d81c322dcf6dc95244d96a0e2673b53083c1d2dc1c33a91af00c1) from the [pull request that introduced `legacy_or_psa.h`](https://github.com/Mbed-TLS/mbedtls/pull/6283) and the related [changes in `mbedtls_config.h`](https://github.com/Mbed-TLS/mbedtls/pull/6283/files#diff-0279e5915ac49daea5fd9ed14934a074d1a88e9b35c674d7d1a0d0e0688f60bb), and I'm ok with preserving what is promised there (quite possibly, in some edge cases, by forcibly …

Make legacy_or_psa.h private

---

library/bignum_mod.c
library/bignum_mod.h
tests/suites/test_suite_bignum_mod.function
tests/suites/test_suite_bignum_mod_raw.function

Notes:
This pr expands the new bignum interface as follows:
* Adds a new struct `mbedtls_mpi_mont_struct` to store the inverse mod and Montgomery constant
* Updates `mbedtls_mpi_mod_modulus_setup/free()` to properly precacacluate and store, zeroise said fields.
* Adds tests
**READY**
NO  
NO

Bignum: Updated the modulus lifecyle

---

tests/configs/tls13-only.h
tests/scripts/all.sh

Remove 5 components from `all.sh` that were fully or almost fully redundant with other components.
We've talked about removing the `build_psa_accel_*` components that build with drivers for a specific feature because they don't do much: there are now tests `test_psa_crypto_config_accel_` that test with drivers. But the build components do something that the test components don't do yet, which is to validate that the correct `#ifdef` guards are in place for specific features. Until we have a `depends.py`-style script that tests with one algorithm accelerated at a time (or something like this), the cookie-cutter `build_psa_accel_*` have some utility, so I think they should stay.
I looked for opportunities to group components together, which would improve CI performance because we sometimes …

Remove a few redundancies from all.sh

---

tests/scripts/all.sh

Backport of #6510.
This omits the parts related to TLS 1.3, and doesn't attempt to identify additional wins specific to 2.28.

All.sh redundancies 2.28

---

README.md

Update PSA links in README.md - 2.28 backport

---

README.md

Update PSA links in README.md. Remove one of the PSA sections as it was a bit redundant with the one above it.
Changelog: no
Backport: #6526

Update PSA links in README.md

---

.github/pull_request_template.md
CONTRIBUTING.md

Almost trivial backport of #6514.
This PR makes `CONTRIBUTING.md` and `.github/pull_request_template.md` identical to the copies in the development branch.

Update pr template - 2.28 backport

---

.github/pull_request_template.md
CONTRIBUTING.md

Aim is to simplify the template, and provide gatekeepers / release-leads with a quick checklist of the things that are often missed.
Backport: #6527 

Update PR template

---

library/bignum.c
library/bignum_core.c
library/bignum_core.h
tests/suites/test_suite_bignum.misc.data
tests/suites/test_suite_bignum_core.function
tests/suites/test_suite_bignum_core.misc.data

Implement `mbedtls_mpi_core_fill_random`, in partial fulfillment of https://github.com/Mbed-TLS/mbedtls/issues/6239.
Continues https://github.com/Mbed-TLS/mbedtls/pull/6449.
Status: ready (subject to CI)
Changelog: no (internal function)
Backport: no (new feature)

Bignum core: fill_random

---

library/aria.c
library/asn1write.c
library/ecdh.c
library/ecp.c
library/sha512.c
library/ssl_cli.c
library/ssl_msg.c
library/ssl_srv.c
library/ssl_ticket.c
library/ssl_tls.c
library/x509_crt.c
programs/ssl/ssl_client2.c
programs/ssl/ssl_server2.c

Pseudo-backport of #6467. In practice, only some of the changes overlap, and this PR contains other macro fixes not fixed in the original PR.
Refactor unusual uses of macros to allow code auto-formatting tools to be run successfully on the code.
**READY**

[Backport-ish 2.28] Fix unusual macros

---

ChangeLog.d/fix_tls13_session_resumption_fail_when_hostname_is_not_localhost.txt
library/ssl_tls.c
programs/ssl/ssl_client2.c
tests/ssl-opt.sh

Fix #6488.
#6488 is not due to `TLS 1.3 session resumption`, that's due to CA wrong. 
But there are still some problems in `TLS 1.3 session resumption` which introduced by `reco_server_name` of `ssl_client2`.  And the output message about certification fail should be update
**READY**
Backport: no, TLS 1.3 not in 2.28
Changelog: yes

BUG: Fix session resumption fail when hostname is not localhost

---

library/ssl_tls.c

`mbedtls_ssl_handshake_step()` shouldn't return `0` (success) if an invalid context is passed in, in this easy-to-detect way.
Doesn't need a ChangeLog entry, as this isn't something that is really visible to the user of the library, it is "just" better representing what a function finds of its inputs (in the same way we have `MBEDTLS_ERR_ERROR_CORRUPTION_DETECTED`)
Fixes #6305
**READY**
**NO** - 2.28-LTS already returns an error (specifically `MBEDTLS_ERR_SSL_FEATURE_UNAVAILABLE`) in this case, so this could be considered to be a regression.

Return an error from mbedtls_ssl_handshake_step() if neither client nor server

---

tests/suites/test_suite_bignum_core.function
tests/suites/test_suite_bignum_mod_raw.function

Follow-up PR for #6289. Use the `mbedtls_test_read_mpi_core` function, introduced in #6386 and #6398, in conditional assign and swap test functions.

Update tests to use conditional assign and swap

---

library/ssl_msg.c

The debug message was incorrectly adapted when `mbedtls_ssl_set_bio_timeout()` was renamed to `mbedtls_ssl_set_bio()` in:
https://github.com/Mbed-TLS/mbedtls/commit/1b511f93c6353db39da0ae7534fb8c7a884f9f47#diff-76b73bf2a8157ee95fdd3b688384812654c63878be4ecce6ee56402eb52b1f4fL2188-L2376
Backport: #6554

Fix outdated reference in debug message

---

include/mbedtls/bignum.h

Trivial backport of https://github.com/Mbed-TLS/mbedtls/pull/6552

Backport 2.28: Add comments for some forbidden aliasing in bignum.h interfaces

---

include/mbedtls/bignum.h

Add comments for some forbidden aliasing in bignum.h interfaces
While porting hostap to use mbedtls, I encountered some aliasing issues which resulted in bugs both difficult and time consuming to trace through crypto calculations to track down.  This PR adds comments about non-aliasing requirements of `mbedtls_mpi_exp_mod` and `mbedtls_mpi_div_mpi` beyond those already documented (recently updated comment in dcd1717f5):
```
* - **Aliasing**: in general, output bignums may be aliased to one or more
*   inputs. As an exception, parameters that are documented as a modulus value
*   may not be aliased to an output. Outputs may not be aliased to one another.
*   Temporaries may not be aliased to any other parameter.
```
([There may be other …

Add comments for some forbidden aliasing in bignum.h interfaces

---

include/mbedtls/lms.h

This adds a missing private access header.
Signed-off-by: Moritz Fischer <moritzf@google.com>
Fix compile errors.
Should be fairly non-controversial.

include: mbedtls: Add missing private_access header

---

tests/suites/test_suite_psa_crypto.function

The problem described in https://github.com/Mbed-TLS/mbedtls/issues/6503 was caused by two bytes filled with zeros being shifted in tests:
```
buffer0[s_x1_pk_off + 8] >>= 4;
buffer0[s_x2_pk_off + 7] <<= 4;
```
The test expected an error, but with zeros in place the data doesn't change.
Fix - instead of shifting date, perform a bitflip.
Also, instead of corrupting the public key part of the message, corrupt the proof part. A proof is conceptually similar to a signature, and changing anything in it should make it invalid with a high probability (as @mpg has noted).
Fixes https://github.com/Mbed-TLS/mbedtls/issues/6503.
**Changelog not needed**, since it's a test fix, **backport not needed**, since it's a feature that's not backported.

Improve error injection in EC J-PAKE tests

---

tests/scripts/run-test-suites.pl

Looking for executables causes problems with leftover compiled test suites from other branches when we forget to run make clean before switching branches. Using the .data files is more robust as most of them are tracked, so will be removed when switching branches.
**Testing:**
- tested locally on Linux, both that it ignores extra executables (see steps below), and that it runs the expected number of suites;
- checked in CI logs that it executes the expected number of suites in `Windows-mingw` (`win32-msvc12_{64,32}` are not running the test suites, and `Windows-2013` and `win32-mingw` use cmake which doesn't use this script).
Steps to reproduce:
```
make tests
(cd tests && cp /bin/false test_suite_00leftover)
make test
```
Before: runs `test_suite_00leftover` and fails. After: correctly …

Improve test suite detection in run-test-suites.pl

---

tests/scripts/run-test-suites.pl

This is the 2.28 backport of https://github.com/Mbed-TLS/mbedtls/pull/6543

[backport 2.28] Improve test suite detection in run-test-suites.pl

---

programs/ssl/ssl_client2.c
programs/ssl/ssl_server2.c
programs/ssl/ssl_test_lib.h

Backport the changes in PR #6436 to branch mbedtls-2.28.
Signed-off-by: Yanray Wang <yanray.wang@arm.com>
This commit is identical with PR #6436 in order to resolve issue of #5443

Backport 2.28: Add build version to the output of ssl_client2 and ssl_server2

---

scripts/mbedtls_dev/bignum_mod_raw.py
tests/scripts/generate_bignum_tests.py

This pr is implementing some required base classes ( **BignumModRawOperation**, **BignumModRawOperationArchSplit** )for `bignum_mod_raw.py module`.  
The class structure is configured in order to make is simpler for test classes to inherit from it.
* Adds new optional parameters, which dynamically calculate or convert members if requested.
* Adjusts the expected input variable pair from `(val_a, val_b)` to `(val_n, val_a, val_b(optional)`)
* Added the optional `bits_to_limbs` argument which allows generation of 32 and 64 bit tests cases.
* Added zeropadded string hex representations of all input arguments.

Bignum: Add BignumModRaw Operation base classes

---

tests/suites/test_suite_bignum_mod_raw.function

Fixes (new) Coverity issues 381893 and 381894

Bignum: Must call mbedtls_mpi_mod_modulus_init() before anything else in tests

---

ChangeLog.d/fix_dh_genprime_error_reporting.txt
programs/pkey/dh_genprime.c

[Backport 2.28] dh_genprime: Fix issue where the error code returned by mbedtls_mpi_write_file() is incorrectly reported on failure

---

ChangeLog.d/fix_dh_genprime_error_reporting.txt
programs/pkey/dh_genprime.c

In `dh_genprime.c`, the following condition can be found inside an `if` statement:
```
ret = mbedtls_mpi_write_file( "P = ", &P, 16, fout ) != 0 
```
As the `!=` operator binds closer than the assignment operator (`=`), the value assigned to `ret` will be the boolean result of the comparison (0 or 1) instead of the status code returned by `mbedtls_mpi_write_file`. This means that the above statement is actually equivalent to:
```
ret = ( mbedtls_mpi_write_file( "P = ", &P, 16, fout ) != 0 )
```
What we want instead is for the the status code to be assigned to `ret`. If the value assigned is non-zero, it will be 'truthy' and the `if` branch will be taken.
```
( ret = mbedtls_mpi_write_file( "P = ", &P, 16, fout ) )  != 0 
```
This PR fixes the issue by explicitly specifying the precedence …

dh_genprime: Fix issue where the error code returned by mbedtls_mpi_write_file() is incorrectly reported on failure

---

ChangeLog.d/negative-zero-from-add.txt
include/mbedtls/bignum.h
library/bignum.c
tests/include/test/helpers.h
tests/scripts/generate_bignum_tests.py
tests/src/helpers.c
tests/suites/test_suite_bignum.function
tests/suites/test_suite_bignum.generated.data
tests/suites/test_suite_bignum.misc.data

In the bignum module, operations of the form (-A) - (+A) or (-A) - (-A) with A > 0 created a "negative zero" representation of the value 0. Fix this.
The negative zero was processed correctly (i.e. as if it was a valid representation of 0) by most bignum operations (in particular all variants of add, sub, mul and div, as well as `mbedtls_mpi_mod_mpi`), but not all (`mbedtls_mpi_mod_int` outputs b instead of 0 for (-X) % b when X is a multiple of b, and `mbedtls_mpi_lt_mpi_ct` treats -0 as strictly less than +0). This bug had no consequence on cryptography code.
This is the 2.28 backport. I did it before the `development` version because in `development`, this may clash with the bignum refactoring.
Contents:
* Fix the bug.
* In bignum test case generation for binary operations, test both x …

Backport 2.28: Fix negative zero from bignum add/subtract

---

ChangeLog.d/negative-zero-from-add.txt
include/mbedtls/bignum.h
library/bignum.c
scripts/mbedtls_dev/bignum_common.py
tests/include/test/helpers.h
tests/scripts/generate_bignum_tests.py
tests/src/helpers.c
tests/suites/test_suite_bignum.function
tests/suites/test_suite_bignum.misc.data

In the bignum module, operations of the form (-A) - (+A) or (-A) - (-A) with A > 0 created a "negative zero" representation of the value 0. Fix this.
The negative zero was processed correctly (i.e. as if it was a valid representation of 0) by most bignum operations (in particular all variants of add, sub, mul and div, as well as `mbedtls_mpi_mod_mpi`), but not all (`mbedtls_mpi_mod_int` outputs b instead of 0 for (-X) % b when X is a multiple of b, and `mbedtls_mpi_lt_mpi_ct` treats -0 as strictly less than +0). This bug had no consequence on cryptography code.
Contents:
* Fix the bug.
* In bignum test case generation for binary operations, test both x op y and y op x. We previously refrained from doing that because it would have triggered this bug. This way we get a non-regression test. …

Fix negative zero from bignum add/subtract

---

ChangeLog.d/fix-tls12server-sent-sigalgs.txt
library/ssl_tls12_client.c
library/ssl_tls12_server.c
tests/ssl-opt.sh

Fix a bug whereby the supported signature algorithm list sent by the TLS1.2 server in the certificate request would not leave enough space for the length to be written, and thus the first element would get overwritten, leaving two random bytes in the last entry. 
@AndrzejKurek has provided tests for this.

Fix TLS1.2 signature algorithms list entry getting overwritten by length.

---

tests/suites/test_suite_bignum_mod_raw.function

Manual inspection found these two, in addition to the ones Coverity found, which were fixed in #6604

Must call mbedtls_mpi_mod_modulus_init() before anything else in tests

---

ChangeLog.d/mpi-add-0-ub.txt
ChangeLog.d/mpi-most-negative-sint.txt
include/mbedtls/bignum.h
library/bignum.c
tests/suites/test_suite_bignum.function
tests/suites/test_suite_bignum.misc.data

Fix two kinds of typically harmless undefined behavior in bignum:
* NULL+0 when doing 0+0 in `mbedtls_mpi_add_abs()`
* -SINT_MIN (https://github.com/Mbed-TLS/mbedtls/issues/6597)
A reasonably modern UBSan with Clang (Ubuntu 20.04 with Clang 10) complains about both (but not GCC 12 from Ubuntu 22.04 or Clang 6 from Ubuntu 18.04). The addition bug already had a test, but we only run an ancient UBSan on our CI. I added a test for -SINT_MIN, without using the test framework to pass function arguments because you can't easily pass the interesting values.

Fix undefined behavior in bignum: NULL+0 and -most-negative-sint

---

ChangeLog.d/mpi-add-0-ub.txt
ChangeLog.d/mpi-most-negative-sint.txt
include/mbedtls/bignum.h
library/bignum.c
tests/suites/test_suite_bignum.function
tests/suites/test_suite_bignum.misc.data

Fix two kinds of typically harmless undefined behavior in bignum. Trivial backport of https://github.com/Mbed-TLS/mbedtls/pull/6609.

Backport 2.28: Fix undefined behavior in bignum: NULL+0 and -most-negative-sint

---

tests/scripts/run-test-suites.pl

Improve https://github.com/Mbed-TLS/mbedtls/pull/6543 to work in out-of-tree builds. Look for the `.datax` file rather than the `.data` file.

Fix run-test-suites.pl in out-of-tree builds

---

tests/scripts/run-test-suites.pl

Trivial backport of https://github.com/Mbed-TLS/mbedtls/pull/6611

Backport 2.28: Fix run-test-suites.pl in out-of-tree builds

---

library/ssl_tls13_client.c
tests/opt-testcases/tls13-misc.sh

Parse early data indication in encrypted extentions.
Empty to indicate that early data supported by server side.

Tls13 parse early data indication ee

---

library/bignum.c
library/bignum_core.c
library/bignum_core.h
scripts/mbedtls_dev/bignum_core.py
tests/suites/test_suite_bignum_core.function

Extract MPI_CORE(sub_int) from the [prototype](https://github.com/hanno-arm/mbedtls/blob/ecp_prototype/library/bignum_core.c#L214-L227). Fixes #6231
**READY**
**NO**

Bignum: extract core_sub_int from the prototype

---

docs/architecture/tls13-support.md
include/mbedtls/ssl.h
library/ssl_tls13_client.c

Add definition of mbedtls_ssl_{write,read}_early_data to write and read early data.
Fix #4902
Fix #6310

TLS 1.3: Add definition of mbedtls_ssl_{write,read}_early_data

---

ChangeLog.d/driver-only-hashes.txt
include/mbedtls/mbedtls_config.h

Fixes #6497 by documenting the limitation.

Document another limitation of driver-only hashes

---

tests/compat.sh

Fix #6650
I've done some checks of the number of tests: full configuration + OpenSSL 1.0.2g.
./tests/compat.sh -p OpenSSL -m "ssl3 tls1 tls1_1 dtls1":
. mbedtls-2.28 + this PR: 232 tests 2 skipped
. mbedtls-2.28.0: 232 test 2 skipped
./tests/compat.sh
. mbedtls-2.28 + this PR: 1984 tests 4 skipped
. mbedtls-2.28.0: 856 tests 2 skipped
Much more tests now because of #5660 I think.

2.28 compat.sh: Restore testing against OpenSSL for pre 1.2 TLS versions

---

ChangeLog.d/fix-possible-false-success-in-mbedtls_cipher_check_tag.txt
library/cipher.c
tests/suites/test_suite_cipher.function

Originally this was PR #2164 - creating a new PR as that was based off user's `development` branch
I've taken the commit in the original PR, fixed the conflict, and updated the tests to reflect the new return values in the "you shouldn't call these functions in this mode" cases.
This is not a bug fix - calling AEAD-specific functions on non-AEAD algorithms is misuse of the library - rather, this is a change of library behaviour to help badly-written calling code fail safe. Both the previous behaviour and this new behaviour comply with the documentation of these functions. Accordingly I don't think it needs a backport.
Original description:
We should report a error when the security check of the security
tag was not made. In the other case false success is possible and
is not observable by …

mbedtls: fix possible false success in mbedtls_cipher_check_tag()

---

.travis.yml
ChangeLog.d/psa-ecb-ub.txt
library/aria.c
library/chacha20.c
library/common.h
library/debug.c
library/ecp.c
library/ecp_curves.c
library/mps_reader.c
library/poly1305.c
library/psa_crypto.c
library/psa_crypto_cipher.c
tests/compat.sh
tests/ssl-opt.sh
tests/suites/test_suite_psa_crypto.function

Backport of https://github.com/Mbed-TLS/mbedtls/pull/6648. Differences:
* Define `inline` in `library/common.h`, don't touch public headers in the LTS.
* I included Ronald's fix from https://github.com/Mbed-TLS/mbedtls/pull/6654 so we don't have surprises later on the CI.
* The set of things that didn't work out of the box was different in 2.28, but I found a simple fix that solves all of them for OpenSSL which I forward-ported.

Backport 2.28: Fix NULL+0 undefined behavior in PSA crypto ECB

---

.travis.yml
ChangeLog.d/psa-ecb-ub.txt
include/mbedtls/aes.h
include/mbedtls/build_info.h
include/mbedtls/cipher.h
include/mbedtls/error.h
include/mbedtls/pem.h
include/mbedtls/pk.h
include/psa/crypto_platform.h
library/aria.c
library/chacha20.c
library/common.h
library/debug.c
library/ecp.c
library/ecp_curves.c
library/mps_reader.c
library/poly1305.c
library/psa_crypto.c
library/psa_crypto_cipher.c
library/ssl_misc.h
tests/compat.sh
tests/ssl-opt.sh
tests/suites/test_suite_psa_crypto.function

Fix NULL+0 undefined behavior in PSA crypto ECB code and tests.
This is caught by UBSan with Clang ≥10 (but not GCC 11). So this pull request is necessary so that ASan builds work on Ubuntu 20.04 and up.
We aren't currently catching this on the CI because we only test on ancient Linux platforms (Ubuntu 16.04, Ubuntu 18.04). Moving some CI testing opens a big can of worms (see https://github.com/Mbed-TLS/mbedtls/pull/6614) which should not hold the bug fix. So here I'm keeping the non-regression testing to something small: I'm replacing the full-config job on Travis by one that uses Clang 10, and only tests what works out of the box on Ubuntu 20.04.
As a consequence, Travis will not be (nearly identical to) a subset of Jenkins. We used to desire this property because we didn't have Travis …

Fix NULL+0 undefined behavior in PSA crypto ECB

---

library/bignum_mod_raw.c
library/bignum_mod_raw.h
scripts/mbedtls_dev/bignum_mod_raw.py
tests/suites/test_suite_bignum_mod_raw.function

Resolves #6225 
Adds `mbedtls_mpi_mod_raw_add()`, with implementation from [prototype](https://github.com/hanno-becker/mbedtls/blob/ecp_prototype/library/bignum_core.c#L415-L426).
This is modified to take a modulus structure in place of the modulus mpi and limbs parameters.
Test cases are generated for a variety of moduli using the python test framework.
**Most of this work is from Werner's PR #6546, with minor changes to comments by me, and completely different python test generation, using the new framework**

Bignum: add mod_raw_add

---

ChangeLog.d/move-ssl-modules.txt
library/CMakeLists.txt
library/Makefile

`ssl_debug_helpers_generated` was accidentally added to libmbedcrypto instead of libmbedtls in 3.1. The MPS modules were accidentally added to libmbedcrypto instead of libmbedtls in 2.27. Move them to the correct library.
This is an ABI change for libmbedcrypto (a new libmbedtls wouldn't work with the old libmbedcrypto since it's missing those functions). It isn't an API change since none of those modules implement any functions that are part of the API.
The bug is also present in 2.28, but this only concerns TLS 1.3 (the only feature that uses MPS) and in 2.28 it's a work in progress that isn't really usable for anything. So it's not worth breaking the ABI in 2.28 LTS.

Move SSL modules out of libmbedcrypto

---

ChangeLog.d/ecjpake-in-tls.txt

Missing changelog entry after https://github.com/Mbed-TLS/mbedtls/pull/6533 was merged.
Fixes https://github.com/Mbed-TLS/mbedtls/issues/6653.

Add a changelog entry explaining usage of PSA in TLS 1.2 EC J-PAKE

---

ChangeLog.d/dtls-connection-id.txt

We managed to forget it in https://github.com/Mbed-TLS/mbedtls/pull/6264

Add ChangeLog entry for DTLS Connection ID

---

tests/CMakeLists.txt

If the variable SKIP_TEST_SUITES is not defined with -D, but is defined in an environment variable, tell cmake to get it from there.
This should allow #6665 to work.

Tell cmake to get SKIP_TEST_SUITES from ENV

---

library/bignum_core.c
library/bignum_core.h
scripts/mbedtls_dev/bignum_core.py
tests/suites/test_suite_bignum_core.function
tests/suites/test_suite_bignum_core.misc.data

The second PR of a series related to #6293 .

Bignum: Extract mod exp from prototype

---

tests/data_files/Makefile
tests/data_files/test-ca.opensslconf

Fix a typo in test files: "unsupoported" is not a word.

Fix typo 'unsupoported' -> 'unsupported'

---

tests/data_files/Makefile
tests/data_files/test-ca.opensslconf

[Backport 2.28] Fix typo 'unsupoported' -> 'unsupported'

---

library/ssl_misc.h
library/ssl_tls.c
library/ssl_tls13_keys.c
library/ssl_tls13_keys.h

fix #6341 
Add needed functions for computing early keys

TLS 1.3: EarlyData: Add early data transform computation

---

tests/scripts/basic-build-test.sh

`basic-build-test.sh` calls itself `basic-build-tests.sh` internally, which is wrong, so fix it.

Fix the name of basic-build-test.sh within the file

---

tests/scripts/basic-build-test.sh

`basic-build-test.sh` calls itself `basic-build-tests.sh` internally, which is wrong, so fix it.

Backport 2.28: Fix name of basic build test.sh 2.28

---

scripts/mbedtls_dev/bignum_mod.py
tests/CMakeLists.txt
tests/Makefile
tests/scripts/generate_bignum_tests.py

Adds the `bignum_mod` module to the bignum test generation script, and as a dependency for the `generated_file` target in CMake and make. This is a prerequisite for adding tests to `bignum_mod.py`.

Bignum: Enable test generation from bignum_mod.py

---

library/bignum_mod.c
library/bignum_mod.h
scripts/mbedtls_dev/bignum_mod.py
tests/suites/test_suite_bignum_mod.data
tests/suites/test_suite_bignum_mod.function

Fixes #6020 (Implement fixed width modular subtraction)

Implement mbedtls_mpi_mod_sub()

---

ChangeLog.d/fix_build_tls1_2_with_single_encryption_type.txt
ChangeLog.d/fix_cmake_using_iar_toolchain.txt
ChangeLog.d/fix_zeroization.txt

Backport of https://github.com/Mbed-TLS/mbedtls/pull/6689. Only a few changes were in bugfixes with backports. `ChangeLog.d` is identical here and in https://github.com/Mbed-TLS/mbedtls/pull/6689 except for files that are only present in 3.3 and for `psa_rsa_needs_pk.txt` where 2.28 and 3.3 had different problems in the same area.

Backport 2.28: Changelog improvements for 3.3

---

tests/CMakeLists.txt

Simple backport of #6676, will allow #6710 to work.

[backport 2.28] Tell cmake to get SKIP_TEST_SUITES from ENV

---

library/bignum_core.c
library/bignum_core.h
scripts/mbedtls_dev/bignum_common.py
scripts/mbedtls_dev/bignum_core.py
scripts/mbedtls_dev/bignum_mod_raw.py

One of the PRs needed for #6293

Require input to mbedtls_mpi_core_exp_mod() to already be in Montgomery form

---

library/bignum_core.c
library/bignum_core.h
scripts/mbedtls_dev/bignum_common.py
scripts/mbedtls_dev/bignum_core.py
scripts/mbedtls_dev/bignum_mod_raw.py
tests/suites/test_suite_bignum_core.function

This is the last PR needed for #6293
Based on top of #6731 (which now has two approvals, just waiting for CI to complete before it can go in)
The new content of this PR is the final commit

Have mbedtls_mpi_core_exp_mod() take a temporary instead of allocating memory

---

tests/scripts/all.sh

This is the 2.28 backport of #6683 - only the part about -O2 with Asan, the rest is not applicable since the affected component is only present in development (and part of the rest was reverted anyway).

[backport 2.28] Optimize with asan

---

tests/scripts/all.sh

This is an attempt at resolving https://github.com/Mbed-TLS/mbedtls/issues/6662, see [this comment](https://github.com/Mbed-TLS/mbedtls/issues/6662#issuecomment-1330347859) and the next one in particular.
Running time of this component on my laptop (which ccache disabled):
- Before: 26:17
- After first commit: 20:51 (-20%)
- ~After second commit 19:18 (-8% from previous commit, -26% total)~ reverted
- After third commit 14:43 (-24% from previous commit, -40% total)
~Note: the second commit only addresses `test_psa_crypto_config_accel_hash_use_psa` but could be applicable to other components that build with libtestdriver1. However I wanted to wait for review feedback before applying it everywhere. (Note that it's also the change with the least impact.)~ (Edit: reverted.)

Optimize with asan

---

ChangeLog

The wrong generated file is referred to as having been missing in the changelog entry for 3.2.1. The missing file was library/psa_crypto_driver_wrappers.c, not library/ssl_debug_helpers_generated.c.
**READY**
NO  
NO

Fix missing file name in changelog

---

ChangeLog.d/alignment-perf.txt
README.md
library/aes.c
library/alignment.h
library/aria.c
library/bignum_core.c
library/camellia.c
library/ccm.c
library/chacha20.c
library/cmac.c
library/common.h
library/ctr_drbg.c
library/des.c
library/gcm.c
library/md.c
library/pkcs5.c
library/platform_util.c
library/ssl_msg.c
tests/suites/test_suite_alignment.data
tests/suites/test_suite_alignment.function
tests/suites/test_suite_common.data
tests/suites/test_suite_common.function

Following on from #6641, more efficient versions of all of the unaligned memory access macros.
Typically something like MBEDTLS_GET_UINT32_BE will compile to two instructions. For some compilers, this is equivalent to the existing code; for others (e.g. GCC targeting Arm v8) it's a big improvement.
Example: https://gcc.godbolt.org/z/Prooo6ePv
Fixes #1666.

Fast unaligned memory access macros

---

library/entropy.c

Signed-off-by: Zachary Fleckenstein <ZachFleck42@Gmail.com>
Fixes a typo in `entropy.c`; specifically changes 'hat' to 'that' on line 567.

Fix typo in `library/entropy.c`

---

library/entropy.c

Signed-off-by: Zachary Fleckenstein <ZachFleck42@Gmail.com>
Fixes a typo in `entropy.c`; specifically changes 'hat' to 'that' on line 593.

Backport 2.28: Fix typo in `library/entropy.c`

---

include/mbedtls/check_config.h
include/mbedtls/legacy_or_psa.h
include/psa/crypto_values.h
library/psa_crypto_aead.h
library/psa_crypto_its.h
library/psa_crypto_rsa.h
scripts/data_files/driver_templates/psa_crypto_driver_wrappers.c.jinja
tests/scripts/check_names.py

This PR extends typo checks of `check_names.py` to include PSA macro/enum names.
Resolve: #6416
**READY**

check_names: extend typo check to PSA macro/enum names

---

include/mbedtls/cipher.h

Refactor the `MBEDTLS_DEPRECATED` macro to be in front of the function name rather than on its own line after the function arguments.
If it is placed on its own line, Uncrustify moves it to the start of the line which causes `check_names.py` to think it is an identifier. As a result `check_names.py` doesn't treat it as a macro name and it gets detected as a typo.

2.28 only: Move `MBEDTLS_DEPRECATED` annotation to prefix

---

CMakeLists.txt
ChangeLog.d/cmake-install.txt
programs/test/cmake_package_install/CMakeLists.txt

Right now, CMake files are installed in `<prefix>/cmake`. That being said, it gets easily bloated, and the standard is to use a directory with the same name as the project `<prefix>/lib/cmake/<name>`.
I discovered this issue with this "bug": https://github.com/termux/termux-packages/issues/12416
The issue's author claimed that MbedTLS's files were not installed in the `lib` directory. But the patch applied broke CMake's search of mbedTLS config files. So I wanted to upstream the real fix here instead.
Note that `CMAKE_INSTALL_LIBDIR` is set by `include(GNUInstallDirs)` at line 42.
Here are some examples of projects using directories:
- https://github.com/xiph/flac/blob/1.4.2/CMakeLists.txt#L239
- https://gitlab.freedesktop.org/dbus/dbus/-/blob/dbus-1.15.2/CMakeLists.txt#L675
- …

Install CMake files in MbedTLS dir

---

include/mbedtls/ssl.h
library/ssl_tls.c
programs/ssl/ssl_client2.c
programs/ssl/ssl_server2.c
tests/scripts/all.sh
tests/ssl-opt.sh
tests/suites/test_suite_ssl.data
tests/suites/test_suite_ssl.function

The goal of this PR is to enable the use of opaque passwords in EC-JPAKE.
Resolves #6599

Allow isolation of EC J-PAKE password when used in TLS

---

tests/Makefile
tests/scripts/generate_test_code.py
tests/scripts/test_generate_test_code.py
tests/suites/test_suite_psa_crypto.function

Trivial backport of https://github.com/Mbed-TLS/mbedtls/pull/6594

Backport 2.28: Allow comments in test function prototypes

---

tests/Makefile
tests/scripts/generate_test_code.py
tests/scripts/test_generate_test_code.py
tests/suites/test_suite_psa_crypto.function

Allow comments between `/* BEGIN_CASE */` and `void foo(…)`, and inside the argument list.
We have a bad habit of not documenting test functions. The fact that you can't put comments in the most natural place is a disincentive, which I am now lifting.
(You could always put comments before `/* BEGIN_CASE */`, but I didn't know that — turns out what's between `/* END_CASE */` and `/* BEGIN_CASE */` is silently ignored, so you can write whatever you like, but we shouldn't start relying on it.)

Allow comments in test function prototypes

---

scripts/mbedtls_dev/bignum_core.py
tests/suites/test_suite_bignum_core.function

Tests are refactored to generate separate cases for 32-bit and 64-bit limbs using `arch_split`. Duplicate arguments and branching in the test function is removed.
Resolves #6725.

Bignum: Refactor mpi_core_sub tests to use arch_split

---

tests/suites/test_suite_bignum_mod.function

Update the mod_sub tests to incorporate feedback that was given to mod_add tests that were based on mod_sub:
- [rename `oret` to `expected_ret`](https://github.com/Mbed-TLS/mbedtls/pull/6732#discussion_r1047292056) and
- [don't over allocate, to allow memsan to catch overflows](https://github.com/Mbed-TLS/mbedtls/pull/6732#discussion_r1047286674)

Update mbedtls_mpi_mod_sub() tests to incorporate mod_add test feedback

---

programs/fuzz/Makefile

Running make from programs/fuzz didn't set any optimization flags (running make from programs or from the root inherited the parent's optimization flags). Default to -O2.
There were no -W flags. Default to -Wall -Wextra, but not -Werror in line with the other makefiles.

programs/fuzz: set sensible default CFLAGS

---

programs/fuzz/Makefile

Trivial backport of https://github.com/Mbed-TLS/mbedtls/pull/6687

Backport 2.28: programs/fuzz: set sensible default CFLAGS

---

ChangeLog.d/pk-sign-restartable.txt
docs/architecture/psa-migration/psa-limitations.md
docs/use-psa-crypto.md
include/mbedtls/check_config.h
include/mbedtls/mbedtls_config.h
library/pk_wrap.c
scripts/config.py
tests/scripts/all.sh
tests/scripts/depends.py
tests/ssl-opt.sh
tests/suites/test_suite_ecp.function
tests/suites/test_suite_x509parse.function

This PR does two things:
1. Fix a documentation gap: there was no place except the ChangeLog that mentioned the effect of `MBEDTLS_ECP_RESTARTABLE` on TLS.
2. Remove a long-standing limitation by making it possible to build with both `ECP_RESTARTABLE` and `USE_PSA`. The result for TLS is not fully satisfying, but limitations are documented and tested, and this is still an improvement over the existing (mostly for non-TLS use of restartable).

Document ECP_RESTARTABLE and make it compatible with USE_PSA

---

include/mbedtls/check_config.h
include/mbedtls/config.h
tests/scripts/depends.py
tests/ssl-opt.sh
tests/suites/test_suite_ecp.function

This is the partial backport of #6723 - only the documentation fixes (and related test improvements), not the changes.
A few differences, both contextual, and due to the fact that it's only a partial backports, so I don't think it's trivial enough to qualify for single-reviewer.

[Backport 2.28] Document ECP_RESTARTABLE

---

library/bignum_mod.h
library/bignum_mod_raw.h

Adds conventions to `bignum_mod.h` and `bignum_mod_raw.h`, similar to those for core. Resolves #6684.

Bignum: document conventions for bignum mod and mod_raw

---

tests/opt-testcases/tls13-misc.sh

TLS 1.3: Fix some test dependencies

TLS 1.3: Fix some test dependencies

---

tests/scripts/check_names.py

[Backport 2.28] Fix an incorrect regex in check_names.py

---

tests/scripts/check_names.py

This PR fixes nightly CI failures in the code-style preview branches.
Allow check_names.py to detect declarations of the form:
`enum some_enum_name {`
This pattern has only just appeared due to code style correction, which explains why the issue was not previously noticed.
Backport: #6811

Fix an incorrect regex in check_names.py

---

README.md
tests/compat-in-docker.sh
tests/docker/bionic/Dockerfile
tests/make-in-docker.sh
tests/scripts/all-in-docker.sh
tests/scripts/basic-in-docker.sh
tests/scripts/docker_env.sh
tests/ssl-opt-in-docker.sh

This is an attempt at making Docker images from the CI more discoverable.
It's just a quick fix, in an ideal word all the `xxx-in-docker.sh` would be made to work with images from the CI, but in the meantime at least try to document the situation.
See also https://github.com/Mbed-TLS/mbedtls-test/pull/83

Point to docker images used in the CI

---

README.md
tests/compat-in-docker.sh
tests/docker/bionic/Dockerfile
tests/make-in-docker.sh
tests/scripts/all-in-docker.sh
tests/scripts/basic-in-docker.sh
tests/scripts/docker_env.sh
tests/ssl-opt-in-docker.sh

This is the 2.28 backport of #6789 - entirely trivial.

[Backport 2.28] Point to docker images used in the CI

---

library/bignum_mod_raw.c
library/bignum_mod_raw.h
scripts/mbedtls_dev/bignum_mod_raw.py
tests/suites/test_suite_bignum_mod_raw.function

Implement fixed width modular multiplication. The `_mod_raw` version should take a caller-managed buffer for the temporary buffer. 
Resolve #6022

Bignum: Implement fixed width raw modular multiplication

---

tests/scripts/basic-build-test.sh

Fix `basic-build-test.sh` failing when it reports the coverage statistics. I inadvertently broke this in https://github.com/Mbed-TLS/mbedtls/pull/6699 by adding an extra output line to `make lcov`. Unfortunately [we don't run `basic-build-test.sh` on pull requests](https://github.com/Mbed-TLS/mbedtls-test/issues/25).

Fix code_coverage broken by extra echo in make lcov

---

tests/scripts/basic-build-test.sh

This is the 2.28 backport of #6808 - entirely trivial.
Ad-hoc test run: https://jenkins-mbedtls.oss.arm.com/job/mbedtls-release-new/804/

[Backport 2.28] Fix code_coverage broken by extra echo in make lcov

---

ChangeLog.d/fix-gettimeofday-overflow.txt
library/timing.c

Backport of #6826, fixes #3066

Backport 2.28 - fix gettimeofday overflow

---

ChangeLog.d/fix-gettimeofday-overflow.txt
programs/test/benchmark.c

Fixes #3066. It's a (very minor) bug so probably should backport.

Fix gettimeofday overflow

---

.pylintrc

This patch adjusts pylint to disregard duplicate matches for up to 10 lines.
The number is chosen to permit overriding with up to 3 identical lines for `def arguments(self)` and
`def result(self)` while two more lines for `arity` and `input_style` in the bignum test suite.

pylint: Set a minimum duplicate match to 10 lines.

---

tests/scripts/all.sh

We aren't paying attention to the warnings ("Test description too long"). So hide them and save log size. Errors (which cause the test to fail) are still shown.

Hide check_test_cases warnings on the CI

---

.uncrustify.cfg

Backport 2.28: Tweak code style to be more like K&R

---

.uncrustify.cfg

* Require a space after a cast.

Tweak code style to be more like K&R

---

library/lms.c

Larger height (e.g. H=20) trees cannot be put on the stack. Allocate memory for them based on need using mbedtls_calloc().
Signed-off-by: Moritz Fischer <moritzf@google.com>
This is in preparation of adding H=20 support in a separate PR https://github.com/Mbed-TLS/mbedtls/pull/6584.

lms: Move merkle tree generation to heap allocation

---

include/mbedtls/bn_mul.h
library/aesni.c
library/padlock.c
library/timing.c

Backport of #6868.
The following code:
```c
#ifndef asm
#define asm __asm
#endif
```
causes Uncrustify to stop correcting the rest of the file. This may be due to parsing the "asm" keyword in the definition.
Work around this by wrapping the idiom in an *INDENT-OFF* comment wherever it appears.

[Backport 2.28] Workaround Uncrustify parsing of "asm"

---

library/aesni.c
library/bn_mul.h
library/padlock.c
library/sha256.c
library/sha512.c
programs/test/benchmark.c

Fixes #6845.
Backport: #6869
The following code:
```c
#ifndef asm
#define asm __asm
#endif
```
causes Uncrustify to stop correcting the rest of the file. This may be due to parsing the "asm" keyword in the definition.
Work around this by wrapping the idiom in an *INDENT-OFF* comment wherever it appears.

Workaround Uncrustify parsing of "asm"

---

include/mbedtls/bn_mul.h
scripts/code_style.py

Trivial backport of #6876.
Check the returncode of Uncrustify when fixing code style. This means that unparseable files cause checking or correction to fail.
The inline assembly defined in `bn_mul.h` confuses code style parsing, causing code style correction to fail. Disable code style correction for the whole section gated by `#if defined(MBEDTLS_HAVE_ASM)` to prevent this.

[Backport 2.28] Check for Uncrustify errors in `code_style.py`

---

library/bn_mul.h
scripts/code_style.py

Check the returncode of Uncrustify when fixing code style. This means that unparseable files cause checking or correction to fail.
The inline assembly defined in `bn_mul.h` confuses code style parsing, causing code style correction to fail. Disable code style correction for the whole section gated by `#if defined(MBEDTLS_HAVE_ASM)` to prevent this.
Backport 2.28: #6877

Check for Uncrustify errors in `code_style.py`

---

tests/suites/test_suite_psa_crypto.function

`mbedtls_test_psa_setup_key_derivation_wrap()` returns 1 for success, 0 for error, so the test here was wrong. Other uses of this function in the same file have the correct check (either `!` or `== 0`). This was causing tests using `derive_key_exercises()` to be marked as PASS even in [builds where other derive key tests fail](https://github.com/Mbed-TLS/mbedtls/issues/6839#issuecomment-1370855076) which made me notice.

Fix test function derive_key_exercise()

---

tests/suites/test_suite_psa_crypto.function

This is the 2.28 backport of #6873 - entirely trivial

[Backport 2.28] Fix test function derive_key_exercise()

---

include/mbedtls/check_config.h
include/mbedtls/mbedtls_config.h
tests/scripts/all.sh

This PR aims at adding the missing dependencies' checks for building the library without the BIGNUM_C dependency.
Resolves #6831

Document/test dependencies on ECP & Bignum

---

ChangeLog.d/fix-iar-warnings.txt
library/bignum.c

Backport 2.28: Fix iar warning bignum backport

---

include/psa/crypto_values.h

Trivial backport of https://github.com/Mbed-TLS/mbedtls/pull/6878

Backport 2.28: Don't restyle some PSA macros

---

include/psa/crypto_values.h

Some preprocessor macro definitions must have a specific expansion so that the same macro name can be defined in different products. The definition of having the same expansion (per the C language specification) means the same sequence of tokens, and also the same absence/presence of spacing between tokens. Don't restyle those macros (it would add a space between casts and their value, since https://github.com/Mbed-TLS/mbedtls/pull/6836). Fixes https://github.com/Mbed-TLS/mbedtls/issues/6875.

Don't restyle some PSA macros

---

ChangeLog.d/fix_build_for_directory_names_containing_spaces.txt
scripts/generate_errors.pl

Backport 2.28: Make generate_errors.pl handle directory names containing spaces when opening files

---

ChangeLog.d/fix_build_for_directory_names_containing_spaces.txt
scripts/generate_errors.pl

Fixes #6879 
Modify generate_errors.pl such that it can now handle opening files where the file path includes a directory name containing spaces.
Fix provided by
@tom-cosgrove-arm in aforementioned issue.
2.28 backport: #6894 

Make generate_errors.pl handle directory names containing spaces when opening files

---

tests/compat-in-docker.sh
tests/compat.sh
tests/scripts/all.sh
tests/scripts/basic-build-test.sh
tests/ssl-opt-in-docker.sh
tests/ssl-opt.sh

These variables were both used to select the default version of OpenSSL to use for tests:
- when running compat.sh or ssl-opt.sh directly, OPENSSL_CMD was used;
- when running all.sh, OPENSSL was used.
This caused surprising situations if you had one but not the other set in your environment. For example I used to have OPENSSL_CMD set but not OPENSSL, so ssl-opt.sh was failing in some all.sh components but passing when I ran it manually in the same configuration and build, a rather unpleasant experience.
The natural name would be OPENSSL, and that's what set in the Docker images used by the CI. However back in the 1.3.x days, that name was already used in library/Makefile, so it was preferable to pick a different one, hence OPENSSL_CMD. However the build system has not been using this …

Use OPENSSL everywhere, not OPENSSL_CMD

---

tests/compat-in-docker.sh
tests/compat.sh
tests/scripts/all.sh
tests/scripts/basic-build-test.sh
tests/ssl-opt-in-docker.sh
tests/ssl-opt.sh

This is the 2.28 backport of #6823. It's almost entirely trivial except:
- the invocations with `OPENSSL=$OPENSSL_LEGACY` are different in 2.28 because more old things are supported there;
- there's one more of them.

[Backport 2.28] Use OPENSSL everywhere, not OPENSSL_CMD

---

ChangeLog.d/workaround_gnutls_anti_replay_fail.txt
library/ssl_tls13_client.c
programs/ssl/ssl_client2.c
tests/opt-testcases/tls13-misc.sh
tests/ssl-opt.sh

fix #6623 
anti_replay_check of GnuTLS check the ticket ages of client and server.
The restriction is in https://gitlab.com/gnutls/gnutls/-/blob/master/lib/tls13/anti_replay.c#L150
**TIME RESOLUTION OF TICKET AGE**
The time precision of ticket_age is milliseconds(RFC 8446). But our precision is senconds, we caculate
ticket age with (mbedtls_time( NULL ) - ticket_recived)*1000 .
If the ticket is sent/received near the end of a second and client send ticket at the beggining of
next second, ticket age of client is 1000 ms, but ticket age of server is less than it. As a result,
it offends the anit replay ruler.
Workaround solution: Add 1 second to ticket_received and do reconnect 1 second later.
The issue can be reproduce and verified with #6712 . That PR include test script and test result. …

TLS 1.3: EarlyData: Workaround anti replay fail from GnuTLS

---

tests/scripts/check_files.py

Reject invalid UTF-8 and weird characters in text files
Reject "weird" characters in text files, especially control characters that might be escape sequences or that might cause other text to appear garbled (as in https://trojansource.codes/).
Also reject byte sequences that aren't valid UTF-8.
One thing this doesn't do is to reject misleading Python identifiers (e.g. `Α` is not `A`). But for that Pylint checks identifier names and we have it configured to accept only ASCII alphanumerics.

Reject bad characters in source code

---

tests/scripts/check_files.py

Quasi-trivial backport of https://github.com/Mbed-TLS/mbedtls/pull/6884
Difference with the original:
* "Treat more *.bin files as binary" — there wasn't a `pkcs7_data.*\.bin` entry before. We do need to catch `tests/data_files/base64/def_b64_ff.bin` even in 2.28.

Backport 2.28: Reject bad characters in source code

---

library/psa_crypto_its.h

We're including psa/crypto_values.h, which defines the necessary error codes. Remove redundant definitions, which hurt because they need to be styled in exactly the same way (same presence/absence of spaces between tokens).
This completes the fix of https://github.com/Mbed-TLS/mbedtls/issues/6875, following https://github.com/Mbed-TLS/mbedtls/pull/6897 which [broke the restyled code](https://jenkins-mbedtls.oss.arm.com/job/mbed-tls-nightly-tests/3148/).

Backport 2.28: Remove redundant error code definitions

---

library/psa_crypto_its.h

We're including psa/crypto_values.h, which defines the necessary error codes. Remove redundant definitions, which hurt because they need to be styled in exactly the same way (same presence/absence of spaces between tokens).
This completes the fix of https://github.com/Mbed-TLS/mbedtls/issues/6875, following https://github.com/Mbed-TLS/mbedtls/pull/6878 which [broke the restyled code](https://jenkins-mbedtls.oss.arm.com/job/mbed-tls-nightly-tests/3147/).

Remove redundant error code definitions

---

tests/compat.sh
tests/ssl-opt.sh

Backport 2.28: Have compat.sh and ssl-opt.sh not return success for > 255 errors

---

tests/compat.sh
tests/ssl-opt.sh

Have compat.sh and ssl-opt.sh not return success for > 255 errors

---

scripts/code_style.py

Backport 2.28: code_style.py: Support restyling only the specified files

---

ChangeLog.d/fix-rsaalt-test-guards.txt
tests/scripts/all.sh
tests/suites/test_suite_x509write.function

Fix RSA ALT test guards

---

ChangeLog.d/fix-rsaalt-test-guards.txt
tests/scripts/all.sh
tests/suites/test_suite_x509write.function

Backport 2.28 - Fix RSA ALT test guards

---

include/mbedtls/build_info.h
include/mbedtls/mbedtls_config.h
library/aesni.c
library/alignment.h
library/bn_mul.h
library/common.h
library/constant_time.c
library/padlock.c
library/sha256.c
library/sha512.c
tests/suites/test_suite_alignment.function
tests/suites/test_suite_constant_time.data
tests/suites/test_suite_constant_time.function

Follow-up to #6666 - improve efficiency of our constant time memcmp and memcpy implementations.

Improve efficiency of some constant time functions

---

docs/getting_started.md

Update some out-of-date references to Mbed Crypto in the getting started doc. Fix a few other errors and out-of-date bits. Fix line widths.
Fixes #3232

Update the getting-started doc

---

docs/architecture/psa-migration/outcome-analysis.sh
docs/architecture/psa-migration/strategy.md
tests/Makefile
tests/scripts/all.sh
tests/scripts/analyze_outcomes.py

This creates / updates the infrastructure for testing work on driver-only ECDSA. 
Context: see https://github.com/Mbed-TLS/mbedtls/issues/6839. This is about the TL-ecdsa intermediate goal - not doing the work itself, just putting the test components in place. TL-ecdsa will be achieved when the `all.sh` component introduced here is complete (full config without undue exclusions, running `ssl-opt.sh` too) and has testing parity with its reference component (that is, the extra "ignore"s in `analyze_outcome.py` are removed).
Follow-ups: #6856 #6857 #6858 #6860 #6861 #6862

Driver-only ECDSA starter

---

library/bignum_mod.c
library/bignum_mod.h
library/bignum_mod_raw.c
library/bignum_mod_raw.h

bignum_mod.c
bignum_mod.h
bignum_mod_raw.c
bignum_mod_raw.h
test_suite_bignum_mod.function
Rename modulus input argument from m to N in above mentioned files.

Rename modulus input argument from m to N

---

library/bignum_mod_raw.h

Fix doxygen return parameter spelling

---

library/ecp.c
library/ecp_curves.c
library/pkparse.c

This PR is changing the behavior of `ecp_use_curve448()` and `ecp_use_curve25519()`. The Montgomery constants are no longer calculated on the fly and are simply provided as embedded constant. 
This is a a design requirement which fullfils #[6027](https://github.com/Mbed-TLS/mbedtls/issues/6027)

Bignum: hardcode montgomery moduli

---

tests/compat.sh

Trivial backport of https://github.com/Mbed-TLS/mbedtls/pull/6917

Backport 2.28: Fix the problem of printing "Terminated" in compat.sh under Ubuntu-22.04

---

scripts/mbedtls_dev/crypto_knowledge.py
tests/scripts/generate_psa_tests.py

Add type hints in 2 places, fixing errors in `check-python-files.sh`.

Fix check python errors

---

ChangeLog.d/fix_timing_alt.txt
library/Makefile
library/timing.c
tests/scripts/all.sh
tests/src/external_timing/external_timing_for_test.c
tests/src/external_timing/timing_alt.h

This caused trouble for users that were using the selftest feature along with an alternative timing implementation. They were forced to  provide their own version of a selftest. Since it was not mentioned in the define description, it should not be required, and is provided roughly as it was before breaking changes in 77daaad198 were introduced.
Bonus change: the FAIL macro no longer uses a field that exists only without `MBEDTLS_TIMING_ALT`.
Fixes #6923 
**backport not required**

[2.28] Enable the timing.c selftest with MBEDTLS_TIMING_ALT

---

scripts/mbedtls_dev/crypto_knowledge.py
tests/scripts/generate_psa_tests.py

Very partial backport of https://github.com/Mbed-TLS/mbedtls/pull/6802: 2.28 doesn't have any of the stuff that was partially missing in development, so these are just minor improvements to scripts.

Backport 2.28: Add metadata tests for CCM* and TLS1.2-ECJPAKE-to-PMS

---

tests/scripts/check_names.py
tests/scripts/list_internal_identifiers.py

`check_names.py` allows for specific files to be excluded, either from specific groups of checks or from everything. Excluding a header file containing identifiers (e.g. to avoid enforcement of naming rules in `3rdparty/`) will stop the checks being run on it. However, as the functions defined in that header file are still compiled alongside Mbed TLS, they will be present in the output of `nm` when symbols are parsed. As a result, the `All symbols in header` check will fail.
This PR fixes this by parsing the identifiers from excluded header files and storing them separately. Checks are not performed on these identifiers (as intended), but they are compared against the output of `nm`. This way, excluding a header file from naming checks will not trigger the aforementioned failure.

check_names.py: Compare identifiers in excluded files against symbols parsed by nm

---

tests/scripts/check_names.py
tests/scripts/list_internal_identifiers.py

`check_names.py` allows for specific files to be excluded, either from specific groups of checks or from everything. Excluding a header file containing identifiers (e.g. to avoid enforcement of naming rules in `3rdparty/`) will stop the checks being run on it. However, as the functions defined in that header file are still compiled alongside Mbed TLS, they will be present in the output of `nm` when symbols are parsed. As a result, the `All symbols in header` check will fail.
This PR fixes this by parsing the identifiers from excluded header files and storing them separately. Checks are not performed on these identifiers (as intended), but they are compared against the output of `nm`. This way, excluding a header file from naming checks will not trigger the aforementioned failure.

[Backport 2.28] check_names.py: Compare identifiers in excluded files against symbols parsed by nm

---

library/constant_time.c

Follow-up to the discussion here: https://github.com/Mbed-TLS/mbedtls/pull/6832#discussion_r1066969858
Adding volatile prevents the compile from optimising the assembly line out, without the overhead of making `diff` volatile as suggested in that discussion. From a usability point of view, it also seems cleaner that `mbedtls_get_unaligned_volatile_uint32()` does the right thing without requiring the caller to do anything special with volatile.

Inhibit compiler from optimising out const-time asm

---

.uncrustify.cfg
scripts/code_style.py

[Backport 2.28] Improvements to code style script

---

ChangeLog.d/conditionalize-mbedtls_mpi_sub_abs-memcpy.txt
library/bignum.c

In some contexts, the output pointer may equal the first input pointer, in which case copying is not only superfluous but results in "Source and destination overlap in memcpy" errors from Valgrind (as I observed in the context of ecp_double_jac) and a diagnostic message from TrustInSoft Analyzer (as Pascal Cuoq reported in the context of other ECP functions called by cert-app with a suitable certificate).
I will be happy to supply a corresponding LTS PR in due course, particularly given that I'm using that branch myself.
(Split from #6930.)

mbedtls_mpi_sub_abs: Skip memcpy when redundant (#6701).

---

ChangeLog.d/conditionalize-mbedtls_mpi_sub_abs-memcpy.txt
library/bignum.c

In some contexts, the output pointer may equal the first input pointer, in which case copying is not only superfluous but results in "Source and destination overlap in memcpy" errors from Valgrind (as I observed in the context of ecp_double_jac) and a diagnostic message from TrustInSoft Analyzer (as Pascal Cuoq reported in the context of other ECP functions called by cert-app with a suitable certificate).
Signed-off-by: Aaron M. Ucko <ucko@ncbi.nlm.nih.gov>
Backport of #6942.

[Backport 2.28] mbedtls_mpi_sub_abs: Skip memcpy when redundant (#6701).

---

library/bignum_core.h
library/bignum_mod.h

Fix typos in doxygen commands in new bignum modules

---

.travis.yml
tests/compat.sh
tests/scripts/translate_ciphers.py

Fix: #6651
This PR is not finished yet, just to back up all the modifications. We need further dicussion to consider if we should put more effort on this PR since we may rewrite `compat.sh` in Python.

compat.sh: report and filter cipher suite names consistently

---

tests/scripts/check_files.py

Currently, `check_files.py` enforces that Mbed TLS uses only valid UTF-8 and only other explicitly allowed characters. This PR adds three characters from the Box Drawings range to the list of allowed characters:
- `u\2500`: “─”
- `u\2514`: “└”
- `u\251C`: “├”
These characters are used to construct file trees in Markdown, like the one below. These can serve as useful visual aids.
```
├── src
│   ├── dir1
│   │   ├── file1.c
│   ├── file2.c
│   ├── file3.c
│   ├── file4.c
├── include
│   ├── head1.h
│   ├── head2.h
│   ├── head3.h
├── Makefile
└── .gitignore
```
This PR also changes the wording of how the allowed characters are explained using inclusive terminology.

[Backport 2.28] check_files.py: Allow specific Box Drawings characters to be used

---

tests/scripts/check_files.py

Currently, `check_files.py` enforces that Mbed TLS uses only valid UTF-8 and only other explicitly allowed characters. This PR adds three characters from the Box Drawings range to the list of allowed characters:
- `u\2500`: “─”
- `u\2514`: “└”
- `u\251C`: “├”
These characters are used to construct file trees in Markdown, like the one below. These can serve as useful visual aids.
```
├── src
│   ├── dir1
│   │   ├── file1.c
│   ├── file2.c
│   ├── file3.c
│   ├── file4.c
├── include
│   ├── head1.h
│   ├── head2.h
│   ├── head3.h
├── Makefile
└── .gitignore
```
This PR also changes the wording of how the allowed characters are explained using inclusive terminology.

check_files.py: Allow specific Box Drawing characters to be used

---

include/mbedtls/cipher.h
include/mbedtls/des.h
include/mbedtls/mbedtls_config.h

Ensure DES warnings also refer to 3DES

Improve warnings for DES/3DES

---

include/mbedtls/cipher.h
include/mbedtls/config.h
include/mbedtls/des.h

Backport 2.28: Improve warnings for DES/3DES

---

ChangeLog.d/fix-example-programs-no-args.txt
programs/hash/generic_sum.c
programs/pkey/dh_genprime.c
programs/pkey/gen_key.c
programs/pkey/key_app.c
programs/pkey/key_app_writer.c
programs/ssl/ssl_client2.c
programs/ssl/ssl_mail_client.c
programs/ssl/ssl_server2.c
programs/test/query_compile_time_config.c
programs/util/pem2der.c
programs/x509/cert_app.c
programs/x509/cert_req.c
programs/x509/cert_write.c
programs/x509/crl_app.c
programs/x509/req_app.c

Fixes issues #1120 and #6700.
Numerous example programs contain the following:
```
if (argc == 0) {
goto USAGE;
}
// later in program
p = argv[1];
```
If a program is called from the shell then`argc = 1`, so the program will not go to USAGE due to the check. The access to `argv[1]` is accessing undefined memory. This PR changes the check to `if (argc < 2)`.

Fix incorrect dispatch to USAGE in example programs, which causes uninitialized memory to be used

---

ChangeLog.d/fix-example-programs-no-args.txt
programs/hash/generic_sum.c
programs/pkey/dh_genprime.c
programs/pkey/gen_key.c
programs/pkey/key_app.c
programs/pkey/key_app_writer.c
programs/ssl/ssl_client2.c
programs/ssl/ssl_mail_client.c
programs/ssl/ssl_server2.c
programs/test/query_compile_time_config.c
programs/util/pem2der.c
programs/x509/cert_app.c
programs/x509/cert_req.c
programs/x509/cert_write.c
programs/x509/crl_app.c
programs/x509/req_app.c

Fixes issues #1120 and #6700.
Numerous example programs contain the following:
```
if (argc == 0) {
goto USAGE;
}
// later in program
p = argv[1];
```
If a program is called from the shell then`argc = 1`, so the program will not go to USAGE due to the check. The access to `argv[1]` is accessing undefined memory. This PR changes the check to `if (argc < 2)`.

[Backport 2.28] Fix incorrect dispatch to USAGE in example programs, which causes uninitialized memory to be used

---

programs/ssl/ssl_server2.c

Would have used `mbedtls_put_unaligned_uint32()`, but `alignment.h` is in `library/`.

Don't use cast-assignment in ssl_server.c

---

ChangeLog.d/c-build-helper-hostcc.txt
scripts/mbedtls_dev/c_build_helper.py

This PR contains 2 improvements:
- Refactor `c_build_helper` to use a helper function for compilation. This allows a more flexible usage in other scripts that need to compile C code.
- Respect `$HOSTCC` for compilation if it is set, before falling back on `$CC`, allowing generated files to be generated when `$CC` is set for cross compiling.

Minor improvements to `c_build_helper.py`

---

tests/scripts/all.sh

test_m32_xxx tests are x86 specific, but the support function only identifies a 64-bit system. So the tests will be run on arm64 host and cause a test failure. This change restricts those tests to amd64/x86_64 only.

all.sh: test_m32_xx is not supported on arm64 host

---

tests/scripts/all.sh

This PR is a backport of #7003  to branch mbedtls-2.28.

Backport 2.28: all.sh: test_m32_xx is not supported on arm64 host 

---

CONTRIBUTING.md
ChangeLog.d/coding-style.txt

Minor documentation updates to account for the coding style change.
* Tweak `CONTRIBUTING.md`.
* Changelog entry, because it affects some consumers of the library (not users, but contributors and maintainers of patches).

Switch to the new coding style: documentation

---

CONTRIBUTING.md
ChangeLog.d/coding-style.txt

Trivial backport of https://github.com/Mbed-TLS/mbedtls/pull/6925

Backport 2.28: Switch to the new coding style: documentation

---

tests/compat.sh

Backport 2.28: compat.sh: remove VERIFY and duplicate test cases for PSK

---

ChangeLog.d/pk_ext-pss_options-public.txt
include/mbedtls/pk.h

This makes it possible to verify RSA PSS signatures with the pk module, which was inadvertently broken since Mbed TLS 3.0. Fixes #7040.

Make the fields of mbedtls_pk_rsassa_pss_options public

---

library/x509_crt.c

The lstrlenW() function isn't available to UWP apps, and isn't necessary, since when given -1, `WideCharToMultiByte()` will process the terminating null character itself (and the length returned by the function includes this character).
Resolves #2994

Don't use lstrlenW() on Windows

---

library/psa_crypto_driver_wrappers.c

Signed-off-by: Sergey <sergio_nsk@yahoo.de>
Backported https://github.com/Mbed-TLS/mbedtls/pull/7085
If the macro `MBEDTLS_PSA_BUILTIN_CIPHER` is defined, there are 2 sequential `return` statements:
```c
return status;
#endif /* MBEDTLS_PSA_BUILTIN_CIPHER */
return PSA_ERROR_NOT_SUPPORTED;
```
The second `return` is unreachable and should be enclosed in `#else` block.

Backport 2.28: Fix unreachable code compiler warning in psa_crypto_driver_wrappers.c

---

scripts/data_files/driver_templates/psa_crypto_driver_wrappers.c.jinja

Signed-off-by: Sergey <sergio_nsk@yahoo.de>
If the macro `MBEDTLS_PSA_BUILTIN_CIPHER` is defined, there are 2 sequential `return` statements:
```c
return(( status );
#endif /* MBEDTLS_PSA_BUILTIN_CIPHER */
return( PSA_ERROR_NOT_SUPPORTED );
```
The second `return` is unreachable and should be enclosed in `#else` block.

Fix unreachable code compiler warning in psa_crypto_driver_wrappers.c

---

tests/include/test/macros.h
tests/suites/test_suite_md.data
tests/suites/test_suite_md.function

This is the 2.28 backport of #7046.
It was mostly trivial except:
1. The first commit had a lot of contextual differences in the data file due SHA-224 and SHA-384 dependencies being handled differently in 2.28. Also, 2.28 still has some hashes (MD2, MD4) that were removed in 3.0. What I did is I re-created the changes to the data file from scratch, as it was just a big search-and-replace, and only cherry-picked the changes to the function file.
2. There were also a few contextual differences in the function file due to the fact that 2.28 doesn't have `info_from_ctx()`.

[Backport] Clean up MD tests

---

library/ssl_misc.h
library/ssl_tls13_keys.c

Fix sub-issue for: #6675 
This PR only fixes one issue listed in #6675.

TLS 1.3: Key Generation: Change tls13_early_secrets to local variable

---

README.md
library/ctr_drbg.c
library/pk.c
library/pk_wrap.c
library/psa_crypto_rsa.c
library/psa_crypto_se.c
library/ssl_msg.c
programs/test/selftest.c
tests/suites/test_suite_pk.function
tests/suites/test_suite_psa_crypto.function

Document that SIZE_MAX >= INT_MAX and UINT_MAX; remove checks for this in the library.
Some of the checks where guards are removed are redundant where SIZE_MAX == UINT_MAX - I've removed the guards anyway on the basis that the compiler should know this and optimise them out anyway.
Added checks to selftest.c (plus a couple of extras as per `README.md`).
Fixes #3577

Assume SIZE_MAX >= INT_MAX, UINT_MAX

---

ChangeLog.d/fix-iar-warnings.txt
library/bignum.c

IAR was warning that conditional execution could bypass initialisation of variables, although those same variables were not used uninitialised. This is the forward port of #6929

Fix IAR Warnings

---

ChangeLog.d/fix-iar-warnings.txt
library/bignum.c
library/ecp.c

IAR was warning that conditional execution could bypass initialisation of variables, although those same variables were not used uninitialised, however this is a quick fix to keep IAR quiet.
This will need forward porting to development once it has been checked to be ok (I cannot run IAR here)

Backport 2.28: Fix IAR warnings

---

library/x509_crt.c

The lstrlenW() function isn't available to UWP apps, and isn't necessary, since when given -1, WideCharToMultiByte() will process the terminating null character itself (and the length returned by the function includes this character).

Backport 2.28: Don't use lstrlenW() on Windows

---

scripts/code_style.py

This PR is a backport of https://github.com/Mbed-TLS/mbedtls/pull/7045 to branch mbedtls-2.28.

Backport 2.28: code_style.py: Apply exclusions when restyling a list of files

---

tests/suites/test_suite_constant_time.function

Fix a warning with GCC 12 about variable being used uninitialised which has been annoying me greatlyof late. Only GCC finds this, Clang does not.

Fix warning with GCC 12

---

ChangeLog.d/fix-oid-to-string-bugs.txt
library/oid.c
tests/suites/test_suite_oid.data
tests/suites/test_suite_oid.function
tests/suites/test_suite_x509parse.data

Fix 2 issues in the OID-to-string function `mbedtls_oid_get_numeric_string()`:
1. Subtleties in the specification meant that we were not dealing with the first 2 subidentifiers of the OID properly. For example the OID `2.40.0.25` was converted to the string `"3.0.0.25"`.
2. The function accepted overlong encodings of subidentifiers, which are disallowed by X.690/BER. Reject these.

Fix bugs in OID to string conversion

---

ChangeLog.d/fix-oid-to-string-bugs.txt
library/oid.c
tests/suites/test_suite_oid.data
tests/suites/test_suite_oid.function
tests/suites/test_suite_x509parse.data

[Backport 2.28] Fix bugs in OID to string conversion

---

library/ssl_client.c
library/ssl_misc.h
library/ssl_msg.c
library/ssl_tls.c
library/ssl_tls12_client.c
library/ssl_tls12_server.c
library/ssl_tls13_client.c
library/ssl_tls13_generic.c
library/ssl_tls13_server.c

Historical context: back in the Old Days, most hash functions (`mbedtls_shaxxx_yyy()`) used to return `void`, because the software implementation couldn't fail. Then we made some of them return `int` because when an `_ALT` implementation is used, the hardware might fail at any time and must be able to return an error. However, the change was only partially done in TLS, in that lots of functions that deal with hashes were not checking for error, or when checking (in the `USE_PSA` path), not propagating the error, because they were returning `void` themselves. In addition, on some error paths, some temporary contexts were not properly released.
This PR hopefully fixes all of that.
This is preparation work for #6989 - the functions in MD produce a warning when their return value is not …

Handle errors from hash functions in TLS code

---

ChangeLog.d/mpi-window-perf
include/mbedtls/bignum.h
include/mbedtls/config.h

Backport of https://github.com/Mbed-TLS/mbedtls/pull/7169.
As tested in https://github.com/Mbed-TLS/mbedtls/issues/6790, after introducing side-channel counter-measures to bignum, the performance of RSA decryption in correlation to the MBEDTLS_ECP_WINDOW_SIZE has changed.
The default value of 2 has been chosen as it provides best or close-to-best results for tests on Cortex-M4 and Intel I-7.

[Backport 2.28] Reduce the default MBEDTLS_ECP_WINDOW_SIZE value to 2

---

include/psa/crypto.h
library/psa_crypto_core.h

The previous Clang 15 \retval fixes in #7098 were pushed before the Interruptible sign|verify hash changes were merged, and thus were not included in those fixes (see https://github.com/Mbed-TLS/mbedtls/pull/7098#issuecomment-1445976065).
Adding Clang 15 fixes for the interruptible sign|verify hash work.

Interruptible {sign|verify} hash - Pacify Clang 15

---

library/psa_crypto.c

Change name and document to ensure suitability only for "tags" is explicit. Add support for output size of zero in PSA_SUCCESS case.

Update psa_wipe_output_buffer() and change name to psa_wipe_tag_output_buffer()

---

tests/suites/test_suite_psa_crypto.function

Backport 2.28 - Fix test to check output length on PSA_SUCCESS only

---

tests/suites/test_suite_psa_crypto.function

Fix `asymmetric_encrypt ` in `test_suite_psa_crypto.function` so that it only expects a defined `output_length` if `psa_asymmetric_encrypt` returns `PSA_SUCCESS`. 
Signed-off-by: Oberon microsystems AG, Zürich

Fix test to check output length on PSA_SUCCESS only

---

.travis.yml
tests/compat.sh

Fix: https://github.com/Mbed-TLS/mbedtls/issues/1785
This PR add the ability in `compat.sh` to check if the under testing `openssl` program supports static ECDH (i.e. `ECDH_ECDSA`) key exchange methods. The cases for `TLS_ECDH_ECDSA_xxx` ciphersuites will be skipped if `openssl` doesn't support so.
This PR would like to cover all out of box failures of ssl-opt.sh and compat.sh on modern systems (e.g Ubuntu 18.04 and newer).

compat.sh: Skip static ECDH cases if unsupported in openssl

---

.travis.yml
tests/compat.sh

This PR is a backport of https://github.com/Mbed-TLS/mbedtls/pull/7137 to branch mbedtls-2.28.
Because `compat.sh` has changed a lot from `development` branch, the backport isn't a simple cherry-pick. The commit history has been reorganized.

Backport 2.28: compat.sh: Skip static ECDH cases if unsupported in openssl

---

.travis.yml
include/mbedtls/check_config.h
include/mbedtls/mbedtls_config.h
library/CMakeLists.txt
library/Makefile
library/aes.c
library/aesce.c
library/aesce.h
tests/scripts/all.sh

fix #5387
Add aes with Armv8 crypto extension 

Add AES with armv8 crypto extension

---

include/psa/crypto.h
library/psa_crypto.c
library/psa_crypto_driver_wrappers.h
scripts/data_files/driver_templates/psa_crypto_driver_wrappers.c.jinja

Remove the driver entry points for `psa_{get|set}_max_ops()` as they were currently only calling internal implementations. There was no way to write a driver interface that would work within the current driver interface (without making another list of registered drivers).
Instead, switch over to just using a global variable in the PSA layer and move the internal setting into the various functions where the value needs to be set.
Drivers in the future can call `psa_get_max_ops()` and set their internal value accordingly, in the same way the internal implementation does.

Remove driver entry points for psa_{get|set}_max_ops()

---

library/alignment.h

Avoid redefining the MBEDTLS_BSWAPxx macros for compilers which support multiple options, such as armclang.
Fixes some of #7186

Fix macro redefinition warning from armclang

---

tests/suites/test_suite_psa_crypto.function

Improve the sign & verification tests and verification tests.
Add a check  to corrupt the original hash and check verification fails to normal verification, and add the normal Ops testing to sign & verify, as this is the only code path testing non-deterministic ECDSA.

Interruptible {sign|verify} hash verification test improvements

---

tests/suites/test_suite_psa_crypto.function

Add tests to check `{sign|verify}_complete()` will fail with `BAD_STATE` after a failing call to `{sign|verify}_start()`, to emulate a bad implementation that doesn't check its return values.
I was in the process of writing a separate test to test calling `{sign|verify}_start()` fails with `BAD_STATE` after a failing call to `{sign|verify}_start()`, but during this process this felt like more and more of a waste of time as its basically a complete duplicate of the current sign and verify failure tests (and I'm very conscious about adding new tests right now).
My reasoning is as follows: Calling `{sign|verify}_complete()` should not change the internal state in any way shape or form, if we are in a bad state. It should just report this fact and return, therefore it should not matter …

Interruptible {sign|verify} hash - Call complete() after start() failure.

---

include/mbedtls/check_config.h
include/mbedtls/mbedtls_config.h
library/sha256.c
library/sha512.c

Fix #5758 .
This PR changed the rule of CPU feature modifier cflags for building with hardware acceleration. The flags is checked in global header file and report error if they are not set in global `CFLAGS`. This commit suggests set the cflags per file with compiler extension( `#pragma GCC target` or target attributes ).
That is more readable to resolve with compiler extension than cflags of compiler command line. The cpu feature modifier is just near the code which needs them.
Script issue raised in [Mbed-TLS/mbedtls#5758](https://github.com/Mbed-TLS/mbedtls/issues/5758) can be resolved with this solution.
`illegal instruction` error was found in #6918 . When MBedTLS is build with optimization flag and `-march=armv8.2-a+sha3-crypto` which is requested by …

Replace CPU modifier check with file scope target cpu modifiers

---

tests/scripts/depends.py

`depends.py` now uses `config.py` to get the available configuration options as well as manipulate the config file.
Fixes https://github.com/Mbed-TLS/mbedtls/issues/6440.
[Backport here](https://github.com/Mbed-TLS/mbedtls/pull/7104)

Use `config.py` as a module in `depends.py`

---

tests/scripts/all.sh

Suppress a warning from armclang builds in all.sh. This allows all.sh to turn on -Werror for armclang builds.
Partial fix for #7186

Enable -Werror in all.sh for armclang

---

tests/scripts/all.sh

Backport of #7197  (the only relevant part is enabling -Werror)

Backport 2.28: enable -Werror for armclang

---

tests/suites/test_suite_psa_crypto_op_fail.function

Due to a misunderstanding about the purpose of this test, I had limited this to ECC keys only, however this defeats the purpose of the test, and left gaps in test coverage, which were later shown up by lcov.

Enable all keys for interruptible op fail tests

---

ChangeLog.d/psa-alt-headers.txt
include/mbedtls/build_info.h
include/mbedtls/mbedtls_config.h
include/psa/crypto.h
include/psa/crypto_types.h
programs/.gitignore
programs/Makefile
programs/test/CMakeLists.txt
programs/test/query_included_headers.c
tests/.gitignore
tests/Makefile
tests/include/alt-extra/psa/crypto.h
tests/scripts/all.sh

Allow alternative paths for the PSA headers that integrators may override (`psa/crypto_platform.h` and `psa/crypto_struct.h`). Fixes #7145.
Also move the implication `MBEDTLS_PSA_CRYPTO_C` ⇒ `MBEDTLS_PSA_CRYPTO_CLIENT` to `build_info.h` where it belongs, in partial fulfilment of https://github.com/Mbed-TLS/mbedtls/issues/7144.

Allow alternative names for overridable PSA headers

---

ChangeLog.d/platform-zeroization.txt
library/platform_util.c
tests/suites/test_suite_platform_util.data
tests/suites/test_suite_platform_util.function

Use `explicit_bzero`, `memset_s`, or `SecureZeroMemory` where provided.
Fixes #1584

Use platform-provided secure zeroization

---

library/platform_util.c

Enable explicit_bzero() on OpenBSD

---

tests/src/psa_exercise_key.c

The `mbedtls_test_psa_exported_key_sanity_check` required by `test_suite_psa_crypto_storage` expects a `size of 2 * keysize + 1` for all elliptic curve public keys except Montgomery type curves where the expected size is keysize. This PR adds another case for Edwards curves where the expected size is key size plus one extra bit.
Signed-off-by: Oberon microsystems AG, Zürich

Fix expected export length for Edwards curves in test suite.

---

library/ssl_misc.h
library/ssl_tls.c
library/x509write_crt.c

This is part 1 of #6989 - X.509 and TLS.
(Part 2 will address PEM and RSA (self-test) but those don't already depend on `MD_C` so they will want to auto-enable `MD_LIGHT`, which depends on #7120.)

Use MD (not low-level hash interface) in X.509 and TLS

---

include/mbedtls/mbedtls_config.h
include/mbedtls/pk.h
include/mbedtls/ssl.h
include/mbedtls/x509_crl.h
include/mbedtls/x509_crt.h
include/mbedtls/x509_csr.h

It isn't obvious that you need to call `psa_crypto_init()` in application code before starting a TLS 1.3 handshake, so document it.
Also document this on common functions for when `MBEDTLS_USE_PSA_CRYPTO` is enabled. (It's already mentioned in the documentation for `MBEDTLS_USE_PSA_CRYPTO` itself, but users who're writing the application code and didn't write the configuration might not think of looking there.) I do not try to be exhaustive, just the common non-obvious cases (basically anything that calls PK parsing, and SSL handshake setup).

Document the need to call psa_crypto_init for TLS 1.3

---

ChangeLog

Backport 2.28: Update ChangeLog to make "fix" explicit

---

ChangeLog.d/driver-only-ecdsa.txt
docs/use-psa-crypto.md
include/mbedtls/check_config.h
include/mbedtls/config_psa.h

This PR:
- fixes the issue found here: https://github.com/Mbed-TLS/mbedtls/pull/7117#discussion_r1131360315
- fixes a related issue that I noticed while looking at this
- adds a ChangeLog entry for the driver-only ECDSA work.

Driver-only ecdsa wrapup

---

ChangeLog.d/mbedtls_ssl_read_undefined_behavior.txt
library/ssl_msg.c
tests/suites/test_suite_ssl.function

Backport 2.28: Fix undefined behavior in ssl_read if buf parameter is NULL

---

ChangeLog.d/mbedtls_ssl_read_undefined_behavior.txt
library/ssl_msg.c
tests/suites/test_suite_ssl.function

Updated version of #5527 
- Adds a corresponding fix to `mbedtls_ssl_write`
- Adds tests
- Adds a sign-off to cover @gilles-peskine-arm 's suggestion
- Updated Changelog
Fixes #3076
Note - I've disabled the test for DTLS as it's not a no-op here. Presumably this is expected behaviour - please can a reviewer who understands DTLS better should check this.

Fix undefined behavior in ssl_read if buf parameter is NULL

---

tests/include/test/macros.h
tests/src/random.c

Minor cleanup - some test macros are just a duplicate of macros from the main library.

Remove duplicate test macros

---

tests/scripts/analyze_outcomes.py

Before this PR, `analyze_outcomes.py` was printing warning and error messages on stderr, while info messages were printed on stdout. This PR fixes this behavior and sends all the output to stderr.
Resolves #7140

Handle output consistently in analyze_outcomes.py

---

tests/scripts/all.sh

We are going to sperate the Arm Compiler docker image from the main docker images in CI: https://github.com/Mbed-TLS/mbedtls-test/pull/96. 
The CI depends on `all.sh --list-components` for list of available case on a specific platform. However, `build_armcc` is always listed no metter if there are Arm Compilers or not. That causes the CI generate a job which runs `build_armcc` on a platform that is not installed with the tools.
This PR add support functions for `build_armcc` case, so that it would not be listed if there is no Arm Compiler detected.

all.sh: Do not list unsupported cases

---

tests/scripts/all.sh

This PR is a backport of https://github.com/Mbed-TLS/mbedtls/pull/7163 to branch mbedtls-2.28.

Backport 2.28: all.sh: Do not list unsupported cases 

---

tests/scripts/all.sh
tests/ssl-opt.sh

This PR is the continuation of #7142 and aims at:
- enabling `ssl-opt.sh` both in `test_psa_crypto_config_reference_ecdh_use_psa()` and `test_psa_crypto_config_accel_ecdh_use_psa()`
- providing test coverage parity
Resolves #7148

driver-only ECDH: enable ssl-opt.sh with parity

---

.travis.yml
include/mbedtls/mbedtls_config.h
library/aesce.c
library/sha256.c
library/sha512.c

The library does not build out-of-the-box on Arm (the user needs to set compiler flags). This fixes it.
Fix #5758 
#6932 fixed Arm64 host build fail before #6895 merged.
Without `-march=armv8-a+crypto` , AESCE module still reports fail after #6895. This PR add similar pragmas to fix it.
Beside that, Travis CI is updated, for we have resolved conflict issue between SHA512 and AESCE. 

Add CPU modifier for AESCE

---

library/common.h
library/psa_crypto.c
library/psa_crypto_se.c
library/ssl_tls.c
library/ssl_tls12_server.c

Fixes #3693
Tested the following combinations of systems/compilers/compiler flags with assert ok/expected to fail:
OpenBSD gcc 4.2.1 assert_ok [-std=c99 [-pedantic]] -Wall -Wextra -Werror OK
OpenBSD gcc 4.2.1 assert_fails [-std=c99 [-pedantic]] -Wall -Wextra -Werror OK
clang 10.0.1 assert_ok [-std=c99 [-pedantic]] -Wall -Wextra -Werror OK
clang 10.0.1 assert_fails [-std=c99 [-pedantic]] -Wall -Wextra -Werror OK
Ubuntu gcc 12.0.1 assert_ok [-std=c99 [-pedantic]] -Wall -Wextra -Werror OK
Ubuntu gcc 12.0.1 assert_fails [-std=c99 [-pedantic]] -Wall -Wextra -Werror OK
Ubuntu clang 15.0.7 assert_ok [-std=c99 [-pedantic]] -Wall -Wextra -Werror OK
Ubuntu clang 15.0.7 assert_fails [-std=c99 [-pedantic]] -Wall -Wextra -Werror OK
macOS clang 14.0.0 assert_ok [-std=c99 [-pedantic]] -Wall -Wextra …

Implement and use MBEDTLS_STATIC_ASSERT()

---

include/mbedtls/check_config.h

Fixes #7234
Tested using the reproducer in the issue:
- fails to build without this fix on x86_64
- builds successfully with this fix on x86_64
- fails to build without this fix on aarch64
- builds successfully with this fix on aarch64
Simplest fix for an actual regression on non-aarch64; we can worry about tidy-up after release.
~~This is the “lowest impact fix” - it just moves the definition of `MBEDTLS_HAVE_ARM64` and then uses it in the `check_config.h` test.~~
~~The consequence on Armv8 builds is that, although to get AES CE on Armv8 you still need both `MBEDTLS_AESCE_C` and `MBEDTLS_HAVE_ASM`, the library will allow you to build with `MBEDTLS_AESCE_C` but not `MBEDTLS_HAVE_ASM`, and then just not use AES CE (which seems fair, because you clearly said "no asssembler" by disabling …

Don't insist on MBEDTLS_HAVE_ASM for MBEDTLS_AESCE_C on non-Arm64 systems

---

ChangeLog.d/changelog-6567-psa_key_derivation_abort-no-other_secret.txt

Changelog entry for a bug fixed in https://github.com/Mbed-TLS/mbedtls/pull/6567 that got lost in all the code for the new feature. The bug was originally reported [via a pull request](https://github.com/Mbed-TLS/mbedtls/pull/7125).

Add changelog entry for a bug in non-PAKE code fixed during PAKE work

---

ChangeLog.d/add-cache-remove-api.txt
include/mbedtls/ssl_cache.h
library/ssl_cache.c
programs/ssl/ssl_server2.c
tests/ssl-opt.sh

Partially Fix: https://github.com/Mbed-TLS/mbedtls/issues/6840
Add a new interface in `ssl_cache.c` to support the removal of cache entry be the session id. The test is provided as well.

ssl_cache: Add cache entry removal api

---

ChangeLog.d/fix-oid-to-string-bugs.txt
library/oid.c
tests/suites/test_suite_oid.data
tests/suites/test_suite_oid.function

[Backport 2.28] Fix segfault in mbedtls_oid_get_numeric_string

---

ChangeLog.d/fix-oid-to-string-bugs.txt
library/oid.c
tests/suites/test_suite_oid.data
tests/suites/test_suite_oid.function

When passed an empty OID, mbedtls_oid_get_numeric_string would read one byte from the zero-sized buffer and return an error code that depends on its value.  This is demonstrated by the test suite changes, which check that an OID with length zero and an invalid buffer pointer does not cause Mbed TLS to segfault.
Also check that second and subsequent subidentifiers are terminated, and add a test case for that.  Furthermore, stop relying on integer division by 40, use the same loop for both the first and subsequent subidentifiers, and add additional tests.
checklist for PR …

Fix segfault in mbedtls_oid_get_numeric_string

---

include/mbedtls/check_config.h
include/mbedtls/mbedtls_config.h
include/mbedtls/ssl.h
library/ssl_misc.h
library/ssl_tls.c
library/ssl_tls13_client.c
library/ssl_tls13_generic.c
library/ssl_tls13_server.c
scripts/config.py
tests/scripts/all.sh
tests/ssl-opt.sh

Add parsing for Record Size Limit extension in TLS 1.3

---

ChangeLog.d/armv8-aes.txt
include/mbedtls/mbedtls_config.h
library/aesce.c
library/aesce.h

Add missing changelog for #6918 and #6915; tidy-up use of terminology in source files.

Changelog and terminology tidy-up for AESCE

---

library/psa_crypto.c
tests/scripts/all.sh

Fix psa_key_derivation_output_key not being able to derive ECC keys without MBEDTLS_BUILTIN ECC key types enabled.
The PSA crypto drivers can generate these keys without requiring the builtin key types.

psa_crypto: Fix psa_key_derivation_output_key ECC without builtin keys

---

include/mbedtls/check_config.h
include/mbedtls/config_psa.h
tests/scripts/all.sh

This PR addresses issue #7281 by re-enabling EC JPAKE key exchanges and getting test parity in driver coverage analysis.
Depends on #7299
Resolves #7281

Driver only EC JPAKE: re-enable the EC J-PAKE key exchange and get test parity

---

library/common.h
library/psa_crypto.c
library/psa_crypto_se.c

Backport 2.28: Implement and use MBEDTLS_STATIC_ASSERT()

---

tests/scripts/analyze_outcomes.py

The goal of this PR is to improve the behavior of `analyze_outcomes.py` script.
The idea is that:
- if necessary (i.e, the output file does not exist), it can run the required tests before doing the coverage analysis. This it reduces user's interactions from 2 to 1
- At the same time it does not affect previous behavior: if the output file already exists then it just run the analysis without re-executing the tests
This script has no associated issue.

Improve analyze_outcomes.py script

---

tests/.gitignore

ignore `*.o` under `tests/src/test_helpers`
Small fix for #6500

fix: ignore *.o under tests/src/test_helpers

---

docs/architecture/psa-migration/psa-limitations.md
docs/use-psa-crypto.md
include/mbedtls/check_config.h
include/mbedtls/mbedtls_config.h

Resolve #7273.
Most of the updates had been done as part of #7330. I just update the documentation of `USE_PSA` a bit, then addressed minor leftover comments from #7330.

Ecc doc update

---

tests/.gitignore

ignore `*.o` under `tests/src/test_helpers`
Small fix for #6500

Backport 2.28: fix: ignore *.o under tests/src/test_helpers

---

include/mbedtls/timing.h
library/timing.c
tests/suites/test_suite_timing.function

Backport of #7385 
The ABI check failure is because the type of a field has changed (but its size remains the same). Since the only useful thing a user could do with the field is cast it to `struct timeval` (or WIndows equivalent), and its not supposed to be accessed by the user, this seems reasonable.
Alternatives AFAICT:
- use non-portable compiler attributes to align without changing the type
- copy the struct when using it to ensure alignment
- accept the nominal ABI break

Backport 2.28 - Timing alignment

---

include/mbedtls/timing.h
tests/suites/test_suite_timing.function

Fix #5633 cast alignment warning in timing.c.

Fix cast alignment warning in timing.c

---

tests/suites/test_suite_pkcs7.function

While working on support for parsing `SubjectKeyId` and `AuthorityKeyId` x509 V3 extensions I encountered a test failure in `test_suite_pkcs7` (configuration with enabled `MBEDTLS_MEMORY_BUFFER_ALLOC_C` and `MBEDTLS_PLATFORM_MEMORY`).
The following allocation is failing:
https://github.com/Mbed-TLS/mbedtls/blob/development/tests/suites/test_suite_pkcs7.function#L102-L106
This PR fixes memory allocation in test as `ASSERT_ALLOC` is incorrectly used. 

Fix memory allocations in pkcs7_verify test

---

library/pk_wrap.c
library/pkparse.c
tests/suites/test_suite_pkparse.function

Instead of using the legacy `mbedtls_ecp_mul()` function which makes use of ECP's math, this commit adds a new function named `pk_derive_public_key()` which implements the same behavior using PSA functions.
The flow is simple:
- import the private key into PSA
- export its public part
Depends on #7391
Resolves #7388

PK: use PSA to complete public key when USE_PSA is enabled

---

tests/include/test/ssl_helpers.h
tests/src/test_helpers/ssl_helpers.c
tests/suites/test_suite_ssl.function

Fix #7285
minor follow-up PR of #6500

6500 follow-up: enhancements to the new ssl_helpers test module

---

tests/include/test/ssl_helpers.h
tests/src/test_helpers/ssl_helpers.c
tests/suites/test_suite_ssl.function

Backport of #7287 
Since there are some differences between `development` and `mbedtls-2.28`. The backport is not identical with original PR.

Backport 2.28: 6500 follow-up: enhancements to the new ssl_helpers test module #7287

---

ChangeLog.d/add-missing-md-includes.txt
include/mbedtls/ssl.h
programs/pkey/dh_client.c
programs/pkey/dh_server.c
programs/pkey/pk_sign.c
programs/pkey/pk_verify.c
programs/pkey/rsa_sign.c
programs/pkey/rsa_sign_pss.c
programs/pkey/rsa_verify.c
programs/pkey/rsa_verify_pss.c
programs/psa/key_ladder_demo.c
programs/x509/cert_req.c
programs/x509/cert_write.c

After https://github.com/Mbed-TLS/mbedtls/commit/93302422fd146a7520ba3cdac51523dc62cdbe71 there are some guards that render programs useless, since there's no md.h include to load the required symbols.

Add missing md.h includes

---

library/ecp.c

Old link doesn't work any more, update it to one
new link to refer version 2
It will be one simple update.

Update SEC1 link in ecp.c

---

scripts/mbedtls_dev/bignum_common.py
scripts/mbedtls_dev/ecp.py
tests/suites/test_suite_ecp.function

Resolves #7306 .
This patch replaces the test functions for the following curves:
- MBEDTLS_ECP_DP_SECP192R1
- MBEDTLS_ECP_DP_SECP224R1
- MBEDTLS_ECP_DP_BP256R1
- MBEDTLS_ECP_DP_BP512R1
- MBEDTLS_ECP_DP_BP384R1
Instead of invoking a functionally similar curve specific method, 
`ecp_mod_pXXX_raw(char *input_N, char *input_X, char *result)` ,
the new generic implementation is accepting a curve_id, 
`
ecp_mod_p_generic_raw(int curve_id, char *input_N, char *input_X, char *result)` 
which is defined in the [ecp interface](https://github.com/Mbed-TLS/mbedtls/blob/development/include/mbedtls/ecp.h#L66-L76).
Then the curve specific parameters are switch-gated, greatly simplifying the test code.

ecp: Unify test cases

---

tests/suites/test_suite_alignment.function

Improve alignment tests, which fixes big-endian failures.
Fixes #7428

Test fixes for big-endian

---

BRANCHES.md

Backport of https://github.com/Mbed-TLS/mbedtls/pull/7383.
Users can get more value out of our LTS releases and plan transition between versions better if the documentation is more clear about the lifetime of LTS branches.

[Backport 2.28] Clarify LTS lifetime

---

BRANCHES.md

Users can get more value out of our LTS releases and plan transition between versions better if the documentation is more clear about the lifetime of LTS branches.

Clarify LTS lifetime

---

tests/scripts/all.sh
tests/scripts/analyze_outcomes.py
tests/src/psa_exercise_key.c

This PR adds a testing framework for driver's coverage analysis with:
- accelerated EC algs
- disabled ECP & ECP_LIGHT
~Depends on #7410~
Resolves #7404

driver-only: ECP.PSA starter

---

docs/architecture/psa-migration/syms.sh
tests/scripts/all.sh

This is the 3rd step of #7460
Resolves #7460 (partially)
~Requires #7463~

Check remaning dependencies on ECP in PK module

---

library/ecp_invasive.h

The prototype of function mbedtls_ecp_gen_privkey_mx() doesn't allign with the implementation and the comments.
Update it to align with exist comments.

Update gen_prvkey_mx paras to align with comments and c code

---

library/pk.c
library/pk_wrap.c
library/pk_wrap.h

This PR addresses the 2nd point of #7460 
Resolves #7460

Pass pk_context pointer to PK wrappers instead of void pointer

---

library/ecp_curves.c

The function does two passes on the reduction and both of those are the same letter to letter. Rolling them in a loop should have negligible performance impact, but makes the code size smaller and maintenance more efficient. This latter will make upcoming refactoring more efficient as well.
Resolve #7261

Roll up the loop in ecp_mod_koblitz()

---

library/bignum_core.c
library/bignum_core.h
tests/suites/test_suite_bignum_core.function
tests/suites/test_suite_bignum_core.misc.data

For clang and gcc, this saves a few instructions (with gcc -Os on aarch64, the size of libmbedcrypto is reduced by 88b). It also covers a test gap (this function was not directly tested before). Performance is not very different according to programs/test/benchmark.

clz size/perf optimisation

---

library/ecdh.c
library/ecdsa.c
library/ecp.c

The links of SEC1 is out-dated, update them to version 2.
Some RFC missed the links, add them.

Update links to references in bignum

---

library/ecdh.c
library/ecdsa.c
library/ecp.c

This is a backport from development, see #7429 and #7418
The links of SEC1 is out-dated, update them to version 2.
Some RFC missed the links, add them.

Backport 2.28: Update links of references in bignum code

---

include/mbedtls/check_config.h
include/mbedtls/mbedtls_config.h
library/aesce.c
library/aesce.h

Fixes #6920 
This PR is enable MSVC support for AESCE module. 
The code is verified under below condition.
- Build with VS2022 and `platformtoolsetversion=v143`
- With VS2022, platformtoolsetversion=v141 build fail. `arm_neon.h` reports ARM64 not supported
- Test on Windows 10 with `selftest` 
> NOTE:  Build command `msbuild /nodeReuse:false /t:Rebuild /p:Configuration=Debug,Platform=ARM64,PlatformToolset=v143  "mbedTLS.sln"`

Add msvc support for AESCE

---

CONTRIBUTING.md

This is a companion to https://github.com/Mbed-TLS/mbedtls-docs/pull/93 which needs to be merged first.

Add link to review guideline fro contributors

---

ChangeLog.d/mbedtls_ecdsa_can_do-unconditional-define.txt
library/ecdsa.c

When ECDSA_SIGN_ALT but not ECDSA_VERIFY_ALT, mbedtls_ecdsa_can_do was not being defined causing mbedtls_ecdsa_verify_restartable to always fail
closes #7498
This will support ATECC608 integration for signing but not verification.

Bug Fix: mbedtls_ecdsa_verify_restartable fails with ECDSA_SIGN_ALT

---

library/bignum_core.c
library/bignum_core.h

Fix VS2022 build error

---

tests/suites/test_suite_platform.data
tests/suites/test_suite_platform.function

We got random `test_suite_platform` fails in CI tests
The CI reports with this PR
```
Time: delay seconds ............................................... FAILED
elapsed_secs >= delay_secs
at line 87, /var/lib/build/tests/suites/test_suite_platform.function
```
I think it is due to `time(time_t*)` returns Epoch time which is discontinuous. 

Workaround random `test_suite_platform` fail in time test

---

docs/use-psa-crypto.md
include/mbedtls/mbedtls_config.h
tests/suites/test_suite_pk.function
tests/suites/test_suite_pkparse.function
tests/suites/test_suite_pkwrite.function
tests/suites/test_suite_ssl.function
tests/suites/test_suite_x509parse.function
tests/suites/test_suite_x509write.function

Fixing USE_PSA_INIT/DONE in SSL/X509/PK test suites

---

tests/suites/test_suite_pk.function
tests/suites/test_suite_pkparse.function
tests/suites/test_suite_pkwrite.function
tests/suites/test_suite_ssl.function
tests/suites/test_suite_x509parse.function
tests/suites/test_suite_x509write.function

This is the backport of PR #7461

Backport: Fixing USE_PSA_INIT/DONE in SSL/X509/PK test suites

---

library/constant_time.c

Saves a few bytes by removing an effectively duplicated function
| orig:d3ca5e589 | THIS PR |      Delta | Filename |
|---------------:|-----------:|-----------:|:---------|
|    1542, 0 |    1512, 0 |      -30+0 | `constant_time.o` |
From @daverodgman - thanks!

Use mbedtls_ct_uint_if() rather than mbedtls_ct_cond_select_sign()

---

library/constant_time.c

Saves a few bytes by removing an effectively duplicated function
From @daverodgman - thanks!

Backport 2.28: Use mbedtls_ct_uint_if() rather than mbedtls_ct_cond_select_sign()

---

programs/test/benchmark.c

The `QueryPerformanceCounter` implementation previously was within `defined(_MSC_VER)`, but it works just as well on other Windows toolchains, like mingw.
For most common mingw x86 build configurations, one of the earlier inline assembly implementations would end up used, but for non-x86 (arm, aarch64), it would end up falling back on the `gettimeofday` implementation.
This implementation did build successfully (as mingw toolchains do provide `gettimeofday`, contrary to MSVC), but the header providing gettimeofday, `<sys/time.h>`, wasn't ever included when building targeting Windows - thus the function was called without a proper declaration.
Clang 15 changes such implicit function declarations into a hard error by default, when building in C99 mode (or newer) [1]. (While Clang 15 still …

Use QueryPerformanceCounter as fallback timer on non-x86 mingw

---

include/mbedtls/pk.h
library/pk.c
library/pk_wrap.c
library/pkwrite.c
library/ssl_tls12_server.c
tests/src/test_helpers/ssl_helpers.c

Store the opaque key ID directly into the `mbedtls_pk_context` instead of the previous `pk_ctx` member of that structure.
Resolves #7513

PK: move the opaque context to a new member of the mbedtls_pk_context structure

---

library/ssl_tls.c

Add const to move variables to .rodata section
Signed-off-by: Xeenych <xeenych@gmail.com>
Fix #5891

Reduce RAM - move some variables to .rodata

---

tests/suites/test_suite_platform.data
tests/suites/test_suite_platform.function

Fix CI [random failure](https://ci.staging.trustedfirmware.org/blue/organizations/jenkins/mbed-tls-nightly-tests/detail/mbed-tls-nightly-tests/420/pipeline/499/) on Windows.
Below is the log from above link
```
[2023-05-05T00:32:09.365Z]         Start 115: x509parse-suite
[2023-05-05T00:32:09.365Z] 115/116 Test #115: x509parse-suite ............................   Passed    0.96 sec
[2023-05-05T00:32:09.365Z]         Start 116: x509write-suite
[2023-05-05T00:32:18.802Z] 116/116 Test #116: x509write-suite ............................   Passed    0.74 sec
[2023-05-05T00:32:18.802Z] 
[2023-05-05T00:32:18.802Z] 99% tests passed, 1 tests failed out of 116
[2023-05-05T00:32:18.802Z] 
[2023-05-05T00:32:18.802Z] Total Test time (real) =  62.30 sec
[2023-05-05T00:32:18.802Z] …
```

Remove delay milliseconds test to workaround randome platform-suite fail.

---

scripts/ci.requirements.txt
tests/scripts/audit-validity-dates.py
tests/scripts/generate_test_code.py

We want to introduce this script to audit the expiration date of X509 (i.e. crt/crl/csr files) files in `tests/data_files/` and data in `tests/suites/*.data`.
Fix: #7014, #7015, #7016

cert_audit: Add test certificate date audit script

---

.readthedocs.yaml
docs/redirects.yaml
docs/requirements.in
docs/requirements.txt

This PR is a port of Mbed-TLS/mbedtls-docs#91 for the versioned documentation.
It allows us to maintain our page redirects in-tree.
The update step only runs when the `development` version is built ie. after a PR is merged.
Test runs on a separate [test branch](https://github.com/Mbed-TLS/mbedtls/tree/dev/bensze01/in-tree-redirects-test), and with the branch filter modified (needed because the API token is not exported in PR jobs for safety reasons.):
- 7ce8fba - https://readthedocs.org/projects/mbedtls-versioned/builds/20362324/
- 71f41de - https://readthedocs.org/projects/mbedtls-versioned/builds/20596236/

Add in-tree configuration file for Readthedocs redirects

---

CMakeLists.txt

When Mbed TLS is built as a TF-M subproject with a recent enough version of cmake (i.e. 3.22.1), GNUInstallDirs complains about LANGUAGES not being set in project when the short signature is used. So make sure to use the normal signature, i.e. set the LANGUAGES option explicitly

Set LANGUAGES explicitly in CMakeLists.txt project()

---

library/x509_crt.c
tests/suites/test_suite_x509parse.data

Leading zeroes in IPv4 addresses might mean that we're dealing with the octal format, and we do not support that.
Current behaviour might lead to an ambiguity and a flaw where we accept 0.010.0.0 (as octal, decimal equivalent 0.8.0.0) as 0.10.0.0. 
Following the discussion [here](https://github.com/Mbed-TLS/mbedtls/issues/7477), this PR removes the support for leading zeroes.
Resolves https://github.com/Mbed-TLS/mbedtls/issues/7477.

Disallow leading zeroes when parsing IPv4 addresses

---

configs/config-symmetric-only.h
docs/architecture/mbed-crypto-storage-specification.md
docs/architecture/testing/driver-interface-test-strategy.md
docs/architecture/testing/psa-storage-format-testing.md
include/psa/crypto_compat.h
include/psa/crypto_extra.h
include/psa/crypto_se_driver.h
include/psa/crypto_struct.h
include/psa/crypto_types.h
scripts/config.py
tests/include/spe/crypto_spe.h
tests/scripts/psa_collect_statuses.py
tests/src/psa_exercise_key.c

Replace references to Mbed Crypto (rebase)

---

configs/config-symmetric-only.h
docs/architecture/mbed-crypto-storage-specification.md
docs/architecture/testing/driver-interface-test-strategy.md
docs/architecture/testing/psa-storage-format-testing.md
include/psa/crypto_compat.h
include/psa/crypto_extra.h
include/psa/crypto_se_driver.h
include/psa/crypto_struct.h
include/psa/crypto_types.h
scripts/config.py
tests/include/spe/crypto_spe.h
tests/scripts/psa_collect_statuses.py
tests/src/psa_exercise_key.c

Mostly trivial backport of #7589 

Replace references to Mbed Crypto (rebase) - backport 2.28

---

include/mbedtls/pk.h
include/mbedtls/x509.h
library/pk.c
library/pk_internal.h
library/pkparse.c
library/pkwrite.c
library/ssl_misc.h
library/ssl_tls.c
library/ssl_tls12_client.c
library/ssl_tls12_server.c
library/x509_crt.c
tests/suites/test_suite_pk.function
tests/suites/test_suite_pkparse.function

The `mbedtls_pk_ec()` is not ideal as:
- provides direct access to the `ecp_keypair` structure embedded by the `pk_context` and
- it bypasses the control of the PK module
However it cannot be deprecated since it is a public function (i.e. it might be used by some user) and at the same time it is not easy to find the right replacement.
As a consequence, as intermediate solution, this PR does the following:
- when ECP_C is defined, then the legacy `mbedtls_pk_ec` is available
- when ECP_C is not defined, but `ECP_LIGHT` is, then 2 new functions are present: `mbedtls_pk_ec_[ro/rw]`
- they still return a pointer, but it will be `const` or non-`const` accordingly
- their name explicitly state the usage purpose of the returned pointer

Set mbedtls_pk_ec() as internal function when ECP_C is not defined

---

library/debug.c

Fix: no newline when debug msg over DEBUG_BUF_SIZE - backport 2.28

---

include/mbedtls/bignum.h
library/bignum.c

Resolves #7246 . This pr updates `mbedtls_mpi_shift_l()` to use the newly introduced `mbedtls_mpi_core_shift_l`

[Bignum] Adjust mbedtls_mpi_core_shift_l to use the core function

---

library/debug.c

Rebase of #6511 with a fix for the static assert issue.

Fix: no newline when debug msg over DEBUG_BUF_SIZE

---

ChangeLog.d/add-psa_want_alg_some_pake.txt
include/mbedtls/config_psa.h
library/psa_crypto.c

This removes several functions if no PAKE algorithms are specified, saving up to ~1.5KB by removing the functions `psa_pake_abort()`, `psa_pake_complete_inputs()`, `psa_pake_get_implicit_key()`, `psa_pake_input()`, `psa_pake_output()`, `psa_pake_set_password_key()`, `psa_pake_set_peer()`, `psa_pake_set_role()`, `psa_pake_set_user()` and `psa_pake_setup()` completely if they are not needed.
Code size improvements for Armv8-M/Thumb2:
| orig:1d046fa0d | orig:6d62faca8 |      Delta | Filename |
|---------------:|-----------:|-----------:|:---------|
|   37556, 4 |   36014, 4 |    -1542+0 | `psa_crypto.o` |

Only include psa_pake_setup() and friends if some PAKE algorithms are required

---

library/base64.c
library/bignum.c

Trivial clean-up: remove DIY definitions of SIZE_MAX since this is guaranteed by C99 (and already relied on elsewhere in the codebase).

Remove DIY SIZE_MAX definitions

---

programs/psa/key_ladder_demo.sh
programs/test/dlopen_demo.sh

Allow the demo scripts `dlopen_demo.sh` and `key_ladder_demo.sh` to be run in out-of-tree builds, by requiring that they are run in the project's build directory. For in-tree builds, this is just the project root directory.
**READY**
Yes  
Which branch?
2.x

Fix demo scripts for out-of-tree builds

---

library/ecp_curves.c
library/ecp_invasive.h
scripts/mbedtls_dev/ecp.py
tests/suites/test_suite_ecp.function

Create ecp_mod_p192k1_raw(), ecp_mod_p224k1_raw() and ecp_mod_256k1_raw() which are called by their non-raw counterparts.
Resolves #7263 

[Bignum] Split out _raw Koblitz reduction functions

---

include/mbedtls/build_info.h

This PR temporarily fix the issues mentioned in #7609. 
By tweaking the location of including `config_psa.h`, config options [after `#include "mbedtls/config_psa.h"`](https://github.com/Mbed-TLS/mbedtls/pull/7611/files#diff-a8f17907111aedcf1c8d23fd7bb54af6f6bc68728f1f33d1b8f21114d68d371fR95) are implied correctly in `build_info.h`. I have checked config options after `#include "mbedtls/config_psa.h"` don't have impact on how config options defined/implied in `config_psa.h`. So this PR could be a quick fix for the mutual implications between `config_psa.h` and `build_info.h`.

build_info.h: fix mutual implications with config_psa.h temporarily 

---

tests/data_files/Makefile

https://github.com/Mbed-TLS/mbedtls/commit/b17f6a211daa6df3d7783f9a1373ba21fe8ca117 from https://github.com/Mbed-TLS/mbedtls/pull/7416 introduced a Makefile target that has two issues: missing tab and a prerequisite that's not a file. This PR fixes that.

Fix wrong makefile target

---

tests/data_files/Makefile

Backport of https://github.com/Mbed-TLS/mbedtls/pull/7634.
https://github.com/Mbed-TLS/mbedtls/commit/b17f6a211daa6df3d7783f9a1373ba21fe8ca117 from https://github.com/Mbed-TLS/mbedtls/pull/7416 introduced a Makefile target that has two issues: missing tab and a prerequisite that's not a file. This PR fixes that.

[2.28 backport] Fix bad keyfile prereqs

---

include/mbedtls/pk.h
library/debug.c
library/pk.c
library/pk_internal.h
library/pk_wrap.c
library/pkparse.c
library/pkwrite.c
library/pkwrite.h
library/ssl_tls12_client.c
tests/suites/test_suite_debug.function
tests/suites/test_suite_pk.function
tests/suites/test_suite_pkparse.function

As suggested [here](https://github.com/Mbed-TLS/mbedtls/pull/7202#issuecomment-1508063453), this PR is the reshaped version of #7202 which includes only the changes which are relevant to solve issue #7073.
Depends on:
- ~#6838~
- #7595
Resolves #7073

Avoid parse/unparse public ECC keys in PK with USE_PSA when !ECP_C

---

tests/suites/test_suite_debug.function

`USE_PSA_INIT/DONE` macros were recently updated in SSL/X509/PK test suites (see https://github.com/Mbed-TLS/mbedtls/pull/7461 and its backport https://github.com/Mbed-TLS/mbedtls/pull/7505), but unfortunately `test_suite_debug` was not taken into account for this fix. 
The `development` version was fixed in PR #7554 and this is the backport for `mbedtls-2.28`.

Backport: add missing USE_PSA_INIT/DONE in test_suite_debug

---

include/mbedtls/platform.h

Some identifiers (e.g. mbedtls_free) can name either functions or macros depending on configuration settings.  For those that turn out to name macros, first clear out any existing macro definitions to accommodate possible unconditional bulk symbol renaming.  (There remains no standard provision for such renaming, but it's nevertheless straightforward enough to do as desired, particularly with this change in place.)
Backport of #6943.

Backport 2.28: mbedtls/platform.h: Avoid potential macro redefinition warnings.

---

include/mbedtls/platform.h

Some identifiers (e.g. mbedtls_free) can name either functions or macros depending on configuration settings.  For those that turn out to name macros, first clear out any existing macro definitions to accommodate possible unconditional bulk symbol renaming.  (There remains no standard provision for such renaming, but it's nevertheless straightforward enough to do as desired, particularly with this change in place.)
I will be happy to supply a corresponding LTS PR in due course, particularly given that I'm using that branch myself.
(Split from #6930.)

mbedtls/platform.h: Avoid potential macro redefinition warnings.

---

library/ssl_cookie.c
library/ssl_tls.c
library/ssl_tls12_server.c

Fixes #7374.
Refactoring reading of big endian values to use the macros in `alignment.h`.
This is produced for the code size EPIC however after using the code size tracking script from #7426 there has been no impact on code size, either positively or negatively, as a result of these changes, so I am not sure this is worth merging.
- **changelog** not required: Not a user visible change.
- **backport** not required: It's an enhancement.
- **tests** not required: Changes are a refactor which does not change functionality. Existing tests are enough. …

Refactor reading of multi-byte values using functions in alignment.h

---

library/ssl_tls.c

Fixes #7529.
Issue 7529 uncovered an unrequired check in a for loop condition in ssl_tls.c. This PR removes said check.

Remove extraneous check in for loop condition

---

tests/scripts/audit-validity-dates.py

Preceding PR: https://github.com/Mbed-TLS/mbedtls/pull/7399 — ~~the first new commit is the one after "[cert_audit: Reword the options and their descriptions](https://github.com/Mbed-TLS/mbedtls/pull/7399/commits/1d4cc917cea1abc710e96465e4e6aa7f6296c738)"~~
This PR contains several improvements of the certificate audit scripts.
- Support parsing multiple PEM objects in a single file.
- Merge the AuditData for identical X.509 objects in different locations.
- Sorted outputs

cert_audit: Improvements of audit script

---

tests/src/psa_exercise_key.c

If test function `key_storage_read()` in `test_suite_psa_crypto_storage_format.function` is called with algorithm `PSA_ALG_PURE_EDDSA`, this leads to a call of `psa_sign_hash()` in `psa_exercise_key.c`. Pure EDDSA can only be used with `psa_sign_message()`.
Signed-off-by: Oberon microsystems AG, Zürich

Fix test conditions because PURE_EDDSA does not support sign_hash

---

include/mbedtls/pk.h
library/pk.c
library/pk_internal.h
library/pk_wrap.c
library/pkparse.c
library/pkwrite.c
library/ssl_tls.c
library/ssl_tls12_client.c
library/ssl_tls12_server.c
library/x509_crt.c
tests/scripts/analyze_outcomes.py
tests/suites/test_suite_ecp.function
tests/suites/test_suite_pk.function
tests/suites/test_suite_pkparse.data
tests/suites/test_suite_pkparse.function

The goal of this PR is to continue the work started with #7202 (related issue #7073) allowing to get rid of the `ecp_keypair` structure also for the public key. However, differently from #7202, in this case the content of the public key is not kept in clear in `pk_context` structure, but it is instead imported into PSA and only its ID is kept.
~Depends on #7554~
Resolves #7074

Avoid parse/unparse private ECC keys in PK with USE_PSA when !ECP_C

---

configs/crypto_config_profile_medium.h
configs/tfm_mbedcrypto_config_profile_medium.h
include/psa/crypto_platform.h
scripts/code_size_compare.py

Fix: #7360 
This PR adds support to measure code size for tfm-medium. It can auto-detect host architecture in order to reflect correct architecture information in size report.
A follow-up PR will handle more cases:

code size measurement support for tfm-medium

---

library/ssl_tls13_client.c
library/ssl_tls13_server.c

In `library/ssl_tls13_client.c` and `library/ssl_tls13_server.c`, calling to `time` function need to be changed to `mbedtls_time` to handle the case when `MBEDTLS_PLATFORM_TIME_MACRO` is defined.
This PR will close #7655

Fix: correct calling to time function in tls13 client&server

---

library/pk.c
library/pk_internal.h
library/pk_wrap.c
tests/suites/test_suite_pk.function

Add support for key pair check for opaque EC keys.
Depends on #7533 
Resolves #7485

PK: add support for check_pair() with "opaque" EC keys

---

ChangeLog.d/basic-uri-verification.txt
include/mbedtls/x509_crt.h
library/x509_crt.c
tests/suites/test_suite_x509parse.data

Only exact matching without normalization is supported.
Fixes https://github.com/Mbed-TLS/mbedtls/issues/7563.
See https://github.com/Mbed-TLS/mbedtls/pull/7436 and https://github.com/Mbed-TLS/mbedtls/pull/7025 for comparison.

Add partial support for URI SubjectAltNames verification

---

tests/data_files/Makefile

The commands in `tests/data_files/Makefile` to generate ec key files is invalid, which is introduced in #6838

Fix invalid commands for ec_x{25519,448}_{prv,pub}.{der,pem}

---

ChangeLog.d/oid-parse-from-numeric-string.txt
include/mbedtls/oid.h
library/oid.c
tests/suites/test_suite_oid.data
tests/suites/test_suite_oid.function

Add a new function `mbedtls_oid_from_numeric_string()` that parses the provided OID string into an `mbedtls_asn1_buf`.

Parse an OID from a string

---

ChangeLog.d/armclang-compile-fix.txt
library/bn_mul.h
tests/scripts/all.sh

Fix compile fail on armclang for certain M-class CPUs, when optimisation is enabled. Fixes #1077 

Fix armclang compile fail

---

.gitignore

The clangd language server uses a file called `compile_commands.json` to interpret the source tree. This is generated by CMake and must be present in the source tree in order to use clangd properly.
Add this to the gitignore to improve the Mbed TLS developer experience for users of clangd.

Add clangd compilation databases to gitignore

---

ChangeLog.d/fix-unterminated-pragma-clang-attribute-push.txt
library/sha256.c
library/sha512.c
tests/scripts/all.sh

If we're built with `MBEDTLS_SHAxxx_USE_A64_CRYPTO_IF_PRESENT` but don't have a way to detect the crypto extensions required, the code turns off `xxx_IF_PRESENT` and falls back to C only (with a warning). This was done after the attributes are pushed, and the pop is done only `#if defined(xxx_IF_PRESENT)`, so this commit fixes that.
Also fix an issue with `all.sh` that cropped up while testing (`--armc5-bin-dir` and `--armc6-bin-dir` don't work)

Fix "unterminated '#pragma clang attribute push'" in sha256/sha512.c

---

.readthedocs.yaml

Tiny but not trivial backport of #7750.
Ensure that all possible config options are documented by building the docs in the realfull config on Read The Docs.

[Backport 2.28] Build the docs in realfull config

---

tests/src/drivers/test_driver_pake.c

gcc 11.3 fails when compiling ecjpake drivers

---

ChangeLog.d/aes-perf.txt
library/aes.c
library/common.h
tests/suites/test_suite_common.data

This improves block-XOR performance on architectures with 64-bit registers, which benefits mostly AES (presumably because use of AESCE / AESNI is fast so the XOR part is more significant than other ciphers).
I've modified the AES-CBC implementation to make better use of this and also eliminated some unnecessary memcpy's, which has improved AES-CBC performance everywhere (around 7%-11%).
Performance uplift is quite varied depending on compiler (clang vs gcc), optimisation level (O2 vs Os) and mode (all measurements on M1 Pro). Everything is same-or-faster (only clang -Os XTS is the same; everything else sees some uplift). gcc gets most benefit (around 30% average over the different modes and optimisation levels). clang averages around 8% uplift overall. Biggest win is AES-XTS (61-85% on …

AES perf improvements

---

scripts/data_files/version_features.fmt
scripts/generate_features.pl

Save code-size by not storing the "MBEDTLS_" prefix that is present for every feature macro.
Saves a bit over 1 kB for clang -Os with default configuration.

Shorten encoding of version features

---

CMakeLists.txt
ChangeLog.d/bugfix_iar_typo.txt

[Backport 2.28] Fix typo in CMakeList.txt in IAR compiler flags

---

CMakeLists.txt
ChangeLog.d/bugfix_iar_typo.txt

Continuation of #7657.
Commit 5d8adab9838d8ee6b18edd6a42e75fd8fd191b21 introduced a typo in the flag for the IAR compiler. 
--warnings_are_errors is the correct flag

Fix typo in CMakeList.txt in IAR compiler flags

---

tests/scripts/all.sh

The various all.sh components that use libtestdriver1 have a lot of code in common. Factor the common bits into helper functions: this reduces duplication and makes each component less cluttered hence more readable. Also add a bit of documentation.
The purpose of this PR is to change as little as possible while making things more readable and uniform.
Questions such as "is the current content of `helper_libtestdriver1_adjust_config` really needed?" or "should it not include CMAC as well?" or "should we take an entirely different approach to things that don't have their own ACCEL macros?" are explicitly out of scope for this PR.

Libtestdriver1 helpers

---

include/mbedtls/ecp.h
library/ecp_invasive.h

This is an internal detail of the ECC arithmetic implementation, only exposed for the sake of the unit tests
Mbed TLS 3.4.0 was released with the type mbedtls_ecp_modulus_type defined in a public header, but without Doxygen documentation, and without any public function or data structure using it. So removing it is not an API break.

Move mbedtls_ecp_modulus_type out of the public headers

---

library/ecp_curves.c
library/ecp_invasive.h
scripts/mbedtls_dev/ecp.py
tests/suites/test_suite_ecp.function

Split out raw functions for ECP mod p448 reduction, and change testing over to using the generic mod P functions.

[Bignum] Split out raw ECP mod p448

---

docs/proposed/psa-conditional-inclusion-c.md

Resolves #7744. Part of the text shamelessly stolen from #7766.
Context: https://github.com/Mbed-TLS/mbedtls/issues/7439#issuecomment-1543790495 (and preceding + following discussion).
Implementation: #7641 and follow-up issues #7771, #7772 and #7773.

Update `PSA_WANT` spec for new `KEY_PAIR` scheme

---

include/mbedtls/build_info.h
include/mbedtls/mbedtls_config.h
library/pkparse.c
tests/scripts/all.sh
tests/scripts/analyze_outcomes.py
tests/scripts/depends.py
tests/suites/test_suite_pkparse.data

This PR resolves #7442 (please refer to the original issue because the goals are described pretty well there).
Depends on ~#7641~ (merged) 
Resolves #7442

Driver-only ECC: auto-enable ECP_LIGHT when needed

---

library/psa_crypto_ffdh.h
library/psa_crypto_pake.h

Fix modern (>version 13) clang warnings about empty descriptions for return values, which break the build with warnings as errors.

Pacify clang15 warnings about empty \retval

---

library/ecp_curves.c

Given the size of ciL is set dependant on MBEDTLS_HAVE_INT32, clang rightfully reports this as unreachable code. Fix this by using #define guards instead.
Addresses #7787

[Bignum] Fix 32 bit unreachable code build failure

---

tests/suites/test_suite_x509parse.function

The latter gives much more informative errors.

x509parse tests: Replace TEST_ASSERT with TEST_EQUAL

---

tests/suites/test_suite_x509parse.function

Backport of https://github.com/Mbed-TLS/mbedtls/pull/7691

Backport 2.28: x509parse tests: Replace TEST_ASSERT with TEST_EQUAL

---

ChangeLog.d/ssl_debug_helpers-stack_usage.txt
scripts/generate_ssl_debug_helpers.py

Use a switch instead of an array. The array was very hollow for some enum types such as mbedtls_ssl_protocol_version (which formerly used small values, but switched to using the protocol encoding as enum values in Mbed TLS 3.2.0). Optimizing compilers know how to compile a switch into a lookup table when the range warrants it. Fixes #7804.

Fix very high stack usage in SSL debug code

---

library/common.h

Small improvement to aarch64 asm documentation.

Aarch64 asm docs improvement

---

library/common.h
library/constant_time.c
library/lmots.c
library/lms.c
library/psa_crypto.c
library/psa_crypto_slot_management.c
library/sha512.c
library/ssl_cookie.c
library/ssl_msg.c
library/ssl_ticket.c
library/ssl_tls.c
library/ssl_tls12_client.c
library/ssl_tls12_server.c
library/ssl_tls13_client.c
library/ssl_tls13_generic.c
library/ssl_tls13_keys.c
tests/include/test/macros.h
tests/src/psa_crypto_helpers.c

Introducing an intermediate function saves code size that's otherwise taken by excessive, repeated arguments in each place that was translating errors. Fixes https://github.com/Mbed-TLS/mbedtls/issues/7402.
Tested using 
```
scripts/config.py baremetal_size
./scripts/footprint.sh
```
Before this PR:
```
default (include/mbedtls/mbedtls_config.h):
text    data     bss     dec     hex filename
313232     162    3166  316560   4d490 (TOTALS)
```
After this PR:
```
default (include/mbedtls/mbedtls_config.h):
text    data     bss     dec     hex filename
312792     162    3166  316120   4d2d8 (TOTALS)
```
440 bytes saved.

Optimize error translation code size

---

scripts/code_style.py

Add an option to speed up the code style check by only considering files modified since a given commit:
```
scripts/code_style.py -s HEAD # only check files that aren't committed yet
scripts/code_style.py -s HEAD~3 # only check files modified in the last 3 commits
scripts/code_style.py -s upstream/development # only check files modified in my branch
```

code_style.py --since

---

tests/suites/test_suite_x509parse.data
tests/suites/test_suite_x509parse.function

Remove custom parsing code in AuthorityKeyIdentifier tests and use `mbedtls_x509_dn_gets()` and `strcmp()` instead.
Followup for a [comment](https://github.com/Mbed-TLS/mbedtls/pull/7411/files#r1228451285) on #7411.

Simplify directory name comparison in AuthorityKeyIdentifier tests

---

ChangeLog.d/fix-crypt_and_hash-decrypt-issue.txt
programs/aes/crypt_and_hash.c

crypt_and_hash decryption fails when used with a stream cipher
mode of operation due to the input not being multiple of block
size, this only applies to block cipher modes and not stream
ciphers.This change exempts CTR, CFB & OFB modes from this check.

Backport 2.28: Fix crypt_and_hash decrypt issue when used with stream cipher

---

ChangeLog.d/fix-crypt_and_hash-decrypt-issue.txt
programs/aes/crypt_and_hash.c

crypt_and_hash decryption fails when used with a stream cipher mode of operation due to the input not being multiple of block size, this only applies to block cipher modes and not stream ciphers.This change exempts CTR, CFB & OFB modes from this check.
fixes #7417
crypt_and_hash decryption fails when used with a stream cipher mode of operation due to the input not being multiple of block size, this only applies to block cipher modes and not stream ciphers.This change exempts CTR, CFB & OFB modes from this check.

Fix crypt_and_hash decrypt issue when used with stream cipher

---

ChangeLog.d/fix-string-to-names-retcode.txt
library/x509_create.c
tests/suites/test_suite_x509write.data

Fix an issue where `mbedtls_x509_string_to_names()` returns success while in fact failing to parse a name. This happens whenever a string is supplied that doesn't contain either `=` or `,`.
In the problematic case, the supplied `mbedtls_x509_name` list is left alone and the function returns success when it should return an error.
Fixes #2969.

Fix false success return code in `mbedtls_x509_string_to_names()`

---

ChangeLog.d/fix-string-to-names-retcode.txt
library/x509_create.c
tests/suites/test_suite_x509write.data

[Backport 2.28] Fix false success return code in `mbedtls_x509_string_to_names()`

---

ChangeLog.d/fix-win32-llvm-build.txt
library/aesni.c

The Microsoft-only equivalent to GCC's `cpuid.h` is `intrin.h`. CLang contains both, but neither is directly included in Win32 builds, causing `__cpuid` to not be defined. This change explicitly includes `intrin.h` when `cpuid.h` is not used.

Support compilation using CLang on Windows

---

ChangeLog.d/fix-tfm-build.txt
library/aes.c
library/ctr_drbg.c
library/entropy.c
library/pkparse.c
library/pkwrite.c
tests/scripts/all.sh

Backport of #7851 , plus some extra fixes only needed for 2.28, and excluding the TF-M config build tests (because we don't ship the necessary configs in 2.28). Also includes the build-test for all `aes.c` variations.
It's still necessary to add `MBEDTLS_SHA256_C` to the TF-M config (to allow entropy.c to build) and to disable `MBEDTLS_PSA_CRYPTO_SPM`, but at least all of the warnings about unused variables, etc are addressed.

Fix AES dependencies - build TF-M config cleanly - backport 2.28

---

ChangeLog.d/fix-tfm-build.txt
library/aes.c
library/x509.c
tests/scripts/all.sh

Fixes the build w.r.t. clang warnings for unused variables for all combinations of:
MBEDTLS_AES_SETKEY_ENC_ALT
MBEDTLS_AES_DECRYPT_ALT
MBEDTLS_AES_ROM_TABLES
MBEDTLS_AES_ENCRYPT_ALT
MBEDTLS_AES_SETKEY_DEC_ALT
MBEDTLS_AES_FEWER_TABLES
MBEDTLS_PADLOCK_C
I've tested every combination of the above - all 128 variations build cleanly.
With this PR, we build cleanly out-of-the-box for the TF-M config that we ship.

Fix AES dependencies - build TF-M config cleanly

---

library/aes.c

Fix: #7381, #744
This PR changes `pow` and `log` table in `aes_gen_tables` from `int` to `uint8_t` in order to save RAM usage. Additionally, local variable `x`, `y`, `z` only handles values of `8 bit`. We can also use `uint8_t` for those three values to save RAM usage further.
**RAM Usage**: (at 961f5dc)
`command: make CC=gcc CFLAGS="-fstack-usage" -j` 
| Function | Old Size | New Size | Change (Bytes) |
| ---: | ---: |  ---: |  ---: |
| aes_gen_tables | 2096 | 560 | -1536 |

AES: use uint8_t for array of pow and log to save RAM usage

---

library/aesce.c

Building mbedtls with different aarch64 tuning variations revealed that we should use the crypto extensions without forcing a particular architecture version or core, as that can create issues.
This was discovered with yocto, after adding v3.4.0 support to upstream openembedded, where it is built with a lot of tuning variations.
- [x ] **changelog** not required
- [x ] **backport**  not required
- [x ] **tests** not required (change was tested in yocto with different tuning configurations)
I don't know who should review this, so I am going to cc some folks below:
@gilles-peskine-arm @tom-cosgrove-arm 
Thanks!

aesce: do not specify an arch version when enabling crypto instructions

---

library/ssl_tls.c

Resolves #7227.
Upon inspection, I decided that `ssl_update_checksum_sha{256,384}()` didn't need de-duplicating as they are already one-liners.
Code size, measured with `all.sh build_arm_none_eabi_gcc_m0plus` (possibly manually disabling `USE_PSA`):
|               | USE_PSA |      |      | !USE_PSA  |      |      |
| ---           | ---:    | ---: | ---: | ---:      | ---: | ---: |
| Before        | 333341  |      |      | 322411    |      |      |
| calc_verify   | 333305  | -36  |      | 322363    | -48  |      |
| finished      | 333249  | -56  | -92  | 322291    | -72  | -120 |

De-duplicate TLS hashing functions

---

scripts/code_size_compare.py

If we don't remove all executable files in current working directory, we might measure code size between different architecture and configuration. This generates a wrong code size comparison report. This PR guarantees it runs `make clean` before build libraries for code size comparison.
This is an enhancement of #7650. 

code_size_compare.py: run make clean before build libraries

---

scripts/code_style.py

Trivial backport of https://github.com/Mbed-TLS/mbedtls/pull/7822

Backport 2.28: code_style.py --since

---

ChangeLog.d/mbedtls_x509_time.txt
include/mbedtls/x509.h
library/x509.c
library/x509_crt.c

Features
* Improve mbedtls_x509_time performance and reduce memory use.
* Reduce syscalls to time() during certificate verification.
Please consider reviewing commit-by-commit to step through the code transformations.
**READY**
NO  
NO

mbedtls_x509_time performance and reduce memory use
