Mbed-TLS/mbedtls

library/aes.c
A tiny and quick fix to match comment in `#endif` for aes.
=> AES: fix mismatch comment in #endif

README.md
Since https://github.com/Mbed-TLS/mbedtls/pull/7059, there is no natural entry point in the documentation to read about drivers. Add a section to the readme file.
Resolves #7474.
=> README: add section about drivers

ChangeLog.d/python3.8.txt, README.md
Python 3.7 [has just reached its end of life](https://devguide.python.org/versions/). Officially require Python 3.8.
Currently all of our scripts work with Python 3.5, but we do not promise that this will remain true in the next release.
Targetting the next release, because by that time we might not be testing everything on older Python versions anymore.
Note: 2.28.0 was released a few days before EOL of Python 3.6. Its documentation states a requirement for “Python 3”.
=> Officially require Python 3.8

README.md
Mbed TLS 2.28.0 was released on 2021-12-15. At the time, the oldest officially supported Python version was 3.6 (which reached its end of life on 2021-12-23). So promise backward compatibility with 3.6, but no earlier.
=> Backport 2.28: officially require Python 3.6

programs/fuzz/onefile.c
Trivial backport of https://github.com/Mbed-TLS/mbedtls/pull/7584
=> Backport 2.28: Fuzz programs: print an error if loading the reproducer fails

programs/fuzz/onefile.c
The fuzz programs were returning a nonzero status if they failed to load the reproducer, but that's discreet and not informative. Make them also print an error message.
=> Fuzz programs: print an error if loading the reproducer fails

library/ssl_client.c, library/ssl_misc.h, library/ssl_tls.c, library/ssl_tls12_client.c, library/ssl_tls12_server.c, library/ssl_tls13_client.c, library/ssl_tls13_generic.c, library/ssl_tls13_keys.c, library/ssl_tls13_server.c, programs/ssl/ssl_client2.c, programs/ssl/ssl_server2.c, programs/ssl/ssl_test_lib.c, programs/ssl/ssl_test_lib.h, tests/opt-testcases/tls13-compat.sh, tests/opt-testcases/tls13-kex-modes.sh, tests/scripts/generate_tls13_compat_tests.py, tests/ssl-opt.sh, tests/suites/test_suite_ssl.function
Follow-up PR for PR https://github.com/Mbed-TLS/mbedtls/pull/7627. Resolves https://github.com/Mbed-TLS/mbedtls/issues/7667
Built on top of PR https://github.com/Mbed-TLS/mbedtls/pull/7627.
Clean up the code by adapting names (function, fields, macros, parameters, etc.) for FFDH.
=> Make use of FFDH keys in TLS 1.3 - follow-up

library/platform_util.c
CLOCK_MONOTONIC does not account for time when suspend. And CLOCK_BOOTTIME does it.
It is also reported at https://github.com/golang/go/issues/24595, https://github.com/eclipse/paho.mqtt.c/issues/1095
=> Replace CLOCK_MONOTONIC with CLOCK_BOOTTIME for `mbedtls_ms_time` on linux

library/net_sockets.c
```
mbedtls/library/net_sockets.c:497:9: error: comparison of integers of different signs: 'SOCKET' (aka 'unsigned long long') and 'int' [-Werror,-Wsign-compare]
FD_SET(fd, &read_fds);
^~~~~~~~~~~~~~~~~~~~~
```
Unfortunately, there is `SOCKET fd_set::fd_array[FD_SETSIZE]` and `SOCKET` is `unsigned long long` on Windows, thus the comparison `int fd` with `fd_set::fd_array` elements raises the warning that is treated as error while compiling with LLVM Clang.
=> Fix error: comparison of integers of different signs: 'SOCKET' and 'int'

library/net_sockets.c
Backport of https://github.com/Mbed-TLS/mbedtls/pull/7212
```
mbedtls/library/net_sockets.c:497:9: error: comparison of integers of different signs: 'SOCKET' (aka 'unsigned long long') and 'int' [-Werror,-Wsign-compare]
FD_SET(fd, &read_fds);
^~~~~~~~~~~~~~~~~~~~~
```
Unfortunately, there is `SOCKET fd_set::fd_array[FD_SETSIZE]` and `SOCKET` is `unsigned long long` on Windows, thus the comparison `int fd` with `fd_set::fd_array` elements raises the warning that is treated as error while compiling with LLVM Clang.
=> mbedtls-2.28: Fix error: comparison of integers of different signs: 'SOCKET' and 'int'

CMakeLists.txt, ChangeLog.d/cmake-pass-through-config-defines.txt, library/CMakeLists.txt, tests/scripts/all.sh
Backport of #6914.
Conflicts:
- `library/CMakeLists.txt` - the code that adds include directories and definitions has changed between 2.28 and development.
- `all.sh` - 2.28 does not have the CMake as-package and as-package install tests.
=> [Backport 2.28] Pass `MBEDTLS_CONFIG_FILE` defines through cmake

CMakeLists.txt, ChangeLog.d/cmake-pass-through-config-defines.txt, library/CMakeLists.txt, tests/scripts/all.sh
When `-DMBEDTLS_CONFIG_FILE` or `-DMBEDTLS_USER_CONFIG_FILE` are passed to cmake, pass them through as compile definitions. This allows different mbedtls configs to be passed at configure time without modifying any cmake files.
The following will build with a different config in `my_config.h`:
```sh
cd mbedtls
cmake -DMBEDTLS_CONFIG_FILE=my_config.h .
make
```
Or to add extra options from a config file `extra_config.h`:
```sh
cd mbedtls
cmake -DMBEDTLS_USER_CONFIG_FILE=extra_config.h .
make
```
Fixes #4805
Fixes #4496
=> Pass `MBEDTLS_CONFIG_FILE` defines through cmake

ChangeLog.d/fix-hrr-in-psk-kem.txt, library/ssl_tls13_server.c, tests/ssl-opt.sh
Follow-up on #7627 comment https://github.com/Mbed-TLS/mbedtls/pull/7627#issuecomment-1590792002.
=> tls13: server: Fix spurious HRR

docs/architecture/testing/test-framework.md, tests/compat.sh, tests/ssl-opt.sh
Fix: #5692 
For `compat.sh`, if `MBEDTLS_TEST_OUTCOME_FILE` is set, the outcome of each test case is recorded in a outcome file with the format of
```
platform;configuration;test suite name;test case description;PASS/FAIL/SKIP;failure cause
```
In addition, `--append-outcome` is introduced to append test records to the outcome file if set.
=> Record the outcome of each test case in compat.sh

docs/architecture/testing/test-framework.md, tests/compat.sh, tests/ssl-opt.sh
=> Backport 2.28: Record the outcome of each test case in compat.sh

tests/scripts/all.sh, tests/scripts/analyze_outcomes.py, tests/suites/test_suite_psa_crypto_metadata.function
Resolves: https://github.com/Mbed-TLS/mbedtls/issues/7569
Needs: https://github.com/Mbed-TLS/mbedtls/pull/7577 https://github.com/Mbed-TLS/mbedtls/pull/7627
=> FFDH 4: driver-only parity testing - with TLS 1.3

ChangeLog.d/add-getters-for-some-fields.txt, include/mbedtls/ssl.h, include/mbedtls/ssl_cache.h, tests/src/test_helpers/ssl_helpers.c, tests/suites/test_suite_ssl.function
Partially Fix: https://github.com/Mbed-TLS/mbedtls/issues/6840
The getters are added for the convenience of application usage.
=> Add getters for some fields

tests/suites/test_suite_pem.data
A few negative test cases in test_suite_pem.data rely on DES (“invalid iv”, “malformed”). DES is deprecated.
Construct similar test cases using AES and use them to remove the DES ones.
This is in response to issue #7037 
=> tests/test_suite_pem: Augment DES test cases with AES: PEM

tests/ssl-opt.sh
Reconcile https://github.com/Mbed-TLS/mbedtls/pull/7887 with https://github.com/Mbed-TLS/mbedtls/pull/7858 to fix a [CI failure in `development`](http://ci.trustedfirmware.org/job/mbed-tls-nightly-tests/92/).
=> Fix failure of ssl-opt "TLS 1.3: no HRR in case of PSK key exchange mode"

library/alignment.h
If this particular block of code is ever executed, we define `MBEDTLS_BSWAP32()` to be `__rev()`, but don't include the header that declares the function, and so we get a compilation error - see https://developer.arm.com/documentation/100068/0620/Compiler-Source-Code-Compatibility/Language-extension-compatibility--intrinsics
```
aria.c:350:9: error: call to undeclared function '__rev'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
t = ARIA_P3(b[j]);                      // big endian
^
aria.c:102:20: note: expanded from macro 'ARIA_P3'
#define ARIA_P3(x) MBEDTLS_BSWAP32(x)
^
./alignment.h:185:25: note: expanded from macro 'MBEDTLS_BSWAP32'
#define MBEDTLS_BSWAP32 __rev
^
```
This PR adds the correct header include.
Found when trying to …
=> Fix MBEDTLS_BSWAP32 on armcc 5

tests/suites/test_suite_ecp.function
ECP group compare function should not check the value of T. We only need to assert the value of T after the ECP group copy function is called.
Relates to #6707.
=> 2.28 only: tests/test_suite_ecp: Fix ECP group compare test

include/mbedtls/mbedtls_config.h, library/aesce.c, library/sha256.c, library/sha512.c
When target flags are not set at command line, `armclang` will reports required feature not set error.
This is found and verified at 6.20.1. 
Armclang 6.6 can not enable `aes` and  `sha2`   with `pragma`  and miss `sha3`.
[Armclang 6.20.1 download page](https://developer.arm.com/downloads/view/ACOMPE)
=> Fix armclang without cmd target flags fail

library/gcm.c
Reduce size of static data in gcm. Saves 104 bytes.
=> Reduce size of static data in gcm

library/entropy_poll.c, library/net_sockets.c, library/x509_crt.c
Forcing `_WIN32_WINNT` when the SDK has a default value is not a good idea. Assuming _WIN32_WINNT can be set to a certain value also has bad consequences and it may force some API's to be called when the (old) system doesn't have that. That should make the mbedtls build unsuable in that case.
Each commit explains why the change is needed. In the end `_WIN32_WINNT` is not used and either fallback calls are used or compilation errors are emited explaining what is wrong.
=> Don't force _WIN32_WINNT values

tests/suites/test_suite_psa_crypto.function
Function `derive_ecjpake_to_pms` in [mbedtls/test_suite_psa_crypto.function, line 8909](https://github.com/Mbed-TLS/mbedtls/blob/development/tests/suites/test_suite_psa_crypto.function#L8909) has declared wrong dependency in comment before the function. It should be `PSA_WANT_ALG_TLS12_ECJPAKE_TO_PMS` instead of `MBEDTLS_PSA_BUILTIN_ALG_TLS12_PSK_TO_MS`. The comment is interpreted by the test suite generator.
=> Fix derive_ecjpake_to_pms dependency in PSA crypto test

include/mbedtls/bignum.h, library/bignum.c, library/ecp.c, library/ecp_curves.c, tests/suites/test_suite_bignum_random.function
Reduce the size of mbedtls_mpi from 3 words to 2 on most architectures.
This also reduces the code size significantly in bignum.o and ecp_curves.o, with negligible variations in other modules. I hadn't expected that!
=> Reduce the size of mbedtls_mpi

library/platform_util.c
Originally part of #7939.  In platform_util.c because of IAR predefining `__STDC_LIB_EXT1__` irregardless of whether or not `memset_s` is available we need to add a condition there as well.
=> Fix IAR trying to use memset_s in platform_util

library/common.h
Originally part of #7939. IAR doesn't recognise the __asm__ keyword so in common.h we add a preprocessor condition.
=> Use correct asm keyword for IAR compilers

include/mbedtls/bignum.h, library/bignum_core.c
Since the max size of `mbedtls_mpi_uint` is platform dependent, some checks in mbedtls_mpi_core can be redundant, so a macro was added to check this. This is a part of #7931 .
Fixes:
```
if (sizeof(mbedtls_mpi_uint) == sizeof(unsigned long)) {
^
"/home/agabra02/Documents/mbedtls/library/bignum_core.c",45  Warning[Pe111]: 
statement is unreachable
if (sizeof(mbedtls_mpi_uint) == sizeof(unsigned long long)) {
^
"/home/agabra02/Documents/mbedtls/library/bignum_core.c",50  Warning[Pe111]: 
statement is unreachable
```
=> Use compile-time determination of which __builtin_clz() to use, with new MBEDTLS_MPI_UINT_SIZE macro

library/common.h
Ensure proper behaviour when the argument does not evaluate to either 0 or 1.
=> Robustness fix to MBEDTLS_LIKELY

include/mbedtls/md.h, library/md.c, library/md_psa.h, library/psa_crypto_rsa.c, library/ssl_tls.c, tests/scripts/all.sh, tests/suites/test_suite_md.data, tests/suites/test_suite_md.function
Resolve #6994 
Impact on code size, as measured with `tests/scripts/all.sh -k build_arm_none_eabi_gcc_m0plus`:
| Size in bytes        | crypto |      | x509  |      | tls   |      | total  |      |
| ---                  |   ---: | ---: | ---:  | ---: | ---:  | ---: | ---:   | ---: |
| before               | 229580 |      | 25281 |      | 79534 |      | 334395 |      |
| with NONE -> NONE    | 229600 | +20  | 25297 | +16  | 79582 | +48  | 334479 | +84  |
| (inline + NONE->NONE) | 229556 | -24 | 25329 | +48 | 79562 | +28 | 334447 | +52 |
| (only one inline) | 229580 | -0 | 25297 | +16 | 79590 | + 56 | 334467 | +72 |
| without NONE -> NONE | 229596 | +16  | 25297 | +16  | 79582 | +48  | 334475 | +80  |
| with inline          | 229472 | -108 | 25301 | +20  | 79422 | -112 | 334195 | -200 | …
=> Align psa md identifiers

include/mbedtls/aria.h, include/mbedtls/asn1.h, include/mbedtls/bignum.h, include/mbedtls/camellia.h, include/mbedtls/cipher.h, include/mbedtls/dhm.h, include/mbedtls/ecdsa.h, include/mbedtls/ecp.h, include/mbedtls/hmac_drbg.h, include/mbedtls/mbedtls_config.h, include/mbedtls/pk.h, include/mbedtls/rsa.h, include/mbedtls/ssl.h, include/mbedtls/ssl_cache.h, include/mbedtls/x509.h, include/psa/crypto.h, include/psa/crypto_extra.h
This PR adjusts comments in documentation to fix misuses of \p commands.
Fixes #4209.
=> Fix wrong doxygen parameter names and misused `\p` commands

include/mbedtls/aria.h, include/mbedtls/asn1.h, include/mbedtls/bignum.h, include/mbedtls/camellia.h, include/mbedtls/cipher.h, include/mbedtls/config.h, include/mbedtls/ecdsa.h, include/mbedtls/ecp.h, include/mbedtls/hmac_drbg.h, include/mbedtls/pk.h, include/mbedtls/rsa.h, include/mbedtls/ssl.h, include/mbedtls/x509_crt.h
This PR adjusts comments in documentation to fix misuses of \p commands.
It is a partial backport of https://github.com/Mbed-TLS/mbedtls/pull/5549 - some of the changes did not apply.
=> [Backport 2.28] Fix wrong doxygen parameter names and misused \p commands

.gitignore, ChangeLog.d/inject-entropy.txt, library/psa_crypto.c, scripts/config.py, tests/configs/user-config-for-test.h, tests/include/test/psa_crypto_helpers.h, tests/scripts/all.sh, tests/src/helpers.c, tests/src/psa_crypto_helpers.c, tests/suites/test_suite_entropy.function, tests/suites/test_suite_psa_crypto_entropy.function, tests/suites/test_suite_psa_crypto_init.data, tests/suites/test_suite_random.function
* Fix #7516: fix the build when `MBEDTLS_PSA_INJECT_ENTROPY` is enabled.
* Add a test component with `MBEDTLS_PSA_INJECT_ENTROPY` enabled. This required instrumenting the test framework to perform the necessary entropy injection.
* We had tests for `MBEDTLS_PSA_INJECT_ENTROPY`, but they'd never been enabled in any CI build. Make sure they pass and don't leave the system in a state that breaks subsequent tests.
* Add some checks in the tests that would break if we made an incompatible change to the seed file. Fixes https://github.com/Mbed-TLS/mbedtls/issues/7517.
=> Fix and test MBEDTLS_PSA_INJECT_ENTROPY

library/psa_crypto.c
PAKE getter functions should be removed if no PAKE algorithms are specified. This adds guard for `psa_crypto_driver_pake_get_password_len`,  `psa_crypto_driver_pake_get_password`, `psa_crypto_driver_pake_get_user_len`, `psa_crypto_driver_pake_get_user`, `psa_crypto_driver_pake_get_peer_len`, `psa_crypto_driver_pake_get_peer` and `psa_crypto_driver_pake_get_cipher_suite`.
**Size measured:**
command: `./scripts/code_size_compare.py -o 6aca2c9 -n e6d0038 -a armv8-m -c tfm-medium`
| armclang(6.19) | File Name | Old Size | New Size | Change (Bytes) | Change (%) |
| ---: | ---: | ---: |  ---: |  ---: | ---: |
|  | psa_crypto.o | 19206 | 18936 | -270 | -1.41% |
|  | libmbedcrypto.a | 78278 | 78008 | -270 | -0.34% |
Please tick as appropriate and edit the reasons (e.g.: "backport: not needed …
=> PSA: add guards for PAKE getter functions

ChangeLog.d/driver-only-ecc.txt, ChangeLog.d/extend-pk-opaque-ecc.txt, docs/driver-only-builds.md
Resolves #7452. The most important part is adding some user-oriented documentation about driver-only builds. So far, only covering generalities as well as ECC - the section on hashes is overdue but will be added in another PR.
=> ECPf wrap-up

library/lmots.c, library/lms.c, library/psa_crypto.c, library/rsa.c, library/ssl_ciphersuites.c, library/ssl_msg.c, library/ssl_tls.c, library/ssl_tls12_client.c, library/ssl_tls12_server.c, tests/include/test/macros.h, tests/src/psa_exercise_key.c, tests/src/test_helpers/ssl_helpers.c
Part of #7931. Sorts IAR compile warnings about conversion from enum to int and vice versa. This doesn't handle the case in #7917 which requires further discussion.
=> Add type casts for integer and enum types

library/CMakeLists.txt, library/Makefile, library/ecp_curves.c, library/ecp_curves_new.c, library/ecp_new.c
Make a copy of library/ecp_curves.c to library/ecp_curves_new.c and protect it by the macro guard MBEDTLS_ECP_WITH_MPI_UINT.
This is part of work to refactor the ECP module, without affecting users with temporary code size and performance regressions.
=> [Bignum] Bignum clone ecp curves

scripts/mbedtls_dev/crypto_knowledge.py, tests/scripts/generate_psa_tests.py
Resolves #7812: add support for DH keys to `generate_psa_tests.py`.
=> Enable DH in generate_psa_tests.py

ChangeLog.d/ssl_premaster_secret-empty.txt, include/mbedtls/ssl.h
When all TLS 1.2 support is disabled, `union mbedtls_ssl_premaster_secret` was empty, which is not valid C even if the union is never used. Fixes #6628.
As this is a bit of an edge case and has a simple workaround (don't include `mbedtls/ssl.h` if you aren't going to use it), I haven't gone through the effort of adding a test. If we think this really needs a test, I think we should use the following strategy: have a test program that includes all headers, which is built by a plain `make` — this way we would test that all headers work correctly in all the configurations we test (including ones with no TLS, and ones with picky compilers). We already have such a test program, but it's a C++ program, which we don't build in most configurations. So the implementation of this test would be to …
=> Fix empty union when TLS is disabled

tests/scripts/all.sh
Add 32bit test component for ecp with new bignum interface.
=> Add 32bit test component for ecp with new bignum interface

scripts/code_style.py
Ensure that code_style.py doesn't pick up more files than needed (if development has moved on a lot, `code_style.py -s development` can end up including files changed in development, which are not changed in the range `development..HEAD`.
Also make `-s` default to `-s development`, which is normally what is wanted.
=> Make code_style.py --since more precise

include/mbedtls/md.h, library/md.c, library/md_wrap.h, library/psa_crypto.c, library/psa_crypto_hash.h
Resolves #6996.
Note: did not do the part about `get_size`, as I believe it wouldn't actually save code size in configs with only a few hashes enabled, considering the PSA macros is not optimized in this case but the current code is.
Code size savings (default config, [see below](https://github.com/Mbed-TLS/mbedtls/pull/7811#issuecomment-1600400301)):
- 151 bytes with `MD_C`;
- 152 bytes with only `MD_LIGHT`.
Note: this is in a config with all hashes enabled; we'd expect smaller savings in configs with fewer hashes enabled.
=> Optimize strings in MD

library/ecp.c, library/ecp_curves.c, tests/suites/test_suite_ecp.function
The recent refactoring of ECP bignum is only needed in the new copy file ecp_curves_new.c. 
The ecp_curves.c will be reverted to the commmit 449bd83 which is before the refactoring work.
Re-apply the changes other than the refactoring work to ecp_curves.c.
Use macro guard to tell which copy is used.
=> [Bignum] Bignum cleanup ecp curves

docs/architecture/psa-migration/outcome-analysis.sh
`outcome-analysis.sh` scripts should be run on the same Docker instance that is used by the CI in order to have also tests included by `ssl-opt` script to be executed with the proper OpenSSL/GnuTLS versions.
Unfortunately that Docker instance have an old version of Git (2.7.4) which does not support a command used in this script:
```
git branch --show-current
```
This was added only in Git version 2.22.
As a consequence this PR:
- proposes a "fall back" solution when an old Git version is used
- speeds up the build time by parallelizing the work (not related to the issue above, but beneficial for testing purposes)
=> Improve `outcome-analysis.sh` script

include/mbedtls/mbedtls_config.h, library/ecp_invasive.h, scripts/config.py, tests/scripts/all.sh
These new bignum weren't working, because they use CMake and can't pass options with CFLAGS directly.
This PR fixes them by using config.py as it is less invasive and more standard than using a CMake option.
~The test being added in https://github.com/Mbed-TLS/mbedtls/pull/7988 is correct, as it is using make. I will rebase after https://github.com/Mbed-TLS/mbedtls/pull/7988 is in and make all new bignum tests use config.py~
~Preceding PR: https://github.com/Mbed-TLS/mbedtls/pull/7988~
=> Fix new bignum tests

programs/fuzz/common.c, programs/fuzz/common.h, programs/ssl/ssl_context_info.c, programs/test/udp_proxy.c, scripts/output_env.sh, tests/scripts/all.sh, tests/scripts/generate_test_code.py, tests/scripts/test_generate_test_code.py
Backport of #7968
Needs https://github.com/Mbed-TLS/mbedtls-test/pull/118 to be merged, otherwise the CI won't pass.
Closes #7891
This PR has adds following changes:
- The Ubuntu 16.04 and 22.04 docker images in mbedtls-test have been updated with earliest and latest versions of gcc and clang respectively. This PR adds the components and support functions required for the CI to run these compilers. For FreeBSD, we invoke the function by name so a condition is added to disable the existing test_clang_opt function for Linux.
- Running clang-16 on mbedtls reports warnings of type "-Wstrict-prototypes". This patch fixes these warnings by adding void to functions with no arguments.
=> Backport 2.28: Use earliest latest compilers 2.28

library/ecp.c, programs/fuzz/common.c, programs/fuzz/common.h, programs/ssl/ssl_context_info.c, programs/test/udp_proxy.c, scripts/output_env.sh, tests/scripts/all.sh, tests/scripts/generate_test_code.py, tests/scripts/test_generate_test_code.py
Closes #7891
Needs https://github.com/Mbed-TLS/mbedtls-test/pull/118 to be merged, otherwise the CI won't pass.
This PR has adds following changes: 
- The Ubuntu 16.04 and 22.04 docker images in mbedtls-test have been updated with earliest and latest versions of gcc and clang respectively. This PR adds the components and support functions required for the CI to run these compilers. For FreeBSD, we invoke the function by name so a condition is added to disable the existing test_clang_opt function for Linux. 
- Running clang-16 on mbedtls reports warnings of type "-Wstrict-prototypes". This patch fixes these warnings by adding void to functions with no arguments.
=> Use earliest latest compilers

library/ecp.c, library/psa_crypto.c, tests/src/test_helpers/ssl_helpers.c
Addresses most of the IAR compiler warnings in #7873 (specifically Pe546). Moved declarations of variables to the top of functions.
=> Fix control bypass warnings

ChangeLog.d/fix-win32-llvm-build.txt, library/aesni.c
Merge master into development, so that development contains the PR that accidentally went into master instead of development.
=> Sync development with accidental merge directly onto master

library/ecp.c
This fixes the first of the compiler errors in #7873.
=> Fix IAR warning about unnecessary type quantifier

ChangeLog.d/00README.md
=> Backport 2.28: Clarify changelog not needed for compiler warnings

ChangeLog.d/00README.md
Clarify the guidance on requiring a Changelog update for compiler warning fixes.
=> Clarify changelog not needed for compiler warnings

library/aes.c, library/ctr_drbg.c
The link to the DRBG paper points to the March 2007 version, the same as the original link (rather than the latest version).
The amended Rijndael paper has a two-page "Note on naming" prefix.
Fixes #7193
=> Backport 2.28: Update links to Rijndael paper and NIST SP 800-90 DRBGs

library/aes.c, library/ctr_drbg.c
The link to the DRBG paper points to the March 2007 version, the same as the original link (rather than the latest version).
The amended Rijndael paper has a two-page "Note on naming" prefix.
Fixes #7193
=> Update links to Rijndael paper and NIST SP 800-90 DRBGs

include/mbedtls/mbedtls_config.h
The documentation of  `MBEDTLS_PSA_CRYPTO_CONFIG` is obsoletely negative.
=> MBEDTLS_PSA_CRYPTO_CONFIG is ready for production

library/bignum.c, library/bignum_core.c
Miscellaneous code size wins in bignum.c and bignum_core.c, totalling 108 bytes saving under armclang -Oz.
=> Bignum codesize misc

ChangeLog.d/improve-doc-on-ecp-curve-optimized-representation.txt, include/mbedtls/ecp.h
Backport of https://github.com/Mbed-TLS/mbedtls/pull/6999.
The changes made on #6999 are:
1. mbedtls_ecp_group_a_is_minus_3(): 2.28 does not have MBEDTLS_PRIVATE. 
2. Added macro inline in ecp.h.
=> Backport 2.28: Doc: Add note on special use of A in ecp group structure

ChangeLog.d/improve-doc-on-ecp-curve-optimized-representation.txt, include/mbedtls/ecp.h, library/ecp.c
ECP implementation sets A to NULL in structure mbedtls_ecp_group for optimizing Short Weierstrass curves with A = -3.
We should warn on this in the document, as using domain parameters in external program is likely to encounter errors if not
noticing this.
Fixes #8045
=> Doc: Add note on special use of A in ecp group structure

library/debug.c
The purpose of this PR is to be able to use the `debug` module for printing EC points even when BIGNUM_C is not available.
Resolves #7759
=> Driver-only ECC: TLS: rm uses of mbedtls_debug_print_mpi

tests/include/test/macros.h, tests/src/psa_exercise_key.c, tests/suites/test_suite_asn1write.function, tests/suites/test_suite_psa_crypto.function, tests/suites/test_suite_psa_crypto_se_driver_hal.function, tests/suites/test_suite_psa_crypto_slot_management.function
=> [Backport 2.28] Add TEST_FAIL macro for tests

tests/include/test/macros.h, tests/src/psa_exercise_key.c, tests/src/test_helpers/ssl_helpers.c, tests/suites/test_suite_alignment.function, tests/suites/test_suite_asn1write.function, tests/suites/test_suite_bignum.function, tests/suites/test_suite_psa_crypto.function, tests/suites/test_suite_psa_crypto_driver_wrappers.function, tests/suites/test_suite_psa_crypto_se_driver_hal.function, tests/suites/test_suite_psa_crypto_slot_management.function, tests/suites/test_suite_shax.function, tests/suites/test_suite_x509parse.function
The TEST_ASSERT macro was being used in places where we wanted to just assert false, using the pattern `TEST_ASSERT(!"message")` which expanded to a tautology in the if statement, so the new macro ASSERT_FALSE is being used in these instances.
=> Add TEST_FAIL macro for tests

include/mbedtls/check_config.h, include/mbedtls/pk.h, tests/scripts/all.sh, tests/suites/test_suite_x509parse.function, tests/suites/test_suite_x509write.function
This PR is the continuation of #7989 and it enables also X509 testing.
Depends on #7989 
Resolves #7755
=> driver-only ECC: BN.x509 testing

tests/scripts/all.sh
[component_test_crypto_full_no_cipher doesn't bring any extra value given the existence of component_test_full_no_cipher](https://github.com/Mbed-TLS/mbedtls/pull/5794#discussion_r1289868953).
=> Remove redundant test component component_test_crypto_full_no_cipher

library/ssl_tls13_generic.c, tests/scripts/all.sh, tests/scripts/analyze_outcomes.py, tests/ssl-opt.sh
This PR is the continuation of #7992 and it enables also TLS and key exchanges as well as `ssl-opt` testing. 
Depends on #7992 and #7999
Resolves #7756
=> driver-only ECC: BN.TLS testing

ChangeLog.d/fix-aes-cbc-iv-corruption, library/aes.c
If passed a zero length, AES CBC could potentially corrupt the passed in IV by memcpying it over itself. Although this might be ok with some more recent compilers, its not for every compiler we support. Found by coverity.
=> Fix potential corruption of IV for AES CBC with zero length

tests/suites/test_suite_bignum_mod.function
If any of the tests inside the loop were to fail, execution would jump to exit, and ref_buf would be leaked. Found by Coverity.
=> Fix resource leak in bignum test failure case

ChangeLog.d/fix-empty-enum.txt, library/cipher_wrap.c
Fix compile fail for minimal configurations. Fixes #7625
=> Fix compile fail for empty enum in cipher_wrap

ChangeLog.d/use_heap_rsa_signature.txt, library/pk_wrap.c
[mbedtls_pk_psa_rsa_sign_ext](https://github.com/Mbed-TLS/mbedtls/blob/51ed3139d1f833c0698c834e1869747f97bcd432/library/pk_wrap.c#L293) function allocates a buffer of maximum size 5679 bytes ([MBEDTLS_PK_RSA_PRV_DER_MAX_BYTES](https://github.com/Mbed-TLS/mbedtls/blob/51ed3139d1f833c0698c834e1869747f97bcd432/library/pkwrite.h#L66)) on the stack to store DER encoded private key. 
This increased stack usage significantly for RSA signature operations when `MBEDTLS_PSA_CRYPTO_C` is defined.
This issue was discovered when adding support for EAP-TLS 1.3 ([rfc9190](https://datatracker.ietf.org/doc/html/rfc9190)).
=> rsa_signature: Use heap memory to allocate DER encoded RSA private key

CMakeLists.txt, library/aes.c, library/common.h, library/constant_time.c, library/entropy_poll.c, library/psa_crypto.c, library/psa_crypto_storage.h, library/x509_crt.c
Applied the same change as in mbed-crypto for using this as a sub project with the IAR toolchain. Use __asm generic ,and avoid empty enum. Avoid declaration of array with null size.
Note: This is a porting of the original patch contributed to trusted-firmware-m at https://git.trustedfirmware.org/TF-M/trusted-firmware-m.git/tree/lib/ext/mbedcrypto/0001-BUILD-Update-For-IAR-support.patch
=> Small fixes for IAR support

scripts/code_size_compare.py, scripts/mbedtls_dev/logging_util.py, tests/scripts/audit-validity-dates.py
In order to show code size changes between `development` and `latest commit` in a PR, this PR adds support to show results in a marddown format. We wont' show `total` as code size anymore, it's been splitted as `text,data` as this is what we care about in code-size-optimization.
Furthermore, the code is re-constructed as 
- `CodeSizeBuildInfo` to only infer build commands based on input arguments, like architecture, config.
- `CodeSizeCalculator` to calculate code size for a specified commit.
- `CodeSizeGenerator` to generate code size record and comparison result as a parser for a measurement tool.
- `CodeSizeComparison` to control the whole process of workflow.
**Example of usage:**
E.g. `./scripts/code_size_compare.py -o bc775c4~100  -n bc775c4 -a armv8-m -c tfm-medium --markdown …
=> code_size_compare.py: preparation work to show code size changes in PR comment

.travis.yml, ChangeLog.d/add-aes-hardware-only-option.txt, include/mbedtls/check_config.h, include/mbedtls/mbedtls_config.h, library/aes.c, library/aesce.c, library/aesce.h, library/aesni.c, library/aesni.h, library/gcm.c, library/padlock.c, library/padlock.h, tests/scripts/all.sh
Add new option(`MBEDTLS_AES_USE_HARDWARE_ONLY `) to disable built-in AES implementation.
For time being, there are only two implementations in each known architecture. This PR just disable runtime detection to meet the requirement. When runtime detection was disabled and accelerator is enabled, built-in implementation become dead code, compiler will remove those dead code.
Fixes #7141 
=> AES: Add accelerator only mode

ChangeLog.d/fix-a-few-unchecked-return.txt, library/bignum.c, library/ecdsa.c, library/rsa_internal.c
Patches in this PR are identical with https://github.com/Mbed-TLS/mbedtls/pull/8017.
=> Backport 2.28: Fix a few unchecked return values

ChangeLog.d/fix-a-few-unchecked-return.txt, library/bignum.c, library/ecdsa.c, library/rsa_alt_helpers.c
I found a few function calls of which return value is not checked.
Not sure if these checks are all really needed.
=> Fix a few unchecked return values

library/aes.c, library/aesce.c, library/aesce.h, library/gcm.c
`mbedtls_aesce_has_support()` is called a lot during AES - e.g., `selftest aes` calls it 120,000 times. Avoid calling `getauxval` every time. This improves the overall time to run `selftest aes` by 2.5%. `benchmark aes_ccm` shows an improvement of 4.4%.
**Gatekeeper notice**: Needs https://github.com/Mbed-TLS/mbedtls/pull/7384 to be merged first, [then CI should pass](https://github.com/Mbed-TLS/mbedtls/pull/8035#issuecomment-1665613398).
=> Make mbedtls_aesce_has_support more efficient

tests/data_files/Makefile
server1.crt.der needed to be changed to parse_input/server1.crt.der to match target earlier in the makefile. Prior the makefile was unable to build.
=> Fix server1.crt.der in tests/data_files/Makefile

library/psa_crypto_pake.c
I'm not entirely sure what happened here, and the last person to touch this code is not around to ask anymore, so I am opening this to attract opinion as much as anything.
I'm also not entirely happy with this - whilst I fixed the dead code issue, I am presuming here that these errors do not require the calling of `mbedtls_psa_pake_abort()`, which I have to say I am unsure about.
Given we are clearly not testing these paths, should we be?
I'm going to be away, but wanted to get this out here - feel free to take over this PR, if you wish, otherwise I will continue with it on return.
=> Fix logical dead code found by Coverity

library/bignum.c
Trivial backport of https://github.com/Mbed-TLS/mbedtls/pull/8053
=> Backport 2.28: mbedtls_mpi_exp_mod: remove spurious copy of the output variable

.travis.yml, doxygen/mbedtls.doxyfile, include/mbedtls/mbedtls_config.h, include/mbedtls/platform.h, programs/test/selftest.c, tests/scripts/all.sh, tests/suites/test_suite_platform.data, tests/suites/test_suite_platform.function
Update the documentation on the fact that `mbedtls_calloc` also zeroizes the buffer.
=> Document mbedtls_calloc zeroization

library/bignum.c
The current version of `mbedtls_mpi_exp_mod` was [originally](https://github.com/Mbed-TLS/mbedtls-restricted/pull/975) (private link) written using `X` as the accumulator, and we didn't fully handle the consequences of using a table entry as the accumulator instead. The result was a misleading comment and a spurious function call.
Found when [analyzing the consequences of failing the copy due to insufficient memory](https://github.com/Mbed-TLS/mbedtls/pull/8017#discussion_r1290141537) — none, since that copy is useless.
=> mbedtls_mpi_exp_mod: remove spurious copy of the output variable

include/mbedtls/net_sockets.h
=> [Backport 2.28] Reword the description of `mbedtls_net_free()`

include/mbedtls/net_sockets.h
This makes it clearer that the context itself is not being freed.
Fixes #2544.
=> Reword the description of `mbedtls_net_free()`

ChangeLog.d/psa_crypto_user_config_file.txt, include/mbedtls/build_info.h, include/mbedtls/config_psa.h, include/psa/crypto_config.h, programs/test/generate_cpp_dummy_build.sh, tests/include/test/drivers/config_test_driver.h
These are minor things from https://github.com/Mbed-TLS/mbedtls/pull/7615 which don't have much impact, but will make the actual split easier. No semantic change except that "Fix condition to include MBEDTLS_PSA_CRYPTO_USER_CONFIG_FILE" fixes how a marginal configuration is handled.
This is step 1 of 3+. [Next steps](https://github.com/Mbed-TLS/mbedtls/pull/7615#issuecomment-1686447123): actually split `config_psa.h`, then fix some of the problems with the ordering.
=> Prepare to split config_psa.h

scripts/mbedtls_dev/crypto_data_tests.py, scripts/mbedtls_dev/psa_information.py, tests/CMakeLists.txt, tests/Makefile, tests/scripts/generate_psa_tests.py, tests/suites/test_suite_psa_crypto_low_hash.function
This is one step on the way to https://github.com/Mbed-TLS/mbedtls/issues/7801 — see the issue for the long-term goal.
In this pull request:
* I introduce a new framework to generate test data for cryptographic operations through the PSA API (or not, for that matter), building on the existing work to generate test data for key creation. This is still the beginning, I expect to do more refactoring later when we figure out what our needs are.
* The test data generator only supports hashes for now, and only for a subset of algorithms (the ones that don't rely on any third-party Python library or a specific version of Python or openSSL).
* I implement some basic tests for hashes: mostly nominal behavior, but also calling a finish function with a larger output buffer, which is the equivalent …
=> Start testing the PSA built-in drivers: hashes

CONTRIBUTING.md, README.md
We had information in both `README.md` and `CONTRIBUTING.md` about Mbed TLS licensing, but the information in `CONTRIBUTING.md` was missing that authors still need to accept that their contributions may be distributed under both Apache 2.0 and GPLv2-or-later.
Move all but the most high-level “Mbed TLS files are provided under the Apache-2.0 license” statement to `CONTRIBUTING.md`, and tidy up the text a bit.               
Also clarify a use of the phrase "the project" while here.
=> Single source of truth for licensing

ChangeLog.d/fix-iar-compiler-warnings.txt
Changelog entry for recent IAR compiler warning fixes.
=> Add changelog entry for 2.28 IAR warning fixes

tests/scripts/analyze_outcomes.py
=> Implement allowlist of test cases that are legitimately not executed

ChangeLog.d/fix-iar-compiler-warnings.txt, library/constant_time_impl.h
IAR warned on unneeded "const" keywords, so removed. Changelog added for all previous changes for IAR support.
=> Remove type qualifier in assignment casts

library/constant_time.c, library/constant_time_impl.h, library/constant_time_internal.h, tests/scripts/all.sh
Size/performance optimisation for Arm constant-time code. Saves 100b with armclang -Oz under TF-M config (`mtest -S`).
=> Arm assembly implementation of constant time primitives

3rdparty/p256-m/p256-m/p256-m.c
The optimised assembly in p256-m does not support aarch64. With this PR, it compiles cleanly for Thumb 1, Thumb 2, arm and aarch64 (tested with `mtest MBEDTLS_P256M_EXAMPLE_DRIVER_ENABLED thumb1 thumb2 arm aarch64 clang gcc`).
=> Disable p256-m asm on aarch64

library/sha3.c, tests/suites/test_suite_shax.function
=> Ensure mbedtls_sha3_finish zeroizes the context

tests/compat.sh, tests/scripts/check_test_cases.py
Backport of #7165 
This PR adds support to list all potential test cases in `compat.sh` by `./tests/compat.sh --list-test-case`. Therefore, `check_test_cases.py` is able to collect those test case description in order to report duplicated test cases.
To analyze outcome by `analyze_outcomes.py`, the test case description should be identical with `OUTCOME.CSV` in #7136 . Please consider those two PRs together.
=> Backport 2.28: check_test_cases.py: support to collect test cases for compat.sh

tests/suites/test_suite_psa_its.function
=> [Backport 2.28] Fix unnecessary header prefix in tests

.travis.yml
On the advice of travis support, try regenerating the coverity scan token to see if that fixes the connection to coverity scan
On the advice of travis support, try regenerating the coverity scan token to see if that fixes the connection to coverity scan
=> Regenerate coverity scan token

tests/suites/test_suite_common.function, tests/suites/test_suite_psa_its.function
Remove unnecessary `../library` prefix from test suite includes. This makes the tests repo-agnostic between the mbedtls and psa-crypto repos.
=> Fix unnecessary header prefixes in tests

tests/suites/test_suite_ecp.function
Fixing a minor issue on `ecp_mod_p_generic_raw`
=> [BigNum] test_suite_ecp: Fixed curve bit-length.

ChangeLog.d/initialize-struct-get-other-name.txt, library/x509_crt.c, tests/suites/test_suite_x509parse.function
Small but not trivial backport of #8095.
Main difference: Functions that deal with `HardwareModuleName` are in `x509_crt.c` not in `x509.c` as in `development`
=> [Backport 2.28] Coverity fix: Set `type_id` in `x509_get_other_name()`

ChangeLog.d/initialize-struct-get-other-name.txt, library/x509.c, tests/suites/test_suite_x509parse.function
When parsing a subject alternative name of type otherName, retain the type-id field of the otherName. Previously this was not copied to the `mbedtls_x509_san_other_name` struct when it should have been.
This fixes an issue found by Coverity
=> Coverity fix: Set `type_id` in `x509_get_other_name()`

scripts/mbedtls_dev/build_tree.py, scripts/mbedtls_dev/psa_storage.py, tests/scripts/all.sh, tests/scripts/test_psa_compliance.py
Enable the scripts to be used either in Mbed TLS or in the PSA Cryptography repository.
Fixes https://github.com/Mbed-TLS/psa-crypto/issues/23
Specifically:
* Change root directory detection logic in several places
* Change filepaths in several places dependent on which repo we are in
=> Miscellaneous changes to scripts for PSA-Crypto enablement

ChangeLog.d/config_psa-include-order.txt
This is just a changelog entry for an issue #7420 that we're resolving in pieces. The next release will have fixed the user-visible part, so we should announce it in the changelog.
This is part of a bigger issue https://github.com/Mbed-TLS/mbedtls/issues/7609 which is still pending since there are still configurations that are not handled correctly. However we have essentially resolved #7420:
* https://github.com/Mbed-TLS/mbedtls/pull/7611 moved the inclusion of `config_psa.h` in `build_info.h` as requested.
* https://github.com/Mbed-TLS/mbedtls/pull/7650 constitutes a non-regression test via the TF-M reference configuration.
* #7420 also requests a comment in `build_info.h` to explain the inclusion order. This is important: after https://github.com/Mbed-TLS/mbedtls/pull/7611, the …
=> Announce that #7420 is fixed

ChangeLog.d/fix-tls-padbuf-zeroization, library/ssl_tls.c
Fix an issue whereby the pad buffer was not completely zeroized in some cases during TLS handshake.
=> Fix TLS pad buffer zeroization

library/platform_util.c
Strengthen `mbedtls_platform_zeroize` to further protect against being optimised away.
=> Add more protection to mbedtls_platform_zeroize

include/mbedtls/platform_util.h, tests/configs/config-wrapper-zeroize-memset.h, tests/configs/user-config-zeroize-memset.h, tests/scripts/all.sh, tests/suites/test_suite_pkwrite.function
Add the ability to verify mbedtls_platform_zeroize() calls with -Wsizeof-pointer-memaccess, and fix a problem it finds in the tests.
=> Backport 2.28: Check mbedtls_platform_zeroize() calls

include/mbedtls/platform_util.h, tests/configs/config-wrapper-zeroize-memset.h, tests/configs/user-config-zeroize-memset.h, tests/scripts/all.sh, tests/suites/test_suite_pkwrite.function
Add the ability to verify mbedtls_platform_zeroize() calls with -Wsizeof-pointer-memaccess, and fix a problem it finds in the tests.
=> Check mbedtls_platform_zeroize() calls

include/mbedtls/bignum.h, library/bignum_core.c, library/common.h, library/x509_crt.c
Ensure we compile cleanly under clang with `-Wunreachable-code`. Under gcc, this warning has no effect (see https://gcc.gnu.org/legacy-ml/gcc-help/2011-05/msg00360.html ).
=> Fix clang warnings about unreachable code

library/sha3.c
=> Remove always-false null pointer check in sha3.c that Coverity complains about

library/md5.c, library/ripemd160.c, library/sha1.c, library/sha256.c, library/sha512.c
Ensure that all hash functions perform zeroization when finish is called.
=> Ensure all md_<hash>_finish functions perform zeroization

include/mbedtls/config_adjust_legacy_from_psa.h, library/pkwrite.c
Fix one minor issue I came across while working on the psa-crypto repository.
=> One minor fix

programs/test/CMakeLists.txt, scripts/generate_query_config.pl
In case of an out-of-tree build with the CMake build system the path to crypto_config.h has to be defined as the path to mbedtls_config.h is. Add this possibility to generate_query_config.pl.
I came across that while investigating on the test framework.
=> Fix query_config.c generation with CMake build system

library/bignum.c, library/constant_time_impl.h, library/constant_time_internal.h
Constant-time x86 and x86-64 asm. This saves code size and improves performance over the plain C implementation.
The final part of #7578 and #7579
=> Constant time asm for x86 and x86-64

tests/suites/test_suite_pkcs7.function
Move the initialisation of the pkcs7 object to before the first possible test failure, otherwise failure in those tests could result in an uninitialised pointer being free'd. Found by coverity.
=> Prevent potential use of uninitialised data in pkcs7 tests

library/ssl_msg.c
=> Use the correct variable when tracking padding length

3rdparty/p256-m/p256-m/p256-m.c
Resolve https://github.com/Mbed-TLS/mbedtls/issues/7883
=> p256-m: Use the zeroize function from Mbed TLS

programs/test/cmake_package/CMakeLists.txt, programs/test/cmake_package_install/CMakeLists.txt, programs/test/cmake_subproject/CMakeLists.txt
Update the minimum version in the CMake tests CMakeLists.txt to match the main CMakeLists.txt.
As of cmake 3.27.4 (and possibly prior) CMake is now emitting warnings that support for CMake versions less than 3.5 will be dropped in a future version. Our main CMakelists.txt is fine, as the minimum version is 3.5.1, however some of the other CMakeLists.txt used for the CMake tests had not been updated.
I cannot see any features used within these that require the older version, this is just the minimum version as used to be, so I think these need updating, and especially before any new LTS is made.
=> Update CMake minimum version(s) to match main CMakeLists.txt

include/mbedtls/build_info.h, library/aes.c, library/aesce.c, library/aesce.h, library/aesni.h, library/gcm.c, library/padlock.c, library/padlock.h
There are many place to detect target architecture, this PR add utility macros for this purpose.
relative to: #7078 .
see also :https://github.com/Mbed-TLS/mbedtls/pull/7384#discussion_r1296594488
preceding-PR: #7384 
=> Add architecture detection macros

include/mbedtls/config_psa.h
=> Backport 2.28: Add comment about HKDF in config_psa.h

library/ssl_msg.c
Follow-up to #8189 - clean up some slightly awkward use of the ct interface.
=> Improve use of ct interface in mbedtls_ssl_decrypt_buf

library/psa_crypto.c, library/ssl_cache.c, tests/suites/test_suite_psa_crypto.function
```
mbedtls/library/psa_crypto.c:3428:30: error: variable 'default_iv_length' may be uninitialized when used here [-Werror,-Wconditional-uninitialized]
memcpy(iv, local_iv, default_iv_length);
^~~~~~~~~~~~~~~~~
mbedtls/library/psa_crypto.c:4646:36: error: variable 'required_nonce_size' may be uninitialized when used here [-Werror,-Wconditional-uninitialized]
memcpy(nonce, local_nonce, required_nonce_size);
^~~~~~~~~~~~~~~~~~~
mbedtls/library/ssl_cache.c:309:54: error: variable 'session_serialized_len' may be uninitialized when used here [-Werror,-Wconditional-uninitialized]
mbedtls_platform_zeroize(session_serialized, session_serialized_len);
^~~~~~~~~~~~~~~~~~~~~~
```
The warnings are false positive, but treated as errors and prevent compiling on Windows with LLVM Clang.
=> Fix llvm error: variable 'default_iv_length' and other may be used uninitialized

library/psa_crypto.c
Backport of https://github.com/Mbed-TLS/mbedtls/pull/7210
```
mbedtls/library/psa_crypto.c:3428:30: error: variable 'default_iv_length' may be uninitialized when used here [-Werror,-Wconditional-uninitialized]
memcpy(iv, local_iv, default_iv_length);
^~~~~~~~~~~~~~~~~
```
The warning is false positive, but treated as error and prevents compiling on Windows with LLVM Clang.
=> mbedtls-2.28: Fix llvm error: variable 'default_iv_length' may be used uninitialized

docs/driver-only-builds.md, tests/scripts/all.sh, tests/scripts/analyze_outcomes.py
This PR:
- extends test scenario introduced by the #7754 + #7755 + #7756 series by accelerating also FFDH together with ECC.
- improves the `driver-only-builds.md` documentation as requested by the issue
Resolves #8005
=> Test with ECC and FFDH accelerated and no bignum

library/ssl_client.c, library/ssl_tls.c
Fix a couple of warnings that emerge when compiling with `clang-18 -std=c23`
=> Fix some clang-18 warnings

ChangeLog.d/fix-log-level-msg.txt, include/mbedtls/version.h, library/ssl_client.c, library/version.c, programs/test/cmake_package/cmake_package.c, programs/test/cmake_package_install/cmake_package_install.c, tests/suites/test_suite_version.function
This is the copy PR of the previous https://github.com/Mbed-TLS/mbedtls/pull/7314
somehow I cannot re-open that.
This PR resolve https://github.com/Mbed-TLS/mbedtls/issues/6765 issue. During one successful DTLS handshake, user seeing many message caused by wrong log level.
=> Fixes log level for got supported group message

include/mbedtls/mbedtls_config.h
Add missing requirements MBEDTLS_SSL_PROTO_TLS1_2 to option MBEDTLS_SSL_RENEGOTIATION documentation.
Make documentation consistent with tests done in check_config.h 
=> Fix issue #8215 : add missing requires documentation in mbedtls_config.h

programs/ssl/dtls_client.c, programs/ssl/dtls_server.c, programs/ssl/ssl_server2.c
Remove coverity warnings on unused values.
=> Remove unneeded setting of ret from ssl programs

programs/ssl/dtls_client.c, programs/ssl/dtls_server.c, programs/ssl/ssl_server2.c
Remove coverity warnings on unused values. Trivial backport of #8217 
=> Backport 2.28: Remove unneeded setting of ret from ssl programs

tests/configs/user-config-for-test.h, tests/configs/user-config-malloc-0-null.h, tests/scripts/all.sh, tests/suites/test_suite_ssl.function
This is a partial backport of #7961. I have not added `MBEDTLS_PSA_CRYPTO_CONFIG` to the full config because I don't think it's worth doing a major overhaul of the tested configurations in 2.28 at this point. I also didn't add a `u` suffix to size constants because it's potentially disruptive. I backported the other changes that were applicable.
Detailed backport log:
* "Remove duplicated component": N/A
* "Remove comments that duplicate the 'msg' call just below": yes, slightly different set of affected components
* "Fix typo in function name": N/A
* "Fix inconsistencies in no-chachapoly test": yes
* "Make malloc-0-null a user config file": yes
* "Enable MBEDTLS_PSA_CRYPTO_CONFIG in "config.py full"": no
* "When subtracting classic symbols from full, turn off PSA_CRYPTO_CONFIG": no
* …
=> Backport 2.28: parts of #7961

CMakeLists.txt, Makefile, library/Makefile, programs/Makefile, scripts/prepare_release.sh, tests/Makefile
* `make GEN_FILES=` now avoids rebuilding the configuration-independent generated files if not needed, similar (but not identical) to `cmake -DGEN_FILES=OFF`.
* In development, we default to re-generating configuration-independent files based on their dependencies. In releases, we bundle the files and avoid rebuilding them. Run `scripts/prepare_release.sh` to switch from development mode to release mode.
Resolves https://github.com/Mbed-TLS/mbedtls/issues/5432, in combination with adding “run `scripts/prepare_release.sh`” to the release preparation instructions.
Status: ready.
Fixes #5432 
=> Generated files off in release

ChangeLog.d/p256-m.txt, docs/psa-driver-example-and-guide.md, include/mbedtls/mbedtls_config.h
I have reviewed the p256-m implementation and integration. The conclusion of my review is:
* The upstream code is very well-written and approved with flying colors. (There was only one upstream bug, in the selection of assembly, listed below.)
* There were a few things missing in the integration (listed below), once those are fixed the integration is fine.
* The [readme needs some work](https://github.com/Mbed-TLS/mbedtls/issues/7882). Not a blocker for release.
* [zeroize was not integrated](https://github.com/Mbed-TLS/mbedtls/issues/7883). Resolved by https://github.com/Mbed-TLS/mbedtls/pull/8166.
* Needs to be tested on the CI. Will be resolved by https://github.com/Mbed-TLS/mbedtls/pull/8041.
* I have not fully reviewed whether the guards around the assembly implementations are …
=> Declare p256-m as ready for production

tests/scripts/all.sh
Workaround for https://github.com/Mbed-TLS/mbedtls/issues/8229
=> Work around a race condition in parallel builds

3rdparty/p256-m/p256-m/p256-m.c, 3rdparty/p256-m/p256-m/p256-m.h, 3rdparty/p256-m/p256-m_driver_entrypoints.c, 3rdparty/p256-m/p256-m_driver_entrypoints.h, include/mbedtls/pk.h, scripts/data_files/driver_jsons/driverlist.json, scripts/data_files/driver_jsons/p256_transparent_driver.json, tests/scripts/all.sh, tests/scripts/analyze_outcomes.py, tests/suites/test_suite_psa_crypto.function
Resolves #8006.
Note: will need rebasing if #8203 gets merged first.
~Built on top of~ Supersedes #8032 ~itself built on top of #7992 (merged)~.
One problem that was uncovered by #8032 is that the p256-m driver does not provide all entry points we'd want in order to be able to get rid of `ECP_C` and `BIGNUM_C`, namely it's missing the `import_key` and `export_public_key` entry points. This PR solve that:
- Before adding the entry points, we need to expand the public API in `p256-m.h` a bit.
- Then we add the entry points.
- Then add a JSON file, as unlike the entry points that were introduced before, those have programmatic generation of the driver wrappers.
- Then a few extra clean-ups in the p256-m driver while at it.
=> Test TF-M config with p256-m driver

library/pkwrite.c
I'm sure some compiler/static analysis tool will complain about these at some point.
Oh, wait:
```
Microsoft (R) C/C++ Optimizing Compiler Version 19.29.30140 for x64
Copyright (C) Microsoft Corporation.  All rights reserved.
pkwrite.c
D:\home\tom\projects\mbedtls\master\library\pkwrite.c(737) : error C4702: unreachable code
```
=> Remove unused variable and unreachable return from mbedtls_pk_write_key_der()

library/pkparse.c
=> fix cast warning

library/cipher_wrap.c
A tiny PR to remove some `192-` and `256-bit` AES ciphers under `MBEDTLS_AES_ONLY_128_BIT_KEY_LENGTH`.
=> AES 128bit only: add guards in cipher_wrap.c

configs/tfm_mbedcrypto_config_profile_medium.h
This brings our copy of the TF-M config closer to the upstream version by removing PK, as per https://git.trustedfirmware.org/TF-M/trusted-firmware-m.git/tree/lib/ext/mbedcrypto/mbedcrypto_config/tfm_mbedcrypto_config_profile_medium.h?id=8a5469cb2469cbddc2977003aa4b6e480503a374
Also, set `MBEDTLS_MD_C`, because this is required by `MBEDTLS_HKDF_C` (which they do set). (Leaving it unset generally works thanks to `config_adjust_legacy_from_psa.h`, but if `PSA_WANT_ALG_DETERMINISTIC_ECDSA` is unset then it doesn't get set automatically and therefore breaks).
Please refer to the [contributing guidelines](https://github.com/Mbed-TLS/mbedtls/blob/development/CONTRIBUTING.md), especially …
=> Update TF-M config

.travis.yml
Remove all travis builds, except for the coverity_scan push. This has to be done in time for our paid plan to run out at the end of the month. Travis has already been set as not required for green CI, so this should not affect anyone.
=> Remove all travis builds except for coverity_scan

.travis.yml
Remove all travis builds except for the coverity_scan push. This needs to be done prior to our paid plan expiring at the end of the month.
Backport of #8244 
=> [Backport 2.28] Remove all travis builds except for coverity_scan

library/pkwrite.c
(Note: previous contents of this comment were the contents of the `library/pkwrite.c` file itself; they have been deleted)
=> Fix MSVC error C4703 about possibly uninitialized variable in pkwrite.c

include/mbedtls/aesni.h, include/mbedtls/padlock.h, library/aes.c, library/padlock.c
Fix: #8168 
This PR does a clean-up of the arch detection and implementation selection macros in `include/mbedtls/aesni.h`, similar to #7384. This would fix the issue when building with MSVC for ARM/ARM64 target if `MBEDTLS_AESNI_C` is not disabled.
=> 2.28: Fix AESNI selection

.travis.yml
Re-add the python dependancies installation to Travis CI, also correct 'distro to 'dist' and update ubuntu to focal in line with previous Travis settings. Too much got removed when disabling travis and the Coverity scan build was failing on 'make generated-files', due to lack of installed python dependencies.
Trivial backport of #8253 
=> [Backport 2.28] Re-add python install of requirements to Travis CI.

.travis.yml
Re-add the python install of dependencies to Travis. Also correct 'distro to 'dist' and update ubuntu to focal in line with previous Travis settings. 
Too much got removed when disabling travis and the Coverity scan build was failing on 'make generated-files', due to lack of installed python dependencies.
=> Re-add python install of requirements to Travis CI

library/CMakeLists.txt, programs/test/cmake_package/CMakeLists.txt, programs/test/cmake_package_install/CMakeLists.txt, tests/scripts/all.sh
Fix a build error from #7980 when building out-of-source with CMake and generating files
Now that we are generating `psa_crypto_driver_wrappers.h`, we need to pass `build/library` as an include directory.
=> Add CMake include path for generated header

library/psa_crypto.c, scripts/data_files/driver_templates/psa_crypto_driver_wrappers.h.jinja
Fix broken error handling in psa_driver_wrapper_xxx_hash_get_num_ops
Does this count as an API break?
=> Fix error handling in psa_driver_wrapper_xxx_hash_get_num_ops

ChangeLog.d/mbedtls_ecdsa_can_do-unconditional-define.txt, library/ecdsa.c
Straightforward backport of https://github.com/Mbed-TLS/mbedtls/pull/7499
Testing manually:
```
./config.py set MBEDTLS_ECDSA_SIGN_ALT
make -C programs pkey/ecdsa
```
Expected: a link error about missing `mbedtls_ecdsa_sign` (when you enable `MBEDTLS_ECDSA_SIGN_ALT`, you have to provide that function).
Actual before this fix: also missing `mbedtls_ecdsa_can_do`
=> Backport 2.28: Bug Fix: mbedtls_ecdsa_verify_restartable fails with ECDSA_SIGN_ALT

ChangeLog.d/driver-ffdh.txt
It was jumping directly to "driver support" and omitting the first step of "PSA support".
This provides the missing entry for #6010.
=> Fix ChangeLog entry for FFDH in PSA

ChangeLog.d/MBEDTLS_ERR_SSL_CACHE_ENTRY_NOT_FOUND.txt
https://github.com/Mbed-TLS/mbedtls/pull/7298 wasn't just cleanup, it fixed a bug, so it needs a changelog entry.
And maybe a backport?
=> Changelog entry for 7298

ChangeLog.d/MBEDTLS_ERR_SSL_CACHE_ENTRY_NOT_FOUND.txt, include/mbedtls/ssl.h, include/mbedtls/ssl_cache.h, library/error.c, library/ssl_cache.c
This is a backport of the bug fix in https://github.com/Mbed-TLS/mbedtls/pull/7298: functions in the `ssl_cache` module were returning 1 on many error conditions, unlike the rest of the library where errors are conveyed by an error code that's always negative.
There was significant refactoring in the `ssl_cache` module in 3.x, so cherry-picking the commits led to significant conflicts, and instead I mostly re-did the same changes:
* Create a new error code — it had to have a different number in 2.28 because the one from 3.5 is taken in 2.28. Also, in 2.28, `error.c` needs to be updated.
* Change functions to return a negative error code — I searched for `return 1` or `ret = 1` and changed to what seemed like sensible values.
* Documentation update — I copied the text we used in 3.5.
* In …
=> Backport 2.28: ssl_cache: misc improvements

ChangeLog.d/rename_psa_crypto_driver_wrappers.txt
Added a missing changelog for renaming an auto-generated file
=> Changelog: Added entry for psa_crypto_driver_wrappers rename

tests/scripts/check-generated-files.sh
This PR updates check-generated-files.sh to check/include the newly added `psa_crypto_driver_wrappers_no_static.c` file
=> Updating check-generated-files

3rdparty/CMakeLists.txt, ChangeLog.d/fix-cmake-3rdparty-custom-config.txt
Backport of #8284.
Main difference: The custom config propagation is not needed due to a difference in the way `3rdparty` works in 2.28.
=> [Backport 2.28] CMake: fix build with 3rdparty module enabled through a custom config

3rdparty/CMakeLists.txt, 3rdparty/everest/CMakeLists.txt, 3rdparty/p256-m/CMakeLists.txt, ChangeLog.d/fix-cmake-3rdparty-custom-config.txt
Fixes #8165
@adeaarm confirms that this fixes the problem for TF-M
=> CMake: fix build with 3rdparty module enabled through a custom config

library/pkcs12.c, tests/suites/test_suite_pkcs12.data
This PR resolves #8052 by replacing all the ciphers steps used in `pkcs12` module with a single call to `mbedtls_cipher_crypt()`.
=> PKCS12: use one-shot API

3rdparty/everest/CMakeLists.txt, 3rdparty/p256-m/CMakeLists.txt, ChangeLog.d/fix-3rdparty-target-prefix.txt
Use the correct names qualified by `MBEDTLS_TARGET_PREFIX`. This was accidentally not merged into the 3.5 release.
=> Fix 3rdparty target names for custom config

include/mbedtls/config_adjust_legacy_crypto.h, library/psa_crypto_pake.c, programs/ssl/ssl_context_info.c, scripts/code_size_compare.py, tests/scripts/audit-validity-dates.py, tests/scripts/check_names.py, tests/scripts/test_psa_compliance.py
Several bits of documentation were incorrectly styling Mbed TLS as MbedTLS.
=> Correct styling of Mbed TLS in documentation

programs/ssl/ssl_context_info.c, tests/scripts/check_names.py, tests/src/external_timing/timing_alt.h
Several bits of documentation were incorrectly styling Mbed TLS as MbedTLS.
=> Backport 2.28: Correct styling of Mbed TLS in documentation

tests/scripts/all.sh
In the full configuration MBEDTLS_TEST_HOOKS is enabled thus the configurations in test_full_cmake_gcc_asan_new_bignum and
test_full_cmake_gcc_asan_new_bignum_test_hooks are the same. Keep the component that runs more tests.
=> Remove redundant test component

scripts/data_files/driver_templates/psa_crypto_driver_wrappers.h.jinja
All paths in both switch statement lead to a return, therefore the end block in both of these functions can never be reached. Fix this by making sure the end block is always called (set status rather than just return), as its safer for future changes. Found by coverity scan.
=> Remove logically dead code

library/aes.c
Looking at #7384 (adds MBEDTLS_AES_USE_HARDWARE_ONLY), we complain with a #error message if this is set on x86 / x86_64 and MBEDTLS_AESNI_C is not set, and similar for Arm.
But if we set AES_USE_HARDWARE_ONLY on some other platform, there's no clean error about "not all prerequisites set", only an unexplained compile fail. This PR fixes that gap.
=> Improve AES hardware-only check

include/psa/crypto_platform.h, include/psa/crypto_sizes.h, include/psa/crypto_struct.h, include/psa/crypto_types.h, library/psa_crypto_core.h, library/psa_crypto_invasive.h, library/psa_crypto_se.h, scripts/mbedtls_dev/build_tree.py, scripts/mbedtls_dev/psa_storage.py, tests/scripts/all.sh, tests/scripts/test_psa_compliance.py
Patterns I looked for:
grep -i "psa-crypto"
grep -i "psa.*crypto.*repo"
grep -i "psa.*crypto.*root"
=> Adapt to new PSA Crypto repo name

include/mbedtls/sha256.h
`is224` should be guarded by `MBEDTLS_SHA224_C`, same as `is384` in `sha512.h`.
=> sha256_context: guard is224 by MBEDTLS_SHA224_C

programs/test/benchmark.c
Small PR to add `AES_CFB128` and `AES_CFB8` in `benchmark.c`.
=> Benchmark: add AES_CFB128 and AES_CFB8

programs/test/benchmark.c
=> Backport 2.28: Benchmark: add AES_CFB128 and AES_CFB8 

ChangeLog.d/fix-cpp-compilation-error.txt, include/mbedtls/asn1.h
The closing curly bracket of `extern "C" {` is excluded when `MBEDTLS_ASN1_PARSE_C` is not defined, due to incorrect position of the `#endif /* MBEDTLS_ASN1_PARSE_C */`.
=> Fix C++ build issue when MBEDTLS_ASN1_PARSE_C is not enabled

library/aes.c
This changes local variable name `RCON` to `round_constants`.
RCON being definition in xc32 compiler headers for some PIC32 register. Without this change, mynewt project for PIC32 platform fails to build due to macro redefinition.
This does not changes behavior of library in any way.
Fixes #8338 
=> Rename local variable in aes.c

library/aes.c
Backport of #8348
This changes local variable name RCON to round_constants.
RCON being definition in xc32 compiler headers for some PIC32 register. Without this change mynewt project for PIC32 platform fails to build due to macro redefinition.
This does not changes behavior of library in any way.
=> [Backport 2.28] Rename local variable in aes.c

library/ssl_tls13_keys.c
In `ssl_tls13_keys.c` missing casting is added. The function `mbedtls_cipher_info_get_key_bitlen` returns size_t but the function `mbedtls_cipher_setkey` accepts `int` so that I have added C style casting to the related fields.
Fixes #8344 
=> Add missing casting size_t to int on ssl_tls13_keys.c

library/pkcs12.c, library/pkcs5.c, library/x509_create.c
Fixes three IAR warnings (the issue is using `goto` to skip past a variable definition)
=> Fix a few IAR warnings

library/pkcs12.c, library/pkcs5.c, library/x509_create.c
Reverts Mbed-TLS/mbedtls#8352 because it's making the CI fail.
We do want Mbed-TLS/mbedtls#8352, but only once it's fixed.
=> Revert "Fix a few IAR warnings" which breaks the CI

ChangeLog.d/pkwrite-pem-use-heap.txt, library/pkwrite.c
backport of #8062 
Similar to #7991 , in `mbedtls_pk_write_pubkey_pem` and `mbedtls_pk_write_key_pem`, we would allocate `2086` and `5679` respectively for a RSA public/private key. We can use heap to save stack usage a lot.
=> Backport 2.28: pkwrite: use heap to save stack usage for writing keys in PEM string

ChangeLog.d/pkwrite-pem-use-heap.txt, library/pkwrite.c
Similar to #7991 , in `mbedtls_pk_write_pubkey_pem` and `mbedtls_pk_write_key_pem`, we would allocate `2086` and `5679` respectively for a RSA public/private key. We can use heap to save stack usage a lot.
Saves of stack usage (measured by 0882828 with `default config` on `x86_64`):
| Function | Old Size | New Size | Change (Bytes) |
| :--- | ---: |  ---: |  ---: |
| mbedtls_pk_write_pubkey_pem | 2176 | 96 | -2080 |
| mbedtls_pk_write_key_pem | 5808 | 128 | -5680 |
=> pkwrite: use heap to save stack usage for writing keys in PEM string

scripts/output_env.sh, tests/compat.sh, tests/scripts/all.sh, tests/scripts/basic-build-test.sh, tests/ssl-opt.sh
We don't need the `GNUTLS_LEGACY` versions in Mbed TLS 3.x: the “main” version works too. This is also mostly the case with `OPENSSL_LEGACY`, but it's still needed for single-DES.
For `GNUTLS_LEGACY`, there is one exception: we mistakenly accept the cipher suite TLS-RSA-WITH-NULL-SHA256 in TLS 1.0/1.1, but like all SHA256-based cipher suites, it was only introduced in TLS 1.2. This is a bug which can cause interoperability issues, but fixing this bug could also break working setups, so I don't think we should fix it in a long-time support branch. (It doesn't apply to Mbed TLS 3.x since we no longer support the affected protocol versions.) GnuTLS fixed this bug in 3.4.7, i.e. between `GNUTLS_LEGACY` (3.3.8) and `GNUTLS` (3.4.10). Patch `compat.sh` to omit this cipher suite with GnuTLS if …
=> Backport 2.28: Remove GNUTLS_LEGACY and OPENSSL_LEGACY (partly)

scripts/output_env.sh, tests/compat.sh, tests/scripts/all.sh, tests/scripts/basic-build-test.sh, tests/ssl-opt.sh
We don't need the `GNUTLS_LEGACY` and `OPENSSL_LEGACY` versions in Mbed TLS 3.x: the “main” versions work too.
=> Remove GNUTLS_LEGACY and OPENSSL_LEGACY

ChangeLog.d/fix-issue-x509-cert_req.txt, programs/x509/cert_req.c
Fix possible NULL dereference issue in X509 cert_write program if an entry in the san parameter is not separated by a colon.
Issue can happen when running a command like this:
`./cert_req san=IP`
=> Fix possible NULL dereference issue in X509 cert_req program

ChangeLog.d/fix-issue-x509-cert_write.txt, programs/x509/cert_write.c
Fix possible NULL dereference issue in X509 cert_write program if an entry in the san parameter is not separated by a colon.
Issue can happen when running a command like this:
`./cert_write is_ca=1 serial=3 request_file=test-ca.req.sha256 selfsign=1 issuer_name="C=NL,O=PolarSSL,CN=PolarSSL Test CA" issuer_key=/Users/walelm01/MbedTLS-fork/mbedtls/tests/data_files/test-ca.key issuer_pwd="PolarSSLTest" not_before=20190210144400 not_after=20290210144400 md=SHA1 version=3  output_file=/Users/walelm01/cert san="DN:C=UK,O=\"Mbed TLS\",CN=\"SubjectAltName test\";URI:http://pki.example.com/;IP:127.1.1.0;DNS"`
Please refer to the [contributing …
=> Fix possible NULL dereference issue in X509 cert_write program

programs/demo_common.sh, programs/psa/key_ladder_demo.sh, programs/test/dlopen_demo.sh, tests/scripts/all.sh, tests/scripts/check_files.py, tests/scripts/run_demos.py
Run sample program demo scripts (`programs/test/*_demo.sh`) in a few components of `all.sh`.
In the long term, we should run the programs in all configurations, but this requires declaring dependencies properly. For the time being, just run the programs in a few builds (out-of-box, full config, with sanitizers, without deprecated functions).
This is a rebase of a part of https://github.com/Mbed-TLS/mbedtls/pull/2698, adapted for the evolution of the development branch and omitting the new demo script for certificate-related programs.
* Create `programs/demo_common.sh` for common logic.
* Create `run_demos.py` and run it from a few components in `all.sh`.
* Do different changes to `check_files.py` because that part of the file has evolved.
* New: Adapt `dlopen_demo.sh` which didn't exist …
=> Run sample program demo scripts in all.sh

library/pk_internal.h, library/ssl_tls12_server.c
This PR resolves #8263 by using `!MBEDTLS_PK_USE_PSA_EC_DATA` as guard for `mbedtls_pk_ec_[ro/rw]` and fixing related issues.
=> Fix dependencies of mbedtls_pk_ec_ro and mbedtls_pk_ec_rw

tests/suites/test_suite_cipher.function
Found by coverity:
Calling mbedtls_cipher_free() on a context that was not initialised is dangerous, and this could happen if the first test in check_set_padding() failed.
=> Move initialisation in test to before first test

tests/ssl-opt.sh
These are explicitly PSA tests, so use PSA_WANT.
Was missed by analyze_outcomes.py because those test cases were not listed properly, which will be fixed by #8088.
=> Fix some dependencies in ssl-opt.sh

library/pk_internal.h, library/pk_wrap.c, library/pkparse.c
This is part 1 of  #7994 - focusing on  `MBEDTLS_PK_USE_PSA_EC_DATA` mostly, plus miscellaneous other things.
I decided to stop after about 20 commits in order to keep it reviewable, I'll continue #7994 in another PR once this one is OK.
Note to reviewers: some commits just move code around and can easily be reviewed with `git show --color-moved <commit_id>`.
=> cleanup PK parse - part 1

ChangeLog.d/fix-mingw32-build.txt, library/aesni.c, tests/scripts/all.sh
=> Backport 2.28: Support cpuid for win32

library/pkcs12.c, library/pkcs5.c
Almost trivial backport of #8363 
=> Backport 2.28: Stop IAR warning about goto skipping variable definition

ChangeLog.d/fix-mingw32-build.txt, library/aesni.c, tests/scripts/all.sh
Fix: #8334 and #8332
`cpuid.h` and `intrin.h` define `__cpuid` with different signatures. We include `intrin.h` for WIN32 but we only use the correct signature for MSVC. This cause problem when build WIN32 target with non-MSVC compilers (i.g `clang` or `i686-w64-mingw32`).
=> Support cpuid for win32

programs/ssl/ssl_client2.c, programs/ssl/ssl_server2.c
Trivial backport of https://github.com/Mbed-TLS/mbedtls/pull/7844
=> Backport 2.28: Fix usage & error reporting in SSL programs

include/mbedtls/ssl.h, library/ssl_misc.h, library/ssl_tls13_server.c, tests/data_files/early_data.txt, tests/data_files/tls13_early_data.txt, tests/opt-testcases/tls13-misc.sh, tests/ssl-opt.sh
=> TLS 1.3: EarlyData SRV: Add early data extension parser.

tests/suites/host_test.function, tests/suites/main_test.function
Trivial backport of https://github.com/Mbed-TLS/mbedtls/pull/8294
=> Backport 2.28: Support running unit tests from another directory

tests/suites/host_test.function, tests/suites/main_test.function
When running a test suite, try to change to the directory containing the executable. This allows running a test suite from any directory, and still allow it to access its .datax file as well as data files (generally in tests/data_files) used by individual test cases.
=> Support running unit tests from another directory

ChangeLog.d/8372.txt, include/mbedtls/aesni.h, library/aesni.c
Fixes #8372. Does not conflict with #8339.
It can successfully compile w/ or w/o the clang options `-maes -mpclmul`.
The macro `__GNUC__` is not defined by Clang on Windows, thus use the macro `__clang__` for `-maes -mpclmul`.
=> Backport 2.28: Fix compiling AESNI in Mbed-TLS with clang on Windows

library/common.h
IAR only supports `__attribute__((unused))` if the '-e' flag is passed to the compiler (which we can't detect), so use a more fail-safe implementation of `MBEDTLS_MAYBE_UNUSED`.
Without the -e flag, the current implementation is a compile fail on IAR.
=> Fix MBEDTLS_MAYBE_UNUSED for IAR

ChangeLog.d/8372.txt, library/aesni.c, library/aesni.h
Fixes #8372. Does not conflict with #8339.
It can successfully compile w/ the clang options `-maes -mpclmul`.
The macro `__GNUC__` is not defined by Clang on Windows, thus use the macro `__clang__` for `-maes -mpclmul`.
=> Fix compiling AESNI in Mbed-TLS with clang on Windows

ChangeLog.d/fix-linux-builds-in-conda-forge.txt, library/platform_util.c
Conda-forge seems to be using a very old set of system headers (I had to go back to CentOS 6 to reproduce the problem)
Fixes #8422
=> Fix builds in conda-forge, which doesn't have CLOCK_BOOTTIME

library/aesni.c, library/aesni.h, tests/scripts/all.sh
Add target attributes for 32-bit builds to compile with intrinsics out of the box.
This fixes 32-bit compilation issues (e.g. https://github.com/Mbed-TLS/mbedtls/issues/8334 and https://github.com/Mbed-TLS/mbedtls/issues/8400).
For 64-bit, assembly will still be used if cpu flags are not passed when building.
Tested that it builds fine on:
Windows 10: MINGW 32-bit/64-bit (13.0.2), Clang 32-bit/64-bit (17.0.1)
Linux Ubuntu 22.04: gcc 32-bit/64-bit (11.4.0), Clang 32-bit/64-bit (14.0.0)
Let me know if there is some better way of doing this.
=> AES-NI: use target attributes for x86 32-bit intrinsics

programs/ssl/ssl_client2.c, tests/include/test/macros.h, tests/suites/test_suite_ctr_drbg.function, tests/suites/test_suite_entropy.function, tests/suites/test_suite_pkwrite.function, tests/suites/test_suite_psa_crypto_se_driver_hal.function, tests/suites/test_suite_ssl.function, tests/suites/test_suite_x509parse.function, tests/suites/test_suite_x509write.function
Backport of https://github.com/Mbed-TLS/mbedtls/pull/8381. Differences with the original:
* In "Fix missing initializations on some error paths", I skipped all the conflicting chunks, which were mostly for test functions that didn't exist in 2.28. I also melded the code style fixup into that commit.
* I looked for other places with possible misplaces init vs `PSA_INIT` and found one, which had been fixed earlier in 3.x but the fix had not been backported. I ended up cherry-picking that fix in "test: proper positioning of USE_PSA_INIT + fixed some exit labels". Here also I skipped most chunks that were conflicting.
* I backported "Introduce TEST_CALLOC_NONNULL" which is needed for "Use modern macros for calloc in test code".
Please tick as appropriate and edit the reasons (e.g.: "backport: …
=> Backport 2.28: Cleanups in test code

tests/suites/test_suite_mps.function, tests/suites/test_suite_psa_crypto.function
Fix two coverity issues, firstly convert one of the PSA sign / verify interruptible tests over to using TEST_CALLOC, and fix a potential leak in the case of a failing test.
Secondly, add explicit exit labels to all the MPS tests, as the 'built in' one would potentially have leaked resources in the case of test failure by jumping past the free call.
=> Fix two coverity issues

tests/compat.sh, tests/scripts/check_test_cases.py, tests/ssl-opt.sh
=> Backport 2.28: Make check_test_cases.py recognize test case name templates in ssl-opt.sh

scripts/lcov.sh
This PR solves part one of https://github.com/Mbed-TLS/TF-PSA-Crypto/issues/41.
Add repository detection (credit to davidhorstmann-arm for adding this in all.sh previously) and use repository detection to set the library directory and title variables.
I have tested this script locally against both mbedtls and tf-psa-crypto and the results were as expected.
Limitations: The modifications rely on the build directory being named "build" in tf-psa-crypto which may not always be the case. Perhaps this is ok for now, but I will document it. Otherwise perhaps we could supply the build directory name as a command line argument. Open to suggestions.
Please refer to the [contributing …
=> Modify lcov.sh to work in tf-psa-crypto as well

scripts/config.py, tests/scripts/all.sh
Add a new config preset: full_no_platform (like full, but with no platform support), and use this in the all.sh component_test_no_platform. This will be the basis of our coverity builds.
Trivial backport of #8391
=> [Backport 2.28] Add build preset full_no_platform

scripts/config.py, tests/scripts/all.sh
Add a new config preset: full_no_platform (like full, but with no platform support), and use this in the all.sh component_test_no_platform. This will be the basis of our coverity builds.
This implements #8380 
=> Add full_no_platform config preset

library/common.h, library/psa_crypto_cipher.c
Reduce code size in mbedtls_cipher_validate_values by eliminating code for algorithms that are not built.
#8119 adds 128 bytes - this removes half of that increase for our reference build.
=> code size for mbedtls_cipher_validate_values

tests/scripts/check_files.py
Trivial backport of https://github.com/Mbed-TLS/mbedtls/pull/8470
=> Backport 2.28: Check copyright statements and SPDX license statements

tests/scripts/check_files.py
Check copyright statements and SPDX license statements, where present. Also complain about suspicious mentions of a license.
Priority justification: with the [license change](https://github.com/Mbed-TLS/mbedtls/pull/8462), we want the CI to complain if we try to add files with an obsolete license header.
Out of scope: enforcing the presence of copyright and license statements. Maybe we want this, but it's a completely different task.
The reporting isn't very nice (it just says “License issue”) because of preexisting technical debt. There's a [fix](https://github.com/Mbed-TLS/mbedtls/pull/2506) but it needs rework and review. Getting the check in is more urgent.
=> Check copyright statements and SPDX license statements

tests/suites/test_suite_constant_time_hmac.function
Some time ago we stopped running `test_suite_constant_time_hmac` on the CI (I guess due to some header file refactoring). ([yesterday's nightly](https://mbedtls.trustedfirmware.org/job/mbed-tls-nightly-tests/213/execution/node/8075/log/)) Fix that.
This would have been detected if https://github.com/Mbed-TLS/mbedtls/issues/2691 had been completed.
=> Fix test suite never executed due to an undefined symbol

tests/ssl-opt.sh
This add new parameter for `ssl-opt.sh` . It can run test-suite in `opt-testcase` directory only. 
It is introduced in #6280 to accelerate the script development. But I think it can be reviewed separately. 
=> Add test-suite parameter to filter tests

tests/scripts/generate_server9_bad_saltlen.py
Fix `check_files` failing in `mbedtls-2.28` since a few minutes ago.
=> 2.28 only: Update license of a newly added file

tests/scripts/all.sh
=> [G3] Disable cipher.c in the accel component

ChangeLog.d/rename-conf-early-data-API.txt, include/mbedtls/mbedtls_config.h, include/mbedtls/ssl.h, library/ssl_tls.c, programs/ssl/ssl_client2.c, programs/ssl/ssl_server2.c, tests/ssl-opt.sh
`mbedtls_ssl_tls13_conf_early_data` -> `mbedtls_ssl_conf_early_data`,
`mbedtls_ssl_tls13_conf_max_early_data_size` -> `mbedtls_ssl_conf_max_early_data_size`,
since in the future this may not be specific to TLS 1.3, we shouldn't need `tls13` prefix.
Fix #6909 
=> TLS 1.3: Rename early_data and max_early_data_size configuration function

include/mbedtls/ssl.h, library/ssl_tls.c, library/ssl_tls13_server.c, tests/src/test_helpers/ssl_helpers.c, tests/suites/test_suite_ssl.function
=> TLS 1.3 EarlyData: add `max_early_data_size` field for ticket

programs/.gitignore, programs/Makefile, programs/test/CMakeLists.txt, programs/test/metatest.c, scripts/generate_visualc_files.pl, tests/scripts/all.sh, tests/scripts/run-metatests.sh
Add a small framework to validate that we to catch some expected errors in our test configurations. For example, check that `test_fail` causes a test failure, and that Asan detects a memory leak.
The scope of this pull request is limited to some basics. We can add more metatests and more sophistication in follow-ups.
Status: ready.
=> Create a metatest program

tests/ssl-opt.sh
Those commands print information in stdout, that's noise for testing. Just disable them.
This is found in #6280. But it can be separate review.
https://github.com/Mbed-TLS/mbedtls/pull/6280/commits/c2a2a5eda54cb7065f338bc97ee6d46cf18a0c91 is the commit in #6280 
=> Disable stdout in require_*_configs_* functions

ChangeLog.d/gnutls_anti_replay_fail.txt, include/mbedtls/debug.h, include/mbedtls/mbedtls_config.h, include/mbedtls/ssl.h, library/ssl_client.c, library/ssl_misc.h, library/ssl_ticket.c, library/ssl_tls.c, library/ssl_tls13_client.c, library/ssl_tls13_server.c, programs/ssl/ssl_server2.c, tests/opt-testcases/tls13-misc.sh, tests/src/test_helpers/ssl_helpers.c, tests/suites/test_suite_ssl.function
fix #6623 
preceding-pr: #6891 
TIME RESOLUTION OF TICKET AGE
The time precision of ticket_age is milliseconds(RFC 8446). But our precision is senconds, we caculate
ticket age with (mbedtls_time( NULL ) - ticket_recived)*1000 .
If the ticket is sent/received near the end of a second and client send ticket at the beggining of
next second, ticket age of client is 1000 ms, but ticket age of server is less than it. As a result,
it offends the anit replay ruler.
Workaround solution: Add 1 second to ticket_received and do reconnect 1 second later.
The issue can be reproduce and verified with https://github.com/Mbed-TLS/mbedtls/pull/6712 . That PR include test script and test result.
This PR is to fix that.
The commit is come from #6712 and verified in that PR
I am not sure if it needs backport. …
=> TLS 1.3: Fix anti replay fail from GnuTLS

include/mbedtls/config_adjust_legacy_crypto.h, include/mbedtls/ssl.h, library/ssl_tls.c
This PR adds missing guard in `mbedtls_ssl_cipher_to_psa` for `ssl_tls.c`.
=> ssl_tls: add missing macro guard

library/ssl_client.c, library/ssl_tls13_client.c
When send `pre_shared_key` extension, then sent_extension should be correctly set for future using. It is missed.
This issue is found in #6280. And this commit is also included in #6280. But I think it can be separate review.
=> Fix missing pre shared key ext sent mask

include/mbedtls/cipher.h
Fixing arithmetic overflow warning (C6297), if compiled in Visual Studio
=> [cipher.h]  Arithmetic overflow in binary left shift operation

tests/include/test/helpers.h
Backport of https://github.com/Mbed-TLS/mbedtls/pull/8286. The problematic test case doesn't exist in 2.28, but backport the new helper macros.
=> Backport 2.28: Fix test_suite_platform failure with Asan on modern Clang

library/aesni.h, tests/suites/test_suite_ssl.function
This PR is aimed to collect some improvements or comments of merged PR that were not worth iterating the original ones. Until it contains sufficient contents, this PR is not worth to be reviewed.
- 9d87a38976cb0b9f8df8228c47acb0ebefe0c00f: improve variable naming in ssl_set_hostname_twice. Resolve https://github.com/Mbed-TLS/mbedtls/pull/7216#discussion_r1258372308
- 6f0259e6da4d7677b48701a68adb529ea02b4473: Resolve https://github.com/Mbed-TLS/mbedtls/pull/8209#discussion_r1326834863
=> misc improvements

scripts/prepare_release.sh
Fixes a minor bug in the release preparation script which will cause it to fail CI because of an extra whitespace introduced in .gitignore.
Resolves #8304 and deprecates [PR8369](https://github.com/Mbed-TLS/mbedtls/pull/8369)
=> prepare_release: sed querry change to strip whitespace

library/psa_crypto.c, library/psa_crypto_core.h, library/psa_crypto_slot_management.c
Add new status field to key slots, use it in `psa_is_key_slot_occupied()`, and make any function setting `slot->attr.type` use the field. Closes https://github.com/Mbed-TLS/mbedtls/issues/8409
=> Make empty key slots explicit

ChangeLog.d/armv8-aesce.txt, include/mbedtls/mbedtls_config.h, library/aes.c, library/aesce.c, library/aesce.h, tests/scripts/all.sh
Extend support for AESCE to 32-bit builds.
Saves around 450b for Thumb 2 -Oz (but not for TF-M, because our reference target doesn't have Neon).
Manually tested via qemu, for arm, thumb and aarch64 with gcc and clang.
Do we want to put this in the Changelog as Security, because it enables const-time AES for these targets?
=> Support hw-accelerated AES on Thumb and Arm

library/constant_time_impl.h
When compiling with:
```
arm-none-eabi-gcc.exe (Sourcery G++ Lite 2011.03-42) 4.5.2
```
We get the following error:
```
constant_time_impl.h:47:13: error: expected [error|warning|ignored] after '#pragma GCC diagnostic'
```
using this commit, we activat the pragma only for GCC 5+
=> Fix compiler error on gcc 4.5.2.

ChangeLog.d/8060.txt, include/mbedtls/ccm.h, include/mbedtls/check_config.h, include/mbedtls/config_adjust_legacy_crypto.h, include/mbedtls/gcm.h, library/ccm.c, library/gcm.c, tests/scripts/all.sh
=> [G2] Make CCM and GCM work with the new block_cipher module

configs/ext/tfm_mbedcrypto_config_profile_medium.h, include/mbedtls/mbedtls_config.h
=> Driver-only: G1: clean up for BLOCK_CIPHER_NO_DECRYPT

tests/include/test/helpers.h, tests/scripts/analyze_outcomes.py, tests/suites/test_suite_platform.data
Fix https://github.com/Mbed-TLS/mbedtls/issues/8285
=> Fix test_suite_platform failure with Asan on modern Clang

tests/ssl-opt.sh
=> Backport 2.28: ssl-opt.sh: Fix getting the list of supported ciphersuites.

tests/ssl-opt.sh
Since the merge of #7844 (3.5.x not impacted) the detection of the supported ciphersuites in ssl-opt.sh is broken and some test cases are not run anymore. This PR fixes this.
=> ssl-opt.sh: Fix getting the list of supported ciphersuites.

configs/config-tfm.h, configs/ext/crypto_config_profile_medium.h, configs/ext/tfm_mbedcrypto_config_profile_medium.h, tests/scripts/all.sh
Bring Mbed TLS in line with recent changes to TF-M config
https://git.trustedfirmware.org/TF-M/trusted-firmware-m.git/log/lib/ext/mbedcrypto/mbedcrypto_config
=> Adjust to match current TF-M config

library/constant_time.c
Remove unused (and non-compiling) code in `constant_time.c` that prevents some configurations from building.
This can be reproduced with: `mtest MBEDTLS_USE_PSA_CRYPTO MBEDTLS_SSL_SOME_SUITES_USE_MAC`
=> Remove unused/non-compiling code

library/platform_util.c
Related to: https://github.com/Mbed-TLS/mbedtls/issues/8562
Without this change I was not able to compile for Haiku OS
=> Fixed compilation for Haiku OS

include/mbedtls/pkcs12.h, include/mbedtls/pkcs5.h
Instead of re-defining MBEDTLS_PKCS5_[EN/DE]CRYPT and MBEDTLS_PKCS12_PBE_[EN/DE]CRYPT from scratch, since these values are to be used with the mbedtls_cipher_setkey() function, ensure that their value matches with enums in cipher.h.
=> pkcs[5/12]: use cipher enums for encrypt and decrypt

library/ssl_tls13_client.c
**Context**: `tls13 early_data` in `ssl_tls13_client.c`
In `ssl_tls13_postprocess_server_hello`, we assign `handshake->ciphersuite_info->id` to `ssl->session_negotiate->ciphersuite`, this doesn't matter in `non-early_data` situation.  But if client sends `early_data ext` in `client_hello` and receives `early_data ext` in `encrypted_extensions`, the aforementioned assignment makes the [check](https://github.com/Mbed-TLS/mbedtls/blob/development/library/ssl_tls13_client.c#L2193) non-functional. Thus we have to do the assignment after the check in `encrypted_extensions`. This won't cause problems of generating handshake keys as we use `handshake->ciphersuite_info->id` to compute the keys in `ssl_tls13_postprocess_server_hello`.
Please tick as appropriate and edit the reasons (e.g.: …
=> TLS13: CLI: EarlyData: Assign ciphersuite after associated verification in EE

programs/test/benchmark.c
As private fields may change without notice, it makes sense to indicate explicitly when those fields are accessed outside the core mbedtls libraries that shall have direct access to those fields. Hence, I added the macros to indicate which private fields are getting accessed in the benchmark.c file.
benchmark.c was uncrustified in the first commit.
=> Explicitly accessing private fields in benchmark

library/ssl_msg.c
We are requested to compile our code with warnings for potentially uninitialized variables enabled and all warnings considered as errors.
When building ssl_msg.c, the following error pops up:
```
library\ssl_msg.c: In function 'mbedtls_ssl_read_record':
library\ssl_msg.c:3653:12: error: 'len' may be used uninitialized in this function
```
In this PR, we fix the problem by initializing the `len` variable to 0.
Uncrustified ssl_msg.c in second commit.
=> Fix uninitialized variable warnings in ssl_msg.c

include/mbedtls/check_config.h, include/mbedtls/ctr_drbg.h, include/mbedtls/mbedtls_config.h, include/psa/crypto_extra.h, library/ctr_drbg.c, library/psa_crypto.c, tests/include/test/drivers/cipher.h, tests/include/test/drivers/key_management.h, tests/include/test/psa_crypto_helpers.h, tests/scripts/all.sh, tests/src/drivers/test_driver_cipher.c, tests/src/drivers/test_driver_key_management.c, tests/src/psa_crypto_helpers.c, tests/suites/test_suite_ctr_drbg.function, tests/suites/test_suite_psa_crypto_driver_wrappers.function, tests/suites/test_suite_psa_crypto_slot_management.function, tests/suites/test_suite_random.function
Resolves #8441.
Opening this PR as draft because it includes several fixes to test I'm not really sure about. In particular `test_suite_psa_crypto_driver_wrappers` is expected to fail in `component_test_psa_crypto_config_accel_cipher_aead`. This is where I'm looking for suggestions (as also reported on the last commit).
=> [G4] Make CTR-DRBG fall back on PSA when AES not built in

scripts/assemble_changelog.py
This PR is part of Mbed-TLS/TF-PSA-Crypto#47.
Add support to specify the name of the project from the previous entries.
=> Modify changelog assembly to work with tf-psa-crypto

tests/scripts/all.sh
Building on https://github.com/Mbed-TLS/mbedtls-test/pull/143 - filter the Valgrind tests from the PR jobs
=> Do not run Valgrind tests in PR jobs

tests/scripts/all.sh
Almost trivial backport of #8613 
=> Do not run Valgrind tests in PR jobs - backport 2.28

library/ssl_misc.h, library/ssl_tls.c, library/ssl_tls13_client.c, library/ssl_tls13_generic.c, library/ssl_tls13_server.c, programs/ssl/ssl_server2.c, tests/opt-testcases/tls13-misc.sh
fix #6347 
This PR write early_data extension of NST message. `max_early_data_field` is come from configured value. Next PRs will fix that.
=> TLS 1.3: EarlyData SRV: Write `early_data` extension of NewSessionTicket

programs/ssl/ssl_client2.c, tests/opt-testcases/tls13-misc.sh
Originally we have one input option to control whether enable early data or not. Currently we need one extra parameter to input various length of  early data. This pr will integrate them together.
This is part of #6542 
=> Change early data flag to input file

tests/suites/test_suite_x509write.function
Simple if not trivial backport of #8626.
This prevents a call to `mbedtls_mpi_free()` on uninitialized data when `USE_PSA_INIT()` fails.
Issue reported by Coverity.
=> [Backport 2.28] Fix possible free of uninitialized MPI

library/pkparse.c, library/ssl_tls12_server.c
This PR disables setting the key enrollment algorithm when parsing EC keys in PK module. Since PK module can only do ECDSA and not all the keys can perform the same operations, then we'll have:
- Weierstrass keys -> `alg` set to [deterministic] ECDSA
- Montgomery keys -> no `alg` set because they cannot be used for ECDSA
When the TLS module will use the key to do ECDH, it will export it and re-import with proper algorithm and flags which are required to do ECDH.
Resolves #8601
=> Quit using enrollment in pkparse

library/ecp.c, tests/scripts/all.sh, tests/suites/test_suite_psa_crypto_pake.function
Tidy up use of ASAN in tests, and prefer clang instead of gcc.
The change to `test_m32_o0` improves coverage (more non-assembly paths get tested which is the point of that test).
In testing yesterday, Asan under clang looks to be around 10-20% faster than gcc, which suggests a saving of several hours of CPU time per CI run (my estimate is 145 components that use Asan, with total mean duration 1765 mins, so perhaps 2-4h of savings from using clang over gcc). HOWEVER, testing more this morning I can't reproduce so a bit uncertain about the impact now.
=> CI perf - prefer clang for Asan

include/mbedtls/net_sockets.h, library/net_sockets.c
=> Backport 2.28: Avoid use of `ip_len` as it clashes with a macro in AIX system headers

include/mbedtls/net_sockets.h, library/net_sockets.c, programs/x509/cert_req.c, programs/x509/cert_write.c
=> Avoid use of `ip_len` as it clashes with a macro in AIX system headers

library/pk.c
This PR introduces guards (`MBEDTLS_PSA_CRYPTO_CLIENT`) in PK module for using key enrollment functions.
Resolves #8602
=> Make enrollement "optional" in pk_can_do_ext()

include/psa/crypto_extra.h, include/psa/crypto_struct.h
It was introduced in https://github.com/Mbed-TLS/mbedtls/pull/8616 but not documented.
=> Document the domain_parameters_size==SIZE_MAX hack

library/ssl_tls12_server.c
The `clienthello` session id comment is wrong, which should be 34 to 34.  And add the meaning of `x`.
=> Make clienthello comment clear

library/ssl_tls.c
Remove a piece of code that was meant to ensure non-usage of the ssl context (by NULL-ing it) under conditions where it should not be used, as this now makes less sense. Backport of #8384
=> [Backport 2.28] Remove NULLing of ssl context in TLS1.2 transform population

library/ssl_tls.c
Remove a piece of code that was meant to ensure non-usage of the ssl context (by NULL-ing it) under conditions where it should not be used, as this now makes less sense and also triggers coverity.
Also remove redundant NULL check on the ssl contextt further down the function.
Have to admit I'm not entirely sure about backporting this one - its not a security fix, just a simplification. I have done the backport, but feel free to express views on this.
=> Remove NULLing of ssl context in TLS1.2 transform population 

docs/architecture/psa-migration/md-cipher-dispatch.md
A quick study of what other modules in the library are using, and a tentative definition of Cipher light based on that.
Note: X.509 never uses ciphers/AEADs directly, and when `USE_PSA_CRYPTO` is enabled, TLS doesn't use any function from `cipher.h` (even less low-level ciphers/AEADs APIs).
=> [G2] Tentative definition of Cipher light

programs/Makefile, scripts/common.make, tests/Makefile, tests/scripts/all.sh, tests/scripts/check_files.py, tests/scripts/depends.py, tests/scripts/psa_collect_statuses.py
1. Create `scripts/common.make` because I am tired of duplicating code between `programs/Makefile` and `tests/Makefile`. At least for now, `library/Makefile` doesn't include it, though it probably should as a subsequent step.
2. Automatically detect whether linking with `pthread` is needed when building with `make`. This is nice to users, and also means we don't need to pass options through to make. **Fixes the [code coverage build failure](https://mbedtls.trustedfirmware.org/job/mbed-tls-nightly-tests/327/execution/node/899/log/) in the CI.**
3. Clean up the machinery added in #8342 for passing `THREADING=pthread` from `all.sh` down to `make`, since it isn't needed after all.
=> Autodetect whether linking with pthread is needed

tests/scripts/all.sh
Support for each test was checked before the command line had been parsed, causing the support_ functions to ignore arguments that set a tool's location.
This patch delays calling the `support_` functions and setting `SUPPORTED_COMPONENTS` until the arguments had been parsed, and had a chance to modify the tool locations that are used by many of the functions.
This builds on @tom-cosgrove-arm's patch in 730addc2031, which fixed this issue for the special case of the ArmCC/ArmClang.
=> all.sh: Parse arguments before checking if a test is supported

include/psa/crypto_extra.h, include/psa/crypto_struct.h
Fixes https://github.com/Mbed-TLS/mbedtls/issues/6910
=> Fixes redundant declarations for psa_set_key_domain_parameters

programs/test/benchmark.c
With a security strength of 128, RSA 3072 is a good compromize between security and processing time. So far, the benchmark considered only RSA 2048 and 4096, however, the latter does not even reach the next level of security strength, namely 192. Hence, when designing products with a particular security security strength in mind, it is good to have some benchmarks available.
I uncrustified the sourcecode using scripts/code_style.py first, before committing my new code in the second commit.
=> Add benchmark for RSA 3072

programs/test/benchmark.c
When activating MBEDTLS_TIMING_ALT, the benchmark was not built correctly. The provided changes make it possible to build the benchmark program when an alternative timing implementation is provided.
=> Alternative Timing compatible benchmark.c

programs/Makefile, scripts/common.make, tests/Makefile
Follow-up to https://github.com/Mbed-TLS/mbedtls/pull/8653, fixing some documentation and robustness issues (mostly raised in review).
Priority: high because this is a follow-up to a merge pull request, which would have been handled by rework before merging in normal circumstances, and was only delayed because the original pull request was very-high-priority.
=> Minor cleanups to common.make

configs/config-tfm.h, configs/ext/README.md, configs/ext/config_tfm.h, configs/ext/crypto_config_profile_medium.h, configs/ext/mbedtls_entropy_nv_seed_config.h, configs/ext/tfm_mbedcrypto_config_profile_medium.h, tests/scripts/check_files.py
To simplify maintenance, take the TF-M config verbatim.
Update: also moves a recent change introduced in #8599 into the correct section, and fixes building with armclang for aarch64 (this was not being detected as baremetal because `__ARM_EABI__` isn't set).
=> Use TF-M config verbatim

library/common.h, tests/scripts/all.sh, tests/scripts/depends.py, tests/suites/test_suite_ecp.function
Backport of #8642 
This was constructed mostly by cherry-picking the individual commits which were applicable. A few were messy and had to be reconstructed by hand, but the changes are very simple so the differences from the main PR are straightforward / obvious.
=> Backport CI perf: Use clang by default in all.sh

include/mbedtls/check_config.h, include/mbedtls/config_adjust_legacy_crypto.h, include/mbedtls/mbedtls_config.h
Check if `CIPHER_C` is enabled when PSA builtin unauthenticated ciphers are enabled.
Resolves #8646
=> check_config.h not complete about builds without CIPHER_C

include/mbedtls/ssl.h, library/ssl_misc.h, library/ssl_msg.c, library/ssl_tls.c, library/ssl_tls13_client.c, library/ssl_tls13_generic.c, library/ssl_tls13_server.c, programs/ssl/ssl_server2.c, tests/scripts/all.sh, tests/src/test_helpers/ssl_helpers.c, tests/ssl-opt.sh, tests/suites/test_suite_ssl.function
=> Comply with the received Record Size Limit extension

library/x509_create.c, tests/suites/test_suite_x509write.data, tests/suites/test_suite_x509write.function
Adds tests and a fix for Issue [#8687](https://github.com/Mbed-TLS/mbedtls/issues/8687).
Backport of [#8688](https://github.com/Mbed-TLS/mbedtls/pull/8688).
=> Backport 2.28: Fix bug in mbedtls_x509_set_extension

include/mbedtls/ssl.h
`deprecated` flag is missed for `mbedtls_ssl_conf_sig_hashes()`
=> Add deprecated flag in document for sig_hashes

ChangeLog.d/fix-tls13-server-min-version-check.txt, library/ssl_tls13_server.c, tests/ssl-opt.sh
=> TLS1.3: SRV: check `min_tls_version` when parsing ClientHello

library/ssl_client.c, library/ssl_misc.h, library/ssl_tls.c, library/ssl_tls13_client.c, library/ssl_tls13_server.c
Fix [comment](https://github.com/Mbed-TLS/mbedtls/pull/6945/files#r1363489728)
Fixes #6935
>Note: convention in TLS code, "check" functions return 0 if the check is successful, something different from zero otherwise. By the way, we should rename or change the value returned by ssl_tls13_check_*_key_exchange() functions.
=> Harmonise the names and return values of check functions in TLS code

tests/scripts/all.sh
=> [Backport 2.28] Set OpenSSL/GnuTLS variables when running release components

docs/redirects.yaml
Migrate to the new redirect format introduced by ReadTheDocs in readthedocs/readthedocs.org#10881
The redirect format is described in full [here](https://docs.readthedocs.io/en/stable/user-defined-redirects.html)
=> Migrate to new RTD redirect format

include/mbedtls/threading.h, include/psa/crypto_values.h, library/psa_crypto_core.h, library/psa_crypto_slot_management.c, library/psa_crypto_slot_management.h, library/threading.c
Add the global key slot mutex, make it initialize and free when we have an Alt implementation, and document that it needs to be held for the key slot primitive functions. Follows on from the work in #8672. Resolves #8674.
=> Implement the key slot mutex

ChangeLog.d/8726.txt, library/entropy_poll.c
Adding the necessary flag to allow this to build in z/OS (an IBM mainframe operating system).
=> Update entropy_poll.c to allow build in z/OS

ChangeLog.d/iar-gcc-perf.txt, include/mbedtls/build_info.h, library/alignment.h, library/common.h, library/platform_util.c
Summary: we saw poor code-gen for IAR, and on further investigation, found similar for some versions of gcc, resulting in decreased perf and increased code-size. This PR:
- ensures efficient unaligned access on IAR and old GCC
- enables better code-size optimisation of mbedtls_xor over constant size input (the common case)
- makes unaligned accessors and mbedtls_xor always inline - this is a win for perf and a mixed outcome for code-size, for the platforms where this wasn't already happening
- overall, our reference config increases by 74 bytes
- I'd expect worst code-size increase for platforms where unaligned access isn't supported, but actually it's not too bad: armv7 thumb2 with -mno-unaligned-access increases by 250 bytes on gcc (TF-M config) and decreases by 156 bytes on clang. This …
=> Improve codegen of unaligned access for IAR and gcc

tests/include/test/macros.h
`gcc-14` added a new `-Wcalloc-transposed-args` warning recently. It detected minor infelicity in `calloc()` API usage in `mbedtls`:
In file included from /build/mbedtls/tests/include/test/ssl_helpers.h:19,
from /build/mbedtls/tests/src/test_helpers/ssl_helpers.c:11:
/build/mbedtls/tests/src/test_helpers/ssl_helpers.c: In function 'mbedtls_test_init_handshake_options':
/build/mbedtls/tests/include/test/macros.h:128:46:
error: 'calloc' sizes specified with 'sizeof' in the earlier argument
and not in the later argument [-Werror=calloc-transposed-args]
128 |             (pointer) = mbedtls_calloc(sizeof(*(pointer)),  \
|                                              ^
Please tick as appropriate and edit …
=> tests: fix `calloc()` argument list (`gcc-14` fix)

programs/pkey/dh_client.c, programs/pkey/dh_server.c, programs/pkey/rsa_decrypt.c, programs/pkey/rsa_encrypt.c, programs/pkey/rsa_sign.c, programs/pkey/rsa_verify.c
This PR replaces the legacy MBEDTLS_PRIVATE directly accessed fields with API calls.
In addition to that it updates the reference program to follow the current recommended guidelines:
* Added the entropy source for blinding purposes.
* Updated SHA1 to SHA256
Resolves #5014 
=> [MBEDTLS_PRIVATE] Update rsa context in programs 5014

library/psa_crypto_core.h
These operations will be very common; the error handling and `#if defined` wrapping makes the patterns span a few lines. So we can make macros out of the patterns to help readability.
Now we can lock/unlock the key slot mutex in a single line, which also handles doing nothing if threading is not enabled. 
=> Add macros for locking/unlocking the key slot mutex

tests/scripts/all.sh
=> Unify clang version checking in all.sh

ChangeLog.d/linux-aarch64-hwcap.txt, library/sha512.c
Pick up the changelog from #7121 .
7121 was closed because the SHA-256 changes were already done, but in preparing this I noticed that we didn't have a fix for SHA-512, so I've added that here (following the existing pattern in `sha256.c`, rather than in 7121).
Tested locally: builds correctly and enables hw acceleration where appropriate for all combinations of `MBEDTLS_SHA512_USE_A64_CRYPTO_ONLY` and `MBEDTLS_SHA512_USE_A64_CRYPTO_IF_PRESENT`, for aarch64. Also tested on x86_64 and armv8 Thumb 2 and behaves as expected there (not enabled).
=> SHA-256 and 512 support for old libc

library/entropy_poll.c, library/platform_util.c
=> fix build for midipix

library/gcm.c, tests/suites/test_suite_gcm.function, tests/suites/test_suite_gcm.misc.data
=> Add back restriction on AD length of GCM

include/psa/crypto_struct.h
Putting the `id` at the of the `psa_key_attributes_s` structure allows for a more efficient marshalling of the parameters around a transport channel which provides separation between a client view and a service view of the key parameters.
=> Put the id field at the end of the psa_key_attributes_s structure

library/alignment.h
Work around bug in old versions of gcc: gcc bug https://gcc.gnu.org/bugzilla/show_bug.cgi?id=94662 shows that __attribute__ aligned may be ignored.
=> Change unaligned access method for old gcc

tests/include/test/helpers.h
Prior to this, we were only detecting TSAN run under clang, and thus not running the platform test that will break under any kind of sanitiser. GCC also supports TSAN, so fix the detection code.
=> Stop platform test failures with GCC and TSAN

library/ecp_curves.c, library/ssl_tls.c
=> Backport 2.28: Reduce many unnecessary static memory consumption

library/ecp_curves.c, library/sha3.c, library/ssl_tls.c
There are some memory waste in the current implementation, especially the SSL/TLS module. Many static variables
could be declared const but not.
After the patch is applied, .data section of sample program ssl_client1 becomes 384 bytes smaller on AMD64.
=> Reduce many unnecessary static memory consumption

programs/pkey/dh_server.c, programs/test/benchmark.c
This PR replaces the legacy MBEDTLS_PRIVATE directly accessed fields with API calls.
Resolves #5015
=>  [MBEDTLS_PRIVATE] Update dhm context in programs

include/psa/crypto_extra.h, library/psa_crypto.c, library/psa_crypto_slot_management.c, library/psa_crypto_slot_management.h
Make functions which transition the state of key slots from PSA_SLOT_FULL to PSA_SLOT_EMPTY thread safe. Make our implementation of the [PSA key destruction API](https://arm-software.github.io/psa-api/crypto/1.1/api/keys/management.html#key-destruction) thread safe. Resolves #8677.
The work of this PR and the issues #8675, #8676 and #8412 is to ensure that API calls are linearizable and correct. To do this we rely on some properties, these properties need to be enforced. The relevant properties are:
- All calls to `psa_register_read`, `psa_unregister_read`, `psa_key_slot_state_transition`, `psa_wipe_key_slot` and `psa_key_slot_has_readers` are performed under the global mutex.
- Every API call has at most one point in time where effects are made visible to other threads. By effects here …
=> Make key destruction thread safe

include/mbedtls/check_config.h, include/mbedtls/config_adjust_legacy_crypto.h
Resolves #8796 - systematically chasing `#define`s in `check_config.h` -  but also a few more things I had noticed while looking at #8797.
=> Misc. clean-ups in `check_config.h`

library/ecp.c
The modified comment is indeed for the bigger scope(ended by the call to ecp_randomize_mxz()).
Fixes 5521b4ce37b2b7768a66c3a2b5a2fcff200ca11a.
=> Fix a comment in ecp

library/sha3.c
This saves a few bytes of code size. E.g. `arm-none-eabi-gcc -Os -mthumb -mcpu=cortex-m0plus`:
```
library/sha3.o: 4182 -> 4158 (diff: 24)
```
=> Inline the SHA3 parameters table into a switch

library/aesce.c, library/lms.c, library/pk.c
Mainly to fix an IAR warning in `pk.c`, but also fixes all remaining warnings for `-Wshorten-64-to-32` (from #8476 )
Fixes #7813
=> Compiler warning fixes

docs/driver-only-builds.md, programs/x509/cert_req.c, programs/x509/cert_write.c, tests/scripts/all.sh, tests/scripts/analyze_outcomes.py, tests/suites/test_suite_entropy.function
This PR add a couple of test components to `all.sh`:
- `component_test_psa_crypto_config_accel_hmac` which accelerates HMAC and all hash alorithms
- `component_test_psa_crypto_config_reference_hmac` which is used as reference component
Test coverage parity is ensured by adding the proper task to `analyze_outcomes.py`.
Resolves #8564
=> Add test for driver-only HMAC

include/mbedtls/check_config.h, include/mbedtls/mbedtls_config.h, include/mbedtls/pk.h, tests/suites/test_suite_pk.function
Fix: #8167
**How to reproduce this issue: (based on f5e46fd)**
1. Add following to `configs/config-tfm.h`
```
#define MBEDTLS_PK_PARSE_C
#define MBEDTLS_PK_WRITE_C
#define MBEDTLS_PK_C
#define MBEDTLS_ASN1_PARSE_C
#define MBEDTLS_ASN1_WRITE_C
#undef MBEDTLS_PSA_P256M_DRIVER_ENABLED
```
2. Run `./tests/scripts/test-ref-configs.pl` for `config-tfm.h`, then see error
```
/usr/bin/ld: ../../library/libmbedcrypto.a(pkparse.o): in function `pk_use_ecparams':
pkparse.c:(.text+0x47): undefined reference to `mbedtls_oid_get_ec_grp'
/usr/bin/ld: ../../library/libmbedcrypto.a(pkparse.o): in function `pk_get_pk_alg':
pkparse.c:(.text+0x122): undefined reference to `mbedtls_oid_get_pk_alg'
/usr/bin/ld: pkparse.c:(.text+0x132): undefined reference to `mbedtls_oid_get_ec_grp_algid'
```
Please tick as …
=> PK parse and PK write: add dependency check with OID

CMakeLists.txt, ChangeLog.d/pkg-config-files-addition.txt, pkgconfig/CMakeLists.txt, pkgconfig/JoinPaths.cmake, pkgconfig/mbedcrypto.pc.in, pkgconfig/mbedtls.pc.in, pkgconfig/mbedx509.pc.in
Add three package config files for mbedtls, mbedcrypto and mbedx509. Also update various project variables so the generated PC files have the required data needed without hardcoding it everywhere.
This will help distros package the project following existing conventsions between a normal and -devel package that includes the headers and .pc files for pkg-config aware consumers.
Fixes: #228
=> pkg-config: add initial pkg-config files

programs/ssl/ssl_client2.c
Use mbedtls_ssl_session_init() to init variable just like session-family APIs described
=> use mbedtls_ssl_session_init() to init session variable

include/psa/crypto_values.h, tests/scripts/depends.py, tests/suites/test_suite_pk.function
Backport of minor bug fixes in tests from https://github.com/Mbed-TLS/mbedtls/pull/8807.
Priority: high even though the bugs are not high-priority, because this is a backport of a high-priority PR.
=> Backport 2.28: bugs fixed in "Implement mbedtls_pk_import_into_psa"

ChangeLog.d/gcm-large-tables.txt, include/mbedtls/gcm.h, include/mbedtls/mbedtls_config.h, library/gcm.c, tests/scripts/all.sh
Currently, mbedTLS uses Shoup's 4-bit tables to speed up GCM calculations in software, while other crypto libraryies such as openssl or wolfssl also support 8-bit tables to increase the GCM throughput.
In this PR, we introduce the option to activate precalculated 8-bit tables by using the new MBEDTLS_GCM_LARGE_TABLE configuration parameter. When executed on a 64-bit Intel architecture, with deactivated AESNI extensions, we can increase the GCM throughput by roghly 30 percent. To compare different variants, we checked out the corresponding branches and activated or deactivated AESNI or GCM_LARGE_TABLE:
```
PR8716_noAESNI 128 mean: 197833 max: 203561 gain: 0.9886305135452789
PR8716_noAESNI 192 mean: 183033 max: 187836 gain: 0.9884024415912439
PR8716_noAESNI 256 mean: 170962 max: 175374 …
```
=> Use large GCM tables

library/psa_crypto.c
Makes all multi-part and restartable operations thread-safe. Resolves #8412.
The work of this PR and the issues #8675, #8676 and #8677 is to ensure that API calls are linearizable and correct. To do this we rely on some properties, these properties need to be enforced once these PRs are merged. The relevant properties are:
- All calls to `psa_register_read`, `psa_unregister_read`, `psa_key_slot_state_transition`, `psa_wipe_key_slot` and `psa_key_slot_has_readers` are performed under the global mutex.
- Every API call has at most one point in time where effects are made visible to other threads. By effects here we mean something like a key being created and now existing in the eyes of other threads, or a key being destroyed. We do not need to consider resource constraints here.
- Any …
=> Make multi-part operations thread-safe

library/psa_crypto_slot_management.c
This is a very simple case of the usual get_and_lock -> unregister_under_mutex approach.
This is the only unaccounted for `unregister_read` (the rest remaining in development are covered by #8833). The function is deprecated, but we need to keep it thread safe.
=> Make psa_open_key threadsafe

tests/src/helpers.c, tests/src/threading_helpers.c
After comments on the recent deadlock fix, attempt to improve the test info data acessors:
1. Mark all internal only functions as static, and rename them as `*_internal` in order to make them more obvious (in line with the aforementioned fix). Also add a comment block to further explain the mutex policies.
2. Whilst checking all the internal functions I spotted two cases which should have had mutex locks but did not (likely due to crossover between two PRs) and have fixed these.
=> Improve test info data accessors

library/pk_wrap.c
Add missing casts to fix IAR warnings
=> Add missing casts to fix IAR warnings

include/mbedtls/ssl.h, library/ssl_debug_helpers.h, library/ssl_misc.h, library/ssl_msg.c, library/ssl_tls13_client.c, library/ssl_tls13_generic.c, library/ssl_tls13_server.c, programs/ssl/ssl_client2.c, tests/include/test/ssl_helpers.h, tests/opt-testcases/tls13-misc.sh, tests/suites/test_suite_ssl.data, tests/suites/test_suite_ssl.function
Second PR of two addressing #6340 .
=> TLS 1.3: Add mbedtls_ssl_write_early_data() API

docs/psa-driver-example-and-guide.md, include/psa/crypto_extra.h, include/psa/crypto_struct.h, library/psa_crypto.c, library/psa_crypto_aead.c, library/psa_crypto_cipher.c, library/psa_crypto_core.h, library/psa_crypto_ecp.c, library/psa_crypto_ffdh.c, library/psa_crypto_rsa.c, library/psa_crypto_slot_management.c, library/psa_crypto_storage.c, library/psa_crypto_storage.h, scripts/data_files/driver_templates/psa_crypto_driver_wrappers.h.jinja, scripts/data_files/driver_templates/psa_crypto_driver_wrappers_no_static.c.jinja, tests/src/drivers/test_driver_signature.c, tests/suites/test_suite_psa_crypto_persistent_key.function, tests/suites/test_suite_psa_crypto_se_driver_hal.function, tests/suites/test_suite_psa_crypto_se_driver_hal_mocks.function, tests/suites/test_suite_psa_crypto_slot_management.function
Resolves https://github.com/Mbed-TLS/mbedtls/issues/6496.
This is an ABI change so we won't be able to do it in a patch update to 3.6 LTS.
Supersedes https://github.com/Mbed-TLS/mbedtls/pull/7743. This is a complete re-do, not a rewrite, because https://github.com/Mbed-TLS/mbedtls/pull/8840 completely changed the deal. I went further and removed the flags field from the default configuration. Unlike https://github.com/Mbed-TLS/mbedtls/pull/7743, I didn't change how slot numbers are stored in key slots. The reason I didn't make this change is that it's a bit trickier than the rest, and it's an internal refactoring that we can do later.
I recommend reviewing commit by commit. In particular, two commits are mechanical search-and-replace.
=> Merge psa_core_key_attributes_t back into psa_key_attributes_t

tests/include/test/drivers/config_test_driver.h, tests/scripts/all.sh
As a precursor to adding threading tests, it had been noticed that when running the driver tests, `MBEDTLS_THREADING_C` and `MBEDTLS_THREADING_PTHREAD` were defined (as part of a full config), however within libtestdriver1, `LIBTESTDRIVER1_MBEDTLS_THREADING_C` and `LIBTESTDRIVER1_MBEDTLS_THREADING_PTHREAD` were **not** defined.
This lead to a situation whereby when running the driver tests the requirements for the multithreaded tests were met (predicated on `MBEDTLS_*` defines), so they were running, however safety mutexes were removed due to the lack of the `LIBTESTDRIVER1_*` defines. This obviously causes some fairly serious test failures.
Attempt to fix this for all driver tests, by basically setting the requisite defines for the driver build config if they are set in the normal …
=> Ensure drivers have threading enabled if required

library/psa_crypto.c
When building with -Og (specifically Zephyr with
CONFIG_DEBUG_OPTIMIZATIONS=y) one observes the following warning:
'shared_secret' may be used uninitialized [-Werror=maybe-uninitialized]
Fix this by zero initializing 'shared_secret' similar to the issue addressed in commit 2fab5c960 ("Work around for GCC bug").
=> library: psa_crypto: Explicitly initialize shared_secret

library/ssl_tls13_server.c, tests/opt-testcases/tls13-kex-modes.sh, tests/opt-testcases/tls13-misc.sh
=> TLS 1.3: SRV: Improve key exchange mode selection

include/mbedtls/ssl.h, library/ssl_misc.h, library/ssl_msg.c, library/ssl_tls.c, library/ssl_tls13_generic.c, library/ssl_tls13_server.c, tests/include/test/ssl_helpers.h, tests/src/test_helpers/ssl_helpers.c, tests/suites/test_suite_ssl.data, tests/suites/test_suite_ssl.function
=> TLS 1.3: Enforce max_early_data_size on server

ChangeLog.d/8825.txt, include/mbedtls/psa_util.h, library/psa_crypto.c, library/psa_crypto_random_impl.h, library/psa_util.c, library/psa_util_internal.h, tests/src/psa_crypto_stubs.c
Resolves #8825.
It does not strictly depends on #8842, but I suspect there might a conflict between the two.
=> Improve support of mbedtls_psa_get_random in client-only builds

library/bignum.c
Follow-up to #8831 which unfortunately triggers an IAR warning (for something that is a non-issue):
```
MBEDTLS_MPI_CHK(mbedtls_mpi_core_get_mont_r2_unsafe(&RR, N));
^
"/home/davrod01/code/mbedtls/library/bignum.c",1656  Error[Pe546]: transfer of
control bypasses initialization of:
variable "mm" (declared at line 1695)
```
=> Fix IAR warning

ChangeLog.d/8824.txt
I've just realized that I made a mistake in https://github.com/Mbed-TLS/mbedtls/issues/8824. I mostly looked at the sign/verify functions, which happily use the wrong algorithm. The encrypt/decrypt functions actually error out if the padding mode specifies V21.
The [check in `rsa_decrypt_wrap`](https://github.com/Mbed-TLS/mbedtls/blob/mbedtls-3.2.0/library/pk_wrap.c#L382) (and the same in `rsa_encrypt_wrap`) was added in 8e80504b46764c2a590a6290cccc5716ff51ea79 which was part of the [pull request](https://github.com/Mbed-TLS/mbedtls/pull/5519) that added the feature, and it was removed in https://github.com/Mbed-TLS/mbedtls/pull/8826 which fixed the bug. So `development` did not have `mbedtls_pk_encrypt` or `mbedtls_pk_decrypt` performing the wrong algorithm at any point, just failing.
=> mbedtls_pk_decrypt/encrypt actually check the padding mode

include/mbedtls/pk.h
Fix the Doxygen rendering of the documentation of functions introduced in #8807. Compare [old](https://mbed-tls--8807.org.readthedocs.build/projects/api/en/8807/api/file/pk_8h/#pk_8h_1a7aa7b33cffb6981d95d1632631de9244), [new](https://mbed-tls--8887.org.readthedocs.build/projects/api/en/8887/api/file/pk_8h/#pk_8h_1a7aa7b33cffb6981d95d1632631de9244)
=> Fix intended code blocks that were not suitably indented

CMakeLists.txt
Set the version of the project within the project() declaration so other cmake scripts can use PROJECT_VERSION.
=> project: set version

library/cmac.c
Very small change to get some perf improvement in CMAC. This benefits PBKDF2 with CMAC significantly - the CMAC parts of the PBKDF2 tests are about 16% faster with this change (`test_suite_psa_crypto.pbkdf2` is ~5% faster overall with this change, which is worth having). Also saves 8 bytes.
=> CMAC size and perf

include/mbedtls/mbedtls_config.h, library/psa_crypto_storage.h, tests/scripts/all.sh
This has been replaced by a new driver interface which does support thread-safety.
Explicitly remove the deprecated flag from the TSan config. Closes #8849.
=> Officially document non thread-safety of MBEDTLS_PSA_CRYPTO_SE_C

ChangeLog.d/add_ssl_session_accessors.txt, include/mbedtls/ssl.h, include/mbedtls/ssl_ciphersuites.h, tests/suites/test_suite_ssl.data, tests/suites/test_suite_ssl.function
The ps is adding accessors for the following members of the `mbedtls_ssl_session`
- `int MBEDTLS_PRIVATE(ciphersuite)` -> `mbedtls_ssl_session_get_ciphersuite_id()`
- `size_t MBEDTLS_PRIVATE(id_len)` -> `mbedtls_ssl_session_get_id_len()`
-`unsigned char MBEDTLS_PRIVATE(id)[32` -> `mbedtls_ssl_session_get_id()`
As well as one accessor for the `mbedtls_ssl_ciphersuite_t` struct
- `uint8_t MBEDTLS_PRIVATE(cipher)` -> `mbedtls_ssl_ciphersuite_get_id()`
Resolves #8529
=> [MBEDTLS_PRIVATE] Add accessor for session and ciphersuite_id

library/cmac.c, library/gcm.c
Surprisingly, `gcc -O3` generates a few (spurious) warnings that other optimisation levels do not (the warnings are also platform dependent).
These were observed on x86 (gcm) and aarch64, thumb2 and x86 (cmac).
=> Fix gcc -O3 warnings

include/mbedtls/ssl.h, library/ssl_debug_helpers.h, library/ssl_misc.h, library/ssl_msg.c, library/ssl_tls.c, library/ssl_tls13_client.c, tests/suites/test_suite_ssl.data, tests/suites/test_suite_ssl.function
Follow-up of #8760, addressing comments https://github.com/Mbed-TLS/mbedtls/pull/8760#discussion_r1505805139, https://github.com/Mbed-TLS/mbedtls/pull/8760#discussion_r1505807730 and https://github.com/Mbed-TLS/mbedtls/pull/8760#discussion_r1505817245.
=> TLS 1.3: CLI: Split early data user status and internal state

scripts/lcov.sh
1. We added multithreaded tests. They cause
```
lcov: WARNING: negative counts found in tracefile Coverage/tmp/tests.info
```
This is [known to be caused by a bug in gcov](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=67937), possibly due to a race condition. We may be getting slightly bad data about a few test cases, but we can live with that.
2. Lcov had a [bug](https://github.com/linux-test-project/lcov/commit/632c25a0d1f5e4d2f4fd5b28ce7c8b86d388c91f) in a warning handler that caused it to change to the root directory before writing the output file.
```
lcov: ERROR: cannot write to Coverage/tmp/all.info!
```
So when the warning triggers, we don't get output at all. We can't live with that.
As we are nearing a release, I am proposing a minimalistic workaround that just prevents the …
=> Work around a bug in ancient lcov

tests/compat.sh, tests/scripts/analyze_outcomes.py, tests/scripts/check_test_cases.py, tests/ssl-opt.sh
~Depends on: #8561~
Same topic: #8586, #8594
Fix: https://github.com/Mbed-TLS/mbedtls/pull/8561#issuecomment-1831125509
In `analyze_outcomes.py`, we use "\<suite\>;\<case\>" generated by `check_test_cases.py` as keys and check if they are excuted at lease once. So, it is critical to make the generated keys consistent with that in the outcomes files.
=> Fix wrong suite name in check_test_cases.py

programs/test/metatest.c
After getting caught with deadlock issues when these particular tests fail, add a metatest to test them failing.
=> Add metatests for failing TEST_EQUAL and TEST_LE_*

include/mbedtls/ssl_ticket.h, library/ssl_ticket.c, library/ssl_tls13_client.c, library/ssl_tls13_server.c, programs/ssl/ssl_client2.c, tests/ssl-opt.sh
Enforce ticket maximum lifetime on server side and discard tickets with 0 lifetime on client side.
Follow-up of #8574, #8525 and #8581
From #8525 and #8581 I've kept:
- the enforcement of the ticket maximum lifetime on server. If the ticket module is set up with a ticket lifetime that is invalid for TLS 1.3 (greater than 7d) then when issuing the first ticket with that lifetime we fail the connection.
- discarding tickets with 0 lifetime on client side
I have not:
- added the ticket lifetime to the ticket data. The lifetime is solely enforced by the ticket module.
- enforced a non-zero lifetime on server side 
Fix #7795
=> TLS 1.3: Enforce ticket maximum lifetime and discard tickets with 0 lifetime

programs/test/metatest.c
After getting caught with deadlock issues when these specific tests fail, add a metatest to test them failing.
This is a straight backport of  #8829
=> [Backport 2.28] Add metatests for failing TEST_EQUAL and TEST_LE_*

tests/ssl-opt.sh
Improve the testing of the version negotiation on server side.
=> TLS: Improve server version negotiation testing

ChangeLog.d/fix-alpn-negotiating-bug.txt, library/ssl_tls.c, library/ssl_tls13_server.c, tests/include/test/ssl_helpers.h, tests/src/test_helpers/ssl_helpers.c, tests/suites/test_suite_ssl.data, tests/suites/test_suite_ssl.function
Check if new session has the same  ALPN  as old session when receiving early data and if not reject early data.
fix #6355 
Depends on #8858
=> Check ALPN when receiving early data

ChangeLog.d/fix-alpn-negotiating-bug.txt, library/ssl_tls.c
=> Backport 2.28: Fix bug in ALPN loading from serialised session

include/mbedtls/threading.h, library/psa_crypto.c, library/psa_crypto_slot_management.c, library/threading.c, tests/suites/test_suite_psa_crypto_init.data, tests/suites/test_suite_psa_crypto_init.function
Make the contents of PSA `global_data` thread safe. Resolves #8425. Resolves #7945
- It should now be safe to call psa_crypto_init() on multiple threads, either concurrently or sequentially.
- Although some protection has now been done on `mbedtls_psa_crypto_free()` it is still not entirely thread safe, even if no operations are running at the time. This is annoying as I could have used this to improve testing, however we never claimed it would be thread safe.
- The Macro PSA_DONE() is still definitely not thread safe, due to the checks it does.
- In this PR we only attempt to make access to global_data.rng_state and global_data.rng thread safe. We are not attempting to make the random number generator thread safe, as that was (mostly) done elsewhere. I have seen an existing issue with …
=> Make PSA global_data thread safe

tests/suites/test_suite_pk.data, tests/suites/test_suite_pk.function
Resolves #8778.
I generated the test cases automatically, but I didn't think it was worth the hassle of a new script to generate pk test cases. We might want to make a `generate_pk_tests.py` that covers most of the test cases we've added this quarter though. For each function I thought the situation was borderline between writing+checking test cases and coverage individually vs writing+checking a script.
=> pk_import_into_psa: test persistent keys

ChangeLog.d/add_threading_changelog.txt
As per #8436 Add the issues fixed to the threading changelog entry. Resolves #8436
=> Add issues fixed to threading MVP changelog entry

ChangeLog.d/enable-tls13-by-default.txt, include/mbedtls/mbedtls_config.h, tests/scripts/all.sh
Enable the TLS 1.3 protocol in the default configuration.
=> Enable TLS 1.3 by default

ChangeLog.d/fix-null-dereference-verify-ext.txt, library/pk.c, tests/suites/test_suite_pk.function
This fixes a NULL dereference crash in `mbedtls_pk_verify_ext()` that was possible when this function was called with an opaque RSA key. The issue was found while working at #8937.
=> [Bugfix] Fix null dereference in `mbedtls_pk_verify_ext()`

BRANCHES.md, BUGS.md, README.md
Backport of #8941 . BRANCHES.md has simply been replaced by the version in 8941, as this document should be version-independent. 
=> Update BRANCHES for 3.6 - 2.28 backport

BRANCHES.md, BUGS.md, README.md
Update BRANCHES.md, and replace references to `master` with `main` - I propose that from 3.6.0, we maintain both `master` and `main`, but only document `main`. At some point in the future (4.0?) we could drop `master`.
I propose to change `master` to be a tag which points at `main`, to ensure consistency. `main` IMO should also be a tag, which in turn points at the latest release (currently it's a branch).
=> Update BRANCHES for 3.6

tests/compat.sh
Same topic: #8575, #8594
`compat.sh` does not correctly list test cases it runs. E.g:
We got on CI:
```
[2023-11-30T13:36:16.703Z] Warning: Test case not executed: compat;G->m dtls12,yes TLS_DHE_PSK_WITH_AES_128_CBC_SHA
...
[2023-11-30T13:36:16.703Z] Warning: Test case not executed: compat;G->m dtls12,yes TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA
```
But actually we don't run these kinds of tests:
- PSK cipher suites do not allow client certificate verification. No PSK cipher suites tests with `VERIFY=YES`
- We workarround all `G->m dtls12,yes ,<cipher_suite>` tests for some reason.
=> Fix fake cases listed of compat.sh

tests/compat.sh
This is the 2.28 backport of #8586.
The backport of the 1st commit is not trivial as the loops are nested differently in 2.28 (the various `add_xxx_ciphersuites` function access the `MODE` variable).
The backport of the 2nd commit is trivial.
=> [Backport 2.28] Fix fake cases listed of compat.sh

tests/suites/test_suite_pk.function
=> Unify consistency tests for mbedtls_pk_import_into_psa and mbedtls_pk_copy_from_psa

.github/pull_request_template.md
We now have two LTS branches to backport to.
=> Add 3.6 backport checkbox to the PR template

docs/use-psa-crypto.md, include/mbedtls/pk.h, library/pk.c, tests/suites/test_suite_pk.function
~Depends on #8942.~
~Depends on #8951 (because a limitation for RSA opaque keys is lifted there and it must be documented here).~
Resolves #8712.
=> Clarify the documentation of mbedtls_pk_setup_opaque

docs/use-psa-crypto.md, include/mbedtls/pk.h, library/pk.c, tests/suites/test_suite_pk.function
This is the 3.6 backport of #8937 (all commits just cherry-picked from there).
=> [Backport 3.6] Clarify the documentation of mbedtls_pk_setup_opaque

tests/suites/test_suite_pk.function
This is the 3.6 backport of #8987
=> [Backport 3.6] Test gap: mbedtls_pk_check_pair with MBEDTLS_PK_OPAQUE

tests/suites/test_suite_pk.function
Fixes #8903
Following the [discussion](https://github.com/Mbed-TLS/mbedtls/issues/8903#issuecomment-2012046448) on the original issue this PR implements the following:
> perhaps also add a test that calling check_pair() on a opaque RSA keys indeed fails with an appropriate error (as opposed to crashing or doing something silly)?
=> Test gap: mbedtls_pk_check_pair with MBEDTLS_PK_OPAQUE

tests/include/test/drivers/key_management.h, tests/src/drivers/test_driver_key_management.c, tests/suites/test_suite_psa_crypto_driver_wrappers.data, tests/suites/test_suite_psa_crypto_driver_wrappers.function, tests/suites/test_suite_psa_crypto_se_driver_hal.function, tests/suites/test_suite_x509parse.data, tests/suites/test_suite_x509parse.function
This is the 2.28 backport of ~#8594~ #8997
Not trivial, as some commits were not applicable, the others had conflicts. Details:
- a2030bfee984 Correct dependancy on `MBEDTLS_X509_INFO` for x509parse
-> typo present but different resolution
- 77a6940b1530 Fix typo in ssl test suite
-> typo not present in 2.28, nothing to do
- 07d215646295 Fix wrong dependency in psa_crypto_pake suite
-> test suite not present in 2.28, nothing to do
- b4ac2ca9ab8c Fix wrong dependency in psa_crypto_driver_wrappers suite
-> typo not present in 2.28, nothing to do (and no other MBEDTLS_PSA_WANT)
- 6a42399e26f1 Add missing definition of AT_LEAST_ONE_BUILTIN_KDF
-> applied, contextual differences + fixed the `&` vs `&&` thing at the same time
- aaf66521dfd0 Add missing dependency of fallback test in driver …
=> [Backport 2.28] Fix wrong dependencies in test cases

ChangeLog.d/fix-compilation-when-memcpy-is-function-like-macro.txt, library/ssl_tls13_generic.c
=> Backport 3.6: Fix compilation when memcpy() is a function-like macro

ChangeLog.d/fix-compilation-when-memcpy-is-function-like-macro.txt, library/ssl_tls13_generic.c
=> Fix compilation when memcpy() is a function-like macro

ChangeLog.d/asn1-missing-guard-in-rsa.txt, include/mbedtls/config_adjust_legacy_crypto.h
=> [3.6 backport] Asn1 missing guard in rsa backport

ChangeLog.d/asn1-missing-guard-in-rsa.txt, include/mbedtls/config_adjust_legacy_crypto.h
RSA needs ASN1 functions to parse/write private and public keys, but there is no guards in the code for that. So we need to enable ASN1 support whenever RSA is enabled.
Resolves #9041.
=> Auto-enable ASN1 when RSA is enabled

tests/scripts/all.sh
This is the first PR for #8153 and https://github.com/Mbed-TLS/TF-PSA-Crypto/issues/63. The end goal is to remove the legacy config symbols in `mbedtls_config.h`, and instead use the equivalents in `crypto_config.h` - without losing test coverage for the CI.
This pattern, if approved, will be applied to all relevant CI components.
The effect of this PR is that this component will still work as intended once `PSA_CRYPTO_CONFIG` is enabled by default. Note that: until `MBEDTLS_GENPRIME` is removed from `mbedtls_config.h` we cannot remove the `unset MBEDTLS_GENPRIME` call in this config, as `config_adjust_legacy_from_psa.h` can not undefine symbols defined elsewhere (`MBEDTLS_GENPRIME` is defined in the default `mbedtls_config.h`). We also cannot remove `MBEDTLS_GENPRIME` from …
=> Make component_test_psa_crypto_rsa_no_genprime work with PSA_CRYPTO_CONFIG set

tests/compat.sh, tests/scripts/all.sh, tests/scripts/analyze_outcomes.py, tests/scripts/basic-build-test.sh
In 2.28 (but not in 3.6 or development), `analyze_outcomes.py` lists 1000+ `compat.sh` test cases as not executed on the CI. While investigating that, I noticed that there are also tests passing in `outcomes.csv` that are not listed by `--list-test-cases`. This PR makes things consistent.
The biggest inconsistency was the different naming schemes were used in `--list-test-cases` and in writing to the outcomes file. (In 3.x we fixed this by using the standard name everywhere, but in 2.28 we still report what we have to pass to the client as the name.)
Then there was a number of special cases, all of them related to things that have been removed in 3.0: SSLv3 / TLS < 1.2, RC4, single-DES suites...
However a few of the changes (reporting all skipped tests instead of silently ignoring some of …
=> [2.28] Fix compat.sh tests (reported as) not executed

tests/compat.sh, tests/scripts/all.sh, tests/scripts/basic-build-test.sh
This is the forward-port to 3.6 of the relevant bits of #9019 / backport to 3.6 of #9022
=> [3.6] Small fixes to compat.sh (partial forward-port)

ChangeLog.d/fix_ubsan_mp_aead_gcm.txt, library/psa_crypto.c
With multipart AEAD, if we attempt to add zero length additional data, then with the buffer sharing fixes this can now lead to undefined behaviour when using gcm because where we had a valid pointer but zero length before buffer sharing, we now have a NULL pointer and zero length.
Fix this by returning early, as there is nothing to do if the input length is zero. Fixes #9064
=> Add early exit if zero length AEAD additional data passed in.

ChangeLog
Add missing reference to CVE-2024-30166 in security entry
=> ChangeLog: Add missing reference to CVE in security entry

ChangeLog.d/fix-concurrently-loading-non-existent-keys.txt, library/psa_crypto_slot_management.c, library/psa_crypto_slot_management.h
=> Backport 3.6: Wipe the returned slot pointer upon failure in `psa_get_and_lock_key_slot`

ChangeLog.d/fix-concurrently-loading-non-existent-keys.txt, library/psa_crypto_slot_management.c, library/psa_crypto_slot_management.h
Throughout the code we assume that it is valid to call `psa_unregister_read(slot)` after calling `psa_get_and_lock_key_slot(key, slot)`, even if the latter call failed. This assumption previously didn't hold, which meant that a set of concurrent key management calls could render the key store in an inconsistent state. This PR makes the assumption official, and upholds it.
Without this change, a bug can occur as follows:
1. Thread A calls some operation on a key `key`.
2. Thread A initializes `slotA` to `NULL`.
3. Thread A calls `psa_get_and_lock_key_slot(key, &slotA)`. When A takes the mutex `key` does not refer to any valid key (it may have existed but been deleted by another thread, or may have never existed).
4. Since the key is not in the key store, the call will reserve some free key …
=> Wipe the returned slot pointer upon failure in `psa_get_and_lock_key_slot`

ChangeLog.d/fix-secure-element-key-creation.txt, library/psa_crypto.c
Trivial backport of #8538. Add some error handling for the call to `psa_copy_key_material_into_slot` in `psa_start_key_creation`. Fixes #8537
=> Backport 2.28: Fix error handling for secure element keys in `psa_start_key_creation`

programs/ssl/ssl_mail_client.c
This is the 2.28 backport of #8897. The backport is trivial.
=> Backport 2.28: ssl_mail_client: Fix unbounded write of sprintf()

ChangeLog.d/fix-secure-element-key-creation.txt, library/psa_crypto.c
Add some error handling for the call to `psa_copy_key_material_into_slot` in `psa_start_key_creation`. Fixes #8537
=> Fix error handling for secure element keys in `psa_start_key_creation`

ChangeLog.d/fix-secure-element-key-creation.txt, library/psa_crypto.c
Trivial 3.6 backport of #8538.
=> Backport 3.6: Fix error handling for secure element keys in `psa_start_key_creation`

programs/ssl/ssl_mail_client.c
Trivial backport of https://github.com/Mbed-TLS/mbedtls/pull/8897
=> Backport 3.6: ssl_mail_client: Fix unbounded write of sprintf()

programs/ssl/ssl_mail_client.c
These calls to sprintf may overflow buf because opt.mail_from and opt.mail_to are controlled by users. Fix by replacing sprintf with snprintf.
* See our [Guidelines for Contributors](https://mbed-tls.readthedocs.io/en/latest/reviews/review-for-contributors/) for more details about the review …
=> ssl_mail_client: Fix unbounded write of sprintf()

ChangeLog
=> [Backport 3.6] ChangeLog: Add missing reference to CVE in security entry

library/md.c
This PR fixes guards for `mbedtls_md_error_from_psa()`.
Resolves #9068.
=> Undefined reference to mbedtls_md_error_from_psa() function

library/md.c
=> [Backport 3.6] Undefined reference to mbedtls_md_error_from_psa() function

ChangeLog.d/fix-redefination_warning_messages_for_GNU_SOURCE.txt, library/entropy_poll.c
This commit solves the issue of redefinition warning messages for _GNU_SOURCE while building on Linux platform.
=> Backport 2.28: Fixed issue of redefinition warning messages for _GNU_SOURCE

ChangeLog.d/fix-redefination_warning_messages_for_GNU_SOURCE.txt, library/entropy_poll.c, library/sha256.c
This commit solves the issue of redefinition warning messages for _GNU_SOURCE while building on Linux platform.
=> Backport 3.6: Fixed issue of redefinition warning messages for _GNU_SOURCE

ChangeLog.d/fix-redefination_warning_messages_for_GNU_SOURCE.txt, library/entropy_poll.c, library/sha256.c
This commit solves the issue of redefinition warning messages for _GNU_SOURCE while building on Linux platform.
=> Fixed redefination warning messages for _GNU_SOURCE

tests/scripts/all.sh
This PR adds a new `component` in `all.sh` to build and test `psasim`.
Resolves #8962
=> Add a component to all.sh to build and run psasim

CMakeLists.txt, tests/CMakeLists.txt, tests/scripts/all.sh
Fixes a fuzzing build failure.
Move test data file generation to the main CMakeLists.txt and perform it whenever either `ENABLE_TESTING` or `ENABLE_PROGRAMS` is on.
=> Move some test data generation to main CMakeLists.txt (/ fix fuzzing build failures)

.gitignore, tests/.gitignore
This is the backport of #9129.
It simply cherry-picks commits from the #9129 to `mbedtls-3.6` branch.
=> [Backport] Update gitignore for `test_keys.h`, `test_certs.h` and `.vscode`

.gitignore, tests/.gitignore
This quick PR fixes a missing update to `.gitignore` in #9017: since `test_certs.h` and `test_keys.h` are automatically generated at build time, they should not be tracked.
While at this, this PR also adds `.vscode` to the `.gitignore` file at the MbedTLS root in order to ignore that local configuration folder automatically created by VScode.
=> Update gitignore for `test_keys.h`, `test_certs.h` and `.vscode`

ChangeLog.d/pk-norsa-warning.txt, docs/driver-only-builds.md, library/pk.c, tests/scripts/analyze_outcomes.py, tests/ssl-opt.sh
Trivial backport of https://github.com/Mbed-TLS/mbedtls/pull/9067
=> Backport 3.6: Fix skipped tests in configurations without RSA

tests/ssl-opt.sh
Backport of incidental bug fixes and improvements from https://github.com/Mbed-TLS/mbedtls/pull/9067 (the main issue doesn't apply in 2.28).
=> Backport 2.28: Fix skipped tests in configurations without RSA

tests/scripts/analyze_outcomes.py
Fixes #8300.
Requires https://github.com/Mbed-TLS/mbedtls-test/pull/166 (before that, we wouldn't have the necessary Python environment to run `make generated_files`).
=> Generate test data before coverage analysis

tests/scripts/analyze_outcomes.py
Trivial backport of https://github.com/Mbed-TLS/mbedtls/pull/9159
=> Backport 3.6: Generate test data before coverage analysis

ChangeLog.d/build_without_check_config.txt, library/oid.c, library/psa_crypto_rsa.c, library/ssl_msg.c, library/x509_crt.c, programs/test/udp_proxy.c, tests/scripts/all.sh, tests/src/test_helpers/ssl_helpers.c
Including `mbedtls/check_config.h` from `mbedtls/config.h` is optional. If done, `limits.h` gets included. If not done, we were missing the inclusion of `limits.h` in several source files. Fix this and add a test build that doesn't include `mbedtls/check_config.h`. Fixes #9152.
Not applicable to ≥3.0 because there `check_config.h` has no side effects (they're in `build_info.h`).
=> 2.28 only: Fix the build without check_config.h (inclusion of limits.h)

library/ssl_tls12_server.c
A large block of code is only reachable if MBEDTLS_PK_USE_PSA_EC_DATA is enabled, i.e. if MBEDTLS_USE_PSA_CRYPTO is enabled with driver-only ECC. Compilers are likely to figure it out, but still, for clarity and robustness, do guard that block of code with the appropriate conditional compilation guard.
Found by Coverity.
=> Guard configuration-specific code in ssl_tls12_server.c

scripts/code_style.py, tests/scripts/check_files.py
Extend basic checks and C coding style checks to framework files
Progresses https://github.com/Mbed-TLS/mbedtls-framework/issues/7
=> Extend basic checks and C coding style check to framework files

scripts/code_style.py, tests/scripts/check_files.py
Backport of #9088, without the commits updating the framework commit as there is no need for them.
=> [Backport 3.6] Extend basic checks and C coding style check to framework files

ChangeLog.d/check-config.txt, include/mbedtls/build_info.h, include/mbedtls/check_config.h, include/mbedtls/config_adjust_legacy_crypto.h, include/mbedtls/config_adjust_legacy_from_psa.h, include/mbedtls/config_adjust_psa_from_legacy.h, include/mbedtls/config_adjust_psa_superset_legacy.h, include/mbedtls/config_adjust_ssl.h, include/mbedtls/config_adjust_x509.h, include/psa/crypto_adjust_auto_enabled.h, include/psa/crypto_adjust_config_dependencies.h, include/psa/crypto_adjust_config_key_pair_types.h, include/psa/crypto_adjust_config_synonyms.h
It's technically possible to `#include` those headers, so users are doing it, and then complaining about the consequences. Resolve #9147.
Including `*adjust*` directly, as several projects have done, may lead to inconsistencies in buffer size calculations, which could result in buffer overflows. Since this is dangerous, deliberately break the build.
=> Backport 3.6: Document check-config.h and *adjust*.h as internal headers

ChangeLog.d/check-config.txt, include/mbedtls/build_info.h, include/mbedtls/check_config.h, include/mbedtls/config_adjust_legacy_crypto.h, include/mbedtls/config_adjust_legacy_from_psa.h, include/mbedtls/config_adjust_psa_from_legacy.h, include/mbedtls/config_adjust_psa_superset_legacy.h, include/mbedtls/config_adjust_ssl.h, include/mbedtls/config_adjust_x509.h, include/psa/crypto_adjust_auto_enabled.h, include/psa/crypto_adjust_config_dependencies.h, include/psa/crypto_adjust_config_key_pair_types.h, include/psa/crypto_adjust_config_synonyms.h
It's technically possible to `#include` those headers, so users are doing it, and then complaining about the consequences. Resolve https://github.com/Mbed-TLS/mbedtls/issues/9147.
=> Document check-config.h and *adjust*.h as internal headers

include/psa/crypto.h
This is the backport of #9220
This PR cherry-picks commit from the original one.
=> [Backport 2.28] fix documentation of psa_hash_compare()

include/psa/crypto.h
This is the backport of  #9220
Commits are cherry-picked from the original PR.
=> [Backport 3.6] fix documentation of psa_hash_compare()

scripts/code_style.py
=> [Backport 3.6] Allow `code_style.py` to work from a git hook

scripts/code_style.py
When running a git hook, git sets certain environment variables (such as `GIT_INDEX_FILE`) which force git to look at the main repository, overriding other options. This trips up code_style.py whenever it tries to run a git command on the framework submodule.
Fix this by explicitly clearing git-related environment-variables before running git commands on the framework. This is recommended by [git's documentation](https://git-scm.com/docs/githooks):
> Environment variables, such as GIT_DIR, GIT_WORK_TREE, etc., are
> exported so that Git commands run by the hook can correctly locate
> the repository. If your hook needs to invoke Git commands in a
> foreign repository or in a different working tree of the same
> repository, then it should clear these environment variables so
> they do not …
=> Allow `code_style.py` to work from a git hook

tests/scripts/check-python-files.sh
=> [Backport 3.6] Extend python checks to framework scripts

tests/scripts/check-python-files.sh
Check scripts in the `framework` directory in `check-python-files.sh`.
Part of the solution to Mbed-TLS/mbedtls-framework#7
=> Extend python checks to framework scripts

tests/scripts/all.sh
Progresses #8153.
Replace Mbed TLS API config options with their PSA API equivalents in three TLS 1.2 components in `all.sh`.
This PR modifies the following three components:
- test_tls1_2_default_stream_cipher_only_use_psa
- test_tls1_2_deafult_cbc_legacy_cipher_only_use_psa
- test_tls1_2_default_cbc_legacy_cbc_etm_cipher_only_use_psa
- please do not force-push …
=> Make TLS 1.2 components work with PSA_CRYPTO_CONFIG set

library/ssl_tls13_generic.c, library/ssl_tls13_server.c
Trivial backport of https://github.com/Mbed-TLS/mbedtls/pull/9225
=> Backport 3.6: Fix uint32_t printed as unsigned int

library/ssl_tls13_generic.c, library/ssl_tls13_server.c
This is ok in practice since we don't support 16-bit platforms, but it makes `arm-none-eabi-gcc-10 -mthumb -Wformat` complain.
Fixes `build_arm_none_eabi_gcc_no_64bit_multiplication` on my machine (arm-none-eabi-gcc 10.3). The CI doesn't complain because we're using an older compiler version.
=> Fix uint32_t printed as unsigned int

tests/compat.sh, tests/ssl-opt.sh
Alert if all tests are filtered out or skipped: that probably indicates a test script that set up an unintended configuration or an overly strict filter. You can pass `--min 0` to bypass this check. You can pass `--min` with a larger value to require that many test cases to run.
Resolves https://github.com/Mbed-TLS/mbedtls/issues/9063 …
=> ssl-opt.sh, compat.sh: Error out if not executing any tests

tests/scripts/all.sh
Make everest component work with PSA_CRYPTO_CONFIG set.
=> Make everest component work with PSA_CRYPTO_CONFIG set

tests/compat.sh, tests/scripts/test-ref-configs.pl, tests/ssl-opt.sh
Backport of https://github.com/Mbed-TLS/mbedtls/pull/9149, and fix some 2.28-only issues that it reveals.
=> Backport 2.28: ssl-opt.sh, compat.sh: Error out if not executing any tests

tests/compat.sh, tests/ssl-opt.sh
Trivial backport of https://github.com/Mbed-TLS/mbedtls/pull/9149
=> Backport 3.6: ssl-opt.sh, compat.sh: Error out if not executing any tests

library/ssl_tls.c
Summary:
Back port [PR 9241](https://github.com/Mbed-TLS/mbedtls/pull/9241) to 2.28 branch
Test Plan:
Reviewers:
Subscribers:
Tasks:
Tags: …
=> Backport 2.28: Set psk to NULL in ssl_psk_remove

library/ssl_tls.c
Summary:
set the psk to NULL after it is released. `ssl_remove_psk` will free`ssl->handshake->psk`. If we don't set it to `NULL`. It may be [used](https://github.com/Mbed-TLS/mbedtls/blob/development/library/ssl_tls13_keys.c#L1875-L1879) or [free](https://github.com/Mbed-TLS/mbedtls/blob/development/library/ssl_tls.c#L4861-L4863) again in other conditions.
Test Plan:
Reviewers: 
Subscribers: ronald.cron@arm.com
Tasks:
Tags:
Address an issue that `psk` is not set to NULL after it is released.
* …
=> Set psk to NULL in ssl_psk_remove

include/mbedtls/ssl.h, library/ssl_tls.c
Fixes #9179
(MBEDTLS_SSL_CID_OUT_LEN_MAX changed to MBEDTLS_SSL_CID_IN_LEN_MAX in library\ssl.h and library\ssl_tls.c)
=> Fix incorrect array length in function prototype

include/mbedtls/ssl.h, library/ssl_tls.c
Issue #9179 (MBEDTLS_SSL_CID_OUT_LEN_MAX changed to MBEDTLS_SSL_CID_IN_LEN_MAX in library\ssl.h and library\ssl_tls.c)
Trivial backport of #9242
=> [Backport 3.6] Fix incorrect array length in function prototype

tests/psa-client-server/psasim/src/psa_ff_server.c
This PR is an extract from https://github.com/Mbed-TLS/mbedtls/pull/9237 in order to split different topics in different PRs. Here's what this one addresses:
- Reduce server's ping time for messages from 50ms to 1us because otherwise tests suites will take forever to execute.
=> psa_sim: make server ping time much faster

tests/psa-client-server/psasim/include/util.h, tests/psa-client-server/psasim/src/client.c, tests/psa-client-server/psasim/src/psa_ff_client.c, tests/psa-client-server/psasim/src/psa_sim_crypto_client.c, tests/psa-client-server/psasim/src/psa_sim_generate.pl, tests/psa-client-server/psasim/src/psa_sim_serialise.c, tests/psa-client-server/psasim/src/psa_sim_serialise.pl
This PR is an extract from #9237 in order to split different topics in different PRs. Here's what this one addresses:
- always print ERROR and FATAL messages because they should never occur, but when they do it's important to see them immediately;
- keep INFO prints under DEBUG guard;
- set client's PRINT as INFO message because otherwise it will mess test_suites's output;
- change some error messages from INFO to ERROR because that's what they are.
=> psa_sim: improve log prints

tests/psa-client-server/psasim/src/psa_sim_crypto_server.c, tests/psa-client-server/psasim/src/psa_sim_generate.pl, tests/psa-client-server/psasim/src/psa_sim_serialise.c, tests/psa-client-server/psasim/src/psa_sim_serialise.h, tests/psa-client-server/psasim/src/psa_sim_serialise.pl, tests/psa-client-server/psasim/src/server.c
This PR is an extract from https://github.com/Mbed-TLS/mbedtls/pull/9237 in order to split different topics in different PRs.
When the client disconnects the server can clean operations slots so that upcoming clients will not hit the maximum slot limit (at least it's very unlikely to happen for normal clients).
=> psasim-server: add function to reset operations slots

tests/include/test/psa_test_wrappers.h, tests/scripts/all.sh, tests/src/psa_test_wrappers.c
Progresses #8153 
Associated mbedtls-framework PR: https://github.com/Mbed-TLS/mbedtls-framework/pull/22
=> Adapt components with MBEDTLS_PSA_CRYPTO_CONFIG enabled

ChangeLog.d/9126.txt, include/mbedtls/config_psa.h
=> Do not perform adjustments on legacy crypto from PSA, when MBEDTLS_PSA_CRYPTO_CLIENT && !MBEDTLS_PSA_CRYPTO_C

ChangeLog.d/9126.txt, include/mbedtls/config_psa.h
This is the backport of #9138. All commits were simply cherry-picked from there.
=> [Backport 3.6] Do not perform adjustments on legacy crypto from PSA, when MBEDTLS_PSA_CRYPTO_CLIENT && !MBEDTLS_PSA_CRYPTO_C

CMakeLists.txt
=> [Backport 3.6] Use CMAKE_C_SIMULATE_ID when available to determine compiler

CMakeLists.txt
Enable mbed-tls to be build using cmake using clang-cl. Clang-cl is used when cross compiling from Linux to target Windows using xwin.
Additionaly removed a superfluous check on the clang-compiler ID.
Fixes #8387 
=> Use CMAKE_C_SIMULATE_ID when available to determine compiler

tests/psa-client-server/psasim/src/psa_ff_server.c, tests/psa-client-server/psasim/src/psa_sim_crypto_client.c, tests/psa-client-server/psasim/src/psa_sim_crypto_server.c, tests/psa-client-server/psasim/src/psa_sim_generate.pl, tests/psa-client-server/psasim/src/psa_sim_serialise.c, tests/psa-client-server/psasim/src/psa_sim_serialise.h, tests/psa-client-server/psasim/src/psa_sim_serialise.pl
This PR contains some commits which were originally part of #9237. The goal is to separate commits which simply improve `psasim` from those which make `psasim` interacting with test suites.
=> psasim: some improvements to the core

library/cipher.c, tests/suites/test_suite_cipher.function
Trivial backport of https://github.com/Mbed-TLS/mbedtls/pull/9082
=> Backport 3.6: Add invalid `padding_len` check in `get_pkcs_padding`

library/cipher.c, tests/suites/test_suite_cipher.function
When trying to decrypt data with an invalid key, we found that `mbedtls` returned `0x6200` (`-25088`), which means "_CIPHER - Input data contains invalid padding and is rejected_" from `mbedtls_cipher_finish`, but it also set the output len as `18446744073709551516`.
In case we detect an error with padding, we leave the output len zero'ed and return `MBEDTLS_ERR_CIPHER_INVALID_PADDING`. I believe that the current test cases are sufficient, as they fail if I return the alternative code `MBEDTLS_ERR_CIPHER_BAD_INPUT_DATA`, so they do already expect a padding failure, but now we don't change the output len in the error case.
Here's a reference for the way `openssl` checks the padding length:
- https://github.com/openssl/openssl/blob/1848c561ec39a9ea91ff1bf740a554be274f98b0/crypto/evp/evp_enc. …
=> Add invalid `padding_len` check in `get_pkcs_padding`

tests/suites/test_suite_debug.function
Since MD_OR_USE_PSA_INIT() can fail and jump to the "exit" label it should be placed after all initializations has been done. This issue was discovered by Coverity testing.
=> tests_suite_debug: fix psa initialization

library/block_cipher.c, library/entropy.c, library/lmots.c, library/lms.c, library/net_sockets.c, library/nist_kw.c, library/pem.c, library/ssl_cookie.c, library/ssl_ticket.c, library/ssl_tls.c, library/x509write_crt.c, library/x509write_csr.c
Added conditional statements to mbedtls_xxx_free() functions to handle NULL arguments.
Resolves #8915
Replaces PR #8955
=> Fix NULL argument handling in mbedtls_xxx_free() functions

library/psa_crypto_cipher.c
Unfortunately this compiler complains about a variable potentially being used un-initialized.  Silence the warning by initializing it to a sane default.
=> Silence gcc 12.2.0 warning

library/psa_crypto_cipher.c
=> [Backport 3.6] Silence gcc 12.2.0 warning

library/block_cipher.c, library/entropy.c, library/lmots.c, library/lms.c, library/net_sockets.c, library/nist_kw.c, library/pem.c, library/ssl_cookie.c, library/ssl_ticket.c, library/ssl_tls.c, library/x509write_crt.c, library/x509write_csr.c
Added conditional statements to mbedtls_xxx_free() functions to handle NULL arguments.
Resolves https://github.com/Mbed-TLS/mbedtls/issues/8915
Relates to PR #8983 
=> [Backport 3.6] Fix NULL argument handling in mbedtls_xxx_free() functions

.github/pull_request_template.md
Updates the development branch's PR checkboxes as discussed in [PR #9008](https://github.com/Mbed-TLS/mbedtls/pull/9008). Will need to apply for 3.6 and 2.28 braches as well before merging.
=> PR-Template: Updated the PR template with new checkboxes

include/psa/crypto.h
This is the backport of #9308
- **tests** not required because: this is only a documentation update
=> [Backport 3.6] psa: fix parameters' names of psa_key_derivation_verify_bytes()

tf-psa-crypto/include/psa/crypto.h
PSA buffers and their length should follow a pattern for which the latter is named after the former as <buffer_name>_length, but this was not the case for psa_key_derivation_verify_bytes().
This makes life of crypto.h parsers (for automatic code generation) harder. This commit aims at solving this problem.
=> psa: fix parameters' names of psa_key_derivation_verify_bytes()

include/mbedtls/ecdh.h, include/mbedtls/ecp.h, programs/test/metatest.c, tests/ssl-opt.sh
Partial backport of #9287 (some files do not exist in 2.28)
=> [Backport 2.28] Fix some typo for include folder

include/mbedtls/config_adjust_legacy_crypto.h, include/mbedtls/config_adjust_ssl.h, include/mbedtls/config_adjust_x509.h, include/mbedtls/ecdh.h, include/mbedtls/ecp.h, include/mbedtls/mbedtls_config.h, programs/test/metatest.c, tests/ssl-opt.sh
=> [Backport 3.6] Fix some typo for include folder

library/platform_util.c
=> [Backport 3.6] Fix typo in platform_util.c

tf-psa-crypto/drivers/builtin/src/platform_util.c
There is a typo in the platform_util.c file where a parenthesis lack. This bug causes the build to fail when `MBEDTLS_HAVE_TIME_DATE` is defined and an non win32 platform is used.
=> Fix typo in platform_util.c

tests/scripts/analyze_outcomes.py, tests/ssl-opt.sh
Replaced `MBEDTLS_MD_CAN_MD5` with `requires_hash_alg MD_5`, and added necessary support for MD5 in `requires_hash_alg`.
In the same tests, `requires_config_enabled MBEDTLS_AES_C` was replaced by `requires_cipher_enabled AES`
=> Add MD5 support for `requires_hash_alg`

tests/scripts/analyze_outcomes.py, tests/ssl-opt.sh
=> Backport 3.6: Add MD5 support for requires_hash_alg

CMakeLists.txt, programs/fuzz/Makefile, tests/CMakeLists.txt, tests/include/test/psa_test_wrappers.h, tests/src/psa_test_wrappers.c
In 3.6, backport some improvements/fixes and the framework update done in PR 9394. 
- **tests**  not required because: no additional tests required
=> [Backport 3.6] PR 9394 backport of fixes and framework submodule update

tests/scripts/basic-build-test.sh
Fix local testing leftover when working on #9394 . This was causing basic-build-test.sh to fail on the Open CI (not the internal one though).
Change tested successfully [here](https://mbedtls.trustedfirmware.org/job/mbed-tls-nightly-tests/812/).
- **tests**  not required because:  fix in a test script
=> basic-build-test.sh: Restore make only command

tf-psa-crypto/core/psa_util.c, tf-psa-crypto/drivers/builtin/include/mbedtls/asn1.h, tf-psa-crypto/drivers/builtin/include/mbedtls/asn1write.h, tf-psa-crypto/drivers/builtin/include/mbedtls/config_psa.h, tf-psa-crypto/drivers/builtin/include/mbedtls/psa_util.h, tf-psa-crypto/drivers/builtin/src/asn1parse.c, tf-psa-crypto/drivers/builtin/src/asn1write.c, tf-psa-crypto/include/psa/crypto_adjust_config_derived.h, tf-psa-crypto/tests/suites/test_suite_psa_crypto_util.function
Replace `MBEDTLS_PSA_UTIL_HAVE_ECDSA` with `PSA_HAVE_ALG_SOME_ECDSA`
Resolves #9336 
=> Replace MBEDTLS_PSA_UTIL_HAVE_ECDSA with PSA_HAVE_ALG_SOME_ECDSA

tests/src/test_helpers/ssl_helpers.c
=> [Backport 3.6] tests/ssl_helpers: Check that message queue is popped

tests/src/test_helpers/ssl_helpers.c
mbedtls_test_mock_tcp_recv_msg is currently popping a message queue and does not check if this was done correctly.
This extra check makes the test more complete/robust.
=> tests/ssl_helpers: Check that message queue is popped

tests/src/test_helpers/ssl_helpers.c
=> [Backport 2.28] tests/ssl_helpers: Check that message queue is popped

docs/architecture/psa-keystore-design.md
Document the design of the PSA key store, which is getting a bit complex. Include the proposed dynamic and fully-static key stores that are currently proposed in https://github.com/Mbed-TLS/mbedtls/pull/9240 and https://github.com/Mbed-TLS/mbedtls/pull/9302.
=> Backport 3.6: Document the key store design

scripts/lcov.sh, scripts/project_name.txt, tests/scripts/all.sh
Fixes #8524 
This PR introduces a more robust way for shell scripts to establish which repository they are being called from, rather than relying on project directory structure as was the case before.
Link to release build CI run for `lcov.sh` testing: https://mbedtls.trustedfirmware.org/job/mbedtls-release-ci-testing/253/
=> Standardise Project Detection in Shell Scripts

tests/psa-client-server/psasim/test/kill_servers.sh, tests/psa-client-server/psasim/test/run_test.sh, tests/scripts/all.sh, tests/scripts/components-psasim.sh
This PR introduces some small fixes to `all.sh` and `psasim` 's bash scripts.
These changes were originally part of #9371, but since that PR is becoming too long, we decided to split minor parts here.
~This PR conflict with #8226, but since that's more urgent, this one will be set as depending on the former.~
=> psasim: small fixes to all.sh and test bash scripts

tests/Makefile
GNU Make 3.81 is officially not supported (we require >= 3.82), but be nice to XCode users who are stuck with 3.81.
- **tests**  it works on my machine
=> Be compatible with GNU Make 3.81

ChangeLog.d/announce-4.0-removals.txt
Ideally we should officially deprecate features before removing them. But we don't add compiler warnings in an LTS release, so we aren't going to make anything deprecated in the warned-by-compiler sense. Still, I think it makes sense to use the changelog as a deprecation announcement channel.
I've only listed the main features we're planning to remove, not every little detail. I'm focusing on where a major feature is getting removed. I don't plan to make such an announcement of this type for individual functions, build system changes, etc.
- **tests**  not required because: documentation only
=> 3.6 only: Announce the main removals planned for 4.0

tests/include/test/psa_test_wrappers.h, tests/src/psa_test_wrappers.c, tf-psa-crypto/core/psa_crypto_ecp.c, tf-psa-crypto/include/psa/crypto.h, tf-psa-crypto/include/psa/crypto_struct.h
Documentation and declarations for the interruptible key agreement PSA interface.
- **tests**  ~~provided~~ | not required because: Tests will be added after implementation is done.
=> Add IOP Key agreement Documentation

ChangeLog.d/psa_util_in_builds_without_psa.txt
Introduced max size/bytes macros in psa_util.c. Prevents 0-size array compiler warning in psa-util.c when MBEDTLS_ECDSA_C is enabled but MBEDTLS_PSA_CRYPTO_C is disabled. Fixes #9311
=> psa_util.c included in builds without PSA, which can break the build

ChangeLog.d/psa_util_in_builds_without_psa.txt, include/mbedtls/config_adjust_legacy_crypto.h
=> [Backport 3.6] psa_util.c included in builds without PSA, which can break the build

tests/include/test/psa_test_wrappers.h, tests/src/psa_test_wrappers.c, tf-psa-crypto/core/psa_crypto_ecp.c, tf-psa-crypto/include/psa/crypto.h, tf-psa-crypto/include/psa/crypto_struct.h
Add the PSA interface documentation for interruptible ECC key generation
- **tests**  ~~provided~~ | not required because: Documentation only, tests will come with implementation.
=> Add documentation for interruptible ECC key generation

library/x509_crt.c, tf-psa-crypto/drivers/builtin/src/sha256.c
See how MS does it: [include/mimalloc/atomic.h:13](https://github.com/microsoft/mimalloc/blob/5eb8c752f7dc2aaef5080831b1f8ff8092bc25af/include/mimalloc/atomic.h#L13)
=> Fix Mbed-TLS build when WIN32_LEAN_AND_MEAN macro is defined globally

library/sha256.c, library/x509_crt.c
See how MS does it: [include/mimalloc/atomic.h:13](https://github.com/microsoft/mimalloc/blob/5eb8c752f7dc2aaef5080831b1f8ff8092bc25af/include/mimalloc/atomic.h#L13)
=> [Backport 3.6] Fix Mbed-TLS build when WIN32_LEAN_AND_MEAN macro is defined globally

ChangeLog.d/dynamic-keystore.txt, include/mbedtls/mbedtls_config.h, library/psa_crypto.c, library/psa_crypto_core.h, library/psa_crypto_slot_management.c, library/psa_crypto_slot_management.h, tests/scripts/components-configuration-crypto.sh, tests/suites/test_suite_psa_crypto_slot_management.data, tests/suites/test_suite_psa_crypto_slot_management.function
Resolve the static limitation on the number of PSA keys at the expense of code size. The new option `MBEDTLS_PSA_KEY_STORE_DYNAMIC` is enabled by the default `mbedtls_config.h`, but will remain disabled by default in projects that have their own configuration file.
Fixes https://github.com/Mbed-TLS/mbedtls/issues/9216.
See https://github.com/Mbed-TLS/mbedtls/pull/9309 for a design document.
I tried to keep the code changes when `MBEDTLS_PSA_KEY_STORE_DYNAMIC` is enabled to a minimum.
Builds off https://github.com/Mbed-TLS/mbedtls/pull/9403
=> Backport 3.6: dynamically sized key store

ChangeLog.d/fix-rsa-performance-regression.txt, include/mbedtls/bignum.h, library/bignum.c, library/bignum_core.c, library/bignum_core.h, library/bignum_internal.h, library/rsa.c, tests/suites/test_suite_bignum.function, tests/suites/test_suite_bignum_core.function
Fix #9232 - partially, the low-hanging fruits (also those that don't make the code size go up by too much).
Status: work in progress.
TODO:
=> [3.6] Reduce performance regression in RSA public operations

ChangeLog.d/fix-legacy-compression-issue.txt, library/ssl_tls13_server.c, tests/ssl-opt.sh
backports #9244 
* See our [Guidelines for Contributors](https://mbed-tls.readthedocs.io/en/latest/reviews/review-for-c …
=> [Backport 3.6] Fix issue in handling legacy_compression_methods in ssl_tls13_parse_client_hello()

ChangeLog.d/dynamic-keystore.txt, include/mbedtls/mbedtls_config.h, tests/scripts/components-configuration-crypto.sh, tf-psa-crypto/core/psa_crypto.c, tf-psa-crypto/core/psa_crypto_core.h, tf-psa-crypto/core/psa_crypto_slot_management.c, tf-psa-crypto/core/psa_crypto_slot_management.h, tf-psa-crypto/tests/suites/test_suite_psa_crypto_slot_management.data, tf-psa-crypto/tests/suites/test_suite_psa_crypto_slot_management.function
Resolve the static limitation on the number of PSA keys at the expense of code size. The new option `MBEDTLS_PSA_KEY_STORE_DYNAMIC` is enabled by the default `mbedtls_config.h`, but will remain disabled by default in projects that have their own configuration file.
Fixes https://github.com/Mbed-TLS/mbedtls/issues/9216.
See https://github.com/Mbed-TLS/mbedtls/pull/9309 for a design document.
This is a direct forward-port of the 3.6 version, which minimizes the changes when the new option is disabled. We could simplify the code, and perhaps even reconsider the compile-time options. But now is not the time, both because we have other higher-priority work and because the 3.6 version may evolve after 3.6.1 and it'll be less work if development remains aligned with 3.6 for a while.
- **tests** …
=> dynamically sized key store

ChangeLog.d/tls13-psa_crypto_init.txt, include/mbedtls/mbedtls_config.h, include/mbedtls/ssl.h, library/ssl_misc.h, library/ssl_tls13_client.c, library/ssl_tls13_generic.c, library/ssl_tls13_server.c, programs/ssl/ssl_client2.c, programs/ssl/ssl_server2.c, tests/include/test/psa_crypto_helpers.h
An application connecting to a peer that supports both TLS 1.2 and TLS 1.3 did not need to call `psa_crypto_init` in Mbed TLS 3.5, so it must not be required to call `psa_crypto_init` in Mbed TLS 3.6. We broke this in Mbed TLS 3.6.0. Fix it. Fixes https://github.com/Mbed-TLS/mbedtls/issues/9072.
- **tests**  provided; also run `programs/ssl/ssl_client1` against a dual 1.2/1.3 server, which in 3.6.0 failed in with an internal error in `psa_generate_key`. This can still fail, but later at the end of the handshake, due to https://github.com/Mbed-TLS/mbedtls/issues/8749.
=> [3.6] TLS 1.3: call psa_crypto_init

tests/scripts/components-configuration.sh
Following commit [635a2beb](https://github.com/Mbed-TLS/mbedtls/commit/635a2beb74dc92173790a9e3c58d9009d2fd1904) in #9394 only the TF-M reference config was tested.
- **tests**  not required because: testing regression fix
=> Restore testing of all reference configs

tests/Makefile
Small fixes to the Makefiles:
- typos in the windows portion;
- some generated files were incorrectly removed by `clean` - they're supposed to be only removed by `neat`.
Forward-ported from the [3.6 release candidate PR](https://github.com/Mbed-TLS/mbedtls-restricted/pull/1286).
- **tests** not required because: Makefiles
=> Misc small makefile fixes

include/mbedtls/check_config.h, tests/scripts/components-sanitizers.sh, tf-psa-crypto/drivers/builtin/src/constant_time_impl.h
=> Remove hacks about asm vs constant-flow testing

include/mbedtls/check_config.h, library/constant_time_impl.h, tests/scripts/components-sanitizers.sh
=> [Backport 3.6] Remove hacks about asm vs constant-flow testing

ChangeLog.d/tls13-cert-regressions.txt, library/ssl_misc.h, library/ssl_tls.c, library/ssl_tls12_server.c, library/ssl_tls13_generic.c, tests/ssl-opt.sh
This is the development forward-port of https://github.com/Mbed-TLS/mbedtls-restricted/pull/1265 - can (and should) be public now that the pre-requisite has been [merged back](https://github.com/Mbed-TLS/mbedtls/pull/9525). Fixes #9018.
.
=> Refactor tls123 verif dev

tests/include/test/macros.h
Backport https://github.com/Mbed-TLS/mbedtls/pull/8751
- **tests**  ~~provided~~ | not required because: Not testable (compiler fix) …
=> [Backport 2.28] tests: fix calloc() argument list (gcc-14 fix)

tests/scripts/analyze_outcomes.py
=> Backport 3.6:  Fix inconsistent ordering of driver vs reference in analyze_outcomes

tests/scripts/analyze_outcomes.py
The header line said “driver vs reference” whereas the error line said “reference -> driver”. Updated the header line to be consistent with the error line.
Resolves #9298
=> Fix inconsistent ordering of driver vs reference in analyze_outcomes

library/bignum_core.c, library/bignum_core.h, library/bignum_core_invasive.h, tests/include/test/bignum_codepath_check.h, tests/src/bignum_codepath_check.c, tests/src/helpers.c, tests/suites/test_suite_bignum.function, tests/suites/test_suite_bignum_core.function, tests/suites/test_suite_rsa.function
~**Depends on:** https://github.com/Mbed-TLS/mbedtls/pull/9281~ merged
Add some more tests for the performance regression fix.
=> [3.6] Rsapub additional tests

library/ssl_misc.h, programs/ssl/ssl_client2.c, tests/opt-testcases/tls13-misc.sh, tests/ssl-opt.sh
This PR addresses leftover feedback on #9507
**Status:** pushed for CI feedback.
=> [3.6] Follow-up to 9507 Disable new session tickets at runtime

tests/scripts/components-build-system.sh, tests/scripts/pkgconfig.sh
=> [BACKPORT 3.6] tests: add a test for pkg-config files

tests/scripts/components-build-system.sh, tests/scripts/pkgconfig.sh
tests: add a test for pkg-config files
Add a test that does some basic validation of the pkg-config files.
Example run:
```
./tests/scripts/all.sh test_cmake_as_package
<snip>
******************************************************************
* test_cmake_as_package: build: cmake 'as-package' build 
* Wed Sep 11 16:22:09 UTC 2024
******************************************************************
cmake .
make
Built against Mbed TLS 3.6.1
testing package config file: mbedtls ... passed
testing package config file: mbedx509 ... passed
testing package config file: mbedcrypto ... passed
make clean
```
Signed-off-by: Bill Roberts <bill.roberts@arm.com>
Please tick as appropriate and edit the reasons (e.g.: …
=> tests: add a test for pkg-config files

CMakeLists.txt, doxygen/input/doc_mainpage.h, doxygen/mbedtls.doxyfile, include/mbedtls/build_info.h, library/CMakeLists.txt, tf-psa-crypto/scripts/project_name.txt, tf-psa-crypto/tests/suites/test_suite_version.data
Improve project (Mbed TLS or TF-PSA-Crypto) detection, add Mbed TLS 3.6 branch detection
- **tests**  not required because: internals
=> Projects and 3.6 branch detections

tests/scripts/components-build-system.sh
[Found by Tom](https://github.com/Mbed-TLS/mbedtls/pull/9446#discussion_r1754922190).
=> Fix typo that caused cpp_dummy_build not to be built with CMake

tests/scripts/components-configuration-crypto.sh, tests/scripts/components-configuration-tls.sh
Adapt some all.sh components to MBEDTLS_PSA_CRYPTO_CONFIG always on
Progresses #8153.
- **tests**  not required because: adaptations of some test components
=> Adapt some all.sh components to MBEDTLS_PSA_CRYPTO_CONFIG always on

tf-psa-crypto/drivers/builtin/src/ccm.c
Adjusts `ccm_calculate_first_block_if_ready` to return early before unnecessarily calculating  invalid context.
- **tests**  provided | not required because: It does not change the functional flow of the code.
- please do not force-push to update your PR - just add new …
=> ccm.c: Return early when ccm* is used without tag.

library/ccm.c
Backport of #9497
- **tests** not required because:  It does not change the functional flow of the code.
* See our [Guidelines for Contributors](https://mbed-tls.readthedocs.io/en/latest/reviews/review-for-co …
=> [Backport 3.6] ccm.c: Return early when ccm* is used without tag.

scripts/config.py
Move the part of the `config.py` which is common in the TF-PSA_Crypto and the MbedTLS repo to the framework repo.
Resolve #9325
=> Move `config.py` functionalities to the framework

scripts/config.py, tests/scripts/depends.py
Move the part of the `config.py` which is common in the TF-PSA_Crypto and the MbedTLS repo to the framework repo.
Trivial backport of #9470 except to use MbedTLSConfig as default config handler.
Resolve #9325
=> [Backport 3.6] Move `config.py` functionalities to the framework

scripts/config.py
MBEDTLS_PSA_CRYPTO_KEY_ID_ENCODES_OWNER has been compatible with MBEDTLS_USE_PSA_CRYPTO since https://github.com/Mbed-TLS/mbedtls/pull/5380. We still don't want to enable it in the full config because it's a behavior change, even an interface change.
=> Fix obsolete comment about MBEDTLS_PSA_CRYPTO_KEY_ID_ENCODES_OWNER

scripts/make_generated_files.bat
Document that `make_generated_files.bat` needs a C compiler as `%CC%` or `cc` (for `c_build_helper` users: `generate_psa_tests.py`).
=> Backport 3.6: make_generated_files.bat: document C compiler requirement

scripts/config.py
In `config.py`, stop relying on section names for `config.py full`, `config.py realfull`, etc. This way we can move configuration settings around as described in https://github.com/Mbed-TLS/mbedtls/pull/9236 without having to worry about messing up the tooling.
Specifically:
* `full` and friends no longer rely on the section to determine which settings are booleans that should be activated.
* `realfull` is now really full. The goal is to document everything, and it turns out that uncommenting everything does work.
The script `tests/scripts/test_config_script.py` runs some tests on `config.py` and places the output in the given directory. Run it on the version of `config.py` from two commits to compare its effects.
```
$ git checkout --recurse-submodules upstream/pull/9604~4
$ …
```
=> config.py: don't rely on section names

scripts/config.py
Straightforward backport of https://github.com/Mbed-TLS/mbedtls/pull/9604.
- **tests**  manual (see #9604)
=> Backport 3.6: config.py: don't rely on section names

programs/ssl/dtls_client.c, programs/ssl/dtls_server.c, programs/ssl/mini_client.c, programs/ssl/ssl_client1.c, programs/ssl/ssl_context_info.c, programs/ssl/ssl_fork_server.c, programs/ssl/ssl_mail_client.c, programs/ssl/ssl_pthread_server.c, programs/ssl/ssl_server.c, tests/opt-testcases/sample.sh, tests/scripts/components-configuration.sh, tests/ssl-opt.sh
Forward-port of https://github.com/Mbed-TLS/mbedtls/pull/9541, plus adaptations needed to handle the incompatible changes between 3.6 and 4.0:
* `psa_crypto_init` mandatory (https://github.com/Mbed-TLS/mbedtls/issues/9072, https://github.com/Mbed-TLS/mbedtls/pull/9501)
* Handling of session tickets in TLS 1.3 clients (https://github.com/Mbed-TLS/mbedtls/issues/8749, https://github.com/Mbed-TLS/mbedtls/pull/9507, https://github.com/Mbed-TLS/mbedtls/issues/6640)
* Stop testing without PSA (otherwise we can no longer build the TLS sample programs).
Closes https://github.com/Mbed-TLS/mbedtls/issues/9072.
=> Test sample programs in ssl-opt.sh

programs/ssl/dtls_client.c, programs/ssl/dtls_server.c, programs/ssl/ssl_client1.c, programs/ssl/ssl_fork_server.c, programs/ssl/ssl_pthread_server.c, programs/ssl/ssl_server.c, tests/opt-testcases/sample.sh, tests/ssl-opt.sh
Test the SSL sample programs (`ssl_client1`, `dtls_client`, `ssl_server`, `ssl_fork_server`, `ssl_pthread_server`, `dtls_server`) in `ssl-opt.sh`. Test against both GnuTLS and OpenSSL. Test with all relevant protocol versions (TLS 1.2/1.3; DTLS 1.2 only).
`mini_client` is excluded because it's complicated, see [this comment](https://github.com/Mbed-TLS/mbedtls/pull/9541#issuecomment-2344479846). It's also not part of the deliverable we want, which is primarily `ssl_client1` and `ssl_server` interoperabiliy with TLS 1.3, and secondarily (because that part is not much more effort) those programs and `dtls_client` and `dtls_server` with (D)TLS 1.2. (I'm still throwing in `ssl_pthread_server` and `ssl_fork_server` because they're really easy.)
The TLS 1.3 test cases are non-regression tests …
=> Backport 3.6: test sample programs in ssl-opt.sh

tests/Makefile, tests/scripts/basic-build-test.sh, tests/scripts/run-test-suites.pl
Fix `make test` not running the crypto tests if a TLS test fails. Ensure that the reporting is correct.
- **tests**  provided + run `basic-build-test.sh`: https://mbedtls.trustedfirmware.org/job/mbedtls-restricted-release-new/33/
=> Run test suites on subproject

docs/driver-only-builds.md, include/mbedtls/check_config.h, include/mbedtls/config_adjust_legacy_crypto.h, tf-psa-crypto/tests/suites/test_suite_pkwrite.data
Resolves #9396
Removal of symbols from #9385, #9540, and #9544 to be included in their respective PRs.
* See our [Guidelines for Contributors](https://mbed-tls.readthedocs.io/en/latest/reviews/review-for-cont …
=> Remove definitions of legacy symbols

programs/ssl/dtls_server.c, tests/opt-testcases/sample.sh
In `dtls_server`, don't treat `MBEDTLS_ERR_SSL_UNEXPECTED_MESSAGE` as a real error if it happens during a handshake. This error can happen if the client sends a `close_notify` alert after the server has decided to close the connection, or if there's a duplicated packet from the first connection.
In testing, this error happens reliably when the client is `dtls_client` or `ssl_client2 dtls=1`. It also happens reliably when the client is `openssl s_client -dtls_12` and I type into it interactively. When the client is `echo stuff | openssl s_client -dtls_12`, I don't see the error locally, but [it's happening with low frequency on the CI](https://github.com/Mbed-TLS/mbedtls/issues/9652).
Fixes https://github.com/Mbed-TLS/mbedtls/issues/9652. Improvement filed as #9666.
=> Backport 3.6: dtls_server: allow unexpected message on second handshake

docs/architecture/psa-migration/psa-limitations.md, docs/architecture/psa-migration/strategy.md, docs/architecture/psa-migration/transition-guards.md, docs/driver-only-builds.md, library/ssl_tls12_client.c, tests/scripts/components-configuration-crypto.sh
Resolves #8736
- **tests**  not required: documentation
=> [3.6 only] Document transitional feature macros / guards

ChangeLog.d/fix-driver-schema-check.txt, scripts/data_files/driver_jsons/driver_opaque_schema.json, scripts/data_files/driver_jsons/driver_transparent_schema.json
Fix the const default value for the driver schema jsons.
- **tests**  not required because: no infrastructure to test driver JSON parsing
=> Fix driver schema json default type requirements

ChangeLog.d/fix-driver-schema-check.txt, scripts/data_files/driver_jsons/driver_opaque_schema.json, scripts/data_files/driver_jsons/driver_transparent_schema.json
Fix the const default value for the driver schema jsons.
- **tests**  not required because: no infrastructure to test driver JSON parsing
=> Backport 3.6: Fix driver schema json default type requirements

ChangeLog.d/replace-close-with-mbedtls_net_close.txt, library/net_sockets.c
In the test examples and real usage scenarios, 'mbedtls_net_free' is called after 'mbedtls_net_connect' fails, which will cause the problem of double close the same fd. It is possible to close this closed fd which has been applied by other link.
hi all. We found that in the scenario of sudden network disconnection, ‘mbedtls_net_connect’ will close fd after the connection fails, and then call ‘mbedtls_net_free’ to close it again. There is a risk of double close here. At first, we suspected that it was used incorrectly, but after referring to the implementation and case in the programs directory, we did not find that it was a usage error. Therefore, we suggest to mark fd as unavailable after closing it to prevent fd from being used by other programs during the interval between …
=> [Backport 2.28] net/mbedtls_net_connect: Preventing double close problem

ChangeLog.d/replace-close-with-mbedtls_net_close.txt, library/net_sockets.c
In the test examples and real usage scenarios, 'mbedtls_net_free' is called after 'mbedtls_net_connect' fails, which will cause the problem of double close the same fd. It is possible to close this closed fd which has been applied by other link.
hi all. We found that in the scenario of sudden network disconnection, ‘mbedtls_net_connect’ will close fd after the connection fails, and then call ‘mbedtls_net_free’ to close it again. There is a risk of double close here. At first, we suspected that it was used incorrectly, but after referring to the implementation and case in the programs directory, we did not find that it was a usage error. Therefore, we suggest to mark fd as unavailable after closing it to prevent fd from being used by other programs during the interval between …
=> [Backport 3.6] net/mbedtls_net_connect: Preventing double close problem

.gitignore, library/Makefile, tests/scripts/components-compiler.sh, tests/scripts/components-configuration-crypto.sh, tests/scripts/components-platform.sh
Some issues I discovered while working on https://github.com/Mbed-TLS/mbedtls/pull/9286. Backport of https://github.com/Mbed-TLS/mbedtls/pull/9293, conceptually identical, but with a lot of merge conflicts due to changes on the same line: we have lines that refer to `${BUILTIN_SRC_PATH}` in `development`, but that's just `library` in 3.6.
=> Backport 3.6: Fix some all.sh components with sub-components

CMakeLists.txt, tf-psa-crypto/tests/suites/test_suite_pkwrite.data
This PR fixes some workaround which were introduced in #9690:
- re-enable all the tests in `test_suite_pkwrite.data`
- use `-O2` flag instead of `-O3` only for old (i.e. version < 7.0) GCC compilers
Depends on #9690
- [] **tests**  not required
=> Revert & fix #9690 workarounds

tests/scripts/all.sh
Partial backport of https://github.com/Mbed-TLS/mbedtls/pull/9608: some bug fixes in `all.sh`. I'm not backporting the changes to `library/Makefile` to support building assembly files because that was only needed for components added in 3.x.
=> Backport 2.28: Fix some all.sh components with sub-components

.gitignore, library/Makefile, tests/scripts/components-compiler.sh, tests/scripts/components-configuration-crypto.sh, tests/scripts/components-platform.sh
This is a collection of fixes to issues in `all.sh` that I discovered while working on https://github.com/Mbed-TLS/mbedtls/pull/9286. The biggest part is a reorganization of `component_build_aes_armce` and `component_build_sha_armce` to make them split into clear distinct configurations.
While the issues themselves are minor, this pull request is priority-high because it blocks [priority-high work](https://github.com/Mbed-TLS/mbedtls/pull/9286).
=> Fix some all.sh components with sub-components

CMakeLists.txt, tests/suites/test_suite_pkwrite.data
This is the backport of #9703.
Since this is targetting the `mbedtls-3.6` branch I think the more appropriate title would be "Revert & fix #9698 workarounds".
=> [Backport 3.6] Revert & fix #9690 workarounds

tests/src/bignum_codepath_check.c, tests/suites/test_suite_ctr_drbg.function, tests/suites/test_suite_psa_crypto_memory.function, tests/suites/test_suite_x509write.function
Trivial backport of #9721 
- **tests**  ~~provided |~~ not required because: Existing test coverage suffices
=> [Backport 3.6] Fix new coverity issues

tests/src/bignum_codepath_check.c, tests/suites/test_suite_x509write.function, tf-psa-crypto/tests/suites/test_suite_ctr_drbg.function, tf-psa-crypto/tests/suites/test_suite_psa_crypto_memory.function
Fix a number of issues detected by coverity in the most recent run.
- **tests**  ~~provided |~~ not required because: Existing tests provide coverage.
=> Fix new coverity issues

tests/scripts/all-core.sh, tests/scripts/all-helpers.sh, tests/scripts/components-platform.sh
This PR adds default-config tests for  A64, A32, Thumb 1 and Thumb 2 instruction sets.
The components are only enabled, if the host machine is capable of running the binaries produced by the (cross) compiler.
The corresponding PR Mbed-TLS/mbedtls-test#171 needs to be merged before this one
=> Add default config tests for the A64, A32, Thumb 1 and Thumb 2 instruction sets

tests/scripts/all.sh
This PR is the 2.28 backport of #9389
=> [Backport 2.28] Add default config tests for the A64, A32, Thumb 1 and Thumb 2 instruction sets

tests/scripts/all-core.sh, tests/scripts/all-helpers.sh, tests/scripts/components-platform.sh
This PR is the 3.6 backport of #9389
=> [Backport 3.6] Add default config tests for the A64, A32, Thumb 1 and Thumb 2 instruction sets

tests/suites/test_suite_psa_crypto_memory.function, tests/suites/test_suite_x509write.function
Backport of the relevant parts of #9721 (Some tests did not exist / bignum codepath tests did not exist)
- **tests**  ~~provided |~~ not required because: Existing tests suffice
=> [Backport 2.28] Fix new coverity issues

scripts/output_env.sh, tests/scripts/all.sh
It is my understanding that with the migration to a new license scheme in the CI, we are loosing support for armcc5. Since this is a legacy version, we can just stop testing with it.
- **tests** not required because: n/a
=> [2.28] Drop armcc5 support in all.sh

scripts/output_env.sh, tests/scripts/all-core.sh, tests/scripts/components-platform.sh
It is my understanding that with the migration to a new license scheme in the CI, we are loosing support for armcc5. Since this is a legacy version, we can just stop testing with it.
- **tests** not required because: n/a
=> [dev] Drop building with armcc5 in all.sh

include/mbedtls/config_adjust_legacy_crypto.h, include/mbedtls/mbedtls_config.h, tests/scripts/components-configuration-crypto.sh, tests/scripts/components-configuration-tls.sh, tests/ssl-opt.sh
Resolve #9630.
There are still builds with `MBEDTLS_PSA_CRYPTO_CLIENT` disabled, when we're only building some low-level crypto.
Continues https://github.com/Mbed-TLS/mbedtls/pull/9614.
=> Force MBEDTLS_USE_PSA_CRYPTO enabled

tf-psa-crypto/tests/suites/test_suite_ecdsa.function, tf-psa-crypto/tests/suites/test_suite_ecjpake.function, tf-psa-crypto/tests/suites/test_suite_hmac_drbg.function, tf-psa-crypto/tests/suites/test_suite_md.function, tf-psa-crypto/tests/suites/test_suite_pem.function, tf-psa-crypto/tests/suites/test_suite_pkcs1_v21.function, tf-psa-crypto/tests/suites/test_suite_pkparse.function, tf-psa-crypto/tests/suites/test_suite_random.function
This fixes accesses to uninitialized memory in test code if `psa_crypto_init()` fails.
A lot of those were pointed out by Coverity after the merge of https://github.com/Mbed-TLS/mbedtls/pull/9430, which made `MD_PSA_INIT` no longer a no-op in the default configuration. I quickly reviewed all calls to `MD_PSA_INIT()` manually, rather than follow any particular list.
- **tests**  run Coverity again once this is merged
=> Fix MD_PSA_INIT called before initializing some data structures

tests/suites/test_suite_ecdsa.function, tests/suites/test_suite_ecjpake.function, tests/suites/test_suite_hmac_drbg.function, tests/suites/test_suite_md.function, tests/suites/test_suite_pem.function, tests/suites/test_suite_pkcs1_v21.function, tests/suites/test_suite_pkparse.function, tests/suites/test_suite_random.function
Trivial backport of https://github.com/Mbed-TLS/mbedtls/pull/9752. Given that this is fixing issues only in tests, only in circumstances that are very unusual in 3.6, I didn't bother to see if 3.6 might have other similar bits of code, i.e. I made even less effort at completeness than in development.
- **tests**  statu quo …
=> Backport 3.6: Fix MD_PSA_INIT called before initializing some data structures

tests/scripts/all-core.sh, tests/scripts/all.sh
This is the 3.6 partial backport of 9720 - here we don't want support for tf-psa-crypto components, so I'm just backporting changes to `all-core.sh` in order to preserver alignment between branches (before this is moved to the framework in the next PR).
- **tests**  not required because: manual testing, see below
=> [Backport 3.6] All.sh changes to support tf-psa-crypto components

tests/scripts/all-core.sh, tests/scripts/all.sh, tests/scripts/components-build-system.sh, tests/scripts/mbedtls-all.sh, tf-psa-crypto/tests/scripts/all.sh, tf-psa-crypto/tests/scripts/components-build-system.sh
- Add `tf-psa-crypto/tests/scripts/all.sh` that can be invoked independently and will source components from `tf-psa-crypto/tests/scripts/component-*.sh`. Ultimately this is going to be the main entry point for tf-psa-crypto's CI when all relevant components have been migrated.
- Turn `tests/scripts/all.sh` into a wrapper that handles both mbedtls and tf-psa-crypto. This is a transitional wapper so that the CI can just keep calling the same single entry point, and still get all components, while we move relevant components to tf-psa-crypto, and until tf-psa-crypto gets its own autonomous CI.
- **tests**  not required because: manual testing, see below
- Once the CI is passing, check the outcome file to confirm we're still running the same number of components.
- Anything else reviewers …
=> All.sh add support for tf-psa-crypto components

docs/architecture/psa-crypto-implementation-structure.md, tests/Makefile, tests/configs/config_test_driver.h, tests/configs/crypto_config_test_driver_extension.h
Companion PR of #9771 
- **tests**  not required because: just moving test config files
=> Move back test configs

tests/include/test/psa_test_wrappers.h, tests/src/psa_test_wrappers.c, tf-psa-crypto/core/psa_crypto.c, tf-psa-crypto/include/psa/crypto.h, tf-psa-crypto/include/psa/crypto_struct.h
Add the PSA interface headers and documentation for interruptible ECC export public-key
=> Add header and documentation for interruptible ECC export public-key

docs/architecture/testing/driver-interface-test-strategy.md
Commit d80134b56d74a3486c5e4d73f9b0546b5c045ca3 moved the `crypto_se_driver.h` to `tf-psa-crypto`. This PR adjusts sources to changes. This PR also fixes some typos found in `driver-interface-test-strategy.md`.
- please do not force-push to update your PR - just add new …
=> Update `crypto_se_driver.h` reference

tests/include/test/psa_test_wrappers.h, tests/src/psa_test_wrappers.c, tf-psa-crypto/core/psa_crypto.c, tf-psa-crypto/core/psa_crypto_core.h, tf-psa-crypto/drivers/builtin/include/mbedtls/ecp.h, tf-psa-crypto/drivers/builtin/src/psa_crypto_ecp.c, tf-psa-crypto/drivers/builtin/src/psa_crypto_ecp.h, tf-psa-crypto/include/psa/crypto.h, tf-psa-crypto/tests/suites/test_suite_psa_crypto.function
Partially fixes #9106
Fixes #9643 
Add PSA interruptible key generation complete API
* See our [Guidelines for Contributors](https://mbed-tls.readthedocs.io/en/latest/reviews/review-for-contributors/) for …
=> Add PSA interruptible key generation complete API

scripts/lcov.sh, tests/scripts/all.sh, tests/scripts/check-generated-files.sh
Resolves https://github.com/Mbed-TLS/mbedtls-framework/issues/39
=> [Backport 3.6] Add project and branch detection in shell

ChangeLog.d/add-psa-iop-generate-key.txt, tf-psa-crypto/core/psa_crypto.c, tf-psa-crypto/drivers/builtin/src/psa_crypto_ecp.c, tf-psa-crypto/drivers/builtin/src/psa_crypto_ecp.h, tf-psa-crypto/tests/suites/test_suite_psa_crypto.function
fixes #9106 
fixes #9644 
Add PSA interruptible key generation get num ops API
=> Add PSA interruptible key generation get num ops API

ChangeLog.d/fix-compilation-with-djgpp.txt, library/net_sockets.c
mbedTLS does not compile on MS-DOS DJGPP because the toolchain does define `__unix__`, but does not provide `suseconds_t`.
Excluding the code path with modifying the `#if` to be false when `__DJGPP__` is defined makes it compile fine.
- **tests**  not required because: no functional change. Existing ifdef is activated for another platform
=> Mbedtls 2.28: Fix compilation on MS-DOS DJGPP

ChangeLog.d/fix-compilation-with-djgpp.txt, library/net_sockets.c
mbedTLS does not compile on MS-DOS DJGPP because the toolchain does define `__unix__`, but does not provide `suseconds_t`.
Excluding the code path with modifying the `#if` to be false when `__DJGPP__` is defined makes it compile fine.
- **tests**  not required because: no functional change. Existing ifdef is activated for another platform
=> Mbedtls 3.6: Fix compilation on MS-DOS DJGPP

ChangeLog.d/fix-compilation-with-djgpp.txt, library/net_sockets.c
mbedTLS does not compile on MS-DOS DJGPP because the toolchain does define `__unix__`, but does not provide `suseconds_t`.
Excluding the code path with modifying the `#if` to be false when `__DJGPP__` is defined makes it compile fine.
- **tests**  not required because: no functional change. Existing ifdef is activated for another platform
=> Fix compilation on MS-DOS DJGPP

configs/ext/README.md, configs/ext/tfm_mbedcrypto_config_profile_medium.h, include/mbedtls/config_adjust_legacy_crypto.h, include/mbedtls/mbedtls_config.h, include/mbedtls/ssl.h, include/mbedtls/ssl_ciphersuites.h, include/mbedtls/x509_crl.h, include/mbedtls/x509_crt.h, include/mbedtls/x509_csr.h, tf-psa-crypto/drivers/builtin/include/mbedtls/cipher.h, tf-psa-crypto/drivers/builtin/include/mbedtls/pk.h
Remove discussions of MBEDTLS_USE_PSA_CRYPTO in API documentation. Resolves partially #9632.
- **tests**  not required because: documentation only
=> Remove discussions of MBEDTLS_USE_PSA_CRYPTO in API documentation

ChangeLog.d/fix-aesni-asm-clobbers.txt, library/aesni.c
Backport of #9809 for #9819.
- **tests** not required because: no functionality is added, and the bug isn't normally reproducible in testing
=> [Backport 2.28] Specify previously missed register clobbers in AES-NI asm blocks

ChangeLog.d/fix-aesni-asm-clobbers.txt, library/aesni.c
Backport of #9809 for #9819.
- **tests** not required because: no functionality is added, and the bug isn't normally reproducible in testing
=> [Backport 3.6] Specify previously missed register clobbers in AES-NI asm blocks

ChangeLog.d/fix-aesni-asm-clobbers.txt, tf-psa-crypto/drivers/builtin/src/aesni.c
We have just integrated mbedTLS AES code into John the Ripper via https://github.com/openwall/john/pull/5591 and I've been reviewing our changes as well as looking at mbedTLS original code. One of our concerns was how good or bad the inline asm blocks are compared to the intrinsics, and whether we should possibly get rid of the inline asm. I found you also have an issue open for that (#8231), which is great. Meanwhile, I noticed a number of performance issues with the inline asm code and what I think is one bug. This PR is to fix the bug:
While most of the inline asm blocks specify what they clobber (memory, condition flags, other registers), the one in `mbedtls_aesni_crypt_ecb` clobbers a couple of input registers without specifying so. This PR fixes that in the same fashion as further …
=> Specify previously missed register clobbers in AES-NI asm blocks

tests/scripts/components-sanitizers.sh
Negative tests for Interruptible Key Agreement.
Resolves #9109 
- **tests**  provided ~~| not required because:~~
=> Add interruptible key agreement negative tests

CMakeLists.txt, Makefile
- **tests**  provided | not required because: 
=> [Backport 3.6] Fix submodule error messages

CMakeLists.txt, Makefile
Fix issue with make file submodule error message displaying incorrect message when inside git repository. 
- **tests**  provided | not required because: 
=> Fix submodule error messages

docs/architecture/psa-migration/strategy.md, docs/driver-only-builds.md
Minor corrections found while rewiewing https://github.com/Mbed-TLS/mbedtls/pull/9818.
=> Backport 3.6: Fix discussions of MBEDTLS_USE_PSA_CRYPTO in standalone documentation

scripts/sbom.cdx.json
Hi,
My name is Richard Hughes and I'm a developer at Red Hat. I'm the maintainer of fwupd and LVFS, and am trying to improve software supply chain security by encouraging OEMs, ODMs and IBVs to ship Software Bill of Materials with each firmware binary blob (SBOMs).
I'm working alongside lots of other companies proactively trying to do the right thing. The reason I've opened this pull request is because your project is either used in the *build process* of a firmware we care about (e.g. EDK II, or coreboot) or is built *into the firmware binary* itself. Although my personal focus is on firmware, the SBOM file is in CycloneDX format (one of the most popular industry standards) which makes it also useful when building containers or OS images too.
I would like to contribute this template SBOM …
=> Add a SBOM file in CycloneDX format

library/ssl_tls13_client.c
=> Backport 3.6: Added debug print in tls13 ssl_tls13_write_key_share_ext

library/psa_crypto.c
https://github.com/Mbed-TLS/mbedtls-framework/pull/104 fixes a bug whereby some negative tests were always skipped (because they were generated with incorrect dependencies). These test cases fail because the test code is more strict about error behavior than the library. Make the library detect some errors earlier to reconcile it with the test code.
Once this is merged, the CI on https://github.com/Mbed-TLS/mbedtls-framework/pull/104 should pass.
=> PSA interruptible sign/verify: detect invalid curve family in start

ChangeLog.d/9892.txt, include/mbedtls/x509_crt.h, library/x509write_crt.c, tests/suites/test_suite_x509write.function
Resolves #9892
- **tests** not required because: this is a removal
=> Remove deprecated function mbedtls_x509write_crt_set_serial()

tests/scripts/components-basic-checks.sh
This commit removes the check_test_dependencies from Mbed TLS as it has been added to TF-PSA-Crypto.
- **tests**  provided | not required because:  …
=> Remove check_test_dependencies TF-PSA-Crypto test from Mbed TLS

tests/scripts/analyze_outcomes.py
This completes the forward port of https://github.com/Mbed-TLS/mbedtls/pull/9025. Everything is happening in the framework, except for removing the exceptions to test coverage that this is fixing.
=> Backport 3.6: Switch generate_psa_test.py to automatic dependencies for negative test cases

tests/scripts/analyze_outcomes.py
This completes the forward port of https://github.com/Mbed-TLS/mbedtls/pull/9025. Everything is happening in the submodules, except for removing the exceptions to test coverage that this is fixing.
=> Switch generate_psa_test.py to automatic dependencies for negative test cases

SECURITY.md
Clarify that strict formatting of X.509 certificates is not checked by Mbed TLS and that it therefore should not be used to construct a CA.
- **tests**  not required because: docs change only
=> Add X.509 formatting validation to SECURITY.md

library/ecp.c
This is a backport of [#166](https://github.com/Mbed-TLS/TF-PSA-Crypto/pull/166)
- **tests**  provided | not required because:  …
=> [Backport 3.6] Refactored a minor check in ecp check privkey

docs/3.0-migration-guide.md, tests/suites/test_suite_ssl.function
This is the very partial 3.6 backport of #9906: don't remove the function but recommend its replacement in the migration guide. Also cherry-pick a commit fixing a test dependency that was always wrong, and then another one fixing a problem in the test that was previously hidden by the wrong dependency.
- **tests**  not required because: covered by existing tests
=> [3.6 backport]: mbedtls_conf_curves()

ChangeLog.d/rm-ssl-conf-curves.txt, docs/3.0-migration-guide.md, include/mbedtls/ssl.h, library/ssl_client.c, library/ssl_misc.h, library/ssl_tls.c, library/ssl_tls12_server.c, library/ssl_tls13_client.c, tests/scripts/analyze_outcomes.py, tests/suites/test_suite_ssl.data, tests/suites/test_suite_ssl.function
Resolve #9891
- **tests**  not required because: covered by existing tests
=> [dev] Remove deprecated function mbedtls_ssl_conf_curves()

ChangeLog.d/9874.txt, include/mbedtls/ssl_ticket.h, library/ssl_ticket.c, programs/fuzz/fuzz_server.c, programs/ssl/ssl_server2.c
Convert the mbedtl_ssl_ticket_setup function to use the TF_PSA_Crypto API. Depends on the merge of #9923 resolves #9874
- **tests**  not required because: covered by existing tests.
=> Move ssl_ticket to the PSA API

SECURITY.md
Clarify that strict formatting of X.509 certificates is not checked by Mbed TLS and that it therefore should not be used to construct a CA.
- **tests**  not required because: docs change only
=> [Backport 2.28] Add X.509 formatting validation to SECURITY.md

SECURITY.md
Clarify that strict formatting of X.509 certificates is not checked by Mbed TLS and that it therefore should not be used to construct a CA.
- **tests**  not required because: docs change only
=> [Backport 3.6] Add X.509 formatting validation to SECURITY.md

ChangeLog.d/tls-hs-defrag-in.txt, include/mbedtls/ssl.h, library/ssl_misc.h, library/ssl_msg.c, library/ssl_tls.c, library/ssl_tls12_server.c, programs/ssl/ssl_context_info.c
This is the 3.6 backport of https://github.com/Mbed-TLS/mbedtls/pull/9872, with extra commits to preserve ABI compatibility in 3.6.
A simpler alternative to https://github.com/Mbed-TLS/mbedtls/pull/9949, which wasn't possible when https://github.com/Mbed-TLS/mbedtls/pull/9949 was made. Originally we needed room for a message size and a pointer in the SSL context. Now, after an [improvement to the original PR](https://github.com/Mbed-TLS/mbedtls/pull/9872/commits/dd14c0a11eeefb0b37db4ba6bd3967746488aff4), we only need room for a message size, and that's easier to find.
- **tests** deferred to #9887, #9987 and #9968
=> [Backport 3.6] Defragment incoming TLS handshake messages (reuse badmac_seen)

ChangeLog.d/tls-hs-defrag-in.txt, include/mbedtls/ssl.h, library/ssl_misc.h, library/ssl_msg.c, library/ssl_tls.c, library/ssl_tls12_server.c
Defragment incoming TLS handshake messages.
Fixes https://github.com/Mbed-TLS/mbedtls/issues/1840
- **tests** deferred to #9887, #9987 and #9968
=> Defragment incoming TLS handshake messages

library/x509_crl.c, library/x509_crt.c, library/x509_csr.c
Rename the `BEFORE_COLON` and `BC` defines to include a `MBEDTLS_` prefix and expand the `BC` to `BEFORE_COLON`.
The existing names are rather short and are not properly namespaced, increasing the likelihood for conflicts.
The defines are not even used in `x509_crl.c`, so remove them entirely there.
The issue came up during Zephyr development. There, the Renesas RA HAL headers have variables named `BC`. Those headers are included into the mbedtls module via the `sys/socket.h` and `arpa/inet.h` headers in `library/x509.crt.c` which will eventually include CPU-specific headers containing the Renesas HAL. The conflict can be triggered with the Zephyr https sample: `west build -p auto -b ek_ra6m4 zephyr/samples/net/sockets/http_server`, which will lead to
~~~ …
=> Rename BEFORE_COLON/BC to avoid conflicts

ChangeLog.d/tls-hs-defrag-in.txt, tests/scripts/analyze_outcomes.py, tests/ssl-opt.sh
=> [3.6 Backport] Add basic handshake defragmentation tests in ssl-opt

ChangeLog.d/tls-hs-defrag-in.txt, tests/scripts/analyze_outcomes.py, tests/ssl-opt.sh
Implements a portion of the testing needed for #9872. This pr extends #9928 and resolves #9887
=> Add basic handshake defragmentation tests in ssl-opt

library/ssl_msg.c, programs/ssl/ssl_test_lib.h, tests/scripts/analyze_outcomes.py
Defragment incoming TLS handshake messages incrementally, instead of all at the end. This makes the code simpler and a little more efficient.
Fixes [defragmentation of encrypted messages with an explicit IV](https://github.com/Mbed-TLS/mbedtls/pull/9872/files#r1967669302).
=> Incremental TLS handshake defragmentation

library/ssl_msg.c
This is the subset of https://github.com/Mbed-TLS/mbedtls/pull/9976 that's the most urgently needed.
- **tests**  not required because: deferred to #9976
=> Fix defrag interleave 3.6

ChangeLog.d/tls-hs-defrag-in.txt, include/mbedtls/ssl.h
Direct backport of https://github.com/Mbed-TLS/mbedtls/pull/10040 (with some trivial conflicts due to changes to the previous `\note`).
=> Backport 3.6: Document the limitations of TLS handshake message defragmentation

ChangeLog.d/tls-hs-defrag-in.txt, include/mbedtls/ssl.h, library/ssl_misc.h, library/ssl_msg.c, library/ssl_tls.c, library/ssl_tls12_server.c, programs/ssl/ssl_context_info.c, programs/ssl/ssl_test_lib.h, scripts/make_generated_files.bat, tests/.gitignore, tests/CMakeLists.txt, tests/Makefile, tests/scripts/check-generated-files.sh, tests/ssl-opt.sh
Merging the defragmentation feature branch back into mbedtls 3.6 branch
=> Merge defragmentation feature branch onto 3.6

ChangeLog.d/tls-hs-defrag-in.txt, include/mbedtls/ssl.h, library/ssl_misc.h, library/ssl_msg.c, library/ssl_tls.c, library/ssl_tls12_server.c, programs/ssl/ssl_test_lib.h, scripts/make_generated_files.bat, tests/.gitignore, tests/CMakeLists.txt, tests/Makefile, tests/scripts/check-generated-files.sh, tests/ssl-opt.sh
Merging the defragmentation feature branch back into mbedtls development branch
=> Merge defragmentation feature branch onto development

ChangeLog.d/fix-msvc-version-guard-format-zu.txt, include/mbedtls/debug.h, tests/suites/test_suite_debug.data, tests/suites/test_suite_debug.function
This PR fixes the preprocessor guards protecting the use of `%zu` in `MBEDTLS_PRINTF_SIZET`
It also adds a non-regression test to `test_suite_debug`.
Fixes #10017
Unblocks #9976
=> Fix preprocessor guards for C99 format size specifiers

include/mbedtls/net_sockets.h
Minor correction to API documentation for `mbedtls_net_send()`.
=> mbedtls_net_send API description typo fix

include/mbedtls/net_sockets.h
Trivial backport of https://github.com/Mbed-TLS/mbedtls/pull/9096
=> Backport 3.6: mbedtls_net_send API description typo fix

docs/3.0-migration-guide.md
Trivial backport of part of #10063
This PR only does the following:
* Fix some typos in the 3.0 migration guide
* Add a note in the migration guide about `MBEDTLS_PRIVATE()` (specifically that it may be used more safely in the 3.6 LTS)
It does not update the link to the PSA crypto driver examples, as this document is intact in mbedtls in the 3.6 branch.
- **tests**  not required because: Docs only
=> [Backport 3.6] Update the 3.0 migration guide

README.md, docs/3.0-migration-guide.md
Do the following things:
* Fix some typos in the 3.0 migration guide
* Add a note in the migration guide about `MBEDTLS_PRIVATE()` (specifically that it may be used more safely in the 3.6 LTS)
* Fix a broken link to PSA crypto driver examples in `README.md`
- **tests** not required because: Docs changes only
=> Update the 3.0 migration guide and fix broken README link

programs/ssl/ssl_client2.c, tests/ssl-opt.sh
=> [Backport 3.6]  Extend ssl-opt testing for TLS HS defragmentation 

programs/ssl/ssl_client2.c, tests/ssl-opt.sh
Continue the work on #9928 adding more specially designed tests in ssl-opt.sh. Currently it is focused on buffer resizing and renegotiation for TLS 1.2. The scope may be expanded. 
=> Extend ssl-opt testing for TLS HS defragmentation

include/mbedtls/ssl_cookie.h, include/mbedtls/ssl_ticket.h, library/ssl_cookie.c, library/ssl_ticket.c, programs/fuzz/fuzz_dtlsserver.c, programs/fuzz/fuzz_server.c, programs/ssl/dtls_server.c, programs/ssl/ssl_server2.c
Remove RNG parameters from public SSL APIs, resolves #9930 
- **tests** not required because: No updates.
=> Remove RNG parameters from public SSL APIs

ChangeLog.d/error-unification.txt, include/mbedtls/error.h, library/ssl_tls.c, library/ssl_tls13_generic.c, scripts/data_files/error.fmt
Never add a low-level error code to a high-level error code. Just use the low-level error code. Resolves https://github.com/Mbed-TLS/mbedtls/issues/9619, a step towards [having unified PSA and mbedtls error codes](https://github.com/Mbed-TLS/mbedtls/issues/8501).
=> Do not add error codes

CMakeLists.txt, scripts/make_generated_files.bat, tests/.gitignore, tests/CMakeLists.txt, tests/Makefile, tests/scripts/check-generated-files.sh, tests/src/certs.c
Adapt test_keys.h and test_cert.h generation to the changes done in https://github.com/Mbed-TLS/mbedtls-framework/pull/149 for the sake of https://github.com/Mbed-TLS/TF-PSA-Crypto/pull/201.
Fixes the component check_generated_files failing in the CI of https://github.com/Mbed-TLS/mbedtls-framework/pull/149 against 3.6.
- **tests**  not required because: only test internal changes.
=> [Backport 3.6] Adapt test_keys.h and test_cert.h generation

ChangeLog
Correctly credit Daniel Stenberg for reporting the problem with `mbedtls_ssl_set_hostname()`, which we had forgotten to do previously.
- **tests**  not required because: ChangeLog update only
=> [3.6] Add missing credit for `set_hostname` issue

.github/pull_request_template.md, BRANCHES.md
Update BRANCHES.md and the PR template.
- **tests**  not required because: doc only
=> The LTS branch 2.28 is now EOL

include/mbedtls/ssl.h, library/ssl_client.c, library/ssl_misc.h, library/ssl_msg.c, library/ssl_tls.c, library/ssl_tls12_server.c, library/ssl_tls13_server.c, programs/fuzz/fuzz_client.c, programs/fuzz/fuzz_dtlsclient.c, programs/fuzz/fuzz_dtlsserver.c, programs/fuzz/fuzz_server.c, programs/ssl/dtls_client.c, programs/ssl/dtls_server.c, programs/ssl/mini_client.c, programs/ssl/ssl_client1.c, programs/ssl/ssl_client2.c, programs/ssl/ssl_fork_server.c, programs/ssl/ssl_mail_client.c, programs/ssl/ssl_pthread_server.c, programs/ssl/ssl_server.c, programs/ssl/ssl_server2.c, programs/x509/cert_app.c, tests/src/test_helpers/ssl_helpers.c, tests/suites/test_suite_debug.function, tests/suites/test_suite_ssl.function
Remove mbedtls_ssl_conf_rng() resolves #9052 depends https://github.com/Mbed-TLS/mbedtls/pull/10039
- **tests**  not required because: No updates.
=> Remove mbedtls_ssl_conf_rng() 

tests/suites/test_suite_x509write.function
Remove MBEDTLS_PK_RSA_ALT resolves https://github.com/Mbed-TLS/TF-PSA-Crypto/issues/208 ~depends https://github.com/Mbed-TLS/TF-PSA-Crypto/pull/218~ (actually the other way round)
=> Pk rsa alt removal

ChangeLog.d/mbedtls_ssl_set_hostname.txt, ChangeLog.d/tls12-check-finished-calc.txt, include/mbedtls/ssl.h, library/ssl_misc.h, library/ssl_tls.c, programs/ssl/ssl_client2.c, programs/ssl/ssl_test_common_source.c, tests/src/test_helpers/ssl_helpers.c, tests/ssl-opt.sh
As part of the 2.28 and 3.6 releases, security fixes were merged to the public 3.6 and 2.28 branches. However, since there was no release from development at the same time, the same didn't happen for development. This PR fixes that.
=> Merge from restricted

.github/ISSUE_TEMPLATE/bug_report.md
People who report bugs might not think about security implications. Try reminding them.
- **tests**  not required because: doc only
=> Update bug report template for security issues

programs/psa/key_ladder_demo.sh, programs/psa/psa_hash_demo.sh
Recently https://github.com/Mbed-TLS/mbedtls-framework/pull/141 was merged in the framework and this requires updates in the demo programs launching scripts. This [was done](https://github.com/Mbed-TLS/TF-PSA-Crypto/pull/181/files) in `development`, but not on the 3.6 branch. This commit solves the problem.
=> [3.6] Fix demo programs' bash scripts

programs/psa/key_ladder_demo.sh, programs/psa/psa_hash_demo.sh
Resolves https://github.com/Mbed-TLS/mbedtls-framework/issues/157 for `mbedtls-3.6`
=> [3.6] Make demo_common.sh usable on its own

tests/src/test_helpers/ssl_helpers.c
Trivial backport of https://github.com/Mbed-TLS/mbedtls/pull/10120. Fix a minor issue in test code.
=> Backport 3.6: Fix uncaught failure conditions in test_suite_ssl

tests/src/test_helpers/ssl_helpers.c
We forgot to check the return value of `mbedtls_ssl_set_hostname()` in some new test code (found by Coverity). Also, fix `mbedtls_test_ssl_endpoint_init()` and a couple other functions returning 0 on some error conditions, which I happened to notice.
=> Fix uncaught failure conditions in test_suite_ssl

programs/Makefile, tests/scripts/components-platform.sh
Changes components in the CI that check the AES implementation so that they no longer use `selftest`, and instead use the new program introduced in https://github.com/Mbed-TLS/TF-PSA-Crypto/pull/199 (`which_aes`) to discover the AES implementation.
Note - due to the way `which_aes` was implemented, there is some difference in test coverage. Namely, with this new program we cannot grep the compiled file to check the result of conditional compilation (as much).
e.g. in the final test of `component_test_aesni`, the test checks the compiled `selftest` to ensure that there is no built-in/software AES implementation, however with `which_aes`, this is not possible (with the current implementation). `which_aes` _can_ check if `AESNI` code is present/absent, but not `AESCE` or software …
=> Switch all.sh components from selftest to which_aes

.pylintrc
Have Pylint complain about a likely missing comma in e.g.
```
mylist = [
"foo"
"bar",
"corge",
]
```
(Patch made because I spotted this in a review and I feel Pylint should have spotted it before me.)
=> Pylint: Complain about a missing comma in multiline lists of strings

programs/ssl/ssl_context_info.c
Implements changes described in #9977 
=> Removed use of mbedtls_cipher_info from ssl_context_info.c

.pylintrc
Backport of https://github.com/Mbed-TLS/mbedtls/pull/10146
=> Backport 3.6: Pylint: Complain about a missing comma in multiline lists of strings

include/mbedtls/x509_crl.h, include/mbedtls/x509_crt.h, include/mbedtls/x509_csr.h, library/ssl_tls12_client.c, library/ssl_tls13_generic.c, library/x509.c, library/x509_crl.c, library/x509_crt.c, library/x509_csr.c, library/x509_internal.h, tests/suites/test_suite_x509parse.data, tests/suites/test_suite_x509write.function
Resolves https://github.com/Mbed-TLS/mbedtls/issues/8154
- **tests**  TODO
=> [development] Restrict MBEDTLS_X509_RSASSA_PSS_SUPPORT

programs/test/dlopen.c, tests/scripts/components-compiler.sh
Resolves https://github.com/Mbed-TLS/mbedtls/issues/9884. Preliminaries for the bug fix to https://github.com/Mbed-TLS/mbedtls/issues/9814. Start testing with GCC 15, but using the workaround `-fzero-init-padding-bits=unions` until we actually fix the bug. Also some miscellaneous things I found useful in https://github.com/Mbed-TLS/mbedtls/pull/9955. Also update the crypto submodule (the framework is already at the tip of main).
Forward-ported from 3.6. Differences:
* Some parts are in crypto now.
* "Enable drivers when testing with GCC 15": Different way to build with all drivers.
=> Test with GCC 15

library/ssl_tls.c
To place in flash and save RAM on targets where this applies.
Save a few bytes of RAM.
- **tests** not required because: nothing new to cover
=> Mark ssl_tls12_preset_default_sig_algs const

library/ssl_tls.c
Backport of https://github.com/Mbed-TLS/mbedtls/pull/8947 to 3.6
cc @mpg
- **tests** not required because: nothing new to cover
=> Mark TLS 1.2 algo suite definitons const

tests/scripts/components-compiler.sh
Update the GCC 15 testing to have basic non-regression testing for https://github.com/Mbed-TLS/mbedtls/issues/9814 and https://github.com/Mbed-TLS/mbedtls/issues/9975. See https://github.com/Mbed-TLS/mbedtls/pull/10168 for more explanations.
Needs preceding PR: update crypto with https://github.com/Mbed-TLS/TF-PSA-Crypto/pull/295.
- **tests**  provided with GCC 15; more to follow in https://github.com/Mbed-TLS/mbedtls-framework/pull/168 and https://github.com/Mbed-TLS/mbedtls/pull/10178
=> Test with GCC 15 with sloppy union initialization

programs/ssl/ssl_server2.c
We no longer use decrypt TLS 1.2 (never did in 1.3) so we no longer need this path. Further simplifications could probably be made (we currently have an enum type with only one possible value...) but for now I'm trying to keep changes minimal.
This is to support https://github.com/Mbed-TLS/TF-PSA-Crypto/pull/297 which in turns paves the way for https://github.com/Mbed-TLS/TF-PSA-Crypto/issues/298
- **tests** not required because: removal
=> Remove call to pk_decrypt() in ssl_server2

tests/ssl-opt.sh
Prerequisite for https://github.com/Mbed-TLS/TF-PSA-Crypto/pull/294, contributes to https://github.com/Mbed-TLS/TF-PSA-Crypto/issues/281
`ssl-opt` checks for specific error code values in the output, namely `MBEDTLS_ERR_ECP_IN_PROGRESS` (`0x4B00`). With the patch https://github.com/Mbed-TLS/TF-PSA-Crypto/pull/294, this error is changing to an alias of `PSA_OPERATION_INCOMPLETE` (`-248`), which is a different error code.
Therefore change the test code to allow the resulting error code to be _either_ the old `mbedtls` error, or the new `PSA` error, so that we do not break the CI/have interdependent patches.
This patch will have to be merged before https://github.com/Mbed-TLS/TF-PSA-Crypto/pull/294 can be merged.
- **tests**  not required because: minor internal test change
=> Change hardcoded error values in ssl-opt to take in the PSA error alias

ChangeLog.d/move-crypto-struct-inclusion.txt, include/psa/crypto.h
Backport of https://github.com/Mbed-TLS/TF-PSA-Crypto/pull/260
- **tests** not required because: the change is validated by the current tests. We can't afford the effort required for non-regression testing right now. Covered by  https://github.com/Mbed-TLS/mbedtls/issues/1767.
=> [Backport 3.6] Move the inclusion of crypto_sizes.h and crypto_struct.h in crypto.h

tests/scripts/components-configuration.sh
With the removal of MBEDTLS_SHA3_C the test cases with disabled SHA3 dependency are never executed. Adding a temporary `all.sh` component which disabling the `PSA_WANT_ALG_SHA3_*` macros to cover these test cases.
Prerequisite for Mbed-TLS/TF-PSA-Crypto#266
=> Add temporary test component for SHA3 testing

include/mbedtls/bignum.h, include/mbedtls/dhm.h, include/mbedtls/ecdh.h, include/mbedtls/ecdsa.h, include/mbedtls/ecjpake.h, include/mbedtls/ecp.h, include/mbedtls/lms.h, include/mbedtls/pk.h, include/mbedtls/platform_util.h, include/mbedtls/rsa.h, include/mbedtls/ssl.h, include/mbedtls/ssl_cookie.h, include/mbedtls/ssl_ticket.h, include/mbedtls/x509_crt.h, include/mbedtls/x509_csr.h
Document the RNG callbacks passed to legacy crypto and functions that call legacy crypto. Resolves https://github.com/Mbed-TLS/mbedtls/issues/5868.
- **tests**  not required because: documentation only
=> 3.6 only: document f_rng callbacks

tests/suites/test_suite_psa_crypto.function, tests/suites/test_suite_psa_crypto_driver_wrappers.function
Improved testing for https://github.com/Mbed-TLS/mbedtls/issues/9814 and https://github.com/Mbed-TLS/mbedtls/issues/9975:
* In unit tests for PSA crypto API multipart operations, use a not-all-bits-zero initializer, simulating what happens with GCC 15. This validates the fix for https://github.com/Mbed-TLS/mbedtls/issues/9814.
* (framework) In test drivers, check that the context is zero on entry to setup. This validates the fix for https://github.com/Mbed-TLS/mbedtls/issues/9975, and also validates that the frontend is robust against https://github.com/Mbed-TLS/mbedtls/issues/9814.
Needs preceding PR:
=> Backport 3.6: Check union initialization portably

tests/scripts/components-configuration.sh, tests/scripts/depends.py
In `depends.py` use PSA macros for the `hashes` domain.
Resolve #9144 #10203
~Depends on #10145 #9292~ (merged)
=> Update the `hashes` domain to use PSA macros in `depends.py`

ChangeLog.d/unterminated-string-initialization.txt, library/common.h, library/ssl_tls13_keys.c, library/ssl_tls13_keys.h, tests/suites/test_suite_psa_crypto.function, tests/suites/test_suite_psa_crypto_slot_management.function, tests/suites/test_suite_ssl_decrypt.function
mbedtls-3.6 part of https://github.com/Mbed-TLS/mbedtls/issues/9944
Merge order (for 3.6):
Merge this PR
Once this PR + the `mbedtls` development (https://github.com/Mbed-TLS/mbedtls/pull/10216) and `TF-PSA-Crypto` (https://github.com/Mbed-TLS/TF-PSA-Crypto/pull/313) PRs have been merged, then merge the framework PR (https://github.com/Mbed-TLS/mbedtls-framework/pull/173)
This PR does not depend on the framework PR https://github.com/Mbed-TLS/mbedtls-framework/pull/173 in terms of submodule updates, but will require it to be merged to fix the issue completely. AIUI during the release process the framework pointer is updated, ~~so I haven't done it here on the assumption that it will be done later, but I can change this to ensure the framework change gets pulled in when this is merged.~~ …
=> [3.6] Fix GCC 15 warning 'Wunterminated-string-initialization'

configs/crypto-config-suite-b.h, configs/crypto-config-thread.h, scripts/generate_errors.pl
Resolves https://github.com/Mbed-TLS/mbedtls/issues/10172
- **tests**  not required because: cleanup (can manually check the effect of the changes to `generate_errors.pl` though).
=> Clean up after crypto hides its OID module

programs/pkey/gen_key.c, programs/pkey/pk_sign.c, programs/pkey/pk_verify.c, programs/pkey/rsa_sign_pss.c, programs/pkey/rsa_verify_pss.c, programs/test/CMakeLists.txt, programs/test/cmake_package/CMakeLists.txt, programs/test/cmake_package_install/CMakeLists.txt, programs/test/cmake_subproject/CMakeLists.txt, programs/util/CMakeLists.txt
Preparatory work for the resolution of #10022. The resolution itself will be in TF-PSA-Crypto. This PR is for the CI of the coming TF-PSA-Crypto PR to pass.
- **tests**  not required because: nothing new to test
=> Preparatory work for the resolution of #10022

library/Makefile
This is a prerequisite PR which helps in https://github.com/Mbed-TLS/TF-PSA-Crypto/pull/308.
This change was suggested [here](https://github.com/Mbed-TLS/TF-PSA-Crypto/pull/308#discussion_r2155320176).
- **tests**  not required because: no code change
=> library: Makefile: use wildcard to select sources for crypto library

library/ssl_msg.c, library/ssl_tls12_client.c, tests/ssl-opt.sh
Cherry-picked from commit [67aa959ea1](https://github.com/Mbed-TLS/mbedtls/commit/67aa959ea1)
- **tests** not required because there is no executable code change - just typo fixes in comments.
=> [BACKPORT] Fixed some minor typos in comments.

tests/scripts/components-compiler.sh
Now that the fixes for the GCC-15 warning `unterminated-string-initialization` are merged, we can remove the exception that stops this being an error due to `Werror`, so that it will become an error again.
Contributes to https://github.com/Mbed-TLS/mbedtls/issues/9944, from comment https://github.com/Mbed-TLS/mbedtls/issues/9944#issuecomment-2995252780
- **tests**  not required because: change to tests
=> [Dev] Turn Wunterminated-string-initialization back into an error

ChangeLog.d/mbedtls_ssl_conf_alpn_protocols.txt, include/mbedtls/ssl.h, library/ssl_client.c, library/ssl_tls.c, library/ssl_tls12_client.c, library/ssl_tls13_client.c, tests/include/test/ssl_helpers.h, tests/src/test_helpers/ssl_helpers.c, tests/suites/test_suite_ssl.function
Break down `mbedtls_test_ssl_perform_handshake()` and make `mbedtls_test_ssl_endpoint_init()` more consistent with it.
This is a preliminary for https://github.com/Mbed-TLS/mbedtls/issues/10160. I struggled a lot with the SSL helper code, and which function does what. In particular, I want to be able to customize what is passed to `mbedtls_ssl_conf_own_cert()`, and that was difficult when it was buried very deep down into the call stack.
There is a lot of further refactoring that should ideally be done, but are out of scope here, including:
* Better documentation for the existing functions.
* Break down `mbedtls_test_ssl_perform_connection()` further, to allow several test functions to start a handshake, do weird stuff, and finally let the common function finish the handshake, verifying …
=> Break down mbedtls_test_ssl_perform_handshake

scripts/generate_errors.pl
- Remove DES from `generate_errors.pl`
- Confirm successful build completion with DES removed
The goal is to fully remove DES support from the error infrastructure as part of the broader DES removal effort (see Mbed-TLS/mbedtls/issues/9164).  
- **tests**  not required because: no runtime behavior changed, only error string generation logic
- please structure your PR into a series …
=> Remove DES from error generation

programs/test/selftest.c, scripts/config.py, tests/compat.sh, tests/scripts/components-configuration-crypto.sh, tests/scripts/components-configuration-tls.sh
This PR removes remaining DES-related code and references from the Mbed TLS core that do not depend on TF-PSA-Crypto as part of the larger DES removal tracked in [#9164](https://github.com/Mbed-TLS/mbedtls/issues/9164).
Specifically:
- Removed DES self-test from `programs/test/selftest.c`
- Removed DES detection logic from `tests/compat.sh` (dead code)
- Removed `component_test_psa_crypto_config_accel_des` from `tests/scripts/components-configuration-crypto.sh`
- Removed DES comments from:
- `scripts/config.py`
- `tests/scripts/components-configuration-tls.sh`
This PR does not update changelogs or documentation files. Those will be addressed separately after the full DES removal is complete.
Generated build artifacts (under `build/`) were not modified or committed.
All tests pass locally. …
=> Remove DES from Mbed TLS core (except references blocked by TF PSA Crypto)

programs/test/dlopen.c
- Replace soon-deprecated mbedtls_md_list() in dlopen.c with psa_hash_compute()
- Add tfpsacrypto_dlopen.c as a PSA-only shared-library loading test
- Enable -fPIC for tf-psa-crypto builtins to support shared linking
- Confirm clean builds and successful dlopen() test execution.
- **tests** not required because this is itself a runtime test rather than an automated test suite.
- …
=> Modify dlopen.c and tfpsacrypto_dlopen.c so that they use PSA API-only dynamic loading

CMakeLists.txt, include/mbedtls/check_config.h, pkgconfig/mbedcrypto.pc.in, tests/scripts/analyze_outcomes.py, tests/scripts/components-configuration-crypto.sh, tests/scripts/depends.py, tests/ssl-opt.sh
Some changes to prepare for the removal of legacy crypto options. The changes should be enough to remove hash, cipher, cmac and aead configuration options in TF-PSA-Crypto with a green CI.
The first commit is a follow-up of https://github.com/Mbed-TLS/TF-PSA-Crypto/pull/332. I've put it here to reduce the number of PRs and CI runs.
- **tests**  not required because: only changing how some tests are done
=> Remove legacy crypto options preparation-1

scripts/ci.requirements.txt
Workaround for Mbed-TLS/mbedtls-test#214
The dependency on cryptography was declared without a version constraint due to us using Python 3.5 on the CI in certain places.
We no longer have a dependency on 3.5, so re-introduce the version constraint.
Cryptography is also causing us issues on the FreeBSD CI due to it needing a Rust toolchain.
Since it is unused on FreeBSD, disable it until we get a toolchain up and running.
=> Clean up ci.requirements.txt

tests/Makefile
A oneliner to fix the private access CI failure for the mbed-tls/tf-psa-crypto#318 PR
- **tests**  not required because: tested by the CI
=> Added a fix for the CI failure due to private access error

configs/crypto-config-ccm-psk-tls1_2.h, configs/crypto-config-suite-b.h, configs/crypto-config-thread.h, scripts/config.py, tests/scripts/analyze_outcomes.py
Just what it takes to make https://github.com/Mbed-TLS/TF-PSA-Crypto/pull/369 work. Contributes to https://github.com/Mbed-TLS/TF-PSA-Crypto/issues/307
First in a chain. See https://github.com/Mbed-TLS/TF-PSA-Crypto/pull/369 for the merge order.
=> Allow builds with no RNG but entropy in an NV seed: prepare Mbed TLS

include/mbedtls/oid.h, programs/test/CMakeLists.txt, scripts/data_files/query_config.fmt, scripts/generate_query_config.pl
This lets us remove or rename crypto headers without hassle, and means we don't risk forgetting to add a new header.
Fix #10323. Helps with https://github.com/Mbed-TLS/mbedtls/issues/9164, https://github.com/Mbed-TLS/mbedtls/issues/10087 and possibly other 1.0/4.0 tasks because it lets us fiddle with crypto headers without needing to prepare the mbedtls repository first.
Alternative to https://github.com/Mbed-TLS/mbedtls/pull/10325
- **tests**  provided; you can check that this doesn't change the output of `programs/test/query_compile_time_config -l`
=> query_config.fmt: glob headers instead of listing them explicitly

library/ssl_tls.c
Fixes #9320
Gatekeeper note: interdependent with Mbed-TLS/tf-psa-crypto#215 - handle with care!
=> Combine psa_pake_set_password_key() with psa_pake_setup()

README.md
Add more detail around how generation of configuration-independent files chooses a C compiler. Mention that setting `HOSTCC` or `CC` is recommended where there are multiple toolchains.
Mention that the fallback location is the cc executable, which may help users troubleshooting when the file generation picks up the wrong toolchain (as in Mbed-TLS/mbedtls#10360).
- **tests**  not required because: Documentation only
=> [Backport 3.6] Clarify use of `CC` and friends for file generation

tests/scripts/components-configuration-crypto.sh
One of the pr's required by https://github.com/Mbed-TLS/TF-PSA-Crypto/issues/328
It is meant to prepare the MbedTLS code to enable Mbed-TLS/TF-PSA-Crypto#396 to be merged.
- **tests**  provided | not required because: Covered by existing tests
=> crypto_config: Introduce MBEDTLS_PSA_CRYPTO_RNG_HASH (2/4)

programs/test/cmake_package_install/CMakeLists.txt
When building cmake_package_install, fail in case of warnings with GNU GCC. This would have caught the issue reported in #10022.
=> Improve detection of CMake library installation problems

programs/ssl/ssl_client2.c, programs/ssl/ssl_test_lib.h
Move private pk interfaces to mbedtls/private/pk.h. Contributes to https://github.com/Mbed-TLS/TF-PSA-Crypto/issues/344
This PR is part of a chain which needs to be merged in the following order:
1.  https://github.com/Mbed-TLS/mbedtls/pull/10351
2. https://github.com/Mbed-TLS/TF-PSA-Crypto/pull/413
- **tests**  not required because: No changes
=> Move private pk interfaces to mbedtls/private/pk.h

tests/suites/test_suite_platform_threading.data, tests/suites/test_suite_platform_threading.function
Backport the new tests from https://github.com/Mbed-TLS/TF-PSA-Crypto/pull/434
=> Smoke tests for threading

programs/Makefile, programs/test/CMakeLists.txt
Prerequisite for https://github.com/Mbed-TLS/mbedtls-framework/pull/205 and https://github.com/Mbed-TLS/TF-PSA-Crypto/pull/439.
* Allow metatest.c to use crypto internal headers
=> mbedtls prerequisite: Return int from platform mutex_init

include/mbedtls/build_info.h, include/mbedtls/mbedtls_config.h
Since we're making incompatible changes to the configuration, we really should advance the configuration version.
=> Increment config version for the new product major version

include/mbedtls/mbedtls_config.h
Checking through the history in https://github.com/Mbed-TLS/mbedtls/pull/4589, this seems to have been what we intended from the start. But we couldn't do it yet because the library version was still 2.x while the config version was already 3.0, so we temporarily commented out the definition in 1cafe5ce20c54e68a4de0f85bd4bc844e3798198. But then we forgot to uncomment it during the release since it wasn't part of any process.
Thinking about it independently of the history, I think it makes more sense to have it uncommented by default. That way, if someone copies the config from a given version and then keeps it around, they'll get the compatibility mode for that version.
=> Have the definition of MBEDTLS_CONFIG_VERSION uncommented by default

library/.gitignore, library/CMakeLists.txt, library/Makefile, scripts/generate_config_checks.py
Introduce `generate_config_checks.py` and instructions to use it in the build scripts. Do not yet consume the generated files, to keep the same pace as crypto.
Contributes to https://github.com/Mbed-TLS/mbedtls/issues/10147. See https://github.com/Mbed-TLS/mbedtls/pull/10306 for what this will look like when consumed by the library.
Needs preceding PR: https://github.com/Mbed-TLS/mbedtls-framework/pull/196, https://github.com/Mbed-TLS/TF-PSA-Crypto/pull/404
=> Introduce generated config checks in mbedtls

README.md, docs/architecture/psa-crypto-implementation-structure.md, docs/proposed/psa-driver-interface.md, library/psa_crypto.c
The PSA implementation has not been experimental for a long while (before 2.28), but we forgot to update the readme.
Don't prominently label it a "reference" implementation. That implies that it's a complete implementation, but it isn't: we do not intend to implement every mechanism that the PSA specification has an encoding for. That also tends to imply that it's for demonstration purposes and not ready for production, but Mbed TLS is intended to be used in production.
=> Backport 3.6: Update README about PSA

include/mbedtls/build_info.h, library/CMakeLists.txt, library/Makefile, library/mbedtls_config.c, scripts/generate_config_checks.py, tests/scripts/test_config_checks.py
Set up a mechanism for erroring out if users try to use removed options in their configuration file. Resolves https://github.com/Mbed-TLS/mbedtls/issues/10147.
Specification in https://github.com/Mbed-TLS/mbedtls-framework/pull/184.
Status: ready.
Needed preceding PR: framework https://github.com/Mbed-TLS/mbedtls-framework/pull/164
=> Mechanism to error out on removed configuration options

scripts/abi_check.py
This fixes our ABI checking in PR-merge jobs.
For parametrihzed jobs, this PR when used in conjuction with https://github.com/Mbed-TLS/mbedtls-test/pull/220 fixes the issue.
Conceptually, this is a port of https://github.com/Mbed-TLS/mbedtls-test/commit/62d05693659a18ad5a1c50e2b94502185c6c7e82 to `abi_check.py`
- **tests** not required
=> Use submodule work trees during ABI check
